### ISSUE TITLE
Clarification on internal ingress

### ISSUE THREAD

**Issue by karoldeland** [microsoft/azure-container-apps#1]
Hi, would it be possible to explain what ingress options existing? 

A question I have is : Is it possible to call an app from a private vnet without going through the internet and public endpoint?

**Comment by ahmelsayed** [comment]
Hi @karoldeland, this doc describes the options that exist today on ingress https://docs.microsoft.com/en-us/azure/container-apps/ingress?tabs=bash 

using `az` cli you can do `--ingress 'external'` or `--ingress 'internal'`. In ARM you can set 

```json
"configuration": {
  "ingress": {
    "external": true | false
  }
}
```

If you create the app with `external: true` (or `--ingress 'external'`) then your app will get an FQDN that looks like 

```bash
{APP_NAME}.{UNIQUE_IDENTIFIER}.{REGION_NAME}.azurecontainerapps.io

# or 

# CONTAINER_APP_ENV_DNS_SUFFIX is an env var that resolves the dnsSuffix
{APP_NAME}.$CONTAINER_APP_ENV_DNS_SUFFIX 
```

If you set `external: false` (or `--ingress 'internal'`) then your app url will be 

```bash
{APP_NAME}.internal.{UNIQUE_IDENTIFIER}.{REGION_NAME}.azurecontainerapps.io

# or 

{APP_NAME}.internal.$CONTAINER_APP_ENV_DNS_SUFFIX 
```

the `*.internal.*` are only resolvable/accessible inside the container app environment. So if you set ingress for an app as internal, then it'll only have the internal endpoint. Other apps running on the same container app env. 

Does this answer your question?

**Comment by ahmelsayed** [comment]
Omit `--target-port` if you don't want ingress. If you set a `target-port` then the cli assumes ingress, and that must have a type.

**Comment by dariagrigoriu** [comment]
Hi @karoldeland, please close if the question is addressed with @ahmelsayed's clarification.

**Comment by dariagrigoriu** [comment]
Please revisit if not addressed, closing for now following 7 days of inactivity.

**Comment by torumakabe** [comment]
test
