### ISSUE TITLE
Feature Request: Allow Secrets to use Managed Identities not linked to Service for app code usage

### ISSUE THREAD

**Issue by mvrius** [microsoft/azure-container-apps#1007]
**Is your feature request related to a problem? Please describe**.  

Azure Container Apps supports Managed Identities for various use cases, each with distinct security implications. 

Managed Identities Usage:

A) Configure ACR Pulls https://learn.microsoft.com/en-us/azure/container-apps/managed-identity-image-pull?tabs=azure-cli&pivots=azure-portal
B) Configure Secrets from KeyVault https://learn.microsoft.com/en-us/azure/container-apps/manage-secrets?tabs=azure-portal#reference-secret-from-key-vault
C) Connect with MI in Code
https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=portal%2Cdotnet#connect-to-azure-services-in-app-code 

When Managed Identities are used for scenarios (A) and (B), they often involve highly sensitive information.

In my specific setup, we use Managed Identities (C) to access Cosmos DB, if a hacker gets access to the service, it will have a blast radius contained to whatever the service is accessing.

If I start using MI for (A) and (B) automatically I increase the blast radius of any potential hack to data available on our private ACR as well as entire KV secrets.|

**Describe the solution you'd like**.    
I would like to be able to specify in Secrets, MIs which are not assigned to the service. 
The MI should be used only during service startup internal to Azure Infrastructure and not made available in application code via REST.

**Describe alternatives you've considered**.   
The workaround is to not use MI for ACR or KeyVault references, and use Secrets with Values instead. 

Would be best to use references which can stay evergreen.

Thanks,
Marius

**Comment by vinisoto** [comment]
Hi @mvrius - A single resource (in this case a container app) having multiple managed identities assigned at the same time is not supported (not only for container apps but, also for any other Azure resource that supports Managed Identity).

If malicious code gets executed inside your container it will anyway have access to the Secrets (which are hydrated as environment variables). Let me know if I didn't quite get your point

**Comment by vturecek** [comment]
@mvrius yes this makes sense, and you are correct today you can get a token for all managed identities that you assign to a Container App using the HTTP endpoint within your application, even if you only intend to use the identity to pull an image from ACR or auto-populate a secret from KeyVault. We would need to have a way to allow a managed identity to "opt out" of use from within a Container App. This is something we can look into.

**Comment by mvrius** [comment]
Thanks @vturecek! 

Exactly, an opt-out mechanism would be great so only app-intended user MI are exposed to the app. Appreciate your response!

**Comment by vturecek** [comment]
@mvrius quick update on this, here is the proposed API change that will allow you to choose the application lifecycle stages where your application code can get a managed identity token: https://github.com/Azure/azure-rest-api-specs/pull/28117

For your scenario, you would choose "None" for identities that you're using for ACR pull or KeyVault secrets.

**Comment by vturecek** [comment]
This is now available in API version 2024-02-02-preview: https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=portal%2Cdotnet#control-managed-identity-availability

Please let us know if you have any feedback.
