### ISSUE TITLE
Ingress IP Restriction not respected for TCP port 22

### ISSUE THREAD

**Issue by woutervanranst** [microsoft/azure-container-apps#1010]
### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Ingress IP Restriction not working for TCP port 22

### Steps to reproduce
1. Deploy an ACE with dedicated network to allow ingress IP restrictions.
2. Deploy ACA `app1` (an SFTP eg `atmoz/sftp`) and configure ingress restrict ips, TCP port 22, setting 'Allow traffic from IPs configured below, deny all other'
3. Deploy another ACA `app2` (eg the quickstart one) and configure the same, but from HTTP port 80

**Expected behavior**
On app1 I cannot connect
On app2 I cannot connect

**Actual behavior**
On app1 I *can* connect
On app2 I cannot connect (I was able to connect before applying the restriction, demonstrating that it had effect)

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/6490925/9a617b9b-e363-46ac-a8ae-b9854b3c3d3e)

![image](https://github.com/microsoft/azure-container-apps/assets/6490925/db69c2da-7dca-4761-9980-762d1e4a8778)

SFTP connection successful
![image](https://github.com/microsoft/azure-container-apps/assets/6490925/dbe5ab44-6d85-4062-8051-71c34f02c68c)

Web Traffic effectively blocked
![image](https://github.com/microsoft/azure-container-apps/assets/6490925/45cf2da9-daec-4313-8aab-c0093004662a)

### Additional context
Occurs through the Portal

**Comment by zhenqxuMSFT** [comment]
@woutervanranst We identified a bug which may delay IP restrictions to take effect for TCP apps (but finally it will take effect).

We will fix the bug in next release.

**Comment by ilmax** [comment]
Same exact issue here, @zhenqxuMSFT do you have an ETA for the next release?

**Comment by ilmax** [comment]
@zhenqxuMSFT ~6 month ping, any news here?

**Comment by vanakool1001** [comment]
> @woutervanranst We identified a bug which may delay IP restrictions to take effect for TCP apps (but finally it will take effect).
> 
> We will fix the bug in next release.

Could you please specify how long this delay is (at least approximately). This would really help me right now. Thanks!

**Comment by zhenqxuMSFT** [comment]
This issue is already fixed. If you are still having issues, please create a new issue.
