### ISSUE TITLE
Azure Container App with custom Vnet deployment fails - load balancer resource group degraded

### ISSUE THREAD

**Issue by sherlynnw-fac** [microsoft/azure-container-apps#1013]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Azure Container App with custom Vnet deployment fails. Looking into the Activity Logs within the `MC_..` resource group, a "health event" referring to load balancer degraded happens. This remains degraded until deployment times out and fails.

### Steps to reproduce
1. set up subnet with /23
2. deploy container app

**Expected behavior** [What you expected to happen.]
in my dev subscription, load balancer degradation resolves itself after a while, container app can then be deployed
<img width="606" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/99327563/1acf6a16-7fd1-4653-a3a9-4597e3273450">

**Actual behavior** [What actually happened.]
however, in my prod subscription, load balancer remains degraded, container app remains stuck in deployment/timeout happens.

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
Deployment done via terraform.

**Comment by cachai2** [comment]
Hi @sherlynnw-fac, can you try this with the Consumption plan in a workload profiles environment? If you are still running into issues, please open a support ticket, and we'll investigate.
