### ISSUE TITLE
Container app job fails for a simple command echo TEST

### ISSUE THREAD

**Issue by blackalegator** [microsoft/azure-container-apps#1016]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When trying to run a manual app container job with a command override "echo TEST EXEC" running takes forever, then the job fails. In the logs this is displayed
```
ParsedLog_msg
Getting latest ServiceRedirectInfos. Id:k8se-apps_myproj-acaj-test-dev-nuus741-gffvl
Start syncing all iptables rules
Generating chains and rules for k8se-apps/cappscanary-yellowdesert-6b7fa01c--main, total mappings: 1
Generating chains and rules for k8se-apps/myproj-aca-hubclient-dev, total mappings: 1
Generating chains and rules for k8se-apps/myproj-aca-hubapi-dev--0l29z5i, total mappings: 1
Generating chains and rules for k8se-apps/myproj-aca-hubclient-dev--d8n7mgw, total mappings: 1
Generating chains and rules for k8se-apps/cappscanary-yellowdesert-6b7fa01c, total mappings: 1
Generating chains and rules for k8se-apps/myproj-aca-hubapi-dev, total mappings: 1
Generating chains and rules for k8se-apps/myproj-aca-hubdebug-dev, total mappings: 1
Generating chains and rules for k8se-apps/myproj-aca-hubdebug-dev--0bf7eqq, total mappings: 1
Loading into iptables.
Successfully synced all iptables rules
measured: sync iptables rules
Initialized
Start listening services redirect info updates
Starting Job Envoy Sidecar
[source/server/server.cc:682] No admin address given, so no admin HTTP server started.
[source/server/server.cc:794] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
[source/server/server.cc:854] caught ENVOY_SIGTERM
Terminated
Failed to receive from stream.
Getting latest ServiceRedirectInfos. Id:k8se-apps_myproj-acaj-test-dev-nuus741-gffvl
Failed to call GetServiceRedirectInfos","error":"rpc error: code = Canceled desc = context canceled","stacktrace":"main.run\n\t/__w/k4apps/k4apps/cmd/proxy/main.go:139\nmain.main\n\t/__w/k4apps/k4apps/cmd/proxy/main.go:103\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```
Getting latest ServiceRedirectInfos. Id:k8se-apps_myproj-acaj-test-dev-nuus741-gffvl
Failed to call GetServiceRedirectInfos
are repeated about 500 times

### Steps to reproduce
1. Create a container app job using az cli
`az containerapp job create --name myproj-acaj-test-dev -g myproj-rg-dev --container-name ubuntu --trigger-type Manual --image ubuntu:latest --command "echo TEST EXEC" --environment myproj-acaenv-dev --replica-timeout 180 --replica-retry-limit 0 --parallelism 1 --replica-completion-count 1`
2. Go to Azure WEB, Press "Run Now"
3. Go to logs, query `ContainerAppConsoleLogs_CL | where ContainerGroupName_s startswith 'job-name'`
(or go to  [Execution History] -> [Logs (Console)] )

**Expected behavior** [What you expected to happen.]
1. Success in execution history
2. TEST EXEC displayed in console logs (in Web Logs)

**Actual behavior** [What actually happened.]
1. Job runs for a long time, then fails (Status Failed is shown)
2. In Logs the previous errors are shown

Might be related to #988

**Comment by anthonychu** [comment]
@KryptoKnight @CallumHoughton Looks like in both instances, the container failed to start. When this happens, you should not see any console logs because your container never started successfully. Currently, there's an issue where some platform-level logs are appearing in the console logs table, which is what's causing some of the confusion here. Work is underway to fix this.

You should, however, see the problem in the system logs table. @CallumHoughton I think you've found that you job has a problem with the image pull. @KryptoKnight, I think the issue might be your command. Try `--command echo "TEST EXEC"` instead.

**Comment by CallumHoughton** [comment]
> @KryptoKnight @CallumHoughton Looks like in both instances, the container failed to start. When this happens, you should not see any console logs because your container never started successfully. Currently, there's an issue where some platform-level logs are appearing in the console logs table, which is what's causing some of the confusion here. Work is underway to fix this.
> 
> You should, however, see the problem in the system logs table. @CallumHoughton I think you've found that you job has a problem with the image pull. @KryptoKnight, I think the issue might be your command. Try `--command echo "TEST EXEC"` instead.

Okay thank you, I can see in the system logs that there's a couple of failures related to image pulling and container starting, I'm not entirely sure why this is the case as the container runs locally? The errors in the system logs are below.

![image](https://github.com/microsoft/azure-container-apps/assets/40490686/8555ed6a-d8cd-41bd-9f4f-26d7f943c295)


 Should I seek help / report this somewhere else outside of the GitHub issues? I contacted Azure Support but they seemed to just point me to here

**Comment by blackalegator** [comment]
@anthonychu Thank you for your reply. Changing the command helped, fixing logs should mitigate such confusion in the future. I think the issue could be closed unless the logs issue should be solved first
