### ISSUE TITLE
Container App Jobs | querying logs from Log Analytics workspace not consistent

### ISSUE THREAD

**Issue by CaishenNefri** [microsoft/azure-container-apps#1018]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Resources:
- Container App Job
- Log Analytics workspace

I've Container App Job ran. I am trying to see logs or any information from Log Analytics workspace but I am getting error 
`'project' operator: Failed to resolve scalar expression named 'EnvironmentName_s' Request id: 103ad085-1ff6-434d-be93-15a04113c0cf`
You can see at the gifs that the same query sometimes works and sometimes not. It was run in couple minutes time span. 

Simple query:
```
ContainerAppConsoleLogs_CL
| project EnvironmentName_s

```
### Steps to reproduce
1. Create Log Analytics workspace
2. Create Container App Environment
3. Create Container App Job
4. Run Job
5. Try to query logs: `ContainerAppConsoleLogs_CL | project EnvironmentName_s`
6. Sometimes works, sometimes not

**Expected behavior** [What you expected to happen.]
Always I should get proper log output.

**Actual behavior** [What actually happened.]
I am getting error `'project' operator: Failed to resolve scalar expression named 'EnvironmentName_s'
Request id: 1155a2fd-1324-4be3-b921-37c3f4aa154d` but sometis the same query is working.

**Screenshots**         
![chrome_zPZyMJZPqD](https://github.com/microsoft/azure-container-apps/assets/24476768/fecd885e-4b73-43a8-81d1-91ffe43e3d9e)

![1rHnRZYIBc](https://github.com/microsoft/azure-container-apps/assets/24476768/b45c3fb4-5d2b-43bf-9e52-8a18ffe0f2f3)

### Additional context
Same issue like #700 but it was closed not resolved.

**Comment by p-bouchon** [comment]
Based on your usage shown in the gifs, it looks like you are highlighting certain sections of the query which runs just that portion of the query. We can reproduce the error seen by highlighting just `EnvironmentName_s`, which attempts to run just that term as the query. Make sure the entire query is highlighted to run that complete query
![image](https://github.com/microsoft/azure-container-apps/assets/107427816/93c7a30e-1d29-4fe1-a238-b860880e0c8a)

**Comment by CaishenNefri** [comment]
Hello @p-bouchon 
Can you see a difference what I am getting from the same query? 
It is not consistent. It seems that for one query it has access to data but for other one it is limited. 

![image](https://github.com/microsoft/azure-container-apps/assets/24476768/3566cb11-fbf1-4cb8-9543-2d3667390a17)

![image](https://github.com/microsoft/azure-container-apps/assets/24476768/1f46454d-441e-444a-ba5d-d89bc80bffd1)

**Comment by CaishenNefri** [comment]
Thanks. I will let you know in the next week as I am  on my holidays.

**Comment by CaishenNefri** [comment]
Weird but I can't also reproduce this error. I was trying to recreate whole RG with Log Analytics workspace and Container Apps Environment. 
Whenever I will get similar error I will refer to this issue.
