### ISSUE TITLE
Feature Request: Ability to cancel a Container App Job

### ISSUE THREAD

**Issue by rhuanbarreto** [microsoft/azure-container-apps#1023]
**Is your feature request related to a problem? Please describe**.  
Today a job run cannot be cancelled manually.
Sometimes, there are some errors that keeps the job running until timeout, like if the job couldn't pull the container image.
This incur costs in case something is wrong.

**Describe the solution you'd like**.    
I want to be able to cancel a job execution, either through the REST API, CLI or portal.

**Describe alternatives you've considered**.   
There are no alternatives today.

**Comment by anthonychu** [comment]
This is available in the REST API: https://learn.microsoft.com/en-us/rest/api/containerapps/jobs/stop-execution?view=rest-containerapps-2023-05-01&tabs=HTTP

You can also use the [`az containerapp job stop`](https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest#az-containerapp-job-stop) command in the CLI.

We have a plan to add it to the portal but no ETA at this time.

**Comment by ltutar** [comment]
I also would like to have this feature since I do not need to configure my local environment to be able to run az cli or rest api calls.

**Comment by christywastaken** [comment]
This would be a great QOL feature!

**Comment by kapslock123** [comment]
Adding it to the portal makes it so much more convenient. I also like the feature with separate log stream access for each replica in container apps. Wish we had the same for container app jobs
