### ISSUE TITLE
az containerapp exec --comand "<multiple arguments>"

### ISSUE THREAD

**Issue by arnoldknott** [microsoft/azure-container-apps#1029]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

Having options to the command in `az container app exec` results in error

### Steps to reproduce
1. az containerapp exec -g <resource_group> -stage -n <container_name> --command "ls -la"

**Expected behavior** [What you expected to happen.]

executes the command with the options - like in terms of `ls -la` shows all  contents of current directory in list view

**Actual behavior** [What actually happened.]

Crashes:

```
INFO: Connecting to the container 'backend'...
Use ctrl + D to exit.
INFO: Successfully connected to container: 'backend'. [ Revision: '<revision_name>', Replica: '<replica_name>']
ERROR: {"Error":{"Code":"ClusterExecFailure","Message":"Cluster exec API returns error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec <...>\u0022: OCI runtime exec failed: exec failed: unable to start container process: exec: \u0022ls -la\u0022: executable file not found in $PATH: unknown, code: 500.","Details":null,"Target":null,"AdditionalInfo":null}}
Disconnecting...
```

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

Seems similar like #628

**Comment by Greedygre** [comment]
Hi @arnoldknott 
Did your image used in this containerapp support shell?
Did this issue occur in the Portal?

Thanks!

**Comment by arnoldknott** [comment]
@Greedygre ,

I have tried with various images. And yes, as long as I only pass one argument, e.g. `/bin/sh` it works fine. As soon as I am inside the container with for example `/bin/sh`, I can execute anything, like `ls -la` successfully.

No, I have not tried in portal. I have used the `az containerapp exec` on my local machine and in a GitHub actions workflow. Same result, no matter which host I executed the command in.

Does that make sense? 🤔
Can you reproduce the issue?

**Comment by Greedygre** [comment]
@arnoldknott 

I cannot reproduce the issue with error 'OCI runtime exec failed: exec failed: unable to start container process: exec: "invalid-command": executable file not found in $PATH: unknown'  when the contatinerapp created in a dedicated workload profile.

May I ask what kind of environment the containerapp in? 
Is your containerapp created in a dedicated workload profile?

Thanks!

**Comment by howang-ms** [comment]
@arnoldknott
We have identified this is a bug for the command with parameters, we will fix this in the next release. 
Thank you for reporting this.

**Comment by arnoldknott** [comment]
> @arnoldknott We have identified this is a bug for the command with parameters, we will fix this in the next release. Thank you for reporting this.

@howang-ms  thank you so much for investigating and looking forward to the fix! 🙏

**Comment by LianaAdaza** [comment]
Issue has been fixed. Thank you for your patience

CC: @howang-ms
