### ISSUE TITLE
Any plans for local development story

### ISSUE THREAD

**Issue by ThorstenHans** [microsoft/azure-container-apps#103]
Are there any thoughts regarding inner-loop (local development) support? 

Although all containers can easily be hosted in a local Kubernetes environment, it would be awesome to have a first-class local development story. 

When thinking about the scenario, I could imagine there are different solutions/ideas like for example

- Compiling Azure Container Apps ARM entities (either from Bicep or plain ARM templates) to Kubernetes manifests to run the app with no change in a k8s environment like KIND or minikube -> that could also become the "eject" functionality  to take existing applications from Azure Container Apps and move it seamlessly to AKS if required
  - This would imply all dependencies being available as helm charts 
- Another option would be providing a collection of helm charts to take Azure Container Apps and run it in any Kubernetes
  - Adding a custom CRD that is able to deal with the schema we use to describe Container Apps `Microsoft.Web/containerApps@2021-03-01`  and `Microsoft.Web/kubeEnvironments@2021-02-01`

**Comment by kendallroden** [comment]
We are working on ways to optimize the developer experience. Thanks for the suggestions

**Comment by onionhammer** [comment]
Making Tye a first-class supported (i.e. not an experimental) CLI tool would basically meet this need, I think.. anything other than this would be duplicate effort.

**Comment by johnnyreilly** [comment]
I've found that doing docker-in-docker with VS Code gives a pretty nice local development experience.

You can borrow the example code from here:

https://github.com/johnnyreilly/dapr-devcontainer-debug-and-deploy/releases

It has:
- deployment to Azure Container Apps
- a devcontainer 
- running locally with docker compose
- debugging locally in VS Code

**Comment by simonjj** [comment]
We're tracking this at #256. Closing this now.
