### ISSUE TITLE
Propagate custom user assigned tags to every resource created/managed by ACA environment

### ISSUE THREAD

**Issue by goldmark** [microsoft/azure-container-apps#1030]
### This issue is a: (mark with an x)

- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

Custom user assigned tags set during ACA environment provisioning are not propageted to all the resources in the managed (MC_) resource group.
We have a policy in place that blocks creation of resources not tagged with mandatory tags.

### Steps to reproduce

Reproducible using the following az cli example:

```
export SUBSCRIPTION_ID=""
export LOGS_WORKSPACE_ID=""
export RESOURCE_GROUP="my-rg"
export NETWORK_NAME="my-vnet"
export SUBNET_NAME="aca-subnet"
export ENVIRONMENT_NAME="my-aca-environment"
export LOCATION="centralus"

az group create \
  --name $RESOURCE_GROUP \
  --location $LOCATION \
  --query "properties.provisioningState"

az containerapp env create \
  --name $ENVIRONMENT_NAME \
  --resource-group $RESOURCE_GROUP \
  --location "$LOCATION" \
  --infrastructure-subnet-resource-id "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Network/virtualNetworks/$NETWORK_NAME/subnets/$SUBNET_NAME" \
  --logs-workspace-id "$LOGS_WORKSPACE_ID" \
  --tags 'tag1=value1' 'tag2=value2' \
  --query "properties.provisioningState"
```

**Expected behavior** [What you expected to happen.]
All resources in the managed (MC_) resource group inherit tags from ACA environment

**Actual behavior** [What actually happened.]
1 out of 2 Public IP address resources, the one mapped to the frontend IP configuration of the LB, in the managed (MC_) resource group is not inheriting tags from the ACA environment.

### Additional context
This was reproduced using cli and terraform.

**Comment by chinadragon0515** [comment]
I will fix this.

**Comment by Seris370** [comment]
Fix is ready. Waiting for rollout.

**Comment by chinadragon0515** [comment]
The fix has been deployed
