### ISSUE TITLE
RestartPolicy Never does not seem to work

### ISSUE THREAD

**Issue by groogiam** [microsoft/azure-container-apps#1034]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
It seems like the Restart Policy never does not work, unless I am just not understanding the semantics. If I launch a container that fails to start e.g. due to an invalid command the retry policy is ignored. The container seems like it will infinitely try to start and fail. This is especially troublesome when we have calling code waiting for the container request to complete as it will hang indefinitely.

### Steps to reproduce
1. Create container instance with nginx
2. Set the retry policy to never
3. Set the command to something invalid. E.g. [ "doesNotExist" ]

**Expected behavior** [What you expected to happen.]

The container should attempt to start once then terminate. 

**Actual behavior** [What actually happened.]

Container continually restarts.

**Screenshots**         

![image](https://github.com/microsoft/azure-container-apps/assets/1992395/957c20c9-2aca-4d5a-b2fb-0ca69b7e73b5)

![image](https://github.com/microsoft/azure-container-apps/assets/1992395/c9474b9d-72b9-48d3-9e76-a29072c34b02)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

This occurs in the portal and when running via the Azure.ResourceManager.ContainerInstance NuGet package using .NET.

**Comment by howang-ms** [comment]
Is it Azure Container App or Azure Container Instance?

**Comment by groogiam** [comment]
It's container instance. Sorry about that.
