### ISSUE TITLE
Fetching IngressFqdn fails with Az.App module version 1.0.0 using Get-AzContainerApp cmdlet

### ISSUE THREAD

**Issue by debasishdaswk** [microsoft/azure-container-apps#1035]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ x] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)

### Issue description
latest versionof Az.App version 1.0.0 has breaking change which results failing following cmdlet.

(Get-AzContainerApp -Name <containerapps_name> -ResourceGroupName <resourceGroupName>).IngressFqdn

according to documentation it must work on amy version of powershell module.
https://learn.microsoft.com/en-us/azure/container-apps/connect-apps?tabs=powershell

### Steps to reproduce
1. install latest Az.App module
2. Run (Get-AzContainerApp -Name <containerapps_name> -ResourceGroupName <resourceGroupName>).IngressFqdn

**Expected behavior** [What you expected to happen.]
As an output of the cndlet I am expecting Fqdn assigned to the container app.
**Actual behavior** [What actually happened.]
returns null
**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by Juliehzl** [comment]
The powershell cmdlet in document is not correct. please use `(Get-AzContainerApp -Name <containerapps_name> -ResourceGroupName ).Configuration.IngressFqdn`

**Comment by debasishdaswk** [comment]
@Juliehzl Thanks for your response. That worked for me.

Thank you
