### ISSUE TITLE
VSCode Extension for Azure Container Apps

### ISSUE THREAD

**Issue by ThorstenHans** [microsoft/azure-container-apps#104]
Is there any kind of integration with VSCode on the roadmap? Seamless provisioning and deployment are top of my mind. Administrating existing revisions, configuring traffic split and other aspects of the service itself would be really nice additions

**Comment by torosent** [comment]
We are working on the extension, and it will be released in the coming weeks.

**Comment by ThorstenHans** [comment]
is it developed in the open? Open for contributions?

**Comment by anthonychu** [comment]
The first release of the VS Code extension is now available! 🎉 https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurecontainerapps

Please file issues at https://github.com/microsoft/vscode-azurecontainerapps/issues
