### ISSUE TITLE
Container App Job unexpectedly killed during execution

### ISSUE THREAD

**Issue by avneeshkumar** [microsoft/azure-container-apps#1047]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
My Container app jobs are being preemptively killed by Container App jobs without any logs on why its getting killed.

I have tested this on local system and the CPU and RAM percentage seems under the allocated 1GB in Container App jobs...

<img width="1289" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/3087417/94acaa1e-e080-439b-a315-db3301ec1374">

**Expected behavior** [What you expected to happen.]
Container app jobs shouldn't kill the job and let it complete.

**Actual behavior** [What actually happened.]
Its getting killed as shown in screenshot.

**Screenshots**         
<img width="1245" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/3087417/ee969f82-60bc-4b48-8120-afc812cbd382">
<img width="1209" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/3087417/64e6c128-7354-4b15-98d6-234466e14dd8">

### Additional context
This Container app job writes a file to disc(can be big file like 100MB as shown in Docker stats screenshot) to tmp folder and then uploads it to storage blob once all the writes are complete...

```
avneeshkumar@Avneeshs-MacBook-Pro microcosmos % docker ps --size
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS         PORTS     NAMES             SIZE
7da99e35699e   395336880036   "./entrypoint.sh --m…"   7 minutes ago   Up 7 minutes             musing_elbakyan   5.2MB (virtual 315MB)
```

There was on related issue https://github.com/microsoft/azure-container-apps/issues/922 but seems they were utilizing more ram which is not our case. 

Subscritption ID 
`/subscriptions/84c14183-d3d2-45a2-9c2c-dd4f3998d2aa/resourceGroups/rg-mm-apps-debug/providers/Microsoft.App/jobs/caj-csv-downloads-debug`

**Comment by vinisoto** [comment]
hi @avneeshkumar - we will use the details that you provided (subscription id and job name) to look at our internal logs and investigate.

Can you please send us an email to `acasupport at microsoft dot com` se we can follow up with you?

**Comment by vinisoto** [comment]
closing this issue here as we are following up through the internal support channels

**Comment by itallackpure** [comment]
Are you able to share the resolution of this?
