### ISSUE TITLE
Issues running GitHub runner containers in job (execution never ends)

### ISSUE THREAD

**Issue by Krusty93** [microsoft/azure-container-apps#1050]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm trying to figure out how to run GitHub runners in ACA Jobs and have followed the [official tutorial](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-github-actions)

However the behavior is not what I expected.

I have configured the GitHub runner as `ephemeral`:
```sh
REGISTRATION_TOKEN="$(curl -X POST -fsSL \
  -H 'Accept: application/vnd.github.v3+json' \
  -H "Authorization: Bearer $GITHUB_PAT" \
  -H 'X-GitHub-Api-Version: 2022-11-28' \
  "$REGISTRATION_TOKEN_API_URL" \
  | jq -r '.token')"

./config.sh \
  --url $REPO_URL \
  --token $REGISTRATION_TOKEN \
  --unattended \
  --disableupdate \
  --ephemeral \
  --replace

./run.sh
```

Although the runner executes correctly the first request, it actually never ends until the timeout is reached. Moreover, having the `ephemeral` flag enabled it means that the runner won't listen for new requests and all GitHub Actions pipelines are then stuck waiting for a new job.

From logs, I see the runner exits with code 0:
```
√ Removed .runner
Runner listener exit with 0 return code, stop the service, no retry needed.
Exiting runner...
```

I also tried to spin up the runner locally and it behaves properly: after the above messages it is correctly shut down.

The container execution history shows all runs as failed, but (at least) few weeks ago they used to be in `succeeded` status and I never faced this issue.

Forcing the container shutdown via `az containerapp job stop` fixes the issue and I'm using this as temporarily workaround.

### Steps to reproduce
1. Create a container app job as explained [in doc](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-github-actions)
2. Set the `github-runner` scale rule with these metadata values: [`github_runner: https://api.github.com`; `owner: <your-org>`; `repos: <your-repo>`; `runnerScope: repo`; `targetWorkflowQueueLength: 1`]
3. Run a `self-hosted` GitHub Actions. Observe how it completes successfully
4. Look at the execution history - container will not terminate
5. Run the GitHub Actions again. Observe how the job is not picked up by the ACA Job

**Expected behavior** [What you expected to happen.]
When a GitHub Actions job is terminated, the ACA container must shutdown

**Actual behavior** [What actually happened.]
When a GitHub Actions job is terminated, the ACA container runs until the timeout is reached

**Comment by vinisoto** [comment]
hi @Krusty93 - can you send these details to `acasupport at microsoft dot com` so we can investigate?:

- Subscription Id
- Container App Environment name
- Container App Job Name and Resource Id

Thanks

**Comment by Krusty93** [comment]
Hi @vinisoto , I sent the details you requested. Thank you for your support, really appreciated.

**Comment by lihaMSFT** [comment]
@Krusty93, I was able to repro your timeout. Simply removing `--disableupdate` fixes it. Otherwise, it throws this error:

```
An error occurred: Runner version vx.xxx.x is deprecated and cannot receive messages.
```

Also I would suggest using `&&` to short circuit `./config.sh` and `./run.sh`. This way if `./config.sh` fails, `./run.sh` will not execute and enter an infinite restart loop for the replica.

**Comment by Krusty93** [comment]
It turned out to be an erroneous usage of the `label` [KEDA `github-runner` property](https://keda.sh/docs/2.12/scalers/github-runner/).

I used to set a single Container App Job for multiple GitHub repositories; the job had a container for each repository, and I thought the `label` property was useful to tell the Container App which container had to scale up.

Instead, `label` filters out GitHub runners based on labels.

Creating a Container App Job for each repository and removing the `label` property solved the issue. Now containers shut down properly.

Thanks to the support for helping me via email.
