### ISSUE TITLE
ACA Container Unable to Resolve AKS Private Cluster DNS

### ISSUE THREAD

**Issue by Chris-Sheridan** [microsoft/azure-container-apps#1054]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduce
1. Follow the tutorial (Azure DevOps)
2. Setup another vnet/private cluster
3. Create new pipeline

**Expected behavior** [What you expected to happen.]
Pipeline is created and executed.

**Actual behavior** [What actually happened.]
The remote name could not be resolved: '<namespace>-dns-nrkdam3r.c84201e0-c52c-46ce-bba0-36840a30c90b.privatelink.eastus.azmk8s.io'

In addition, I have pipelines that once worked and having similar DNS issues as well.  Here's the error message which happens for the existing pipeline:
`error: failed to create secret Post "[https://ss-api-internal-dns-wmmru0vq.hcp.eastus.azmk8s.io/api/v1/namespaces/api-internal/secrets?fieldManager=kubectl-create&fieldValidation=Strict"](https://ss-api-internal-dns-wmmru0vq.hcp.eastus.azmk8s.io/api/v1/namespaces/api-internal/secrets?fieldManager=kubectl-create&fieldValidation=Strict%22): dial tcp: lookup ss-api-internal-dns-wmmru0vq.hcp.eastus.azmk8s.io on 127.0.0.11:53: no such host`

This looks like a DNS or network issue and possibly an AKS issue looking for a DNS endpoint.  I created a non-private cluster and everything worked fine, so seems to be associated to private clusters.

I am totally stuck and have searched feverishly with no answer.  I'm hoping someone can shed some light on what I have wrong.  Thanks!

**Comment by vinisoto** [comment]
hi @Chris-Sheridan thanks for reaching out. 

A few clarifying questions:

Can you please explain a little bit about your scenario? Are you trying to resolve a private AKS cluster from an Azure Container App?

Where/when are you seeing the error: `The remote name could not be resolved: '-dns-nrkdam3r.c84201e0-c52c-46ce-bba0-36840a30c90b.privatelink.eastus.azmk8s.io'` is it when you try to create a new Container App Environment?

Likewise, where are you seeing the error `error: failed to create secret Post "[https://ss-api-internal-dns-wmmru0vq.hcp.eastus.azmk8s.io/api/v1/namespaces/api-internal/secrets?fieldManager=kubectl-create&fieldValidation=Strict"](https://ss-api-internal-dns-wmmru0vq.hcp.eastus.azmk8s.io/api/v1/namespaces/api-internal/secrets?fieldManager=kubectl-create&fieldValidation=Strict%22): dial tcp: lookup ss-api-internal-dns-wmmru0vq.hcp.eastus.azmk8s.io on 127.0.0.11:53: no such host` is it when creating/updating an Environment?

**Comment by Chris-Sheridan** [comment]
This happens before any environment setup.  I think I resolved at least part of the issue.  I created 2 new vents, and I setup the agent container job in one vnet and the cluster was in the other.  Once I peered the 2 vnets together, it worked and the agent was able to interact (i.e. run kubectl) against the cluster in a separate vnet.

**Comment by Chris-Sheridan** [comment]
This problem still exists but it appears isolated to the vnet setup the cluster resides in.  I have a ticket open to Microsoft for it, but I think you we can close this issue for now.

**Comment by Chris-Sheridan** [comment]
I figured this out.  This is relevant for Azure DevOps, GitHub Actions, or using kubectl via the CLI to interact with a private AKS cluster. I received an error message stating, "Unable to connect to the server: dial tcp: lookup <Cluster Name>-dns-rrxn45oq.19568f79-2d23-4df0-8d3e-f7e3e690d17b.privatelink.eastus.azmk8s.io on <Private DNS IP>:53: no such host"

If anyone is getting this error running kubectl from a vnet different than the cluster's vnet, you need to ensure the following:

- The vnets are peered. I tried otherwise but the nslookup showed it was lost in trying to resolve the IP address, especially if IPs overlap.
- The Private DNS zone created by the AKS cluster installation has a Virtual Network Link to the vnet where you run kubectl. To do this, perform the following:
- Select to Private DNS zones from your Azure Portal Homepage (for me, it was: https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.Network%2FprivateDnsZones).
- Click on the Private DNS zone AKS created. In my case, it was "19568f79-2d23-4df0-8d3e-f7e3e690d17b.privatelink.eastus.azmk8s.io".
- Click on Virtual network links (under Settings in left-side pane).
- Click on the "+Add" button.
- Complete the form with your link name and select the virtual network you want to run kubectl (or Azure DevOps or your private GitHub Actions runner) from.
- Once completed, you can test running kubectl from a VM inside the vnet (you first need to run az aks get-credentials first).

Good luck!
