### ISSUE TITLE
Incorrect overwriting of ingress IP restriction rules

### ISSUE THREAD

**Issue by benverhees** [microsoft/azure-container-apps#1057]
### This issue is a:
- [x] bug report
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When using the Azure Portal to update IP Restriction rules for Azure Container Apps ingress, the first IP rule in the list is overwritten with the updated values instead of the selected rule. This behaviour poses a security risk as it allows unintended changes to IP restrictions, potentially allowing unauthorised access to the application when this issue is not noticed.

### Steps to reproduce
1. Add more than one allow rule to the IP Restrictions list on the Ingress tab
2. Click on a rule other than the first one
3. Update the value for `IPv4 address range`, `Name` and/or `Description`
4. Click Save

**Expected behavior**
The selected rule should be updated with the new values. The changes should not affect other rules in the list.

**Actual behavior**
The selected rule is not updated with the new values. Instead, the first rule in the list is overwritten.

**Screenshots**
<img width="655" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/311514/6ad83991-63b2-40a1-b509-52dc7d910bff">
<img width="582" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/311514/f86a9102-51a0-4ec1-b5be-241abc95efa3">
<img width="663" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/311514/8fcfb55a-9183-45a6-b91f-598cb0e47503">

### Additional context
This issue occurs in the Azure Portal

**Comment by anthonychu** [comment]
Thanks for reporting. Was able to reproduce. Will investigate ASAP. Internal bug 26538170.

**Comment by LianaAdaza** [comment]
Bug has been fixed. Please feel free to reach out if you continue to encounter difficulties.
