### ISSUE TITLE
Container Insights in Azure Monitor for Azure Container Apps

### ISSUE THREAD

**Issue by NielsFilter** [microsoft/azure-container-apps#106]
Currently there are some logs already written to Log Analytics Workspace for Container Apps, but I've struggled to troubleshoot issues.

I find the "Container Insights" section in Azure Monitor quite useful and thought it'd be nice to see and monitor my containers for Container Apps in there as well.

![image](https://user-images.githubusercontent.com/4918407/153141047-bd87cc79-c349-44c0-b193-2267f5eb205a.png)

**Comment by simonjj** [comment]
This should now be possible. Please let me know if you have trouble finding.
