### ISSUE TITLE
Feature Request: Missing Creation button for Jobs

### ISSUE THREAD

**Issue by maythamfahmi** [microsoft/azure-container-apps#1066]
**Is your feature request related to a problem? Please describe**.  
When creating jobs in a Container App environment, the only button is for creating App but there is no button for a Job, which is irritating

**Describe the solution you'd like**.    
Add an extra button beside the current button, for instance, one called **Create App** and the other **Create Job**

**Describe alternatives you've considered**.   
Right now I do it by searching for **Container App Jobs** in Azure Portal and from there creating a job.

**Additional context**.  
![image](https://github.com/microsoft/azure-container-apps/assets/9260645/48c6f4b7-c963-45e6-b8da-9d79e0da3efb)

**Comment by anthonychu** [comment]
Thanks for the suggestion. We actually just completed the work on this and it should be available in a couple of weeks! (Internal tracking 24347630)

<img width="355" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/3982077/3e7920ae-3dd9-4571-9b16-ca00e5cb6f7e">

**Comment by maythamfahmi** [comment]
Great effort 👌 .

Looking forward to see the results in portal soon.

**Comment by maythamfahmi** [comment]
I can confirm that this issue has been resolved in the Azure portal. I appreciate the dedicated efforts of you, @anthonychu, and your team members. Your commitment to continuously improving processes at such a quick pace is highly commendable. Thank you.

![image](https://github.com/microsoft/azure-container-apps/assets/9260645/5655a78a-5514-4c60-a047-74620c3b43cd)
