### ISSUE TITLE
Container App Job using the wrong log syntax when switching Logging options from Azure Log Analytics to Azure Monitor

### ISSUE THREAD

**Issue by maythamfahmi** [microsoft/azure-container-apps#1069]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
By default when using Azure Log Analytics for monitoring Container App Environment. When clicking on Logs or Execution history console/logs within Container App Job it is used for Console logs `ContainerAppConsoleLogs_CL` and system logs `ContainerAppSystemLogs_CL`. But when switching from Azure Log Analytics to Azure Monitor
![image](https://github.com/microsoft/azure-container-apps/assets/9260645/8129be6a-5a9b-4276-9f9f-943be9b48723)

It should use `ContainerAppConsoleLogs` and `ContainerAppSystemLogs` instead. but It keeps serving `ContainerAppConsoleLogs_CL`  and `ContainerAppSystemLogs_CL`.

It is logical when switching to Azure Monitor that those correct syntax should also follow with the change.

### Steps to reproduce
1. In the Container App environment under Logging options
2. Change from Azure Log Analytics to Azure Monitor
3. Go to Apps and find any app
4. Click Logs, it will serve you with `ContainerAppConsoleLogs_CL`  and `ContainerAppSystemLogs_CL`. But It should use `ContainerAppConsoleLogs` and `ContainerAppSystemLogs` instead for Azure Monitor.

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/9260645/7d81a9d4-9129-4087-8877-a7654baffaf7)

**Comment by maythamfahmi** [comment]
Example, by default when click on console (logs)

![image](https://github.com/microsoft/azure-container-apps/assets/9260645/6497d11d-da59-4da5-8f26-c25c83efa52c)


It serves 

```
ContainerAppConsoleLogs_CL
| where ContainerGroupName_s startswith 'jobname-28492135'
```
![image](https://github.com/microsoft/azure-container-apps/assets/9260645/ffa89639-eac4-40f5-a971-631deeff31ad)

Removing _CL and _s will work.

ContainerAppConsoleLogs
| where ContainerGroupName startswith 'name-28492135'

![image](https://github.com/microsoft/azure-container-apps/assets/9260645/5cc1a9ba-f9ed-40f9-a8ae-feedb409976c)

**Comment by vinisoto** [comment]
hi @maythamfahmi the Portal fix for this issue has been deployed.

**Comment by maythamfahmi** [comment]
@vinisoto I can confirm that this is solved, I tried it and loved it.
