### ISSUE TITLE
Not more then 2 environments possible in one Azure Subscription?

### ISSUE THREAD

**Issue by wesselkranenborg** [microsoft/azure-container-apps#107]
We are evaluating the use of Azure Container Apps. During creating our development, test and integration environment we got the following error when deploying multiple container environments to the same Azure Subscription:

> The subscription '***' cannot have more than 2 environments.

Is this something which will change once it will go GA? Or is there a specific reason for this?

**Comment by ThorstenHans** [comment]
This is definitely a preview limitation. If I remember correctly (don't judge me if not), @jeffhollan mentioned in the early days of the preview that this limit will also be increased **during** the preview

**Comment by torosent** [comment]
This is a limitation of the preview. We are working on increasing the quotas for GA.

**Comment by MirzaMerdovic** [comment]
@torosent do you know the planned date for GA?

I apologize for asking this question here, but couldn't find the info elsewhere

**Comment by kendallroden** [comment]
With GA we have increased the number of environments per subscription to 10

**Comment by onionhammer** [comment]
These new limits seem fairly limited for organizations that have more than 1 application in a region;

https://docs.microsoft.com/en-us/azure/container-apps/quotas

![image](https://user-images.githubusercontent.com/969938/177602784-f4048305-b691-4882-897d-c1662c89579a.png)

Say your organization has two applications (completely separate), and each application has a QA an a production, that's 4 app environments in potentially 1 environment right here, next application you build has to go into a different region?

Also 20 containers apps per environment per subscription? what does that mean? You can make 20 container apps in a subscription or 20 container apps in an environment?
