### ISSUE TITLE
Label Disappears on Revisions with 0% Traffic in Multi-Revision Mode (Azure Portal)

### ISSUE THREAD

**Issue by almasantiago** [microsoft/azure-container-apps#1078]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We are experiencing an issue within the Azure Container Apps in multi-revision mode. After adding a label to a revision that is allocated 0% traffic, the label initially appears to save successfully. However, upon refreshing the page or revisiting the revision, the label no longer appears.

### Steps to reproduce
1. Switch to multi-revision mode.
2. Create a new revision; allocate 0% traffic. Traffic split is now 100/0.
3. Add a label to the revision with 0% traffic through the Azure portal.
4. Confirm that the label appears to be saved successfully.
5. Refresh the page or navigate away from and back to the revision details page.

**Expected behavior**
The label added to the revision with 0% traffic should persist and be visible after refreshing or revisiting the page.

**Actual behavior**
After refreshing or revisiting the revision details page, the previously added label is no longer visible. The label seemingly does not persist on revisions with 0% traffic, even though it shows that it was saved successfully.

**Screenshots**
![image](https://github.com/microsoft/azure-container-apps/assets/69998978/6a32c70a-17bf-49ad-9d3e-11865aac61e0)

**After adding and saving the label:**
![image](https://github.com/microsoft/azure-container-apps/assets/69998978/0a41f4f8-85ee-4760-b15d-357850b293ec)

**After refreshing the page:**
![image](https://github.com/microsoft/azure-container-apps/assets/69998978/eae06cf9-3f6d-4ec1-aa2f-d8d80ea14421)

### Additional context
- Issue happens when the label is added through the Azure portal. 
- Labels added to revisions with traffic allocation greater than 0% do not exhibit this issue and persist as expected.

**Comment by karpikpl** [comment]
I'm seeing the same issue.

**Comment by anthonychu** [comment]
Thanks for reporting. We'll investigate.

**Comment by LianaAdaza** [comment]
Thank you for your report. This portal bug (26836629) has been resolved. Please feel free to reach out if you continue to encounter difficulties.
