### ISSUE TITLE
CAJ: Changing only env var value leaves "save" disabled

### ISSUE THREAD

**Issue by nikoisonfire** [microsoft/azure-container-apps#1079]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When editing the container in Container App Jobs, when only the value of an environment variable is changed (and not added/deleted/etc.), then the "Save" button is still disabled. An empty variable has to be added for the configuration to be saveable.

### Steps to reproduce
1. Edit a container that contains ENV VARs in Container App Jobs
2. Try to save the configuration 

**Expected behavior** [What you expected to happen.]
Save button is enabled.

**Actual behavior** [What actually happened.]
Save button is disabled.

**Screenshots**         
![Bildschirm­foto 2024-02-13 um 10 25 35](https://github.com/microsoft/azure-container-apps/assets/22169321/c7bb9b7a-531c-46c4-b573-16b6817e6515)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
Portal

**Comment by anthonychu** [comment]
Thanks for reporting. Created internal bug 26797782 to track.

**Comment by JebinAJ** [comment]
is this bug resolved? I am facing similar issue.

**Comment by anthonychu** [comment]
The original issue was fixed and deployed in March. @JebinAJ can you please provide more details to reproduce?
