### ISSUE TITLE
Developer portal custom domain not working

### ISSUE THREAD

**Issue by gordicaleksa** [microsoft/azure-container-apps#1080]
### This issue is a: (mark with an x)
- [ x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
After setting up a custom domain for developer portal the URL is displayed when someone lands on the dev portal but as soon as they login or sign-up they're redirected to the "ugly" <apim project name>.developer.azure-api.net. domain.

Note: I've used https://github.com/microsoft/azure-api-management-monetization/blob/main/documentation/stripe-deploy.md to deploy the initial platform.

### Steps to reproduce
1. Under custom domains add a new custom domain importing the cert from key vault.

https://techmindfactory.com/APIM-With-Front-Door-And-Custom-Domain/ <- this tutorial contains the step I've taken but tl;dr:
1) create new cert using ZeroSSL
2) import into key vault as pfx
3) under custom domain add new binding: for certificate pick key vault, client identity is system assigned identity

**Expected behavior** [What you expected to happen.]
Use my custom domain no matter where the user is on the portal...

**Actual behavior** [What actually happened.]
The domain starts with the custom domain I specified but then toggles to the ugly one.

**Comment by vinisoto** [comment]
hi @gordicaleksa - looks like your issue is related to API Management, not Container Apps

**Comment by gordicaleksa** [comment]
Hi @vinisoto can you point me to the right place? It's not obvious where to post issues https://github.com/Azure/API-Management this repo doesn't even have an issue section

**Comment by LianaAdaza** [comment]
Thank you for your patience. You may post your issue here: https://github.com/Azure/api-management-developer-portal/issues
