### ISSUE TITLE
Feature Request: JVM memory fit in Azure Container Apps

### ISSUE THREAD

**Issue by seanli1988** [microsoft/azure-container-apps#1094]
Default JVM settings are not optimal for the container environment.

**Comment by seanli1988** [comment]
feature complete and I have published a blog post here 
https://techcommunity.microsoft.com/t5/apps-on-azure-blog/automatic-memory-fit-for-java-apps-in-azure-container-apps/ba-p/4134276

**Comment by mortenf1984** [comment]
Hi!
I am having some issues with this feuture, according to the blob and documentation, this should automatically be active, but when I try to verify this, I am unable to see the log entries described, cant find "Disabling jvm memory fitting" or "Calculated JVM Memory Configuration" in the logs. 

are there any steps that I need to do? CAE is located in norwayeast, it does not have this available there yet?
