### ISSUE TITLE
Unable to retrieve secrets from secret store (secretstores.azure.keyvault)

### ISSUE THREAD

**Issue by henrikthorin** [microsoft/azure-container-apps#11]
Hello,

I'm trying to retrieve secrets from Azure Keyvault using the "secretstores.azure.keyvault" Dapr component.
The application uses the Dapr .NET SDK (1.4.0) and the DaprClient.

When trying to retrieve the secret, DaprClient throws exception.

> Dapr.DaprException: Secret operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
> at Dapr.Client.DaprClientGrpc.GetSecretAsync(String storeName, String key, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
>  Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Not Implemented")

Sometimes we also get connection refused from dapr sidecar.
> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:50001) SocketException: Connection refused", DebugException="System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:50001)

I can see in the dapr logs that the component is successfully loaded by the sidecar and no errors are reported there.
The secret store configuration works when running locally using Docker Compose and Dapr.

Is the secretstores.azure.keyvault currently not supported?

See attached ARM template used for deployment.

Best regards
Henrik

```JSON
{
    "$schema": "https://schema.management.azure.com/schemas/2019-08-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "location": {
            "type": "String"
        },
        "environment_name": {
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "name": "myservice",
            "type": "Microsoft.Web/containerApps",
            "apiVersion": "2021-03-01",
            "kind": "containerapp",
            "location": "[parameters('location')]",
            "properties": {
                "kubeEnvironmentId": "[resourceId('Microsoft.Web/kubeEnvironments', parameters('environment_name'))]",
                "configuration": {
                    "ingress": {
                        "external": true,
                        "targetPort": 80
                    },
                    "secrets": [
                        {
                            "name": "container-registry-password",
                            "value": "**"
                        },
                        {
                            "name": "azure-client-secret",
                            "value": "**"
                        }
                    ],
                    "registries": [
                        {
                            "server":"myregistry.azurecr.io",
                            "username":"myregistryusername",
                            "passwordSecretRef":"container-registry-password"
                        }
                    ]
                },
                "template": {
                    "containers": [
                        {
                            "image": "myregistry.azurecr.io/myservice:latest",
                            "name": "myservice",
                            "env": [
                                {
                                    "name": "SECRETSTORE_NAME",
                                    "value": "secret-store"
                                }
                            ],
                            "resources": {
                                "cpu": 0.5,
                                "memory": "1Gi"
                            }
                        }
                    ],
                    "scale": {
                        "minReplicas": 1,
                        "maxReplicas": 1
                    },
                    "dapr": {
                        "enabled": true,
                        "appPort": 80,
                        "appId": "myservice",
                        "components": [
                            {
                                "name": "secret-store",
                                "type": "secretstores.azure.keyvault",
                                "version": "v1",
                                "metadata": [
                                    {
                                        "name": "vaultName",
                                        "value": "thevaultname"
                                    },
                                    {
                                        "name": "azureTenantId",
                                        "value": "**"
                                    },
                                    {
                                        "name": "azureClientId",
                                        "value": "**"
                                    },
                                    {
                                        "name": "azureClientSecret",
                                        "secretRef": "azure-client-secret"
                                    }
                                ]
                            }
                        ]
                    }
                }
            }
        }
    ]
}

**Comment by vturecek** [comment]
`secretstores.azure.keyvault` is currently not supported. Are you able to use the built-in application-wide secret store instead (same place you're currently storing your container registry password and Azure client secret)? 

```
  "secrets": [
                        {
                            "name": "container-registry-password",
                            "value": "**"
                        },
                        {
                            "name": "azure-client-secret",
                            "value": "**"
                        }
                    ],
```

**Comment by johnnyruz** [comment]
Is it documented somewhere what Dapr components are currently supported?

I'm getting the exact same Connection refused error when trying to implement Pub/Sub with the pubsub.azure.eventhubs component type.

**Comment by andreatosato** [comment]
@vturecek Can I use another secrets? Like file o others?
I'm creating Community Demos, I write this: https://github.com/andreatosato/SpotifyMicroservices/tree/feature/container-apps/Deploy
I have secrets where I store Spotify Credential.
Can I use another secret service?

**Comment by takekazuomi** [comment]
@andreatosato 
My understanding is that the current Container Apps secret management is limited and inconvenient.
I'm passing the Key Vault as a parameter when deploying. bicep has a syntax that is convenient for that.

Sample
https://github.com/takekazuomi/container-apps-kv01

Sorry for using Japanese.

**Comment by andreatosato** [comment]
Oh great, I want to use Azure Keyvault for my secrets.
I don't understand how save my json in azure keyvault.

**Comment by takekazuomi** [comment]
I use WSL2 (Linux) for the deployment environment.

This sample consists of two deployments. The first is to deploy to KeyVault and the second is to deploy to Container Apps. The KeyVault Secret can be up to 255 characters, so if I have multiple secrets, I need to save them individually.

The flow of deploying KeyVault is as follows.
1. Put the secret in an environment variable
2. Embed environment variables in JSON with envsubst
https://github.com/takekazuomi/container-apps-kv01/blob/main/Makefile#L101
3. Write keyvault.bicep which references JSON
https://github.com/takekazuomi/container-apps-kv01/blob/main/deploy/keyvault.bicep#L6
https://github.com/takekazuomi/container-apps-kv01/blob/main/deploy/keyvault.bicep#L40-L46
Now you have Secrets in KeyVault.

**Comment by RichardLaos** [comment]
> `secretstores.azure.keyvault` is currently not supported. Are you able to use the built-in application-wide secret store instead (same place you're currently storing your container registry password and Azure client secret)?
> 
> ```
>   "secrets": [
>                         {
>                             "name": "container-registry-password",
>                             "value": "**"
>                         },
>                         {
>                             "name": "azure-client-secret",
>                             "value": "**"
>                         }
>                     ],
> ```

Are these secrets accessible through the dapr API? If, not how would they be accessed from an application?

**Comment by ecosgrave** [comment]
+1 for making it more clear what is and is not available from Dapr in ACA.  I was relying on Dapr self-hosted and Dapr in ACA being equivalent.

Its confusing to have Dapr Self-Hosted components different to components available in ACA.  I wasted a lot of time trying to "fix" my deployment before I found this ticket.  Don't let me deploy a component that isn't available.

Better, just give me all the things and hit me with some disclaimers if they aren't ready for production.

**Comment by kendallroden** [comment]
We have a document coming next week with all supported scenarios. Also, support for Dapr secrets is planned!

**Comment by romanlum** [comment]
+1 for adding secretstores.azure.keyvault support

**Comment by kendallroden** [comment]
this is rolling out in the next week or so

**Comment by esond** [comment]
Any updates? Did it roll out okay? Currently troubleshooting getting secrets from a key vault secret store in my dapr-enabled ASP.NET app. Trying to load them into configuration with the SDK.

**Comment by kendallroden** [comment]
Secrets has been released. @esond please track https://github.com/microsoft/azure-container-apps/issues/460! We have a bug fix going in related to your commend
