### ISSUE TITLE
Azure Portal: health probes display "Port" instead of "Path"

### ISSUE THREAD

**Issue by christiannagel** [microsoft/azure-container-apps#1101]
With the Azure Portal, looking at Health probes with containers, the term *Port* is shown two times, for ports and paths. I think in the first case this should be *Path*:

<img width="491" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/1908285/149cee53-635c-4cb3-adc5-17b4e03f79ab">

**Comment by anthonychu** [comment]
Thanks for reporting. We'll fix it!

**Comment by LianaAdaza** [comment]
Thank you for your report! This bug has been resolved (26952001). Please feel free to reach out if you continue to encounter difficulties.
