### ISSUE TITLE
CAJ: Service bus messages not "consumed" leads to infinite restarts of completed jobs

### ISSUE THREAD

**Issue by nikoisonfire** [microsoft/azure-container-apps#1102]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Messages consumed from Service Bus by event-driven container job starts are not marked as "consumed" or completed and, as a result, remain in the queue/topic indefinitely.

### Steps to reproduce
1. Deploy an Azure Container App with event-driven containers configured to consume messages from an Azure Service Bus queue/topic.
2. Send messages to the configured queue/topic.
3. Observe that a new message starts a new container app job but the message is never removed from the queue/topic.
4. Since the message is not "consumed" the container job will restart indefinitely even if it completes its task successfully

**Expected behavior** Messages should be marked as consumed and removed from the queue/topic after successful processing. The container app job should only be started once.

**Actual behavior** Messages remain in the queue/topic indefinitely, even after being processed by KEDA scaler. This leads to infinite restarts of the container job.

**Screenshots**         

### Additional context
It is not possible to subscribe to the message from within the container because when the container starts the message has already "arrived" and can therefore not be read (and completed/removed) from the queue anymore .

The only way to circumvent this behavior is by sending messages with a TTL that is lower or equal to the container job expected runtime so that the messages get deleted by themselves.

**Comment by anthonychu** [comment]
@nikoisonfire can you please share how you configured your scale rule and what your job container does?

> **Actual behavior** Messages remain in the queue/topic indefinitely, even after being processed by KEDA scaler. This leads to infinite restarts of the container job.

The KEDA scaler only monitors the queue/topic, it doesn't lock or delete messages. Your job should lock a message, process it, and complete it when finished (which deletes it from the queue).

**Comment by nikoisonfire** [comment]
This is an example scale rule. 
![image](https://github.com/microsoft/azure-container-apps/assets/22169321/8cf1f1e8-1ccd-428a-a649-5e4da004e0c4)

The task of the container does not necessarily depend on the message itself, it's rather that the message serves as a "signal" to start the next task in the pipeline.

> The KEDA scaler only monitors the queue/topic, it doesn't lock or delete messages. Your job should lock a message, process it, and complete it when finished (which deletes it from the queue).

How can I do this? When I try to subscribe to the queue or topic from within the job container, the message that started the container in the first place never arrives

**Comment by anthonychu** [comment]
@nikoisonfire I've put together a sample with some details on how this should work: https://github.com/anthonychu/container-apps-scaling-examples/tree/main/azure-servicebus/job-python Please take a look.

**Comment by nikoisonfire** [comment]
I will forward this to the colleague taking over this project. Thank you for taking the time to put this together!
