### ISSUE TITLE
Service Bindings: Postgresql connection environment variables not available to init containers

### ISSUE THREAD

**Issue by jag-eagle-technology** [microsoft/azure-container-apps#1106]
### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm trying to run database migration scripts on a Postgresql database bound to my container app. I've tried running from the service itself and this works fine, but trying to get the same environment variable connection string in my init container doesn't work - POSTGRES_CONNECTION_STRING is not set.

### Steps to reproduce
1. As above - can provide further info if required (replicated using basic ASP.NET Service container & .NET Console App / DBUP init container).

**Expected behavior** Environment variable available and able to run migrations

**Actual behavior** Environment variable not found

### Additional context
Deploying using bicep:

```
resource testapp 'Microsoft.App/containerApps@2023-05-01' = {
  name: 'testapp'
  location: location
  dependsOn: [
    roleAssignment
  ]
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${identity.id}': {}
    }
  }
  properties: {
    managedEnvironmentId: environment.id
    configuration: {
      ingress: {
        targetPort: 8080
        external: true
      }
      registries: [
        {
          server: 'mycontainerreg.azurecr.io'
          identity: identity.id
        }
      ]
    }
    template: {
      serviceBinds: [
        {
          serviceId: testdb.id
          name: 'postgres'
        }
      ]
      initContainers: [
        {
          image: 'mycontainerreg.azurecr.io/testacapostgressetup:latest'
          name: 'testing-setup-container'
        }
      ]
      containers: [
        {
          image: 'mycontainerreg.azurecr.io/testacapostgres:latest'
          name: 'testing-container'
        }
      ]
    }
  }
}
```

**Comment by ahmelsayed** [comment]
Yeah, good point. There is no reason not to inject those values to the initContainer other than it was missed in the initial implementation. It should be in the next release which will rollout in 2-3 weeks.

**Comment by ahmelsayed** [comment]
This should be deployed as of couple of weeks ago
