### ISSUE TITLE
Http scale rule for revision not being respected

### ISSUE THREAD

**Issue by NielsFilter** [microsoft/azure-container-apps#111]
When I create an Http scaling rule via any of the following, it doesn't seem to be respected.

- bicep (ARM)
- yaml
- add rule directly in the Azure portal

Portal shows no scaling rules:
![image](https://user-images.githubusercontent.com/4918407/154091881-a7b4ae54-3886-4684-bdc5-aaf47b0e298b.png)

Checking with AZ CLI it indicates that there are no rules:
![image](https://user-images.githubusercontent.com/4918407/154092127-e37cdd7d-7786-4467-a02a-4ecf1024aae8.png)

**Comment by kendallroden** [comment]
When I added the rule via YAML, I actually see it in the output from the CLI but I do not see it in the portal. Thanks for reporting. We will get this resolved

**Comment by ahmelsayed** [comment]
This issue has been fixed for a while in the API/UI. Please feel free to reactivate or open a new issue if you have issues with this.
