### ISSUE TITLE
Inquire about technical details of the JVM  Memory Fitting  feature

### ISSUE THREAD

**Issue by jungan21** [microsoft/azure-container-apps#1114]
https://learn.microsoft.com/en-us/azure/container-apps/java-overview

Can someone help share more technical details about the JVM Memory Fitting feature.

Is it based on algorithms/technologies mentioned in this paper: https://www.microsoft.com/en-us/research/publication/oppertune/

**Comment by anthonychu** [comment]
@seanli1988 can you please help with this?

**Comment by jungan21** [comment]
anyone can help with issue. thanks

**Comment by seanli1988** [comment]
Yeah, a blog post is in progress to explain the process. Expect the publication to go live in April.

**Comment by seanli1988** [comment]
blog published: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/automatic-memory-fit-for-java-apps-in-azure-container-apps/ba-p/4134276
