### ISSUE TITLE
`infrastructureResourceGroup` is null for Consumption environments

### ISSUE THREAD

**Issue by cailyoung** [microsoft/azure-container-apps#1118]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduce
1. Create an environment without specifying an infrastructure resource group
2. `az containerapp env show` the environment

**Expected behavior** [What you expected to happen.]
`infrastructureResourceGroup` has the resource group containing the load balancer

**Actual behavior** [What actually happened.]
`infrastructureResourceGroup` is `null` in the response

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by Seris370** [comment]
May I confirm if you have created a workload profile environment with custom vNet? You can check the `workloadProfiles` section 
and the `vnetConfiguration` section in the environment response.

**Comment by cailyoung** [comment]
@Seris370 no, we use consumption profile. I'm trying to locate the load balancer that gets created in the `MC_*` resource group.

**Comment by cailyoung** [comment]
@Seris370 thanks for clarifying that. It would be good to have the API docs and/or product documentation clarified so that the pattern for naming the resource group was documented.
