### ISSUE TITLE
Customer KEDA scaler - service bus requires namespace Manage permissions

### ISSUE THREAD

**Issue by jgross-aspire** [microsoft/azure-container-apps#1138]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When setting up a custom servicebus scaler for Container App Jobs, the connection string requires Manage permissions.

I am not sure why this is the case, as the scaler should only need to Listen on the particular queue in which it is listening to. The documentation does not state what level of access the generated connection string should have, only that it should be generated.

It is interesting that in Keda's documentation, separate from Azure, they document only needing Listen permissions: https://github.com/kedacore/sample-dotnet-worker-servicebus-queue/blob/main/connection-string-scenario.md#setup.

### Steps to reproduce
1. Follow these instructions: https://learn.microsoft.com/en-us/azure/container-apps/scale-app?pivots=azure-cli#example-2
2. Generate a key with only Listen permissions, observe container not scaling and service bus queue will report "User Error" metrics
3. Edit key to have manage permissions, observe it works

**Expected behavior** [What you expected to happen.]

Provided key/connection string should only be required to have Listen permissions.

**Actual behavior** [What actually happened.]

Provided key/connection string must have Manage permissions.

**Screenshots**         

![image](https://github.com/microsoft/azure-container-apps/assets/139268618/ad73b973-6c8e-46e6-b5e4-bb2774b7623f)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by anthonychu** [comment]
The official KEDA docs states that manage permissions is required for the scaler to read the metrics needed for scaling: https://keda.sh/docs/2.13/scalers/azure-service-bus/#trigger-specification

Also see this discussion that led to the note being added: https://github.com/kedacore/keda/issues/806

**Comment by tomkerkhove** [comment]
Unfortunately this is correct and enforced by Azure Service Bus in order to get the metrics.

**Comment by jgross-aspire** [comment]
Thank you for the reply. I had missed that documentation.
