### ISSUE TITLE
App job not stopping despite completing task

### ISSUE THREAD

**Issue by itallackpure** [microsoft/azure-container-apps#1145]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
On rare occasions (it's not obvious what causes this), my container app job will continue to run even after completing the task. It runs until either it gets killed or reaches the timeout limit. This one completed the job successfully but got killed a minute later:

**Console Logs**
![image](https://github.com/microsoft/azure-container-apps/assets/142485672/cb9f3634-651b-4394-93e3-8105534f7727)

**System Logs**
![image](https://github.com/microsoft/azure-container-apps/assets/142485672/68543476-0467-4682-a458-67812ee71000)

In this other case, I had to stop the job manually:

**Console Logs**
![image](https://github.com/microsoft/azure-container-apps/assets/142485672/a8610511-0f61-4622-9a86-b63cbeddc806)

**System Logs**
![image](https://github.com/microsoft/azure-container-apps/assets/142485672/747c6866-15b5-4f1f-8049-df8e5978d772)

### Steps to reproduce
1. Not able to reproduce, seems to happen randomly, I would guess <0.5% of the time.

**Expected behavior** [What you expected to happen.]
Container App Job shows 'Succeeded' and finishes, allow new queue messages to be processed.

**Actual behavior** [What actually happened.]
Container App Job doesn't completed, hogging the scaling rule and preventing new messages from being processed.

**Screenshots**         
See above.

### Additional context
I have another app job with almost identical code (regarding completion and resources) which has never had this issue. I can't figure out what is causing it.

**Comment by anandanthony** [comment]
This is an intermittent issue where the ACA Job's container exits but the execution still keeps on running. We have improved the logic for this specific case.
