### ISSUE TITLE
Custom domain does not work as it should

### ISSUE THREAD

**Issue by antonioscript** [microsoft/azure-container-apps#1146]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I created an API container and tried to create a custom domain (CNAME and TXT). I followed all the steps and everything seemed to be ok, but the domain is not being pointed to the container URL. And it also doesn't appear in the overview part

**Expected behavior**:I thought that in the overview section where the URL was changed to the new domain

**Actual behavior** : But nothing happened, everything seems to be correct, but nothing happens

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/10932478/8a905441-148c-4f93-9334-f624d8b3e29b)
Here is the custom domain I set up on my DNS provider

![image](https://github.com/microsoft/azure-container-apps/assets/10932478/b7fc3122-0d49-437e-acc0-6fcd9ac6dfa0)
The domain URL I just added does not appear, the old URL remains
![image](https://github.com/microsoft/azure-container-apps/assets/10932478/8afc862f-7127-42a3-89fd-ebdf5aad5a84)

**Comment by sczd** [comment]
@antonioscript For information, we also setup custom domain and the Azure portal always shown the default domain only.
This is not practical, but I understand it, since the custom domain does not support all features yet, such as a custom domain for each revision (only works with the default domain).
 However, the portal could display both URLs.
