### ISSUE TITLE
Feature Request: KEDA version update to allow scaling with GitHub App toward GitHub Enterprise Server.

### ISSUE THREAD

**Issue by Hi-Fi** [microsoft/azure-container-apps#1147]
**Is your feature request related to a problem? Please describe**.  
We're using GitHub Enterprise Server (GHES), and would like to use GitHub App for runner authentication. For runner side that works fine, but for scaling side currently used KEDA version (2.12.1) doesn't set GitHub API URL correctly to PEM handling part. It's fixed at 2.13.0 release (issue kedacore/keda#5387)

**Describe the solution you'd like**.    
ACA environment to use newer KEDA version (current one 2.13.1).

**Describe alternatives you've considered**.   
Currently we have to use PAT for the authentication, but being able to impersonate registration would be good thing. Other option would be to use bot accounts to get those PATs, but it's also a bit dirty solution as there's native way to authenticate already supported by KEDA.

**Additional context**.  
Runner process can authenticate already fine with PEM, using https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#example-using-bash-to-generate-a-jwt to get the JWT and with that registration token for runner process.

**Comment by tomkerkhove** [comment]
@anthonychu I think this would be a good improvement, can you talk about it?

**Comment by Hi-Fi** [comment]
KEDA version in ACA seems to be now 2.14.0, and scaling works fine with GitHub App.
