### ISSUE TITLE
Workload profile showing as preview

### ISSUE THREAD

**Issue by seanli1988** [microsoft/azure-container-apps#1148]
Reporting the issue on behalf of a customer ask.
Workload profile is a GA-ed product base on this announcement https://techcommunity.microsoft.com/t5/apps-on-azure-blog/generally-available-azure-container-apps-workload-profiles-more/ba-p/3913345
However it's still showing as preview in the Azure portal.
![image](https://github.com/microsoft/azure-container-apps/assets/29985344/f6b55c04-f117-4bfa-9e44-f33a0de20888)

**Comment by LianaAdaza** [comment]
Preview tag has been removed. Thank you
