### ISSUE TITLE
Remove Azure pipeline scaler from docs and add disclaimer 

### ISSUE THREAD

**Issue by jorgearteiro** [microsoft/azure-container-apps#115]
Remove Azure pipeline from documentation as it only works properly when using scalejobs, that’s not available on ACA yet. can we have a disclaimer to let users know that’s not supported. this can save a lot of time for them.
Look discussion on Twitter https://twitter.com/jorgearteiro/status/1494324269371002882?s=21

https://docs.microsoft.com/en-au/azure/container-apps/scale-app

**Comment by anthonychu** [comment]
Perhaps it’s better to list the ones that do work and calling out any notable issues with each. /cc @cebundy @craigshoemaker

**Comment by kendallroden** [comment]
We are working to create validation for supported scalers but the devops support has been completed per the above
