### ISSUE TITLE
413 error while creating container app from source code

### ISSUE THREAD

**Issue by sonalika-roy** [microsoft/azure-container-apps#1150]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When we try to create container app from local source code (without dockerfile), at the step where it uploads the dats, you get 413 error if the file size is greater than 200MB.

### Steps to reproduce
1. Sample command to create container app: 
az containerapp create \
   --name api-gateway \
   --resource-group $RESOURCE_GROUP \
   --ingress external \
   --target-port 8080 \
   --environment $ACA_ENVIRONMENT \
   --user-assigned $USER_ID \
   --source . \
   --min-replicas 1 \
   --cpu 2 --memory 4Gi \
   --build-env-vars "BP_MAVEN_BUILD_ARGUMENTS=mvn clean package -DskipTests -pl :spring-petclinic-api-gateway -am" \
   --build-env-vars "BP_JVM_VERSION=17" \
   --build-env-vars "BP_MAVEN_VERSION=3" \
   --build-env-vars "BP_MAVEN_BUILT_ARTIFACT=spring-petclinic-api-gateway/target/spring-petclinic-api-gateway-$VERSION.jar" \
   --bind $JAVA_COMPONENT_NAME $JAVA_COMPONENT_NAME2

az containerapp create \
   --name admin-server \
   --resource-group $RESOURCE_GROUP \
   --ingress external \
   --target-port 8080 \
   --environment $ACA_ENVIRONMENT \
   --min-replicas 1 \
   --source . \
   --cpu 2 --memory 4Gi \
   --build-env-vars "BP_MAVEN_BUILD_ARGUMENTS=mvn clean package -DskipTests -pl :spring-petclinic-admin-server -am" \
   --build-env-vars "BP_JVM_VERSION=17" \
   --build-env-vars "BP_MAVEN_VERSION=3" \
   --build-env-vars "BP_MAVEN_BUILT_ARTIFACT=spring-petclinic-admin-server/target/spring-petclinic-admin-server-$VERSION.jar" \
   --bind $JAVA_COMPONENT_NAME $JAVA_COMPONENT_NAME2

az containerapp create \
   --name customers-service \
   --resource-group $RESOURCE_GROUP \
   --ingress internal \
   --target-port 8080 \
   --environment $ACA_ENVIRONMENT \
   --user-assigned $USER_ID \
   --source . \
   --min-replicas 1 \
   --cpu 2 --memory 4Gi \
   --build-env-vars "BP_MAVEN_BUILD_ARGUMENTS=mvn clean package -DskipTests -pl :spring-petclinic-customers-service -am" \
   --build-env-vars "BP_JVM_VERSION=17" \
   --build-env-vars "BP_MAVEN_VERSION=3" \
   --build-env-vars "BP_MAVEN_BUILT_ARTIFACT=spring-petclinic-customers-service/target/spring-petclinic-customers-service-$VERSION.jar" \
   --bind $JAVA_COMPONENT_NAME $JAVA_COMPONENT_NAME2

az containerapp create \
   --name vets-service \
   --resource-group $RESOURCE_GROUP \
   --ingress internal \
   --target-port 8080 \
   --environment $ACA_ENVIRONMENT \
   --user-assigned $USER_ID \
   --source . \
   --min-replicas 1 \
   --cpu 2 --memory 4Gi \
   --build-env-vars "BP_MAVEN_BUILD_ARGUMENTS=mvn clean package -DskipTests -pl :spring-petclinic-vets-service -am" \
   --build-env-vars "BP_JVM_VERSION=17" \
   --build-env-vars "BP_MAVEN_VERSION=3" \
   --build-env-vars "BP_MAVEN_BUILT_ARTIFACT=spring-petclinic-vets-service/target/spring-petclinic-vets-service-$VERSION.jar" \
   --bind $JAVA_COMPONENT_NAME $JAVA_COMPONENT_NAME2

az containerapp create \
   --name visits-service \
   --resource-group $RESOURCE_GROUP \
   --ingress internal \
   --target-port 8080 \
   --environment $ACA_ENVIRONMENT \
   --user-assigned $USER_ID \
   --source . \
   --min-replicas 1 \
   --cpu 2 --memory 4Gi \
   --build-env-vars "BP_MAVEN_BUILD_ARGUMENTS=mvn clean package -DskipTests -pl :spring-petclinic-visits-service -am" \
   --build-env-vars "BP_JVM_VERSION=17" \
   --build-env-vars "BP_MAVEN_VERSION=3" \
   --build-env-vars "BP_MAVEN_BUILT_ARTIFACT=spring-petclinic-visits-service/target/spring-petclinic-visits-service-$VERSION.jar" \
   --bind $JAVA_COMPONENT_NAME $JAVA_COMPONENT_NAME2

**Expected behavior** [What you expected to happen.]
The file should be uploaded, and the build should be a success.

**Actual behavior** [What actually happened.]
413 error if the file is big.
(X) Fail: Uploading data (24.6s)
              Error when uploading the file, request exited with 413
              Full logs: 
Error when uploading the file, request exited with 413

### Additional context
Ex. Did this issue occur in the CLI or the Portal?: Az cli command used to create

**Comment by showpune** [comment]
Hi @sonalika-roy ,

I just wonder why the petclinic microservice size will be more than 200m?

**Comment by yilims** [comment]
@sonalika-roy : Did you run `mvn package/install` before run ` az containerapp create` to create container app from source code? The jar file size is very large and it's unnecessary to upload the jar file. pls run `mvn clean` and then run  ` az containerapp create` to create container app from source code
