### ISSUE TITLE
Opentelemetry metrics are not supported in AppInsights

### ISSUE THREAD

**Issue by seanli1988** [microsoft/azure-container-apps#1151]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

based on documentation metrics should be supported https://learn.microsoft.com/en-us/azure/container-apps/opentelemetry-agents?tabs=arm
![image](https://github.com/microsoft/azure-container-apps/assets/29985344/af9ee37d-cef1-4504-ab49-ff9e7dc85d66)
But this metrics are actually not supported when I tried to enable it.
![image](https://github.com/microsoft/azure-container-apps/assets/29985344/cd3f31cf-8cf9-4f3a-8e07-7893a7757eea)

**Comment by anthonychu** [comment]
@SophCarp

**Comment by PrzemyslawMalolepszy-TomTom** [comment]
You probably just forgot a backslash after ...traces true.
That is why zsh screams later "command not found"

**Comment by SophCarp** [comment]
![image](https://github.com/microsoft/azure-container-apps/assets/103968777/2a745410-3001-4bd7-a69d-58b9cd10485b)

Docs have been updated, thank you for reporting the issue.
https://learn.microsoft.com/en-us/azure/container-apps/opentelemetry-agents?tabs=arm
