### ISSUE TITLE
'ImagePullBackOff on legion' using Dedicated D4 workload profile on North Europe

### ISSUE THREAD

**Issue by tamoLo** [microsoft/azure-container-apps#1154]
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
On a fully privatise network, our container app container keep failing with 'ImagePullBackOff on legion' error. 

### Steps to reproduce
1. Deploy an Azure User Assigned Identity
2. Create a subnet for the ACR private endpoint
3. Deploy an ACR with no public access + private endpoint and private DNS zone matching record
4. Assign to this ACR the previously created UAI
5. Push a test image on this ACR
6. Give to the UAI the 'AcrPull' role on the ACR
7. Deploy an Azure Container Apps Environment with D4 workload profile + dedicated /27 subnet + internal load balancer + private DNS zone creation and record A creation
8. Create a container app with 'single' revision mode using the UAI to pull the previously pushed image

**Expected behavior** [What you expected to happen.]
Container running

**Actual behavior** [What actually happened.]
Container failing with 'ImagePullBackOff on legion' error

**Screenshots**         
![failed_acapng](https://github.com/microsoft/azure-container-apps/assets/112874103/aeccd427-dc53-4b53-b454-a8d19a1a6e3b)

### Additional context
- both subnets are on the same Vnet with no nsg rule blocking access from one to another
- deployment made with Terraform

**Comment by anrub** [comment]
Looks like a general broken feature in the service: https://github.com/microsoft/azure-container-apps/issues/1159 - for me, in westeurope it was working. In germanywestcentral, I also don't get it to work.

**Comment by tamoLo** [comment]
Issue due to a mistake in the image Dockerfile...
