### ISSUE TITLE
Container App Jobs terminating giving reason "Deleting Pod for Node Scale Down"

### ISSUE THREAD

**Issue by avneeshkumar** [microsoft/azure-container-apps#1157]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
In Container App Job, I am seeing few instances getting failed and the reason shown in System Logs as ScaleDown.
From what we understand Container App jobs are not supposed to scale down the running instance or long running jobs before the replica timeout has hit.

Resource ID - `/subscriptions/28f003ac-7b92-4fe2-8b92-121f85a95213/resourceGroups/rg-mm-apps-prod/providers/Microsoft.App/jobs/caj-mc-prdcr-prod`. 

### Steps to reproduce
On running the following query 
```
ContainerAppSystemLogs_CL
| where JobName_s == 'caj-mc-prdcr-prod'
| where  Reason_s =='ScaleDown'
| project time_t,Reason_s,Log_s,ExecutionName_s
```

I am seeing a lot of Instances of Container App Jobs which are getting terminated giving the reason 
`deleting pod for node scale down`

```
ContainerAppSystemLogs_CL
| where ExecutionName_s == 'caj-mc-prdcr-prod-gfxql'
```
**Expected behavior** [What you expected to happen.]
Executions should execute with success without the Pod being collected. 

**Actual behavior** [What actually happened.]
Pods are terminated in between or sometime before the pods can even start. 

**Screenshots**         
<img width="1323" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/3087417/55e0824b-6818-4879-9850-8c5cd86f6aae">

### Additional context
Can you help me understand why this is happening. 

Another example of this happening when pod didn't even start and was terminated giving the same reason.
```
ContainerAppSystemLogs_CL
| where ExecutionName_s == 'caj-mc-prdcr-prod-pmhsx'
```
![image](https://github.com/microsoft/azure-container-apps/assets/3087417/bd4e9340-cb88-44c7-8a18-a2151e814d0b)

**Comment by vinisoto** [comment]
When a node scale-down event occurs, all replicas running on the node will be evicted. The scale-down event; or any other event that impacts the underlying compute, doesn't wait for the existing pods to complete.

The job will then be re-scheduled on a different node according to its `replica retry limit` setting.

**Comment by avneeshkumar** [comment]
@vinisoto so now the problem is that we have a long running job, running for 4 5 hrs. And when node is scaled down this job is killed and terminated in middle. That's defeats the whole purpose of having the container app jobs... How do you suggest we go on handling this ? Should we use dedicated workload profile with the nodes always running ?

**Comment by avneeshkumar** [comment]
Closing down this ticket with reply from Microsoft Architecture Support. 
---
Firstly, Azure Container Apps is a serverless platform designed for running short-lived, scalable workloads. It is not optimized for long-running tasks or jobs that take several hours to complete. The platform is designed to automatically scale and recycle instances based on demand and resource utilization, which can cause issues for long-running tasks. This can be problematic for long-running web jobs like yours (3-4 hours).

To address your requirement of having your WebJobs run to completion without interruption, you may need to consider an alternative architecture or deployment model. Here are a few options you could explore:

    Azure Kubernetes Service (AKS): If you need to scale your WebJobs horizontally or want to leverage the benefits of containerization, you could consider deploying your application on Azure Kubernetes Service (AKS) . AKS provides a managed Kubernetes environment, allowing you to run your WebJobs as long-running containers or jobs within Kubernetes pods. With Kubernetes, you can configure resource requests and limits, set restart policies, and leverage features like job tracking and monitoring to ensure your WebJobs run to completion. As already stated, these services provide more control over the container lifecycle and allow you to configure long-running containers. However, you would need to manage the infrastructure and scaling yourself. ([What is Azure Kubernetes Service (AKS)? - Azure Kubernetes Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/aks/what-is-aks))

 

    Azure Batch: Azure Batch is a platform service designed for running large-scale parallel and high-performance computing (HPC) workloads . While it may be overkill for your specific use case, Azure Batch could be an option if you need to run multiple instances of your WebJobs concurrently or if you have other batch processing requirements. Azure Batch automatically scales compute resources and provides job scheduling and monitoring capabilities, which could be useful for your long-running WebJobs. ([Azure Batch documentation - Azure Batch | Microsoft Learn](https://learn.microsoft.com/en-us/azure/batch/))

 

    Azure Virtual Machines (VMs) or Azure Virtual Machine Scale Sets (VMSS): Running your WebJobs on an Azure Virtual Machine (VM) could be a suitable option. By deploying your application on a dedicated VM, you have more control over the runtime environment, and your WebJobs can run continuously without being interrupted by platform-imposed constraints . You can configure your WebJobs to run as Windows Services or use the Windows Task Scheduler to ensure they execute reliably and without interruption. ([Overview of virtual machines in Azure - Azure Virtual Machines | Microsoft Learn](https://learn.microsoft.com/en-us/azure/virtual-machines/overview))

 

    Azure Functions with Durable Functions: If your WebJobs can be broken down into smaller, orchestrated tasks, you could consider using Azure Functions with the Durable Functions extension. Durable Functions are designed to handle long-running, stateful workflows and can provide reliable execution and automatic checkpointing for long-running tasks. ([Durable Functions Overview - Azure | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=in-process%2Cnodejs-v3%2Cv1-model&pivots=csharp))

 

    Azure Web Apps with Webjobs: Another option could be to deploy your WebJobs in Azure Web Apps, which are designed to host longer-running workloads. You could configure your WebJobs to run continuously or on a schedule within the Web App environment. ([Run background tasks with WebJobs - Azure App Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/app-service/webjobs-create?tabs=windowscode))

 

Choosing the Right Approach:

The most suitable approach depends on your specific requirements, level of comfort with different platforms, and cost considerations. Here's a brief decision-making guide:

    Focus on Serverless and Scalability: Choose Azure Functions if you prioritize a serverless approach with automatic scaling for long-running jobs.
    Need More Control and Resource Management: opt for AKS if you require granular control over resource allocation and prefer managing your own Kubernetes cluster.
    Explore Optimization and Configuration: Investigate increasing instance limits or optimizing resource usage within Container Apps by simply scaling up to a different SKU/plan if those options are viable for your scenario.

Again, when choosing an alternative architecture, consider factors such as cost, scalability, management overhead, and integration with other Azure services. It's also important to evaluate the trade-offs between using a serverless platform like Azure Container Apps and managing your own infrastructure. Additionally, you may want to explore alternative architectures or patterns, such as breaking down your long-running jobs into smaller, more manageable tasks or leveraging message queues or event-driven architectures to distribute and orchestrate your workloads.

If you need further clarification of the information provided above, feel free to let me know and i will schedule a call with my technical lead to provide more technical depth on your inquiries.

Thank you for your patience and cooperation. I look forward to your response.
