### ISSUE TITLE
ACR image pull with User Assigned Managed Identity fails

### ISSUE THREAD

**Issue by jvalteren** [microsoft/azure-container-apps#1158]
### This issue is a: 
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Similar to issue #905. We are working with Terraform in an enterprise landing zone conforming to Cloud Adoption Framework. We've created a Container Registry in a production subscription and are attempting to pull images from it in acceptance, test and development subscriptions using a managed identity. We have followed documentation as far as we can see. However, since it's a landing zone with 2 hubs and firewalls (prd and acc/tst/dev are separate), the examples and related issues we have found are not applicable.

This is the error we are encountering:
```
│ Error: creating Container App (Subscription: "A"
│ Resource Group Name: "rg-***-acc-workload"
│ Container App Name: "ca-***-api"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: InvalidParameterValueInContainerTemplate: The following field(s) are either invalid or missing. Field 'template.containers.***-api.image' is invalid with details: 'Invalid value: "cr***.azurecr.io/***/***-api:initial": unable to pull image using Managed identity /subscriptions/P/resourceGroups/rg-***-prd-workload/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-prd-acr for registry cr***.azurecr.io';.
```

Even going across subscriptions within the same hub results in this error. When creating a dedicated Container Registry in the same subscription, this issue does not occur.

### Steps to reproduce
Too many to describe. Landing zone architecture with 2 hubs and multiple subscriptions is necessary.

**Expected behavior** 
Successful pulling of image from container registry.

**Actual behavior**
Non-descriptive error message: 'unable to pull image using Managed identity'.

**Screenshots**         

### Additional context
Using Terraform with AzureRM provider.

**Comment by vturecek** [comment]
@jvalteren does your ACR allow ARM audience tokens? https://learn.microsoft.com/en-us/azure/container-apps/managed-identity-image-pull?tabs=azure-cli&pivots=azure-portal#prerequisites

**Comment by jvalteren** [comment]
Hi @vturecek, thanks for your response. The issue has since been resolved. It had to do with the networking between the Production and Acceptance/Test/Development hubs not being correctly configured, so the Acceptance ACA's couldn't reach the ACR in Production. The setup was the first fully Cloud-native Azure setup that was implemented (previous were hybrid), which caused the team to overlook some crucial network configuration between the 2 hubs.

For completeness, the target ACR in Production shows that ARM audience is enabled.

We can now successfully pull images in Acceptance ACA's from the Production ACR.
