### ISSUE TITLE
Possibility to set Request Size (Dapr: --http-max-request-size flag)

### ISSUE THREAD

**Issue by XavierGeerinck** [microsoft/azure-container-apps#116]
Is there a way to set the `--http-max-request-size` flag? I got an app and am sadly enough triggering the body too large error

**Comment by kendallroden** [comment]
We are investigating and will report back

**Comment by sergiibielskyi** [comment]
Hey. Any updates on it?

**Comment by sergiibielskyi** [comment]
I think it would be great to add this option/parameter as annotation to dapr settings
dapr: {
        enabled: true
        appPort: 80
        appId: 'daprapp'
        http-max-request-size: 16
      }

**Comment by XavierGeerinck** [comment]
Any update on this? I am missing it as well for a production app (always receiving `('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))` now)

**Comment by lewismartin512** [comment]
Any updates? We are blocked from moving forward until this flag becomes available.

**Comment by sahibble** [comment]
This feature is also crucial for me to move forward with container apps. The 4MB limit is very restricting.

**Comment by kendallroden** [comment]
Thanks for letting us know I am checking with engineering

**Comment by dale-personal** [comment]
Any updates?  I will add that the dapr error for this is not properly surfaced in the logs. 

Container apps log the following error:
System.Net.Http.HttpRequestException: An error occurred while sending the request.
2022-09-21T12:26:38.938415931Z        ---> System.IO.IOException: The response ended prematurely.

while debugging locally, i see the more helpful dapr error:
Dapr.DaprApiException: error invoke actor method: body size exceeds the given limit

**Comment by sergiibielskyi** [comment]
it works if you change the extension by using the command like this one
az containerapp dapr enable -n containerapp -g "$NAME_RG" --dapr-app-id daprId --dapr-http-max-request-size 16

**Comment by dale-personal** [comment]
That essentially is the command i am running:
az containerapp dapr enable -n $name -g $resourceGroup --dapr-app-id api --dapr-app-port 80 --dapr-app-protocol http --dapr-http-max-request-size 32

It shows up in the json settings if you change the API version to 2022-06-01-preview but it does not have an effect on the container - I still receive the error message with requests larger than 4MB.

Presumably because this is in the API preview and not actually implemented in the deployed containers yet?

**Comment by sergiibielskyi** [comment]
that works if you use the right template (not a preview one). Just tested on my container apps.

**Comment by dale-personal** [comment]
Can you elaborate a bit on what you mean by "right template"?

Here is what i am using:
resource api 'Microsoft.App/containerApps@2022-03-01' = { ...

This is not working (for me at least).  perhaps i will try setting this to @2022-06-01-preview and see if that works.

**Comment by kendallroden** [comment]
The feature is rolling out across CLI and portal hence why they are not in line yet

**Comment by kendallroden** [comment]
closing due to availability
