### ISSUE TITLE
Misleading error for failed deployments

### ISSUE THREAD

**Issue by alexwolfmsft** [microsoft/azure-container-apps#1162]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Deployments fail with a message "NoRegisteredProviderFound: No registered resource provider found for location 'westus2' and API version '2024-02-02-preview' for type 'managedEnvironments'." 

However, the list of supported regions and APIs then includes the items it says weren't supported.

![image](https://github.com/microsoft/azure-container-apps/assets/93200798/35cb3489-30c0-42e2-8ab5-1b230d2b27e5)

### Steps to reproduce

Run the dotnet new aspire-starter command, then use azd up to deploy - tried on multiple regions (eastus, eastus2, westus2)

**Expected behavior**

Should deploy successfully.

**Actual behavior** 

Deployment failed.

**Comment by chinadragon0515** [comment]
@alexwolfmsft the issue should have been fixed, let us know if you still see issues. thanks
