### ISSUE TITLE
containerapp job ContainerTerminated/ ContainerCreateFailure

### ISSUE THREAD

**Issue by BAndersenRP** [microsoft/azure-container-apps#1163]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
- I am reusing a working containerapp docker image for a new containerapp job and overriding the command to echo test

- I get a single log which contains these reason codes: ContainerTerminated/ ContainerCreateFailure (No console logs as per container create failure) with no additional details

- Execution remains running until timeout

### Additional context
I am new to azure container apps

**Comment by avneeshkumar** [comment]
Can you paste your azure System logs to further understand the issue ?

**Comment by BAndersenRP** [comment]
The solution to my issue was supplying the --command with space separated values and not a comma seperated value. (I'm not sure where I got the idea to use a csv)

Closing this issue

**Comment by rijulg** [comment]
the naming of variables in the resource do not help. There are `commands` and `args` that map to `entrypoint` and `cmd` override respectively. Has been a massive headscratcher.
