### ISSUE TITLE
Dapr initTimeout configuration

### ISSUE THREAD

**Issue by k-schneider** [microsoft/azure-container-apps#117]
Is it possible to configure this for container apps?  I'm trying to use Cosmo DB for my dapr actor state store and the suggested value is 5m.  Discussed here:

https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-azure-cosmosdb/#best-practices-for-production-use

I've attempted to configure this value via a bicep template but I'm warned that the property does not exist:

```
resource containerApp 'Microsoft.Web/containerApps@2021-03-01' = {
  ...
  template: {
    ...
    dapr: {
      components: [
        {
          name: 'statestore'
          type: 'state.azure.cosmosdb'
          version: 'v1'
          initTimeout: '5m'
          metadata: [
            ...
          ]
       }
    }
  }
}
```

When deploying the bicep template the warning I receive is:

`The property "initTimeout" is not allowed on objects of type "DaprComponent".`

The majority of the time it seems like my container fails to correctly start the dapr sidecar and any attempts to invoke actors results in:

`Connection refused (127.0.0.1:3500)`

Any guidance would be appreciated.

**Comment by kendallroden** [comment]
Thanks for reporting @k-schneider I will look into this and get back to you

**Comment by kendallroden** [comment]
initTimeout is configurable via dapr components at the environment level @k-schneider

**Comment by k-schneider** [comment]
This is great, thanks!
