### ISSUE TITLE
JVM not working as expected in NorwayEast

### ISSUE THREAD

**Issue by mortenf1984** [microsoft/azure-container-apps#1178]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am unable to get JVM autoscaling to work, I am not seeing the log messages that I was expecting indicating that my container with Java have activated the JVM Automemory [#1094](https://github.com/microsoft/azure-container-apps/issues/1094)
Followed the documentation, and I fulfill all the criterias for this

### Steps to reproduce
1. create a Environment in NorwayEast
2. create a Java Container App
3. verify that it does not provide the "Disabling jvm memory fitting" or "Calculated JVM Memory Configuration" in logstream

**Expected behavior** [What you expected to happen.]
I expected to see "Calculated JVM Memory Configuration"

**Actual behavior** [What actually happened.]
No change from before JVM Memmory Fit was added

**Comment by bowen5** [comment]
Hey @mortenf1984 , would you please further share how did you "create Java Container App", for example the CLI command you used?

One thing to note that, as the doc https://learn.microsoft.com/en-us/azure/container-apps/java-memory-fit?tabs=create described, currently the "memory fitting" feature supports deploying from source code or JAR file. It doesn't support when you already containerized your application and directly deploy the container image.
