### ISSUE TITLE
Azure Container apps Filters Custom Response Headers

### ISSUE THREAD

**Issue by akmani-w** [microsoft/azure-container-apps#1181]
> Please provide us with the following information:
> ---------------------------------------------------------------
Azure Container apps Filters Custom Headers

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduce
1. Deploy app which sends custom header
2. see header from localhost url and container apps url

**Expected behavior** [What you expected to happen.]
- i want the header to be present in AZURE container aps

**Actual behavior** [What actually happened.]
- The header is missing 

**Screenshots**         
<img width="917" alt="Screenshot 2024-05-28 at 4 26 58 PM" src="https://github.com/microsoft/azure-container-apps/assets/169121137/889a71c8-d446-4771-a704-1084bce4e3aa">

**Comment by akmani-w** [comment]
@vturecek Can I have any document on how request / response headers are filtered ?

**Comment by thammermann** [comment]
Iam facing the same problem. On localhost the header are included in the request and as soon as I deploy on Azure App Container, the headers are removed on the receiving server
