### ISSUE TITLE
Is ContainerApp team out there?

### ISSUE THREAD

**Issue by jsheetzmt** [microsoft/azure-container-apps#1184]
Wondering if the ContainerApp team is out there... looking through GitHub, many issues still need triage. Container app discord is no better even though it is the "preferred" platform for engaging with the team. Just wondering what is going on.

**Comment by anthonychu** [comment]
Sorry, we were busy in the last few weeks but that's no excuse. We need to do better here. Will work with the team to work through these over the next week. Thanks for your patience.

**Comment by jedjohan** [comment]
agreed. "betting" a lot on containerapps and now I am afraid all the future MS investment goes into Automatic AKS haha

Anyway, good to hear you plan to be a bit more focused, thanks
