### ISSUE TITLE
Configure CORS for api requests

### ISSUE THREAD

**Issue by HWouters** [microsoft/azure-container-apps#119]
Is CORS support for api requests like app service on the roadmap?

**Comment by kendallroden** [comment]
We will be providing CORS support in Container Apps and will provide additional details in the future

**Comment by Alec13355** [comment]
@HWouters, @ahmelsayed, or @kendallroden is there a timeline on this or a workaround until it's fully implemented?

**Comment by JamesDawson** [comment]
We are hitting this too, whilst trying to migrate a number of APIs from Azure Functions to Container Apps, which are consumed by an Azure Static Web App.

Our migration effort is blocked right now, so it would be useful to get some clarity on the timeline for this roadmap feature?

**Comment by HWouters** [comment]
@JamesDawson @Alec13355, with Azure Container Apps it's much easier to add CORS middlewear (in comparison with Azure Functions). At least it's a workaround and this missing CORS feature doesn't need to be a blocker.

**Comment by cannehag** [comment]
> @JamesDawson @Alec13355, with Azure Container Apps it's much easier to add CORS middlewear (in comparison with Azure Functions). At least it's a workaround and this missing CORS feature doesn't need to be a blocker.

I don't see how this helps since I do have that middleware configured but the headers are not returned. I think the container app responds before it hits my api if it's a CORS options request

**Comment by torosent** [comment]
CORS is now available in ARM/Bicep
ref https://github.com/microsoft/azure-container-apps/issues/359
