### ISSUE TITLE
Unable to use Azure Container Apps Easy Auth with Entra ID External Identities 

### ISSUE THREAD

**Issue by mvrius** [microsoft/azure-container-apps#1200]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a:
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

It seems that Entra ID External Identities do not work as expected with Easy Auth

### Steps to reproduce
1. Create an Entra ID tenant with External Identities
2. Configure it with Easy Auth

**Expected behavior**

Expect this to work the same way Entra B2C auth works.

**Actual behavior**

{
    "code": 401,
    "message": "An error of type 'invalid_request' occurred during the login process: 'AADSTS500207: The account type can't be used for the resource you're trying to access. Trace ID: 0915ea63-b52a-4a2a-8d32-b56abf6e0000 Correlation ID: 609967fe-e97c-419d-9907-3430fd69c0af Timestamp: 2024-06-18 08:01:18Z'"
}

**Comment by njuCZ** [comment]
Hi @mvrius have you followed this guide?
https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service?toc=%2Fentra%2Fexternal-id%2Ftoc.json&bc=%2Fentra%2Fexternal-id%2Fbreadcrumb%2Ftoc.json&tabs=external-configuration
Though it's a guide for app service, it should also work for container app

**Comment by aitrailblazer** [comment]
it is not working

**Comment by mvrius** [comment]
@anthonychu @njuCZ verified and this is not working. Same error as in bug description.

**Comment by aitrailblazer** [comment]
This is the only bug preventing using Aspire. There is a need of solution and dedicated documentation for this!

**Comment by BrianPinsard** [comment]
We had the exact same error, while playing around with the MSAL sample authentication apps we noticed the issuer url in the response was different than expected.

While setting up the identity provider for the container app we had to provide the issuer url in the following format:
https://{{tenant-name}}.ciamlogin.com/{{tenant-id}}/v2.0 OR https://{{tenant-id}}.ciamlogin.com/{{tenant-id}}/v2.0
