### ISSUE TITLE
mTLS incompatible with .NET Aspire Dashboard

### ISSUE THREAD

**Issue by onionhammer** [microsoft/azure-container-apps#1203]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When you enable '.NET Aspire Dashboard' and 'mTLS', the .NET aspire dashboard's structured logs, traces, and metrics pages will be blank. The 'console' page continues to work.

### Steps to reproduce
1. Deploy a .NET aspire app
2. Enable mTLS

**Expected behavior** [What you expected to happen.]
The three aforementioned pages should work

**Actual behavior** [What actually happened.]
The structured logs, traces, and metrics pages do not work

**Screenshots**

**Comment by snehapar9** [comment]
Thanks for reporting this issue @onionhammer! Can you please confirm if you're still seeing this issue if you enable mTLS and Aspire?
Can you please email your environment name and subscription Id to acasupport@microsoft.com? We will take a look.

**Comment by onionhammer** [comment]
I tried to check it again this morning, was getting a series of 403s (I have contributor role assigned diirectly), now I'm getting an internal server error. Will email the info shortly

**Comment by snehapar9** [comment]
Thanks @onionhammer! Looks like the 403s you're seeing is a different issue un-related to mTLS. Does it throw 403s on re-tries also?

**Comment by onionhammer** [comment]
> Thanks @onionhammer! Looks like the 403s you're seeing is a different issue un-related to mTLS. Does it throw 403s on re-tries also?
> 
> 

I was trying to test out mTLS per your request, but this other issue has now prevented me from accessing the dashboard at all

**Comment by onionhammer** [comment]
Okay, 403 resolved itself this morning so I was able to test re-enabling mTLS, now I see a black screen with just this text:

"upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: delayed connect error: 111"

**Comment by snehapar9** [comment]
@onionhammer Thanks for checking! The error you're seeing should be temporary during the shift between the plaintext endpoint and the encrypted one.

The root cause for missing OTLP data you were seeing earlier is related to [this issue](https://github.com/microsoft/azure-container-apps/issues/1213#issuecomment-2195898553).
Enabling mTLS should have no impact on accessing the Aspire dashboard.

**Comment by onionhammer** [comment]
"Should" being the operative word, I'm guessing? How long is 'temporary'? I'll let it sit overnight and see if it eventually works

**Comment by onionhammer** [comment]
This appears to be resolved now
