### ISSUE TITLE
Container App not starting when same queue with different name is being used

### ISSUE THREAD

**Issue by XavierGeerinck** [microsoft/azure-container-apps#121]
My container app won't start correctly when I have 2 applications using the same queue but a different queue name.

Setup:
* Azure Service Bus
* 2 Queues on the Service Bus
* 2 Container Apps, referencing the same Service Bus
  * They reference the same service bus
  * They each use a different queue name
  * They each have Dapr enabled
  * They each have auto scaling enabled with 0 min replicas and 1 max replica

> Note: everything is "unique" in the sense that I have added unique suffixes so that the Dapr binding names are unique, the scaling rules are unique, ... for each container app

After deploying the first time, it appears that the container app automatically starts, when I test my application it works.

When I now test my application ~1h later it appears that only one of the container apps wants to start but the other doesn't

The only thing I can think of is that somehow there is only one unique listener per connection string allowed for the KEDA autoscaling system internally?

**Comment by XavierGeerinck** [comment]
Oh, Tom is working on this? Sweet!

Awesome to hear @kendallroden! Can't wait for the stable release :) in the meantime I decided to switch back to Container Apps for the system

**Comment by kendallroden** [comment]
I tagged tom because he would know if it is a potential keda limitiation. Tagging @ahmelsayed as well to investigate.

**Comment by tomkerkhove** [comment]
As far as I see it it comes down to this - Two separate apps using different queues.

KEDA only scales based on queue depth, it doesn't change anything related to the workloads themselves so I doubt that this is related to KEDA.

> The only thing I can think of is that somehow there is only one unique listener per connection string allowed for the KEDA autoscaling system internally?

We don't enforce anything so should be good t ogo here

**Comment by tomkerkhove** [comment]
>  ~1h later it appears that only one of the container apps wants to start but the other doesn't

Can you talk more about that? Are you saying it's having issues and throwing exceptions on startup then?

**Comment by XavierGeerinck** [comment]
Hi Tom! So on startup everything works (it seems on initial deployment that the app starts?). Then it scales down to 0 (so nothing working) and when I submit items to each of the queues (so 1 item on each of them) only 1 starts up the other stays down

when I go to 5 items (I put the queue length on 5) it still doesn’t change anything

**Comment by tomkerkhove** [comment]
Do you have an ARM template that you can share or so? Make sure to verify the connection strings because by default it scales to 0 if it has auth issues in KEDA (which we are improving to have more control).

**Comment by XavierGeerinck** [comment]
Hi @tomkerkhove so the app works on one of them, so the connection string details are correct (they both use the same one, just a unique name for the Dapr bindings and a different queue name), but it's the root key for the queue so I can access both queues.

Also, it's randomly switching between the 2. On one deploy, it works on one queue, on another on the other...

Tbh, the only thing I can think of is:
* KEDA doesn't work for re-using the same connection string but 2 different queues at the same time (unlikely?)
* Container Apps has an issue in saving the connection details and only creates one KEDA binding per connection string?

Thoughts?

**Comment by kendallroden** [comment]
We are investigating and will report back
