### ISSUE TITLE
Event-triggered container App Jobs running in Consumption workload profile time out, fail to start and miss console logs

### ISSUE THREAD

**Issue by vinisoto** [microsoft/azure-container-apps#1211]
Starting on 6/19 customers using Event-triggered Container Apps Jobs started experiencing failures to execute, timeouts and missing console logs.
 
We have identified a regression that was introduced in the most recent platform update. This regression was reverted on 6/22 6:05 AM UTC for all impacted Container Apps Environments.
 
This regression did not impact Container Apps environments in Consumption-only plans or in Dedicated workload profiles.
 
If you are impacted by this regression and still experiencing issues, please raise a support ticket through the Azure Portal.

**Comment by robrennie** [comment]
@vinisoto - This did not fix #1206. I just ran a container app job, system log says everything was fine, no Console Log. In fact, ContainerAppConsoleLogs_CL still isn't even created.

'where' operator: Failed to resolve table or column expression named 'ContainerAppConsoleLogs_CL'
Request id: 14fab04f-1582-4890-8c99-93f0ef01319a

**Comment by ttq-ak** [comment]
Has there been another regression causing this? Starting today we're seeing this exact situation with our azure pipelines triggered agents.
They spin up, fail with no console logs at all.

Switching to a dedicated workload profile resolves the issue, it only seems to happen on a consumption workload profile 
![image](https://github.com/microsoft/azure-container-apps/assets/83716750/798b3b39-6b20-474d-9998-d564e202faef)

**Comment by ovokpus** [comment]
What is the lasting solution that Microsoft has done for this issue?

**Comment by robrennie** [comment]
@ovokpus - it was a while ago, but the solution is to not use the consumption model. I think that was being deprecated anyways. But again, it's been a while so I going off memory.
