### ISSUE TITLE
Aspire Dashboard 'freezes' after 10,000 trace entries

### ISSUE THREAD

**Issue by onionhammer** [microsoft/azure-container-apps#1213]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
After getting to 10,000 entries, the aspire dashboard ceases to be useful

### Steps to reproduce
1. Enable aspire dashboard
2. Log traces to it

**Expected behavior** [What you expected to happen.]
Old logs should disappear

**Actual behavior** [What actually happened.]
New logs never appear

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/969938/17362df9-090a-4afe-8ad3-dfc5996848eb)

**Comment by snehapar9** [comment]
Thanks for opening this issue @onionhammer! 
I was able to reproduce what you're seeing in your screenshot by curling the container app endpoint 15,000 times. However, my observation is traces for 15.000 records are populated but the `total results found` remains at 10,000. It does not seem to increase beyond that even though more traces are occurring. Do you have the same observation.

 
![image](https://github.com/microsoft/azure-container-apps/assets/108305436/6ce302a0-adf7-4795-bd4c-e230004f4eb1)

**Comment by onionhammer** [comment]
No, my dashboard traces have since emptied and now no new traces are appearing at all

**Comment by snehapar9** [comment]
@onionhammer do you mind sharing your sub id/managed cluster name to acasupport@microsoft.com? We will take a look.

**Comment by onionhammer** [comment]
> @onionhammer do you mind sharing your sub id/managed cluster name to [acasupport@microsoft.com](mailto:acasupport@microsoft.com)? We will take a look.

Thanks, sent an email

**Comment by snehapar9** [comment]
Thanks @onionhammer for providing us this information! We have identified the root cause of the issue. 

There was an issue with the otlp authentication because of a race condition while setting the otlp api key. So, even though traces were being transmitted they were not showing up on the dashboard. 
I performed temporary mitigation steps on your cluster. Can you please confirm you can see traces now?

We will work on getting a permanent fix out soon. Thanks again for reporting this. We appreciate it! :)

**Comment by onionhammer** [comment]
@snehapar9 yep, things are showing again. Thanks!

**Comment by onionhammer** [comment]
This appears to be resolved now
