### ISSUE TITLE
Feature Request: Smaller/Focused CI/CD Tooling (Azure CLI size is unreasonable for CI/CD usage)

### ISSUE THREAD

**Issue by mikeball** [microsoft/azure-container-apps#1218]
**Is your feature request related to a problem? Please describe**.  
The Azure CLI is far too large for reasonable use in CI/CD. It's size makes pipelines that update revisions slow. The size seems a little silly given we need to make I think 2 http calls. As I was installing azure cli I see it includes things like icon sets, etc... it's wasteful and slow to load stuff like that every time a build pipeline. Here's the command's I'm actually using.
```
az login --service-principal --tenant $AZAD_TENANT --username $AZAD_USERNAME --password $AZAD_PASSWORD
az containerapp update -n my-app-name -g my-resource-group --image $IMAGENAME
``` 

**Describe the solution you'd like**.    
I would like a small focused ACA specific utility for CI/CD pipeline usage that is space and resource efficient.

**Describe alternatives you've considered**.   
I looked at Azure rest endpoints and am considering building an app that uses API directly, and am curious if others might also have same needs, or if there is already an open tool out there somewhere.

https://learn.microsoft.com/en-us/rest/api/containerapps/container-apps/update?view=rest-containerapps-2024-03-01&tabs=HTTP

**Comment by simonjj** [comment]
Mike,

There's a official Github Action which gets configured automatically via the CI/CD workflow in the portal and CLI. Alternatively you can also do it manually. Official docs are available here: https://github.com/marketplace/actions/azure-container-apps-build-and-deploy. Source is available at: https://github.com/Azure/container-apps-deploy-action

Hope this helps? This uses the CLI behind the scenes but the heavy lifting has already been done for you.

**Comment by mikeball** [comment]
> Hope this helps? This uses the CLI behind the scenes but the heavy lifting has already been done for you.

Unfortunately not much. We are using bitbucket pipelines, and sort of misses the core of the problem which avoiding the 1GB+ dependency of the azure-cli requirement to update a revision.

**Comment by ahmelsayed** [comment]
You could do

```bash
TOKEN=$(curl https://login.microsoftonline.com/${AZAD_TENANT}/oauth2/v2.0/token \
  -F "grant_type=client_credentials" \
  -F "scope=https://management.core.windows.net//.default" \
  -F "client_id=${AZAD_USERNAME}" \
  -F "client_secret=${AZAD_PASSWORD}" \
  | jq -r ".access_token")

curl -XPATCH https://management.azure.com/${APP_ID}?api-version=2024-03-01 \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"properties\": {\"template\": {\"containers\": [{\"name\": \"some-name\", \"image\": \"${IMAGENAME}\"}]}}}"
```

Though you wanna be careful as this will patch your entire `.properties.template.container` array, so you might wanna do a GET before the PATCH (or PUT) to make sure to set any other properties you might need there like resources, name, etc. 

The PATCH returns a 202, so you might need to follow the response `Location` header if you need to know when the patch is complete. You might also need to poll the revision status if you need to wait for that.

**Comment by mikeball** [comment]
Thanks @ahmelsayed! I actually have already built on a little golang utility mimic the azure cli to do those same http calls and it's working excellent, was considering sharing. Using curl might be an even better idea and will give it a try, need to see if jq is available in ci/cd. This might be the best suggestion for ci/cd which needs to update revision with new image.

**Comment by mikeball** [comment]
With a small change to the scope from `https://management.core.windows.net//.default` to `https://management.azure.com//.default`, I was able to acquire an access token like this
``` 
AZAD_TOKEN=$(curl https://login.microsoftonline.com/${AZAD_TENANT}/oauth2/v2.0/token \
  -F "grant_type=client_credentials" \
  -F "scope=https://management.azure.com//.default" \
  -F "client_id=${AZAD_USERNAME}" \
  -F "client_secret=${AZAD_PASSWORD}" \
  | jq -r ".access_token")
```
and then issue an ACA update like this
```
curl -XPATCH $AZAPI_ENDPOINT \
  -H "Authorization: Bearer ${AZAD_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"properties\": {\"template\": {\"containers\": [{\"name\": \"$ACA_APPNAME\", \"image\": \"${IMAGENAME}\"}]}}}"
```
This works great and it doesn't get any more lightweight than an already installed curl!

However, I also feel we should be extracting the location header out, then watch/poll for the deploy to succeed in cases where the app won't start successfully... but that is something that feels a too involved for a bash script so may use python/nushell to try.

**Comment by mikeball** [comment]
I wouldn't necessarily consider this issue resolved. There is still a need to be better tooling for azure container apps and using the azure cli is complete overkill. The proposed curl solution while nice, only submits an update revision request, ci/cd jobs still need to watch/check for success of the revision deploy which could fail for a number of reasons.
