### ISSUE TITLE
Error deploying new revision 

### ISSUE THREAD

**Issue by fritzfs** [microsoft/azure-container-apps#1219]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Today I am getting errors while deploying new revisions on all three Azure Container App environments. I successfully built a new docker image (small changes, the docker image is working correctly) and deployed it on ACA using AZ CLI inside the GitHub workflow pipeline.  Revision stays in status "activating" for quite some time and then it moves to "Activation failed" with running status details "Deployment Progress Deadline Exceeded. 0/1 replicas ready." 

Docker image is available on MS ACR , authentication is Managed Identity, identity is System assigned. Health probes are disabled and volume mounts are not added. 

### Additional context
This happened both on CLI and Portal. Initially with CLI and I tried restarting revision using Portal.

**Comment by fritzfs** [comment]
I saw this change by MS in Activity Log:

![Screenshot 2024-07-02 at 14 13 03](https://github.com/microsoft/azure-container-apps/assets/802531/f2b43331-715a-43a7-9bf3-a09346f70240)

So I configured liveness, readiness and startup probe.

These are logs from system logs:

![Screenshot 2024-07-02 at 16 39 12](https://github.com/microsoft/azure-container-apps/assets/802531/c711e1d6-896a-402c-b289-09c02330842d)

**Comment by simonjj** [comment]
Thanks for contacting us @fritzfs. Personally seen similar things when using large images. Could you try to make a change to the revision which causes a restart of the container? Adding an ENV var or changing replica settings for example would do that. Let me know if the container comes up then.

**Comment by fritzfs** [comment]
Thanks for jumping in!
Unfortunately, this docker image isn't that big - around 1.2 GB. 

Yes, I added small changes to re-trigger the new CI/CD pipeline, it did not help. I also used the Restart button on ContainerApp inside Azure Portal for quicker testing ... 

I also saw something else. Inside my Azure ContainerApp Env, my job (that uses the same docker image as scheduled job), failed every time since 28.06.  On three different ACA envs. Without any changes on our side that whole week.

![Screenshot 2024-07-02 at 17 19 22](https://github.com/microsoft/azure-container-apps/assets/802531/9f2fc005-bf2a-47f8-aa4d-d078899edd8b)

My console log is empty, but system log gets these error records after successful docker pull ...

<img width="918" alt="Screenshot 2024-07-02 at 19 06 11" src="https://github.com/microsoft/azure-container-apps/assets/802531/c84445ca-2440-4e4e-85e3-95e1598b05c7">

**Comment by fritzfs** [comment]
@simonjj note that I had dozens of job executions in status Running. I stopped them all with 

`az containerapp job stop -g Dev_Lab_Resource_Group -n dev-lab-app-job --job-execution-name dev-lab-app-job-ID`

I also deleted ACA Job for the moment. Tried again restarting the ACA, still nothing. Even stopped ACA app, gave it couple of minutes before starting ACA app again.

**Comment by fritzfs** [comment]
Got new message in system logs after couple of restarts. How does it mean - no space left? Where do I check that on ACA ENV? :-) 

![Screenshot 2024-07-02 at 20 57 35](https://github.com/microsoft/azure-container-apps/assets/802531/6e0a0eea-842b-40d5-aa6d-000ea7d78575)

**Comment by fritzfs** [comment]
If I create a new Workload profile with dedicated machines on ACA ENV and switch ACA app to that, revision can successfully complete. I switched back to my Workload profile Consumption (default) and again it's stuck ...

**Comment by simonjj** [comment]
@fritzfs let me take a look at this environment. Stay tuned.

**Comment by fritzfs** [comment]
@simonjj thank you. If it helps, since yesterday, I see only these messages in system log:

![Screenshot 2024-07-03 at 08 10 54](https://github.com/microsoft/azure-container-apps/assets/802531/19a7be2c-240d-4c73-8ea1-f19687d2e489)

Context:
- that app is trying to run under Consumption plan
- that app has two containers - one normal and one init container
- normal has 3 vcpu and 6 gb mem while init has 0.5 vcpu and 1 gb mem
- scale min replicas 1 and max replicas 3

**Comment by fritzfs** [comment]
@simonjj it seems that you or someone else from Microsoft cleaned the disk space on Consumption machines. My ACA job started to work early in the morning. I also can now deploy new revisions. 
How can I get more information about what happened? Because this "downtime" lasted around 5 days. 

Thank you!

![Screenshot 2024-07-03 at 11 07 47](https://github.com/microsoft/azure-container-apps/assets/802531/8695ddd3-dbb1-49bb-9335-4496c1fae2bc)

**Comment by simonjj** [comment]
@fritzfs Jobs get allocated to random nodes on every execution. This last execution might just have been allocated to a working node whereas the other ones to non-working ones. We are continuing to investigate this and will report back.

**Comment by chinadragon0515** [comment]
This is caused by an incorrect configuration in that region and we have reverted the incorrect change, the service is recovered now. thanks
