### ISSUE TITLE
Cannot create more than 10 containerapp environment in a subscription

### ISSUE THREAD

**Issue by devopssaurav** [microsoft/azure-container-apps#1226]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I was trying to create a new containerapp, which prompted me to create a new environment for the same but I am getting this error:

Validation failed for a resource. Check 'Error.Details[0]' for more information. (Code: ValidationForResourceFailed)
The subscription 'b493246a-acdc-43bf-b892-46c3eb850a75' cannot have more than 10 Container App Environments. For more information, visit: https://go.microsoft.com/fwlink/?linkid=2208872 (Code: MaxNumberOfGlobalEnvironmentsInSubExceeded)

I don't see any resource quota limits which says I cannot create more that 10 containerapp environment for subscription.
(see screenshot attached.)

### Steps to reproduce
1. Go to containerapp and create new containerapp
2. In containerapp environment choose new environment and fill up the form.
3. Complete setup to Review & Create.

**Expected behavior** [What you expected to happen.]
New container app with new env should have been created.
**Actual behavior** [What actually happened.]
Validation failed for a resource. Check 'Error.Details[0]' for more information. (Code: ValidationForResourceFailed)
The subscription 'b493246a-acdc-43bf-b892-46c3eb850a75' cannot have more than 10 Container App Environments. For more information, visit: https://go.microsoft.com/fwlink/?linkid=2208872 (Code: MaxNumberOfGlobalEnvironmentsInSubExceeded)
**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/106005494/03954073-03aa-459c-9d32-99b40ea8d63f)
![image](https://github.com/microsoft/azure-container-apps/assets/106005494/54f8a449-5651-4302-9d59-e03ebd92db1c)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by simonjj** [comment]
@devopssaurav thanks for reaching out. We have several quotas around environments. There are regional (shown in the screenshot) and global ones. It's possible that the global quota was not raised when your regional ones were raised. Can you please open a support ticket to make sure to have your global quota raised from the current limit to 150 (based on the numbers of the regional ones).

**Comment by Dionmm** [comment]
This is very confusing, the docs need updated to clarify the fact there even is a "global" quota for this. I bumped into this on a brand new sub and there is a absolutely zero feedback on the limits in either the UI or the error message itself

**Comment by simonjj** [comment]
We just updated the quota docs to address this. Please let your Microsoft support tech know that the global quota needs to be raised alongside and regional quotas. Closing this out for now.
