### ISSUE TITLE
az containerapp update --yaml  fails with scale rule with user-assigned identity

### ISSUE THREAD

**Issue by zecloud** [microsoft/azure-container-apps#1229]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When using az containerapp update --yaml with a yaml with user-assigned identity in a scale rule it gives you the following message

(ContainerAppScaleRuleMissingAuth) Scale rule 'azure-queue-rule' requires authentication but has a missing or invalid 'auth' or 'identity' property.

### Steps to reproduce
Create a container app with a scale rule with user assigned identity, save yaml with az containerapp show --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --output yaml > app.yaml
Edit yaml to make a change like mount a volume.
Try to update the container app with the updated yaml with az containerapp update --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --yaml app.yaml --output table
It seems to have the same behavior using the portal too
**Expected behavior** [What you expected to happen.]
Yaml should work with user assigned identity in scaling rule
**Actual behavior** [What actually happened.]

**Comment by Greedygre** [comment]
Hi @zecloud 

May I ask what is the version you are using? Can you show me the result of the `az version` command?

Currently we don't support scale rule identity with `--yaml` yet, for workaround, you can use following command with version `>= 0.3.53`:
`az containerapp update -g {resource_group} -n {ca_name} --user-assigned {user_identity_name1} --scale-rule-name azure-queue --scale-rule-type azure-queue --scale-rule-metadata "accountName=account1" "queueName=queue1" "queueLength=1" --scale-rule-identity {user_identity_name1}`

Thanks

**Comment by zecloud** [comment]
Hi @Greedygre,

Thanks for your answer.
My  az version result
{
  "azure-cli": "2.62.0",
  "azure-cli-core": "2.62.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "containerapp": "0.3.53"
  }
}

For my scenario i saved the yaml with  "auth:"  instead of identity in the scaling rule. and then applied again az containerapp update with the identity, but as i thought it was a weird workaround . i opened the issue. 
Best regards

**Comment by Greedygre** [comment]
Hi @zecloud 

 I checked the log,  in the request body it not contains `auth`, You can repro the error with `--debug` and check.
```
{
  "name": "azure-queue-rule",
  "azureQueue": {
    "queueName": "halloaiavatarvideos",
    "queueLength": 5
  }
}
```

Can you show me the content relate to azure-queue-rule in your yaml file? Thanks

**Comment by Greedygre** [comment]
Hi @zecloud 

If your want to use auth in yaml, we support that.
But I check the log, in the request body not include the `auth`, you can confirm it with `--debug` in the command:

{
  "name": "azure-queue-rule",
  "azureQueue": {
    "queueName": "halloaiavatarvideos",
    "queueLength": 5
  }
}

I want to know what it the content in your YAML file relate to **azureQueue**.
Can you show me?

Please set the content like follwoing:
```
      rules:
      - azureQueue:
          queueLength: 5
          queueName: halloaiavatarvideos
          auth:
          - secretRef: {your-secret, be careful cannot use null}
            triggerParameter: {your-trigger, be careful cannot use null}
```

**Comment by zecloud** [comment]
Hi @Greedygre 

Sorry for the misunderstanding as my previous answer was not complete. 

To make it work i modified the yaml by removing identity in the scaling rule replacing it in the yaml by auth like this :
```
rules:
      - azureQueue:
          queueLength: 5
          queueName: halloaiavatarvideos
          auth:
          - secretRef: connection-string-secret
            triggerParameter: connection
```
But without creating any secret and after that i applied again the scaling rule with something like this : 
```
az containerapp update -n $CONTAINER_APP_NAME -g $RESOURCE_GROUP \
            --scale-rule-name azure-queue-rule \
            --scale-rule-type azure-queue \
            --scale-rule-metadata "accountName=$STORAGE_ACCOUNT_NAME" \
                                  "queueName=halloaiavatarvideos" \
                                  "queueLength=5" \
            --scale-rule-identity  $IDENTITY_ID 
```

It seems it worked because putting something in the queue has started the keda scaler from what i saw in the logs but after that i had another issue the pod never started with this error "AssigningReplicaFailed" i think it's the same issue described here -> #https://github.com/microsoft/azure-container-apps/issues/1168 

So from what i understand currently the better workflow to create a container app with the cli with a scaling rule with user assigned identity and a mounted volume is to :

- start by creating the containerapp without the scaling rule with az containerapp create 
- get the yaml by using  az containerapp show  
- update the containerapp with the yaml modified with the mounted volume
- add the scaling rule with the user assigned identity with az containerapp update 

All could be created with one command with this feature #https://github.com/microsoft/azure-container-apps/issues/1153

**Comment by simonjj** [comment]
@zecloud thanks for raising this and so happy this ended up working. We're tracking #1153 as a Backlog item and will hopefully address that soon.
