### ISSUE TITLE
Missing System Logs (yet again), Container App Jobs

### ISSUE THREAD

**Issue by robrennie** [microsoft/azure-container-apps#1235]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
System logs are gone, again, from Container App Jobs.

**Comment by anthonychu** [comment]
@robrennie Can you please send an email to acasupport@ microsoft.com with:
- Job id (subscription, resource group, job name) and the date/time range where the execution failures occurred and there were no logs
- and/or the job execution ids

We'll review our platform logs to see what caused the executions to stop and investigate issues with missing logs. It looks like this is different than the console log issues discussed in #1206 and #1211

**Comment by dyamo** [comment]
I have the same, system logs stop working for a while on my container app environements and then start again, seems to be a constant issue.

**Comment by vinisoto** [comment]
hi @robrennie and @dyamo - coming back to this. We have added a number of fixes/improvements to log processing for Jobs in the past few weeks. 

Please chime in if you are still seeing issues with system logs missing.

**Comment by dyamo** [comment]
@vinisoto Actually in my one container app environment in UK South, there have been no system logs of any kind starting from around 17:30 UTC yesterday.

**Comment by vinisoto** [comment]
@dyamo - can you please send your environment details (environment name, subscription) to `acasupport at microsoft dot com` so we can follow up closely? At the same time, please feel free to open a support request through the Azure Portal

**Comment by vinisoto** [comment]
@japcio, @ali-akdag - please open a support ticket through the Azure Portal and we will be able to assist you.
