### ISSUE TITLE
Feature Request: Support cron custom scaling rule type for Jobs

### ISSUE THREAD

**Issue by Dilergore** [microsoft/azure-container-apps#1242]
**Is your feature request related to a problem? Please describe**.  
Container App supports the scaling rule type 'cron' while Container App Job does not currently.

**Describe the solution you'd like**.    
I would like to be able to setup a Container App Job with cron custom rule - trigger type:
https://keda.sh/docs/2.14/scalers/cron/

**Describe alternatives you've considered**.   
Currently my workaround will be to deploy a Container App for Cron and Container App Job for Azure-Pipelines trigger. This is okay but increasing the tech dept. I should be able to use a single Job with two triggers for this (Pipelines and Cron).

**Comment by anthonychu** [comment]
Jobs support a schedule trigger that takes a cron expression. Does that work for your scenario? https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#scheduled-jobs

**Comment by Dilergore** [comment]
> Jobs support a schedule trigger that takes a cron expression. Does that work for your scenario? https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#scheduled-jobs

@anthonychu I do not believe so. Based on my understanding schedule can be used to trigger the start of x number of replicas. For example it is good to generate data for reporting at a given time or to run a specific automation.

My use case is that I would like to scale out at a given time automatically and then scale down when it is not required anymore, to be specific, I would like to run 3 replicas at least from 7AM to 7PM.

**Comment by anthonychu** [comment]
Sounds like you want to have 3 Azure Pipelines agents run from 7am to 7pm? You should be able to run them as a container app instead of a job. The agent can run in 2 modes: as a service that continuously runs jobs from Azure Pipelines or as a job that runs 1 job from Azure Pipelines and exits. If you run it without the `--once` flag, it'll run as a service and can be deployed as a container app. You should then be able to use the cron scaler to scale it to 3 replicas from 7am to 7pm.

**Comment by Dilergore** [comment]
What I would like to have is a combination. During the day I would like to have at least 3 agents running with a possibility to scale out based on the queue size (if needed). During the night when It is unlikely (but not impossible) that jobs will run, I do not want to run agents continuously but instead scale only based on the queue.

You are right, that I can (and that is what I have right now) deploy an app for the cron and a job for the queue scaling. That said, the same could and should work (IMO) with a single Job and two event trigger rules hence this feature request.

**Comment by anthonychu** [comment]
Can you achieve what you want by configuring both an Azure Pipelines scaler and a cron scaler on the same container app?

If you need the cron scaler to work for jobs (I'm unsure how that would work in practice), it might be a feature request for KEDA: https://github.com/kedacore/keda/issues

**Comment by Dilergore** [comment]
> Can you achieve what you want by configuring both an Azure Pipelines scaler and a cron scaler on the same container app?
> 
> If you need the cron scaler to work for jobs (I'm unsure how that would work in practice), it might be a feature request for KEDA: https://github.com/kedacore/keda/issues

- You cannot configure the pipeline scaler for a Container App, that is available only for Jobs.
- The cron scaler is available for Apps but not for Jobs.

Currently you cannot combine them in the same resource as one is not available no matter what offering you choose. I am unsure why this should be a KEDA request as both scalers are available on the KEDA side, it is just that either Apps or Jobs not support one or the other.

**Comment by Dilergore** [comment]
I am thinking a bit more about this...

Integrating this into Jobs might be a challenge as Jobs are designed to have a timeout which would break the cron based continuously running agents (without the --once flag).

Instead adding the pipeline scaling to Apps could work, but the problem there would be adding the flag (--once) only to the on-demand instances would not be possible.

There might be no good solution here with the current featureset.

If I keep the current setup (having both the App and the Job) the problem will be replica number settings combined with the time based scaling:
Daytime I will have 3 agents running (in the App) with the possibility to scale to 6 agents (with the Job). This would require me to set the 'activationTargetPipelinesQueueLength' to 4.  The problem is that this setting would not work during the night as I would not have 3 running agents (as daytime) so the on-demand instances would not start. This likely calls for another automation which modifies the 'activationTargetPipelinesQueueLength' variable twice a day.

Also I am unsure what happens if during the downscaling there is a running job on the agent, this might require some testing.

**Comment by Dilergore** [comment]
I stand corrected, azure-pipelines scaler is available for apps as well. I will do some experiments and share my findings soon, it might be useful for some people in the future. I will close this request for now.
