### ISSUE TITLE
Custom domains settings drop after each deployment

### ISSUE THREAD

**Issue by relounge** [microsoft/azure-container-apps#1243]
### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We're trying to work with .NET Aspire. We built a system on it and now try to deploy it from github via GitHub Actions to Azure. We did everything as in the instructions and it worked. But One thing started to annoy critically. Every time we deploy the new version - custom domain settings are just gone. The same is about Ingress settings. My changes drop after each release. 

### Steps to reproduce
1. Deploy .NET Aspire app via GitHub Actions
2. Set up custom domains
3. Deploy again

**Expected behavior**
New version is running but previous network and domains settings are the same

**Actual behavior**
Ingress settings of the app and custom domain settings are dropped.

**Comment by simonjj** [comment]
@relounge thank you for raising this with us. Could you share the repo or Bicep you're using. The  issue may need updating of the boilerplate Bicep to include the custom domain.

**Comment by simonjj** [comment]
Please see here for guidance on how you can add the custom domain to your Bicep file (found in `infra/resources`). https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-bicep#customdomain

**Comment by relounge** [comment]
@simonjj sorry, I cannot share the repo as it's our production repo. As for the Bicep file - I did not have it until you mentioned it. I deployed our aspire app using the instructions I found in the MS documentation and used [this file](https://github.com/Azure-Samples/azd-starter-bicep/blob/main/.github/workflows/azure-dev.yml) as a workflow file for Github actions. 
Then I started digging and found "next-steps.md" file. As I understand I need to run "azd infra synth" to generate 3 infra files including the one you mentioned and set it up, right? I must confess I never worked with Bicep and when I looked into resources.bicep file I didn't understand how to set up custom domains. I also noticed other created files after "synth" command in the AppHost project inside "infra". All of the files are yaml. Still not sure how it works, but we'll try to set it up, deploy and see what happens next

**Comment by relounge** [comment]
I don't get it. All of the examples [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-terraform) are in Bicep/JSON or Terraform syntax, but the files generated for containerized services by "synth" command were yaml files. This adds a bit of complexity. Will try to guess how it works

**Comment by relounge** [comment]
So I:
- ran "azd infra synth" command and got bicep and yaml files in return
- modified the services with domian bindings I needed (I hope it was correct)
- added those new files to the repo and ran the deployement again
...and nothing has changed.

Here is how I changed the service yaml file:
    ingress:
      external: **true**
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
      **customDomains: 
        - bindingType: SniEnabled
          certificateId: [ here I added the certificate _name_ (not id) I found in azure]
          name: [ here I added my domain]**

I think I need some help. We choose Aspire to get rid of docker files hell. Now I see we got bicep and yaml hell instead.

**Comment by relounge** [comment]
Found a solution for custom domains from here https://github.com/Azure/azure-dev/issues/1765
This command helped: azd config set alpha.aca.persistDomains on

Still working on ingress settings. It hides the endpoint after each deployment.

**Comment by simonjj** [comment]
thanks for updating us @relounge. i will share your feedback with the appropriate teams.
