### ISSUE TITLE
Feature Request: Provide Azure Monitor metric for instance count

### ISSUE THREAD

**Issue by tomkerkhove** [microsoft/azure-container-apps#125]
**Is your feature request related to a problem? Please describe**.  
It is hard to understand how your application is scaling. #75 is aiming to fix that but it should be simpler.

**Describe the solution you'd like**.    
An Azure Monitor metric would be nice that gives you the amount of instances for a given container app. This helps you understand how many instances you were running during troubleshooting of throttling.

Also, this is very important to monitoring autoscaling to understand if it is too aggressive, how often it scales to 0 and more.

**Describe alternatives you've considered**.   
N/A

**Additional context**.

**Comment by BigMorty** [comment]
Thanks @tomkerkhove, we are working on providing a replica count metric as well as a restart metric.

**Comment by Hipster74** [comment]
Hi, reading this article [https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-container-apps-virtual-network-integration/ba-p/3096932](url) and watching the video in the end I can see integration with application insights and what appears to be monitoring of the running ACA pods?

![image](https://user-images.githubusercontent.com/7508953/158180066-3915d900-94ba-49ca-98c4-b2d18ab145ca.png)

How can I achieve the same thing, or am i misunderstanding this issue?

**Comment by BigMorty** [comment]
Container Apps now has replica count replica restart metrics.

**Comment by tomkerkhove** [comment]
Thank you!
