### ISSUE TITLE
Delayed response time of apache backend api

### ISSUE THREAD

**Issue by vigneshvky7** [microsoft/azure-container-apps#1250]
> Please provide us with the following information:
> ---------------------------------------------------------------

I have an apache backend in one container and postgresql as db in another container both are able to communicate in ACA environment but the same setup in VM under same docker network has a response in like 2 seconds and in the container apps it is taking average of around 50 seconds and sometimes url not found error is coming up..

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

Need response of backend api under 3 seconds

**Actual behavior** [What actually happened.]

Taking around 50 secs for response from the api
there are no cpu spike or memory usage
I'm using both of the container in a same workload profile

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by simonjj** [comment]
Thank you for reaching out @vigneshvky7 Here are a few things to check:
* Please turn off scale-to-zero by setting your minimum scale of both backend and db to a minimum of 1
* Can you please share a screenshot of the "url not found error", it would be useful to see so we can get a better picture of which part of the platform generates it.
* Does the slow response happen only once in a while or can you reproduce it easily and within short succession?
