### ISSUE TITLE
Question - how to customize timeout period when using scale-to-zero HTTP scaler

### ISSUE THREAD

**Issue by evanjamesjackson** [microsoft/azure-container-apps#1251]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
From what I can tell (although I can't find any official documentation on it), the scale-to-zero behavior of the built-in HTTP scaler uses a timeout of 5 minutes of inactivity before scaling an app to zero replicas. This is a fairly short period of time when performing work within a typical webapp, so I am wondering whether there is any way to customize this timeout period?

**Comment by anthonychu** [comment]
This request is currently tracked here: https://github.com/microsoft/azure-container-apps/issues/573 and we don't yet have an ETA.

You might be able to use the `terminationGracePeriodSeconds` setting in the [container app template](https://learn.microsoft.com/en-us/rest/api/containerapps/container-apps/create-or-update?view=rest-containerapps-2024-03-01&tabs=HTTP#template) to configure how long to wait for your app to gracefully shut down. When a replica is about to be removed, your container is sent a SIGTERM signal. If you trap and handle the signal, you can wait for any ongoing work to complete (up to the `terminationGracePeriodSeconds`) before exiting your process.

What work are you performing in the app? A common and perhaps more recommended pattern is to split this work into a job and invoke the jobs when requests arrive.

**Comment by evanjamesjackson** [comment]
> This request is currently tracked here: #573 and we don't yet have an ETA.
> 
> You might be able to use the `terminationGracePeriodSeconds` setting in the [container app template](https://learn.microsoft.com/en-us/rest/api/containerapps/container-apps/create-or-update?view=rest-containerapps-2024-03-01&tabs=HTTP#template) to configure how long to wait for your app to gracefully shut down. When a replica is about to be removed, your container is sent a SIGTERM signal. If you trap and handle the signal, you can wait for any ongoing work to complete (up to the `terminationGracePeriodSeconds`) before exiting your process.
> 
> What work are you performing in the app? A common and perhaps more recommended pattern is to split this work into a job and invoke the jobs when requests arrive.

Thanks @anthonychu - it looks to be moreso related to https://github.com/microsoft/azure-container-apps/issues/388 - I will close this to avoid duplication
