### ISSUE TITLE
Feature Request: Update Container App Environment Certificate when Key Vault Certificate renews

### ISSUE THREAD

**Issue by michael-sterling** [microsoft/azure-container-apps#1252]
**Is your feature request related to a problem? Please describe**.  

We would like to use the new Azure Key Vault Certificate feature[^1] for Custom Domains in our Container Apps and Custom DNS Suffixes in our Container App Environments.

We are able to successfully upload a certificate to Azure Key Vault and use it in our Container App. However, when I force a renewal of the certificate to test it, uploading a new value to the Azure Key Vault certificate secret, the Container App continues to serve the _original_ certificate, not the updated value.

**Describe the solution you'd like**.    

When the Azure Key Vault secret containing referenced as an Azure Container App Environment certificate by ID is updated with a new version, any Container Apps using that certificate should start serving traffic using the new certificate value and the Container App Environment certificate should reflect the new value.

**Describe alternatives you've considered**.   
I could manually re-create the Custom Domain or Custom DNS Suffix using the latest version of the certificate from Azure Key Vault; however, I would like instead for that step to be automatic.

**Additional context**.  

A user asked if this feature would be present in a comment on the original issue:

> Will this include that the certificate is automatically updated on the container app env when a new version of it is created in KeyVault?
 -- [btbaetwork commented on Oct 13, 2023](https://github.com/microsoft/azure-container-apps/issues/888#issuecomment-1761290331)
 
 They received no answer that I could see.
 
In our Azure Key Vault, the Key Vault Certificate secret shows this history:

| | Version | Thumbprint | Activation Date | Expiration Date |
-- | -- | -- | -- | --|
| CURRENT VERSION | 2b0baa8d5e9e417a88e88a3bce60688b | EFF8726D056383A8C5A686F2DABA2B7BEDB5A112 | 8/11/2024 | 11/9/2024
| OLDER VERSIONS | d0c8c38bd5c04d2ead49f7710873e193 | E828F1F1E802847D57E1EEDC42299067DDC44C22 | 8/9/2024 | 11/7/2024 |

In the Container App Environment "Certificates" blade, the "Bring your own certificates (.pfx)" tab displays the _old_ version of the Key Vault certificate, which was originally uploaded:

| Type | Expiration Date | Thumbprint |
| -- | -- | -- |
| Azure Key Vault Certificate | 11/7/2024 | E828F1F1E802847D57E1EEDC42299067DDC44C22 |

Navigating to the Container App using the Custom Domain or Custom DNS Suffix confirms that it is continuing to serve traffic using the old certificate value.

I can view the existing Container App Environment certificate using `az containerapp env certificate list` and observe it still has the old certificate value's properties:

```
    "properties": {
      "expirationDate": "2024-11-07T18:56:16",
      "issueDate": "2024-08-09T18:56:17",
      "provisioningState": "Succeeded",
      "thumbprint": "E828F1F1E802847D57E1EEDC42299067DDC44C22",
      "valid": true
      [...]
    },
```

[^1]: [Issue](https://github.com/microsoft/azure-container-apps/issues/888), [Announcement](https://azure.microsoft.com/en-us/updates/public-preview-support-for-key-vault-certificates/), [Documentation](https://learn.microsoft.com/en-us/azure/container-apps/key-vault-certificates-manage)

**Comment by simonjj** [comment]
@michael-sterling, thanks for reaching out and pointing this out. We're working on a doc update to address this exact issue. For now there are two points to keep in mind:

1. You need to ensure that `--akv-url` uses a "version-less" url in the form of `https://KEY_VAULT_NAME.vault.azure.net/secrets/SECRET_NAME_IN_KEY_VAULT` instead of `https://KEY_VAULT_NAME.vault.azure.net/secrets/SECRET_NAME_IN_KEY_VAULT/version-details-are-here`
2. If you're already using a version-less url you may have to wait up to 12h before the refresh kicks in.

**Comment by michael-sterling** [comment]
@simonjj, thanks for the response!

I have confirmed that after waiting 12 hours, the updated Key Vault Certificate is indeed reflected on the Container App Environment for both the Container App Environment Certificates used for Custom Domains on my Container App and on the Certificate used for the Custom DNS Suffix.

This resolves my issue, and I look forward to the mentioned documentation update.

**Comment by apsi15** [comment]
> @simonjj I hate to comment on a closed issue but this is relevant to the issue. I find this very puzzling - the latest API no longer has this feature available. The properties have been removed since the last preview API. Why have they been removed, what am I missing here? I do still see this feature available in the Portal. Is this feature intentionally rolled back or what's the deal here?
> 
> https://learn.microsoft.com/en-us/azure/templates/microsoft.app/change-log/managedenvironments/certificates
> 
> Or to quote the changelog here directly:
> 
> **2024-03-01** Removed:
> 
> * properties.certificateKeyVaultProperties
> * properties.certificateKeyVaultProperties.identity
> * properties.certificateKeyVaultProperties.keyVaultUrl
> * properties.certificateType
> 
> **2024-02-02-preview** No new or updated properties
> 
> **2023-11-02-preview** Added:
> 
> * [properties.certificateKeyVaultProperties](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2023-11-02-preview/managedenvironments/certificates#certificateproperties)
> * [properties.certificateKeyVaultProperties.identity](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2023-11-02-preview/managedenvironments/certificates#certificatekeyvaultproperties)
> * [properties.certificateKeyVaultProperties.keyVaultUrl](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2023-11-02-preview/managedenvironments/certificates#certificatekeyvaultproperties)

I've spent 6 hours trying to figure it and gave the answer. I find it as well very confusing why it has been removed. Any one can advice here regarding this topic?

**Comment by saarivirtajCGI** [comment]
@apsi15 See this issue, there's a bit of insight to this: https://github.com/microsoft/azure-container-apps/issues/1288
