### ISSUE TITLE
ARM wrong error message when updating environment file mounts

### ISSUE THREAD

**Issue by itpropro** [microsoft/azure-container-apps#1255]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When trying to update the `azureFile.accessMode` property via API or Bicep, the following error will be thrown.
`Invalid request body for managed environment storage 'MOUNTNAME'. Only 'properties.azureFile.AccountKey' can be updated. (Code: ManagedEnvironmentStorageUpdateBadRequest)`
But the problem is not that only AccountKey can be updated, the problem is that the recreation of the mount is only possible, if no container app is using the environment mount.
The error therefore should point to the mount being in use by a container app and not that a specific field cannot be updated.
As soon the the reference on the container app or the whole container app is deleted while keeping everything else as it is, the deployment goes though successfully.

**Comment by simonjj** [comment]
Thank you @itpropro for letting us know, but based on checking the code base the error does seem to be correct. We don't allow the updating of account name, sharename and access mode, and that's regardless of whether the mount point is used or not.  You say _recreate_ which seems different than updating, deleting and creating (recreating) would allow you to change all kinds of things especially when the storage is unused. Can you provide some additional details please on what exactly you did.

**Comment by itpropro** [comment]
> Thank you @itpropro for letting us know, but based on checking the code base the error does seem to be correct. We don't allow the updating of account name, sharename and access mode, and that's regardless of whether the mount point is used or not. You say _recreate_ which seems different than updating, deleting and creating (recreating) would allow you to change all kinds of things especially when the storage is unused. Can you provide some additional details please on what exactly you did.

Thanks for your reply! I had this feedback from multiple customers, as the error message is not about having only one field that can be modified, but that one or more container app is still using that share.
If I change for example the name of a share on the environment level `sharename`, the API/Bicep return the error mentioned, which is very confusing, as it suggests, that the name cannot be updated. In reality, everything can be updated, as long as it is not used by any container app yet.
Technically, it is a redeploy in the background, but that is never seen by the user and is more of an implementation detail than something the user should be aware of.
The important part for the user is that all of the listed properties can be change (not only the account key), as long as the share mount/claim is not used yet.

**Comment by itpropro** [comment]
@simonjj can you please reopen the issue?

**Comment by P-Stenbumling** [comment]
Im facing the same issue.
