### ISSUE TITLE
Error while deploying Azure Container App with bicep: ContainerAppInvalidResourceTotal

### ISSUE THREAD

**Issue by havarnov** [microsoft/azure-container-apps#1259]
az bicep version
Bicep CLI version 0.28.1 (ba1e9f8c1e)

Describe the bug
Getting an error while trying to deploy an Azure Container App to a Container App Environment with "Consumption" workload profile: ContainerAppInvalidResourceTotal.

In my bicep file a have the following:

```bicep
resource containerApp 'Microsoft.App/containerApps@2024-03-01' = {
  (...)
  properties:{
    (...)
    template: {
      (...)
      containers: [
        {
          (...)
          resources: {
            cpu: json('4')
            memory: '8Gi'
          }
        }
      ]
    }
  }
}
```

But I'll get this error:

```
{"code": "InvalidTemplateDeployment", "message": "The template deployment 'main' is not valid according to the validation procedure. The tracking id is 'f185185a-69fe-45cb-900e-3705995934fe'. See inner errors for details."}

Inner Errors: 
{"code": "ValidationForResourceFailed", "message": "Validation failed for a resource. Check 'Error.Details[0]' for more information."}

Inner Errors: 
{"code": "ContainerAppInvalidResourceTotal", "message": "The total requested CPU and memory resources for this application (CPU: 4, memory: 8) is invalid. Total CPU and memory for all containers defined in a Container App must add up to one of the following CPU - Memory combinations: [cpu: 0.25, memory: 0.5Gi]; [cpu: 0.5, memory: 1.0Gi]; [cpu: 0.75, memory: 1.5Gi]; [cpu: 1.0, memory: 2.0Gi]; [cpu: 1.25, memory: 2.5Gi]; [cpu: 1.5, memory: 3.0Gi]; [cpu: 1.75, memory: 3.5Gi]; [cpu: 2.0, memory: 4.0Gi]"}
```

If I change to 2 vCpu and 4Gi memory it work as expected:

```bicep
          resources: {
            cpu: json('2')
            memory: '4Gi'
          }
```

If I use the portal manually and create a new "revision" of the Azure Container App I can set the resources to 4 vCpu and 8Gi memory. As expected according to the documentation: https://learn.microsoft.com/en-us/azure/container-apps/workload-profiles-overview#profile-types.

First reported here https://github.com/Azure/bicep-types-az/issues/2232.

**Comment by anthonychu** [comment]
There are 2 different "environment types" in Azure Container Apps. The "Consumption only" (V1) environment type has a max of 2 CPU and 4 GB. The "workload profiles" (V2) environment type has a max of 4 CPU and 8 GB when apps run on the Consumption workload profile.

Looks like you are deploying to a V1 environment. By default, in the current API versions, when you deploy an environment with Bicep or ARM, you create a V1 environment. To deploy a V2 environment, you need to add a `workloadProfiles` array property to the `managedEnvironment` resource, with at least one entry for a "Consumption" workload profile. See this example here: https://github.com/Azure/azure-dev/blob/2539f3a1a8a71d21c66be9ea9635cb308ccfc55f/cli/azd/test/functional/testdata/snaps/aspire-full/infra/resources.bicep#L52-L55

You can't change your existing environment's type, you must deploy a new one.

**Comment by havarnov** [comment]
![image](https://github.com/user-attachments/assets/2e14371c-5a37-4867-aeec-cc3a2ecfae95)

I’m pretty sure it’s a “v2 environment”. Also, as I wrote in the OP I’m able to create a revision from the portal with 4vCPU and 8GB.

**Comment by anthonychu** [comment]
Sorry, missed the part where you said it worked in the portal.

Can you send us your container app's resource ID and a more complete copy of the Bicep to acasupport@ microsoft.com so we can investigate?

**Comment by havarnov** [comment]
I got this response from Microsoft support, which helped me work-around this issue.

> The validation logic currently assumes it's a "consumption only" (V1) environment when there's no workloadProfileName property on the app resource, so it's applying a lower limit on the resources you can allocate. Can you please add "workloadProfileName": "Consumption" to your Bicep file and try again?
> 
> The workloadProfileName property should be optional and we'll look into updating the validation to allow this scenario.
