### ISSUE TITLE
Please help me correct my cronJob run inside containerapp.bicep

### ISSUE THREAD

**Issue by nholuongut** [microsoft/azure-container-apps#1264]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by anthonychu** [comment]
Closing as duplicate #1265
