### ISSUE TITLE
Duplicate Environment Variables (was: Start Button Fails to Start Container App)

### ISSUE THREAD

**Issue by avalanchis** [microsoft/azure-container-apps#1269]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I used the "Stop" button to stop my container app.  A short time later I used the "Start" button to restart the app.

I received a notification with a green checkmark that said:

**Successfully started Container App**
The Container App started successfully.

But the container app's status still shows "Stopped".  I tried refreshing the page.  Status still displayed "Stopped".  Confirmed that the app was not running.  Log stream displays "This revision is scaled to zero".  Tried creating a new revision but it will not launch.  Reverted back to a known good version of the app that ran fine several days ago.  Still won't start.

This started happening yesterday 2024-08-21.  I've been using the Stop/Start functionality quite often for some time now with several container apps and this is the first time I've seen this behavior.  

There are no console or system logs available to indicate why the app was not started.

I had stopped another one of my apps around the same timeframe and I was able to restart it without any problems.

I noticed that several others are experiencing a similar issue starting around the same time:

https://learn.microsoft.com/en-us/answers/questions/1921321/unable-to-start-a-container-app

### Steps to reproduce
1. Select "Stop" button on overview page to stop a container app.
2. Select "Start" button on overview page to start the app.

**Expected behavior** [What you expected to happen.]
The app is started successfully.

or at minimum:

There is not a misleading notification that the app was started when it was actually not started.

Also it would be nice to have some logs somewhere indicating why the app did not start.

**Actual behavior** [What actually happened.]
There is a notification indicating that the app was started successfully, but the app was not started.

App status is "Stopped".

**Screenshots**         

![image](https://github.com/user-attachments/assets/4b1be9de-debf-4ca6-b842-5364932dd725)

![image](https://github.com/user-attachments/assets/e3f8b315-2554-4075-a2c8-3d655b78c3be)

![image](https://github.com/user-attachments/assets/f75d4306-5790-48e7-bf35-2e60106aa29b)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

Portal

**Comment by simonjj** [comment]
@avalanchis thank you for reaching out. Could you please share your subscription, environment name and app name via acasupport at microsoft.com. This will allow us to take a closer look and get back to you.

**Comment by jbrailsford** [comment]
Just to add we've had this same issue, for us the way it manifested was that we could deploy the container app, but it would have no revisions listed under revisions & replicas, there were no errors returned by the deployment API to suggest we had submitted unsupported configuration, and there were no errors within the container app resource/container app environment resource which indicated it was a configuration issue.

Similarly, if we attempted to deploy a new revision we'd receive an error stating that the base revision could not be null.

The only information we had to go on was:
- The system logs showed that the CAE attempted top deploy the app/revision 16 times and then stopped
- The API returned an error stating `Failed to provision revision for container app '{redacted}'. Error details: Operation expired.`.

If it wasn't for @avalanchis which the miracle save I'd still be sat here scratching my head. I think in this scenario either the API should reject the deployment OR the revision should appear in a failed state, evidently it's not a retriable error.

**Comment by simonjj** [comment]
Thanks for jumping in. We have a fix enroute for this. @cachai2 will provide an update on the progress of the fix to this.

**Comment by simonjj** [comment]
Yes, I love getting tags "just right".

**Comment by simonjj** [comment]
This should be addressed now. Closing. Please reopen if it's still and issue.
