### ISSUE TITLE
ManagedEnvironmentNoAvailableCapacityInRegion exception during creation of container apps environment

### ISSUE THREAD

**Issue by jscheeres** [microsoft/azure-container-apps#1272]
### This issue is a:
- [x] bug report
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

During creation of a Container Apps Environment we get the following exception:

"No capacity available in this region for provisioning an environment, please try again in another region. (Code: ManagedEnvironmentNoAvailableCapacityInRegion)"

We deploy in region westeurope. We have een quota of 50 managed environments in this subscription. Currently 0 managed environments are deployed into the subscription.

### Steps to reproduce
1. Create container app via Azure Portal of via BICEP

**Expected behavior**

New container app environment.

**Actual behavior**

See error in screenshot.

**Screenshots**         

![image](https://github.com/user-attachments/assets/e8864d9a-6bd0-427f-a529-701a791238f5)

**Comment by apsi15** [comment]
Same issue here for west europe:
`Managed Environment Name: "xxxx"): performing CreateOrUpdate: unexpected status 409 (409 Conflict) with error: ManagedEnvironmentNoAvailableCapacityInRegion: No capacity available in this region for provisioning an environment, please try again in another region.`

**Comment by Yuvaraj-Devaraj** [comment]
I also experience this problem from yesterday. Would be good if Microsoft can fix this soon.

**Comment by rokcarl** [comment]
Same problem here in west Europe:

Managed Environment Name: "[redacted]"): performing
CreateOrUpdate: unexpected status 409 (409 Conflict) with error:
ManagedEnvironmentNoAvailableCapacityInRegion: No capacity available in this
region for provisioning an environment, please try again in another region.

This happened on a Terraform apply that needed to recreate the Container App Environment, so it destroyed and tried creating it and the above error happened.

**Comment by scipbe** [comment]
Microsoft, when will it this be fixed? It is blocking the creation of our new environments

**Comment by yuliyansamuilov** [comment]
![image](https://github.com/user-attachments/assets/f18d9d29-d7c4-4b69-8e05-2592ea5943a6)
It's pretty strange. I have two different types of subscriptions. The Pay-As-You-Go subscription is showing this error, but on my other subscription, I was able to create container apps yesterday and tested everything without any issues. Now, I'm getting this error on the Pay-As-You-Go subscription today.

**Comment by Yuvaraj-Devaraj** [comment]
I have checked with Microsoft support. They said that they are running out of capacity in west europe region and are working on increase the capacity. They suggested to go with other closer regions.

The impact is only for the subscriptions where we deploy container app environment for the first time. If you already have an existing app environment, they allow you to deploy another environment. We got to wait to deploy in west europe or go with alternation location.

**Comment by IanBrown-OAG** [comment]
Same here, we can create in Poland Central, but not West Europe. I am waiting on MS support to confirm the issue though.

**Comment by rokcarl** [comment]
What's the situation with this? What space can I monitor to know when this will be resolved?

The deployment of our app is currently blocked because of this. I wouldn't want to migrate to another region as we have loads of resources in this one already.

**Comment by Sebastianbuus** [comment]
We are blocked as well.

We need a status update on this issue.

**Comment by MarcoP9** [comment]
Hello, experiencing the same problem, Is there any update on this?

**Comment by iwijnen** [comment]
Hello, experiencing the same problem, Is there any update on this?

**Comment by karimatwa** [comment]
Hello,
We're also experiencing the same problem here. Similar to everyone in here, we can deploy container apps environments in other regions, but not Europe west.

**Comment by HuiNextSense** [comment]
Is there a chance the capacity will be increased in WestEurope region? I honestly don't prefer to deploy a set of resources in a different region.

**Comment by mjpraxis** [comment]
Does MS / Azure have a status page of these kind of limits. Would be nice to see if it is possible to create environments in West euro again. And not to get the error while trying to create them.

**Comment by rokcarl** [comment]
I'm pretty sure it's not a limit this time. See, I already had an ACA environment, then my deployment using Terraform needed to re-create (meaning delete and create) the ACA environment. It was able to delete, but creation failed. And it's not like we already have loads of ACA environments created, this specific subscription has none actually.

**Comment by WakaToa** [comment]
Capacity is increased. I was able to deploy a new Consumption Only Environment few minutes ago.

**Comment by jscheeres** [comment]
Still same issue here. I think it's only an issue if it's the first container app environment in a new subscription.

**Comment by yakonstantine** [comment]
I've just faced with same issue. I've accidentally deleted ACA env, now I can't re-deploy it via Terraform.

**Comment by EricCpy** [comment]
Still the same issue. The capacity is not increased and this problem only affects the first environment of a subscription.

**Comment by WakaToa** [comment]
Well, for me it was not working for around a week until today. It was the first environment of a subscription. Maybe i was just lucky.

**Comment by Gert-Jan2AT** [comment]
Just tried it same problem.

**Comment by rokcarl** [comment]
Still happening here.

**Comment by akakaule** [comment]
Have not been able to create it in West Europe region the last week. Still get this error

![image](https://github.com/user-attachments/assets/06826be1-4e5b-4626-8208-c4d3f461567b)

**Comment by dernat71** [comment]
Same as well here .. We are really relying on Container Apps for our runtimes so this is quite urgent

**Comment by ribboncake94** [comment]
> Still the same issue. The capacity is not increased and this problem only affects the first environment of a subscription.

Well, this is not entirely true in my case. I have tried to deploy a new environment in a subscription where I already have an ACA env, and it did not work.

**Comment by Shadikho** [comment]
Same problem here. I even checked and I have "quota" for the resource on my subscription, but no capacity...

**Comment by alexander-kastil** [comment]
What a shame to run out of capacity for such an essential service in a big datacenter like westeurope

**Comment by SYA6161** [comment]
same problem here

**Comment by BartHuls** [comment]
same problem here
"details": [
    {
      "code": "ManagedEnvironmentNoAvailableCapacityInRegion",
      "message": "No capacity available in this region for provisioning an environment, please try again in another region."
    }
  ]

**Comment by romanrabodzei** [comment]
I also have the same error: "ManagedEnvironmentNoAvailableCapacityInRegion." West Europe region

**Comment by ribboncake94** [comment]
> > Still the same issue. The capacity is not increased and this problem only affects the first environment of a subscription.
> 
> Well, this is not entirely true in my case. I have tried to deploy a new environment in a subscription where I already have an ACA env, and it did not work.

Ok now I have managed to deploy ACA ENV just this morning via terraform. Has capacity been increased in West Europe now?

**Comment by JennyLawrance** [comment]
We have been actively working to resolve the issue. Yes, creates on WEU should be successful now.

**Comment by romanrabodzei** [comment]
> We have been actively working to resolve the issue. Yes, creates on West Europe should succeed now.

Just tested. It works for West Europe. Thanks!

**Comment by juicd** [comment]
I just tried to create one via the portal but receiving the same error

**Comment by simonjj** [comment]
We recommend to choose a different region, contact your account executive, or file a support ticket if you're experiencing issues of this kind.

**Comment by ckanaar** [comment]
Currently experiencing this issue. Despite the Azure Service Health being marked as healthy. Anyone else experiencing this issue? Is this on your radar @simonjj ?

**Comment by david-visma** [comment]
Yes, same issue here, I had to recreate an environment deleting and recreating, and when I tried to recreate it, it started to fail with the same error: "ManagedEnvironmentNoAvailableCapacityInRegion." West Europe region.
