### ISSUE TITLE
Container App Revision stuck in a block state

### ISSUE THREAD

**Issue by rlachic** [microsoft/azure-container-apps#1273]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

Container App gets totally blocks when a new revision is wrong, and doesn't show any error, just let you with the previous version.

I have tried to stop the container and modify it, without success. If you stop the container, will not be able to run anymore.

I found the issue, and was related with a duplicated variable added through Azure CLI Or Azure API.

Anyway, this should report something, such as replica Unhealthy or something else, because doesn't show any kind of information and I have lost more than 1 day trying to figure out was going on.

This is the only error that I received through Azure CLI:

Failed to update revisions: Error activating revision something-app-backend-prod. Details Reason: Internal Server Error. Body: {"error":"Error updating revision","success":false}`

### Steps to reproduce
1. Deploy a Container through Azure CLI or Az-API which contains multiple variables, one of them duplicated.

**Expected behavior** [What you expected to happen.]

Don't get the container totally blocked.
Show at least some kind of information such as replica unhealthy.

**Actual behavior** [What actually happened.]

Container is block, if the Container stop, doesn't run anymore.

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by rlachic** [comment]
Hi @simonjj , the problem with this workaround is the Container App stuck in a strange state, and we weren't able to even modify the variables. We tried several times, even activating older revisions, and didn't work.
At least, the revision which doesn't work should be tag as unhealthy and give you the opportunity to re-balance to an older one if is possible.

**Comment by simonjj** [comment]
Understood, out of curiosity this happens across portal, CLI and API? If redeployment is not an option I can see where this fix is in the deployment pipeline.

**Comment by rlachic** [comment]
@simonjj I tried through Azure CLI and Portal, to create a new revision of the application without any environment variable, and the problem was the revision didn't be active because the stuck state of the Container App. So I was completely blocked.

**Comment by simonjj** [comment]
This should be fixed now. No redeploy should be needed things should work again. Please reopen if you run into issues.
