### ISSUE TITLE
Azure Container App fails to load with user assigned managed identity

### ISSUE THREAD

**Issue by kamalsivalingam** [microsoft/azure-container-apps#1289]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We are working on moving to Azure Container Apps from Azure Container Instances. While we are trying to reuse the same docker-compose file, I have been running into issues trying to bootstrap the .NET Core Web API container.
Earlier i was getting error related to managed identity - Service request failed. Unable to load the proper Managed Identity

We are using user assigned managed identity and I found another github issue where someone mentioned we had to set environment variable for AZURE_CLIENT_ID with the user managed identity's Client Id.

While that error is now resolved, the Web API container app is still not starting up. Looking into console, i just see this Probe Failed error.
{"TimeStamp":"2024-09-19 22:07:26 \u002B0000 UTC","Type":"Warning","ContainerAppName":"clinic-api-pr-158","RevisionName":"clinic-api-pr-158--nh7bwes","ReplicaName":"clinic-api-pr-158--nh7bwes-5dcc7674cb-dcgd7","Msg":"Probe with executor TcpExecutor failed with status code: 1","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":1039}

I do not see any other error in the logs. Could you please let me know what could be issue? Is there any other troubleshooting technique/tips?

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by kamalsivalingam** [comment]
Is liveness probe mandatory for the container apps to work?

**Comment by anthonychu** [comment]
If you don’t define any probes, default probes are created for you using the target port you configured on the ingress. Can you confirm the container is listening to the target port?

**Comment by simonjj** [comment]
@kamalsivalingam, sounds like the TCP probe clarity has resolved this issue. Can we close this issue now or do you still need help?

**Comment by kamalsivalingam** [comment]
@simonjj Following were the fixes i had to make to get this working:
- Set AZURE_CLIENT_ID environment variable to get user managed identity working
- Certificate related issue was resolved by MS Team https://github.com/microsoft/azure-container-apps/issues/1297
- With VNet integrated Azure Container App, using IP address to test/access container app was not working as the envoy proxy is using the hostname in the URL/Header to route to the correct container app
- For PostgresDB, Ingress type has to be TCP
