### ISSUE TITLE
 Azure Container Apps TCP/UDP

### ISSUE THREAD

**Issue by Mouzou** [microsoft/azure-container-apps#129]
Hi,
When creating an Azure container Apps, how can i expose port 7777 for TCP ?
Thank you

**Comment by webprofusion-chrisc** [comment]
Regarding UDP, I currently run a cloud based dynamic DNS service (used for ACME certificate validation) which needs to provide results via UDP and TCP port 53. 

In some cases this can be achieved by forwarding external ports to high ports on the container instance itself, but it still needs to be TCP or UDP depending on the client query.

The service in this case uses containers as disposable instances. DNS is a very hostile environment, so it helps if instances can auto scale and recover as required, which is where the containers are ideal (also there are no cloud based serverless functions that I know of which can talk UDP).

**Comment by guitarrapc** [comment]
Is it plan to support host TCP app like redis, Nats or any?
Ingress supports HTTP1/2 protocol and dapr supports http/grpc appProtocol.

**Comment by StefanFl** [comment]
Is there an update, when Container Apps will support the TCP protocol? That would be a very useful feature. I want to deploy a Python Django application with Celery and Redis for asynchronous tasks.

**Comment by kendallroden** [comment]
we have announced TCP support. If you have further asks outside of the currently available capability. Please open a new issue we can track. Thank you
