### ISSUE TITLE
storage mount limit

### ISSUE THREAD

**Issue by seanli1988** [microsoft/azure-container-apps#1294]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A customer is citing 20GB limit of volume mount when using container apps in consumption mode - is this true? Is there a work around?

**Comment by anthonychu** [comment]
@seanli1988 What type of volume mount? Azure Files or ephemeral?

**Comment by whereisyusuf** [comment]
ephemeral

**Comment by whereisyusuf** [comment]
What about azure files?

**Comment by anthonychu** [comment]
> What about azure files?

No. The limit is determined by your Azure file share configuration.
