### ISSUE TITLE
Q: CD using GitHub actions

### ISSUE THREAD

**Issue by johnkors** [microsoft/azure-container-apps#13]
Hi,

I did some brief testing of the GitHub action CD approach, and have a question re traffic to revisions. I believe it works as expected with traffic being directed to the latest revision when setting it up OOB.  However, I wanted to test setting traffic in the Azure Portal. So i set 100% traffic to an older revision in the UI. After doing that, there was no way to tell it to go back to always direct traffic to the latest revision for subsequent deploys. On new revsions, it would just keep the traffic to the old revision (which is understandable). 

So, is there a parameter to `az containerapp update` to get back to "CD mode" (force traffic to the new revision from the image I'm setting right now)?

Any help appreciated.

**Comment by johnkors** [comment]
The only way I got working, was to disconnect and re-connect GitHub actions in the "Continous Deployment" tab. Unfortunately, this leads to some unwanted side-effects:
- It  git pushes another auto-generated yml file (I already have one from the first setup process, so I have to delete it immediately)
- It  immediatly kicks of a deployment process (hey, I don't want to deploy right now, just enable CD mode)

Could you elaborate how one could re-connect for "Continous Deployment" without Azure pushing a new yml file into my git repo?

**Comment by ahmelsayed** [comment]
Hi @johnkors you can restore the original behavior by running 

```
az containerapp update ... --traffic-weight latest=100
```

**Comment by johnkors** [comment]
Ok, thanks! 

Shouldn't that be included in the GitHub action? 

What about the other side effects when disconnecting/connecting? Seems like unwanted behaviour.

**Comment by johnkors** [comment]
If I just setup the GitHub action manually (I prefer this over what is generated) rather than thru `az` CLI or the azure portal, would CD still work? 

Or are there other mechanisms in play dependent on it (ex. does it wire up some config between the container app and the registry, or smth)?

**Comment by xwang971** [comment]
Hi, @johnkors Yes we would provide options for customers to decide if they want to push the file to workflow directory or not.

**Comment by johnkors** [comment]
Could you answer the 2nd part as well?

Are there other mechanisms in play dependent on it (ex. does it wire up some config between the container app and the registry, or smth)?

**Comment by kendallroden** [comment]
You can use the CD scaffolding that we provide or use your own action with container apps as a target and you will not miss out on any functionality or need to in some way "connect" your github action outside of the typical workflow.
