### ISSUE TITLE
"ScaledObject doesn't have correct triggers specification" error in logs

### ISSUE THREAD

**Issue by samgre** [microsoft/azure-container-apps#1307]
### This issue is a

- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

"ScaledObject doesn't have correct triggers specification" message appears in a Container App system log every 15 minutes. We do not want this specific container app to be scaled, so we've specified min and max replicas to 1. In the future the container app will be scalable, but not right now.

[Documentation states](https://learn.microsoft.com/en-us/azure/container-apps/scale-app?pivots=azure-cli) that the default values for min and max replicas are 0 and 10, respectively.

How to disable scaling through configuration so that there is always single replica running and no aforementioned errors are found in logs?

### Steps to reproduce

1. Deploy container app with min replicas = 1 and max replicas = 1, with or without a HTTP scaling rule
2. Look at the logs for ScaledObject messages

**Expected behavior**

There would be a single replica running at all times, and no ScaledObject messages in system logs.

**Actual behavior**

There are messages about incorrect triggers specification.

**Screenshots**         

<img width="799" alt="Screenshot 2024-10-04 at 15 01 36" src="https://github.com/user-attachments/assets/10fac22c-a391-4923-a5de-0655059aa02d">
<img width="569" alt="Screenshot 2024-10-04 at 15 01 44" src="https://github.com/user-attachments/assets/8393d253-24df-4f07-94f4-072891cea7e7">

### Additional context

Azure Portal, container app system logs, query:

```
  ContainerAppSystemLogs_CL
  | where ContainerAppName_s == 'NAME'
  | project TimeGenerated, Log_s
  | order by TimeGenerated desc
```

**Comment by v-vish** [comment]
@samgre I have successfully reproduced the issue with both the minimum and maximum replicas set to 1. Upon reviewing the logs, I could not find any messages related to the scaled object. you can refer the screenshot [screenshot.](![Image](https://github.com/user-attachments/assets/f838ee50-17e4-44ea-8231-02f73478c5e8)
)
Could you kindly confirm the region where this deployment has been carried out?

**Comment by sagrluco** [comment]
Our deployment is in West Europe region.

**Comment by v-vish** [comment]
@samgre I have replicated the same setup in the West Europe region but did not find any scaled object messages in the logs. Could you please try again and let me know the status? If the issue persists, kindly share your environment and application details by emailing acasupport at microsoft.com, referencing this issue in your message.

**Comment by v-vish** [comment]
@samgre sure...Thank you!!!

**Comment by victorhazbun** [comment]
This fix worked for me:

1. Visit your container app overview page.
2. Go to "revisions and replicas".
3. Click on "create and deploy new revision"
4. Click on the container image name.
5. Increment "Container resource allocation", in my case 2 CPU cores and 4 Gi ram.
6. Click "Create" button.

**Comment by iloveitaly** [comment]
@v-vish @samgre Did you ever determine what the root cause is she was here?

**Comment by dappermongo** [comment]
This issue affects us in UK South too

**Comment by DavidePastore** [comment]
This issue also appeared for me in the Poland Center Location.

**Comment by ogiel** [comment]
Same here! Also min / max scale both at 1 deployed through Bicep. 1cpu + 2gb ram if it matters but I will ignore this for now as it doesn't appear to affect performance.

EDIT: I am also receiving this warning in a container with min 1 and max 10 at scaling, so it is not necessarily at 1/1.

**Comment by TWolversonReply** [comment]
Any update? Still noticeable in UK South, and it's only a nuisance, but quite a significant one with amount of rubbish that goes into the logs.
