### ISSUE TITLE
Feature Request: Managed Certificate for VNet Integrated Container Apps

### ISSUE THREAD

**Issue by kamalsivalingam** [microsoft/azure-container-apps#1310]
**Is your feature request related to a problem? Please describe**.  
When enabling custom domain and trying to add certificate, Managed Certificate option is disabled. I believe this is because my container app environment is VNet integrated

**Describe the solution you'd like**.    
Would like to use managed certificate for VNet integrated container app environment

**Describe alternatives you've considered**.   

**Additional context**.

**Comment by v-vish** [comment]
@kamalsivalingam I attempted to replicate the issue by creating a VNET and deploying a container app within it. I noticed that the managed certificate option was enabled when adding a custom domain. Please refer to the screenshot below for reference.![Image](https://github.com/user-attachments/assets/f8f4103d-726b-46d8-8c47-e5b1274a0250)


Could you confirm whether the environment where you deployed the container app was internal or external?

**Comment by kamalsivalingam** [comment]
@v-vish ingress is external for the container app. I have the VNET set at the container environment itself.

On a related note, i now have a workaround..
1. Created a self signed certificate that auto renews in Azure KeyVault
2. Import this certificate from Azure KeyVault in Container Environment-> Custom Domain

**Comment by v-vish** [comment]
@kamalsivalingam Thank you for sharing the workaround. We're glad to hear that you've set up a self-signed certificate that auto-renews in Azure KeyVault and successfully imported it into the Container Environment under Custom Domain. With this solution in place, we will consider the issue resolved and proceed to close it. If you need any further assistance, feel free to reach out. Thanks again!
