### ISSUE TITLE
Storage Accounts getting Created for Azure Container Apps

### ISSUE THREAD

**Issue by VenkataRKC** [microsoft/azure-container-apps#1313]
Hi, 

I see storage accounts getting created and not getting deleted when we delete the container apps...this is for Azure Container Apps hosted in a Azure Container Environment. 

Is there a way to check which azure storage account is being used by which Container App ?. Basically trying to identify if the Azure Storage Account is being used or not...because even though the Container App is deleted the Storage Account still persists....unless that is not the expected behavior. 

Screen shot for clarity.   There are 14 storage accounts that got created even though there are only 8 Container Apps.

![Image](https://github.com/user-attachments/assets/040ce7f7-cd59-42a1-ac5a-dbb2696ee830)

**Comment by anthonychu** [comment]
@VenkataRKC Can you please share more information about how you created these apps and environments? I don't believe Container Apps automatically creates storage accounts by default. Thanks.

**Comment by VenkataRKC** [comment]
> [@VenkataRKC](https://github.com/VenkataRKC) Can you please share more information about how you created these apps and environments? I don't believe Container Apps automatically creates storage accounts by default. Thanks.

@anthonychu thanks for the response, the environment is created via the Bicep and we are using the portal to deploy the container apps. Do you think these might get created when we create a azure function in the container app? ...I am trying to figure out what these storage accounts are. I am positive we did not create them and i see that the naming convention for the storage account is getting generated from the resource group....Wondering how to find out whether it is container app or when we create a azure function in container app environment. We have been working on Dev environment and been creating apps from the portal. I can clean delete them but not sure which container apps/functions are mapped to which storage accounts.

**Comment by simonjj** [comment]
@VenkataRKC if you are deploying Functions on ACA these storage accounts could easily originate from those deployments. You can check in your Function app settings by taking a look at the WebJobStorage environment variable.

**Comment by VenkataRKC** [comment]
@simonjj will check it thank you for the confirmation.
