### ISSUE TITLE
Can't re-add MS as ID provider after deleting it once from container app

### ISSUE THREAD

**Issue by thomasalcock** [microsoft/azure-container-apps#1314]
![Image](https://github.com/user-attachments/assets/327dc935-d413-49fe-932f-6627fc6cf8aa)
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Cannot add MS as an ID provider in a container app after deleting the previously configured MS provider in Azure Portal.

### Steps to reproduce
1. Create a container app
2. Configure MS as an ID provider in a single tenant
3. Add first 4 permissions
4. Delete ID provider
5. Attempt to add MS as an ID provider again and fail, because it is unselectable in the drop down menu

**Expected behavior** [What you expected to happen.]

I expect the same ID provider to be available even after I've deleted it once before.

**Actual behavior** [What actually happened.]

The same ID provider cannot be selected after deleting it once.

**Screenshots**         

### Additional context
In the Portal

**Comment by anthonychu** [comment]
@thomasalcock Can you please share your app's resource ID with us at acasupport@ microsoft.com and reference this GitHub issue so we can look into?

**Comment by thomasalcock** [comment]
Oddly enough I was able to add the ID provider now. For some reason the ID provider didn't delete the first time.
