### ISSUE TITLE
Internal server error while deploying using bicep

### ISSUE THREAD

**Issue by kamalsivalingam** [microsoft/azure-container-apps#1318]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have been trying to deploy azure container apps using bicep, randomly mostly the first try keeps throwing internal server error
{
  "code": "InternalServerError",
  "message": "There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: f9384c70-2c26-4eca-afb2-f0a9255be2a0"
}

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         
![Image](https://github.com/user-attachments/assets/8df97c96-fc29-40bb-a5ff-b0142020c1b0)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by anthonychu** [comment]
There's not enough information here to help troubleshoot. Can you please share the bicep files you're deploying? Alternatively, you can open a support ticket.

**Comment by kamalsivalingam** [comment]
@anthonychu How do i open support ticket?

**Comment by anthonychu** [comment]
Please see https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by kamalsivalingam** [comment]
Thank you @anthonychu

**Comment by kamalsivalingam** [comment]
@anthonychu Looks like with my plan i am not able to create support ticket. Let me know what details do you need to troubleshoot. Thanks!

**Comment by v-vish** [comment]
@kamalsivalingam Could you please share the details of the Bicep files you're using for the deployment? We’ll review them and get back to you with an update.

**Comment by kamalsivalingam** [comment]
resource feedGenerator 'Microsoft.Web/sites@2022-09-01' = {
  name: '${appNamePrefix}-afg'
  location: location
  kind: 'functionapp,linux,container,azurecontainerapps'
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userManagedIdentity}': {}
    }
  }  
  properties: {
    httpsOnly: true                    
    managedEnvironmentId: environmentId
    siteConfig: {
      linuxFxVersion: 'DOCKER|${registryServer}/feed-generator:${feedGeneratorImageTag}'
      functionAppScaleLimit: 1
      minimumElasticInstanceCount: 1      
      appSettings: [
        {
          name: 'DOCKER_REGISTRY_SERVER_URL'
          value: registryServer
        },{
          name: 'DOCKER_REGISTRY_SERVER_USERNAME'
          value: registryUsername
        },{
          name: 'DOCKER_REGISTRY_SERVER_PASSWORD'
          value: registryPassword
        },{
          name: 'FUNCTIONS_WORKER_RUNTIME'
          value: 'dotnet'
        },{
          name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
          value: appInsightsInstrumentationKey
        },{
          name: 'Database__Host'
          value: '${appNamePrefix}-db'
        },{
          name: 'Database__RequireSsl'
          value: 'false'
        },{
          name: 'EventStream__ConnectionString'
          value: eventStreamConnectionString
        },{
          name: 'EventStream__Name'
          value: environmentName
        },{
          name: 'EventStream__ConsumerGroup'
          value: 'feed-generator'
        },{
          name: 'ConfigStore__AppConfigUrl'
          value: appConfigUrl
        },{
          name: 'ConfigStore__KeyVaultUrl'
          value: keyVaultUrl
        },{
          name: 'BlobStore__ConnectionString'
          value: blobStoreConnectionString
        },{
          name: 'TableStore__ConnectionString'
          value: tableStoreConnectionString
        },{
          name: 'AzureWebJobsStorage'
          value: blobStoreConnectionString
        },{
          name: 'AZURE_CLIENT_ID'
          value: azureClientId
        },{
          name: 'FUNCTIONS_EXTENSION_VERSION'
          value: '~4'
        },{
          name: 'WEBSITE_CLOUD_ROLENAME'
          value: '${appNamePrefix}-afg'
        },{
          name: 'AZURE_FUNCTIONS_ENVIRONMENT'
          value: 'Development'
        },{
          name: 'ASPNETCORE_ENVIRONMENT'
          value: 'Development'
        },{
          name: 'AzureWebJobsScriptRoot'
          value: '/home/site/wwwroot'
        }
      ]
    }
  }
}

**Comment by kamalsivalingam** [comment]
@v-vish Should i and where can i email the all the bicep files?

**Comment by v-vish** [comment]
@kamalsivalingam You can send the details to Azure Container Apps Support acasupport@microsoft.com.

**Comment by kamalsivalingam** [comment]
Thanks for the help @v-vish. With Vaclav's help, was able to find out the root cause. Turned out the container app running azure function was trying to connect to EventHub that was being created as a post deployment step. After moving the step to create the EventHub as a predeployment step, deployment has been consistently working!

**Comment by v-vish** [comment]
@kamalsivalingam Thanks for the update! I'll go ahead and mark this as resolved since the issue has been fixed.
