### ISSUE TITLE
IMPORTANT: Dapr configuration changes for Container Apps

### ISSUE THREAD

**Issue by ruslany** [microsoft/azure-container-apps#132]
### ⚠️ UPDATE: These changes are now available in all regions ⚠️

Container Apps team is planning to enable several dapr-related enhancements to provide a more intuitive Dapr experience on Azure Container Apps based on additional research and feedback from our users. The changes are:

1. Dapr components are now globally configured for a Container Apps environment. With this change, Dapr-enabled Container Apps within an environment can share components, and Dapr scopes have been introduced so you can limit which dapr apps load each component at runtime.
2. Dapr configuration changes no longer result in a new revision and instead will trigger an automatic restart of your container app to reflect changes. For example, if you enable Dapr for your container app and are running in multi-revision mode, all revisions will be restarted to enable Dapr. Also, if Dapr appId is changed then all revisions will be restarted to use that new Dapr appId.
3. In addition to HTTP, Container Apps now supports using gRPC as the Dapr protocol.

To support these changes, we’re making the following modifications to the API resource specifications:

1. The `components` array for specifying Dapr components is removed from the `containerApp` spec.
2. Dapr components collection is added as a separate resource type under `managedEnvironment`.
3. The `dapr` section is moved to the `configuration` section of the `containerApp` spec. (It was previously under the `template` section)
4. An `appProtocol` property is added to the `dapr` section.

The changes will be available only in `Microsoft.App` namespace starting from API version `2022-01-01-preview`. The changes will take effect in March 2022. Join our [mailing list](https://groups.google.com/g/azure-container-apps) to get notified when the new functionality is available. 

### ARM template example

Refer to the [API specification](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/app/resource-manager/Microsoft.App/preview/2022-01-01-preview/DaprComponents.json) for more details.

```diff
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "containerappName": {
      "defaultValue": "mycontainerapp",
      "type": "String"
    },
    "location": {
      "defaultValue": "canadacentral",
      "type": "String"
    },
    "environment_name": {
      "defaultValue": "myenvironment",
      "type": "String"
    }
  },
  "variables": {},
  "resources": [
    {
      "apiVersion": "2022-01-01-preview",
      "type": "Microsoft.App/managedEnvironments/daprComponents",
      "name": "[parameters(environment_name)]/reddog",
      "properties": {
        "componentType": "state.azure.cosmosdb",
        "version": "v1",
        "ignoreErrors": false,
        "initTimeout": "50s",
        "secrets": [
          {
            "name": "keyname",
            "value": "keyvalue"
          }
        ],
        "metadata": [
          {
            "name": "url",
            "value": "<COSMOS-URL>"
          }
        ],
        "scopes": [
          "container-app-1",
          "container-app-2"
        ]
      }
    },
    {
      "apiVersion": "2022-01-01-preview",
      "type": "Microsoft.App/containerApps",
      "name": "[parameters('containerappName')]",
      "location": "[parameters('location')]",
      "properties": {
        "managedEnvironmentId": "[resourceId('Microsoft.App/managedEnvironments', parameters('environment_name'))]",
        "configuration": {
          "secrets": [
            {
              "name": "mysecret",
              "value": "thisismysecret"
            }
          ],
          "ingress": {
            "external": true,
            "targetPort": 80,
            "allowInsecure": false,
            "traffic": [
              {
                "latestRevision": true,
                "weight": 100
              }
            ]
          },
+         "dapr": {
+            "enabled": true,
+            "appId": "container-app-1",
+            "appPort": 3000,
+            "appProtocol": "http"
+         }
        },
        "template": {
          "revisionSuffix": "myrevision",
          "containers": [
            {
              "name": "nginx",
              "image": "nginx",
              "env": [
                {
                  "name": "HTTP_PORT",
                  "value": "80"
                },
                {
                  "name": "SECRET_VAL",
                  "secretRef": "mysecret"
                }
              ],
              "resources": {
                "cpu": 0.5,
                "memory": "1Gi"
              }
            }
          ],
          "scale": {
            "minReplicas": 1,
            "maxReplicas": 3
          },
-        "dapr": {
-           "enabled": true,
-           "appPort": 3000
-         }
        }
      }
    }
  ]
}
```

**Comment by tomkerkhove** [comment]
Was there any consideration doing to change it to use the following instead?
```diff
         "dapr": {
            "enabled": true,
+            "app": {
+              "id": "container-app-1",
+              "port": 3000,
+              "protocol": "http"
+            }
-            "appId": "container-app-1",
-            "appPort": 3000,
-            "appProtocol": "http"
         }
```

**Comment by jeffhollan** [comment]
@ruslany looking at the api-spec I think there's a missing property here. Just confirming. It wouldn't be:

```json
"secrets": [
          {
            "value": "keyvalue"
          }
        ],
```
but rather
```json
"secrets: [
{  
    "name": "value",
    "value": "keyValue"
}
]
```
Yes?

**Comment by jeffhollan** [comment]
@ruslany looking at the api-spec I think there's a typo here. Just confirming. It wouldn't be:

```json
"secrets": [
    {
      "value": "keyvalue"
    }
  ],
```
but rather
```json
"secrets": [
 {  
   "name": "value",
   "value": "keyValue" 
 }
]
````
for PUT. I assume the above is what's returned in a GET yes?

**Comment by ruslany** [comment]
@jeffhollan - thanks for pointing this out! Updated. Also you can find the working bicep template for this here: https://github.com/microsoft/azure-container-apps/blob/main/docs/templates/bicep/main.bicep

**Comment by yoshioterada** [comment]
When will it be available? I need demonstrate dapr function on the one big event.
If there is no azure CLI yet, I can't do anything in the demo.
So if you take the time for version up, could you give me some workaround.

**Comment by jeffhollan** [comment]
@yoshioterada when is your event? Shoot me a note and happy to help sort out mitigation so you can still demo. jehollan@microsoft is email

**Comment by geekwhocodes** [comment]
I am going to take a session tomorrow morning(in approx 9 hours), I have existing demo setup but I won't able to show live deployment and all :(

Using `Microsoft.App/containerApps@2022-01-01-preview` version but dapr is not getting enabled(it's not visible on the portal). 

Tried with older `Microsoft.Web/containerApps@2021-03-01` version but getting an error : 
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"WebhookInvalidParameterValue","message":"The following field(s) are either invalid or missing. Required value: template.dapr.components.scopes."}]}

```
Raw error message :

```
{
      "code": "WebhookInvalidParameterValue",
      "message": "The following field(s) are either invalid or missing. Required value: template.dapr.components.scopes."
}
```

**Comment by ruslany** [comment]
@geekwhocodes - The dapr will not be visible in portal yet. The portal support for dapr is not enabled yet. We are working on enabling that and CLI support in the upcoming weeks. Try to check the JSON view for the app in portal - if you enabled dapr for an app then it should show that under `properties.configuration.dapr`.

**Comment by geekwhocodes** [comment]
Thanks @ruslany. It is visible in resource JSON :)
