### ISSUE TITLE
Azure Function Timer trigger doesn't invoke accordingly to cron expression

### ISSUE THREAD

**Issue by kmadof** [microsoft/azure-container-apps#1320]
### Issue description
I have Azure Function written in F# (dotnet 8) deployed to Container App Environment with function trigger as below
```
module TimerFunctions =
    [<Function("TimerFunction")>]
    let Run ([<TimerTrigger("0 0 * * * *")>] timer: TimerInfo, log: ILogger) =
        Console.WriteLine("================== Hey, I am a 'TimerFunction'. I am really lazy, so I only print to console ==================")
```

Sometimes this function is not invoked.

My function is scaled to 0, but this should not be an issue [for this trigger](https://learn.microsoft.com/en-us/azure/azure-functions/functions-container-apps-hosting)
> While all triggers can be used, only the following triggers can dynamically scale (from zero instances) when running in a Container Apps environment:
> - HTTP
> - Azure Queue Storage
> - Azure Service Bus
> - Azure Event Hubs
> - Kafka
> - Timer

**Expected behavior** [What you expected to happen.]
I expected to have this function executed according to the cron expression.

**Screenshots**         
![Image](https://github.com/user-attachments/assets/a9d2332b-d99a-493e-abdb-58523437a41a)

### Additional context
Here are version of packages I use:
```
	<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.23.0" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.18.1" OutputItemType="Analyzer" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.2" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.22.0" />
```

**Comment by simonjj** [comment]
@kmadof thank you for reaching out. When you mention that executions got skipped you meant 17/10 6,7 and 9am as examples?

**Comment by raorugan** [comment]
hi @kmadof  - can you confirm if the function is deployed using Azure functions on Azure Container Apps hosting as mentioned in the link - https://learn.microsoft.com/en-us/azure/azure-functions/functions-deploy-container-apps?tabs=acr%2Cbash&pivots=programming-language-csharp

**Comment by raorugan** [comment]
Hi @kmadof , I am sorry about the issue you have faced. This is not expected behaviour of the trigger. It can scale from and to zero. May I ask you raise an issue here in the functions github repo - https://github.com/Azure/azure-functions-on-container-apps/issues

**Comment by kmadof** [comment]
> [@kmadof](https://github.com/kmadof) thank you for reaching out. When you mention that executions got skipped you meant 17/10 6,7 and 9am as examples?

Yes, that's my point.



> Hi [@kmadof](https://github.com/kmadof) , I am sorry about the issue you have faced. This is not expected behaviour of the trigger. It can scale from and to zero. May I ask you raise an issue here in the functions github repo - https://github.com/Azure/azure-functions-on-container-apps/issues

Yes of course!

**Comment by kmadof** [comment]
Here is link to new [issue](https://github.com/Azure/azure-functions-on-container-apps/issues/86)

**Comment by anthonychu** [comment]
We'll track this in the other issue. Closing this one.
