### ISSUE TITLE
Java Buildpack sample fails when deploying

### ISSUE THREAD

**Issue by graemefoster** [microsoft/azure-container-apps#1321]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting

### Issue description
Following the instructions here: https://learn.microsoft.com/en-us/azure/container-apps/quickstart-code-to-cloud?tabs=bash%2Cjava&pivots=without-dockerfile
Results in:
ERROR: failed to build: failed to write image to the following tags: [pack.local/builder/717471786c7870686765:latest: saving image "pack.local/builder/717471786c7870686765:latest": Error response from daemon: No such image: sha256:0e671222ca6fe5965ec5a37c92545434b3652ef09be0b4c390a4e5c49023bb46
Unable to run 'pack build' command to produce runnable application image: Non-zero exit code returned from 'pack build'; please check the above output for more details.
No supported builder could be used to build an image from the provided application source.

### Steps to reproduce
1. Follow instructions here: https://learn.microsoft.com/en-us/azure/container-apps/quickstart-code-to-cloud?tabs=bash%2Cjava&pivots=without-dockerfile

**Expected behavior** [What you expected to happen.]
Application should deploy as expected

**Actual behavior** [What actually happened.]
Deployment fails with above error

### Additional context
Occurred using Azure CLI

**Comment by v-vish** [comment]
@graemefoster I successfully deployed the container app following the steps outlined in the URL "https://learn.microsoft.com/en-us/azure/container-apps/quickstart-code-to-cloud?tabs=bash%2Cjava&pivots=without-dockerfile" without encountering any errors.  

![Image](https://github.com/user-attachments/assets/6d64289e-f4dd-4e41-b511-dcc9ec6a8d22)

Please ensure that you execute the "az containerapp" up command from the correct directory where the code is located. For example, I am running the command from the following path: PS C:\Users\v-vishnuu\Desktop\containerapps-albumapi-java-buildpack>.

![Image](https://github.com/user-attachments/assets/ca248e93-e06f-424a-92aa-59cbaa133dab)

**Comment by graemefoster** [comment]
Hi @v-vish,

Unsure what's going wrong on my side. I'm running from an Apple Silicon macbook-pro but that shouldn't make a difference in this case. I made sure it was a fresh unzip of the sample code.

![Image](https://github.com/user-attachments/assets/7efd9b00-aba7-4166-97ab-edbab26b03f1)

![Image](https://github.com/user-attachments/assets/e40801c4-b828-433a-bd6e-ab753f151986)

Thanks,
Graeme

**Comment by graemefoster** [comment]
@v-vish I'm also getting errors when I try and upload a jar file using the --artifact switch:

![Image](https://github.com/user-attachments/assets/3e4390ad-5418-405a-ba56-e37b5afa664f)

Just to confirm my az cli setup:

![Image](https://github.com/user-attachments/assets/60803a45-6a8c-4f0b-883e-6ca46d20c514)

**Comment by v-vish** [comment]
@graemefoster Could you please open a support ticket with Microsoft regarding the issue outlined above? You can use the following URL for reference: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request. 

If you need any further assistance, feel free to reach out to me.
