### ISSUE TITLE
Feature Request:  Improve AZ CLI docs - remove env vars

### ISSUE THREAD

**Issue by dfberry** [microsoft/azure-container-apps#1322]
**Is your feature request related to a problem? Please describe**.  
The two switches to remote env vars have the same description. Can the text be improved to differentiate the two switches? 

![Image](https://github.com/user-attachments/assets/ea8af625-6a27-4f98-84a2-b6d75a2f305d)

**Describe the solution you'd like**.    
The separated vars need an example. 

**Describe alternatives you've considered**.   

**Additional context**.

**Comment by anthonychu** [comment]
`--remove-all-env-vars` removes all the env vars, and `--remove-env-vars` removes one or more env vars that you supply. We can review how we can improve the help text, but is there a certain part that's causing the confusion?
