### ISSUE TITLE
infrastructureResourceGroup is null

### ISSUE THREAD

**Issue by vc2023** [microsoft/azure-container-apps#1323]
The issue is related to the following [#1118](https://github.com/microsoft/azure-container-apps/issues/1118) issue, which was closed.
Below is my bicep module which still returns Null.
What am I doing wrong?
Maybe workload profile is wrong?

```
param location string = resourceGroup().location
param tags object
param infrastructureSubnetId string
param name string
param logAnalyticsWorkspaceName  string
param infrastructureResourceGroup string

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' existing = {
  name: logAnalyticsWorkspaceName
}

resource managedEnvironment 'Microsoft.App/managedEnvironments@2023-05-01' = {
  name: name
  location: location
  tags: tags
  //kind: 'string'
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
    infrastructureResourceGroup: infrastructureResourceGroup
    vnetConfiguration: {
      //dockerBridgeCidr: 'string'
      //infrastructureSubnetId: infrastructureSubnetId
      internal: false
      // platformReservedCidr: 'string'
      // platformReservedDnsIP: 'string'
    }
    workloadProfiles: [
      {
        maximumCount: 5
        minimumCount: 1
        name: 'D4'
        workloadProfileType: 'D4'
      }
    ]
    // zoneRedundant: bool
  }
}


output managedEnvironmentId string = managedEnvironment.id
output staticIp string = managedEnvironment.properties.staticIp
output name string = managedEnvironment.name
output infrastructureResourceGroup string = managedEnvironment.properties.infrastructureResourceGroup
```

**Comment by v-vish** [comment]
@vc2023 Could you please provide more context on the objective of this setup? I noticed that the infrastructureSubnetId parameter is currently commented out in your Bicep file (//infrastructureSubnetId: infrastructureSubnetId). 

Would you be able to try uncommenting this line to enable the infrastructureSubnetId and test if it addresses the configuration requirements? Let us know the outcome,

**Comment by vc2023** [comment]
So subnet id(`infrastructureSubnetId`) is need.
The workloadProfiles also.
But the problem was with subnet delegations.
So it seems the delegations are needed in order for `infrastructureResourceGroup: infrastructureResourceGroup` to work.
After adding the following to the subnet, the infrastructure resource group could be created.
```
          delegations: [ 
            { 
              name: 'appServiceDelegation' 
              properties: { 
                serviceName: 'Microsoft.App/environments' 
              } 
            } 
          ]
```

**Comment by v-vish** [comment]
@vc2023 I'm glad to hear that the issue has been resolved. Could you please confirm if it’s okay for me to close this issue?

**Comment by vc2023** [comment]
@v-vish , yes you can close the issue.

**Comment by vc2023** [comment]
@v-vish I guess I can close the issue with a comment too.
