### ISSUE TITLE
SocketException: Cannot assign requested address

### ISSUE THREAD

**Issue by jsheetzmt** [microsoft/azure-container-apps#1325]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Our .NET containers are getting SocketException  `Cannot assign requested address` when making HTTP or gRPC requests. This only impacts us randomly where 100 requests go through fine and then a single request gets this error.

### Steps to reproduce
1. Unsure because the issue happens at random

**Comment by jsheetzmt** [comment]
What additional information can be provided @v-vish ?

**Comment by v-vish** [comment]
@jsheetzmt could you please confirm whether this is an app-to-app call or an external call?

**Comment by jsheetzmt** [comment]
I have examples of both.

**app-to-app call using dapr**: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: Cannot assign requested address")

**external HTTP call**: Cannot assign requested address (api-gateway.ourdomain.com:443). The api-gateway subdomain is managed in Frontdoor

Also have many examples of transient errors between container apps and Azure SQL (similar to https://github.com/microsoft/azure-container-apps/issues/1338)
