### ISSUE TITLE
Incoming and outgoing traffic when connected to custom VNet

### ISSUE THREAD

**Issue by dennishog** [microsoft/azure-container-apps#133]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Hi,

We have created a VNET with 2 subnets and connected to the environment.
We have also created a NSG connected to the app subnet.

We would like to have all outgoing traffic go through VNET (same as route all in app services), so we can use VNET / Service Endpoints to use access restrictions, in for instance, app services.
We would also like to be able to control incoming traffic through an NSG, so we can limit access to our container apps from APIM.

Neither of the above seem to be working for us at the moment. All traffic in and out from our container apps seems to bypass the VNET completely.

Is this currently supported? And, if it is, do you have any documentation describing how we should configure environment/vnet to accomplish this?

### Steps to reproduce
1. Create VNET with 2 subnets according to documentation
2. Create NSG connected to the app subnet created above and add inbound rule for limiting access
3. Create kubeenvironment connected to the 2 subnets
4. Create a container app in the environment with external ingress

**Expected behavior**
We expected incoming and outgoing traffic to go through VNET

**Actual behavior**
All traffic seem to bypass the VNET

**Comment by kendallroden** [comment]
Hi @dennishog did you create the environment with the --internal-only flag? If so, I am unsure how traffic could "bypass" the VNET. We are working on documentation for locking down ingress. Let me know on the above ? 

If you create the VNET integration without the --internal-only flag, you will get public IP address that can be accessible from the VNET or the Internet.

**Comment by kendallroden** [comment]
Closing for now due to lack of response. Please feel free to refile or reach out on discord if you run into issues!
