### ISSUE TITLE
Cannot connect to app using external environment custom vnet load balancer

### ISSUE THREAD

**Issue by dyllandry** [microsoft/azure-container-apps#1339]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A couple times I have tried to follow the tutorial [Provide a virtual network to an external Azure Container Apps environment](https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-portal) but haven't gotten it to work. I'm able to follow all the steps successfully, but the created ACA is not accessible from the public internet.

### Steps to reproduce
1. Follow all the steps in [Provide a virtual network to an external Azure Container Apps environment](https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-portal)

**Expected behavior** [What you expected to happen.]

My expectation is that by the end of the tutorial I'll be able to access the created ACA from its FQDN from the public internet.

**Actual behavior** [What actually happened.]

When I try to access the created ACA by its FQDN I receive this error in my browser:

```
The public network access on this managed environment is disabled. To connect to this managed environment, please use the Private Endpoint from inside your virtual network. To learn more https://aka.ms/PrivateEndpointTroubleshooting.
```

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
I've been using the portal to follow the tutorial.

In the [load balancer troubleshooting docs on no inbound connectivity](https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-troubleshoot#problem-no-inbound-connectivity-to-standard-external-load-balancers) it says load balancers and their public IP addresses are closed by default unless a network security group opens them. That you need to put an NSG on a subnet or network interface card.

> Standard load balancers and standard public IP addresses are closed to inbound connections unless network security groups open them. You use NSGs to explicitly permit allowed traffic. You must configure your NSGs to explicitly permit allowed traffic. If you don't have an NSG on a subnet or network interface card (NIC) of your VM resource, traffic isn't allowed to reach the resource.

But the [Securing a custom VNET in Azure Container Apps with Network Security Groups](https://learn.microsoft.com/en-us/azure/container-apps/firewall-integration?tabs=workload-profiles) say that the external workload profiles environment doesn't support NSG.

> When using an external workload profiles environment, inbound traffic to Azure Container Apps is routed through the public IP that exists in the [managed resource group](https://learn.microsoft.com/en-us/azure/container-apps/networking#workload-profiles-environment-2) rather than through your subnet. This means that locking down inbound traffic via NSG or Firewall on an external workload profiles environment isn't supported.

I tried using the load balancer torubleshooting tool under Diagnose and solve problems. I entered the LB's frontend ip, port, and the https load balancing rule's backend port and got this error:

> STD UP EXT NSG UDR solution
> Data path issues may occur due to the path being blocked by network security groups (NSG) or firewalls, or if it's misrouted.
> 
> There are two potential causes: NSG misconfiguration or UDR misconfiguration.
> 
> NSG misconfiguration
> Standard Load Balancer is secured by default and requires an explicit NSG rule allowing traffic from the original client IPs. See [Load Balancer overview](https://learn.microsoft.com/azure/load-balancer/load-balancer-overview#securebydefault).
> 
> Confirm that there is an NSG in the backend VM's subnet or NIC that explicitly allows traffic from the client IP.
> 
> To resolve this issue, add a rule with a higher priority (lower number) to allow traffic. Test this using the [Network Watcher IP flow verify tool](https://docs.microsoft.com/azure/network-watcher/network-watcher-ip-flow-verify-overview) in the Azure portal.
> 
> UDR misconfiguration
> Confirm that the effective routes of the backend network interface have the correct route for the source client IP:
> 
> For internet users, check if the next hop is set to internet. Otherwise, you'll need to confirm that there is no asymmetric routing and that firewalls in between are allowing traffic.
> 
> For Azure users, confirm that the next hop is correct and that there is no asymmetric routing.
> 
> If you're still having the issue, review the additional information in this article.

This again points to NSG issues. But I'm not sure how to proceed on configuring that correctly.

I added an NSG to the ACA environment subnet that allowed all inbound and outbound traffic and I still couldn't connect. Which possibly makes sense since the previous article said that external environments don't support NSG for inbound connections since it uses the load balancer's public IP.

**Comment by v-vish** [comment]
@dyllandry Could you please check the security group settings for your subnet and confirm if anything is being blocked? You can refer to the details of my security group for reference.
![Image](https://github.com/user-attachments/assets/71e6f3af-5f50-4bd7-864b-d26f2c7614bf)

**Comment by dyllandry** [comment]
The NSG started with the default inbound and outbound security rules. I've added one inbound and one outbound rule to allow anything. I did that to try and debug the NSG.
![Image](https://github.com/user-attachments/assets/9119ffae-90d4-44e2-a9e3-8e9410ca5e8e)

**Comment by v-vish** [comment]
@dyllandry Could you please try following the steps again for https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-portal  without creating a Load Balancer, and share the outcome with us?

**Comment by dyllandry** [comment]
I’ll try this out, but I just want to specify in case it helps, the load balancer isn’t something that I created myself. It was automatically created by azure when I create a custom vent while creating a container app. And the container apps networking docs say I shouldn’t change these managed resources or the resource group they are in.

So the closest I could get to following your instructions is to delete the managed load balancer from that resource group. Just wanted to be specific about this in case it was helpful.

The docs I’m talking about are the purple tip in this networking section and the link inside it: https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=workload-profiles-env%2Cazure-cli#custom-vnet-configuration

**Comment by dyllandry** [comment]
A support engineer was able to help me out with this today. Turns out there is another setting not mentioned in the tutorial that needs to be enabled.

While setting up the Container Apps Environment you can select "Public Network Access (preview)" and enable it.

![Image](https://github.com/user-attachments/assets/0f3361aa-41b4-435e-b4e7-b0210fcdec7d)

This can be changed in an existing Container Apps Environment as long as it wasn originally created as external. From the environment resource page click "Settings > Networking (preview)".

I really recommend adding that to the tutorial! I know the tutorial doesn't specifically list deliverables like there being a publicly available container app accessible by the time you finish the tutorial. But from my experience that is what I expected to get at the end.
