### ISSUE TITLE
Scale rule targetting service bus topic does not scale down to zero

### ISSUE THREAD

**Issue by hboiled** [microsoft/azure-container-apps#1341]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
This is sort of related to the issue described here: https://github.com/microsoft/azure-container-apps/issues/952

Except instead of queues, it's topics.

```
"scale": {
                "minReplicas": 0,
                "maxReplicas": 3,
                "rules": [
                    {
                        "name": "sb",
                        "custom": {
                            "type": "azure-servicebus",
                            "metadata": {
                                "messageCount": "1",
                                "subscriptionName": "sub",
                                "topicName": "x-test"
// I have also tried specifying the SB namespace here, like in the queue issue linked
                            },
                            "auth": [
                                {
// this is a container app secret
                                    "secretRef": "servicebusconnection",
                                    "triggerParameter": "connection"
                                }
                            ]
                        }
                    }
                ]
            },
```

### Steps to reproduce
1. Create container app (in case this is relevant, it's hosting a function app)
2. Create a scale rule as detailed above
3. After waiting 5 mins+, it does not scale to zero

**Expected behavior** [What you expected to happen.]
Scaled down to zero, as the topic is just a test topic with 0 usage right now.

**Actual behavior** [What actually happened.]
Does not scale down to zero. 

I even tried the queue example as a sanity to check to ensure it can scale down to zero, and it does work. So queue works but topics don't.

**Screenshots**         
![Image](https://github.com/user-attachments/assets/446a6665-a2cf-41e9-8526-e2e538911c23)
(it's been 2 hours for reference)

**Comment by v-vish** [comment]
@hboiled I have reproduced the issue on my end, and the app is scaling down to zero as expected. Could you please check and confirm that the subscription has zero messages? If there are any remaining messages, try deleting them to see if the app scales down to zero.

**Comment by hboiled** [comment]
> [@hboiled](https://github.com/hboiled) I have reproduced the issue on my end, and the app is scaling down to zero as expected. Could you please check and confirm that the subscription has zero messages? If there are any remaining messages, try deleting them to see if the app scales down to zero.

We realised that the topic name we were using had a ~, and that we need to reference it with a / instead to make it valid.

Happy to close this now.
