### ISSUE TITLE
Scale rule for azure service bus with user assigned identity

### ISSUE THREAD

**Issue by karpikpl** [microsoft/azure-container-apps#1344]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Creating container app with bicep does not set managed identity on the scale rule

```bicep
    scaleRules: [
      {
        // https://keda.sh/docs/2.0/scalers/azure-service-bus/
        name: 'azure-servicebus-topic-rule'
        custom: {
          type: 'azure-servicebus'
          identity: userIdentity.id
          metadata: {
            topicName: serviceBusTopicName
            subscriptionName: serviceBusSubscriptionName
            namespace: serviceBusName
            messageCount: '5'
          }
        }
      }
    ]
```

bicep: `Microsoft.App/containerApps@2024-10-02-preview`

### Steps to reproduce
1. Run bicep deployment with scale rule
2. Verify it was created correctly in azure portal

**Expected behavior** [What you expected to happen.]
Scale rule is created with user assigned managed identity.

**Actual behavior** [What actually happened.]
Managed identity is not set.

**Screenshots**         
![Image](https://github.com/user-attachments/assets/8a1676cf-8ada-40d0-b40e-98d01c1d3017)

### Additional context
Scale rule can be updated in the portal and produces exactly the same JSON as the one in the sample: `identity: userIdentity.id`.
Verified in ARM deployments that correct JSON is sent.

**Comment by perry2of5** [comment]
I've encountered a similar issue trying to set the identity with --scale-rule-identity, there it checks the box but doesn't select the identity. Perhaps that is a different issue? Or maybe it has the same root cause.

**Comment by karpikpl** [comment]
I use AZD for deployment and it seems first deployment "checks the checkbox" but identity is not selected.
Next deployment (AZD does two - one for provision, one for deployment) removes the check.

**Comment by v-vish** [comment]
@karpikpl We are currently investigating this issue. Please allow us some time, and we will get back to you with an update soon.

**Comment by karpikpl** [comment]
Thanks @v-vish 
I'm also trying to reproduce the issue where my container looks stopped after deployment with a service bus scale rule.
The scaling is setup to scale between 1 and 10 so there always should be an active service bus listener present, however my queue was full of messages and nothing was picking them up. Restarting the container app solved the issue.

I'm having some issues with reproducing it though :/

**Comment by ali-akdag** [comment]
Same issue here, but with ‘postgresql’ scaler. Was unable to utilize the scaler. Combined with the system log bug (no logs appearing), unable to conclude whether it’s a parameter problem or authentication problem (due to checkmark not working, whether it’s a GUI bug or actually not working).

**Comment by v-vish** [comment]
@perry2of5  I attempted to reproduce the issue (eastus) using the CLI, and it worked without any problems. Please refer to the screenshot below for reference:
![Image](https://github.com/user-attachments/assets/25139804-f70b-41c9-a328-32f36408c260)

Could you please retry the process by following the document below and let us know if you encounter any issues? Additionally, kindly specify the region where you are experiencing the issue
[https://learn.microsoft.com/en-us/azure/container-apps/scale-app?pivots=azure-cli#using-managed-identity-1](url)

**Comment by ali-akdag** [comment]
I have tried CLI/portal/bicep, none of them are working for the 'postgresql' scaler. Maybe it's something else, MS ticket is 2411080050003126.

CLI part:
`    --scale-rule-name "parser" `
    --scale-rule-type "postgresql" `
	--scale-rule-metadata 'host=psql-database-01.postgres.database.azure.com' `
						  'dbName=db' `
						  'port=5432' `
						  'sslmode=require' `
						  'userName=sa_mailservice' `
						  'query="SELECT COUNT(*) FROM public.log_webapi_mailservice;"' `
						  'targetQueryValue=1'`
	--scale-rule-identity "/subscriptions/<subid>/resourcegroups/rg-api-dev-01/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-psql-mailservice-dev-01"`

Bicep part:

`eventTriggerConfig: {
        parallelism: 1
        replicaCompletionCount: 1
        scale: {
          maxExecutions: 9
          minExecutions: 1
          pollingInterval: 20
          rules: [
            {
              auth: []
              identity: '/subscriptions/<subid>/resourcegroups/rg-api-dev-01/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-psql-mailservice-dev-01'
              metadata: {
                dbName: 'db'
                host: 'psql-database-01.postgres.database.azure.com'
                port: '5432'
                query: 'SELECT COUNT(*) FROM public.log_webapi_mailservice;'
                sslmode: 'require'
                targetQueryValue: '1'
                userName: 'sa_mailservice'
              }
              name: 'parser'
              type: 'postgresql'
            }`

**Comment by perry2of5** [comment]
Specifically, the box to the right of "Managed identity *" is empty and prompts you to "Select a managed identity"

**Comment by perry2of5** [comment]
I just had time to test this and I can confirm it is now working. Sorry for the earlier skepticism.

**Comment by karpikpl** [comment]
> [@karpikpl](https://github.com/karpikpl) Apologies for the delayed response. Are you encountering this issue only when using the CLI? I tried reproducing it through the Azure portal, and it worked without any issues. Could you please share your JSON configuration from the portal so I can compare it?

Hi @v-vish , apology for the delay.

I'm using bicep to deploy.

Here's what I get in the portal when I view after deployment:
```json
            "scale": {
                "minReplicas": 0,
                "maxReplicas": 10,
                "rules": [
                    {
                        "name": "azure-servicebus-topic-rule",
                        "custom": {
                            "type": "azure-servicebus",
                            "metadata": {
                                "messageCount": "5",
                                "namespace": "sb-foo",
                                "subscriptionName": "jobs",
                                "topicName": "jobs"
                            }
                        }
                    }
                ]
            },
```

where my scale rules passed to ARM

```json
[
    {
        "name": "azure-servicebus-topic-rule",
        "custom": {
            "type": "azure-servicebus",
            "identity": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-aca-sb-scale/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-djlhzkqprgdsy",
            "metadata": {
                "topicName": "jobs",
                "subscriptionName": "jobs",
                "namespace": "sb-foo",
                "messageCount": "5"
            }
        }
    }
]
```

and in the portal:
![Image](https://github.com/user-attachments/assets/39db2c83-d8eb-4f75-8456-29ecf9a945aa)

**Comment by karpikpl** [comment]
Here's the repository with full steps https://github.com/[karpikpl/aca-servicebus-scaling](https://github.com/karpikpl/aca-servicebus-scaling)
