### ISSUE TITLE
Azure Container App stops reading from Service Bus Queue

### ISSUE THREAD

**Issue by jsuchome** [microsoft/azure-container-apps#135]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I have an application deployed in Container App that is supposed to read from Service Bus queue. When it reads a message it resends it to another queue so I have some confirmation that it works. However it seems that after it reads all messages that are present in the queue right after deployment, it is not able to read any new messages that are sent to the queue later.

When I run the app locally (just as a python code) it works as expected.
When I package it in the docker container and run it locally, it works as expected.
When I use the same docker container in Azure Container Instance, it works as expected.

But when I use the same docker container in Azure Container App, it behaves differently.

### Steps to reproduce
1. Write the app using python SDK
2. Package it into docker container, push into Azure container registry
3. Deploy as Azure Container App
4. Keep sending messages to the queue and watch how (if) the app processes them

**Expected behavior**

Whenever I send new (text) message to the Service Bus queue (for example using Azure console -> Service Bus namespace -> Queues -> select queue -> Service Bus Explorer -> Send), I expect the application will log the received message and sends it to validation queue.

**Actual behavior** 

If there were messages in the queue before app deployment, they are logged and resent to the second queue. However when I send a new one right after it was deployed (and I can see in the UI that the app is running), nothing seems to happen.

### Additional context

I deployed the app via the portal, and then used the console to create new revisions.
There are no scaling rules configured.
No ingress is configured (the app does only polling, I do not need to access it from outside)
The app (actually it's last revision) is shown as running.

I posted this question here as well: https://docs.microsoft.com/en-us/answers/questions/765745/azure-container-app-stops-reading-from-service-bus.html

**Comment by jsuchome** [comment]
```python
import logging
import os
import sys

from azure.servicebus import ServiceBusClient, ServiceBusMessage

logger = logging.getLogger('DocumentParser')
logging.basicConfig(stream=sys.stdout, level=logging.INFO)

def receive_messages(test_queue, validation_queue):

    conn_str = os.getenv('AZURE_SERVICE_BUS_CONNECTION_STRING')
    if not conn_str:
        logger.error("connection string not provided!")
        return

    servicebus_client = ServiceBusClient.from_connection_string(conn_str)
    receiver = servicebus_client.get_queue_receiver(queue_name=test_queue)
    sender = servicebus_client.get_queue_sender(queue_name=validation_queue)

    receive_loop = True
    while receive_loop:
        received_msgs = receiver.receive_messages(max_message_count=1, max_wait_time=5)
        for msg in received_msgs:
            logger.info(f'received message {msg}')
            logger.info(f'sending the message to {validation_queue}...')

            message = ServiceBusMessage(str(msg))
            sender.send_messages(message)
            receiver.complete_message(msg)
            logger.info(f'message completed')

            if str(msg) == "quit":
                receive_loop = False
                logger.info("ending the loop...")

    receiver.close()
    servicebus_client.close()


if __name__ == '__main__':
    receive_messages("test_queue", "test-validation")
```

**Comment by jsuchome** [comment]
The Dockerfile:
This is NOT the real one, I removed the parts related to our product, so it might not work, I'm just editing it here to give an idea:

```
FROM python:3.7-slim

RUN apt-get clean && apt-get update -y

RUN pip install --upgrade pip
RUN pip install azure-servicebus boto3

COPY azuretest.py .

ENTRYPOINT ["python3 -m azuretest"]
```

**Comment by jsuchome** [comment]
yaml file used to create new app revision (I'm commenting out account specific data):
```
configuration:
  activeRevisionsMode: Single
  registries:
  - passwordSecretRef: <azure-registry-secret>
    server: <azure registry location>
    username: <azure registry username>
name: parser-queues-test
resourceGroup: <my-resource-group>
template:
  containers:
  - args: null
    command: null
    env:
    - name: AZURE_SERVICE_BUS_CONNECTION_STRING
      value: <connection-string-for-service-bus>
    image: <image-in-azure-registry>
    name: parser-queues-test
    resources:
      cpu: 0.5
      memory: 1Gi
  dapr: null
  revisionSuffix: null
  scale:
    maxReplicas: 10
    minReplicas: null
    rules: null
type: Microsoft.Web/containerApps```

I'm calling `az containerapp update --name parser-queues-test --yaml app.yaml` to create new app revision

**Comment by kendallroden** [comment]
The app min replica is set to 0 by default. Your app is immediately scaling to 0 after processing the initial messages. Please try setting min to 1 to keep it continuously running!

**Comment by jsuchome** [comment]
Oh, that's it, this really works! Thanks a lot, I did not notice that the replica number was set to 0 for the app.

(So I was wrong saying the "app is running")

**Comment by tomkerkhove** [comment]
I'm not sure I'm getting the issue here though - Are you using autoscaling or simply rely on the default min replicas?

**Comment by jsuchome** [comment]
I did not have any scaling rules set up, so this was default deployment setup

**Comment by tomkerkhove** [comment]
Oh OK, in that case I can see how that would help by setting to min 1 :D

**Comment by jsuchome** [comment]
Unless you want to update documentation or default values, this issue could be closed from my POV

**Comment by anthonychu** [comment]
@craigshoemaker @kendallroden Should consider this in the scaling/KEDA doc updates. How do we let folks know they need to set min replicas to 1 and possibly set up a scaler for these types of apps to function correctly?

Should also consider some warnings in our clients when an app with no ingress is deployed.

**Comment by sshquack** [comment]
Ran into this problem and I set the main count to 1. Also note that the pricing is based on if the container is active or idle. Would be good to note that in the docs as well.

![image](https://user-images.githubusercontent.com/5678459/160908193-d0fbee4a-25ca-49c9-a377-9b714dd003d8.jpeg)

**Comment by kendallroden** [comment]
We've updated the doc with this info and it will be rolling out shortly.
