### ISSUE TITLE
Unable to run a Container App Job with GPU due to a 'Backoff Limit Exceeded' error

### ISSUE THREAD

**Issue by facundoctes** [microsoft/azure-container-apps#1357]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I encountered an issue when running a Container App Job with GPU support (workload profile: Consumption-GPU-NC8as-T4, assigned resources: 8 CPUs and 56 GiB memory, West US 3). The job is triggered upon receiving a message in a queue, but the container fails to execute, logging a 'Backoff limit' error in the system log under 'Execution History.'

Interestingly, if I run the same container image in a regular Container App instead of as a Container App Job, it works perfectly without any issues.

**Expected behavior** [What you expected to happen.]
The container should process the message 

**Screenshots**         
![Image](https://github.com/user-attachments/assets/b6d94f81-9fe7-4389-9a89-8dd96318d0dd)

### Additional context
The resources were deployed using biceps files.

```
resource containerAppEnvironment 'Microsoft.App/managedEnvironments@2023-11-02-preview' = {
  name: containerAppEnvironmentName
  location: gpuResourcesLocation
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
       .....................................
    }
    workloadProfiles: [
      {
        workloadProfileType: 'Consumption'
        name: 'Consumption'
      }
      {
        workloadProfileType: 'Consumption-GPU-NC8as-T4'
        name: 'NC8as-T4'
      }
    ]
  }
}
```

```
resource ffmpegGpuEncodingContainerAppJob 'Microsoft.App/jobs@2024-02-02-preview' = {
  name: ffmpegGpuEncodingContainerAppJobName
  location: gpuResourcesLocation
  identity: {...............}
  properties: {
    environmentId: containerAppEnvironment.id
    configuration: {
      triggerType: 'Event'
      replicaRetryLimit: 0
      replicaTimeout: 36000
      eventTriggerConfig: {
        parallelism: 1
        replicaCompletionCount: 1
        scale: {
          maxExecutions: 1
          minExecutions: 0
          pollingInterval: 60
          rules: [..............................]
        }
      }
      registries: [....................]
      secrets: ..............
    }
    workloadProfileName: 'NC8as-T4'
    template: {
      containers: [
        {
          env: [.............................................]
          image: .......................................
          name: ........................................
          resources: {
            cpu: 8
            memory: '56Gi'
          }
          volumeMounts: [..............................]
        }
      ]
      volumes: [.......................................]
    }
  }
}
```

**Comment by facundoctes** [comment]
Hello, the base image I'm using is `nvidia/cuda:12.6.2-runtime-ubuntu20.04` the image size is 3.01 GB. But I also tried running the `mcr.microsoft.com/k8se/gpu-quickstart:latest` image in the container job with the same results.

**Comment by v-vish** [comment]
@facundoctes I have successfully reproduced the issue on my end by deploying a Container App Job with GPU support (workload profile: Consumption-GPU-NC8as-T4, assigned resources: 8 CPUs and 56 GiB memory, located in West US 3), and it worked without any issues.
![Image](https://github.com/user-attachments/assets/04e0b46c-96e4-4c31-85fc-5c49afa483ec)
![Image](https://github.com/user-attachments/assets/465c27b9-b41a-4678-b0b6-3c9f7a2a2546)
Could you please confirm if you are still facing the problem? If so, kindly retry and let us know the updated status.
