### ISSUE TITLE
How to access the server running in a Sidecar Container from First Main Container in Azure Container Apps?

### ISSUE THREAD

**Issue by PannagadharaKS** [microsoft/azure-container-apps#1361]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I deployed 2 Containers in 1 Container App:, 1st container which is running a nodejs application and a sidecar container which is running an apache ignite server.

Ports used in 1st Container [Nodejs] : 3000
Ports used in 2nd Container [Apache Ignite]: 10800

I tried many ways as host for Apache Ignite i.e.:
0.0.0.0:10800
<NAME_OF_CONTAINER>:10800

But , still it says ENOTFOUND / ECONNREFUSED  [Screenshot is attached below]

### Steps to reproduce
1. Deploy 2 Containers in Azure Container App, one for nodejs and another for apache-ignite [Public Docker Registry]
2. Add Host for connecting Apache Ignite in Nodejs App

**Expected behavior** [What you expected to happen.]
Nodejs [1st Container] should be able to access Apache Ignite [2nd Container].

**Actual behavior** [What actually happened.]
1st Container is unable to access 2nd Container

**Screenshots**         
![Image](https://github.com/user-attachments/assets/318610be-71fc-4645-83a7-bc391d0d4d54)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
Occured & Viewed in Azure Portal / Azure Container App / Monitoring / Log Stream

**Comment by v-vish** [comment]
@PannagadharaKS Sidecar containers share the same network host as the main container, meaning the main container (and other sidecar containers) can access any port on the sidecar using localhost:<port>. It seems you're currently using the IP 0.0.0.0:10800. Could you try using localhost:10800 or 127.0.0.1:10800 instead and let us know the result?

You can refer below document for the configuration of sidecar containers: https://learn.microsoft.com/en-us/azure/app-service/tutorial-custom-container-sidecar

**Comment by PannagadharaKS** [comment]
![Image](https://github.com/user-attachments/assets/7020e3c7-fb80-4c70-8cb4-44eaee14ea71)
![Image](https://github.com/user-attachments/assets/44c4e1a2-fc9c-45fd-9d46-e64053dcde89)


As seen in the screenshot , tried with 127.0.0.1:10800 & 0.0.0.0:10800, but still getting the same error.
But when i started the apache ignite server in my local with the same 127.0.0.1:10800 config, it connected, maybe because of same machine!?

**Comment by PannagadharaKS** [comment]
Update : I deployed the apache ignite container privately using Dedicated Repo + Azure Container Registry instead of Public Docker image and then added necessary configurations needed in that Apache Ignite Container for exposing 10800. 
After that I tried to connect in first main container. And it worked!

@v-vish Thanks for your time on this issue!

**Comment by v-vish** [comment]
@PannagadharaKS I'm glad it worked for you! Can we go ahead and close this issue?

**Comment by PannagadharaKS** [comment]
Sure! We can close it.
