### ISSUE TITLE
Secrets "sh.helm.release.v1.k8se.v26" not found

### ISSUE THREAD

**Issue by kamalsivalingam** [microsoft/azure-container-apps#1362]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Deploying Azure Container Environment is failing with OperationFailed related to updating environment chart handler
secrets "sh.helm.release.v1.k8se.v26" not found

### Steps to reproduce
1. Deploy Azure Container Environment

**Expected behavior** [What you expected to happen.]
Azure Container Environment is created

**Actual behavior** [What actually happened.]
Getting below error
Update environment chart handler failed: Error running Helm upgrade --install k8se ./k8se --namespace k8se-system --create-namespace --set containerAppController.enableDefaultProbeForConsumptionV2=true --values C:\local\Temp\tmp4g042k.tmp
output: 

error: Error: UPGRADE FAILED: update: failed to update: secrets "sh.helm.release.v1.k8se.v26" not found

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by v-vish** [comment]
@kamalsivalingam Could you please provide more information so we can troubleshoot this issue further? How are you attempting to create the container environment—via the CLI or the Azure Portal? If you're using the CLI, could you share the command you're running and a screenshot of the error you're encountering? Also, please let us know the region where you're facing this issue.
