### ISSUE TITLE
System-assigned managed identity for ACA

### ISSUE THREAD

**Issue by bengeset96** [microsoft/azure-container-apps#137]
When is the plan to have system-assigned identity supported for ACA?

Currently granting ACA access to the admin user for the ACR, but this is really starting to become a security concern of mine. 

It would be really nice to grant ACA some sort of JEA for ACR =)

/Benjamin

**Comment by christiannagel** [comment]
this is already on the roadmap, see #16

**Comment by bengeset96** [comment]
Thank you @christiannagel
