### ISSUE TITLE
Custom VNET, slim down size of subnets requirement?

### ISSUE THREAD

**Issue by bengeset96** [microsoft/azure-container-apps#139]
When using custom VNET for ACA, following requirment is needed:

__Additionally, subnets must have a size between /21 and /12.__

Is there any plan in the future to slim this down? In many cases it is not possible to ask for something that large, both in terms of security and for small ACA deployments. 

I believe this is due to Azure CNI. If this is limitation, will we see Kubenet support in the future for overlay networking? 

This is currently a big deal breaker =( 

/Benjamin

**Comment by torosent** [comment]
@bengeset96, we are planning to reduce the subnet size requirement and change to only one required subnet.

**Comment by bengeset96** [comment]
Great news @torosent! 

Looking forward to that.

/Benjamin

**Comment by jvaca92** [comment]
Do you know what minimum range will be required and when we can expect implementation of this feature ?

**Comment by ezYakaEagle442** [comment]
@torosent so what will be the subnet size requirement ?

I have a customer that would need to deploy to a VNet, as he also considers that the IP Range is too large the ACA Env. will be shared accross several Dept./Teams/Apps.

Is there any plan to leverage some of the AKS features ?  like : 

- [Dynamic allocation of IPs and enhanced subnet support - in preview](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support-preview)
- [Add a node pool with a unique subnet - in preview)](https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#add-a-node-pool-with-a-unique-subnet-preview)

**Comment by kendallroden** [comment]
We have updated to require only a single /23 subnet. @jvaca92 
@ezYakaEagle442 we have plans in the future to reconsider ways to optimize the networking.
Will close this for now, as there is a new issue which reiterates this request based on the new subnet sizing https://github.com/microsoft/azure-container-apps/issues/247 

Feel free to follow that thread if you are in agreement

**Comment by anrub** [comment]
@kendallroden sounds like it is not on a high priority, should we better plan with some workarounds or is it something that can be considered in, say e.g. within this year? e.g. on the app service delegated subnets, we use /28 subnets for small cases - will something like this ever be possible?

**Comment by bengeset96** [comment]
@anrub 

/23 is still way too big. Seems like AKS with kubenet will still have to be used until the subnet gets slimmed down even further.

**Comment by chriswangelin** [comment]
@torosent 

[This doc](https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-cli#networking-parameters) leads me to believe that the minimum ACA vnet size is determined not only by the infrastructure subnet size but also the minimum platform-reserved-cidr (/21 minimum) and docker-bridge-cidr (/28 minimum) values: 

"The platform-reserved-cidr and docker-bridge-cidr address ranges can't conflict with each other, or with the ranges of either provided subnet. Further, **make sure these ranges don't conflict with any other address range in the VNET**."

Thus, the VNET to which ACA is connected must minimally accommodate:
- /23 for the infrastructure subnet
- /21 for platform-reserved-cidr
- /28 for docker-bridge-cidr

Am I understanding this correctly?

**Comment by khaliddermoumi** [comment]
Looks like updating the docs was forgotten, they still state /21 is required: https://learn.microsoft.com/en-us/azure/container-apps/networking#ports-and-ip-addresses

BTW /23 is still too large. /25 or /26 should be doable.
