### ISSUE TITLE
Error passing parameters --environment-variables

### ISSUE THREAD

**Issue by ramonduraes** [microsoft/azure-container-apps#14]
Hi Team,

I'm trying to pass my parameters as I already use in the docker but it's failing. I have the block called 'app' where I have my internal parameters. 

**Docker Sample**
-e app= 'MyInternalValue=3,myname=true'
-e db= 'Load=true, othervalue=true'

az containerapp create -n $app -g $group -e $appenv -i $myimage  --registry-login-server $myimagelogin
 --registry-username $acrid --registry-password $acrkey --target-port 80 --ingress 'external' --query configuration.ingress.fqdn -v app='MyInternalValue=3,myname=true'
 
 Result:
 Environment variables must be in the format "<key>=<value>,<key>=secretref:<value>,...".
 
 Note:
  I believe the rule should not validate my internal value 'MyInternalValue=3,myname=true'

**Comment by calvinsID** [comment]
Hi @ramonduraes , thanks for reporting the bug. As an immediate mitigation, please use the create command using a yaml configuration (`--yaml` parameter). We will work on a bugfix for environment variables with "," and "=" characters in the value

**Comment by ramonduraes** [comment]
Hi @calvinsID Thanks. Do you have an example of this yaml?

**Comment by calvinsID** [comment]
This is fixed in the new CLI extension, secrets/env variables are now space delimited
