### ISSUE TITLE
Unable to connect to new Container App

### ISSUE THREAD

**Issue by charris-msft** [microsoft/azure-container-apps#140]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduce
1. follow [Quickstart ](https://docs.microsoft.com/en-us/azure/container-apps/get-started?ocid=AID3042118&tabs=powershell) and create container app in canadacentral via CLI using PowerShell

**Expected behavior** [What you expected to happen.]
I expected to be able to view the new app in a browser

**Actual behavior** [What actually happened.]
The browser timed out (multiple times over 12+ hours)
![image](https://user-images.githubusercontent.com/74415662/159481819-df8ca5d5-144d-440a-92b1-fa52ff2bd0f9.png)

**Screenshots**         
There is a full video here: [Deploy a Python app to Azure Container Apps](https://msit.microsoftstream.com/video/e9e80840-98dc-997d-44c0-f1eca9715185)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
CLI

Here's some additional information.
The Container App above that is failing is located here:
Resource Group: [charris-container-app01](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/1163fbbe-27e7-4b0f-8466-195fe5417043/resourceGroups/charris-container-app01/overview)
Container app: https://[my-container-app.blackcliff-4e19c3d1.canadacentral.azurecontainerapps.io](https://my-container-app.blackcliff-4e19c3d1.canadacentral.azurecontainerapps.io/)/

I created a 2nd container app in the same RG, and it is also failing due to timeout.

This morning, I created a new container app in a new RG, but same region (canadacentral) and this one is working:
Resource Group: [charris-container-app2](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/1163fbbe-27e7-4b0f-8466-195fe5417043/resourceGroups/charris-container-app2/overview)
Container app: https://charris-containerapp2.happyriver-56be0df4.canadacentral.azurecontainerapps.io/

**Comment by charris-msft** [comment]
Here is the subscription ID: 1163fbbe-27e7-4b0f-8466-195fe5417043
The env name in both RGs is: my-environment

**Comment by adjentz** [comment]
@charris-msft Once you were able to get a container app going, do you know if subsequent creations also worked?

I've tried doing the quickstart with both portal and cli, tried across many different resource groups, environments , etc. (mostly trying to stick to Central Canada, but I tried others as well).
but all of my container apps give me the same timeout.

most recent attempt here: https://asdlfl.mangobush-60d3a0c5.canadacentral.azurecontainerapps.io

I was hoping that waiting long enough to give it all some breathing room and then maybe creating yet another new one would end up working, but to no avail as of yet.

**Comment by xwang971** [comment]
Hi, sorry for the inconvenience. The issue was caused by the reourses migration. It has already been resolved. Can you please have a try?
