### ISSUE TITLE
Feature Request: Add https:// to the fqdn of the container app in the CLI output

### ISSUE THREAD

**Issue by charris-msft** [microsoft/azure-container-apps#141]
**Is your feature request related to a problem? Please describe**.  
No

**Describe the solution you'd like**.    
When I run `az containerapp create` it should return a URL including https:// rather than just a fqdn. With a URL, I can ctrl+click the url in the CLI (at least in Windows Terminal) to open the browser, rather than needing to copy the fqdn, open a browser, then paste the fqdn.

**Describe alternatives you've considered**.   

**Additional context**.  
![image](https://user-images.githubusercontent.com/74415662/159482935-ad40a431-2414-47bf-abae-9bcb9210d047.png)

**Comment by simonjj** [comment]
closing this issue, we now display both protocol and fqdn on create when you enable ingress.
