### ISSUE TITLE
Feature Request: Quickstart should take advantage of param-persist to reduce keystrokes

### ISSUE THREAD

**Issue by charris-msft** [microsoft/azure-container-apps#142]
**Is your feature request related to a problem? Please describe**.  
I ran through the quickstart twice. The first time I typed all of the commands and parameters, taking advantage of tab-completion in PowerShell for the variables. The second time I took advantage of param-persist and only typed --resource-group $RESOURCE_GROUP and --location $LOCATION once.

The first time it took 899 keystrokes. The second time it took only 795 keystrokes. (Reduction of about 12%)

This not only reduced the keystrokes, and the time to complete the quickstart, but it also reduced the opportunity for typos that would have further slowed me down.

**Describe the solution you'd like**.    
I would like to see the Quickstart provide a description of how param-persist works near the top, and then eliminate all --resource-group and --location parameters where possible.

**Describe alternatives you've considered**.   

**Additional context**.

**Comment by simonjj** [comment]
Chris, I am not familiar with params-persist could you maybe submit a PR against the docs. Closing now.

**Comment by charris-msft** [comment]
@simonjj - 

https://techcommunity.microsoft.com/t5/azure-tools-blog/boosting-your-in-tool-productivity-with-azure-cli/ba-p/1700710#:~:text=Similar%20to%20how%20one%20could%20use%20the%20basic,arguments%20in%20CLI%20commands%20once%20they%E2%80%99ve%20been%20declared.

```
az config param-persist -h

Group
    az config param-persist : Manage parameter persistence.
        Command group 'config' is experimental and under development. Reference and support
        levels: https://aka.ms/CLI_refstatus
Commands:
    delete : Delete parameter persistence data.
    off    : Turn off parameter persistence.
    on     : Turn on parameter persistence.
    show   : Show parameter persistence data.
```
