### ISSUE TITLE
The --ingress argument does not have a Default value described in the --help description

### ISSUE THREAD

**Issue by charris-msft** [microsoft/azure-container-apps#144]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The --ingress argument does not have a Default value described in the --help description

### Steps to reproduct
1. `az containerapp create --help`

**Expected behavior** [What you expected to happen.]
`--ingress` has a Default value described. 
Generally speaking, the default should be "secure-by-default", which would be `internal` in this case

**Actual behavior** [What actually happened.]
`--ingress` does not have a Default value described 

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by kendallroden** [comment]
Can we add a default value to the ingress if possible so users know what is set by default? @anthonychu
