### ISSUE TITLE
Ingress Proxy Support

### ISSUE THREAD

**Issue by Falven** [microsoft/azure-container-apps#148]
### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

1. Is it possible for the Azure Container Apps HTTPS ingress, in its current form, to accept HTTP CONNECT verb requests and forward them to the individual proxy servers for load balancing?
2. Can the Azure Container Apps load balancing be replaced with a Load Balancer which operates at layer 4 using NAT rather than layer 7 in order to make the load balancing protocol agnostic and allow our proxy servers to work?
3. Do the Azure Container Apps containers have internet access? That is to say, can they forward our proxy requests to arbitrary internet endpoints? Could this be what’s standing in the way of us operating in the current configuration?
4. Is there anything else we can do to get a working cloud proxy environment using Azure Container Apps?

### Steps to reproduct
1. .. Host a containerized proxy server in Azure Container Apps such as [this apache proxy](https://hub.docker.com/repository/docker/falven/proxy-apache) [or this squid proxy](https://hub.docker.com/repository/docker/falven/proxy-squid)
2. .. Attempt to use the proxy server for ex, via wget

`https_proxy=https://proxy-squid.politecoast-f3865209.westeurope.azurecontainerapps.io:3128 wget https://www.bing.com`

**Expected behavior** [What you expected to happen.]

The proxy should work. Wget should download the page.

**Actual behavior** [What actually happened.]

Connection times out.

**Comment by ahmelsayed** [comment]
Hi @Falven,

As mentioned on IM: 

Yes, http CONNECT won’t work. 
HTTP containerApps on a given environment share the same public IP and are routed based on their Host/Authority. CONNECT semantics for Host/Authority are different, the Host/Authority is that of the target of the CONNECT, not the app itself (as you show below). Supporting that with an L7 load balancer is tricky. We are working on adding TCP transport option for containerApps ingress. Once that’s available, you will be able to use that to get a connect proxy to work.

**Comment by kendallroden** [comment]
closing with announcement of TCP support
