### ISSUE TITLE
Empty environment variable is unset in Container App

### ISSUE THREAD

**Issue by jsuchome** [microsoft/azure-container-apps#149]
### This issue is a: 
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When deploying an app, I passed one of my environment variables with an empty value (`""`). However it the application it seems that the variable was not visible at all, and by checking with `az containerapp show` the value is seen as nil (I think - I don't have it by me right now). These are however distinct cases; see for example the behavior of python's `os.environ["MYVAR"]` which correctly sets the variable to empty string if it is empty, but raises an exception when it is not set at all.

### Steps to reproduct
1. Use the yaml file with the env variable set to empty string 
2. `az containerapp update ...`

**Expected behavior** 

Variable is found as empty.

**Actual behavior**

Variable is seen as unset.

**Comment by SophCarp** [comment]
Backlog work item: # 17760693

**Comment by simonjj** [comment]
We have this fixed now! Closing.
