### ISSUE TITLE
Yaml specification documentation

### ISSUE THREAD

**Issue by ramonduraes** [microsoft/azure-container-apps#15]
Hi Team

I'm try this command:
 az containerapp create --yaml ...

The link is broken 
"kubeEnvironmentId is required. Please see https://github.com/microsoft/k4apps/wiki/WorkerApps-ARM-API-Specification for a valid containerapps YAML spec."

Where can I find documentation?

**Comment by SatyKrish** [comment]
> Where can I find documentation?

I couldn't find `yaml` spec either. I used `az containerapp show --output yaml`  as reference and came up with this example here - https://github.com/microsoft/azure-container-apps/issues/9#issuecomment-963283933

**Comment by calvinsID** [comment]
We've added a sample YAML configuration here: https://docs.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec#examples. I'll also have this link in the CLI help text (where applicable) in the next CLI version

**Comment by larryclaman** [comment]
/reopen

@calvinsID I had the same question as the OP (where is the YAML specification) and I found this thread after searching.

Appreciate that you added a sample YAML config to the docs at https://docs.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec#examples , but my question remains: where is the YAML specification for the container app config?  It should be part of docs.microsoft.com and/or part of this repo (https://github.com/microsoft/azure-container-apps).
