### ISSUE TITLE
Feature Request: documentation that outlines the difference compared to Webapps for Containers

### ISSUE THREAD

**Issue by johnknoop** [microsoft/azure-container-apps#150]
If there already exists some help page that explains when you would choose Azure Container Apps over Webapps for Containers, then can you add a link to it? Otherwise, please create such a page that helps poeple choose which one best fits their usecase.

**Comment by BigMorty** [comment]
We have this page - https://docs.microsoft.com/en-us/azure/container-apps/compare-options
