### ISSUE TITLE
Announcement: Azure Container Apps CLI extension for Microsoft.App namespace

### ISSUE THREAD

**Issue by anthonychu** [microsoft/azure-container-apps#152]
A few weeks ago, we [announced](https://github.com/microsoft/azure-container-apps/issues/109) that we're migrating existing Azure Container Apps from the `Microsoft.Web` namespace to `Microsoft.App` (follow the progress [here](https://github.com/microsoft/azure-container-apps/issues/109)). You don't need to wait to start creating new Container Apps resources in `Microsoft.App` — you can do that today. We've released a new version of the Azure CLI extension for Azure Container Apps that lets you create and manage apps in the new namespace.

_The Azure Container Apps CLI extension is currently in preview. Expect changes as we continue to add features and improvements in the coming months._

## What's new?

Here are some of the bigger changes in this version of the CLI extension. Keep in mind that there are many more smaller updates. Add `--help` after any command to read about how to use it.

* The extension is now available as a public Azure CLI extension. This means you can install and update it using simpler commands (see below).

* This version only works with apps in the `Microsoft.App` namespace. If you also have `Microsoft.Web` Container Apps resources, you'll need to switch between the `Microsoft.Web` and `Microsoft.App` versions of the CLI extension until we migrate all the apps in your subscription to `Microsoft.App`.

* `az containerapp env create` now automatically creates a Log Analytics workspace if one is not supplied.

* `az containerapp create` includes some improvements, including:
    - The command is idempotent.
    - The app is created in single revision mode by default.
    - Secrets and environment variables are now set using space separated name/value pairs, consistent with other CLI commands.

* `az containerapp update` has been simplified to focus on managing settings in your app's template.
    - For an app in single revision mode, it updates the app.
    - For an app in multiple revision mode, it creates a new revision based on the latest revision. To base changes on another revision, use the new `az containerapp revision copy` command.

* To manage specific features, we've added several task-specific subgroups, including `ingress`, `revision`, and `secret`.

* There's are new `dapr` and `env dapr-component` subgroups. We recently [announced](https://github.com/microsoft/azure-container-apps/issues/132) some changes to how Dapr is integrated with Azure Container Apps. These new subgroups contain commands for working with Dapr.

## Installation

Before installing any version of the Azure Container Apps CLI extension, ensure you've removed any previously installed versions:

```bash
az extension remove -n containerapp
```

### Install the latest `Microsoft.App` version

```bash
az extension add -n containerapp
```

### Install the previous `Microsoft.Web` version

```bash
az extension add \
  --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.4-py2.py3-none-any.whl
```

## Resources

* [Azure Container Apps CLI reference](https://docs.microsoft.com/cli/azure/containerapp?view=azure-cli-latest&preserve-view=true) (new!)
* [Updated quickstart](https://docs.microsoft.com/azure/container-apps/get-started?tabs=bash)

## Feedback and questions

Let us know if you have any questions or feedback by [opening an issue](https://github.com/microsoft/azure-container-apps/issues).

**Comment by adeturner** [comment]
Great news, I can confirm http apps are working fine. I however have a question about keda scaling .... which seems to have disappeared

It is referenced here in Nov: 
https://github.com/microsoft/azure-container-apps/issues/42 shows --scale-rules

but with the new release...
$ az containerapp update -n ${CONTAINERAPP_NAME} -g ${FRONTEND_RESOURCE_GROUP} --scale-rules $SCALE_RULES_FILE
unrecognized arguments: --scale-rules rules.yaml

Am I missing something? Thanks
