### ISSUE TITLE
Authentication Required when attempting to pull from Docker Private Repository 

### ISSUE THREAD

**Issue by comment-it-out** [microsoft/azure-container-apps#154]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Attempt to pull images from Docker Private Repository results in "UNAUTHORIZED" with "authentication required" error

### Steps to reproduct
Enter the following command
az containerapp create --name myapp --resource-group myresource --image myprivaterepo/myapp:latest --environment myenv --registry-server docker.io --registry-username [username] --registry-password [password]

**Expected behavior** [What you expected to happen.]
The container to be deployed

**Actual behavior** [What actually happened.]
The following error occured
The following field(s) are either invalid or missing. Invalid value: "myprivaterepo/myapp:latest": GET https://index.docker.io/v2/privaterepo/myapp/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:privaterepo/myapp Type:repository]]: template.containers.myapp.image.
**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal? Both CLI and Portal have the same error.

**Comment by BetzaidaGp12** [comment]
Where you able to fix it?

**Comment by rcangus** [comment]
Have the same issue but using the Azure Container Registry as part of the tutorial (https://docs.microsoft.com/en-us/azure/container-apps/communicate-between-microservices?tabs=bash&pivots=acr-remote)

As well as this, the tutorial does not set the FRONTEND_NAME variable. Minor I know but will cause a bit of confusion for first timers (IMO)

**Comment by ahmelsayed** [comment]
For ACR you should be able to use managed identity for authentication, so it should just work without needing to pass a password. 

For external registries, like dockerhub, you'll need to set a registry auth on the container app. It should be 

```
az containerapp registry set -g {resourceGroup} -n {appName} --server {registryDomain} --username {userName} --password {password}
```

for dockerhub in particular the registry domain should be `--server index.docker.io`. You can still refer to dockerhub images with `{repo}/{imageName}` or `docker.io/{repo}/{imageName}` or `index.docker.io/{repo}/{imageName}`
