### ISSUE TITLE
Querying the state does not work in Azure Containers App

### ISSUE THREAD

**Issue by sergiibielskyi** [microsoft/azure-container-apps#155]
Hi team,
I am trying to find the solution to how to get results from state storage by using a specific query, not just getting item by id. I found a good explanation here https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-state-query-api/. And I prepared method to use query state.

CancellationTokenSource source = new CancellationTokenSource();
CancellationToken cancellationToken = source.Token;

    var query = "{" +
            "\"filter\": {" +
                "\"EQ\": { \"value.style\": \""+ style +"\" }" +
            "}" +
        "}";
var queryResponse = await daprClient.QueryStateAsync<dynamic>(storeName, query, cancellationToken: cancellationToken);

Locally, it works. But when I try to publish that into the Azure Containers App I see 500 error.

I assume, probably Azure Containers App service doesn't have the right Dapr runtime but I can not prove it.
Any ideas?

App logs info below,
Dapr.DaprException: Query state operation failed: the Dapr endpointed indicated a failure.
See InnerException for details. ---> Grpc.Core.RpcException: Status(StatusCode="Unknown",
Detail="cannot proxy request: missing dapr-app-id metadata")
at Dapr.Client.DaprClientGrpc.QueryStateAsync[TValue](String storeName, String jsonQuery,
IReadOnlyDictionary2 metadata, CancellationToken cancellationToken) --- End of inner exception stack trace --- at Dapr.Client.DaprClientGrpc.QueryStateAsync[TValue](String storeName, String jsonQuery, IReadOnlyDictionary2 metadata, CancellationToken cancellationToken)
at mart.cosmosdb.ObjectController.GetObjectsByQuery(String style)
in /cosmosdb/mart-api-cosmos-db/Controllers/ObjectController.cs:line 38
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.
TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper,
ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.
g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker. <InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)

**Comment by sergiibielskyi** [comment]
Also, I just added metadata but still have an error.
`CancellationTokenSource source = new CancellationTokenSource();
        CancellationToken cancellationToken = source.Token;
        var metadata = new Dictionary<string, string>
        {
            { "dapr-app-id", "cosmosdbapp" }
        };
        
        var query = "{" +
                "\"filter\": {" +
                    "\"EQ\": { \"value.style\": \""+ style +"\" }" +
                "}" +
            "}";
        
        var queryResponse =  await daprClient.QueryStateAsync<dynamic>(storeName, query, metadata, cancellationToken: cancellationToken);`

**Comment by ahmelsayed** [comment]
@sergiibielskyi can you share what your `configuration` section in the ContainerApp resource looks like as well as what your dapr component looks like.

**Comment by sergiibielskyi** [comment]
> @sergiibielskyi can you share what your `configuration` section in the ContainerApp resource looks like as well as what your dapr component looks like.

Sure,
resource cosmosDBComponent 'Microsoft.App/managedEnvironments/daprComponents@2022-01-01-preview' = {
  name: '${environmentName}/cosmosdb'
  properties: {
    componentType: 'state.azure.cosmosdb'
    version: 'v1'
    secrets: [
      {
        name: 'cosmos-key'
        value: cosmosKey
      }
    ]
    metadata: [
      {
        name: 'url'
        value: cosmosdbUrl
      }
      {
        name: 'database'
        value: cosmosDBName
      }
      {
        name: 'collection'
        value: collectionName
      }
      {
        name: 'masterkey'
        secretRef: 'cosmos-key'
      }
    ]
    scopes: [
      cosmosdbapp.name
    ]
  }
}

resource cosmosdbapp 'Microsoft.App/containerapps@2022-01-01-preview' = {
  name: 'cosmosdbapp'
  location: location
  properties: {
    managedEnvironmentId: environmentId
    configuration: {
      ingress: {
        external: false
        targetPort: 80
      }
      registries: [
        {
          server: containerRegistry
          username: containerRegistryUsername
          passwordSecretRef: 'registry-key'
        }
      ]
      secrets: [
        {
          name: 'registry-key'
          value: registrySecretRefName
        }
      ]
      dapr: {
        enabled: true
        appPort: 80
        appId: 'cosmosdbapp'
      }
    }
    template: {
      containers: [
        {
          image: imagePath
          name: 'cosmosdbapi'
          resources: {
            cpu: '0.5'
            memory: '1Gi'
          }
        }
      ]
      scale: {
        minReplicas: 1
        maxReplicas: 1
      }
    }
  }
}

**Comment by sergiibielskyi** [comment]
Also, tested by adding apiVersion: 'dapr.io/v1alpha1' to properties but it was nothing changed

**Comment by sergiibielskyi** [comment]
Hey @ahmelsayed, any updates from your side? What I did wrong?

**Comment by tjoudeh** [comment]
The problem is still there even though the Container Apps is using dapr v1.7.3. 

I can't query Cosmos DB store when deploying to Azure container apps, while query cosmos db works fine when I self-host dapr on my machine with no issues. Other operations such as GET/PUT/Delete/Post are working fine in container apps with cosmos state store.

This is the exception I'm receiving 

```
Dapr.DaprException: Query state operation failed: the Dapr endpointed indicated a failure. See InnerException for details.
 ---> Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Not Implemented")
 at Dapr.Client.DaprClientGrpc.QueryStateAsync[TValue](String storeName, String jsonQuery, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
 --- End of inner exception stack trace ---
```
My query is very simple, like the below

```
            var query = "{" +
                   "\"filter\": {" +
                       "\"EQ\": { \"taskCreatedBy\": \"" + createdBy + "\" }" +
                   "}}";

            var queryResponse = await _daprClient.QueryStateAsync<TaskModel>(STORE_NAME, query);

            var tasksList = queryResponse.Results.Select(q => q.Data).OrderByDescending(o=>o.TaskCreatedOn);

            return tasksList.ToList();
```
Here is my state store yaml used for azure container apps deployment

```
componentType: state.azure.cosmosdb
version: v1
metadata:
- name: url
  value: https://<url>.documents.azure.com:443/
- name: masterkey
  secretRef: cosmoskey
- name: database
  value: tasksmanagerdb
- name: collection
  value: taskscollection
secrets:
- name: cosmoskey
  value: <value>
scopes:
- tasksmanager-backend-api
```
Here is my state store yaml used locally to test dapr on my machine
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: https://<url>.documents.azure.com:443/
  - name: masterKey
    value: <value>
  - name: database
    value: tasksmanagerdb
  - name: collection
    value: taskscollection
scopes:
- tasksmanager-backend-api   
```

![image](https://user-images.githubusercontent.com/3114431/184274259-e6392f29-4c13-40d2-a312-2f0167526efc.png)
FYI @ahmelsayed @torosent

**Comment by torosent** [comment]
@ItalyPaleAle Can you help with this issue?

**Comment by ItalyPaleAle** [comment]
@tjoudeh Thanks for the report.

Can you confirm if while running in Container Apps you can connect to Cosmos DB? I understand that querying doesn't work, but are you able to perform operations to get or set a state?

**Comment by tjoudeh** [comment]
Thanks @ItalyPaleAle for reaching out, as I stated in my comment, all other operations such as GET by id, POST, DELETE, etc.. are working fine with no issues on container apps. Only query the collection is throwing this exception. Yet when running the app self hosted on my machine the query works fine with no issues, so I believe it's something related to container apps hosting. I'm using the latest .net core dapr sdks too.

**Comment by ItalyPaleAle** [comment]
Thanks for confirming @tjoudeh . As you confirm that, I believe we have identified the root cause of the issue and are working on a fix. The issue in upstream Dapr is here: https://github.com/dapr/dapr/pull/5008 I am working with @torosent and his team to understand how we can ship this to CApps as soon as feasible.

**Comment by tjoudeh** [comment]
Perfect, thank you so much, happy to early test this of there is a preview version which will be shipped soon, please consider looking into the **order by** part too as its not working on self hosted dapr application and most probably on CApps too 😀

**Comment by ItalyPaleAle** [comment]
Can you please open an issue on for that in http://github.com/dapr/components-contrib and we'll look into it :)

**Comment by tjoudeh** [comment]
Sure thing, will do on Sunday 👊

**Comment by akshat172** [comment]
the issue is still there 

![image](https://user-images.githubusercontent.com/26165605/185820423-31aeb263-022b-4cfd-8a1b-391781ea7d4d.png)
![image](https://user-images.githubusercontent.com/26165605/185820435-6ee632f7-459c-4594-ba10-19fd2fcdb74d.png)

**Comment by ItalyPaleAle** [comment]
@akshat172 Yes, the rollout of the fix hasn't been completed yet. It may take another week or two.

**Comment by akshat172** [comment]
> @akshat172 Yes, the rollout of the fix hasn't been completed yet. It may take another week or two.

Ok Great thanks for the update. Will wait for the fix to be released.

**Comment by ItalyPaleAle** [comment]
I believe the updated version of Dapr should be available in all Azure regions now. If it’s still not working for you, can you please let us know?

**Comment by akshat172** [comment]
> I believe the updated version of Dapr should be available in all Azure regions now. If it’s still not working for you, can you please let us know?

@ItalyPaleAle I deployed my code this morning, I was still getting that gRPC unimplemented error.

**Comment by akshat172** [comment]
![image](https://user-images.githubusercontent.com/26165605/187845615-ae3b0a36-0de2-4047-86cd-0fb519b6d67e.png)
I redeployed my code and still getting this error

This is how I am calling the Dapr Query Async function
![image](https://user-images.githubusercontent.com/26165605/187846155-beedbffb-51cd-4119-ab2b-292587a9ead0.png)

**Comment by ItalyPaleAle** [comment]
You are right, I just checked and the fix hasn’t rolled out yet. It will be in Dapr version 1.8.4-msft-2 (you’re still running 1.8.4-msft-1). Checking with the release team what the status is. Sorry about that

**Comment by akshat172** [comment]
Hi, @ItalyPaleAle PLease let me know once it has been rolled out.
Do I need to make any changes to my CA environment or in my code when fix is released.

**Comment by ItalyPaleAle** [comment]
> Do I need to make any changes to my CA environment or in my code when fix is released.

No, it should “just work” once it’s been rolled out

**Comment by tjoudeh** [comment]
Hello @ItalyPaleAle Has this been rolled out now? Thank you.

**Comment by tjoudeh** [comment]
I tried it out right now on East US, and I can confirm that query API is working as expected on ACA with the latest dapr update. thanks @ItalyPaleAle & @torosent

**Comment by sergiibielskyi** [comment]
Hey, happy to hear that it should work. But after testing I see response 200 but without content in response. But if we are talking about executing the same piece of code locally, I do not see such a problem. What will be and how to trace that?  My example is following below,
CancellationTokenSource source = new CancellationTokenSource();
        CancellationToken cancellationToken = source.Token;
        
        var query = "{" +
                "\"filter\": {" +
                    "\"EQ\": { \"value.style\": \""+ style +"\" }" +
                "}" +
            "}";
        
        var queryResponse =  await daprClient.QueryStateAsync<ObjectModel>(storeName, query, cancellationToken: cancellationToken);

**Comment by mehmetaltuntas** [comment]
Hi, do we know this has been fixed entirely in all Azure regions? thanks
