### ISSUE TITLE
Error during deployment

### ISSUE THREAD

**Issue by ffrankozz** [microsoft/azure-container-apps#156]
While deploying   the app in the tutorial, the link and the name of which is given below, , I get an error which I think is coming from the following line:
value: listKeys(resourceId('Microsoft.Storage/storageAccounts/', storage_account_name), '2021-09-01').keys[0].value
The error content is:
'The template resource 'ffcontainerapps-env/statestore' at line '31' and column '5' is not valid: The resource identificator '/subscriptions//resourceGroups//providers/Microsoft.Storage/' is malformed.

[Tutorial: Deploy a Dapr application to Azure Container Apps with an ARM or Bicep template](https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr-azure-resource-manager?tabs=bash&pivots=container-apps-bicep)

**Comment by ffrankozz** [comment]
Could the double forward slashes after the subscriptions and resourceGroups  be causing  the error? I just noticed that in the error output  there exist  those double forward slashes.

**Comment by kendallroden** [comment]
this doc is updated
