### ISSUE TITLE
Documentation API not inline with implementation

### ISSUE THREAD

**Issue by vimorra** [microsoft/azure-container-apps#159]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
in the official doc https://docs.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?tabs=bicep#ingress is mentioned that resources can be:

![image](https://user-images.githubusercontent.com/48756634/161551387-ca9ccb6c-3f4d-474a-8271-4b98bdc3ef5a.png)

cpu: Required CPU in cores, e.g. 0.5, but the field is an int so is not possible to use decimal, I have received an error trying to deploy with 0.5
memory: Required memory, e.g. "250Mb", but I receive this error The 'memory' field for each container, if provided, must contain a decimal value to no more than 2 decimal places followed by 'Gi' to denote the unit (Gibibytes). Example: '1.25Gi' or '2Gi'."}]

### Steps to reproduct

**Expected behavior** [What you expected to happen.]
That the documentation is inline with the current implementation
**Actual behavior** [What actually happened.]
the implementation of the API provides error that are not documented and inline with the official documentation
**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by kendallroden** [comment]
https://github.com/microsoft/azure-container-apps/issues/135
