### ISSUE TITLE
CLI: Creating an app when login expired says it can't find the env

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#160]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
My az login token expired so when I tried to create a new app it failed, as expected. However, the error said that it couldn't find the "environment" instead of telling me that I needed to login. This could lead people down the wrong path while trying to debug it. Can we report the real issue?

### Steps to reproduct
1. create an env
2. wait for the az login token to expire
3. try to create an app

**Expected behavior** [What you expected to happen.]

Error message with a statement about needing to login again

**Actual behavior** [What actually happened.]

Complained about a missing env

**Comment by panchagnula** [comment]
@torosent can this be transferred as well please - will follow up with core-cli if this can be handled by them or if we need to add checks on our commands.

**Comment by simonjj** [comment]
Closing this, please reopen if you feel strongly.
