### ISSUE TITLE
CLI: Avoid use of separate args for options

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#161]
### This issue is a: (mark with an x)
- [x] bug report
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Not so much a bug but I do think it's an issue.... several options in ACA support space-separated args. For example, the help text for "app create" shows:
```
--env-vars GREETING="Hello, world" SECRETENV=secretref:anothersecret
```
This is kind of odd from a Linux CLI perspective. Normally spaces are only used to separate distinct args, not as a separator within one arg. So, normally the above would be written as:
```
--env-vars 'GREETING="Hello, world" SECRETENV=secretref:anothersecret'   # grouped into one arg
or
--env-vars GREETING="Hello, world" --env-var SECRETENV=secretref:anothersecret    # repeat the flag
```

As current done, it's ambiguous as to whether the SECRETENV arg is meant to be a positional arg for the entire CMD or whether it's a continuation of the previous arg. If we go with the "repeat the flag" option then we should rename the flag to "--env-var" (no 's'), or just "--env" (with an alias of `-e`) since that's what most CLIs use.

I would point out that while some Azure CLIs do this today, it's actually not recommended per the Azure CLI guidelines: https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#collection-management-with-actions

I think many Linux people will scratch their heads over this one, and consistency with the rest of Linux tooling is pretty important.

**Comment by panchagnula** [comment]
I believe this is the confusion from incorrect help examples. Will take a look, but space separated args is not recommended by azure-cli either. @torosent can this issue be transferred to CLI project as well for tracking purposes?

**Comment by anthonychu** [comment]
> I would point out that while some Azure CLIs do this today, it's actually not recommended per the Azure CLI guidelines: https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#collection-management-with-actions

Need to confirm with the az CLI folks but I don't believe they are referring to the same scenario.

Whether it's good practice or not, the CLI's convention is to use space-separated args and I don't think we should deviate from it: https://cs.github.com/Azure/azure-cli?q=%22space-separated%22+OR+%22space-delimited%22+OR+%22space+separated%22+OR+%22space+delimited%22

We could add a shorthand of `-e` and allow it to be repeated for each env var. This would be in addition to supporting space-separated though.

**Comment by magodo** [comment]
Under linux (bash), I'm not able to set moer than one `--args`:

```shell
💤  az containerapp update -n go-simple -g magodo-container-apps --args --name=foo --port=3000
unrecognized arguments: --port=3000

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
```
