### ISSUE TITLE
CLI: Some warnings are not warnings

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#162]
### This issue is a:
- [x] bug report 
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
While running the 'env create' command I see this:
```
$ az containerapp env create -n testenv -g default
WARNING: Command group 'containerapp' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: No Log Analytics workspace provided.
WARNING: Generating a Log Analytics workspace with name "workspace-defaultHUJd"
WARNING:  ..
Container Apps environment created. To deploy a container app, use: az containerapp create --help

{ ... }
```
These 2 lines:
```
WARNING: Generating a Log Analytics workspace with name "workspace-defaultHUJd"
WARNING:  ..
```
are not warnings. To me a WARNING is something that the user should probably look at and potentially fix. These are more like "informational" messages just telling the user what's going on. Can we drop the "WARNING:" prefix?
I also don't know what I'm supposed to do with the `..` line. That's an odd line to show - can we remove that?

I would also look at dropping:
```
WARNING: No Log Analytics workspace provided.
```
since 1) it's not a warning either, and 2) telling the user this info provides no value since they know they didn't specify it on the cmd. The next line "Generating a Log Analytics..." line should be sufficient for the user to know what's going on.

This might apply to other cmds too. I'll try to remember to add a comment here as I see more.

**Comment by panchagnula** [comment]
in CLI for display text to be displayed logger.warning needs to be used & this comes automatically for CLI. logger.info doesn't   get displayed until run with --debug flag. @calvinsID tagging you - just to make sure my response here is right & this is not some custom logger we are using. Thanks!

**Comment by duglin** [comment]
@panchagnula just wondering, being new to MSFT, who can I talk to about what's allowed (and not allowed) via the `az` CLI ? I've seen the guidelines https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md but those seem to be written for a CLI that is more like a "nicer curl" CLI. While I'm all for consistency, it needs to be done when it makes sense for the user. So, if an offering wanted to create a CLI that is more user-friendly than a "nicer curl" I'd like to understand how much freedom that offering has w.r.t. to CLI output. Any ideas on who might be a good person to talk to?

**Comment by calvinsID** [comment]
@panchagnula Correct that logger.info doesn't get displayed unless run with `--debug`. Alternatively can a print statement be used?

**Comment by panchagnula** [comment]
> @panchagnula Correct that logger.info doesn't get displayed unless run with `--debug`. Alternatively can a print statement be used?

Thanks. Makes me suspect that this is azure-cli's way of proposing "less is more" as well & recommending not to add log statements until & unless these are necessary, logger.warning were not prefixed with "warning" label earlier - this is a newer change. I am ok with removing some of these in the general create/ delete commands. However, for a command like up - we would need some logs displayed.

**Comment by anthonychu** [comment]
I can't repro the `WARNING: ` prefix in messages. @duglin is this something your shell is adding?

> Alternatively can a print statement be used?

My understanding is that _only_ the command's output can be written to stdout so that JSON, YAML, TSV can be piped to other commands without risk of corruption. This is why `print` is not allowed and `logger.info()` is suppressed by default.

**Comment by panchagnula** [comment]
> I can't repro the `WARNING: ` prefix in messages. @duglin is this something your shell is adding?
> 
> > Alternatively can a print statement be used?
> 
> My understanding is that _only_ the command's output can be written to stdout so that JSON, YAML, TSV can be piped to other commands without risk of corruption. This is why `print` is not allowed and `logger.info()` is suppressed by default.

@duglin please check if you the color config turned off locally which is adding the "Warning" label in your case

![image](https://user-images.githubusercontent.com/13839372/162052406-fc82cef9-893e-4d64-beb7-110ba479fc2f.png)

**Comment by duglin** [comment]
Correct, I have colors turned off. But even if we show people colors (which implies "warning") instead of the word "WARNING", it still feels a bit off.

Funny that they add words just because I turned off color. I never would have thought of changing the actual text strings just due to colors. I'd want to see the exact same text in both cases, just one more lively :-)

**Comment by panchagnula** [comment]
> Correct, I have colors turned off. But even if we show people colors (which implies "warning") instead of the word "WARNING", it still feels a bit off.
> 
> Funny that they add words just because I turned off color. I never would have thought of changing the actual text strings just due to colors. I'd want to see the exact same text in both cases, just one more lively :-)

Thank for the feedback. Its always interesting to see how folks, especially brand new to CLI use azcli. I passed it to the core-cli folks as well.

**Comment by simonjj** [comment]
Closing this, please reopen if you feel strongly.
