### ISSUE TITLE
Feature Request: Be a little less verbose in the happy path

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#164]
For some commands we're unnecessarily chatty. Usually Linux commands take a "no news is good news approach" and only show errors or warnings. No output means "I did what you asked". Therefore there's no reason to state the obvious. For example:
```
$ az containerapp env delete -n testenv -g default --yes
WARNING: Containerapp environment successfully deleted
```
The last line should be removed since it's unnecessary by the fact that there were no errors generated. Aside from not really aligning with normal Linux commands, the issue with being chatty is that it then forces people to "think" too much :-)  By that I mean they can't just quickly look to see if there's something to take of because something went wrong. With no output it's clear... nothing bad happened because there as no output. But, with chatty output the user now needs to read through all of the text to see if there's something do take care of - that's extra work. This is especially true if someone isn't advanced and doesn't have special shell prompt magic that shows when the exit code from the previous command wasn't zero.

Imagine this:
```
$ rm file
File 'file' was deleted
```
Would be annoying.

**Comment by panchagnula** [comment]
@duglin thanks for sharing - we have had mixed feedback in needing to be verbose vs don't assume no news is good news. Happy to consider this based on feedback or consensus on this.

**Comment by marcindulak** [comment]
I think configurable verbosity levels may help here, kubectl [does it](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging). When running cli commands as part of iac systems having verbose logs is useful to diagnose transient errors. Verbose flags are also available for some linux commands

```
touch 1 && rm -vf file
removed 'file'
```

**Comment by duglin** [comment]
Yup exactly. I'm more used to "quiet by default" (since that makes things easier to read and errors are very noticeable) but then use -v type of flags when people want chattiness.

**Comment by simonjj** [comment]
Closing this issue, please feel free to reopen if you feel strongly.
