### ISSUE TITLE
Apps are not scoped to environments

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#165]
### This issue is a: (mark with an x)
- [x] bug report
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I noticed that when I created an app I needed to specify both the "resource group" and the "environment". This seemed to make sense since I suspect I could have the same environment named in multiple resource groups.

However, when I then deleted the app I only needed to specify the resource group. The environment wasn't needed. I'm told that this is because both Apps and Environments are top-level resources in Azure. This seems really limiting because it means that I can't have the same App name in different Environments if they happen to be part of the same resource group. Seems like this will force an unnecessary explosion of resource groups just to avoid potential name collisions in the future.

Can we make it so that there's a clear hierarchy of:
```
resourceGroup -- (1:M) --> Environment -- (1:M) --> App
```
I think this is how most users would expect it to work.

**Comment by KarsonAlford** [comment]
Until yesterday we were using the direct hierarchy that duglin is advocating.  As part of the Microsoft.Web to Microsoft.App migration we are no longer able to create more than 2 environments per subscription.  We have begun switching to having Dev and QA environments in one subscription and a Prod environment in another subscription.

How should we think about a container app environment?  
Are they similar to Kubernetes namespaces or closer to Azure DevOps Pipeline environments?
What will be a likely limit for environments per subscription long term?

Note:
Previously we created all of the objects (environments and apps) in the same resource groups.  With the 2 environment limit we have now moved the environments to a separate resource group from the container apps.  For this to work we could no longer refer to the environment by its Name, when creating the container apps, we had to switch to using the environment Id.

You can get the Id:
`az containerapp env list`

If you use the environment name and the resource groups don't match you will get an error similar to:
`ERROR: The environment '/subscriptions/c488911...abf9d570a9/resourceGroups/helloworld-dev-resource-group-125/providers/Microsoft.App/managedEnvironments/Dev' does not exist. Specify a valid environment
`

**Comment by duglin** [comment]
From talking with Jeff Hollan last week I believe that an ACA environment is more akin to a K8s cluster, even though today it's a bit of a mixture of a K8s cluster and a K8s namespace. In a proposal we're working on I'm hoping we can nail this point down and then agree that we'll need another entity between the Env (cluster) and the App - something that equates to a K8s Namespace. I refer to it as a "workspace" for now. Even in a single-tenant env I think people will still want groupings of app to share the same cluster but be isolated from other groups.

**Comment by kendallroden** [comment]
@anthonychu @tomerrt check this out re: convo we had recently

**Comment by duglin** [comment]
Based on a chat with Jenny recently I was corrected and ACA envs are more like Kube namespaces.
I still think we need 3 layers though.... cluster, namespace and app. :-)

**Comment by kendallroden** [comment]
yes agree with Jenny on the namespace. Also resources in Azure that are of the same type and in the same RG have to be uniquely named due to the way the resource provider works.

**Comment by duglin** [comment]
Are we closing this because "that's just the way it works today" or because "that's the way it SHOULD work going forward" ? This means a user can not have a 'dev' and a 'prod' env in the same RG - that seems pretty limiting. I'd like to ask that we revisit/reopen this.
