### ISSUE TITLE
Feature Request: CLI: add an "app" sub-command/NOUN

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#166]
Today ACA has app management commands at the top-level - for example:
```
$ az containerapp create -n myapp --image nginx
```
instead of:
```
$ az containerapp app create -n myapp --image nginx
```
While there is some niceness to not having to specify the resource-type/NOUN, in the long run it's limiting because it means that if we ever have the need for an action/VERB that could apply to both the App and something global then we can't differentiate between the two. For example:
```
$ az containerapp init
```
if "init" made sense in both instances we'd be forced to choose a different VERB simply to avoid the ambiguity. But then of course, we may have ambiguity anyway because chances are the two VERBs would probably be synonyms.

There's also the advantage of being able to do:
```
$ az containerapp --help
```
add seeing the full list of resources/NOUN in one nice list w/o it also being co-located with VERBs for Apps. It's also more consistent this way to always have things in the form `az containerapp NOUN VERB`.

**Comment by simonjj** [comment]
Closing this issue, please feel free to reopen if you feel strongly.
