### ISSUE TITLE
Feature Request: Auto-save the user's scope (resource group and environment)

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#167]
Related to: https://github.com/microsoft/azure-container-apps/issues/165

When someone runs ACA commands they need to specify the associated resource group on each command, while there is a way to tell the `az` CLI to default to a certain resource group I find this kind of hard to remember (and use since the help text doesn't help someone set the resource group) and it's an extra step that should be unnecessary.  What if instead we allow for this:
```
$ az containerapp env create -n myenv -g myrg
$ az containerapp create -n myapp --image nginx
```

This means certain commands will save the current resource-group and environment (if we ever do #165) in an ACA config file so the user will not need to specify it on subsequent commands. 

Also, they may not want to set it for ALL az commands, this allows them to scope it just to ACA commands - not critical but nice.

We could then also add:
```
$ az containerapp env select -n myenv
$ az containerapp env select -n myenv2 -g rg2
```
to switch between environments and would save both the env and resource-group in an ACA config.

I have a feeling some folks may look at this as duplicating `az config`, and to some extent it is, however we're aiming for UX that's better than generic `az` and I don't think there's any guidelines that precludes us from doing something like this within the scope of ACA. All ACA commands need to be done within the scope of an env anyway (aside from env cmds).

**Comment by simonjj** [comment]
We're closing this issue, please reopen if you feel strongly.
