### ISSUE TITLE
Feature Request: show the scale of an app on "app show" and "app list" (~hide revisions)

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#168]
I consider "revisions" to be an advanced feature - which means I expect a large percentage of the time people will really only be using one revision at a time and user-defined traffic splitting will not be the most common flow beyond a short term upgrade process. As such, and even if traffic splitting is used, I think we should show some key bits of Revision data on the "app show" and "app list" metadata. In particular, today the number of instances (replica scale) is only shown on the revision. Which, to a user, is kind of odd since it appears that the traffic splitting percentages and scale ranges (min/max) are shown on the App metadata. 

In the end, I think we should treat Revisions as a very advanced feature and ideally a user should never need to access the Revision directly. All actions and metadata should be accessed via the App.

While the title of the issue say "hide revisions", if we can just make it so people never need to do any "az containerapp revision" commands then that's good enough for now. We can then later on (based on user feedback) decide if we want to deprecate it because no one really uses it. Or, in the spirit of "it's hard to take away stuff from the user"... hide it now from the CLI help text and only tell people about it if they ask. Then we can un-hide it based on user feedback.

**Comment by duglin** [comment]
Thinking more about this... this may be a backend issue since the REST API should probably show the info instead of the CLI doing multiple queries and merging data.

**Comment by simonjj** [comment]
Closing this issue, please feel free to reopen if you feel strongly.
