### ISSUE TITLE
Support for end-to-end encryption in transit

### ISSUE THREAD

**Issue by SatyKrish** [microsoft/azure-container-apps#17]
TLS is terminated on ingress, and  any communication from ingress controller to containerapp could be on plain HTTP. Is there a way to ensure end-to-end encryption in transit?

**Comment by denniszielke** [comment]
If the ingress would have a dapr sidecar this could be solved relatively easy.

**Comment by jeffhollan** [comment]
Potentially. @SatyKrish do you want to do HTTPS termination with your own code in the container and not have the ingress do HTTPS termination at all? In that case I expect that terminating and then creating a new request with encryption via Dapr sidecar may not work? But maybe either approach works

**Comment by SatyKrish** [comment]
> @SatyKrish do you want to do HTTPS termination with your own code in the container and not have the ingress do HTTPS termination at all?

No, I want Ingress controller to terminate inbound TLS. 

Currently I use open service mesh to ensure traffic is encrypted between ingress controller pod to backend pod. Here envoy takes care of mTLS for in-cluster pod communication. Similar implementation could be done by injecting DAPR sidecar to ingress controller, but haven’t tried.

**Comment by denniszielke** [comment]
Having a dapr sidecar in the ingress would be a great addition. Not only to get mTLS between ingress and containers but also do get tracing spans from the ingress path to the containers, use bearer token validation or define dapr access policies.

**Comment by SatyKrish** [comment]
Container Apps should include support for service mesh (like OSM) for securing traffic using mTLS. Make DAPR optional component, as not all apps may be using DAPR for service invocation.

[when-to-choose-using-dapr-a-service-mesh-or-both](https://docs.dapr.io/concepts/service-mesh/#when-to-choose-using-dapr-a-service-mesh-or-both)
`Typically you would use a service mesh with Dapr where there is a corporate policy that traffic on the network must be encrypted for all applications. For example, you may be using Dapr in only part of your application, and other services and processes that are not using Dapr in your application also need their traffic encrypted. In this scenario a service mesh is the better option, and most likely you should use mTLS and distributed tracing on the service mesh and disable this on Dapr.`

**Comment by marcovergari** [comment]
Any ETA on when this feature would be available?

**Comment by torosent** [comment]
Feature is available `az containerapp env update --enable-mtls`

**Comment by onionhammer** [comment]
@torosent can it be enabled with bicep?

**Comment by torosent** [comment]
docs will be published this week
```azurecli
az containerapp env update \
    --name <environment-name> \
    --resource-group <resource-group> \
    --enable-mtls
```

or 

```bicep
resource environment 'Microsoft.App/managedEnvironments@2023-04-01-preview' = {
  name: environmentName
  location: location
  properties: {
    peerAuthentication: {
      mtls: {
        enabled: true
      }
    }
}
}
```

**Comment by SatyKrish** [comment]
Thanks @torosent. Is this based on servicemesh or DAPR proxy bases implementation  or more like wiregaurd? How do we troubleshoot any connection issues?

**Comment by swh-cb** [comment]
@SatyKrish I asked the same question in discord #general channel and got the following answer from @torosent and @ahmelsayed:

ACA is using envoy as a base for the mTLS implementation. There is an envoy sidecar that handles mTLS in a way similar to other service meshes (e.g. OSM, istio). It's not as configurable or exposed as it's something that's completely managed by the ACA team.

TLS from client is negotiated/terminated on the edge proxy. The request needs to be decrypted to apply routing rules, update headers, etc. It's then re-encrypted before being sent to the sidecar envoy which decrypts it and passes it to the app.
