### ISSUE TITLE
Feature Request: when --target-port is specified, default to --ingress=external

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#170]
When the user specifies a `--target-port` they're clearly expecting to get traffic into their app so in cases where they don't also don't specify an `--ingress` value I'd like to suggest that we default it to `--ingress=external`.
This will give the best user-experience for new folks to the project since they would then not need to debug things to figure out why their app isn't getting traffic, or why they don't have an external URL associated with their app.

It means their app create command should be something as trivial as (if combined with #169):
```
$ az containerapp create -n myapp --image nginx --port 80
```
which is pretty nice and minimal for a 1st experience.

I didn't add the "CLI:" prefix to the issue because I think we should support this via the REST APIs too so it's more of a backend issue.

**Comment by curib** [comment]
Hi @duglin, we're going to close this issue. If you'd like us to reconsider the ask, please reopen!
