### ISSUE TITLE
Feature Request: CLI add a "-o url" flag for show cmd

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#171]
The URL of an app is probably one of (if not the most) important bit of metadata about an externally facing app, but in order for someone to get that info they need to either parse a table, yaml or json to extract it. While obviously that's possible, it's also more work than what should be needed. Some PaaS platforms allow for something like:
```
$ az containerapp show -n myapp -o url
```
and it'll show nothing but the URL of the app in the output (with https:// protocol). This makes it really easy when scripting stuff since no other tools are need (not even grep or sed), so someone can do stuff like:
```
curl $(az containerapp show -n myapp -o url)
```
It's really really handy.

In case it hasn't been noticed with all my issues today, I'm of the belief that "it's the little things that matter" and can really impact people's gut-reaction when using a product. Yes the big ticket features are most important but often it's those little annoyances that can eat away at people over time - or make other products look hard if they don't have niceties like this.

**Comment by anthonychu** [comment]
I think this is a request for the core CLI. They control the output formats. A command is only able to return the resource and it's up to the CLI to print it in the format requested.

**Comment by ThorstenHans** [comment]
I think the `show` command should remain consistent and work the same way as it does with all other Azure resources.

JMESPath and output formatting works everywhere 😬

**Comment by duglin** [comment]
Sure, but at some point it's not about whether someone can do something, it's about how hard we make it for them to do it.

Is an azure CLI allowed to extend the list of --output options?

**Comment by ThorstenHans** [comment]
IMO it’s not possible to create a custom output format looked into az extension development some weeks ago. Found nothing about that in the docs


https://thorsten-hans.com
________________________________

**Comment by simonjj** [comment]
when you create or up your container app with external ingress we now show the URL in clickable ready-to-use format. closing
