### ISSUE TITLE
Deployments are failing with InternalServerError

### ISSUE THREAD

**Issue by forki** [microsoft/azure-container-apps#175]
` {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InternalServerError","message":"{\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"Encountered internal server error. Diagnostic information: timestamp '20220408T084211Z', subscription id 'b0ffc8cb-91ff-4b78-924b-a4c0ad1f8004', tracking id '0ee705f5-bf46-493c-9cb3-1bf8961d9c85', request correlation id 'b874bb5f-4045-45f8-b2dd-53ef36b89957'.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InternalServerError\",\r\n    \"message\": \"There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: b874bb5f-4045-45f8-b2dd-53ef36b89957\"\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"code\": \"ContainerAppLockConflict\",\r\n  \"message\": \"Cannot modify container App 'parkinggates' because another modification is in progress. Please retry the operation.\"\r\n}"}]}}`

We're seeing things like this over and over again with azure-container-apps. The ARM deployment just fails because who knows what. The last deployment was yesterday. The error goes usally away after multiple retries, but it almost always fails with one container during the first try. Currently we have 9 containers in the ARM template.

**Comment by forki** [comment]
ok this time we're already at rerun 7 of the ARM deployment with the same ARM template. It's always complaining a different container. This is absolutely unusable at the moment. 

@anthonychu is there any known workaround?

**Comment by forki** [comment]
`{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"code\": \"ContainerAppLockConflict\",\r\n  \"message\": \"Cannot modify container App 'operatorlog' because another modification is in progress. Please retry the operation.\"\r\n}"},{"code":"Conflict","message":"{\r\n  \"code\": \"ContainerAppLockConflict\",\r\n  \"message\": \"Cannot modify container App 'chargingpointevents' because another modification is in progress. Please retry the operation.\"\r\n}"}]}}`

That's the other kind of error message that we see

**Comment by forki** [comment]
the only way to get the whole deployment through was to manually delete half of the container apps in the portal, so that ARM deployment can recreate them without running into this conflict. I don't hope I have to do this now multiple times a day.

**Comment by forki** [comment]
ok this is without doubt the worst CD workflow that I had in the last couple of years. It#s completely broken for me

**Comment by ruslany** [comment]
@forki - thanks for reporting this issue. We've identified what caused the conflict error and are working on a fix. The problem happens when several apps are created/updated on the same environment in parallel. Until the fix is deployed you can try to temporarily workaround the issue by using "dependsOn" in the ARM template to force ARM to create/update ARM in a sequence.

As for the InternalServerError  - this error happened in the Microsoft.Web namespace when updating a serverfarm. It looked like a transient issue. It should not happen if you retry.

**Comment by forki** [comment]
Thanks for investigating this. I'm looking forward for the fix.

Ruslan Yakushev ***@***.***> schrieb am Do., 14. Apr. 2022,
23:01:

**Comment by ruslany** [comment]
@forki - the fix for this bug has been deployed. Please let us know if you still encounter the problem.

**Comment by forki** [comment]
Looks like it's working. It's also much much faster than before. Good work! Thx
