### ISSUE TITLE
Traffic api split not setting the traffic

### ISSUE THREAD

**Issue by denniszielke** [microsoft/azure-container-apps#177]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
When I set the traffic split via the 'az containerapp ingress traffic set' cli command to --traffic-weight $OLD_BACKEND_RELEASE_NAME=0 latest=100 the traffic is not routed to any release anymore.

### Steps to reproduct
1. Deploy first app with multi revision mode
2. Deploy a new revision with traffic split (to prevent traffic from getting routed to the new revision
            traffic:
            - latestRevision: true
              weight: 0
            - revisionName: $OLD_BACKEND_RELEASE_NAME
              weight: 100
3. Set traffic split to --traffic-weight $OLD_BACKEND_RELEASE_NAME=0 latest=100 
4. The revision works fine and the portal shows that all traffic should be routed to a revision but the traffic from the top container app fqdn does not end up there and times out. 

**Expected behavior**
I would expect the traffic split api to work.

**Actual behavior** [What actually happened.]
The revision fqdn works fine but the container app fqdn not even though the traffic split should route 100 of traffic to that revision.

**Comment by zhenqxuMSFT** [comment]
@denniszielke I tried your steps but I cannot repro your issue in our prod. I also write an e2e test with the same step as yours, and it can pass too.

**Comment by kendallroden** [comment]
Can we get an update re: if this is working? @denniszielke

**Comment by denniszielke** [comment]
I rebuild the environment and retried the same process. I still get the same result. The revision url is working as expected while the fqdn of the container app is not responding. The traffic split claims that 100% of the traffic is routed to the latest revision.

**Comment by kendallroden** [comment]
Resolved offline
