### ISSUE TITLE
Using Azure Container Registry, when is latest version pushed to a new revision?

### ISSUE THREAD

**Issue by bppn** [microsoft/azure-container-apps#180]
When using Azure Container Registry to host the containers, when a new version is pushed (e.g. using :latest), is (and when) a new revision created in the azure container apps?

Or must this be done manually?

The container is running with a minimum of 1 replica.

**Comment by kendallroden** [comment]
You would to have an automated process for pushing the new image and then deploying it to azure container apps. It will not poll acr and create a new version.
