### ISSUE TITLE
Container logs

### ISSUE THREAD

**Issue by ekjuanrejon** [microsoft/azure-container-apps#185]
Container logs do not appear in Log Analytics

**Comment by BigMorty** [comment]
The stdout and stderr logs for each container in your container app should show in the 'ContainerAppConsoleLogs_CL' table. Here is a sample query to try (just replace 'foo' with your container app name.

ContainerAppConsoleLogs_CL 
| where ContainerAppName_s == 'foo'
| project Time=TimeGenerated, AppName=ContainerAppName_s, Container=ContainerName_s, Message=Message, LogLevel_s
| take 100

**Comment by kendallroden** [comment]
@ekjuanrejon please confirm if you got this working. Sometimes it takes 10 minutes for the table to load upon initial env creation

**Comment by ekjuanrejon** [comment]
Nope.. it did not work.

**Comment by BigMorty** [comment]
Can you share a PII-safe image of what was returned when running the query?

**Comment by kendallroden** [comment]
How did you get the key for log analytics? It may have a trailing space

**Comment by kendallroden** [comment]
Also do you have a table that was created and no data, or was the table not even present in the Log Analytics Workspace?

**Comment by ekjuanrejon** [comment]
Hi guys. I have deleted the container apps. I created the container app and environment via the azure portal and was using azure devops with bash to deploy the container apps

the only thing i can see in Log Analytics is the following:
ContainerAppConsoleLogs_CL

I will re-create the container some time later

**Comment by kendallroden** [comment]
Just let us know if you are able to repro or it it works for you!

**Comment by ekjuanrejon** [comment]
Right i just created a new app evnironment and is working. For the previous one it does not work. 
Doesn't matter i'm at liberty to recreate it

**Comment by BigMorty** [comment]
Great to hear, thanks for letting us know!
