### ISSUE TITLE
Unable to Enable Continuous Deployment via the Portal

### ISSUE THREAD

**Issue by davidtucker** [microsoft/azure-container-apps#187]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When attempting to add Continuous Deployment to an existing or new Container App, I get the following error:

```Failed to set up continuous deployment with error: The operation for sourcecontrol 'covid-api-2-AutoDeployTrigger-245f5aec-9dbc-4825-a36b-6119f8d76be4' failed. Error details: 'Reason: Unprocessable Entity. Body: System.Threading.Tasks.Task`1[System.String]'.```

I should note that in both cases (new and existing Container App) this leveraged a repository that had been used for a previous container app that had Continuous Deployment enabled.  The previous Continuous Deployment had been disconnected prior to this attempt to connect it again.

**Comment by xwang971** [comment]
@davidtucker This was due to some github secrets setting issue. The fix was deployed this morning. Could you please have a try now?

**Comment by davidtucker** [comment]
@xwang971 Verified that this is now fixed.
