### ISSUE TITLE
LogAnalyticsConfiguration.CustomerId is invalid.  CustomerId must be a GUID

### ISSUE THREAD

**Issue by miabot-11** [microsoft/azure-container-apps#188]
When attempting to create container app related resources via Pulumi (Workspace + Managed Environment), I get the following error:

`azure-native:app:ManagedEnvironment:
    error: Code="InvalidRequestParameterWithDetails" Message="LogAnalyticsConfiguration.CustomerId is invalid.  CustomerId must be a GUID"`

` error: Error: invocation of azure-native:operationalinsights:getSharedKeys returned an error: request failed /subscriptions/xxxxxxxxxxxxxx/resourcegroups/Calling%20%5BtoString%5D%20on%20an%20%5BOutput%3CT%3E%5D%20is%20not%20supported.%0A%0ATo%20get%20the%20value%20of%20an%20Output%3CT%3E%20as%20an%20Output%3Cstring%3E%20consider%20either%3A%0A1%3A%20o.apply%28v%20%3D%3E%20%60prefix%24%7Bv%7Dsuffix%60%29%0A2%3A%20pulumi.interpolate%20%60prefix%24%7Bv%7Dsuffix%60%0A%0ASee%20https%3A%2F%2Fpulumi.io%2Fhelp%2Foutputs%20for%20more%20details.%0AThis%20function%20may%20throw%20in%20a%20future%20version%20of%20%40pulumi%2Fpulumi./providers/Microsoft.OperationalInsights/workspaces/Calling%20%5BtoString%5D%20on%20an%20%5BOutput%3CT%3E%5D%20is%20not%20supported.%0A%0ATo%20get%20the%20value%20of%20an%20Output%3CT%3E%20as%20an%20Output%3Cstring%3E%20consider%20either%3A%0A1%3A%20o.apply%28v%20%3D%3E%20%60prefix%24%7Bv%7Dsuffix%60%29%0A2%3A%20pulumi.interpolate%20%60prefix%24%7Bv%7Dsuffix%60%0A%0ASee%20https%3A%2F%2Fpulumi.io%2Fhelp%2Foutputs%20for%20more%20details.%0AThis%20function%20may%20throw%20in%20a%20future%20version%20of%20%40pulumi%2Fpulumi./sharedKeys: autorest/azure: error response cannot be parsed: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Invalid URL</h2>\r\n<hr><p>HTTP Error 400. The request URL is invalid.</p>\r\n</BODY></HTML>\r\n" error: invalid character '<' looking for beginning of value`

I have created pulumi modules according to azure-native documentation, and I am using them in my stack like so:

`const workspace = new WorkspaceComponent({
    resourceGroupName: resourceGroup.resourceGroupName,
    workspaceName: config.require("workspaceName"),
    location: location,
    retentionInDays: 365,
    sku: {
        name: "Premium"
    },
    tags: tags
});

const workspaceSharedKeys = getSharedKeys({
    resourceGroupName: resourceGroup.resourceGroupName.toString(),
    workspaceName: workspace.workspaceName.toString(),
})

const managedEnvironment = new ManagedEnvironmentComponent({
    resourceGroupName: resourceGroup.resourceGroupName,
    location: location,
    name: config.require("managedEnvName"),
    appLogsConfiguration: {
        destination: "log-analytics",
        logAnalyticsConfiguration: {
            customerId: workspace.customerId.toString(),
            sharedKey: workspaceSharedKeys.then(r => r.primarySharedKey).toString(),
        }
    },
    tags: tags
}, { dependsOn: [resourceGroup, workspace] });`

**Comment by kendallroden** [comment]
Is there a repo for the Pulumi implementation that you can put this issue on? I am assuming the issue may be stemming from there, as this works in bicep and arm so it does not at least at first report appear to be an issue with container apps. 
@miabot-11
