### ISSUE TITLE
Dapr Service Invocation failed with 404 on Container Apps

### ISSUE THREAD

**Issue by yoshioterada** [microsoft/azure-container-apps#189]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)

### Issue description

The application was created as Java Quarkus Application and it run successfully on the local Dapr environment.
If I run it on the local, it returns the specific String as `Hello from local`.
However after I deployed the same application on the Container Apps, it failed with 404.

### Steps to reproduce

Following is my setup procedure.

```bash
## Environment Variable Settings

export RESOURCE_GROUP="joad-container-apps"
export LOCATION="eastus"
export LOG_ANALYTICS_WORKSPACE="joad-containerapps-logs"
export CONTAINERAPPS_ENVIRONMENT="joad-env"
export APPLICATION_NAME="quarkus-dapr-test"

## Create Docker Image and Push the Image
export VERSION_TAG_OF_IMAGE=1.0
docker build -f Dockerfile -t tyoshio2002/quarkus-dapr-test:$VERSION_TAG_OF_IMAGE .
docker tag tyoshio2002/quarkus-dapr-test:$VERSION_TAG_OF_IMAGE yoshio.azurecr.io/tyoshio2002/quarkus-dapr-test:$VERSION_TAG_OF_IMAGE
docker push yoshio.azurecr.io/tyoshio2002/quarkus-dapr-test:$VERSION_TAG_OF_IMAGE

## Create Azure Container Apps Env
az group create \
  --name $RESOURCE_GROUP \
  --location $LOCATION

az monitor log-analytics workspace create \
  --resource-group $RESOURCE_GROUP \
  --location $LOCATION  \
  --workspace-name $LOG_ANALYTICS_WORKSPACE

LOG_ANALYTICS_WORKSPACE_CLIENT_ID=`az monitor log-analytics workspace show --query customerId -g $RESOURCE_GROUP -n $LOG_ANALYTICS_WORKSPACE -o tsv | tr -d '[:space:]'`
LOG_ANALYTICS_WORKSPACE_CLIENT_SECRET=`az monitor log-analytics workspace get-shared-keys --query primarySharedKey -g $RESOURCE_GROUP -n $LOG_ANALYTICS_WORKSPACE -o tsv | tr -d '[:space:]'`

az extension add --name containerapp
az provider register --namespace Microsoft.App

az containerapp env create \
  --name $CONTAINERAPPS_ENVIRONMENT \
  --resource-group $RESOURCE_GROUP \
  --logs-workspace-id $LOG_ANALYTICS_WORKSPACE_CLIENT_ID \
  --logs-workspace-key $LOG_ANALYTICS_WORKSPACE_CLIENT_SECRET \
  --location $LOCATION

az containerapp create \
  --name $APPLICATION_NAME \
  --resource-group $RESOURCE_GROUP \
  --environment $CONTAINERAPPS_ENVIRONMENT \
  --image yoshio.azurecr.io/tyoshio2002/quarkus-dapr-test:$VERSION_TAG_OF_IMAGE \
  --target-port 8080 \
  --ingress 'external' \
  --query 'configuration.ingress.fqdn' \
  --cpu 1 --memory 2.0Gi \
  --min-replicas 1 --max-replicas 4 \
  --enable-dapr \
  --dapr-app-port 3500 \
  --dapr-app-id $APPLICATION_NAME 
```

I used the following Java Code.
[quarkus-dapr-test.zip](https://github.com/microsoft/azure-container-apps/files/8508130/quarkus-dapr-test.zip)
You can also confirm the Application behavior with [Swagger UI](https://quarkus-dapr-test.blacksea-5e5974d3.eastus.azurecontainerapps.io/q/swagger-ui/)

**Expected behavior** [What you expected to happen.]

If I run it on the local, it returns the specific String as `Hello from local` as follows.
And I expected the same result on the Azure Container Apps too.

```bash
> curl -v -X 'GET' \
  'http://localhost:8080/invoke/quarkus-micro-service-dapr' \
  -H 'accept: */*'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /invoke/quarkus-micro-service-dapr HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.79.1
> accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 16
< Server: fasthttp
< Date: Mon, 18 Apr 2022 19:26:08 GMT
< Traceparent: 00-b28142cfaf61bbbbe16921f19ac293e5-746a46b51e3300cf-01
< Content-Type: application/json
< 
* Connection #0 to host localhost left intact
Hello from local
```

**Actual behavior** [What actually happened.]

However after I deployed the same application on the Container Apps, it failed with 404.

```bash
curl -v -X 'GET' \
  'https://quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io/invoke/quarkus-micro-service-dapr' \
  -H 'accept: */*'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 20.121.87.165:443...
* Connected to quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io (20.121.87.165) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=blacksea-5e5974d3.eastus.azurecontainerapps.io
*  start date: Apr  3 02:55:07 2022 GMT
*  expire date: Mar 29 02:55:07 2023 GMT
*  subjectAltName: host "quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io" matched cert's "*.blacksea-5e5974d3.eastus.azurecontainerapps.io"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure TLS Issuing CA 06
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7feded80b600)
> GET /invoke/quarkus-micro-service-dapr HTTP/2
> Host: quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io
> user-agent: curl/7.79.1
> accept: */*
> 
< HTTP/2 404 
< allow: 
< content-type: application/json
< content-length: 0
< date: Mon, 18 Apr 2022 19:28:05 GMT
< 
* Connection #0 to host quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io left intact
```

### Additional context

In my sample application, I implemented a RESTful endpoint as `/invoke/{applicationID}`, which receive the Dapr Application ID in the Path Parameter.
In the above example, it invoked the `hello` method of `quarkus-micro-service-dapr` application.

And inside of the method, it will invoke the following.

`http://localhost:{DAPR_PORT}/v1.0/invoke/{applicationID}/method/hello`

When it failed, the following error was shown on the log.

```text
2022-04-18 19:11:00,676 ERROR [org.jbo.res.res.i18n] (executor-thread-0) RESTEASY002010: Failed to execute: org.jboss.resteasy.client.exception.ResteasyWebApplicationException: Unknown error, status code 404	
	at org.jboss.resteasy.client.exception.WebApplicationExceptionWrapper.wrap(WebApplicationExceptionWrapper.java:107)	
	at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:21)	
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)	
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:153)	
	at com.sun.proxy.$Proxy233.invokeService(Unknown Source)	
	at com.yoshio3.Main.invokeService(Main.java:69)	
	at java.lang.reflect.Method.invoke(Method.java:566)	
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)	
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)	
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)	
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)	
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)	
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)	
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)	
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)	
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)	
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)	
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)	
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)	
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)	
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)	
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)	
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)	
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)	
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)	
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)	
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)	
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)	
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)	
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)	
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)	
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)	
	at java.lang.Thread.run(Thread.java:829)	
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:600)	
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)	
```

If I invoke the following Health Check endpoint as `http://localhost:{DAPR_PORT}/v1.0/healthz`,
it return the 204. So it seems that the `http://localhost:{DAPR_PORT}` is running.

```bash
> curl -v -X 'GET' \
  'https://quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io/healthCheck' \            
  -H 'accept: */*'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 20.121.87.165:443...
* Connected to quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io (20.121.87.165) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=blacksea-5e5974d3.eastus.azurecontainerapps.io
*  start date: Apr  3 02:55:07 2022 GMT
*  expire date: Mar 29 02:55:07 2023 GMT
*  subjectAltName: host "quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io" matched cert's "*.blacksea-5e5974d3.eastus.azurecontainerapps.io"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure TLS Issuing CA 06
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb13080d400)
> GET /healthCheck HTTP/2
> Host: quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io
> user-agent: curl/7.79.1
> accept: */*
> 
< HTTP/2 204 
< server: fasthttp
< date: Mon, 18 Apr 2022 19:38:22 GMT
< content-type: application/octet-stream
< 
* Connection #0 to host quarkus-micro-service-dapr.blacksea-5e5974d3.eastus.azurecontainerapps.io left intact
```

During the startup time of the Application, the following log was shown on the console.
[log1.txt](https://github.com/microsoft/azure-container-apps/files/8508146/log1.txt)

**Comment by berndverst** [comment]
Aren't you missing the `v1.0` from the path?

`localhost:PORT/v1.0/invoke` similar when you make requests against container apps.

In your case it seems like the sidecar is never actually reached.

If service invocation isn't finding the target I would expect this:

```
{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: quarkus-micro-service-dapr, err: couldn't find service: tests"}%
```

I cannot see your code where you define `invokeService`, so it is unclear whether you are correctly making the request to the sidecar.

**Comment by yoshioterada** [comment]
Dear @berndverst san.

Thank you so much for your messages.
I specified the /v1.0/ in the RestClient Code.

In my code, I implemented both Rest Server code(Main.java) and Rest Client code(RestClientDebug.java).
From Main.java code it invokes the RestClientDebug.java code.
And I attach the source code, so please see it and if it is possible, could you try it, please?


More detail Explanation: 
(Based on the [USING THE REST CLIENT by Quarkus](https://quarkus.io/guides/rest-client), I implemented like following.

In the application.properties file, I defined the host URL to access.
```text
quarkus.rest-client."com.yoshio3.RestClientDebug".url=http://localhost:3500/
```

And actual URL path was strutted by @Path annotation in the RESTClientDebug.java code.

```text
@Path("/v1.0")
@Path("/invoke/{applicationID}/method/hello")
```

As a result, if the user access to the `http://HOST_NAME/invoke/{applicationID}` of Main.java(RESTful Server) code.
It will invoke the following URL.

`http://localhost:3500/v1.0/invoke/{applicationID}/method/hello`

```java
public class Main {
    @GET
    @Path("/invoke/{applicationID}")
    @Produces(MediaType.APPLICATION_JSON)
    public Response  invokeService(@PathParam("applicationID") String appID) {
        return debug.invokeService(appID);
    }
```

```text
├── Dockerfile
├── README.md
├── mvnw
├── mvnw.cmd
├── pom.xml
├── src
│   ├── main
│   │   ├── docker
│   │   │   ├── Dockerfile.jvm
│   │   │   ├── Dockerfile.legacy-jar
│   │   │   ├── Dockerfile.native
│   │   │   └── Dockerfile.native-micro
│   │   ├── java
│   │   │   └── com
│   │   │       └── yoshio3
│   │   │           ├── Main.java
│   │   │           └── RestClientDebug.java
│   │   └── resources
│   │       ├── META-INF
│   │       │   └── resources
│   │       │       └── index.html
│   │       └── application.properties
```

**Comment by berndverst** [comment]
Thanks for explaining @yoshioterada-san. I'm not too familiar with Java and this particular framework :)

Still, it is interesting you are getting a 404 response.

If this were a problem where the sidecar simply cannot find the app to invoke the error would be different.

```bash
curl --verbose localhost:4444/v1.0/invoke/doesnotexist/method/hello
*   Trying 127.0.0.1:4444...
* Connected to localhost (127.0.0.1) port 4444 (#0)
> GET /v1.0/invoke/doesnotexist/method/hello HTTP/1.1
> Host: localhost:4444
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Server: fasthttp
< Date: Mon, 18 Apr 2022 23:37:58 GMT
< Content-Type: application/json
< Content-Length: 120
< Traceparent: 00-5a6f98c4ddf7779d11658905a2fc4da3-248105b1a95d0fab-01
<
* Connection #0 to host localhost left intact
{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: doesnotexist, err: couldn't find service: doesnotexist"}%
```

Note the error message and 500 status code.

So in your case it is almost as if container apps does not actually have any route for `/v1.0/invoke` registered and that is why you are seeing a 404.

Are you sure the sidecar is running? Do any other Dapr APIs work?

**Comment by yoshioterada** [comment]
I noticed that the following `Shutting down` message was shown on the log.

```text
time="2022-04-19T00:56:35.853241572Z" level=info msg=**"Shutting down actor"** app_id=quarkus-dapr-test instance=quarkus-dapr-test--6w6xmee-6c8f4bdb67-gh2rn scope=dapr.runtime type=log ver=edge       
time="2022-04-19T00:56:36.270125376Z" level=info msg=**"dapr shutting down. Waiting 5s to finish outstanding operations"** app_id=quarkus-dapr-test instance=quarkus-dapr-test--6w6xmee-6c8f4bdb67-gh2rn scope=dapr.runtime type=log ver=edge PrimaryResult
time="2022-04-19T00:56:41.271106186Z" level=info msg="Shutting down all components" app_id=quarkus-dapr-test instance=quarkus-dapr-test--6w6xmee-6c8f4bdb67-gh2rn scope=dapr.runtime type=log ver=edge      
```
Could you let me know what kind of situation, does the `Waiting 5s to finish outstanding operations` message showed?

**Comment by yoshioterada** [comment]
> Are you sure the sidecar is running? Do any other Dapr APIs work?

In the local environment, I can confirm with `docker ps` command.

```bash
$ docker ps
CONTAINER ID   IMAGE               COMMAND                  CREATED        STATUS                  PORTS                              NAMES
f0b94aa1b49d   openzipkin/zipkin   "start-zipkin"           18 hours ago   Up 18 hours (healthy)   9410/tcp, 0.0.0.0:9411->9411/tcp   dapr_zipkin
c3016507eae2   daprio/dapr:1.7.0   "./placement"            18 hours ago   Up 18 hours             0.0.0.0:50005->50005/tcp           dapr_placement
f64b7c1adc93   redis               "docker-entrypoint.s…"   18 hours ago   Up 18 hours             0.0.0.0:6379->6379/tcp             dapr_redis
```

And it seems that the `http://localhost:3500/v1.0/healthz` returns the status code 204.

In the `Azure Container Apps` environment, could you let me know how to check the required service is running?

**Comment by yoshioterada** [comment]
Now I may be able to solve the issue by myself. However, I don’t know the reason why this worked.

When the problem occurs, I specified the following parameter for creating the instance.
At that time, 404 was shown.

(`--target-port`  and `--dapr-app-port` number is difference)
```bash
az containerapp create \
  --name $APPLICATION_NAME \
  --resource-group $RESOURCE_GROUP \
  --environment $CONTAINERAPPS_ENVIRONMENT \
  --image yoshio.azurecr.io/tyoshio2002/quarkus-sample:$VERSION_TAG_OF_IMAGE \
  --target-port 8080 \
  --ingress 'external' \
  --query 'configuration.ingress.fqdn' \
  --cpu 1 --memory 2.0Gi \
  --min-replicas 1 --max-replicas 4 \
  --enable-dapr \
  --dapr-app-port 3500 \
  --dapr-app-id $APPLICATION_NAME 
```

And now I tried to create it with the following parameter, then it seems that it worked fine.

```bash
az containerapp create \
--name $APPLICATION_NAME \
--resource-group $RESOURCE_GROUP \
--environment $CONTAINERAPPS_ENVIRONMENT \
--image yoshio.azurecr.io/tyoshio2002/quarkus-dapr-test:$COUNTER \
--target-port 8080 \
--ingress 'external' \
--query 'configuration.ingress.fqdn' \
--cpu 1 --memory 2.0Gi \
--min-replicas 1 --max-replicas 4 \
--enable-dapr \
--dapr-app-port 8080 \
--dapr-app-id $APPLICATION_NAME
```
(`--target-port`  and `--dapr-app-port` number is same)


After deploying it, I tried to execute like follows. And I confirmed it worked fine.

```bash
> curl https://dapr-sample10.blacksea-5e5974d3.eastus.azurecontainerapps.io/invoke/dapr-sample2
Hello from local
> curl https://dapr-sample10.blacksea-5e5974d3.eastus.azurecontainerapps.io/invoke/dapr-sample10
Hello from local 5     <---------------- Difference result returned(it was expectation behavior)
> 
```

From the specification point of view,  is it the expected behavior?

[Tutorial: Deploy a Dapr application to Azure Container Apps using the Azure CLI](https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash)
```text
the service (Node) app server on (the app port)--target-port 3000
its accompanying Dapr sidecar configured with and for service discovery and invocation--dapr-app-id nodeapp--dapr-app-port 3000
```

The above explanation was written. However, it didn’t write that the user need to specify the same port number.
If the user needs to specify the same port number, please explain in more detail, or please remove the parameter?

**Comment by yoshioterada** [comment]
And I have one more question.

```bash
az containerapp create \
--name $APPLICATION_NAME \
--resource-group $RESOURCE_GROUP \
--environment $CONTAINERAPPS_ENVIRONMENT \
--image yoshio.azurecr.io/tyoshio2002/quarkus-dapr-test:$COUNTER \
--target-port 8080 \
--ingress 'external' \
--query 'configuration.ingress.fqdn' \
--cpu 1 --memory 2.0Gi \
--min-replicas 1 --max-replicas 4 \
--enable-dapr \
--dapr-app-port 8080 \
--dapr-app-id $APPLICATION_NAME
```

Even though, after I specified the `--dapr-app-port 8080`, the Environment Variable in the container
had the following value.

```text
DAPR_HTTP_PORT=3500
```

As a result, in order to invoke another service, I need to invoke the following port number instead of the 8080(`--dapr-app-port`)

`http://localhost:3500/v1.0/invoke/{applicationID}/method/hello`

Exactly, could you let me know what is the purpose of the `--dapr-app-port 8080`?

**Comment by kendallroden** [comment]
dapr app port is the port that your application is running on i.e. if your dapr app port is 8080, your exposed container port should also be 8080. The Dapr sidecar runs on 3500 by default. Dapr HTTP port is the port Dapr is running on.

**Comment by berndverst** [comment]
`DAPR_HTTP_PORT` is where your sidecar is listening for requests. Similarly we have `DAPR_GRPC_PORT` in standalone Dapr.

`DAPR_APP_PORT` is the web server port that the Dapr sidecar is calling for service invocation, PubSub etc

So one of these is for requests to the sidecar and one of them is for requests from the sidecar to your app!

It makes sense that Dapr App Port needs to be the same port as your app that is exposing the HTTP server with the "/hello" method. Of course you don't necessarily need to expose that publicly via the target port - but in most cases that's probably what you want to do.

If you were to specify a Dapr App Port that isn't responding to HTTP requests your service invocation attempts would return:
`{"errorCode":"ERR_DIRECT_INVOKE","message":"invoke API is not ready"}`

However in this case the Dapr App Port *IS* responding to HTTP requests -- this happens to be the Dapr Sidecar API running on the Dapr HTTP port.

Apparently that configuration causes the confusing error message:
`{"errorCode":"ERR_DIRECT_INVOKE","message":"failed getting app id either from the URL path or the header dapr-app-id"}` 

There are two things we will do to make this less confusing in the future:

On the Container Apps side:
- When dapr-app-port isn't specified, automatically use the target-port value

On Dapr itself:
- Introduce a new error message when dapr-app-port is set to the same value as the dapr-http-port.

**Comment by guidoffm** [comment]
I have a similar issue. 
What I get in the logs is:

Error: {"errorCode":"ERR_DIRECT_INVOKE","message":"failed getting app id either from the URL path or the header dapr-app-id"}

**Comment by berndverst** [comment]
https://github.com/dapr/dapr/issues/4531

**Comment by guidoffm** [comment]
> `DAPR_HTTP_PORT` is where your sidecar is listening for requests. Similarly we have `DAPR_GRPC_PORT` in standalone Dapr.
> 
> `DAPR_APP_PORT` is the web server port that the Dapr sidecar is calling for service invocation, PubSub etc
> 
> So one of these is for requests to the sidecar and one of them is for requests from the sidecar to your app!
> 
> It makes sense that Dapr App Port needs to be the same port as your app that is exposing the HTTP server with the "/hello" method. Of course you don't necessarily need to expose that publicly via the target port - but in most cases that's probably what you want to do.
> 
> If you were to specify a Dapr App Port that isn't responding to HTTP requests your service invocation attempts would return: `{"errorCode":"ERR_DIRECT_INVOKE","message":"invoke API is not ready"}`
> 
> However in this case the Dapr App Port _IS_ responding to HTTP requests -- this happens to be the Dapr Sidecar API running on the Dapr HTTP port.
> 
> Apparently that configuration causes the confusing error message: `{"errorCode":"ERR_DIRECT_INVOKE","message":"failed getting app id either from the URL path or the header dapr-app-id"}`
> 
> There are two things we will do to make this less confusing in the future:
> 
> On the Container Apps side:
> 
> * When dapr-app-port isn't specified, automatically use the target-port value
> 
> On Dapr itself:
> 
> * Introduce a new error message when dapr-app-port is set to the same value as the dapr-http-port.

@berndverst Thank you for your explanation.

What I still do not understand:

Which options do I have to provide to allow the call of the Dapr sidecar? I do not need my code to be invoked by Dapr.

How can I prevent this error?

**Comment by berndverst** [comment]
> > `DAPR_HTTP_PORT` is where your sidecar is listening for requests. Similarly we have `DAPR_GRPC_PORT` in standalone Dapr.
> > `DAPR_APP_PORT` is the web server port that the Dapr sidecar is calling for service invocation, PubSub etc
> > So one of these is for requests to the sidecar and one of them is for requests from the sidecar to your app!
> > It makes sense that Dapr App Port needs to be the same port as your app that is exposing the HTTP server with the "/hello" method. Of course you don't necessarily need to expose that publicly via the target port - but in most cases that's probably what you want to do.
> > If you were to specify a Dapr App Port that isn't responding to HTTP requests your service invocation attempts would return: `{"errorCode":"ERR_DIRECT_INVOKE","message":"invoke API is not ready"}`
> > However in this case the Dapr App Port _IS_ responding to HTTP requests -- this happens to be the Dapr Sidecar API running on the Dapr HTTP port.
> > Apparently that configuration causes the confusing error message: `{"errorCode":"ERR_DIRECT_INVOKE","message":"failed getting app id either from the URL path or the header dapr-app-id"}`
> > There are two things we will do to make this less confusing in the future:
> > On the Container Apps side:
> > 
> > * When dapr-app-port isn't specified, automatically use the target-port value
> > 
> > On Dapr itself:
> > 
> > * Introduce a new error message when dapr-app-port is set to the same value as the dapr-http-port.
> 
> @berndverst Thank you for your explanation.
> 
> What I still do not understand:
> 
> Which options do I have to provide to allow the call of the Dapr sidecar? I do not need my code to be invoked by Dapr.
> 
> How can I prevent this error?

You are experiencing a different issue - but the error is the same. Can you open a new issue? Happy to help.

For your case - either set the Dapr HTTP Port or use the default 3500.
From your app with Dapr enabled, make sure you have a state store configure (e.g. with name `<storename>`) you can then use the SDK or make a HTTP call

`POST http://localhost:<daprPort>/v1.0/state/<storename>`

https://docs.dapr.io/reference/api/state_api/#http-request

Using a Dapr component uses a different API on the sidecar compared to invoking other Dapr apps.

If you still have problems after reviewing this, please do open a new issue as I mentioned because it's not related to this issue here! Thanks!

**Comment by guidoffm** [comment]
https://github.com/microsoft/azure-container-apps/issues/191

**Comment by kendallroden** [comment]
@guidoffm was using the Dapr Secret Store API which is not implemented in container apps today, you would instead use the Azure Container Apps secrets. Visit this example for clarity: https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr 

@yoshioterada did acknowledged there was confusion around how the dapr sidecar and ports map. I believe that is resolved. 

I think this issue can be closed. Let me know if not!

**Comment by guidoffm** [comment]
As far as I understand Azure container app secrets gives us the opportunity to provide environment variables to the containers. This is what I already use.
So I think I have to use the environment variables directly and not through Dapr.

Interesting that container apps needs a special implementation of Dapr.

B.T.W. At the moment I cannot set an environment variable using a reference in the Azure console. The dropdown box is disabled.

**Comment by yoshioterada** [comment]
Dear @kendallroden san and @berndverst  san
Thank you so much !!

Yes, I could understand this.
And please close the issue.

Thank you so much & Best Regards.
Yoshio
