### ISSUE TITLE
Bug in the default github actions created when CD is enabled

### ISSUE THREAD

**Issue by vimorra** [microsoft/azure-container-apps#19]
Issue Description:
```
The default github workflow include these lines:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        **with:
          path: main**
```

the lines to point to the "main" path generate an error when to build and push the docker images is required to use the context, anyway is not clear why there is this configuration at checkout time. Moreover I assume that this is related to this config:

![image](https://user-images.githubusercontent.com/48756634/140964809-4a3ea24b-0faf-4097-99c5-e7c947d6b0f2.png)
in which the branch should be used to configure the trigger and which branch to point during the deployment time.

Desired Behavihour:
The out of the box github workflow should avoid to point to the path.

**Comment by xwang971** [comment]
@vimorra hi Vincenzo, thanks for reporting this. We do need point to the certain branch when do the deployment since there will be chance that mulitple branchs exist in the same repo and only one is a product version and others are for dev and test purpose. Could you please paste the exact error you saw here so we can take a look?

**Comment by vimorra** [comment]
This is the issue that I receive if I use the default action 
![image](https://user-images.githubusercontent.com/48756634/141207089-b72852f3-65fb-4b26-b3b7-eefd2a2311d0.png)

I'm using the sample 
![image](https://user-images.githubusercontent.com/48756634/141207128-319b08c9-ca66-429c-9553-033e981101d8.png)

I think that the issue is that this default configuration is not correct:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        **with:
          path: main**

Based on the documentation of the github action the proper way to checkout a branch is 
![image](https://user-images.githubusercontent.com/48756634/141207324-eb091c7c-4a32-45d1-8ee9-17332f17af6f.png)

Indeed this should be the proper configuration of the default workflow that is defined by the Container Apps

**Comment by xwang971** [comment]
Hi, can you please check if the workflow file is in the same branch as the file you missed?
Why we need branch info is we need to figure out which branch has the file we need and then we push the yml file to that branch and declare the work_space in "path". So this checkout github action line is not used to switch a branch, instead it points the current repo as the one we will work on.

**Comment by vimorra** [comment]
yes the workflow files and application files are in the same branch, I have only one branch that is master. I'm a bit confusing about the "branch" field in the azure portal, it is to point to a folder or is a git branch?

**Comment by xwang971** [comment]
Hi, Vincenzo, that points to a branch. We will push the yml file to that branch and claim that branch as our work space so that it has access to all file under that branch. If all your files are under master, could you try link the repo using branch "master"?

**Comment by vimorra** [comment]
sorry for the question but wat do you mean for "try link the repo using branch "master" "?

**Comment by johnkors** [comment]
I find that the portal or the cli _pushing_ a commit with a GitHub action yaml into our git repos is very odd. Couldn't you just provide a sample in the docs (explaining the secrets needed, and how to generate them) how to use `az containterapp update` instead?

**Comment by xwang971** [comment]
@vimorra Hi, Vincenzo. Sorry for the delay. I mean disconnect the repo from portal and then connect it again and this time choose branch "master".

**Comment by xwang971** [comment]
Hi, @johnkors Sorry for the inconvenience. Yes we definitely can use cli command to update the containerapp. We will add that in the doc

**Comment by johnkors** [comment]
Sorry, I was not clear in my communication. I'll try to rephrase:

Connecting a container app (either via the portal or via `az containerapp github-action add`) causes a commit to be pushed to the repo. The added GitHub action immediately runs on Github causing a deploy. I find this behaviour very odd and side-effecty.

What I would prefer instead:
- Nice samples and docs explaining how to setup a yaml, what secrets are necessary, and how to setup authentication (service principal).
- Let `az containerapp github-action create` create a yaml LOCALLY, and then the developer can add this to GitHub when/how they want in their own pace.

**Comment by xwang971** [comment]
Hi, @johnkors, thatnks for the suggestion. We would provide options for customer to push it to workflow directory or somewhere else in the repo. Does that sound good?
And yes sure we will update the docs to provide more details for the parameters we need.

**Comment by johnkors** [comment]
>We would provide options for customer to push it to workflow directory or somewhere else in the repo. Does that sound good?

The hole point I was making was that a git push is intrusive. You are talking about adding additional parameters and keeping a git push to a repo? Then no, I still won't use it.

I guess as long as the hole github action setup is _optional_ and one can always set up continous delivery by just manually writing a yml, then ok.

Could you confirm that everything is doable by writing the yml manually? i.e. I can setup continous delivery without doing either:
1) az containerapp github-action create
2) using the portal and connecting github

**Comment by xwang971** [comment]
Hi, @johnkors. I think the answer is yes. You can use this file and set up all required parameters and push it to your repo when you feel it's a proper time. [https://github.com/xwang971/sampleYml/blob/main/AutoDeployTrigger.yml](url) 
Also you may need to set the secrets "REGISTRY_USERNAME", "REGISTRY_PASSWORD" and "AZURE_CREDENTIALS" in github secrets. 
We will definitely update the docs to include such file and how to set parameters for more flexibility.

**Comment by SophCarp** [comment]
Hi! I think this issue has been resolved. Our docs have been updated in these two places:

We have documentation on Github actions: https://learn.microsoft.com/en-us/azure/container-apps/authentication-github
And we have docs about enabling authentication and authorization here: https://github.com/MicrosoftDocs/azure-docs/blob/788e763ab8615ade88663b82b7ca0f037ea59022/articles/container-apps/github-actions-cli.md

I'm doing a spring cleaning, so if I haven't fully addressed this issue, feel free to reopen it!
