### ISSUE TITLE
 Error "The environment network configuration is invalid" when executing `az containerapp env create` command

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#190]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When run `az containerapp env create` command as follows, I get an error **"The environment network configuration is invalid: Must specify AppSubnetResourceId when providing ControlPlaneSubnetResourceId"** and cannot create it :

```
az containerapp env create \
  --name $CONTAINER_APPS_ENV_NAME \
  --resource-group $RG_NAME \
  --location $LOCATION \
  --internal-only false \
  --infrastructure-subnet-resource-id $CONTROL_PLANE_SUBNET_RESOURCE_ID \
  --docker-bridge-cidr '10.2.0.1/16' \
  --platform-reserved-cidr '10.1.0.0/16' \
  --platform-reserved-dns-ip '10.1.0.2' \
  --logs-workspace-id $LOG_ANALYTICS_WORKSPACE_RESOURCE_ID \
  --logs-workspace-key $LOG_ANALYTICS_WORKSPACE_KEY
```
Also, if you run it with `--app-subnet-resource-id` option, you will get an error **"unrecognized arguments: --app-subnet-resource-id"**.

### Steps to reproduct
1. Run `az containerapp env create` command with `--infrastructure-subnet-resource-id` option

**Expected behavior** [What you expected to happen.]
A container app environment with a custom VNet should be created.

**Actual behavior** [What actually happened.]
An error has occurred and it cannot be created.

### Additional context
Azure CLI version

```
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "containerapp": "0.3.0",
    "ssh": "1.1.0"
  }
}
```

**Comment by kendallroden** [comment]
thanks investigating

**Comment by ebencarek** [comment]
@YuKogasaka we are in the process of removing the requirement for the second subnet resource ID, the CLI got a little ahead of things and removed the argument before the change was made in the backend. We are working to update the backend, and in the meantime, you should be able to use the Azure Portal to deploy your environment.

**Comment by MarkNickeson** [comment]
Is there an ETA on when the CLI and service backend will be back in sync on this?

**Comment by MarkNickeson** [comment]
FWIW, the recently released containerapp extension version 0.3.2 still fails with the error "The environment network configuration is invalid: Must specify RuntimeSubnetId when providing InfrastructureSubnetId"

**Comment by ebencarek** [comment]
Deployment of the backend change to fix this has just begun, it will take approximately 5 to 7 days before the change reaches all regions.

**Comment by ebencarek** [comment]
@YuKogasaka @MarkNickeson I forgot to update when the deployment finished, but the change is deployed everywhere now and the CLI should be in sync with the backend. Can you confirm if this is working for you?

**Comment by YuKogasaka** [comment]
@ebencarek,
In containerapp extension v0.3.4, I have confirmed that the az containerapp env create command works normally and can be deployed using the --infrastructure-subnet-resource-id option.
