### ISSUE TITLE
Cannot call service from Dapr sidecar - Misleading error message

### ISSUE THREAD

**Issue by guidoffm** [microsoft/azure-container-apps#191]
### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have created a simple test case for this:

https://github.com/guidoffm/dapr-test

You can use the pre-compiled images from Docker Hub.

It uses the Dapr SDK for Javascript: https://github.com/dapr/js-sdk

### Steps to reproduce

1. Create a file `configstore.yml` with this content:
  ```yaml
  componentType: secretstores.local.env
  version: v1
  ```

2. Deploy a Dapr secretstore component 
```bash
    az containerapp env dapr-component set \
    -g $RESOURCE_GROUP --name $CONTAINERAPPS_ENVIRONMENT \
    --dapr-component-name configstore \
    --yaml configstore.yml
```

3. Create an Azure Container App:

```bash
    az containerapp create \
    --name daprtest \
    --resource-group $RESOURCE_GROUP \
    --environment $CONTAINERAPPS_ENVIRONMENT \
    --image guidoffm/dapr-test:main \
    --target-port 3000 \
    --ingress 'external' \
    --min-replicas 1 \
    --max-replicas 1 \
    --dapr-app-id daprtest \
    --enable-dapr true \
    --cpu 0.25 \
    --memory 0.5
````
4. Wait for the app to come up. Call its URL in the browser and you see an error message:
```text
Error: {"errorCode":"ERR_DIRECT_INVOKE","message":"failed getting app id either from the URL path or the header dapr-app-id"}
    at HTTPClient.<anonymous> (/home/node/node_modules/dapr-client/implementation/Client/HTTPClient/HTTPClient.js:116:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/node/node_modules/dapr-client/implementation/Client/HTTPClient/HTTPClient.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by kendallroden** [comment]
Dapr secret stores are not implemented in Azure Container Apps and are on the roadmap. We are updating documentation for clarity already @guidoffm

**Comment by guidoffm** [comment]
So there are still two issues here:
1st: Azure CLI. You should not be allowed to configure a secret resource. The command should say this is not supported (at the moment).

2nd: Dapr API. The next problem is the missleading error message when I try to accee the secret resource with Dapr. 
The message should be that secrets are not supported.

**Comment by kendallroden** [comment]
There is likely another problem you are facing in your api call, because you will get a not implemented exception when you try to access the secret store via dapr in container apps
