### ISSUE TITLE
Cannot create or update `Microsoft.App` provider resource tag

### ISSUE THREAD

**Issue by shibayan** [microsoft/azure-container-apps#195]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Attempting to tag each resource in Container Apps results in a provider error and the tag cannot be properly saved.

### Steps to reproduct
1. Create Container App
2. Add Tags from Azure Portal.
3. Can’t save tags with error

**Expected behavior** [What you expected to happen.]
Resource tags saved correctly.

**Actual behavior** [What actually happened.]
Raise Provider response error (Microsoft.App provider)

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
This issue occur in Portal and REST API

**Comment by ruslany** [comment]
@shibayan - thanks for reporting this. We got a repro too and are investigating.

**Comment by kendallroden** [comment]
@ruslany  please provide an update when possible

**Comment by ruslany** [comment]
@shibayan @kendallroden - there are two bugs. 

1. Unable to update tags for containerapps
2. Unable to update tags for environments.

The fix for #1 is in the release pipeline and should be in prod in all regions by middle of next week. We are still working on the fix for #2.

**Comment by ruslany** [comment]
The fix for updating tags on containerapps has been deployed to all regions. The fix for updating tags for environments has been coded but not deployed yet.

**Comment by ruslany** [comment]
The fix for managed environment tags has been deployed to all regions
