### ISSUE TITLE
Ability to see KEDA and Dapr logs in Log Analytics

### ISSUE THREAD

**Issue by BigMorty** [microsoft/azure-container-apps#196]
Ability to see KEDA and Dapr logs in Log Analytics. And streaming logs for my Dapr sidecar.

This ask came from https://github.com/microsoft/azure-container-apps/issues/27 by @guythetechie

**Comment by BigMorty** [comment]
Dapr logs are in the consolelogs table in Log Analytics. Sidecars containers should show in Streaming Logs also. We are working to get KEDA events into our systemlogs table. These events will also be visible in the Streaming Logs UX.

**Comment by taehokangithub** [comment]
This issue is closed - does it mean I can see KEDA event in system logs?

**Comment by tomkerkhove** [comment]
Yes, you should be able to see those AFAIK.

**Comment by BigMorty** [comment]
@tomkerkhove beat me to it. Yes the KEDA scale up/down events are in the SystemLogs table.

**Comment by yansyunchen** [comment]
Hi, @BigMorty and @tomkerkhove,
May I know is that possible to see "which metric" to trigger scaling event on the ContainerAppSystemLogs_CL?
From my personal lab, I rule below
<img width="1675" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/15064864/bdae272b-0db7-4184-a7f5-137f6fb1dfe1">

But it seems I cannot see any related scaling event detail in the ContainerAppSystemLogs_CL. (E.g. Scaling up cuz of cpu>1)
ContainerAppSystemLogs_CL
//| where EventSource_s == "KEDA"
| where RevisionName_s == "container-app-power--0cuzw05"
| take 100
| project TimeGenerated, Type_s, Log_s, RevisionName_s, ContainerAppName_s, EventSource_s, Reason_s
[query_data.csv](https://github.com/microsoft/azure-container-apps/files/12888711/query_data.csv)

Thank you
