### ISSUE TITLE
Azure devops batch script environment variable

### ISSUE THREAD

**Issue by ekjuanrejon** [microsoft/azure-container-apps#197]
1) Create the following bash script
2) Use Azure Devops Run a bash script
3) Set EnvironmentVariables to container sql connection string

return the following error
ERROR: Environment variables must be in the format "<key>=<value> <key>=secretref:<value> ...".

It only works if the environment variable is a very simple one like
ConnectionStrings__SQLCommandTimeout=0

The moment i try to define the data source, catalog, user name and password if fails....

`az containerapp create \
  --name $Environment-$1 \
  --resource-group $ResourceGroup \
  --environment $Environment \
  --env-vars $EnvironmentVariables \
  --image $RegistryServer/$2 \
  --cpu 2.0 --memory 4.0Gi \
  --target-port 80 \
  --ingress 'external' \
  --query properties.configuration.ingress.fqdn \
  --registry-server $RegistryServer \
  --registry-username $RegistryUsername \
  --registry-password $RegistryPassword`

**Comment by ekjuanrejon** [comment]
So now i manage to get the environment variable but everything is in one envrionment variable

**Comment by jrunestone** [comment]
@ekjuanrejon sorry for the necro but would you mind sharing what you did to solve the issue if you recall? I'm having the same issue, passing environment variables as a variable to the command. I either get formatting errors or they all end up in one single entry.

**Comment by ekjuanrejon** [comment]
I don't recall what I did. But almost sure I moved to use azure bicep

**Comment by jrunestone** [comment]
Thanks anyway!
