### ISSUE TITLE
Cold Start

### ISSUE THREAD

**Issue by spyroskaravanis** [microsoft/azure-container-apps#199]
### This issue is a: (mark with an x)
- [ x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have created a .net core 6 web API with minimal APIs. Docker image is alpine.

I have enabled PublishReadyToRun

RUN dotnet publish "TestApi.csproj" -c Release -o /app/publish \
    -r linux-musl-x64 \
    --no-restore \
    -p:PublishReadyToRun=true \
    --self-contained true \
    /p:PublishTrimmed=true \
    /p:PublishSingleFile=true

but the cold start time is 5-6 seconds

**Expected behavior** 
I was expecting 1-2 seconds tops.

This means that we cannot use scaling from 0 on a web API.

**Comment by torosent** [comment]
The cold start times is depended on many factors such as image size.  We are working to reduce the cold start times in the infrastructure but even 1-2 seconds might be insufficient for certain workloads. You can set your min replica count to 1 to ensure that your app is always ready.

**Comment by spyroskaravanis** [comment]
Thanks for your answer. I have many microservices and I am trying to reduce the operational cost. 
A sample .net image is about 50 MB and it takes 5-6 seconds. 
Is it what is expected or am I doing something wrong?  
Is there some guide or best practices?
Are there benchmarks where we can see how image size affects the cold start times?
It would be nice if we could know the optimal configuration of a .net image in order to reduce the cold start times.
Thanks for your time.

**Comment by k-krupka** [comment]
I guess this is up to you to investigate. The minimal CPU is a value you can measure based on the metrics used by your container. Memory as well. In VS the diagnostic tools will be your friend, i.e.:
![](https://user-images.githubusercontent.com/20299573/179149174-a1e9054e-393d-44cc-93f7-950729656211.png)
Following @torosent  idea. Number of replicas 0 or 1 for webapp is also something you could measure. In Dev env maybe have 0 and in more user-impacted environments, start with 1? You just accept the cold start. It's nothing new in the container world.

**Comment by visualstuart** [comment]
Take a look at specifying a minimal number of containers to run as Idle. If the container is inactive, it gets billed at the Idle rate (I see about 1/8 the cost of the Active rate) and you won't be experiencing cold start times.
