### ISSUE TITLE
Allow me to Deploy using Docker Compose/Swarm YAML

### ISSUE THREAD

**Issue by RehanSaeed** [microsoft/azure-container-apps#2]
I'd like to take a Docker Compose or Docker Swarm YAML file and deploy it to multiple container apps.

- I'd like any features that are not supported to be configurable via a series of environment variables.
- There should not be any features that are not configurable and no downsides to this approach.
- Docker Compose/Swarm easily connects up containers to each other and gives them simple DNS names to facilitate this. I'd like container apps to be given equally simple DNS names, so they can talk to each other internally without me having to re-configure my app in any way or to give my app any knowledge that its hosted by container apps.

**Comment by dariagrigoriu** [comment]
This is currently not part of the Azure Container Apps roadmap but we definitely appreciate the insight and will keep watching for use cases here.
