### ISSUE TITLE
Azure Functions Support

### ISSUE THREAD

**Issue by cmenzi** [microsoft/azure-container-apps#20]
Is there a plan to support Azure Functions like you do on [AKS w/ KEDA](https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda)?

**Comment by ahmelsayed** [comment]
I think this should be tracked over at https://github.com/Azure/azure-functions-core-tools 

 a `func azure containerapp deploy ....` could take care of configuring/updating the correct scale rules for an app.

**Comment by MCGPPeters** [comment]
Wouldn't this already be supported with the current toolset I wonder? Creating an azure function with docker support, deploying that to your repo and provisioning it in? You can configure the scale rules in ACA... Correct me if I am wrong

**Comment by tomkerkhove** [comment]
Certainly can, question is can it be made simpler?

**Comment by MCGPPeters** [comment]
Missed that nuance in the comment  :)

**Comment by KaiWalter** [comment]
@tomkerkhove - I created this sample of deploying Function Apps side by side to test scaling with HTTP and Service Bus queue. What exactly are you missing? OK, there could be primitives to directly describe Function App - because as I did it, it is just another ASP.NET core container.

**Comment by tomkerkhove** [comment]
I'm not missing anything personally, the question above is to have a smoother way of deploying them because in the end, as you mention, they are just containers to run.

**Comment by cmenzi** [comment]
@tomkerkhove Yes, that was initially the idea. But running functions as container apps works quite good, but you need multiple tooling to deploy. 

In my opinion, after some weeks working on container apps, it became a "nice to have".

**Comment by curib** [comment]
Closing this issue, since this is now supported! Please see our docs for more information: https://learn.microsoft.com/azure/azure-functions/functions-container-apps-hosting
