### ISSUE TITLE
Feature Request: control outgoing traffic

### ISSUE THREAD

**Issue by torokzs** [microsoft/azure-container-apps#202]
**Is your feature request related to a problem? Please describe**.  
OutboundType LoadBalancer is used so even we have network integration whole environment does not seem to work with UDRs (hub and spoke) or vWAN systems. 

**Describe the solution you'd like**.    
Supported way to control outgoing traffic (for instance with Azure Firewall). 

**Describe alternatives you've considered**.   
In the technical MC resource group there is Load balancer with Outbound rule:
![aca](https://user-images.githubusercontent.com/36155767/165694935-21e8a866-9893-4f1e-9eeb-c80be49aea5a.png)
If I delete this rule, UDR is used and AZ FW is used, but I guess this is not supported setup since MC resource group shouldn't have to be modified.

**Additional context**.  
Looking for a user-friendly version of this: https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic

**Comment by torosent** [comment]
Thanks @torokzs. I added this feature request to our backlog and will discuss it.

**Comment by davidxw** [comment]
Some additional comments related to this feature request in this issue #255

**Comment by chinadragon0515** [comment]
refer to newest update in https://github.com/microsoft/azure-container-apps/issues/227

**Comment by chinadragon0515** [comment]
refer to newest update in https://github.com/microsoft/azure-container-apps/issues/227
