### ISSUE TITLE
Guidance for secret references in Dapr component files using the CLI

### ISSUE THREAD

**Issue by markheath** [microsoft/azure-container-apps#203]
The official documentation showing [how to deploy a Dapr application to Azure Container Apps using the CLI](https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash) instructs you to copy the storage account key directly into the Dapr state store yaml file. Obviously this is a non-ideal situation as the component definition is likely to be checked into source control.

It would be nice if we could use a secretRef here just like you would with a regular Dapr app on Kubernetes to access a k8s secret. 

However, the `az containerapp secret set` command only allows you to create secrets scoped to a containerapp, not to an environment and there seems to be no way to reference a containerapp secret in the component file.

I am wondering if there are any plans to improve this situation, or perhaps there is another recommended way of referencing secrets in component files I am unaware of. 

Even something very simple like allowing us to pass secrets as command line parameters to `az containerapp env dapr-component set` to override placeholders in the dapr component definition yaml would be an improvement.

I'd also love to see it be possible to make use of managed identities for the connection strings in the dapr component definitions. I see that there is some [managed identity support](https://docs.microsoft.com/en-us/azure/container-apps/managed-identity) for container apps, but doesn't look like it's possible to use them from Dapr component files at the moment. Are there any plans to support that?

**Comment by markheath** [comment]
I can see from the Dapr sidecar logs that the kubernetes secret store is getting configured by default which is nice:

```
time="2022-05-03T17:58:26.817680694Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes/v1" app_id=catalog instance=catalog--1vjhrle-5ddc4565d-jtplt scope=dapr.runtime type=log ver=edge
```

But so far I've not had any success using the Dapr secrets API to fetch a secret from it (getting an "unimplemented" exception which was not what I expected). Should it be possible? I'm not even sure if the secrets I set for my containerapp are put in that store anyway.

```
Dapr.DaprException: Secret operation failed: the Dapr endpoint indicated a failure. See InnerException for details.  ---> 
Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Not Implemented")
    at Dapr.Client.DaprClientGrpc.GetSecretAsync(String storeName, String key, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at Dapr.Client.DaprClientGrpc.GetSecretAsync(String storeName, String key, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)    
...
```

**Comment by kendallroden** [comment]
@markheath 
1. Dapr secrets API is not supported 
2. A comprehensive doc is coming this coming week 
3. You can define a secret directly in the dapr component but I understand your concern here 
4. We are working to parameterize yaml files

**Comment by markheath** [comment]
Many thanks for the update @kendallroden - glad to hear these things are all on the roadmap. Looking forward to the new features & docs.

For now I've written some powershell to create temporary component definition files containing my actual secrets so they don't get checked into source control.

**Comment by kendallroden** [comment]
Great closing this for now as we have an existing issue to track dapr secrets support! Thanks for your feedback and appreciate you using the platform!

**Comment by NMillard** [comment]
Are there any news on this?
Commenting here because I couldn't find a suitable active issue with the same problem.
