### ISSUE TITLE
Dapr components in a container app environment visibility

### ISSUE THREAD

**Issue by joeklin** [microsoft/azure-container-apps#204]
**Is your feature request related to a problem? Please describe**.  
There is no user friendly way to observe and/or configure dapr components in the a container environment

**Describe the solution you'd like**.    
A tab/blade in the container app environment that shows the available components and their configurations

**Describe alternatives you've considered**.   
Currently using CLI to view this information but it becomes cumbersome when the amount of components increases. The components are being set up via bicep templates but troubleshooting misconfigurations can be difficult when first starting

**Additional context**.

**Comment by BigMorty** [comment]
The UI for this in the portal is coming very soon!

**Comment by markheath** [comment]
This would be extremely useful for troubleshooting purposes. Ideally all the info that you can find in the Dapr dashboard should be available

**Comment by BigMorty** [comment]
The UI in the portal shows the different Dapr components and scopes for the Azure Container App environment. The Dapr dashboard does not show in the portal. @kendallroden, is the Dapr dashboard available in the running container app or elsewhere?

**Comment by markheath** [comment]
Maybe I'm misunderstanding you, but I can't see anything showing the Dapr components in the Azure portal at all. I've looked at the environment and the container app pages. Am I missing something obvious?

**Comment by BigMorty** [comment]
Ya, what I said above was "The UI for this in the portal is coming very soon!". Sorry if that was not clear.

**Comment by markheath** [comment]
Ah OK, gotcha. Looking forward to the new UI

**Comment by kendallroden** [comment]
Closing with the availability of Dapr in the portal!
