### ISSUE TITLE
Container apps programmaticlly subscribed to topics via dapr in azure bus do not show up in azure service bus

### ISSUE THREAD

**Issue by joeklin** [microsoft/azure-container-apps#205]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Container apps do not show as subscribers to topics in Azure Service Bus. 
When running in self hosted on local, the same containers show up in the Azure Service Bus UI. The containers correctly subscribe  to the topic and process the message and but its misleading to not see them active subscribers.

### Steps to reproduce
1.  Create a dapr component for Azure Service Bus
2.  Programmatically subscribe to a topic (my solution is in .NET)

**Expected behavior** [What you expected to happen.]
App shows as a subscriber when inspecting the Azure Service Bus topic

**Actual behavior** [What actually happened.]
App does not show as a subscriber

**Screenshots**         
![image](https://user-images.githubusercontent.com/3605836/165946072-a226ed40-16d8-4156-be72-cc2b5031f77e.png)

**Comment by joeklin** [comment]
@kendallroden  No we were connecting using the client pubsub component. It seems to have corrected itself and is showing up now. 

On a possibly related note, api management services is not picking up the container apps for import in the new namespace. If I redeploy to the old namespace the app will show up for import. We've moved to maintain the apis through source control but it seems that some of the azure services haven't picked up the namespace switch.

**Comment by kendallroden** [comment]
Thanks for reporting. I will check on apim but feel free to file an issue with apim team as well! Appreciate your feedback and glad things are working for you. Closing out this particular issue, if you need to open another for different issue please do!
