### ISSUE TITLE
Allow maxReplicas to be 32?

### ISSUE THREAD

**Issue by cmenzi** [microsoft/azure-container-apps#21]
When using Azure EventHubs there are 32 partitions possible. Would it make sense to allow the max value of maxReplicas to be 32 as well?

With this, each replica could process its own partition?

**Comment by dariagrigoriu** [comment]
We are considering updating quotas before GA, thank you for sharing this use case!

**Comment by BigMorty** [comment]
We have increased the max replicas to 30 now.
