### ISSUE TITLE
ARM PUT fails on ACR authentication

### ISSUE THREAD

**Issue by piizei** [microsoft/azure-container-apps#212]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When submitting ARM PUT payload, an error is received on ACR authentication:

`az rest --method put --uri /subscriptions/OMITTED/resourceGroups/rg-weu-dev-acr/providers/Microsoft.App/containerApps/xyzcontainerapp?api-version=2022-03-01 --body @body.json`

Bad Request({"code":"WebhookInvalidParameterValue","message":"The following field(s) are either invalid or missing. Invalid value: \"crweuxyzdev.azurecr.io/azuredocs/containerapps-helloworld:latest\": GET https://crweuxyzdev.azurecr.io/oauth2/token?scope=repository%3Aazuredocs%2Fcontainerapps-helloworld%3Apull&service=crweuxyzdev.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.: template.containers.helloworld.image."})

Payload:
```
{
	"location": "westeurope",
	"properties": {
		"configuration": {
			"ingress": {
				"external": true,
				"targetPort": 80
			},
			"registries": [
				{
					"passwordSecretRef": "registry-password",
					"server": "crweuxyzdev.azurecr.io",
					"username": "crweuxyzdev"
				}
			],
			"secrets": [
				{
					"name": "registry-password",
					"value": "OMITTED"
				}
			]
		},
		"managedEnvironmentId": "/subscriptions/OMITTED/resourceGroups/rg-weu-dev-acr/providers/Microsoft.App/managedEnvironments/myContainerAppEnv",
		"template": {
			"containers": [
				{
					"image": "crweuxyzdev.azurecr.io/azuredocs/containerapps-helloworld:latest",
					"name": "helloworld"
				}
			]
		}
	}
}
```

The container exists in the container registry. It works if the container reference is from public registry.

### Steps to reproduct
1. Run AZ cli command specified with the issue description using the json payload

**Expected behavior** [What you expected to happen.]
It should create a new container-instances with the container from private registry

**Actual behavior** [What actually happened.]
Gives error and dies.

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
az-cli

**Comment by hubatish** [comment]
I have also gotten this error message when running an az containerapp create command, e.g.:

`az containerapp create --resource-group my-resource-group --name app-name --environment my-1environment --image my-image.azurecr.io/serverless:latest`

When I run `sudo docker pull pkba396f1ea.azurecr.io/serverless/pi_bbp:latest`, that succeeds, so I suspect my error cause is more permissions rather than missing value.
