### ISSUE TITLE
Feature Request: Support for Dapr v1.7

### ISSUE THREAD

**Issue by k33lan** [microsoft/azure-container-apps#214]
**Is your feature request related to a problem? Please describe**.  

There are several features of Dapr that I wish to use (e.g querying Azure CosmosDb) in my container app services but as I understand it, container apps only support up to Dapr v1.4 currently which does not support this.

**Describe the solution you'd like**.    

After investigating an issue on the Dapr side here: https://github.com/dapr/dapr/issues/4459 Dapr's co-founder @yaron2 has said that container apps need to support Dapr v1.7 for querying to work properly (https://github.com/dapr/dapr/issues/4459#issuecomment-1112236588). Is it possible to confirm if the upgrade to 1.7 is planned from your side and when please? I have multiple projects waiting on this. :) 

**Describe alternatives you've considered**.   

I have considered hosting the services affected by this using a different hosting model. I have also considered dropping Dapr for the querying element and directly querying the 3rd party resource. However, these solutions represent issues related to time, duplication of effort and moving further away from container apps - which I don't want.

**Additional context**.  

If anyone knows a better workaround to being able to use container apps with Dapr querying, I'm all ears.

**Comment by kendallroden** [comment]
Upgrade in process
