### ISSUE TITLE
Deployment failure due to invalid scope

### ISSUE THREAD

**Issue by achaikou** [microsoft/azure-container-apps#215]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Container apps deployment seemingly randomly fails with message
```
{
    "status": "Failed",
    "error": {
        "code": "AuthorizationFailed",
        "message": "The client 'SERVICE_PRINCIPAL_OBJECT_ID' with object id 'SERVICE_PRINCIPAL_OBJECT_ID' does not have authorization to perform action 'Microsoft.App/locations/containerappOperationStatuses/read' over scope '/subscriptions/SUBSCRIPTION_ID' or the scope is invalid. If access was recently granted, please refresh your credentials."
    }
}
```
The message makes sense, because service principal which is used for deployment has access only to the resource group, not to subscription.

Unsure if issue has started this week or if our code changes lead to it being visible. 
Couple of deployments with this code passed, some were stuck. In the portal this error is seen, Microsoft.App/containerApps resource deployment status is "Forbidden" and deployment status was "in progress" rather than "failed".

**Expected behavior** 
Deployment always succeeds even if service principal has no access to the subscription itself.

**Actual behavior**
Deployment sometimes fails.

### Additional context
Deployment is done from CI (bicep files) with Service Principal. All the resources already exist and are updated with new image.

**Comment by bppn** [comment]
I have the same problem since of today.

**{
    "status": "Failed",
    "error": {
        "code": "AuthorizationFailed",
        "message": "The client 'a0145e66-a6d8-4f91-b447-xxxxxxxx' with object id 'a0145e66-a6d8-4f91-b447-xxxxxx' does not have authorization to perform action 'Microsoft.App/locations/containerappOperationStatuses/read' over scope '/subscriptions/xxxxxx' or the scope is invalid. If access was recently granted, please refresh your credentials."
    }
}**

**Comment by alecor191** [comment]
@ruslany do you have an ETA for the fix to be rolled out? Unfortunately, in my case the workaround of giving the SP access to the subscription is not an option (company security policy).

**Comment by Restogro** [comment]
+1 Please let us on know the ETA for the fix. we shall plan accordingly

**Comment by ruslany** [comment]
Thanks @alecor191 for confirming.

**Comment by csruchitaoza** [comment]
I'm getting same error rightnow in develop side , other developer can use that scope perfectly but from my side I'm getting error like scope is in invalid format should be in https or guild
