### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by ekjuanrejon** [microsoft/azure-container-apps#216]
How to use cloudflare with azure container apps.

**Comment by madhancock** [comment]
> How to use cloudflare with azure container apps.

Did you ever get this working? I've tried origin certs (ACA rejects it) and custom domains with valid certs but no joy (SSL handshake error).

**Comment by gjoshevski** [comment]
Check this blog post:
https://medium.com/@gjoshevski/azure-container-apps-aca-and-cloudflare-e63e16ae1c64
