### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by ekjuanrejon** [microsoft/azure-container-apps#217]
Getting the following error when using the portal to add a custom domain

Invalid Request: Container app secret(s) with name(s) cannot have a null value

**Comment by ekjuanrejon** [comment]
I had to inspect the put being sent and manually pass the container registry password in the request

**Comment by alex-frankel** [comment]
+1 seeing the exact same issue. @ekjuanrejon -- did resubmitting the request end up working for you?

**Comment by alex-frankel** [comment]
Looks like setting the custom domain is done with the `*.properties.ingress.customDomains` property is what I needed. I was able to set up my domain by adding the below bicep code snippet:

```bicep
resource containerApp 'Microsoft.App/containerApps@2022-03-01' = {
  ...
  properties: {
    ...
    configuration: {
      ingress: {
        ...
        customDomains: [
          {
            // todo - replace certId w/ real reference
            certificateId: '<RESOURCE_ID_OF_CERTIFICATE' // type is 'microsoft.app/managedEnvironments/certificates'
            bindingType: 'SniEnabled'
            name: '<CUSTOM_DOMAIN_NAME>'
          }
        ]
      }
    }
  }
}
```

**Comment by ekjuanrejon** [comment]
@alex-frankel I was adding the cert via the azure portal and i noticed that the docker secret value was missing.. I want to be able to do it via cli

**Comment by source-studio** [comment]
I couldn't seem to deploy a certificate using a Bicep template, due to the current restriction on the name property. Since `certificates` is a sub-resource of `managedEnvironments`, ARM obviously requires a `/` character to delimit the resource name of the parent and child resources. However, there is a restriction on the name property of the certificate that prevents the `/` character, which means deploying via a Bicep template is basically impossible at the moment, as far as I can tell. The Azure Portal bypasses this restriction because it currently doesn't use an ARM template. However, when exporting the ARM template via the Portal, I can see that the name of the certificate name is indeed of the format: `ENVIRONMENT-NAME/CERTIFICATE-NAME`.

For example, using the following Bicep template:

```bicep
resource environment 'Microsoft.App/managedEnvironments@2022-03-01' = {
  name: '<ENVIRONMENT-NAME>'
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: '<LAW-CUSTOMER-ID>'
        sharedKey: '<LAW-SHARED-KEY>'
      }
    }
  }

  resource certificate 'certificates' = {
    name: '<CERTIFICATE-NAME>'
    location: location
    properties: {
      value: '<BASE64-ENCODED-PFX>'
      password: '<PASSWORD>'
    }
  }
}
```

Yields the following error (`incorrect segment lengths`):

```json
{
    "code": "DeploymentFailed",
    "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
    "details": [
        {
            "code": "InvalidTemplate",
            "message": "Deployment template validation failed: 'The template resource '<DEPLOYMENT-NAME>' for type 'Microsoft.App/managedEnvironments/certificates' at line '1' and column '42435' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'."
        }
    ]
}
```

**Comment by vinisoto** [comment]
@ekjuanrejon, @alex-frankel - we had a recent deployment (completed on Monday evening PST) that contains a fix to this issue. Can you try again and if the issue still persists, share which Region are you using? Thanks!

**Comment by ekjuanrejon** [comment]
@vinisoto I will try again. I am using US East. Is the functionality available on the cli?

**Comment by vinisoto** [comment]
> @vinisoto I will try again. I am using US East. Is the functionality available on the cli?

Thanks. Not in CLi just yet. Targeting end of week of 5/23

**Comment by michaelmcneilnet** [comment]
> @ekjuanrejon, @alex-frankel - we had a recent deployment (completed on Monday evening PST) that contains a fix to this issue. Can you try again and if the issue still persists, share which Region are you using? Thanks!

We are hitting this just now in North Europe

**Comment by vinisoto** [comment]
> > @ekjuanrejon, @alex-frankel - we had a recent deployment (completed on Monday evening PST) that contains a fix to this issue. Can you try again and if the issue still persists, share which Region are you using? Thanks!
> 
> We are hitting this just now in North Europe

Thanks. Investigating.

**Comment by vinisoto** [comment]
> @ekjuanrejon, @alex-frankel - we had a recent deployment (completed on Monday evening PST) that contains a fix to this issue. Can you try again and if the issue still persists, share which Region are you using? Thanks!

I referred to a different deployment here. The deployment with the fix for this issue is still ongoing. I will update here once it completes (2-3 days).

**Comment by michaelmcneilnet** [comment]
> > @ekjuanrejon, @alex-frankel - we had a recent deployment (completed on Monday evening PST) that contains a fix to this issue. Can you try again and if the issue still persists, share which Region are you using? Thanks!
> 
> I referred to a different deployment here. The deployment with the fix for this issue is still ongoing. I will update here once it completes (2-3 days).

Just tried again and working in North Europe, thanks!

**Comment by m-v-k** [comment]
same issue, inspecting and editing the put request worked (need to add the "value":"mysupersecret" fields for each secret.
but now the binded certificate doesn't work....

**Comment by ekjuanrejon** [comment]
when will this functionality be available via the cli? every time we deploy new container (code changes) the custom domain is removed...

**Comment by vinisoto** [comment]
Portal fix and CLI functionality are available now. Closing this.
