### ISSUE TITLE
Deployment timeout when deploying App with disabled ingress

### ISSUE THREAD

**Issue by alecor191** [microsoft/azure-container-apps#218]
### This issue is a:
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When deploying an app with disabled HTTP ingress for the first time, deployment times out after ~10min.

### Steps to reproduct
1. Setup clean App Environment
2. Create an app with disabled Ingress
3. Deploy the app

**Expected behavior**
App is deployed successfully.

**Actual behavior**

- Deployment fails after ~10min.
- When looking at the App in Azure Portal during the deployment, I noticed that a revision appears in the "Revision Management" blade, but after a few seconds it disappears; then it appears again and disappears again after a few sec...as if it would deploy the app, then realize that something is wrong, removes the revision and tries again.
- I have a 100% repro when deploying an app for the first time; I also tried to create new App Environments from scratch, but it didn't help.
- I don't see any logs in Log Analytics that could help pinpoint the root cause (there are literally no logs in Log Analytics)

### Additional context

- This used to work until recently: I successfully deployed that same app several times during the past weeks. Only about ~1 week ago I started to notice this issue
- I found a workaround: *Enable* Ingress when deploying the app for the *first* time (external or internal doesn't matter, both work). Then, after successful deployment, remove the Ingress configuration and deploy the app again. Now also the second deployment works perfectly fine, and Azure Portal shows that ingress is correctly disabled. IOW this issue only exists when deploying an app for the first time. Updating configuration of an already deployed app works fine.

#### Activity log entry for failed deployment

Notice `statusMessage` field at the end of the JSON blob.

```json
{
    ...
    "correlationId": "71088ff5-bf2a-406b-af8a-dd0bad11cc29",
    "description": "",
    "eventDataId": "dacffdda-c6a4-424a-b8eb-2d6655238d26",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2022-05-16T06:11:09.5460725Z",
    "level": "Error",
    "operationId": "f56d8762-fb77-485d-842e-1e44d593ca51",
    "operationName": {
        "value": "Microsoft.App/containerApps/write",
        "localizedValue": "Create or Update Container App"
    },
    "resourceProviderName": {
        "value": "Microsoft.App",
        "localizedValue": "Microsoft.App"
    },
    "resourceType": {
        "value": "Microsoft.App/containerApps",
        "localizedValue": "Microsoft.App/containerApps"
    },
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "2022-05-16T06:12:52.1429041Z",
    "properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ContainerAppOperationError\",\"message\":\"Failed to provision revision for container app 'sub-app'. Error details: Operation expired.\"}]}}",
        "eventCategory": "Administrative",
        "message": "Microsoft.App/containerApps/write",
        ...
    },
    "relatedEvents": []
}
```

**Comment by alecor191** [comment]
@kendallroden thanks a lot for your suggestions.

I'm using [Pulumi](https://www.pulumi.com/) for the deployment. Specifically, I'm using the [Azure Native Pulumi provider](https://github.com/pulumi/pulumi-azure-native). From what I understand, it uses the ARM REST API under the hood.

Regarding Ingress/target port: I'm neither setting target port nor enabling Ingress (in the repro scenario). However, as I'm using Pulumi, I don't know what data is actually being sent by Pulumi in the ARM API call.

For context: The app doesn't listen/expose any port; it subscribes to Dapr PubSub with Azure Service Bus as backend.

I tried to repro today again after you mentioned that it works for you and I can still repro the issue with the steps above.

**Comment by Dmitrii034** [comment]
I am facing the same issue when deploying the [Tutorial: Deploy a Dapr application to Azure Container Apps using the Azure CLI](https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash), from the documentation. 
Everything goes fine until the deployment of the client application "pythonapp". The Portal page of the Container App says that the deployment is "In progress"  for ~10 minutes, then fails. At the same time you can see that the application actually works fine (if you look at the logs or at the storage account with the orders). However after this, information from Revision management and Container blades seems to disappear completely, from all Container Apps in the Environment.
Deployments of new Container Apps to the same Environment are also met with the timeout (tried with the sample image from the Portal).

**Comment by torosent** [comment]
We are investigating

**Comment by xwang971** [comment]
Hi, @alecor191 @Dmitrii034 This is fixed already and would be deployed to all regions in two weeks. To mitigate it, can you please enable the ingress when create the app?

**Comment by ItayPodhajcer** [comment]
I'm now seeing the exact opposite
When I deploy for the first time (using the new `azurerm_container_app` terraform resource) with ingress enabled the script fails with the same error as above.
Only after running once with the ingress disabled and then re-running with it enabled, the script succeeds.
