### ISSUE TITLE
Certificate Deployments via ARM Failing

### ISSUE THREAD

**Issue by source-studio** [microsoft/azure-container-apps#220]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I couldn't seem to deploy a certificate using a Bicep template, due to the current restriction on the name property. Since `certificates` is a sub-resource of `Microsoft.App/managedEnvironments`, ARM obviously requires a `/` character to delimit the resource name of the parent and child resources. However, there is a restriction on the name property of the certificate that prevents the `/` character, which means deploying via an ARM template is seemingly impossible at the moment, as far as I can tell. The Azure Portal bypasses this restriction because it currently doesn't use an ARM template. When exporting the template following creation of the certificate in the Portal, I can see that the name of the certificate is indeed of the format: `ENVIRONMENT-NAME/CERTIFICATE-NAME`, suggesting the current restriction on the name should be relaxed in order to allow templated deployments to operate as expected.

For example, using the following Bicep template:

```bicep
resource environment 'Microsoft.App/managedEnvironments@2022-03-01' = {
  name: '<ENVIRONMENT-NAME>'
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: '<LAW-CUSTOMER-ID>'
        sharedKey: '<LAW-SHARED-KEY>'
      }
    }
  }

  resource certificate 'certificates' = {
    name: '<CERTIFICATE-NAME>'
    location: location
    properties: {
      value: '<BASE64-ENCODED-PFX>'
      password: '<PASSWORD>'
    }
  }
}
```

Yields an error similar to the following:

```
Certificate name '<ENVIRONMENT-NAME>/<CERTIFICATE-NAME>' is invalid. A value must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
```

**Comment by kendallroden** [comment]
Thanks for reporting. Will send to engineering and get back to you!

**Comment by kendallroden** [comment]
Also @source-studio, in the meantime can you use the approach which allows you to specify the parent using a param? This should solve your problem if I am not mistaken. Can you confirm if this would work for you?

`resource caEnvironment  'Microsoft.App/managedEnvironments@2022-01-01-preview' existing = {
  name: containerAppsEnvName
}

resource daprComponent 'Microsoft.App/managedEnvironments/daprComponents@2022-01-01-preview' = {
  parent: caEnvironment
  name: 'statestore'
`

**Comment by vinisoto** [comment]
We are in the process of producing a fix and deploying it. It will take a few days to complete globally. I will update here once the deployment is complete.
