### ISSUE TITLE
DAPR ANNOUNCEMENT: Removal of default content type for Dapr service invocation 

### ISSUE THREAD

**Issue by kendallroden** [microsoft/azure-container-apps#222]
### Context
You may have noticed the following deprecation warning when working with Dapr via the Dapr CLI or when viewing Container Apps dapr logs via log streaming or log analytics. 

`[DEPRECATION NOTICE] Adding a default content type to incoming service invocation requests is deprecated and will be removed in the future. You can opt into the new behavior today by setting the configuration option ServiceInvocation.NoDefaultContentType to true.`

This announcement pertains to the above and explains our path forward in Container Apps to address this deprecation.

### Previous Behavior 
In Dapr, when no content-type header value was provided for service to service calls, Dapr would set a default value of `application/json` 

### New Behavior 

Having the `ServiceInvocation.NoDefaultContentType` set to `true` will become the default Dapr behavior in release v1.9.0. For Container Apps, in order to minimize the disruption of this change for customers in the future, this behavior is enabled by default in the Container Apps Dapr version 1.7.3. 

## Action Items
Enablement of this feature will require you to explicitly set content-type headers for Dapr service invocation api calls as required for your apps.

## Reference

* [Standardize use of content type in runtime and SDKs](https://github.com/dapr/dapr/issues/4301)

## Feedback and questions

While the service is in preview, we recognize this could be a breaking change for some customers. We are working directly with the Dapr project maintainers to create a reliable process for similar changes.

Let us know if you have any questions or feedback by [opening an issue](https://github.com/microsoft/azure-container-apps/issues) or sharing your comments below. 

cc: @greenie-msft @ahmelsayed

**Comment by berndverst** [comment]
Additionally, you may be wondering how you can tell whether you are impacted:

If your applications being called via Dapr Service Invocations previously treated the request body as JSON (for example this can be quite comment using Python with the Flask framework) the request parsing in your app will now fail as the content-type is no longer `application/json`. As stated above, please explicitly specify the content type during the Dapr Service Invocation call.
On the receiving side we also recommend that you explicit check for the content type of the service invocation request.

Here is an example of something that would fail:

```python

from flask import Flask, request

app = Flask('__name__')

@app.route('/invoke')
def invoke_from_dapr():
  body = request.json  # this will fail unless the content type is explicitly set
  # if content type is set body is now a dictionary representation of the JSON request body
  # other logic here...

if __name__ == '__main__':
  app.run(host='0.0.0.0', port=80)
```
