### ISSUE TITLE
dapr telemetry

### ISSUE THREAD

**Issue by sf-declanomalley** [microsoft/azure-container-apps#223]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
there is no documentation that shows how to setup telemetry correctly while using dapr in container apps, only kuburnetes. We can specify app insights in the container apps environment but no metrics regarding the dapr sidecar are logged, including errors. I would expect to see sidecar telemetry and errors, we are only seeing service invocation and http requests with no errors.

does container apps utilise the "open telemetry collector" as referenced in the dapr documentation for setting up kuburnetes?

### Steps to reproduce
1. setup container apps environment with app insights
2. create 2 services, one should invoke the other through the dapr sidecar
3. build the 2 images
4. push the 2 images to container apps specifying a dapr sidecar setup
5. call the service , which should call the other service through the sidecar

**Expected behavior** [What you expected to happen.]
telemetry similar to zipkin when running dapr locally including errors being caught by sidecar . telemetry should show the sidecars talking to each other and then the service, this helps with resolving where an error occurred especially through a long chain of requests. because no errors are logged we cannot see what the request payloads were to resolve.

**Actual behavior** [What actually happened.]
service makes a http call to the other service. the sidecar forwarded request is hidden.  no errors logged

**Screenshots**         

### Additional context
calling a dapr workflow through a sidecar that errors doesn't log anything in errors or app insights to show the request failed. this is an issue because the dapr workflow service contains no error logging and therefore there is no flag of an error occurring. running locally these errors are captured through zipkin.

**Comment by kendallroden** [comment]
Please refer to the following documentation: https://docs.microsoft.com/en-us/azure/container-apps/dapr-overview
Application insights is currently the supported export location for distributed tracing, and you can provide the app insights connection info during environment create to wire this up! We will likely expose the configuration for this in the future.

**Comment by sf-declanomalley** [comment]
please refer to my "steps to reproduce" section , step 1 . I have setup the environment with app insights but have no sidecar telemetry/errors.

**Comment by kkilton** [comment]
There is still no ACA documentation on how to configure OTEL
