### ISSUE TITLE
Property 'secrets.name' has an invalid value

### ISSUE THREAD

**Issue by sutinse1** [microsoft/azure-container-apps#224]
Createting new ACA using existing ACR

az containerapp up --name aca-otso-sutinense-test001 --source . --registry-server acrotsosutinse1dockertest1.azurecr.io --registry-user seppo.sutinen@iurcgifisaas.onmicrosoft.com --registry-password $ACR_TOKEN

Creating Containerapp aca-otso-sutinense-test001 in resource group rg-otso-sutinse1-container-apps-test1
Property 'secrets.name' has an invalid value 'acrotsosutinse1dockertest1azurecrio-seppo.sutinen@iurcgifisaas.onmicrosoft.com'. A value must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.

**Comment by torosent** [comment]
What is the user name you see in the ACR resource? I think it should be just `seppo.sutinen`

**Comment by sutinse1** [comment]
My mistake, ACR credentials was wrong like @torosent advice.

Using right ACR credentials worked fine. Also password is password, not token :)

az containerapp up --name aca-otso-sutinense-test001 --source . --registry-server acrotsosutinse1dockertest1.azurecr.io --registry-user acrotsosutinse1dockertest1 --registry-password mypassword
