### ISSUE TITLE
dapr telemetry

### ISSUE THREAD

**Issue by sf-declanomalley** [microsoft/azure-container-apps#225]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
having configured container apps environment with app insights (see https://github.com/microsoft/azure-container-apps/issues/223) I only see http requests and my services receiving requests in app insights, with no errors. is this by design? local development with the dapr sidecar gives much greater telemetry/error experience through zipkin with no additional configuration.

### Steps to reproduce
1. container apps environment with app insights configured
2. 2 container services with dapr sidecar enabled
3. communicate to each other through dapr sidecar invocation

**Expected behavior** [What you expected to happen.]
sidecar telemetry and errors.
**Actual behavior** [What actually happened.]
no sidecar telemetry or errors, just http requests
**Screenshots**

**Comment by ahmelsayed** [comment]
dapr stdout logs are available in the log analytics workspace defined on the environment. Dapr's Application Insights integration is for request tracing https://docs.dapr.io/operations/monitoring/tracing/open-telemetry-collector-appinsights/

**Comment by sf-declanomalley** [comment]
@ahmelsayed . Thanks for the reply. I have been using logs to retrieve stdout. the url you linked to me is for running insights for kuburnetes, which I'm not doing, I am running in container apps so do not have access configure open telemetry .

**Comment by ahmelsayed** [comment]
Sorry maybe I misunderstood the type of telemetry you're after.

tagging a couple of dapr experts to weigh on this @berndverst @ItalyPaleAle

**Comment by sf-declanomalley** [comment]
will generate some screenshots and post shortly.

**Comment by tjoudeh** [comment]
Hello @kendallroden @ItalyPaleAle @torosent 

I'm currently using 1 App Insights instance and I have 3 Azure Container Apps deployed to 1 single Container Apps Env.

The service named "tasksmanager-frontend-webapp" sends a sync request to the service named "tasksmanager-backend-api" then, the backend API service publishes a message to the Azure Service Bus topic, which the service named "tasksmanager-backend-processor" consumes this message and sends an email via SendGrid, you can check the [arch diagram](https://user-images.githubusercontent.com/3114431/186751157-c2857bf1-8db9-492b-92ce-6127209a6757.jpg) of my project. I'm using Dapr service to service and pub/sub application blocks to achieve this.

What I see in the AppInsights Application map is the below diagram, there is no relation (arrow) between the Frontend App and the Backend App, not there is no relation between the backend service and service bus for example.

What is a document [here](https://docs.dapr.io/operations/monitoring/tracing/open-telemetry-collector-appinsights/) that will work when we deploy to K8S only, right?

So I was wondering how we can achieve proper tracing for distributed services when deploying to Azure Container Apps and integrate it with App Insights.

The [source code](https://github.com/tjoudeh/TasksTracker.ContainerApps) of the project is available here, nothing explicit done other than setting the env variable "ApplicationInsights__InstrumentationKey" on the 3 services when deploying to ACA and installing the NuGet "Microsoft.ApplicationInsights.AspNetCore" on the 3 services.
![image](https://user-images.githubusercontent.com/3114431/187459516-9d9a1bee-a020-42d6-990b-8f13c4136607.png)
