### ISSUE TITLE
custom domain certificate error 'cannot have a value of null'

### ISSUE THREAD

**Issue by m-v-k** [microsoft/azure-container-apps#226]
### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Adding a pfx certificate (wildcard) to a custom domain fails with error
"Failed to add hostname ....... Invalid Request: Container app secret(s) with name(s) 'microsoft-provider-authentication-secret, someothername...' cannot have a value of null."
It seems that the add certificate step tries to add a secret, and when it does it's trying to update the already existing ones with null values (secrets for authentication and acr access)

### Steps to reproduct
1. in the portal, in a container app
2. set some secret
3. add custom domain (including dns validation)
4. in next step, 'bind certificate and add' select (browse) a certificate set name and password
5. wait
6. get error

**Expected behavior** [What you expected to happen.]
custom domain is added with certificate mapped, other secrets remain unchanged

**Actual behavior** [What actually happened.]
error, no custom domain is added.

**Screenshots**         
![image](https://user-images.githubusercontent.com/42929057/169790608-64045fdd-fcbc-42aa-8026-894b97647908.png)

### Additional context
in portal

**Comment by vinisoto** [comment]
Hi @m-v-k - we recently completed a Portal deployment (a couple of hours ago) that addresses this issue. Can you please retry and see if the issue persists? If it does persist, could you please open a New Support Request via the Azure Portal so we can follow up? Thanks!

**Comment by m-v-k** [comment]
verified it's fixed.
thanks, closing issue.
