### ISSUE TITLE
certificate not valid error with container app (but works on app service)

### ISSUE THREAD

**Issue by m-v-k** [microsoft/azure-container-apps#229]
### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

custom domain certificates not working. Tried with 2 certificates and 2 hostnames, but keep getting the typical ssl error on the client _'SSL peer certificate or SSH remote key was not OK'_  if i disable ssl validation with curl or any other tool it works just fine (in firefox i can also see that correct certificate is being used, so not a k8s self-signed or something). tested in different browsers on different systems, all same error. created a azure app service and added the same container, custom domain and certificate, this works just fine.

maybe something is wrong with trust of intermediate or root cert?
or maybe some missing cypher suite?

### Steps to reproduce
1. add custom domain and upload certificate

intermediate = Sectigo RSA Domain Validation Secure Server CA (http://crt.sectigo.com/SectigoRSADomainValidationSecureServerCA.crt)
root = USERTrust RSA Certification Authority
(tried both 2k and 4k keysize, tried both wildcard and single hostname, signature SHA-256 ECDSA)
subscription = dee80dd6-41ab-4def-84ab-28fa6ed279d1
resourcegroup = ssp

**Expected behavior**

same as app service, app works on custom domain with ssl from my mapped certificate.
or....
document (minimum) specs of supported certificates.

**Actual behavior**

getting ssl not valid error on all clients  when using container app (but works with identitcal cert & hostname on app service)
and optionally
no information available about certificate requirements

**Screenshots**

**Comment by torosent** [comment]
Can you open a support ticket with your details and we will investigate? 
FYI @vinisoto

**Comment by m-v-k** [comment]
unfortunately i cannot, it sits on a subscription without support plan.

**Comment by vinisoto** [comment]
@m-v-k - can you shoot me an email: vsoto at microsoft dot com? Here is what we would need:

Region
Subscription
Container App Environment name
Container App Name

Description on how/where did you acquire the certificate so I can try and repro.

**Comment by m-v-k** [comment]
@vinisoto  sure, done

**Comment by vinisoto** [comment]
thanks @ahmelsayed for investigating.

@m-v-k - The certificate that you provided doesn't have the full chain (i.e. doesn't have the intermediate certificates). App Service is indeed building the full chain for you, but in Container Apps we require that the certificate has the full chain. 

We will publish this guidance and also discuss internally how/if to build the full chain when it is not present in the certificate provided.

Thanks!

**Comment by m-v-k** [comment]
great, i can work with that!
thanks a lot guys.

**Comment by graemefoster** [comment]
Just to double check this @vinisoto I have a LetsEncrypt certificate that definitely contains the full chain but am seeing this issue when binding a custom domain on container apps. 

Output of openssl pkcs12 -in C:\temp\foo.pfx -chain -nokeys shows 3 certs. Mine, the R3 intermediate, and the ISRG Root X1.

Everything looks good when I import the pfx and bind a custom domain in the container app.

But when I try and curl, openssl fails: "Verify return code: 21 (unable to verify the first certificate)". It only reports the leaf certificate as being presented.

Happy to share my pfx file if you want?

**Comment by torosent** [comment]
> Just to double check this @vinisoto and @ahmelsayed I have a LetsEncrypt certificate that definitely contains the full chain but am seeing this issue when binding a custom domain on container apps.
> 
> Output of openssl pkcs12 -in C:\temp\foo.pfx -chain -nokeys shows 3 certs. Mine, the R3 intermediate, and the ISRG Root X1.
> 
> Everything looks good when I import the pfx and bind a custom domain in the container app.
> 
> But when I try and curl, openssl fails: "Verify return code: 21 (unable to verify the first certificate)". It only reports the leaf certificate as being presented.
> 
> Happy to share my pfx file if you want?

Hi. We have a fix for this issue and it will be deployed in the next couple of weeks to all regions.

**Comment by asankaf** [comment]
Hi,

I have a same sort of issue when trying to bind an exported wildcard certificate that was generated as an Azure App Service Certificate. As @graemefoster mentioned, `openssl pkcs12 -in C:\certstore\appserviceswildcardcert.pfx -chain -nokeys` clearly shows the full chain with the 3 certs. When I upload the certificate to the container apps environment and bind it to a custom domain in a container app, the app doesn't really work with the custom domain. 

nslookup to the custom domain correctly shows that the DNS level name resolution takes place just fine. If I navigate to the container app generated https endpoint (xxx.azurecontainerapps.io), it works just fine too, but not the custom domain. 

![image](https://user-images.githubusercontent.com/1999525/176691319-ea883874-7b63-435c-9538-aeb61a7f7702.png)

Weird thing was that this setup used to work just fine a couple of weeks ago. But all of a sudden it stopped working this week. Any advice on what is going on here?

**Comment by Mathijs-Dijk** [comment]
Hi,

We have an issue uploading a certificate to the Container Apps certificates. 
When we try to upload the certificate via the Azure Portal we get the following error:
![image](https://user-images.githubusercontent.com/108129056/177984443-74ccac8c-1bff-48c4-95a1-142293e4d807.png)

The password is correct though.

When I try to upload the certificate via CLI I get the following error:
![image](https://user-images.githubusercontent.com/108129056/177984863-7aa8bcbf-652e-4e46-93e3-7a80bf07f08b.png)

Now the pfx contains 3 keys (domain, intermediate and root) in that exact same order.
When I try with 1 private key same error.

The certificate is uploaded to KeyVault and used by App Services and Function Apps without any problem.
The error does not say much. When using the --debug option the error is : {"code":"CertificateMustContainOnePrivateKey","message":"Certificate must contain one private key."}

What is going wrong here?

**Comment by AndrewTriesToCode** [comment]
@torosent is that update deployed yet?

**Comment by vinisoto** [comment]
@AndrewTriesToCode, @asankaf, @Mathijs-Dijk - since this github issue is closed, can you open new ones (if still required)?

@AndrewTriesToCode, @asankaf - We had an issue where the full cert chain was not being preserved when uploading the certificate to the Container App Environment. The fix for that issue has been deployed.

@Mathijs-Dijk - Container Apps only supports PFX (if you have a PEM, you have convert it to PFX) that contain **exactly one** private key. If this doesn't help, can you open a support ticket?

**Comment by Mathijs-Dijk** [comment]
@vinisoto I have been helped by MS Support. Issue is resolved by adding the certificate on my local machine. Then the upload worked. The message "Certificate must contain one private key." was very confusing and actually telling what was going wrong.

**Comment by asankaf** [comment]
@vinisoto I can confirm that the container apps with a wildcard cert are working now. Thank you for the update.

**Comment by dyardy** [comment]
I have the same issue when trying to attach a certificate (pfx) with a password to the container app.  
"Failed to add new private key certificate" "The certificate ___ is invalid, or password is incorrect."  I see above that it should work with a wildcard certificate.  We keep the certificate in our key vault and have no issues with it.
