### ISSUE TITLE
Request to have a functionality of the update with traffic weight=0.

### ISSUE THREAD

**Issue by yoshioterada** [microsoft/azure-container-apps#23]
Every time I update the new image, it will replace it from the old to the latest version.
At that time, during the start-up time(during provisioning) of the new image, it stops receiving the new request from outside.
And new version may have some technical issues. The user may not want to show the issue to end-users.

At that time, if we can update the new image with traffic weight 0, we may solve the issue.

However, now it may be difficult to execute like this. 
Because during the update of the new image, we can’t understand the new revision name look like follows.

Run **az containerapp update** --name name --resource-group rg-name --image test.azurecr.io/imagename:6 --target-port 8080 **--traffic-weight 0**
az containerapp update --name name --resource-group rg-name --image test.azurecr.io/imagename:6 --target-port 8080 --traffic-weight 0
  shell: /usr/bin/bash -e 0
  env:
    DOCKER_CONFIG: /home/runner/work/_temp/docker_login_1635950822126
    JAVA_HOME_11.0.13_x64: /opt/hostedtoolcache/jdk/11.0.13/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.13/x64
    JAVA_HOME_11_0_13_X64: /opt/hostedtoolcache/jdk/11.0.13/x64
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
WARNING: Command group 'containerapp' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
ERROR: **--traffic-weight: must be in format "<revision>=<weight>,<revision>=<weight>,..."**

**Comment by ahmelsayed** [comment]
If you have a revision named `A` that you would like to pin it to 100% you can do 

```
az containerapp update --name name --resource-group rgname --traffic-weight A=100
```

Then when you do an update, for example `az containerapp update --name name --image {new-image} ...` 

That will create a new revision `B`, but since you explicitly set `A=100`, `B` won't get any traffic by default. You can then slowly sihft traffic to it. 

```bash
# Start with 20% of traffic to the new revision `B`
az containerapp update --name name --resource-group rgname --traffic-weight A=80,B=20

# test or sleep for a while, then change to 50/50
az containerapp update --name name --resource-group rgname --traffic-weight A=50,B=50

# If everything looks good with B, set 100 traffic to it. 
az containerapp update --name name --resource-group rgname --traffic-weight A=0,B=100
```

If you want to restore the default behavior you can do 

```
az containerapp update --name name --resource-group rgname --traffic-weight latest=100
```
