### ISSUE TITLE
Feature Request: region availability for norwayeast

### ISSUE THREAD

**Issue by davidkarlsen** [microsoft/azure-container-apps#230]
**Is your feature request related to a problem? Please describe**.  
We are interested in container apps in the norwayeast (and west) regions.

**Describe the solution you'd like**.    
Please consider norwayeast as a target region as soon as possible after GA.

**Describe alternatives you've considered**.   
We need to seek solutions from other vendors that are present in our regions.

**Additional context**.  
We are aware that container apps is currently not GA and in public preview - but we need it in our home region.

**Comment by torosent** [comment]
Hi. ACA is GA now and you can find the updates regions list in the portal. We will have more regions in the upcoming months but I can't share ETA for Norway yet.

**Comment by onionhammer** [comment]
@torosent what about other regions like central US?

**Comment by torosent** [comment]
We are working on new regions like central us but I don't have an ETA yet.

**Comment by bgmonroe** [comment]
Please add the list of available regions to the ACA documentation (https://docs.microsoft.com/en-us/azure/container-apps/).

**Comment by onionhammer** [comment]
Seems like central us is available now?

**Comment by torosent** [comment]
Norway and central us are available now.

**Comment by davidkarlsen** [comment]
How about norway-west? We need it for DR-purposes.
