### ISSUE TITLE
Can't change scale via Portal UI - SecretRef not found

### ISSUE THREAD

**Issue by michaelmcneilnet** [microsoft/azure-container-apps#231]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When creating a new revision via the portal to change scale rules, the deployment fails because the existing revision has secrets

### Steps to reproduce
1. Go to Azure Container Apps > Revisions > Scale
2. Select a revision with secrets and give it a new name
3. Click next to the scale screen, and then Create

**Expected behavior**
The new revision is deployed

**Actual behavior**
An error notification stating `Failed to deploy new revision: SecretRef 'my-secret' defined for container 'my-container' not found.`

**Comment by torosent** [comment]
Hi. I'm able to reproduce this error. Can you open a support ticket with your details and we will investigate?

**Comment by torosent** [comment]
Please send me an email `torosent at microsoft dot com`

**Comment by michaelmcneilnet** [comment]
> Please send me an email `torosent at microsoft dot com`

I've sent you an email, we can still replicate this every time.

**Comment by kendallroden** [comment]
Hi Chris- so sorry for the delay. These issues get buried sometimes and trying to be more proactive about checking in. @chris-ray can you let me know if this is still something you are struggling with or if the issue has resolved?

**Comment by chris-ray** [comment]
@kendallroden No, i'm not struggling with this issue anymore, although I haven't tried to do any scaling operations from the portal since I reported it. I do all ACA operations through bicep deployments now. Thanks.
