### ISSUE TITLE
How do I set internalOnly for the environment?

### ISSUE THREAD

**Issue by masters3d** [microsoft/azure-container-apps#232]
> Please provide us with the following information:
> ---------------------------------------------------------------

<img width="469" alt="image" src="https://user-images.githubusercontent.com/6539412/170533434-5c6af708-3bad-4558-92e3-1b3ad1840ae2.png">

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduct
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by ahmelsayed** [comment]
internalOnly environments are ones that are ones running with a custom vnet setup https://docs.microsoft.com/en-us/azure/container-apps/vnet-custom-internal?tabs=bash&pivots=azure-portal

**Comment by masters3d** [comment]
Is this only available to certain regions? I deployed one yesterday  to eastus2 with a custom vnet and the option is grayed out for me. Is there a CLI or ARM template option

**Comment by masters3d** [comment]
The confusion for me is that the internalOnly is part of the enviroment but it can not be changed after the enviroment has been created ( at least from the portal). Once the environment is created then as public ingress option is grayed out (makes sense now). I guess having the option to change the environment to be internal from the environment would be nice ( when attached to vnet)

![image](https://user-images.githubusercontent.com/6539412/170810328-7e19c271-75bd-4865-8f29-64d5c0db6327.png)

![image](https://user-images.githubusercontent.com/6539412/170810348-40d612f7-7f59-4324-8082-1197703b59f1.png)

**Comment by masters3d** [comment]
Looks like the are some resources deployed in the customer subscription for this magic to work. Its a little surprising and it kind of makes sense why this is not a option on the environment. I would love it if there a link to the mc_ resource group so folks can see the stuff powering this magic since it is deployed in the subscription.

**Comment by masters3d** [comment]
https://docs.microsoft.com/en-us/azure/container-apps/networking#managed-resources
Managed resources
When you deploy an internal or an external environment into your own network, a new resource group prefixed with MC_ is created in the Azure subscription where your environment is hosted. This resource group contains infrastructure components managed by the Azure Container Apps platform, and shouldn't be modified. The resource group contains Public IP addresses used specifically for outbound connectivity from your environment and a load balancer. As the load balancer is created in your subscription, there are extra costs associated with deploying the service to a custom virtual network.
