### ISSUE TITLE
Default revision log query in portal is invalid

### ISSUE THREAD

**Issue by mmckechney** [microsoft/azure-container-apps#233]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [x ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When opening the logs for a container app revision details, the default query that is generated is invalid

### Steps to reproduce
1. In the Azure portal blade for a container app, click on "Revision Management"
2. Select a revision name to open the "Revision Details" fly-out
3. Select "View Details" for Logs
<img width="269" alt="image" src="https://user-images.githubusercontent.com/7117089/170776772-3f07bd58-e969-415e-acf9-f3daebde80e2.png">
4. The log analytics window that opens with a default query has an incorrect syntax ( RevisionName_s is not valid in the ContainerAppSystemLogs_CL table)

  ```
ContainerAppConsoleLogs_CL 
| where RevisionName_s == "<revision name>"
```
<img width="329" alt="image" src="https://user-images.githubusercontent.com/7117089/170777198-0c15a217-35bc-444c-8dc1-5dc712dd6e15.png">

**Expected behavior**
The query that should be created would reference the ContainerAppSystemLogs_CL  table

```
ContainerAppSystemLogs_CL 
| where RevisionName_s == "<revision name>"
```

**Comment by dariagrigoriu** [comment]
@mmckechney, this should be addressed, please validate.

**Comment by mmckechney** [comment]
@dariagrigoriu - yes, this has been fixed and works great. Thank you.
