### ISSUE TITLE
custom domains are cleared when updating a container app via command line

### ISSUE THREAD

**Issue by vmantese** [microsoft/azure-container-apps#234]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I noticed that when using the az containerapp up command in my azure devops pipeline to update a container app with a new image the custom domains are all cleared.

### Steps to reproduct
1. Create a container app custom domain
2. Update container app via command line (az containerapp up)
3. Check custom domains

**Expected behavior** [What you expected to happen.]
Custom domains remain

**Actual behavior** [What actually happened.]
custom domains are cleared

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
Occurs via cli but visible in portal

**Comment by panchagnula** [comment]
Thanks for reporting we are taking a look at this. @vmantese can you run az--version & share what cli version being used. Thanks!

**Comment by panchagnula** [comment]
> I'm able to repro this in the latest version. It looks like the CLI is missing the existing ingress settings on the PUT call for `az containerapp up`. I'll start working on a fix

Thanks for the update - out of curiosity is there a reason CLI "up" doesn't use PATCH for existing apps instead of PUT - that will cause such behavior

**Comment by StrawnSC** [comment]
It looks like I was mistaken -- we actually do call PATCH for updates. This might be an API error then since having custom domains as null shouldn't clear them if the method is PATCH

**Comment by panchagnula** [comment]
> It looks like I was mistaken -- we actually do call PATCH for updates. This might be an API error then since having custom domains as null shouldn't clear them if the method is PATCH

@vinisoto FYI - since this seems to be a API issue with PATCH?

**Comment by vmantese** [comment]
Here is the version number from azdevops.

From logs:

Starting: AzureCLI
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================

**Comment by vmantese** [comment]
@StrawnSC  Do you publish your forked versions anywhere or should I wait for an official version bump?

**Comment by StrawnSC** [comment]
@vmantese the [azure CLI](http://github.com/azure/azure-cli-extensions) and the [azure CLI extensions](http://github.com/azure/azure-cli) repos are both open source. My forks are public, but I wouldn't recommend going using a non-release version of the containerapp CLI extension. 

We're targeting a 6/7 release for [the update with this fix](https://github.com/Azure/azure-cli-extensions/pull/4879).
