### ISSUE TITLE
documentation required for VNET when setting up container environment

### ISSUE THREAD

**Issue by mfatbmw** [microsoft/azure-container-apps#237]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Please provide information on network requirements for setting up a Container Apps Environment when using an  already provided VNETs.
For the preview there was the Information that 2 /21 subnets were necessary for the control plane and the app subnet.

There is to my knowledge no clear documentation on the minimum requirements for the VNETs are at the moment. (when providing your own)

### Steps to reproduct
none.

**Expected behavior** [What you expected to happen.]
Clear concise documentation on the necessary VNET sizes and restrictions

**Actual behavior** [What actually happened.]
No documentation available.

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by BigMorty** [comment]
@craigshoemaker Can you help get this page updated with the /23 requirements - https://docs.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-portal
