### ISSUE TITLE
Custom domain, SNI and self signed cert

### ISSUE THREAD

**Issue by benc-uk** [microsoft/azure-container-apps#239]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm trying to the custom domain feature of ACA. To do so I am required to provide a TLS cert with SNI. So I am using openssl command line to generate a self signed one.
After configuring it all in ACA, when I access the app via the custom domain, I get "connect reset by peer" error

Questions:
- Is there anywhere I can see errors relating to the cert? I looked in the LA logs and saw nothing
- I notice that "Solution" is always blank in the portal, I don't know if that is related
- Is it possible to use self-signed certs with ACA? If so could the steps be documented?

### Steps to reproduce
1. Create a self signed cert using openSSL. [This is the command I've been using](https://gist.githubusercontent.com/benc-uk/3c4b00ce33432ade88914aee28737c4c/raw/9774cc05caa283656c56d209f9c18dcb56f59817/self-sign.sh)
2. Configure ACA as per the docs, e.g. setup & upload the cert, add DNS records, add custom domain to ingress in ACA
3. Try to hit the site with `curl http://foo.mydomain.com` 

**Expected behaviour** [What you expected to happen.]
I am able to access the site, even if I get a browser warning about the self signed cert

**Actual behaviour** [What actually happened.]
Connect reset by peer error is returned 

### Additional context
I've configured ACA with the cert and domain using the portal and using Bicep. It makes no difference.

**Comment by torosent** [comment]
Did you also ran `openssl pkcs12 -inkey cert.key -in cert.pem -export -out test.dev.export.pem` and used the output cert?
Also, note that your app will still have self sign cert and you will have to tweak your browser. 
For curl, you can add `--insecure`

**Comment by benc-uk** [comment]
Just including here, what I covered in our chat

The error I was seeing was connection reset, I got this error when using the PEM formatted cert, when I tried pkcs12 format, then it works, with the warnings (which is what I expected with a self signed cert)

It seems like the cert must be in PKCS12 format to work with ACA, **however it lets you upload and try with PEM**, and doesn't tell you that it's not going to work. I still feel like there might be a bug or issue here, perhaps disallow PEM format certs?

**Comment by kendallroden** [comment]
Thanks @benc-uk we will discuss the best way to handle this within the platform and make sure it is documented as well.

**Comment by RamParameswaran** [comment]
:clap: Thanks @benc-uk. I had the exact same problem - and this issue saved me a huge amount of time.
Agreed that the platform should handle this better.
