### ISSUE TITLE
Support the KEDA `ScaledJobs` / Jobs Pattern

### ISSUE THREAD

**Issue by jeffhollan** [microsoft/azure-container-apps#24]
KEDA supports a pattern of `ScaledJobs` for containers or jobs that "run to completion".  This is especially useful if you are pulling messages from a queue or event source and want to have it run to completion without scaling down

https://keda.sh/docs/2.4/concepts/scaling-jobs/

This could also be merged with the traditional "job" concept - and expose a "manual invoke" ability where you can kick off the job without it being tied to an event with something like `az containerapp invoke-job -n myjob --image {}`

**Comment by guidooliveira** [comment]
This would support one of my most needed use cases, having it work as an Azure Pipelines/Github Actions pool.

**Comment by shahiddev** [comment]
Adding my voice to this too. This is key for us to enable the use of containerapps for a bunch of deployment pipeline situations where we need jobs to run to completion.

**Comment by safari137** [comment]
This would be very beneficial for the use cases we have for container apps as well.

**Comment by tmakowka-tc** [comment]
We are currently looking into utilizing Container Apps for our workloads. Since we need to run numerous long-running batch jobs and would like to scale those via KEDA Queues, we are very interested in having ScaledJobs support in CA. Otherwise we cannot utilize CA for our workloads in this case.

**Comment by henriksen** [comment]
Would be useful for our use cases as well. Have a lot of minor apps that should start every now and again, do their thing to completion and then scale down automatically. Based mostly on cron expressions and EventGrid triggers (HTTP).

**Comment by kendallroden** [comment]
we will be working on jobs and support for this will happen with support for jobs!

**Comment by ezYakaEagle442** [comment]
one of my customers ask for this feature as well

**Comment by Mike-Kolter** [comment]
Any ETA on this one?

**Comment by kendallroden** [comment]
We are making progress in design phase - will keep updated

**Comment by jagusztinl** [comment]
One of our customers ask for this feature as well!

Where is the official roadmap of ContainerAppService?

**Comment by BC89** [comment]
Need this feature too. Our use case is around processing lidar data in a container app which would require long-running jobs and even vertical scaling of resources for particular batch jobs.

**Comment by michal-chmel** [comment]
Adding my voice to the line as well. We would greatly appreciate this feature to support our pipeline deployments.

**Comment by dougclutter** [comment]
We're looking forward to this as well.  Our current use case is for Azure DevOps pipelines, but we're also considering it for other long running jobs.  Thanks!

**Comment by VOVELEE** [comment]
Need this as well

**Comment by caspeco-dan** [comment]
Any updates regarding this? Would be very useful in our use-case.

**Comment by caspeco-dan** [comment]
> Any updates regarding this? Would be very useful in our use-case.

Found the answer myself in #526 if someone else is wondering.

**Comment by larryclaman** [comment]
#please-close
https://techcommunity.microsoft.com/t5/apps-on-azure-blog/introducing-jobs-for-azure-container-apps/ba-p/3826677#:~:text=With%20this%20new%20feature%2C%20Container%20Apps%20now%20supports,can%20run%20for%20minutes%20or%20even%20hours.%20

**Comment by vinisoto** [comment]
Closing this issue as Container Apps Jobs is in Public Preview:

https://techcommunity.microsoft.com/t5/apps-on-azure-blog/introducing-jobs-for-azure-container-apps/ba-p/3826677#:~:text=With%20this%20new%20feature%2C%20Container%20Apps%20now%20supports,can%20run%20for%20minutes%20or%20even%20hours.%20
