### ISSUE TITLE
Feature Request: Control over scale down behavior

### ISSUE THREAD

**Issue by JoaoBrandao** [microsoft/azure-container-apps#240]
**Is your feature request related to a problem? Please describe**.  
As client, I would like to control the scale down/out of our Replicas in Container Apps in the same way that we have the "control" to set the scale up rule based on CPU, Memory, HTTP.

**Describe the solution you'd like**.    
The solution to this could be to make the scale down using a custom rule.

The configuration could be provided via:
- yaml file
- az cli
- azure endpoint
- via Azure Portal

**Describe alternatives you've considered**.   
Currently, there are no alternatives for controlling the scaling down. The process to scale down the number of replicas is done automatically by Container Apps based on load performance.

**Additional context**.  
The concept of scale up and scale down is already present in diverse Azure Services like Azure Spring Cloud. As a developer would be great to have the control to scale down the number of replicas(pods) that are running anytime based on my rules.
The rule could be applied in CPU and/or memory usage.

**Comment by tomkerkhove** [comment]
> As client, I would like to control the scale down/out of our Replicas in Container Apps in the same way that we have the "control" to set the scale up rule based on CPU, Memory, HTTP.

Can you elaborate on what amount of control you have for CPU, memory or HTTP compared to other scaling rules?

> **Additional context**. The concept of scale up and scale down is already present in diverse Azure Services like Azure Spring Cloud. As a developer would be great to have the control to scale down the number of replicas(pods) that are running anytime based on my rules. The rule could be applied in CPU and/or memory usage.

Is this what you are looking for https://github.com/kedacore/keda/issues/2614?

**Comment by tomkerkhove** [comment]
That's something KEDA can look at, but you're initial request indicates that this approach is already in place for CPU/Memory in Container Apps but I don't see it: https://docs.microsoft.com/en-us/azure/container-apps/scale-app#cpu

**Comment by tomkerkhove** [comment]
> As client, I would like to control the scale down/out of our Replicas in Container Apps in the same way that we have the "control" to set the scale up rule based on CPU, Memory, HTTP.

Ok so this refers to Azure Monitor Autoscale and not Azure Container Apps  so that clarifies my confusion, thanks you :)
