### ISSUE TITLE
Cannot update environment variables from a Container App

### ISSUE THREAD

**Issue by JoaoBrandao** [microsoft/azure-container-apps#241]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Changing _**only environment variables**_  from a Container that already has environment variables does not allow the developer to save the new environment variables.

### Steps to reproduct

**Pre-Requisites:**

1. Should have already a container App
2. The container app should have Environment variables of the type "Reference a Secret"

**Step-by-Step:**
1. Open Azure Container Apps Service
4. Click in a pre-existing Container Apps
5. Under the section **Application**, select the option **Containers**
6. Click on the Environment variables option in the middle
7. (VALIDATE) Should exist a few environment variables of type **reference a secret** in that container
8. Click to Edit and Deploy option
9. Click on the Container image. ( CPU must be 2 and Memory 4Gi)
10. (VALIDATE) The option Save should be disabled
11. In environment variables, change the source to manual entry
12. insert a new value

**Expected behavior** [What you expected to happen.]
The button "save" should be enabled after editing the environment variables.

**Actual behavior** [What actually happened.]
After the change, the button is not enabled

**Screenshots**         

**Before**
<img width="564" alt="Screenshot 2022-05-30 at 21 09 06" src="https://user-images.githubusercontent.com/13374459/171054385-f6c8e40d-31f3-41fb-bfc7-eaeb3de39fbd.png">

**After**
<img width="577" alt="Screenshot 2022-05-30 at 21 09 16" src="https://user-images.githubusercontent.com/13374459/171054383-3fb6735d-7e1b-40eb-81dd-27bb0fe34cea.png">

### Additional context
The problem occurs in the Portal

**Comment by kendallroden** [comment]
closing due to above and timing. please reopen if still relevant

**Comment by SiddharthSingi** [comment]
I am facing the same issue on containerapp job, where I cannot pass in the env variable successfully when I start the job. I am unable to pass any argument to the containerapp job. Can you please help, I dont see any similar option for the app job just yet so how do I deal with this?

**Comment by kevindiependaele-at-ap** [comment]
I face the same problem

**Comment by ilyevskii** [comment]
Same problem for me
