### ISSUE TITLE
[Feedback]: Migration path from App Service to Container Apps 

### ISSUE THREAD

**Issue by cosminstirbu** [microsoft/azure-container-apps#245]
Hello,

We currently have 3 APIs which are hosted in Azure using App Services (Windows).
Two of them sit behind an API Management instance and one of them is directly accessible from the Internet.

We are looking at moving towards Container Apps, however we found a few feature gaps that we'd like to highlight:

- Inbound traffic cannot be easily restricted only to specific IP addresses (e.g., APIM's public IP address) - this is tracked via https://github.com/microsoft/azure-container-apps/issues/243
- Swapping / zero-downtime deployment doesn't seem fully supported, or it requires additional effort from our side to warm up the instances - this is tracked via https://github.com/microsoft/azure-container-apps/issues/244
- No Key Vault integration. We use Key Vault integration mainly to achieve truly immutable "revisions", since we leverage the versioning of a Key Vault secret, this allows us to independently update a secret and control when the new version of the secret is being picked up. Key Vault integration is partially tracked via https://github.com/microsoft/azure-container-apps/issues/39
- No "out-of-the-box" file logging support. We use the [Storage Account application logs](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#enable-application-logging-windows) with [Microsoft.Extensions.Logging.AzureAppServices](https://www.nuget.org/packages/Microsoft.Extensions.Logging.AzureAppServices) for some of our larger logs (e.g., to capture request / response body) when we want to turn on additional logging to investigate an issue. Not a really big deal breaker, as most likely this could be solved via [storage mounts](https://docs.microsoft.com/en-us/azure/container-apps/storage-mounts?pivots=aca-cli), we could use some guidance for this though. Please note that we prefer file logging for large log entries due to size / cost limitations by other logging sinks such as Application Insights
- Terraform support - this is tracked via https://github.com/hashicorp/terraform-provider-azurerm/issues/14122

I know this is still early days, however we're hoping that maybe in a 6 months timeframe most of the items above will be addressed (either directly or with reasonable developer effort) and that we'll then be able to make the switch from an App Service to Container Apps.

Thank you,
Cosmin

**Comment by ilmax** [comment]
@cosminstirbu the last point (terraform support) is covered for now by the AzApi provider, more info [here](https://dev.to/maxx_don/create-azure-container-apps-with-terraform-5bk)

**Comment by kendallroden** [comment]
Thanks for this, will review with the team and take into account.

**Comment by vturecek** [comment]
@cosminstirbu for KeyVault, is there anything preventing you from using the KeyVault client to pull secrets at runtime, and using a managed identity to authenticate with KeyVault?

**Comment by cosminstirbu** [comment]
@vturecek - that is a reasonable alternative. I am a bit concerned about how that might impact the startup time of the application. Injecting (presumably cached) secrets from outside rather than reading them from a remote location at startup seems like it would be faster.

Maybe it's a non-issue though for most cases, I am happy for it to be de-prioritized over the other feature gaps.

**Comment by dariagrigoriu** [comment]
The Azure Container Apps service does not support Windows containers. Please refer to individual GitHub issues mentioned for progress of specific enhancements/features requested.
