### ISSUE TITLE
Volume mounting in a container app environment with a custom VNet and Azure Files with a service endpoint does not use the VNet private IP address

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#246]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When I volume mount in a container app environment with a custom VNet and Azure Files with a service endpoint, it looks like the public IP address is being used instead of the VNet private IP address.

Also, Azure Files with a service endpoint can be used in a container app environment that does not have a custom VNet.

### Steps to reproduct
1. Create an Azure File with a service endpoint (Blocked public access).
2. Deploy the container app to use Azure Files
3. Deploy an ACA with Azure Files mounted

**Expected behavior** [What you expected to happen.]
- container app enviromment  
→ not mounted
- container app enviromment with custom VNet (Internal)  
→ mounted (using VNet private IP address)
- container app enviromment with custom VNet (External)  
→ mounted (using VNet private IP address)

**Actual behavior** [What actually happened.]
- container app enviromment  
→ mounted (using Azure Files public IP address)
- container app enviromment with custom VNet (Internal)  
→ mounted (using Azure Files public IP address)
- container app enviromment with custom VNet (External)  
→ mounted (using Azure Files public IP address)

**Screenshots**
This is a screenshot showing the volume mount status of ACA deployed on the container app environment with Custom VNet (Internal).
![20220601-01_002](https://user-images.githubusercontent.com/15773157/171370659-031ea61b-2ac2-4e0f-8c55-518f63c10c30.png)

### Additional context
- Related issue  
https://github.com/microsoft/azure-container-apps/issues/59

**Comment by kendallroden** [comment]
Thanks for reporting. Out of curiosity is there a reason you chose service endpoint vs. private endpoint?

**Comment by YuKogasaka** [comment]
@kendallroden,
Although I understand that communication between Azure services does not go out on the Internet, because customer requirements that do not require external communication must be done via VNet (service/private endpoint).

If strictly restrict access, it is a private endpoint. However, because container app environments with custom VNets require a dedicated subnet, I chose a service endpoint that is easy to configure.

**Comment by njuCZ** [comment]
Hi @YuKogasaka, I had a test for it and the result is:
- container app enviromment
   could not mounted, revision shows provisioning (the pod is pending because failed to mount)
- container app enviromment with custom VNet
   mounted (using Azure Files public IP address)

this is my storage service endpoint settings
![image](https://user-images.githubusercontent.com/2786738/171604135-489126c6-0011-45d5-a8be-f11c2964a36b.png)

As for why it will use public IP, I think this is by designed. The service endpoint just means traffic goes through the tunnel. If you wants to know the detail reason, that will need to refer to the storage team and network team.
