### ISSUE TITLE
Feature Request: Make ACA available with smaller VNET sizes

### ISSUE THREAD

**Issue by mfatbmw** [microsoft/azure-container-apps#247]
**Is your feature request related to a problem? Please describe**.  
Currently the required VNET size is set at /23. (512 IPs)
We have a lot of applications (100+) that would benefit from a lean container app solution and see ACA as one of our possible solutions. Our VNETs are internal and thus contain internal IP ranges. Giving out /23 nets is not feasible and will exhaust our allotted IP space. 

**Describe the solution you'd like**.    
Make ACA available for smaller VNET sizes starting with /26.

**Describe alternatives you've considered**.   
Implement NAT gateway between Container App VNET/subnet and company VNET.
Not preferred as we need extra infrastructure and complexity.

**Additional context**.  
Instead of reducing the size of the VNET, it probably would make more sense to have an option to integrate the ILB with its external-facing IP-address in the internal VNET. This would allow us to have a very large cluster but would only consume one IP on the customer/internal VNET side.

**Comment by anrub** [comment]
I want to add, that the size requirement is not only /23 for the VNet, but for the **subnet** of container app only. 

Most of our projects also have delegated subnets for other services like postgres flex, mariadb or something like that. Now you need an even bigger vnet than /23. Then add another subnet for private endpoint and you have a big boy vnet.

Which makes it nearly unsable for small projects (e.g. 1 app) and connection to on-prem. (with the default [hub and spoke architecture](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke))

**Comment by Soufianux** [comment]
Hello,

is this feature request integrated in the roadmap ? a /23 ACA dedicated subnet is huge and IP address space overconsuming. many of my clients refuse to go for ACA until reducing the subnet space is considered. 

Thanks in advance,

**Comment by torosent** [comment]
This is supported with Workload profiles
