### ISSUE TITLE
Issue: Missing a error message on Log Stream

### ISSUE THREAD

**Issue by JoaoBrandao** [microsoft/azure-container-apps#248]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Trying to load Log Streams from a revision that is already running we are getting an error and an empty panel.

Pre-requisites:
- You should have 1 container revision running.

### Steps to reproduct

1.  Open a Container App instance
2.  Select the option of log stream.

A scenario where the problem can occur:
- When you have already 1 person looking into the Log streams and the developer tries to load the log streaming of the same revision.

**Expected behavior** [What you expected to happen.]
If an error occurs, a message should be presented to the user.

**Actual behavior** [What actually happened.]
Presenting an error panel without any information inside.

**Screenshots**         

<img width="1632" alt="Screenshot 2022-05-25 at 15 13 51" src="https://user-images.githubusercontent.com/13374459/171428768-70eb894b-f62f-43dd-bd09-6affe0cab93e.png">

<img width="1655" alt="Screenshot 2022-05-25 at 15 14 18" src="https://user-images.githubusercontent.com/13374459/171429216-0acc05d0-be79-4e7a-91b3-b85a7ab4974c.png">

### Additional context
Portal

**Comment by kendallroden** [comment]
Thanks for reporting, passed along to the portal team.

**Comment by sanchitmehta** [comment]
@JoaoBrandao Could you provide us your Container App Name, Resource Group, and Subscription either here, at acasupport@microsoft.com, or open a support case? We

**Comment by JoaoBrandao** [comment]
Hi Sanchit,
An email was sent with that information.

**Comment by BigMorty** [comment]
@sanchitmehta Any update on this issue?

**Comment by BigMorty** [comment]
@sekhemrekhutawysobekhotep, this looks like a different issue than this one. Please create a new issue so it can be investigated. Any additional details you can provide would be helpful.

**Comment by BigMorty** [comment]
@JoaoBrandao, I did not see a reply in email to the last thread. Can you resend please?

**Comment by JoaoBrandao** [comment]
Hi,
I already replied to our email thread.
@sanchitmehta Please schedule a meeting with me in one of your free slots to review this.

**Comment by agoncal** [comment]
@JoaoBrandao do you still have this issue?

**Comment by simonjj** [comment]
Closing this. Assuming this is no longer an issue.
