### ISSUE TITLE
Add Support for Azure Policy 

### ISSUE THREAD

**Issue by SatyKrish** [microsoft/azure-container-apps#25]
As an enterprise customer, having support for AKS like policy initiatives will help ensure security and compliance.

Namely,

- Deny containerapp creation with public endpoint 
- Allow containerapp creation using images  from allowed registries
- Ensure ContainerApp Environment is integrated with a specific LA workspace

**Comment by simonjj** [comment]
ACA now has support for Policy these scenarios should be covered. Closing now, please reopen if you find this is still an issue.
