### ISSUE TITLE
Unable add Revision label of traffic 0% in Azure Container Apps

### ISSUE THREAD

**Issue by thara0402** [microsoft/azure-container-apps#254]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I can’t add Revision label with Azure CLI in Azure Container Apps.
```shell-session
$ az containerapp revision label add -n dapr-frontend -g <rg name> --label staging --revision dapr-frontend--v2
Please specify a revision name with an associated traffic weight.
```
Revision traffic of "dapr-frontend--v2" is 0%.
But I can add Revision label to traffic 0% with Azure Portal.
https://docs.microsoft.com/en-us/azure/container-apps/revisions#revision-labels

Which specification is correct, CLI or Portal?

### Steps to reproduct
1. 2 container revision running.(100% / 0%)
2. execute Azure CLI.

**Comment by torosent** [comment]
@thara0402 , please verify that this is issue is resolved for you

**Comment by thara0402** [comment]
@torosent
I succeeded in verification using v0.3.6.
Thank you so much.

![revision-label](https://user-images.githubusercontent.com/6549976/173821511-51c3b28c-30cb-4e12-9623-74156287ec56.png)
