### ISSUE TITLE
Exist outbound type userDefinedRouting ?

### ISSUE THREAD

**Issue by jvaca92Code** [microsoft/azure-container-apps#255]
I wonder if would be possible to configure outbound type userDefinedRouting as the same option we can configure on AKS side ?
Or there will be default outbound type loadBalancer.

**Comment by chinadragon0515** [comment]
@jvaca92Code We do not expose option to customize the AKS. 
You can achieve this via these steps,
1. Join container apps into a vnet, and refer to guide in this link, https://docs.microsoft.com/en-us/azure/container-apps/vnet-custom-internal?tabs=bash&pivots=azure-cli
2. Create custom route for the vnet, and you can customize routes as you want.  and you can refer to this page about container app route requests https://docs.microsoft.com/en-us/azure/container-apps/firewall-integration#firewall-configuration

let us know if you have any more questions or comments. thanks

**Comment by graemefoster** [comment]
@chinadragon0515 do you have a working sample template for this? I tried to deploy container apps in a vnet that was connected to a secure vhub today (routes propagated to the container environment subnet from the vwan ,sending traffic via the firewall).

The container environment failed to initialise after an hour of waiting. I could see container app traffic hitting the firewall. 

When I added a UDR to the container environment subnet to bypass the firewall for internet traffic, the container environment successfully initialised. 

Is it possible that the SNAT the firewall would apply to container apps traffic (that would normally present via the load balancers public IP address) is busting the container environment?

**Comment by davidxw** [comment]
@chinadragon0515 do you have any further comments on this?  As per Graeme's comments above I can't get this to work either. Not being able to control egress is a real showstopper in the environments I work in.

**Comment by denniszielke** [comment]
Agree. This is a blocker for customers that do not allow public ip by policy. 
We would need ability to set outboundtype, force egress through a firewall and prevent ACA from creating public IPs for egress.

**Comment by chinadragon0515** [comment]
refer to https://github.com/microsoft/azure-container-apps/issues/227 which has newest update.

**Comment by chinadragon0515** [comment]
Refer to https://github.com/microsoft/azure-container-apps/issues/227 for newest update
