### ISSUE TITLE
Query regarding the container size and scaling beyond 10 instances

### ISSUE THREAD

**Issue by purijatin** [microsoft/azure-container-apps#257]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

Quoting from the [docs](https://docs.microsoft.com/en-us/azure/container-apps/containers#configuration):

> The total of the CPU requests in all of your containers must match one of the values in the vCPUs column.
> The total of the memory requests in all your containers must match the memory value in the memory column in the same row of the CPU column.

If I deploy a single container of size 2cores and 4 Gi ram. And given the limitation of maximum 10 instances. Does it mean:

1. At maximum my service can use 40Gi and 20 cores in total? And can't scale beyond?
2. If so, any reason to limit a container instance to 2core and 4Gi only?
3. We wish to use beyond 10 instances

Here is our scenario:

We have some long-running jobs, which we wish to isolate from each other (as much as possible, so that the failures of one don't affect the other). And wish to run each job separately (this can be done by setting the scale HTTP concurrency factor to `1`). So that every http call is preferably run on a separate node. 
From my understanding above, at a maximum, we can only run 10 concurrent HTTP calls.

How do we deal with this in ACA

### Steps to reproduct

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**

**Comment by BigMorty** [comment]
We have raised the max replica size from 10 to 30 - https://docs.microsoft.com/en-us/azure/container-apps/scale-app
We plan to have larger than 2vCPU and 4 Gi ram in the future.

Hope this helps, if so feel free to close this issue.

**Comment by purijatin** [comment]
Thanks for the update. Closed the issue.
