### ISSUE TITLE
dapr-component glitch in UX and inconsistency between docs & CLI

### ISSUE THREAD

**Issue by dabedin** [microsoft/azure-container-apps#258]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Managing to successfully create a dapr-component with missing properties breaks the portal UX

### Steps to reproduct
I managed to create a component via CLI with the following schema:
```
name: commonpubsub
componentType: pubsub.azure.servicebus
version: v1
metadata:
- name: connectionString
  secretRef: pubsub-servicebus-connectionstring
secrets:
- name: pubsub-servicebus-connectionstring
  value: Endpoint=sb://da...........
```
**Actual behavior** [What actually happened.]
If I retrieve the dapr-component via CLI `az containerapp env dapr-component show` I get
```
{
  "id": "/subscriptions/xyz/resourceGroups/dapracargdb/providers/Microsoft.App/managedEnvironments/xyz/daprComponents/commonpubsub3",
  "name": "commonpubsub2",
  "properties": {
    "componentType": "pubsub.azure.servicebus",
    "ignoreErrors": false,
    "metadata": [
      {
        "name": "connectionString",
        "secretRef": "pubsub-servicebus-connectionstring"
      }
    ],
    "secrets": [
      {
        "name": "pubsub-servicebus-connectionstring"
      }
    ],
    "version": "v1"
  },
  "resourceGroup": "dapracargdb",
  "systemData": {
    "createdAt": "2022-06-07T17:31:21.6881338",
    "createdBy": "xyz",
    "createdByType": "User",
    "lastModifiedAt": "2022-06-07T17:48:50.0800949Z",
    "lastModifiedBy": "xyz",
    "lastModifiedByType": "User"
  },
  "type": "Microsoft.App/managedEnvironments/daprComponents"
}
``` 
In the output above you notice there is no `scopes` section or `value` in metadata, as I did not add it to the input.
If I open the Dapr component from portal UX I get the following error:
![image](https://user-images.githubusercontent.com/11557301/172448502-7c5b81c3-2752-4c43-9666-45fad66e290b.png)

**Expected behavior** [What you expected to happen.]
Only if I create the dapr-component from UX, or CLI with the empty `scopes` and `value` in metadata, I get the UX to comply
``` 
{
  "id": "/subscriptions/xyz/resourceGroups/dapracargdb/providers/Microsoft.App/managedEnvironments/xyz/daprComponents/commonpubsub",
  "name": "commonpubsub",
  "properties": {
    "componentType": "pubsub.azure.servicebus",
    "ignoreErrors": false,
    "metadata": [
      {
        "name": "connectionstring",
        "secretRef": "pubsub-servicebus-connectionstring",
        "value": ""
      }
    ],
    "scopes": [],
    "secrets": [
      {
        "name": "pubsub-servicebus-connectionstring"
      }
    ],
    "version": "v1"
  },
  "resourceGroup": "dapracargdb",
  "systemData": {
    "createdAt": "2022-06-07T17:14:41.3484488",
    "createdBy": "xyz",
    "createdByType": "User",
    "lastModifiedAt": "2022-06-07T17:14:41.3484488",
    "lastModifiedBy": "xyz",
    "lastModifiedByType": "User"
  },
  "type": "Microsoft.App/managedEnvironments/daprComponents"
}
``` 
From the UX, I can see the dapr-component created via CLI
![image](https://user-images.githubusercontent.com/11557301/172453122-9888ed4a-8ef1-4f61-b5c1-69b4ce11c1f9.png)

**Screenshots**         
In addition to the issue above, following the schema at https://docs.microsoft.com/en-us/azure/container-apps/dapr-overview?tabs=yaml fails with _Invalid YAML provided._ error. 
![image](https://user-images.githubusercontent.com/11557301/172447637-f28d88dc-fb54-4c77-89ef-c70990b25bd4.png)
The schema that seems to work is at https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=powershell. 
![image](https://user-images.githubusercontent.com/11557301/172447723-767e47b3-81bf-4eb2-9204-c630b0434c93.png)

### Additional context
Using CLI with extension 0.3.4

**Comment by danbuche** [comment]
I also saw the YAML syntax issue for the servicebus sample - when adapting it to the below format for blobstorage, I got it to work - I had opened a separate bug for that already in the MicrosoftDocs repo.
