### ISSUE TITLE
internalOnly flag on az containerapps env create does not create internal container app envrionment

### ISSUE THREAD

**Issue by davidxw** [microsoft/azure-container-apps#260]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Using the CLI command "az containerapps env create" with the --internal-only flag is not creating an internal container apps environment.  See repro steps details

### Steps to reproduct
1. Create resource group, VNet with appropriately sized subnet, and log analytics workspace
2. Run az containerapps env create, e.g.
```
az containerapp env create -n aca-cli-test-1 -g aca_cli_test -l australiaeast \
--logs-workspace-id <id> \
--logs-workspace-key <key> \
--internal-only \
--infrastructure-subnet-resource-id  <id>
```

3. Create container app in the environment, e.g:
```
az containerapp create -n aca-cli-test-app -g aca_cli_test \
--environment aca-cli-test-1 \
--ingress internal \
--target-port 80
```

4. Get details of container app env, e.g.

```
az containerapp env show -n aca-cli-test-1 -g aca_cli_test
```

**Expected behavior** [What you expected to happen.]

Container app environment is set to internal only, and IP address is private, e.g:
```
 "defaultDomain": "wittymushroom-a9c29b91.australiaeast.azurecontainerapps.io",
    "provisioningState": "Succeeded",
    "staticIp": "172.23.2.248",
    "vnetConfiguration": {
      "dockerBridgeCidr": "10.1.0.1/16",
      "infrastructureSubnetId": "/subscriptions/8b20cf3a-4f12-44df-bc4a-f9a0fc9fb115/resourceGroups/aca_internal/providers/Microsoft.Network/virtualNetworks/aca_internal_vnet/subnets/aca_infra",
      "internal": true,
      "platformReservedCidr": "10.0.0.0/16",
      "platformReservedDnsIP": "10.0.0.2"
    }
```

**Actual behavior** [What actually happened.]

Container app environment created with internal=false, IP address is public:
```
  "location": "australiaeast",
  "name": "aca-cli-test-1",
  "properties": {
    "appLogsConfiguration": {
      "destination": "log-analytics",
      "logAnalyticsConfiguration": {
        "customerId": "5fb5e847-ac09-470c-85c9-01a11308f14c"
      }
    },
    "defaultDomain": "jollycliff-4757da1a.australiaeast.azurecontainerapps.io",
    "provisioningState": "Succeeded",
    "staticIp": "20.213.66.96",
    "vnetConfiguration": {
      "dockerBridgeCidr": "10.2.0.1/16",
      "infrastructureSubnetId": "/subscriptions/85ac5960-efc5-4749-971a-10dcca41340f/resourceGroups/aca_cli_test/providers/Microsoft.Network/virtualNetworks/aca_cli_test/subnets/aca_infra",
      "internal": false,
      "platformReservedCidr": "10.0.0.0/16",
      "platformReservedDnsIP": "10.0.0.2"
    }
```
We captured some calls to the REST API and it doesn't look like the payload matches the [API definition ](https://docs.microsoft.com/en-us/rest/api/containerapps/managed-environments/create-or-update#vnetconfiguration)(this to a different subscription/environment), e.g. "internal" is missing from VnetConfiguration, internalLoadBalancerEnabled no longer used.

```
PUT https://management.azure.com/subscriptions/8d2059f3-b805-41fa-ab84-e13d4dfec042/resourceGroups/gri-aue-dev-rsg-capp/providers/Microsoft.App/managedEnvironments/gri-aue-dev-rsg-capp-cli-2?api-version=2022-03-01 HTTP/1.1

{
    "location":"australiaeast",
    "tags":null,
    "properties":{
        "daprAIInstrumentationKey":null,
        "vnetConfiguration":{
            "infrastructureSubnetId":"//subscriptions/8d2059f3-b805-41fa-ab84-e13d4dfec042/resourceGroups/gri-aue-dev-rsg-shared/providers/Microsoft.Network/virtualNetworks/gri-aue-dev-vnt-default/subnets/container-infra",
            "runtimeSubnetId":null,
            "dockerBridgeCidr":null,
            "platformReservedCidr":null,
            "platformReservedDnsIP":null
        },
        "internalLoadBalancerEnabled":true,
        "appLogsConfiguration":{
            "destination":"log-analytics",
            "logAnalyticsConfiguration":{
                "customerId":"xxx",
                "sharedKey":"xxx"
            }
        }
    }
}
```

**Screenshots**         

### Additional context
* Issue does not occur in the portal (snippet in the "expected behavior" above is taken from an env created via portal).  
* Issue has been reproduced by colleague, also in Australia East
* Version of containerapp extension is 0.3.4

**Comment by LaylaLiu-gmail** [comment]
This should be a known issue in azure cli, which assigned the internal flag to an old, deprecated property internalLoadBalancerEnabled. @StrawnSC should have been working on this.

**Comment by DevSecNinja** [comment]
@davidxw It could be that I'm experiencing the same issue from the portal. Was your web site and app URL accessible? In my case, the URL wasn't resolve-able via the Azure DNS servers and the IP address wasn't pingable. (Could be that ICMP is not allowed). So I wasn't able to successfully deploy a container app connected with a VNET via the Azure Portal as well.

**Comment by dariagrigoriu** [comment]
The CLI issue should be addressed in the next CLI release.

**Comment by digitalkirkley** [comment]
> The CLI issue should be addressed in the next CLI release.

When is this release due with this fix please?

**Comment by peteneville** [comment]
> > The CLI issue should be addressed in the next CLI release.
> 
> When is this release due with this fix please?

Just come across this same problem in uksouth using the cli with either yaml or json.
Release date would be useful please.

**Comment by digitalkirkley** [comment]
> The CLI issue should be addressed in the next CLI release.

Will the fix be available this week please? (I noticed PR/code changes) We need to be able to deploy an environment that allows for an internal VNET configuration. Or is there a work around until release? I believe this doesn't work via the portal either.

**Comment by peteneville** [comment]
> > The CLI issue should be addressed in the next CLI release.
> 
> Will the fix be available this week please? (I noticed PR/code changes) We need to be able to deploy an environment that allows for an internal VNET configuration. Or is there a work around until release? I believe this doesn't work via the portal either.

For info - I have this working on internal only VNet with the app created via the portal.

**Comment by StrawnSC** [comment]
The fix for this is currently in review [here](https://github.com/Azure/azure-cli-extensions/pull/4960). The fix will be released shortly after that PR is merged.
I'm aiming to have this released as soon as possible this week

**Comment by StrawnSC** [comment]
@anthonychu we should be good to close this since the fix has been released
