### ISSUE TITLE
`username` and `passwordSecretRef` settings remain after executing the `az containerapp registry set --identity` command

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#261]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
In Azue CLI containerapp extension v0.3.6, I ran to change the authentication to ACR to a Managed ID using `az containerapp registry set --identity` command, but the `username` and `passwordSecretRef` settings are still remain.

### Steps to reproduct
1. The following command was executed for existing ACA (deploy from ACR, authentication method is username/password).    
```console
az containerapp registry set \
  -n '<ACA Name>' \
  -g '<Resouce Group Name>' \
  --server '<ACR Server Name>' \
  --identity 'system'
```

**Expected behavior** [What you expected to happen.]
I think the execution result should be like this.
```json
Updating existing registry.
[
  {
    "identity": "system",
    "server": "<ACR Server Name>",
  }
]
```

**Actual behavior** [What actually happened.]
Actually, the result is as follows.
Note : The result was the same for `--identity '<user-assigned managed ID'`
```json
Updating existing registry.
[
  {
    "identity": "system",
    "passwordSecretRef": "<Password (Secret)>",
    "server": "<ACR Server Name>",
    "username": "<User Name>"
  }
]
```

### Additional context
- az version resuilts
```json
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "containerapp": "0.3.6",
    "ssh": "1.1.1"
  }
}
```

**Comment by StrawnSC** [comment]
The fix for this will be [released](https://github.com/Azure/azure-cli-extensions/pull/4960) with the next version of the containerapp CLI extension

**Comment by StrawnSC** [comment]
@anthonychu the fix for this has been released as well
