### ISSUE TITLE
Creating Container App on VNet in brand new resource group with all defaults from Azure Portal fails

### ISSUE THREAD

**Issue by joshuadmatthews** [microsoft/azure-container-apps#263]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

In a brand new resource group, add a new Container App. Follow the prompts to create a new Container App Environment, and enable VNet. Follow the prompts to create a new VNet and SubNet. Use Azure defaults for all CIDR ranges, and default sample Container image. Internal or External endpoint doesn't matter they both fail the same way. 

I have discovered that it works in another subscription, so it appears to be "something" related to the one I am working in. Would be helpful to get a more detailed error message to help figure out what. 

Deployment fails with 

```
{
    "status": "Failed",
    "error": {
        "code": "OperationFailed",
        "message": "Fail to reprovision managed environment, error message Index (zero based) must be greater than or equal to zero and less than the size of the argument list."
    }
}
```

### Steps to reproduce 

Use Default Azure suggested names and settings for everything.

1. New Container App
2. New Container App Environment
3. New Log Analytics
4. Enable VNet
5. New VNet
6. New Subnet
7. Internal endpoint (Accept only internal traffic)
8. Deploy

**Expected behavior** [What you expected to happen.]

Deployment should succeed

**Actual behavior** [What actually happened.]

Container App Environment deployment fails with cryptic error

```
{
    "status": "Failed",
    "error": {
        "code": "OperationFailed",
        "message": "Fail to reprovision managed environment, error message Index (zero based) must be greater than or equal to zero and less than the size of the argument list."
    }
}
```

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

I get the same issue with my Bicep templates, and also in Azure Portal.

**Comment by joshuadmatthews** [comment]
It appears that this is due to policy that requires certain tags on resources, which are supposed to be automatically inherited from the resource group. I believe this is due to the resource group that it wants to create for Vnet integration. Is there any way to pass in tags for this resource group? I tried passing tags to the managed environment but they don't seem to get used when it creates the resource group.

**Comment by Seris370** [comment]
The fix has been deployed worldwide. Please verify.
