### ISSUE TITLE
Underscore Header Bad Request

### ISSUE THREAD

**Issue by sleekflowleochoi** [microsoft/azure-container-apps#264]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

When I request my container app with the header
Sfdc_stack_depth: 1
Then the container app responds "Bad Request" but I confirm the request is not reached my runtime.

When I request without Sfdc_stack_depth, then the request is reached my runtime.

https://stackoverflow.com/questions/47005217/enable-underscores-in-headers-on-azure-ingress

I can't customize the setting in azure container app.

### Steps to reproduct
1. POST request with Sfdc_stack_depth

**Comment by sleekflowleochoi** [comment]
$ curl https://sleekflow-apigw-app4811ecf6.delightfulwave-63e42554.eastasia.azurecontainerapps.io/v1/healthz && echo
{"crm-hub":{"content":"HEALTH"},"salesforce-integrator":{"content":"HEALTH"}}

$ curl --header "Sfdc_stack_depth: 123" https://sleekflow-apigw-app4811ecf6.delightfulwave-63e42554.eastasia.azurecontainerapps.io/v1/healthz && echo
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

**Comment by andlju** [comment]
I'm also running into this problem and it is currently blocking me from moving to Container Apps. If anyone can find a work-around that would be amazing!

**Comment by andlju** [comment]
Update: Something that worked for me was to use DAPR for the HTTP calls instead of the ingress endpoint. Unfortunately that doesn't solve the problem if you need to access the app outside of the container apps environment.

**Comment by leoiii12** [comment]
Finally, I placed a azure front door in front of the azure container apps. The front door acts a an apigw to change the underscore header to a normal header, or simply remove the underscroe header if you don't need to read it.

**Comment by uabarahona** [comment]
Same on my case, I do have this problem, I'm currently deploying a normal next.js app, this app though is doing some request using the following headers:

```
__rsc__: 1
__next_router_state_tree__": ["",{"children":["",{}]},null,null,true]
```

the request is not reaching the runtime, and these headers are needed since not include them produced different result than including them.

**Comment by onionhammer** [comment]
@ahmelsayed this one can probably be closed as well
