### ISSUE TITLE
Custom domain certificates are not signed with correct root CA certificate

### ISSUE THREAD

**Issue by vmantese** [microsoft/azure-container-apps#265]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Steps to reproduce
1. Purchase a valid wildcard domain certificate from Azure certificate manager (e.g. *.example.org)
2. Export certificate in pfx format to local machine.
3.  Apply certificate to custom domain via custom domain screen (for example container-app-api.example.org)
4. Check certificate status on one of the many certificate validity check sites (https://www.geocerts.com/ssl-checker,https://www.digicert.com/help/...)
5. Note that all portions of the certificate match expected except that the root CA certificate was not signed by trusted authority.

This is odd as the same certificate was used to create a custom domain in the 'static web app' application in azure (different subdomain, same domain name) and the certificate showed as trusted. It seems that the passed certificate is valid but that the certificate signing the chain (for ACA) is not being recognized as valid.

 

**Expected behavior** [What you expected to happen.]

Certificate shows as signed by trusted authority

**Actual behavior** [What actually happened.]

Certificate shows as not trusted by authority.

**Screenshots**         

The custom domain setup showing as if correctly installed.

![Screen Shot 2022-06-13 at 3 03 05 PM](https://user-images.githubusercontent.com/10504414/173436921-1bcb4658-c4b3-447f-946f-58ab55dfa882.png)

Digicert of ACA app showing incorrect.
![Screen Shot 2022-06-13 at 3 05 37 PM](https://user-images.githubusercontent.com/10504414/173436971-08667210-26a7-483e-b1ee-e72fde521a47.png)

Custom domain of Azure static web site using same certificate showing no issues.

![Screen Shot 2022-06-13 at 3 08 12 PM](https://user-images.githubusercontent.com/10504414/173437038-89aa61a1-bd9c-4f5d-b98a-921875c4a0de.png)

### Additional context
Portal

**Comment by torosent** [comment]
Hi. We have a fix for this issue and it will be deployed in the next couple of weeks to all regions.

**Comment by vmantese** [comment]
@torosent Is there any update on the timeline?

**Comment by robheymann** [comment]
Any updates, or workarounds? We cant continue to upgrade our application gateway because of a container app that is giving the above error since changing DNS.

**Comment by vinisoto** [comment]
@vmantese - Is the displayed certificate chain from Container Apps and Static Web Apps the same? There was an issue in Container Apps in which the certificate chain was not being fully uploaded when loading the certificate to the Container Apps Environment but a fix for that has already been deployed.

Maybe this issue is different.

**Comment by vmantese** [comment]
@vinisoto I believe these issues are one and the same, I'm still seeing the same issue even after manually removing the custom domain and re-adding it.

**Comment by vmantese** [comment]
@vinisoto @robheymann @torosent On a hunch I deleted the certificate from the container app environment and re-added it there as well. After doing this, rebinding the domain worked as expected and the certificate chain is complete. Thanks!
