### ISSUE TITLE
Provisioning a new AC environment with App fails with conflict with a custom VNET

### ISSUE THREAD

**Issue by mfatbmw** [microsoft/azure-container-apps#267]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Provisioning to a custom /23 Vnet fails into a new resource group West Europe.
Zone redundancy enabled.
Use Internal LoadBalancer.

`{
    "status": "Failed",
    "error": {
        "code": "OperationFailed",
        "message": "Managed environment failed to initialize"
    }
}`

CorrelationID: a0fdc899-9a96-4fc5-b5e2-927556331696

### Steps to reproduct
All actions via Portal.
1. Create VNET with a /23 Subnet
2. Create Container Apps environment with new Resource Group (Location West Europe), new Analytics Log Space, select internal ILB and Zone Redundancy.
3. Create an App with the default quickstartet app.

**Expected behavior** [What you expected to happen.]
ACA environment is provsioned correctly and app is deployed.

**Actual behavior** [What actually happened.]
Log Analytics workspace is created, but during provisioning of ACA the process fails with conflict. 
`{
    "status": "Failed",
    "error": {
        "code": "OperationFailed",
        "message": "Managed environment failed to initialize"
    }
}`

**Comment by vturecek** [comment]
@mfatbmw I don't see anything wrong with your environment configuration, can you try creating the environment one more time?

**Comment by mfatbmw** [comment]
Retried from Portal but still failing:

- non-redundant zone
- self provided vnet with a peering active

OperationID: /subscriptions/ba7468c4-1f0d-4ce7-b625-0ee82475bcfe/resourceGroups/rg-aca-ga/providers/Microsoft.Resources/deployments/Microsoft.App-ContainerApp-Portal-bd96d68d-afc4/operations/44C646D9E86FAB83
Correlation ID: 93123d04-fddf-404c-aabf-dcb69182ef37

`{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource provision operation did not complete within the allowed timeout period."
    }
}`

**Comment by gregpakes** [comment]
I am getting the same issue.  Trying to deploy with custom vnet and I just get the same timeout.

**Comment by kendallroden** [comment]
Closing due to timing. Please reopen and we will be more timely in getting back to you! apologies

**Comment by hoijnet** [comment]
I notice I had a VNet with 10.2.x.x/16 which was the same as the docker infrastructure CIDR of 10.2.x.x/16 used, which was assigned as the private VNet for the service. Not sure if this is what caused it for me, but it takes forever to delete the Container Apps and I seem to have the same issue. Unsure if it helps you uncover what causes it.

**Comment by lewis-b-xlab** [comment]
> Closing due to timing. Please reopen and we will be more timely in getting back to you! apologies

@mfatbmw would be great if you are able to reopen this? Having the exact same issue having tried to follow all docs around custom subnets. No error reports or anything just stuck in `Waiting` provisioned state - assuming it must be subnet clashes but so hard to diagnose!

**Comment by tdkeeley** [comment]
@lewis-b-xlab @mfatbmw we are too. saw this for the first time on 12/1.

**Comment by ceramey1997** [comment]
I am running into this issue as well. I am trying to deploy a container environment with a custom vnet that does not have any NSG rules and the deployment is timing out without a clear error message. @lewis-b-xlab @mfatbmw

**Comment by ivanignatiev** [comment]
Hello,

Having the same issue in Swiss North 

No UDR, no NSG

Command with AZ CLI completes successfully:
 
```
az containerapp env create \
  --subscription "0000-0000-0000-0000" \
  -n aca-01 \
  -g rg-01 \
  --logs-destination none \
  --location "switzerlandnorth" \
  --infrastructure-subnet-resource-id $SUBNETID \
  --internal-only true \
  --debug 
``` 

Provisioning State is in Waiting for long hours and after Azure Container Service removes RG MC_ and put provisioning state to Failed without any detailed error.
