### ISSUE TITLE
Creating container app from portal fails silently if ACR does not have admin password enabled

### ISSUE THREAD

**Issue by piizei** [microsoft/azure-container-apps#268]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When creating container app from the portal and user selects a container registry that does not have admin password enabled there is no error, but the selection of imagesjust says 'no images found'. 

Looking at the network traffic from browser there is error: 
Cannot perform credential operations for /subscriptions/.../ as admin user is disabled. Kindly enable admin user as per docs

### Steps to reproduct
1. Create acr without admin password enabled
2. Try to create container apps from that ACR

**Expected behavior** [What you expected to happen.]

It should give clear error (or just work).

**Actual behavior** [What actually happened.]

You cannot create a container app and dont know why.

**Comment by simonjj** [comment]
We have a error message for this now. Closing.
