### ISSUE TITLE
Feature Request: Custom Domains for Private DNS Servers

### ISSUE THREAD

**Issue by alicejgibbons** [microsoft/azure-container-apps#269]
**Is your feature request related to a problem? Please describe**.  
Today, DNS servers need to be accessible outside the Container Apps VNet in order to validate a custom DNS CNAME or A Record on a container app. This is a limitation as many customers use their own internal DNS severs and this validation will fail for them even if they are using an internal-only Container Apps Env.

**Describe the solution you'd like**.    
For internal Container Apps Environments, the DNS name resolution should follow the DNS on the containing VNet and custom DNS validation in the portal should work for private DNS servers. 

CC: @vinisoto

**Comment by cannehag** [comment]
Also curious on a solution for this. It makes no sense to use a public DNS on internal environments. Just let me change the custom domain and use my own private zone

**Comment by mirroredcube** [comment]
Do we have any update on this? How do we manage private custom domains within corporate network boundary?

**Comment by anrub** [comment]
I galdly found today, that it is working right now! I am able to set a private DNS name, without public-DNS validation. Just the keyvault integration for TLS Certs is missing, then it works like a charm for private DNS names.

**Comment by tamland** [comment]
Indeed, public DNS validation seems to be removed now. Not sure if this is intentional. Combined with `allowInsecure` you can bind any hostname and use private DNS without certs. You still have to upload a cert though, but it can be self-signed as it is not used.

**Comment by ivanthelad** [comment]
@dariagrigoriu  is Private DNS domains without public DNS resolution planned for ACA?

**Comment by simonjj** [comment]
Closing this, there's been a fair number of changes in this area more recently. Private DNS was always an option as far as I know (simply via CNAME record). Validation is now more relevant because we offer managed certificates now. If there's something that's still missing here, please reopen a new ticket to hone in on the issue which still exists.
