### ISSUE TITLE
I suggest simplifying the viewing of logs

### ISSUE THREAD

**Issue by ramonduraes** [microsoft/azure-container-apps#27]
Visualization by 'Log Analytics' is very complex.

1)  We need a simple screen that shows the real-time log stream

2)  Creating a simple command to view the log
=>  az containerapp logs ...
kubectl logs -l app=myapp
kubectl logs -f deployment/myapp

3)  Evaluate compatibility with other tools like 'stern'. We need to view the continuous log.
https://github.com/stern/stern

**Comment by guythetechie** [comment]
I would add surfacing the KEDA and DAPR logs to this as well, please. Should make troubleshooting a lot easier.

**Comment by SebastianSchuetze** [comment]
agree with @guythetechie

**Comment by mikeball** [comment]
Totally agree with this. While I created what was it a log analytics workspace... I can't even find the logs or know where to search them or figure out how to access even the most basic of log information.

**Comment by ramonduraes** [comment]
It is essential to be able to view the logs. 
simplify please.
![WhatsApp Image 2022-02-26 at 15 54 42](https://user-images.githubusercontent.com/2014324/155855905-094880e5-35eb-4d62-ab03-ea6333ba615f.jpeg)

**Comment by BigMorty** [comment]
I created https://github.com/microsoft/azure-container-apps/issues/196 to track the ask to view KEDA and Dapr logs.

**Comment by kendallroden** [comment]
Log streaming is available and Mike's issue linked above will track ongoing visibility improvements for dapr and keda
