### ISSUE TITLE
How do I get client IP address 

### ISSUE THREAD

**Issue by iAmBipinPaul** [microsoft/azure-container-apps#272]
When running app it returns private IP address instead of client IP address.

code 

```csharp

 IPAddress ipAddress = _httpContextAccessor.HttpContext.Connection.RemoteIpAddress

```

this above code return IP address like this 

```
::ffff:10.250.0.221
```

here is code 

https://github.com/iAmBipinPaul/UrlShortener/blob/864dfa8158ab03cc5ee513cc7f841b687f52f491/src/API/UrlShortener.Server/EndPoints/ShortUrlEndPoints.cs#L89

**Comment by torosent** [comment]
Hi. You can get the outbound IPs of your environments with the CLI, portal or the SDK. They are static IPs.

**Comment by anthonychu** [comment]
In Azure Container Apps, your app runs behind an ingress (proxy). The client's IP and some other properties (like protocol) from the original request are passed to your app in `x-forwarded-*` headers.

For ASP.NET Core, see this [documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0) for more details. Here's an example ASP.NET Core app that was configured to use these headers in Container Apps:

```csharp
using Microsoft.AspNetCore.HttpOverrides;

var builder = WebApplication.CreateBuilder(args);
builder.Services.Configure<ForwardedHeadersOptions> (options => 
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

var app = builder.Build();

app.UseForwardedHeaders();

app.MapGet("/", ctx => 
{
    return ctx.Response.WriteAsync($"Remote IP: {ctx.Connection.RemoteIpAddress?.ToString()}");
});

app.Run();
```

**Comment by torosent** [comment]
+1 to Anthony's comment. I misread the original issue :)

**Comment by iAmBipinPaul** [comment]
I tried like this
```csharp 
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor |
                       ForwardedHeaders.XForwardedProto
});
```
 and I was not able to get this working , it's may be due to missing `KnownNetworks.Clear()` and `KnownProxies.Clear()`

let me try as you suggested , I will give update here.

Thank you !

**Comment by iAmBipinPaul** [comment]
It's works , Thank you !

**Comment by FahaoTang** [comment]
Thanks for providing the solution. I've also summarized this into my article https://kontext.tech/article/1291/retrieve-client-ip-address-of-azure-container-apps

**Comment by nssidhu** [comment]
Just using the following code form @tang2087 works. Looks like there is no need or changes in program.cs file.
Not sure, why we even we need to make changes to program.cs
if(!HttpContext.Request.Headers.TryGetValue("X-Forwarded-For", out var ipAddress))                
{                 
    ipAddress = HttpContext.Connection.RemoteIpAddress?.ToString();                
}
