### ISSUE TITLE
Unable to update environment variables during Bicep template deployment

### ISSUE THREAD

**Issue by willvelida** [microsoft/azure-container-apps#273]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

When updating environment variables within my Bicep template for a container app, the added environment variables are not updated within the container's environment variables list in the portal. For example:

My environment variables defined in my bicep template:

```bicep
env: [
            {
              name: 'ASPNETCORE_ENVIRONMENT'
              value: 'Development'
            }
            {
              name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
              value: appInsights.properties.InstrumentationKey
            }
            {
              name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
              value: appInsights.properties.ConnectionString
            }
            {
              name: 'servicebusconnectionstring'
              secretRef: 'servicebusconnectionstring'
            }
            {
              name: 'cosmosdbconnectionstring'
              secretRef: 'cosmosdbconnectionstring'
            }
          ]
```

My listed environment variables in the portal:

![image](https://user-images.githubusercontent.com/8111944/174502343-c2baad30-20ce-49c2-8f74-046a09a8ce6d.png)

Doing a quick scan of existing issues, I'm unsure whether this is a portal bug issue similar to #241 or whether the API fails to update the Container App.

### Steps to reproduce

1. Use the following [Bicep template](https://github.com/willvelida/order-scaler-containerapps/blob/main/deploy/main.bicep) as a starter template.
2. Deploy the bicep template to your subscription using the following AZ CLI command:

```bash
az deployment group create --resource-group <name-of-your-rg> --template-file main.bicep
```

3. Navigate to portal to verify the template has been successfully deployed.
4. Add the following environment variables to the ```orderweb``` Container App resource in the Bicep template:

```bicep
{
              name: 'servicebusconnectionstring'
              secretRef: 'servicebusconnectionstring'
            }
            {
              name: 'cosmosdbconnectionstring'
              secretRef: 'cosmosdbconnectionstring'
            }
}
```

5. Deploy the Bicep template again using the same CLI command.
6. Navigate to the Container App in the portal and observe that the environment variables have not been updated.

**Expected behavior** [What you expected to happen.]

Expected additional environment variables defined in the Bicep template to be listed within the container's environment variable list in the portal.

**Actual behavior** [What actually happened.]

New environment variables were not listed in portal.

### Additional context

I was attempting to deploy my updated Bicep template locally using the AZ CLI.

**Comment by anthonychu** [comment]
@willvelida  When you update a container app and change something in the `template` section, a new revision is generated. Can you check that a second revision was created and what its environment variables look like (`az containerapp revision list ...`)? Do the variables appear there but not when viewing the revision in the container app?

**Comment by willvelida** [comment]
@anthonychu I checked the second revision and the added environment variable was there. Was a little confused by the portal not defaulting to the latest revision in the drop down under containers. Thanks for the help, I'll close the issue now.
