### ISSUE TITLE
Regions availability

### ISSUE THREAD

**Issue by eaboshosha** [microsoft/azure-container-apps#274]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x] documentation issue or request

### Issue description
I can't find the exact list of regions available , when looked on the product list it says south central is available (screenshot below ) but its not part of the options on portal and on the pricing list it says north , south US are both options but again not available on portal   

**Screenshots**         
![image](https://user-images.githubusercontent.com/93554587/174679168-cb632e36-e454-48ec-993c-7fb48939851d.png)

**Comment by torosent** [comment]
Hi. We are aware there is an issue with this specific doc. We are working to resolve it.

**Comment by coolhome** [comment]
I also submitted a support ticket back in June for this - and now today South and North Central US shows up. Azure Status Page shows N/A for NC/SC. 

Is it officially supported yet?

**Comment by jcjiang** [comment]
Hi! These sources of region information can be out of date at times. The most recent list of supported regions can be found by running the following command:

`az provider show --namespace Microsoft.App --query "resourceTypes[?resourceType=='managedEnvironments'].locations"`
