### ISSUE TITLE
Feature Request: Communication between Container Apps when Ingress is disabled

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#276]
**Is your feature request related to a problem? Please describe**.  
Communication between Container Apps does not work with Ingress disabled.

**Describe the solution you'd like**.    
I think that Container Apps host name or IP address and name resolution will be required when communicating, but I think that it will change frequently due to the nature of the container.
Even if it is changed, we request a mechanism that can dynamically acquire the Container Apps  host name or IP address and resolve the name.

**Describe alternatives you've considered**.   
By enabling Ingress, an endpoint will be given, so use it.
(However, I would like to disable Ingress for Container Apps that are on the back end side.)

**Comment by ahmelsayed** [comment]
That's what `external: false` is for in ingress. If you want apps to communicate to each other, they need to either define that, or piggyback on dapr's app to app communication pattern. Without declaring that, scaling, routing, and other traffic features won't work.

**Comment by YuKogasaka** [comment]
@ahmelsayed, I want you to tell me a little more detail. Does "they need to eaither define that" mean that use gRPC and define it in container app code?

**Comment by markharrison** [comment]
@YuKogasaka  

>> Communication between Container Apps does not work with Ingress disabled.

It does work with Ingress disabled.
I show it here https://markharrison.io/lab-azure-container-apps/deploy-apiapp

**Comment by YuKogasaka** [comment]
Ingress seems to be not disabled (ingress internal; Limited to Container Apps Environment) in the content of the link.
I just want to see how and samples can communicate between Container Apps when the ingress state is "Disabled".

![20220624-001](https://user-images.githubusercontent.com/15773157/175348295-b67d3196-4ece-4594-b57b-99c5693862e7.png)

**Comment by YuKogasaka** [comment]
I hope to implement a web system that runs solely on microservices with Container Apps instead of Kubernetes.
// I don't want to manage Kubernetes!

I think it is possible by using "ingress internal", but it has only 443 access ports, which makes it impossible to forward multiple ports.

**Comment by ahmelsayed** [comment]
By define that, I meant define `ingress` property.

> I think it is possible by using "ingress internal", but it has only 443 access ports, which makes it impossible to forward multiple ports.

Yes, apps can only expose 1 port. Without that most managed traffic features I mentioned (autoscaling, activation, traffic splitting, auth, etc) won't work.

**Comment by iamdanthedev** [comment]
Hi guys

Is something wrong or am I missing something? The documentation states that containers running in the same container env can communicate with each other inside the container env vnet. Ingress configuration seems to be irrelevant for internal communication, isn't it?

I am running two redis containers for testing purposes. They can see each other perfectly by an IP address

<img width="684" alt="image" src="https://user-images.githubusercontent.com/24467138/179283520-c47f4808-e4f6-48ca-a7c1-511349881426.png">

But after spending multiple hours trying to find corresponding host names of the running containers I have found nothing that works.  The `*.internal*` FDQN cannot be resolved, although it supposedly should. I have tried all possible combinations and it doesn't work.

**Comment by iamdanthedev** [comment]
Agree with @jelledruyts 

I managed to solve my problem by creating an instance of Azure Cache for Redis and connecting it to the vnet via a private endpoint, but this feels like a workaround

**Comment by kendallroden** [comment]
a) we are still working on TCP support 
b) ingress is required for two container apps to communicate. If you want it to communicate, you need to enable internal ingress and communicate to the app using the internal fqdn

**Comment by bengimblett** [comment]
@kendallroden

This DOES work through DAPR though right? If i deploy service-a and service-b and turn OFF ingress for service-b then service-a can still reach it through the dapr sidecars and service invocation (we tried it, it works) RE the following comment strongly alluding to that https://github.com/microsoft/azure-container-apps/issues/276#issuecomment-1163436654

**Comment by ahmelsayed** [comment]
> @kendallroden
> 
> This DOES work through DAPR though right? If i deploy service-a and service-b and turn OFF ingress for service-b then service-a can still reach it through the dapr sidecars and service invocation (we tried it, it works) RE the following comment strongly alluding to that [#276 (comment)](https://github.com/microsoft/azure-container-apps/issues/276#issuecomment-1163436654)

Yes, as long as you have dapr enabled on both, you don't need to enable ingress. 
If you have app `A` and app `B`, both have dapr enabled without ingress defined, you can call `B` from `A` using 
```bash
curl http://localhost:$DAPR_HTTP_PORT/v1.0/invoke/B/method/{pathOnAppB}
# or
curl -H 'dapr-app-id: B' http://localhost:$DAPR_HTTP_PORT/{pathOnAppB}
```

if you have internal ingress enabled on `B`, you can call `B` from `A` using
```bash
curl https://b.internal.$CONTAINER_APP_ENV_DNS_SUFFIX/{pathOnAppB}
```

if you have both dapr and ingress enabled you can use either. 

Note that dapr api proxy may not work for all HTTP scenarios (streaming, polling, h2 server push, etc)

**Comment by andyhoyle** [comment]
We're trying to achieve this and it seems that right now TCP is not supported, so no combination of Ingress settings will work for us.

```mermaid
flowchart TB
  subgraph Container App Environment
    direction TB
    subgraph ContainerApp1
        API
    end
    subgraph ContainerApp2
        TCPServiceReplica1
        TCPServiceReplica2
    end
    subgraph ContainerApp3
        TCPService2
    end
  end
  SPA --> |Http Ingress| API
  API --> |Tcp| TCPServiceReplica1
  API --> |Tcp| TCPServiceReplica2
  TCPServiceReplica1 --> |Tcp| TCPService2
  TCPServiceReplica2 --> |Tcp| TCPService2
```

**Comment by nisargaviasole** [comment]
I'm working with a streaming response — can Dapr help in this case? I tried connecting to the MCP server, but it's not connecting to my container through Dapr.
