### ISSUE TITLE
 DAPR Components - routing 0.0.0.0/0 UDR to Azure Firewall - saving component fails with internal server error. Blocked by firewall "HTTPS request from 10.0.0.4:51038. Action: Deny. Reason: SNI TLS extension was missing."

### ISSUE THREAD

**Issue by joshuadmatthews** [microsoft/azure-container-apps#277]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

With a VNet integrated container apps environment, and a 0.0.0.0/0 UDR, traffic from the control plane subnet when adding a DAPR PubSub (or any other type) component to the private endpoint FQDN is blocked by the firewall with

`HTTPS request from 10.0.0.4:51038. Action: Deny. Reason: SNI TLS extension was missing.`

### Steps to reproduct
1. Setup Vnet Integrated Container App Environment
2. Add a route table to the control plane subnet with a UDR for 0.0.0.0/0 -> Azure Firewall Private IP (on a separate peered VNet)
3. Setup an Azure Service Bus (premium) and setup a Private Endpoint for it.
4. Setup a Private DNS Zone so that the standard Azure Service Bus connection string will route to the Private Endpoint NIC
5. Attempt to add a DAPR PubSub component configured with a connection string to Azure Service Bus

**Expected behavior** [What you expected to happen.]

Should succeed.

**Actual behavior** [What actually happened.]

Fails with Internal Server Error. Upon inspecting firewall logs, can see it was denied due to a missing SNI TLS extension.

### Additional context
Portal, same thing happens if attempted through ARM deployment.

**Comment by dariagrigoriu** [comment]
UDR is currently not supported for outgoing connections.

**Comment by joshuadmatthews** [comment]
@dariagrigoriu That seems to me to be at odds with the documentation on outbound firewall configuration found here 

https://docs.microsoft.com/en-us/azure/container-apps/firewall-integration#firewall-configuration

As it talks about firewall outbound rules, how else can I direct the outbound traffic to a firewall with a UDR?

**Comment by chinadragon0515** [comment]
@joshuadmatthews 
For now, using custom user-defined routes (UDRs) or ExpressRoutes, other than with UDRs of selected destinations that you own, are not yet supported for Container App Environments with VNETs.

**Comment by joshuadmatthews** [comment]
@chinadragon0515 is there a way to direct the outbound traffic to a firewall without a UDR?

**Comment by denniszielke** [comment]
Yes you can force traffic to a firewall by BGB configuration.

**Comment by kendallroden** [comment]
This is related to support for UDR which is tracked in #318
