### ISSUE TITLE
Azure REST PATCH request fails for managed environments

### ISSUE THREAD

**Issue by mvromer** [microsoft/azure-container-apps#278]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

This is actually a bit of a two-part issue.

I originally deployed a managed environment via a Bicep template with the wrong Log Analytics workspace specified. I tried redeploying my template with the correct workspace config, but I noticed that the `customerId` property on the managed environment never updated (it still refers to the old workspace).

I decided to try to update the managed environment by using the `az rest` CLI to run the [Update operation](https://docs.microsoft.com/en-us/rest/api/containerapps/managed-environments/update) on my managed environment resource. However, doing that returns a 405 method not allowed error, suggesting that the PATCH operation that is documented at the above link isn't actually supported.

### Steps to reproduce
1. Deploy an ACA managed environment via Bicep template configured to use Log Analytics workspace X
2. Update template to reference Log Analytics workspace Y and redeploy Bicep template.
3. Either use Export Template functionality in Azure Portal for ACA environment or use `az containerapp env show` to confirm that the `customerId` of the Log Analytics workspace still refers to the first workspace.
4. Try to run `az rest --method patch --uri '<URI of managed environment>?api-versoin=2022-03-01' @body.json`, where `body.json` contains the request body that will patch the `properties.appLogsConfiguration.logAnalyticsConfiguration` property on the managed environment.

**Expected behavior** [What you expected to happen.]

The ACA environment is reconfigured to use the new Log Analytics workspace and the PATCH operation to succeed.

**Actual behavior** [What actually happened.]

The ACA environment continues to reference the original Log Analytics workspace, and the PATCH operation fails with a 405.

**Comment by vturecek** [comment]
@mvromer Currently we don't support changing a managed environment once it's been created. The PATCH operation only supports updating the `tags` property for a managed environment. 

I see the auto-generated API docs don't reflect this accurately. We'll get that fixed until managed environment updates are fully supported. Thanks for reporting this.

**Comment by howang-ms** [comment]
The PATCH to managed enviorment should be supported. now.
