### ISSUE TITLE
Feature Request: Plans to support client authentication?

### ISSUE THREAD

**Issue by mvromer** [microsoft/azure-container-apps#279]
**Is your feature request related to a problem? Please describe**. 

I'm currently setting up an ACA environment where a small number of teams can deploy their container apps independently. I would like to use a non-premium SKU of Azure API Management to expose a client-friendly API to those container apps that enable ingress, and I would like to ensure that clients can only connect to those services by going through the APIM gateway.

**Describe the solution you'd like**. 

It would be nice if I could configure ingress on my ACA environment so that it authenticates client connections via client certificates/mTLS. That way I could configure APIM to present a client certificate to my ACA environment backend, and my ACA environment would only allow connections from those clients that presented one of the allowed certificates.

**Describe alternatives you've considered**.   

I first thought about seeing if I could setup IP restrictions on my ACA environment so that it would only allow connections from my APIM backend. But it seems like ACA doesn't allow setting up IP restrictions in this way at this time. Also, I think this would preclude me from using the consumption tier of APIM since your APIM service then doesn't have dedicated IPs you can use for setting IP restrictions.

That's when I figured something akin to mTLS would be a good alternative. It was similar to how I secured communication and access from APIM to a Service Fabric cluster I was building last year for hosting containers. In lieu of ACA directly supporting client authentication on ingress, I _think_ I can achieve this by deploying an Azure App Gateway that does the client authentication. App Gateway can then forward authenticated requests to my ACA apps assuming I deployed the environment to my own VNET and used internal ingress on exposed apps. However, this is obviously more things for me to manage, and being able to manage less Azure infrastructure and reduce the cost of running container workloads was one of the appeals of ACA for me.

Would this (or something like it) be something that would make its way onto the ACA roadmap at some point?

**Comment by quality-leftovers** [comment]
It would be really great, if we could get the x-forwarded-client-cert header forwarded to the app. Could that be in the near future?

**Comment by kzhen** [comment]
+1

As mentioned above by @quality-leftovers if the x-forwarded-client-cert header was sent to Container Apps this would allow us to run APIs that implement mTLS authentication.

**Comment by onionhammer** [comment]
Definitely need more guidance / documentation on how to protect ACA as a backend.. really Azure has a TON of well documented solutions for creating gateways (APIGW, Frontdoor, APIM, etc), but there isn't a ton of documentation on how to secure backends and restrict them to ONLY those gateways (that AREN'T premium & cost $1500/month).

Googling this comes up pretty dry.

**Comment by Erikvdv** [comment]
@ahmelsayed I have made this update and I do see my requests blocked when I set the mode to "require" when I don't include the client cert. However, when I do use the client cert I don't see a request header present returning the certificate info

**Comment by zhenqxuMSFT** [comment]
@Erikvdv I just tested with a self signed cert with no chain and it works. Could you send an email to acasupport@microsoft.com with your app name, environment name, as well as how you make calls to your app so that we can take a look? Note, we may make some test calls to your app fqdn during investigation.

**Comment by Erikvdv** [comment]
@zhenqxuMSFT I just did another check and it is working for me now. Don't know if something has changed on your end. But when I generate a certificate like this, it is passed through now:
FILENAME="acatestcert"
openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout $FILENAME.key -out $FILENAME.crt

**Comment by zhenqxuMSFT** [comment]
@Erikvdv We do not have changes on our side but it's good to know it works for you now. If you see same issue again, kindly let us know :-) 

For bicep thing, I am not 100% sure but you may try it out now. The 2022-10-01 api version is already available on ARM.

**Comment by ahmelsayed** [comment]
2022-10-01 api should be released and the `clientCertificateMode` is documented here https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-10-01/containerapps?pivots=deployment-language-bicep#ingress

**Comment by andrekiba** [comment]
It would be nice to have a better documentation about this. Tried with a self signed certificate, it works from a caller in .net core/net 6.0 but always fails in .net full framework (4.5 or 4.8)…seems that during the tls handshake the certificate is not sent at all…so then nothing is present in the x-forwarded-client-cert that is missing. Any idea?

**Comment by ahmelsayed** [comment]
If I remember correctly, you might need to store the certificate in a Windows Certificate Store to use it with .NET Framework 4.5+ HttpClients.

**Comment by andrekiba** [comment]
@ahmelsayed the certificate is inside the store, I read it from the store.
If I deploy the same containerized .net 6 api (the one that is now on ACA) using a linux azure app service...it works also from .net full framework. In that case the header where I can find the certificate information is the standard one, X-ARR-ClientCert.
The deployed docker container image is exactly the same for both, ACA and web api on app service...
so I think something different (Envoy vs Gateway in front of app service?) happens during the tls handshake before reaching the api code

**Comment by andrekiba** [comment]
@ahmelsayed could you please do a test with a self signed certificate and .net framework 4.5 or 4.8?

**Comment by andrekiba** [comment]
@ahmelsayed  with the trace enabled on caller one thing that I can notice during the tls handshake is this

ACA:
System.Net Information: 0 : [13544] SecureChannel#41622463 - We have user-provided certificates. The server has specified 127 issuer(s). Looking for certificates that match any of the issuers.
System.Net Information: 0 : [13544] SecureChannel#41622463 - Left with 0 client certificates to choose from.

App Service:
System.Net Information: 0 : [34872] SecureChannel#41622463 - We have user-provided certificates. The server has not specified any issuers, so try all the certificates.
System.Net Information: 0 : [34872] SecureChannel#41622463 - Left with 1 client certificates to choose from.
System.Net Information: 0 : [34872] SecureChannel#41622463 - Selected certificate: [Version] V3

During the SERVER HELLO step of the handshake seems that the app service is more permissive, it doesn't specify any issuer allowing the caller to provide it's own self signed certificate (and then is the api code in charge to control the info and eventually trust the certificate or not).
On the other hand ACA specifies a list of possible issuers (where do those 127 default ones I see come from?) and this automatically deletes the self signed certificate by not finding any trusted issuers...this leads to an anonymous call --> no x-forwarded-client-cert --> 403 forbidden

**Comment by ahmelsayed** [comment]
I see thanks for the schannel trace logs. Yes, it seems we're advertising a list of acceptable CAs, those  127 issuer(s). You can see them with 

```bash
$ openssl s_client -connect {appName}.{env}.{region}.azurecontainerapps.io:443
```

should be the default mariner linux `/etc/ssl/certs/ca-certificates.crt` bundle.


It'll still pass whatever cert the client actually sends to the app, which seems to be how curl, go and dotnet core, etc do it. But .net 4.8 + schannel seem to require it to match or be empty. The list is meant to just help the client (like a browser) give feedback to the user about which certs might be acceptable, but since we always pass whatever cert to the app, it doesn't make sense to advertise any particular list there.

**Comment by andrekiba** [comment]
thank you @ahmelsayed, yes please we really need to call the api also from .net full framework.
Do you want me to open another issue to track this?
In the meantime if you can think of a workaround...when will be the next update of the proxy?

**Comment by ahmelsayed** [comment]
Sure, feel free to open another issue on this repo linking to this one. And I'll update it once the deployment has rolled out everywhere.

I'm not really sure about a workaround. All the [documented SCHANNEL registry settings](https://learn.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#sendtrustedissuerlist) I can see only refer to a server side fix. Someone from [dotnet](https://github.com/dotnet/runtime/issues) might know more, but we can have an update start rolling out by end of this week.

**Comment by andrekiba** [comment]
@ahmelsayed do we have an update?

**Comment by torosent** [comment]
We are working on a fix but it will take a few weeks to roll it out to all regions

**Comment by andrekiba** [comment]
ok but is it possible to know when it will be for north europe?

**Comment by andrekiba** [comment]
@torosent could you please provide confirmation about the roll out? Seems that it works now.

**Comment by ahmelsayed** [comment]
yes, this should have rolled out to all regions earlier this week.

**Comment by zhenqxuMSFT** [comment]
@andrekiba today the "require" mode actually behave exactly same as "accept" mode, which is inconsistent with the name "require". Recently we had an internal discussion on it and plan to restore the "require" behavior to old one - which advertises default Ubuntu trusted CA and rejects connection if no client cert is provided.
For you, we suggest you to change mode type to accept, this won't break your functionality because currently require is same as accept.

**Comment by MarekLani** [comment]
@zhenqxuMSFT please any update on require vs accept?

**Comment by j94305** [comment]
The documentation now specifies the client certificate modes available. In order to enforce mTLS, we could say "require".
The documentation also specified the headers used to pass the certificate information to the application. Fine.
The documentation mentions the relevant client certificates could be self-signed. Perfect.

What the documentation does not mention (and I have done extensive search in all kinds of resources by now): how do you specify the PKCS#12 keystore with the permitted client certificates? There do not seem to be any parameters in the GUI or the CLI to provide the keystore. Can anybody resolve this mystery?

If this would work, we could use the ingress of ACA essentially like an NGINX in front of a bunch of containers, implementing mTLS and passing proper authentication headers to the applications behind.

Thanks much in advance for any pointers.

**Comment by TiloGit** [comment]
documentation is missing how the cert is forwarded, just states: 
_Ingress passes the client certificate to the container app if require or accept are set._

Here a return info (after pulling my hair that ACA doesn't support Ingress to TLS Exposed port ,see https://github.com/microsoft/azure-container-apps/issues/705 )

here the info: 
```console
tilo@mypc:/mnt/c/tso-azure-container-app$ curl -k -v --cert-type P12 --cert /mnt/c/dev-tso-ns/X509/certs-for-tso/tso-service-keystore.p12:ZUo---AOjv -f https://echo-app.applepie-99999d2c.westus3.azurecontainerapps.io/
*   Trying 99.99.99.187:443...
* Connected to echo-app.applepie-99999d2c.westus3.azurecontainerapps.io (99.99.99.187) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=applepie-99999d2c.westus3.azurecontainerapps.io
*  start date: Sep  4 02:10:12 2024 GMT
*  expire date: Aug 30 02:10:12 2025 GMT
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure RSA TLS Issuing CA 04
*  SSL certificate verify result: self-signed certificate in certificate chain (19), continuing anyway.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x562560383eb0)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET / HTTP/2
> Host: echo-app.applepie-99999d2c.westus3.azurecontainerapps.io
> user-agent: curl/7.81.0
> accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 200
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< content-length: 8367
< etag: W/"20af-dPQdlhk____wXUmLYzfg"
< date: Mon, 09 Sep 2024 23:55:45 GMT
<
{
  "path": "/",
  "headers": {
    "host": "echo-app.applepie-99999d2c.westus3.azurecontainerapps.io",
    "user-agent": "curl/7.81.0",
    "accept": "*/*",
    "x-forwarded-for": "96.53.39.98",
    "x-envoy-external-address": "96.53.39.98",
    "x-request-id": "50add482-8895-444a-8278-4e530beb85da",
    "x-forwarded-client-cert": "Hash=ab44189bf65______4795dd02d;Cert=\"-----BEGIN%20CERTIFICATE-----%0AMIIGf_______OOzMMYUao%3D%0A-----END%20CERTIFICATE-----%0A\";Chain=\"-----BEGIN%20CERTIFICATE-----%0AMIIGfDCCBGS____YPMeaJoGIcAb4%2BEgmOOzMMYUao%3D%0A-----END%20CERTIFICATE-----%0A-----BEGIN%20CERTIFICATE-----%0AMIIFsjCCA5qgAwI____pBTeRNmrqFXU7zBRldRVsvdtKNumuX%2FUGpM9NXSoe%0A5ENvqBTUt62Ll%2F3nu8O3F3ofF74B7Q%3D%3D%0A-----END%20CERTIFICATE-----%0A\"",
    "x-envoy-expected-rq-timeout-ms": "1800000",
    "x-k8se-app-name": "echo-app--9xzn81v",
    "x-k8se-app-namespace": "k8se-apps",
    "x-k8se-protocol": "http1",
    "x-k8se-app-kind": "web",
    "x-ms-containerapp-name": "echo-app",
    "x-ms-containerapp-revision-name": "echo-app--9xzn81v",
    "x-arr-ssl": "true",
    "x-forwarded-proto": "https"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "echo-app.applepie-99999d2c.westus3.azurecontainerapps.io",
  "ip": "96.53.39.98",
  "ips": [
    "96.53.39.98"
  ],
  "protocol": "https",
  "query": {},
  "subdomains": [
    "westus3",
    "applepie-99999d2c",
    "echo-app"
  ],
  "xhr": false,
  "os": {
    "hostname": "echo-app--9xzn81v-7595579f59-w4h4m"
  },
  "connection": {}
* Connection #0 to host echo-app.applepie-99999d2c.westus3.azurecontainerapps.io left intact
* ```

**Comment by ahmelsayed** [comment]
It's mentioned under headers in https://learn.microsoft.com/en-us/azure/container-apps/ingress-overview#http-headers
but can be added to the client cert doc as well.

Regarding #705, you can set `targetPortHttpScheme: https` on the ingress in api-version >= `2024-08-02-preview`

Note that the proxy is still serving its own certs to the client (or or whatever cert you configure on the app). If you want to handle TLS completely within your application you will have to use a TCP ingress rather than an HTTP one.
