### ISSUE TITLE
GitHub actions errors `Could not retrieve credential from local cache for service principal`

### ISSUE THREAD

**Issue by johnkors** [microsoft/azure-container-apps#28]
Hi,

Any changes to the az cli in GitHub actions agents lately? Suddenly started getting the error below when doing `az containerapp update` in an action. The `azure/login@v1` step succeds just fine. It's only the `az containerapp update` which fails.

> ERROR: Could not retrieve credential from local cache for service principal <snip>. Please run 'az login' for this service principal.

**Comment by Phiph** [comment]
Yeah I had the same problem in my pipeline. 

It's something to do with the difference of version in the Azure CLI for each step. I made sure I used the host's version of the auzre CLI and don't set a version between the 2  - that seemed to have worked for me.  

`
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Deploy bicep
        uses: azure/CLI@v1
        with:
        
          inlineScript: |
            az group create -g ${{ secrets.RESOURCE_GROUP }} -l northeurope
            az deployment group create -g ${{ secrets.RESOURCE_GROUP }} -f ./deployment/main.bicep \
             -p \
                minReplicas=0 \
                actorImage='${{ needs.build.outputs.containerImage-actor }}' \
                actorPort=80 \
                apiImage='${{ needs.build.outputs.containerImage-api }}' \
                apiPort=80 \
                containerRegistry=${{ env.REGISTRY }} \
                containerRegistryUsername=${{ github.actor }} \
                containerRegistryPassword=${{ secrets.PACKAGES_TOKEN }}
`

I used this issue here for my own troubleshooting  https://github.com/Azure/azure-cli/issues/20153

**Comment by Phiph** [comment]
#Azure/azure-cli#20153

**Comment by xwang971** [comment]
Hi, @johnkors thanks for reporting this and thanks for info from@Phiph. I think this should be a known issue that comes from github action azure/login@v1. If dont specify the version, the azure/login@v1 will automatically intall the latest one which has some problem retrieving SP. To mitigate the issue, could you try set azcliversion to previous version like: 2.29.2? We will keep tracking the issue and let you know when it is fixed.

**Comment by johnkors** [comment]
Ok, my version was provided by the the auto-generate feature, so I already had a version lower than 2.29.2 though:
```
- name: Deploy to containerapp
  uses: azure/CLI@v1
  with:
    azcliversion: 2.20.0
```

**Comment by Phiph** [comment]
@johnkors Cool :) Glad I could help. 

Would you mind closing the issue if it's resolved. :)

**Comment by johnkors** [comment]
Is it resolved?

Anyone using `az containerapp github-action add` would get an explicit azcliversion set with this error. 

Fine by me to close it if you track that elsewhere, ofc.

**Comment by xwang971** [comment]
Thanks for your patience.
This is resolved by changing the yml file to use the latest version.
