### ISSUE TITLE
Websockets do not work with transport protocol set to either "auto" or "http2".

### ISSUE THREAD

**Issue by edmundmunday** [microsoft/azure-container-apps#280]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
- We run an instance of Hasura in an Azure Container app, talking to our front-end using GraphQL subscriptions over websockets.
- On the default configuration for Container Apps, the `transport` property for the ingress is set to `auto`, which seems to force it towards HTTP2.
- For some reason, this seems to break Websockets (maybe due to something missing in HTTP2 re: the HTTP1.1 Protocol Upgrade Mechanism? (https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism).
- The connection will get rejected every time it is attempted and will return a 503.
- Forcing the Container App to use `http` for its transport protocol on the ingress resolves the issue, but this is not a documented requirement anywhere.
### Steps to reproduct
1. Setup an app that uses a GraphQL Subscription over a WSS connection running in a Container App.
2. Attempt to create a Subscription connection to the app, it will throw a 503 (we were using Hasura, specifically).
3. Force the Container App to use `http` for it's ingress transport instead of `auto` or `http2` and it will work.

**Expected behavior** [What you expected to happen.]
- I'd expect it to work with the `auto` preset, since the docs for the ingress say that it supports WebSockets out of the box.
- At the least, it should be documented that it needs to be pinned to `http` for WebSockets to work.
- Also, for the love of god, provide a reference ARM template with ALL the possible configuration variables. We were only able to find that this property existed by trawling through the docs for the CLI, and guessing that there was an equivalent property for the templates.

**Actual behavior** [What actually happened.]
- Nothing documented.

**Screenshots**         
<img width="799" alt="image" src="https://user-images.githubusercontent.com/20222644/175757935-e76e9a06-7b1a-4fd1-a44f-b52a9d985c2b.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/20222644/175757941-a7885245-2267-40a0-9d6e-6b4575c42284.png">

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by ahmelsayed** [comment]
Websockets should definitly work out of the box with `transport: auto` in fact `transport: auto` == `transport: http`, so I'm a bit surprised that it works if you explicitly set it to `http` and doesn't with `auto`. `transport: http2` just assumes the upstream, i.e: your app, can also do http2. The endpoint, i.e: `{myapp}.delightfulenv-00000.eastus.azurecontainerapps.io` will always do what the client asks for (http1, http1.1, http2, and soon http3) but the upstream between that endpoint and the app will assume the value in `transport`. 

Do you have a repro I can look at? Trying with just `hasura/graphql-engine:v2.8.1` and a simple subscription gql subscription query in the UI there works fine on container apps with the default values for ingress.

```graphql
subscription {
  users {
    id
    name
    created_at
  }
}
```

Though I'm not sure if the client, apollo I'm assuming?, is doing something different? If you can share the URL of the app you had the issue with I can look furthor into it. Either here or shoot me an email: ahmels at microsoft.com

**Comment by michaelmcneilnet** [comment]
We've been using websockets with transport set to auto for a couple of months with no issues

**Comment by mariusmuntean** [comment]
I seem to have the same problem with my GraphQL server (using GraphQL-dotnet), i.e. no websocket connection can be established from my React frontend to my GraphQL backend running on ACA.

Is there an option in the portal to set the transport to http?

**Comment by ahmelsayed** [comment]
@mariusmuntean do you have a repro you can share? If you have an app that's reproducing that behavior, can you share it with me. You can use ahmels at microsoft.

**Comment by edmundmunday** [comment]
@ahmelsayed - we'll try and recreate the issue over the next few days and pass you the details. If we recreate it in a site and share a resource group ID where it's all running and the issue is occurring, are you able to access that?

**Comment by edmundmunday** [comment]
@ahmelsayed - worth noting that we aren't using Apollo, we rolled our own client that wraps graphql-ws (https://github.com/enisdenjo/graphql-ws). 

Depending on the Apollo implementation you're using, it might still be wrapping `subscriptions-transport-ws` (https://github.com/apollographql/subscriptions-transport-ws) which is technically no longer supported - I know this was the default for Apollo for quite a while.

Will work on that repro and let you know.

**Comment by SophCarp** [comment]
We are tracking this request in #562. We are investigating and should have a solution some time in Q2 2023. I'm going to close this issue so that we can keep track of it in 562. Thanks!

**Comment by Vernon271** [comment]
what a joke still an issue in 2026
