### ISSUE TITLE
Unable to get Ingress to work correctly

### ISSUE THREAD

**Issue by gregpakes** [microsoft/azure-container-apps#282]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am trying to setup a container app that is accessible only to a vnet.  The container listens on port 3310, but I can't seem to get the ingress to work correctly.

The container is the official CLAMAV docker container.

### Steps to reproduce

```
resource clamAvContainerApp 'Microsoft.App/containerApps@2022-03-01' = {
  name: 'ca-isams-${locationCode}-clamav-${environment}-01'
  location: location
  properties: {
    managedEnvironmentId: managedEnvironmentId
    template: {
      containers: [
        {
          name: 'ci-isams-${locationCode}-clamav-${environment}-01'
          image: 'docker.io/clamav/clamav:latest'
          resources: {
            cpu: 1
            memory: '2Gi'
          }
          volumeMounts: [
            {
              mountPath: '/var/lib/clamav'
              volumeName: 'azurefiles-mount'
            }
          ]
        }
        
      ]
      volumes: [
        {
          name: 'azurefiles-mount'
          storageType: 'AzureFile'
          storageName: 'azurefilestorage' // must match the name in the managed environment
        }
      ]
    }
    configuration: {
      ingress: {
        external: true
        targetPort: 3310
        transport: 'http'
        allowInsecure: true
      }
    }
  }
}
```

**Expected behavior**

I would expect that a request to the fqdn on port 80 would get sent to port 3310 of the container.  Instead I just get 400 bad request.

If I identify the container IP directly and try to access it on port 3310, it works.

**Actual behavior** [What actually happened.]

I get 400 bad request.

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by ahmelsayed** [comment]
`clamd`'s 3310 port is a TCP port, not an HTTP port. [see](https://docs.clamav.net/manual/Installing/Docker.html#tcp)

Tracking that in https://github.com/microsoft/azure-container-apps/issues/129
