### ISSUE TITLE
Revision gets stuck provisioning if unable to access Storage Account

### ISSUE THREAD

**Issue by gregpakes** [microsoft/azure-container-apps#283]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
If you are using a custom vnet and Azure Files and the vnet subnet ddoes not have access to the storage account, the container will get stuck in the provisioning state.

### Steps to reproduct
1. Create a container app environment on a custom vnet
2. Create a container app that uses Azure File mount
3. Ensure the environment subnet does not have access to the Storage Account for the Azure File mount.

**Expected behavior** [What you expected to happen.]

An error should be thrown when provisioning is attempted.

**Actual behavior** [What actually happened.]

The provisioning just hangs indefinitely.

**Comment by simonjj** [comment]
We've closing this, please file a new issue pointing to this one if it's still an ongoing bug.
