### ISSUE TITLE
Unable to configure custom domain

### ISSUE THREAD

**Issue by mihaiLucian** [microsoft/azure-container-apps#284]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
After I import my domain certificate, it is not available to be selected in the dropdown menu when adding a custom domain.

### Steps to reproduce
1. Add new domain and validate the domain
2. Create new certificate
3. Certificate is not available to be selected from the dropdown

**Expected behavior** [What you expected to happen.]
Certificate to be available to be linked with the domain

**Actual behavior** [What actually happened.]
Certificate is not available

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by vreshch** [comment]
Having same issue, certificate were ordered via portal.

**Comment by vinisoto** [comment]
We removed a validation in the portal that was only looking at CN and ignoring SAN. This fix has been rolled out (early this week). Can you try again?
