### ISSUE TITLE
Custom domain is added but is not working

### ISSUE THREAD

**Issue by gerwim** [microsoft/azure-container-apps#287]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The custom domain is added through the Azure portal (which means a valid certificate aswell), but the custom domain does not end up working. SSL error and regular HTTP requests return a 404.

### Steps to reproduct
1. Create a container app environment ~~with a custom vnet~~ (edit: custom vnet is not related)
2. Create a container app
3. Configure custom domain

**Expected behavior** [What you expected to happen.]
The custom domain name works
**Actual behavior** [What actually happened.]
Sending a HTTP request to the domain returns a 404. Only the default Azure FQDN works.

### Additional context
The CLI also returns the custom domain:
```
az containerapp ingress show --name dzg-api --resource-group PN-ClosedLoop-TST-rg
{
  "allowInsecure": false,
  "customDomains": [
    {
      "bindingType": "SniEnabled",
      "certificateId": "/subscriptions/xxx/resourceGroups/PN-ClosedLoop-TST-rg/providers/Microsoft.App/managedEnvironments/PN-ClosedLoop-TST-cae/certificates/api-tst-cert",
      "name": "yyy" <---- the domain is returned from the CLI aswell
    }
  ],
  "external": true,
  "fqdn": "zzz.westeurope.azurecontainerapps.io",
  "targetPort": 80,
  "traffic": [
    {
      "latestRevision": true,
      "weight": 100
    }
  ],
  "transport": "Auto"
}
```

**Comment by aaberg** [comment]
I'm listening in. We have have the exact same problem. 
I actually managed to make it work by doing the following:
- I created an app service (web app) and gave it the custom domain. I set up the CNAME and asuid TXT record and everything with our DNS-provider.
- When that worked, I set up the custom domain with the container app.
- Then I deleted the app service.

Makes me believe that it is an internal networking problem with Azure.

**Comment by asankaf** [comment]
Hi,

I have the same sort of issue when trying to bind an exported wildcard certificate that was generated as an Azure App Service Certificate. `openssl pkcs12 -in C:\certstore\appserviceswildcardcert.pfx -chain -nokeys` clearly shows the full chain with the 3 certs, so I am certain that this certificate is valid. But when I upload the certificate to the container apps environment and bind it to a custom domain in a container app, the app doesn't really work with the custom domain (404).

nslookup to the custom domain correctly shows that the DNS level name resolution takes place just fine. If I navigate to the container app generated https endpoint (xxx.azurecontainerapps.io), it works just fine too, but not when I go to the custom domain.

![image](https://user-images.githubusercontent.com/1999525/176850285-aeca748c-a048-43ae-972a-71b1b6ffcee3.png)

**Comment by gerwim** [comment]
I have configured six domains across three resource groups and can confirm custom domains are now working. Looks like Microsoft fixed the issue.

**Comment by schafei** [comment]
It seems, I have the exact same issue at the moment. Anybody else still experiencing problems with custom domains not working?
