### ISSUE TITLE
Ensure better integration / documentation / sample of provisionning with Pulumi IaC

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure-container-apps#288]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Pulumi [docs](https://www.pulumi.com/registry/packages/azure-native/how-to-guides/azure-ts-containerapps) does not show how to provision Azure Container App with latest features such as deployment to VNet.

### Steps to reproduct
1.  Read [https://github.com/pulumi/examples/blob/master/azure-ts-containerapps/index.ts](https://github.com/pulumi/examples/blob/master/azure-ts-containerapps/index.ts)
2. try to deploy 1 Azure Container App with all latest features including deployment to VNet, AuthConfigs, Probes, Scaling rules, volumes, etc.

**Expected behavior** [What you expected to happen.]
A Pulumni newbbie should be able to provision a full Azure Container App following Pulumni  docs

**Actual behavior** [What actually happened.]
Pulumi doc is not comprehensive

**Screenshots**         
N/A

### Additional context
N/A

**Comment by kendallroden** [comment]
Please refer to the official Pulumi documentation for additional insights: https://www.pulumi.com/blog/azure-container-apps/
