### ISSUE TITLE
Feature Request: support third-party monitoring solutions

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure-container-apps#289]
**Is your feature request related to a problem? Please describe**.  
support third-party monitoring solutions as [Azure Spring Apps](https://docs.microsoft.com/en-us/azure/spring-cloud/how-to-dynatrace-one-agent-monitor) does including : 

- Dynatrace
- Datadog
- CISCO AppDynamics
- Elastic

**Describe the solution you'd like**.    
A customer already uses one of the above solution and wants to use the same  one with Azure Container Apps

**Describe alternatives you've considered**.   
N/A

**Additional context**.  
N/A

**Comment by epomatti** [comment]
Datadog integration: https://app.datadoghq.com/integrations/azure-container-apps

**Comment by joergjo** [comment]
Note that the current Datadog solution mentioned above seems severely limited in scope. It provides ACA provided metrics and a pod inventory, but no logs, traces, or application metrics.

**Comment by BigMorty** [comment]
Datadog has more information for integrating logs and custom metrics in their documentation - https://docs.datadoghq.com/serverless/azure_container_apps/

**Comment by jometzg** [comment]
My customer would like DynaTrace integrated.

**Comment by BigMorty** [comment]
Thanks @jometzg, I am working to get DynaTrace integration working with Azure Container Apps. I don't have an ETA at this time.

**Comment by storm1er** [comment]
We are also looking into this.

There's an very hard constraints with current datadog integration: it's limited to some languages and framework only.

**Comment by storm1er** [comment]
Relates to https://github.com/DataDog/datadog-agent/issues/18160

**Comment by LianaAdaza** [comment]
A managed Open telemetry agent is now in public preview. If you have any feedback or further questions, please refer to https://github.com/microsoft/azure-container-apps/issues/768

Thank you
