### ISSUE TITLE
Automatic zonal distribution of replicas

### ISSUE THREAD

**Issue by denniszielke** [microsoft/azure-container-apps#29]
As a customer I care about zonal resiliency and would like to get automatic zonal distribution of replicas (assuming that I have enough replicas and the DC supports zones).

**Comment by krispenner** [comment]
I would very much like to know if there are any plans to support availability zones. We have Cosmos DB, blob storage, key vaults, service bus and web apps all deployed across availability zones. We want to move away from web apps and to container apps. Would we be losing the resiliency of zones though? Is there any plan to support this preferably automatically?

**Comment by kendallroden** [comment]
Azure Container Apps is deployed on top of AKS and supports AKS availability zones automatically by deploying across three zones. @torosent can confirm

**Comment by kendallroden** [comment]
We are working on plans to enable availability zones transparently.

**Comment by kendallroden** [comment]
Closing: https://learn.microsoft.com/en-us/azure/container-apps/disaster-recovery?tabs=bash 

If there are additional requests or the above az feature does not meet needs please let us know via a new issue!
