### ISSUE TITLE
Feature Request: Application Insights / Distributed tracing support

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure-container-apps#290]
**Is your feature request related to a problem? Please describe**.  
Azure Container Apps does not provide a Distributed tracing solution, like Java In-Process Agent which is supported in [Azure Spring Apps](https://docs.microsoft.com/en-us/azure/spring-cloud/how-to-application-insights?pivots=sc-standard-tier)

**Describe the solution you'd like**.    
When designing micro-services and connecting multiple apps, with or WITHOUT Dapr, SRE/Ops need a Distributed tracing solution integrated in the Azure portal

**Describe alternatives you've considered**.   
None

**Additional context**.  
N/A

**Comment by BigMorty** [comment]
While Azure Container Apps does not have a no-code way to integrate App Insights today, you can still use the App Insights SDK and get the same benefits.

**Comment by bengimblett** [comment]
@BigMorty I am also struggling here

I have a simple two microservices (dotnet core minimal api, latest) each with AI SDK latest and they communicate via DAPR and an SB Queue binding

I set the following when deploying the ACA Env daprAIInstrumentationKey

I therefore have 3 x AI resources - one for DAPR, one for each microservice 

So whilst i do see telemetry none of it is correlated each item has its own operation id (which is incorrect) 

I had expected end to end correlation (an app map of each component connected by DAPR) 

Looking at the DAPR docs the config for AI is via OTEL but this appears abstracted away for ACA

Can you help ? Is this supposed to work in the way i assumed it would?

**Comment by kendallroden** [comment]
You should see an app map in the resource you provided the instrumentation key for- can you share any additional information on your config? How did you deploy this solution, etc.?

**Comment by ezYakaEagle442** [comment]
@kendallroden I have understood now, it should work : in my case I do not use Dapr, I have provisionned AppInsights with [Bicep](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/iac/bicep/aca/pre-req.bicep#L129) ,  then I use its ConnectionString in my [main.bicep](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/iac/bicep/aca/main.bicep#L205) where a Module create the [ACA Apps ](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/iac/bicep/aca/aca.bicep#L232) inside which I use the ConnectionString as env : 

```
resource AdminServerContainerApp 'Microsoft.App/containerApps@2022-03-01' = {
  name: adminServerContainerAppName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    managedEnvironmentId: corpManagedEnvironment.id 
    configuration: {
      activeRevisionsMode: 'Multiple'
      ingress: {
        allowInsecure: true
        external: true
        targetPort: 9090
        traffic: [
          {
            latestRevision: true
            revisionName: revisionName
            weight: 100
          }
        ]
        transport: 'auto'
      }
      registries: [
        {
          passwordSecretRef: 'registrypassword'
          server: ghaSettingsCfgRegistryUrl
          username: ghaSettingsCfgRegistryUserName
        }
      ]
      secrets: [
        {
          name: 'registrypassword'
          value: ghaSettingsCfgRegistryPassword
        }
        {
          name: 'appinscon'
          value: appInsightsInstrumentationKey
        }
    template: {
      containers: [
        {
          command: [
            'ENTRYPOINT ["java", "-javaagent:${applicationInsightsAgentJarFilePath}", "org.springframework.boot.loader.JarLauncher", "--server.port=8080", "--spring.profiles.active=docker,mysql"]'
          ]
          env: [
            {
              name: 'SPRING_PROFILES_ACTIVE'
              value: 'docker,mysql'
            }
            {
              // https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#set-the-application-insights-connection-string
              name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
              secretRef: 'appinscon'
            }
```

**Comment by bengimblett** [comment]
> You should see an app map in the resource you provided the instrumentation key for- can you share any additional information on your config? How did you deploy this solution, etc.?

Thanks - i will redeploy and try again, I'll DM you if i see same

**Comment by bengimblett** [comment]
@kendalrollden

In a simple test I have two dotnet web api in an ACA env. Each web app has its own app insights (via sdk and connection string env var config). The ACA Env is also linked to it's own AI resource.

Overview
![overview](https://user-images.githubusercontent.com/4322131/179501815-b73a0433-b599-4b4f-8756-02eb0a695c7c.gif)

Resources
![components](https://user-images.githubusercontent.com/4322131/179501827-8a975b94-0864-4a49-bbda-db81d1eb7507.gif)

Bicep for env

`resource environment 'Microsoft.App/managedEnvironments@2022-03-01' = {
  name: environmentName
  location: location
  properties: {
    daprAIInstrumentationKey: reference(appInsights.id, '2020-02-02').InstrumentationKey
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: reference(workspaceId).customerId
        sharedKey: logAnalyticsWorkspace.listKeys().primarySharedKey
      }
    }`

What I'm seeing is telemetry in all 3 but not linked. The operations id is unique. Therefore the app map and end-to-end view isnt working. The gap seems to be with the env/dapr.

Am i doing anything wrong here? What should be happening is the http call from the ACA App to DAPR should have the traceparent header and then DAPR should do the rest. I cant easily repro this outside of ACA, running locally via Docker compose for example, as i'd need to know more exactly what you did on the AKS hosting side (presumably using otel) and I dont :)

**Comment by bengimblett** [comment]
This didnt work in a slightly more complex test with ASB via DAPR (queue) either

**Comment by ezYakaEagle442** [comment]
I deploy Java Apps to ACA, I have set correctly the AppInsights config files applicationinsights.json with 1 unique name for each App.
Ex at   [https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-customers-service/src/main/resources/applicationinsights.json](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-customers-service/src/main/resources/applicationinsights.json)

AppInsight Agent for Java in ACA shows only 1 green circle in Application Map.
Could you please tell me what is wrong in my config ?

The Application Map looks like this :                                                                                                               
 
![image](https://user-images.githubusercontent.com/43554247/198845329-ee6469b5-f07e-48a3-becb-fe2432794da5.png)


Whereas it should looks like this : 
![image](https://user-images.githubusercontent.com/43554247/198845337-4e06ac95-fc33-49eb-b3ea-5fe5bd83fbe6.png)



The Container command is set in Bicep with: 
```sh
      secrets: [
        // [https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#set-the-application-insights-connection-string](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#set-the-application-insights-connection-string)
        {
          name: 'appinscon'
          value: appInsights.properties.ConnectionString
        }

    template: {
      containers: [
        { 
          command: [
            'java', '-javaagent:${applicationInsightsAgentJarFilePath}', 'org.springframework.boot.loader.JarLauncher', '--server.port=8080', '-Xms512m -Xmx1024m'
          ]
          env: [
            {
              name: 'SPRING_PROFILES_ACTIVE'
              value: 'docker,mysql'
            }
            {
            // [https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#set-the-application-insights-connection-string](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#set-the-application-insights-connection-string)
        {
              name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
              secretRef: 'appinscon'
            }
```
 
 

![image](https://user-images.githubusercontent.com/43554247/198845390-cdb7536b-4113-4711-b678-0b041cafb481.png)

**Comment by ezYakaEagle442** [comment]
@BigMorty  @sanchitmehta  is it because I set this config [https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/iac/bicep/modules/aca/acaPublicEnv.bicep#L22](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/iac/bicep/modules/aca/acaPublicEnv.bicep#L22)   with **destination:log-analytics**  ?: 

```sh
@allowed([
  'log-analytics'
  'azure-monitor'
])
@description('Cluster configuration which enables the log daemon to export app logs to a destination. Currently only "log-analytics" is supported https://learn.microsoft.com/en-us/azure/templates/microsoft.app/managedenvironments?pivots=deployment-language-bicep#managedenvironmentproperties')
param logDestination string = 'log-analytics' // 'log-analytics' or 'azure-monitor' 

resource logAnalyticsWorkspace  'Microsoft.OperationalInsights/workspaces@2021-12-01-preview' existing =  {
  name: logAnalyticsWorkspaceName
}

resource appInsights 'Microsoft.Insights/components@2020-02-02-preview' existing = {
  name: appInsightsName
}

/*
ACA does not yet support diagnostic settings
container apps do no support currently diagnostic settings. Integration happen trough property on the app environment resource currently.
https://github.com/microsoft/azure-container-apps/issues/382
https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/diagnosticsettings?tabs=bicep
*/
resource corpManagedEnvironment 'Microsoft.App/managedEnvironments@2022-06-01-preview' = {
  name: azureContainerAppEnvName
  location: location
  properties: {
    appLogsConfiguration: {
      destination: logDestination // azure-monitor
      logAnalyticsConfiguration: {
        customerId: logAnalyticsWorkspace.properties.customerId
        sharedKey: logAnalyticsWorkspace.listKeys().primarySharedKey
      }
    }
    zoneRedundant: zoneRedundant
    daprAIInstrumentationKey: appInsights.properties.InstrumentationKey
    daprAIConnectionString: appInsights.properties.ConnectionString
  }
}

output corpManagedEnvironmentId string = corpManagedEnvironment.id 
output corpManagedEnvironmentDefaultDomain string = corpManagedEnvironment.properties.defaultDomain
output corpManagedEnvironmentStaticIp string = corpManagedEnvironment.properties.staticIp
```

Would this fix the issue ?:
```sh
param logDestination string = 'azure-monitor' 

resource appInsightsDiagnosticSettings 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'dgs-${appName}-send-${azureContainerAppEnvName}-logs-and-metrics-to-log-analytics'
  scope: corpManagedEnvironment
  properties: {
    logAnalyticsDestinationType: 'AzureDiagnostics'
    workspaceId: logAnalyticsWorkspace.id
    logs: [
      {
        category: 'ContainerAppConsoleLogs'
        enabled: true
      }
      {
        category: 'ContainerAppSystemLogs'
        enabled: true
      }      
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
        retentionPolicy: {
          days: 7
          enabled: true
        }
      }
    ]
  }
}
```

**Comment by ezYakaEagle442** [comment]
@BigMorty @sanchitmehta 

As stated in the [docs](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#configuration-file-path) , by default, Application Insights Java 3.x expects the configuration file to be named applicationinsights.json and to be located in the same directory as applicationinsights-agent-3.x.x.jar

You can specify your own configuration file path by using one of these two options:
- APPLICATIONINSIGHTS_CONFIGURATION_FILE environment variable
- applicationinsights.configuration.file Java system property

In my configuration:

- applicationinsights-agent-3.4.1.jar is located in the container at /tmp/app/applicationinsights-agent-3.4.1.jar
- In the source code, the config files are located in each micro-service at src/main/resources/applicationinsights.json
- in the ACA containers the applicationinsights.json is located at BOOT-INF/classes/applicationinsights.json because in the [Dockerfile](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/docker/petclinic-customers-service/Dockerfile#L19) I use Java layertools to extract all the files from the jar.

setting this Env. var APPLICATIONINSIGHTS_CONFIGURATION_FILE=BOOT-INF/classes/applicationinsights.json fixed the issue, I then see each service in a green circle in the AppMap  EXCEPT Key-Vault whereas each service get the DB connection string secret from KV

**Comment by SophCarp** [comment]
There's been a lot of discussion on this thread. Has the issue been resolved? @ezYakaEagle442

**Comment by edeandrea** [comment]
I see this issue was closed but I don't see a solution mentioned in the thread. Was there ever a distributed tracing solution added?
