### ISSUE TITLE
Custom Domain Certificate Binding ignores SAN value and always uses CN value

### ISSUE THREAD

**Issue by relusion** [microsoft/azure-container-apps#292]
### This issue is a: (mark with an x)
- [ x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
"Subject Alternative Name" is ignored for certificates uploaded to App Container environment certificates list and CN value is displayed in as a host value.  That breaks the custom domain binding process.

### Steps to reproduct
1. Create a certificate with CN = some text value  and SAN = domain uri
2. upload the pfx to the Container apps certificates
3. wrong host value is displayed. (taken from CN and not from SAN)
4. Cannot bind this certificate to custom domain with error " No certificate match for selected domain"

**Expected behavior** [What you expected to happen.]
user can bind the certificate with CN and SAN values assigned and SAN takes priority over CN when certificate information gets parsed.

If a SSL Certificate has a Subject Alternative Name (SAN) field, then Container Apps service is supposed to ignore the Common Name value and seek a match in the SAN list. 

**Actual behavior** [What actually happened.]
Because Container apps loads wrong host value certificates cannot be bound to custom domains.
**Screenshots**         

### Additional context
One can reproduce this in Portal.

**Comment by sanjay3290** [comment]
@relusion did you find any workaround?

**Comment by rs-troper** [comment]
Any updates on this?

**Comment by relusion** [comment]
> @relusion did you find any workaround?

no

**Comment by vinisoto** [comment]
@relusion - we rolled out a fix (within the last day or two) in the portal in which the list of available certificates is no longer filtered by CN only. Can you try again?

**Comment by rs-troper** [comment]
While I am not the author of this issue, for what it's worth, I had this same issue and it is now working as expected.

**Comment by relusion** [comment]
> @relusion - we rolled out a fix (within the last day or two) in the portal in which the list of available certificates is no longer filtered by CN only. Can you try again?

also can confirm it works now, thanks!
