### ISSUE TITLE
Inaccurate ACA DNS Doc

### ISSUE THREAD

**Issue by zlatko-ms** [microsoft/azure-container-apps#298]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

The following commands to retrieve the CA Environnement static IP and domain shown at https://docs.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-cli are inaccurate :

``
ENVIRONMENT_STATIC_IP=`az containerapp env show --name ${CONTAINERAPPS_ENVIRONMENT} --resource-group ${RESOURCE_GROUP} --query staticIp --out json | tr -d '"'`
``
and 
``
ENVIRONMENT_DEFAULT_D
![issueDnsCLI](https://user-images.githubusercontent.com/72125625/177377440-39aa9658-79a0-4155-8d8d-835c731ded77.png)
OMAIN=`az containerapp env show --name ${CONTAINERAPPS_ENVIRONMENT} --resource-group ${RESOURCE_GROUP} --query defaultDomain --out json | tr -d '"'`
``

The information is contained in the **properties** object of the response, hence the command line should be written as : 

``
ENVIRONMENT_STATIC_IP=`az containerapp env show --name ${CONTAINERAPPS_ENVIRONMENT} --resource-group ${RESOURCE_GROUP} --query properties.staticIp --out json | tr -d '"'`
``
and
``
ENVIRONMENT_DEFAULT_DOMAIN=`az containerapp env show --name ${CONTAINERAPPS_ENVIRONMENT} --resource-group ${RESOURCE_GROUP} --query properties.defaultDomain --out json | tr -d '"'`
``

I would also suggest to move to the $() form and avoid the backquotes as it makes the copy/paste in scripts easier.

### Steps to reproduct
1. execute the following command : 
ENVIRONMENT_DEFAULT_DOMAIN=`az containerapp env show --name ${CONTAINERAPPS_ENVIRONMENT} --resource-group ${RESOURCE_GROUP} --query defaultDomain --out json | tr -d '"'`
echo $ENVIRONMENT_DEFAULT_DOMAIN
``

**Expected behavior** [What you expected to happen.]

The environnement default domain is displayed

**Actual behavior** [What actually happened.]

It will display an empty string as there is no defaultDomain entry within the top level response object.

**Screenshots**         

Attached screenshot of erroneous and correct CLI commands.

### Additional context
CLI

**Comment by anthonychu** [comment]
Thanks for reporting. A fix for this is rolling out in a few hours.

**Comment by zlatko-ms** [comment]
Hi, I noticed that the doc still has the same issues. Any plans on updating the page ?

**Comment by kendallroden** [comment]
@anthonychu can we please check this was closed or not?

**Comment by kendallroden** [comment]
Fixed
