### ISSUE TITLE
Unable to query console logs via CLI

### ISSUE THREAD

**Issue by zlatko-ms** [microsoft/azure-container-apps#299]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

When querying the console logs of an app using the CLI with the following command : 

`az containerapp logs show -n helloer -g privatecapps`

I get the following error : 

`HTTPSConnectionPool(host='helloer.politesky-4265fa35.westeurope.azurecontainerapps.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd008c21ea0>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

Please note that : 

- the log stream from the portal correctly displays the logs for this application
- the apps serves via HTTP with an average load around 100 Requests per second

An app within the same Environnement, but not serving HTTP requests can be queried for logs without issues. 

### Steps to reproduct
1. Deploy an app with HTTP serving  ~ 100 Requests/seconds
2. Issue the `az containerapp logs show -n ...' command

**Expected behavior** [What you expected to happen.]

Application console logs are displayed.

**Actual behavior** [What actually happened.]

Throws an error with the following message : 

`HTTPSConnectionPool(host='helloer.politesky-4265fa35.westeurope.azurecontainerapps.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd008c21ea0>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

**Screenshots**         

See command and error in the screenshot.

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
![errorLogsACA](https://user-images.githubusercontent.com/72125625/177379082-bf2a3ab0-6cdc-4e82-9715-815ce92d0260.png)

**Comment by zlatko-ms** [comment]
@torosent , here are the steps to reproduce the issue in a certain way, simply open a WSL and execute the following commands : 

- az bicep install
- git clone -b aca-issue-299 git@github.com:zlatko-ms/az-capps-private.git
- cd az-capps-private/src/bicep
- make reproduce

It will take approximately 10/15 minutes to complete, and you'll get the reported error message at the end.

PS : I can update the initial report with steps to reproduce but I'm afraid it could raise some confusion, so if necessary let me know I'll do it.

**Comment by StrawnSC** [comment]
@zlatko-ms @torosent we have a [fix for this in review](https://github.com/calvinsID/azure-cli-extensions/pull/134). I anticipate this fix will go out with the next CLI extension version

**Comment by torosent** [comment]
Hi All, 
The GET command doesn't return any secrets values since it can be a security risk for the users.
The CLI will be updated very soon to support PATCH for the update command instead of PUT. This will allow you to remove the `Secrets` property from the YAML file without removing the actual secrets from the app.
You can also use the `az containerapp secret` command to manage the app secrets

**Comment by StrawnSC** [comment]
> Hi All,
> The GET command doesn't return any secrets values since it can be a security risk for the users.
> The CLI will be updated very soon to support PATCH for the update command instead of PUT. This will allow you to remove the `Secrets` property from the YAML file without removing the actual secrets from the app.
> You can also use the `az containerapp secret` command to manage the app secrets

@torosent I think you meant to comment on this issue: https://github.com/microsoft/azure-container-apps/issues/259

**Comment by torosent** [comment]
Thanks @StrawnSC. By bad :)

**Comment by zlatko-ms** [comment]
Hi I just re-tested with the latest version of the CLI (2.39.0) and containerapp  extension (0.3.8) and the issue seems to be fixed, the logs can be obtained via the az containerapp logs show.
Maybe this issue can be closed ?
