### ISSUE TITLE
Support for Heath Checks

### ISSUE THREAD

**Issue by dpaquette** [microsoft/azure-container-apps#30]
Are there plans to support monitoring of revisions via Health Checks similar to App Service (https://docs.microsoft.com/en-us/azure/app-service/monitor-instances-health-check)?

**Comment by vturecek** [comment]
Yes, this is on our roadmap. Would you typically use this for HTTP applications (so that HTTP requests are not routed to unhealthy containers), or would you also use this for non-HTTP applications (a background processing container that is unhealthy and needs to be restarted)?

**Comment by SatyKrish** [comment]
Both cases are valid. For event driven container apps it is useful to restart when dependencies are not met.

**Comment by dpaquette** [comment]
Primary use case for me would be for HTTP applications but I would use this for background processes too

**Comment by BigMorty** [comment]
We now support Startup, Readiness, and Liveness probes - https://docs.microsoft.com/en-us/azure/container-apps/health-probes?tabs=arm-template
