### ISSUE TITLE
Feature Request: Question -> How secure is the Sidecar?

### ISSUE THREAD

**Issue by joeakim** [microsoft/azure-container-apps#300]
Hi there,

sorry for posting this in "Feature Request", but I found no matching category.

I am a noob when it comes to containers, etc. yet I need to clarify a few security questions. Maybe the questions are nonsense. So, any help is appreciated 🙂
I have an Azure Container App Environment which has dapr components configured and hosts Container Apps.
For the sidecars to able to connect to the components, I assume they "somehow" need the connection strings incl. secrets configure in the Container App Environment's dapr components.
The questions now are:

How do the dapr sidecars receive this information?
Where do the dapr sidecars store this information? Only in RAM or somewhere in their filesystem, etc.?
Is it possible to get (OS level, filesystem, RAM) access to the sidecars? Either from "outside" or from the App-container...
If yes, could those connections strings and secrets (from the dapr component's configuration) be read (and stolen)?
Thanks for you help 🙂

Regards,
Joachim

**Comment by kendallroden** [comment]
How do the dapr sidecars receive this information? Right now they use container apps secrets, which are backed by kubernetes secrets today. We are working on implementing the Dapr secrets building block which will allow these values to be pulled from places like key vault for example.

Where do the dapr sidecars store this information? The secrets are stored by kubernetes in etcd 

Is it possible to get (OS level, filesystem, RAM) access to the sidecars? No we do not let you get this type of access from the sidecars. you can mount azure files to your container app if you want your core app workload to have some type of persistent mount.
