### ISSUE TITLE
Azure container app on azure machine learning studio

### ISSUE THREAD

**Issue by cloudwithdeb** [microsoft/azure-container-apps#302]
When will azure container app be available on azure machine learning studio. I mean it will be really great having such serverless service part of it aside kubernetes and container instance.  I'm eargaly waiting for it or what do you guys think.

**Comment by marcindulak** [comment]
Requested previously in https://github.com/microsoft/azure-container-apps/issues/221

**Comment by kendallroden** [comment]
closing duplicate
