### ISSUE TITLE
Provision always fails when using image from ACR. No logs available.

### ISSUE THREAD

**Issue by charlesleaub** [microsoft/azure-container-apps#304]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

When I try to create a container app running an image that I have on ACR it shows in the revision management tab that the status of the provisioning is "Failed". I can't see any logs or anything so I did not find a way to see what actually failed. I followed the steps described in the doc either on the portal or using azure cli and the result is always the same. Is there a way to check what failed and why?

### Steps to reproduct
1. Create a container app from the portal using an image which is in an ACR.
2. Create a container app using az cli using an image which is on an ACR.

**Expected behavior** [The container app starts and I'm able to see the logs or the provision fails for some reasons and I can see why.]

**Actual behavior** [Provisioning step fails and I can't see why.]

### Additional context
This issue occurs both on azure cli and on the portal.

**Comment by BigMorty** [comment]
Sorry you are having troubles here. Did you look in the Log Analytics table named 'ContainerAppSystemLogs_CL'? There may be a system log message in there that may help.

**Comment by charlesleaub** [comment]
Hello,
thanks for your answer. Yes I tried to take a look at this table. When I
check this table with the revision name it shows me that the table does not
exist. If I check without the revision name, I can't find logs associated
to this container. I tried with the quick start image "hello-world" and it
worked well but with my personal ACR it does not.
Thanks again for your help.

Charles.

Le ven. 8 juil. 2022 à 22:02, Mike Morton ***@***.***> a
écrit :

**Comment by torosent** [comment]
If you are using busybox without any command it will terminate and the container app will try to restart it. You need to run an http server or any other container that's listening to messages.

**Comment by charlesleaub** [comment]
Do I really need to have an http server runing even if I don't need to expose any ports (I just want to deploy a worker)? Another question would be how to keep my container app up to date with my container registry? I mean updating the image automatically.

**Comment by torosent** [comment]
You can have a worker but it needs to wait for events. Even if you run it locally, it cannot terminate immediately after you start it.  If you run busybox container without any command it will terminate immediately. For example: https://docs.microsoft.com/en-us/azure/container-apps/background-processing?tabs=bash
Regarding your second question, please looks at the revisions docs. https://docs.microsoft.com/en-us/azure/container-apps/revisions

**Comment by mswilson4040** [comment]
I get the same thing. The provisioning failed with no information. I am not using busybox. I am only using a Worker Service that is consuming rabbitmq messages. I can tell the container was up and running for a bit as messages were consumed and I saw the connection. But, provisioning still fails? I think the container was provisioned and there was some exception that was thrown that made it crash. But, I am having a hard time figuring out how the logging works.

**Comment by BigMorty** [comment]
In the portal, select "Logs" in the nave area of your container app. Expand the "Customer Logs" section to see the Console and System logs table. The Console table has all logs from your app and the System table has messages produced from the container apps "runtime".

![image](https://user-images.githubusercontent.com/947510/180925584-df06e325-6763-456c-bf0f-a69433dfd752.png)

**Comment by mswilson4040** [comment]
Thanks, @BigMorty. The issue ended up being that my Ingress was enabled. I am assuming that turns on some sort of liveliness probe or health check. If that health check ever fails, provisioning continues until it gets something healthy. Since my worker has no HTTP endpoints (strictly just a BackgroundService), it never got a healthy response.

Once I disabled my Ingress, it worked immediately.

**Comment by BigMorty** [comment]
Yes, we create a default TCP readiness probe if Ingress is on, and the user has not created any probes. I think this is what caused the failure. Glad it is working now! Closing this issue.

**Comment by jordigarcia-galeo** [comment]
Hi guys,

I have a similar issue. When I enabled Ingress support to Container App, the provisioning process fails. The same docker image works fine in App Service environment. It's the [metabase image from Docker Hub](https://hub.docker.com/r/metabase/metabase/).

The TCP port is listening:
![image](https://user-images.githubusercontent.com/111049241/184100400-93e85dd2-7cd4-474f-8a8a-4cd9662bbd84.png)

And Ingress configuration refers to this TCP port:
![image](https://user-images.githubusercontent.com/111049241/184100760-d1fad3f0-1358-4917-acb0-4de5dad51a25.png)

And these are the errors:
![image](https://user-images.githubusercontent.com/111049241/184101686-b574ee61-6450-4ce6-8819-cd06cb6c6613.png)

What's wrong?
Thanks in advance

**Comment by jordigarcia-galeo** [comment]
Just clarify, 
can access to console when Ingress is not configured.
