### ISSUE TITLE
Certificate upload fails via cli but works via portal

### ISSUE THREAD

**Issue by tmcgannon** [microsoft/azure-container-apps#305]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have obtained my certificate via LetsEncrypt and produced a valid pfx file which I can upload to KeyVault via azure cli but fails when adding to Azure Container App Environment using this command:

```
az containerapp env certificate upload \    
      --resource-group ${RESOURCE_GROUP} \
      --name ${CONTAINER_APP_ENV_NAME} \
      --certificate-file ${PFX_CERT_PATH} \
      --certificate-name ${CONTAINER_APP_CERTIFICATE_NAME} \
      --password ${PFX_PASSWORD}
```

The error is:
```
Certificate must contain one private key.
```

However, I can upload manually in the portal.azure.com without an issue:

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/2172012/178083444-1f78cecd-8486-426b-8fa3-59e499eb5f74.png">

I looked at the pfx file using Mac Keychain Access and it looks like it has a private key with an intermediate key:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/2172012/178083509-6d9451b4-c7d1-4630-96b1-424309124453.png">

### Steps to reproduct

See above

**Expected behavior** 

The `az containerapp env certificate upload` command should succeed.

**Actual behavior**

I get this error: `Certificate must contain one private key.`

**Comment by StrawnSC** [comment]
@lil131 can you take a look at this? Thanks

**Comment by Mathijs-Dijk** [comment]
after support from microsoft what helped in my case was adding the certificate (pfx) on the local machine (with mmc). After this the upload worked. 

I had the exact same issues as in this thread (cli => "must contain one private key", portal => "password not correct"

**Comment by lil131** [comment]
@Mathijs-Dijk thanks for reporting your case. Were you using a certificate obtained from LetsEncrypt as well?

**Comment by tmcgannon** [comment]
@Mathijs-Dijk Regarding:

> adding the certificate (pfx) on the local machine (with mmc). 

How did you add the certificate? What commands were used?  Did the pfx get changed during the process?

**Comment by panchagnula** [comment]
@tmcgannon are you still able to repro this only on CLI & not on portal. If so would you be willing to run the CLI command with --debug & share the details, after removing some PII info or send an email to us directly with the details? We can share our email address to send the debug info to. Thanks!

**Comment by Mathijs-Dijk** [comment]
@tmxgannon
I work on a Windows machine as developer. I used MMC to add the certificate on my local machine.

@lil131 no our certificate is from Sectigo. But I think this issue occurs with all third party certificates. As I mentioned, after adding the certificate to my local machine it worked. * Only downside is that I cannot upload it a.t.m. through Bicep in our release pipeline on Azure.

**Comment by panchagnula** [comment]
> @tmxgannon I work on a Windows machine as developer. I used MMC to add the certificate on my local machine.
> 
> @lil131 no our certificate is from Sectigo. But I think this issue occurs with all third party certificates for Azure Container Apps. We had no problems uploading the certificate in KeyVault and App Services with the exact same certificate.. As I mentioned, after adding the certificate to my local machine it worked. * Only downside is that I cannot upload it a.t.m. through Bicep in our release pipeline on Azure.

@vinisoto / @anthonychu , @tmcgannon 's issue doesn't seem be client specific, could you help here? Thanks!

**Comment by vinisoto** [comment]
Would like to hear from @tmcgannon: to confirm if the issue is still reproducible only on CLI but not on Portal

**Comment by tmcgannon** [comment]
@vinisoto @panchagnula It still does not work and shows this message:

![image](https://user-images.githubusercontent.com/2172012/180582891-425685e6-6b07-40d6-87f1-051ceb7a1e40.png)

**Comment by kendallroden** [comment]
@vinisoto do we know the status of this issue?

**Comment by tmcgannon** [comment]
@kendallroden As of today, this is still a problem for me.

**Comment by panchagnula** [comment]
> @kendallroden As of today, this is still a problem for me.

@tmcgannon sorry to hear this - have you checked this with the latest version of ACA CLI 0.3.11? You can check using az --version & do update to latest using [ az upgrade](https://github.com/microsoft/azure-container-apps/issues/305#issuecomment-1260184299)

**Comment by tmcgannon** [comment]
@panchagnula I upgraded to 0.3.11 (from 0.3.9) and it worked.  Thank you
