### ISSUE TITLE
Upload of valid PEM certificate + key file throws error citing missing private key

### ISSUE THREAD

**Issue by bbi-willemtoorenburgh** [microsoft/azure-container-apps#307]
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
When trying to upload a PEM-encoded certificate + private key file, which I have verified is valid, both the Azure portal and API throw an error:
```
Failed to add new private key certificate: <cert name>. Certificate must contain one private key.
```
To troubleshoot, I tried:
* Uploading a bundle which had successfully uploaded in the past - same error
* Uploading the bundle without the private key - same error
* Uploading a bundle without the full chain - same error
* Uploading specifying a different friendly name - same error

I suspect this is a regression, as I have successfully uploaded these certificates as recently as three weeks ago.

### Steps to reproduct
1. Establish a Container Apps Environment in the Portal
2. Attempt to upload a PEM-encoded certificate and key bundle
3. Observe the error returned in the Portal

**Expected behavior** [What you expected to happen.]
The certificate is uploaded successfully and is made available to the Apps inside the Environment.

**Actual behavior** [What actually happened.]
The error described above, which did not previously happen.

**Screenshots**         
n/a

### Additional context
This is a Let's Encrypt certificate obtained via CertBot. I have previously successfully uploaded a Let's Encrypt certificate to Container Apps, which makes me suspect this is a regression. I am using the [Pulumi](https://www.pulumi.com/) infrastructure-as-code tool, with the [Azure Native](https://www.pulumi.com/registry/packages/azure-native/) provider, creating a [Certificate](https://www.pulumi.com/registry/packages/azure-native/api-docs/app/certificate/) resource. All of this worked in the past. Additionally, because of the Pulumi workflow, I am locked in to using PEM certificate bundles, as the only upload method I can currently use only supports text.

**Comment by torosent** [comment]
Hi, you need to convert your cert `openssl pkcs12 -inkey cert.key -in cert.pem -export -out output.pem`. We will update the docs. @craigshoemaker

**Comment by bbi-willemtoorenburgh** [comment]
Thanks for the update, @torosent . Does this mean that Container Apps is dropping support for text-encoded PEM files?

**Comment by torosent** [comment]
No. It's not supported yet but it's in our backlog.

**Comment by bbi-willemtoorenburgh** [comment]
You're certain it's not supported? I was successfully uploading text-encoded PEM files just a few weeks ago, and the Azure portal was recognizing them correctly.

**Comment by bbi-willemtoorenburgh** [comment]
Further, when I tried uploading the certificate after processing it using `openssl pkcs12 -inkey cert.key -in cert.pem -export -out output.pem` as you suggested, the Azure Portal rejected it as invalid with the message:
```
Failed to add new private key certificate: <cert name>. The certificate <cert name> is invalid or password is incorrect.
```

**Comment by torosent** [comment]
@vinisoto , can you confirm please?

**Comment by bbi-willemtoorenburgh** [comment]
Hey @vinisoto , thanks for the suggestion. Sadly, the CLI also rejects the certificate with the same `Certificate must contain one private key.` message. I suspected this would be the case, as the AzureRM API is giving the same message when Pulumi tries to upload the certificate

**Comment by bbi-willemtoorenburgh** [comment]
Seeing as this error is consistent across the Portal, CLI, and API, and I have made sure the certificate and key are valid, I'd speculate that it suggests that Container Apps' cert verification mechanism is the source of the regression. Please let me know if there's anything else I can provide to help troubleshoot :)

**Comment by vinisoto** [comment]
This validation was recently added. I'm checking internally and will get back to you soon.

**Comment by ahmelsayed** [comment]
Hi @bbi-willemtoorenburgh

The pfx file you're uploading, if you read it with openssl 

```bash
$ openssl pkcs12 -in output.pfx -nodes
```

how many `-----BEGIN CERTIFICATE-----` and `-----BEGIN PRIVATE KEY-----` do you see in it? You can have multiple certificates for the chain, but only one private key and its corresponding public cert. 

The key must be either an RSA key with minimum length of 2048, or a P256 ECDSA key.

**Comment by benc-uk** [comment]
[The docs page](https://github.com/microsoft/azure-container-apps/issues/239), has no mention of PEM not being a supported format. Given PEM is a lot more common than PFX as it's the format output by most OpenSSL tools, I expect many customers to trip over this. I also encountered this problem on #239

**Comment by bbi-willemtoorenburgh** [comment]
Hey @ahmelsayed , thank you for the response. I can confirm that the PEM cert bundle has multiple `-----BEGIN CERTIFICATE-----` lines for the main cert and the chain, and one `-----BEGIN PRIVATE KEY-----`.

@benc-uk , thanks for weighing in. The reason I was trying to use a PEM cert was that in the [Pulumi provider docs for Container Apps](https://www.pulumi.com/registry/packages/azure-native/api-docs/app/certificate/#certificateproperties), it mentions both PFX and PEM. My understanding is that those docs are auto-generated, along with the actual code for the provider, by a tool of theirs which consumes the API spec for Azure. I believe this means that the description for the certificate resource, which mentions PFX and PEM, comes from Azure's own API docs. Indeed, it's [in the CLI docs](https://docs.microsoft.com/en-us/cli/azure/containerapp/env/certificate?view=azure-cli-latest#az-containerapp-env-certificate-upload-required-parameters).

**Comment by vinisoto** [comment]
@bbi-willemtoorenburgh I have tagged this a bug. Although we will work to support PEM shortly, for now we should change the documentation to specify that Container Apps only supports PFX.

**Comment by benc-uk** [comment]
@bbi-willemtoorenburgh Good spot! It turns out the API specs for ManagedEnvironments states that PEM is accepted, perhaps it was added to the spec, but the feature support slipped. Oh well it happens 🤷 

https://github.com/Azure/azure-rest-api-specs/blob/37966a6de2451407408adc2da5ab25631f0dd9b9/specification/app/resource-manager/Microsoft.App/stable/2022-03-01/ManagedEnvironments.json#L889

**Comment by bbi-willemtoorenburgh** [comment]
Thanks @vinisoto . For the time being, I'm trying to upload a PFX version of my cert bundle, and both the Portal and the API are saying the bundle is invalid. Has anyone had any success uploading any certificates?

**Comment by bbi-willemtoorenburgh** [comment]
I suppose it's also worth noting that the Portal also does mention support for both PEM and PFX
![image](https://user-images.githubusercontent.com/91083185/181105187-c9a76a22-5f40-41f6-910d-1a43fb2e68f8.png)

**Comment by StevKast** [comment]
I have had no luck and facing the same issue. PEM and PFX giving the same errors as @bbi-willemtoorenburgh

**Comment by ThorstenSauter** [comment]
I've encountered the same issues when trying to upload a certificate from LetsEncrypt. I generated the PFX including the full chain, but neither the Portal nor the CLI would accept it. The portal failed with the following error message:

![image](https://user-images.githubusercontent.com/43311536/182027218-fa4c1c12-e978-47dd-8dbe-48b457b16dde.png)

and the Azure CLI failed with `Certificate must contain one private key.`.

I've found the following workaround to be successful:
1. Import the PFX file as a certificate into Azure Key Vault
2. Export the certificate in "PFX/PEM Format"
3. Upload this certificate to the Azure Container Apps Environment
4. Assign the custom domain using the certificate

Interestingly, this downloaded certificate file only contains the certificate and the private key with the intermediate certs only being mentioned as the issuer, as can be seen when running `openssl pkcs12 -in cert.pfx -nodes`:

```
Bag Attributes
    localKeyID: 01 00 00 00
    friendlyName: {002BDB3F-F8DC-4775-92BE-D10EFF7F7E9B}
    Microsoft CSP Name: Microsoft Enhanced Cryptographic Provider v1.0
Key Attributes
    X509v3 Key Usage: 10
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
Bag Attributes
    localKeyID: 01 00 00 00
subject=CN = my.domain.example
issuer=C = US, O = Let's Encrypt, CN = R3
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

**Comment by vinisoto** [comment]
We have added support for PEM certificates. The rollout has begun and will be available in all supported regions by 8/18

**Comment by bbi-willemtoorenburgh** [comment]
Hey @vinisoto ! I'm happy to confirm that certificates are uploading successfully! I have been unable to test their functionality due to a new regression in secret management, but I'll make a new issue for that.

**Comment by cschar** [comment]
for anyone who wants to skip using the az keyvault export as pfx/pem as described above:

> I've found the following workaround to be successful:
> Import the PFX file as a certificate into Azure Key Vault
> Export the certificate in "PFX/PEM Format"
> Upload this certificate to the Azure Container Apps Environment
> Assign the custom domain using the certificate


I wanted to automate it fully on CLI so had been trying 'openssl' tool, eventually got it working using an alternate 'step' cli tool.

```
# create a 90 day certificate
step certificate create test1.my.domain.net steptest1.crt steptest1.key --profile self-signed --subtle \
  --kty RSA --size 4096 \
  --san test1.my.domain.net \
  --not-after 2160h \
  --insecure --no-password

# package the crt and key together as a PFX/PKCS12 file 
step certificate p12 test1.p12 steptest1.crt steptest1.key \
  --insecure --no-password 

# az cli accepts only .pfx or .pem
cp test1.p12 test1.pfx 

# add to cae
az containerapp env certificate upload -g my-cae-rg --name my-cae \
                                       --certificate-file ./test1.pfx \
                                       --certificate-name my-test1-90day-cert


# then cert will be available for binding to container apps at test1.my.domain.net

```

**Comment by fardarter** [comment]
Leaving this here for anyone searching for why their PEM file upload is invalid on azure cli because it cost me 2 hours yesterday.

Despite containing newlines being the spec compliant format, you need it in a single line format to get the upload working from cli:

`./intermediate-ca.crt | tr -d '\n' > ./intermediate-ca-formatted.crt`

```sh
az eventgrid namespace ca-certificate create \
         --resource-group rg-name \
         --namespace-name ns-name \
         -n intermediate-ca \
         --certificate  ./intermediate-ca-formatted.crt
```

I imagine that whatever is happening here would use similar verification/parsing code.
