### ISSUE TITLE
Regression: environment variables can no longer contain a dot

### ISSUE THREAD

**Issue by gerwim** [microsoft/azure-container-apps#308]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
We have an environment variable as such:
`SolutionName.Feature` however, the dot `.` is no longer allowed (last week it still was allowed).

### Steps to reproduce
1. Set environment variable with dot

**Expected behavior** [What you expected to happen.]
The dot should be allowed. The allowed character range should be less strict.

**Actual behavior** [What actually happened.]
Error:
```
Env variable name 'SolutionName.Feature' contains invalid character, allowed characters are 'a-z, A-Z, 0-9 and _'
```

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
Both. Even our CI/CD deployments broke because of this change.

**Comment by Cavorter** [comment]
We are seeing the same problem. Our last CD run at 7/8/2022 8:08:00 PM UTC worked fine, but the next run at 7/12/2022 4:35:00 PM UTC failed so the change happened somewhere between those two timestamps.

**Comment by evklein** [comment]
Same here, my CD failed as well. I store my database connection string in an Azure secret that gets injected into the Container. I haven't deployed in several days, and I have no changes that would upset the Azure deployment process.

**Comment by gerwim** [comment]
Can confirm, environment variables containing a dot are working again. Thank you!

**Comment by CdTgr** [comment]
I know its an old issue, also closed. but @mjqin I am facing this issue on container deployment. Did something change?
