### ISSUE TITLE
Allow Container App to support http endpoint

### ISSUE THREAD

**Issue by szavoda** [microsoft/azure-container-apps#310]
When hosting a container app in Azure Api Management, the call to the backend is done with a http call (no SSL).  However, since the container app is only accepting https, the call response is a 301 redirect with the location pointing to the secure URL.

This is problematic on many levels including performance as well as issues with the authentication headers not automatically added to the redirect.

In theory, this problem could be addressed on either side:  the container app allows non-SSL communication or the API Management allows configuration of the outgoing protocol.  Unfortunately, I have not been able to identify how to accomplish either, so I figured I would start here...

**Comment by ahmelsayed** [comment]
you can set `allowInsecure: true` on the ingress to disable auto redirect to https

https://docs.microsoft.com/en-us/azure/container-apps/ingress?tabs=bash#configuration
