### ISSUE TITLE
Feature Request: Add "force" option to Update / Revision

### ISSUE THREAD

**Issue by szavoda** [microsoft/azure-container-apps#312]
**Is your feature request related to a problem? Please describe**.  

Currently, a container app revision cannot be made unless there is a change to the underlying template.  This becomes a problem when you have a change in the underlying docker image but nothing else changes.  In this case, a "az containerapp update" (or "New Revision" in portal) will not actually create a new revision despite the success result.

**Describe the solution you'd like**.    

Either make a new revision regardless of the detection of changes to the template when the command is given or add a "--force" option to make it happen.

**Describe alternatives you've considered**.   

As a work around, I have added the "--revision-suffix" to the az containerapp update CLI command and assigned it the value of my build number in the release pipeline.  This change to the template will result in a new revision.

**Additional context**.  

As mentioned, this issue can be recreated either in the az containerapp update cli command or within the portal when trying to create  a "New Revision" for the container app.

**Comment by anthonychu** [comment]
Related #311

**Comment by anthonychu** [comment]
Added to CLI backlog to discuss. /cc @panchagnula

**Comment by szavoda** [comment]
Given the info in #311 I don't think this feature request is needed.
