### ISSUE TITLE
Feature Request: Document when/if support of Azure China Cloud is planned

### ISSUE THREAD

**Issue by quality-leftovers** [microsoft/azure-container-apps#313]
**Is your feature request related to a problem? Please describe**.  
There is no roadmap / information regarding support of azure container apps  in China

**Describe the solution you'd like**.    
Please provide an outlook on support of azure container apps in China

**Describe alternatives you've considered**.   
n.a.

**Additional context**.  
n.a.

**Comment by torosent** [comment]
China cloud is on our roadmap and planned for Q4 2022

**Comment by vc2023** [comment]
Hello,
Is there any progress regarding container apps in China?
Thank you.

**Comment by alex-graf** [comment]
We also need container apps in China! Can you give us the current status? We must soon decide which way to go.
Thanks!

**Comment by vc2023** [comment]
Hello again.
I just wanted to ask again if you plan to support container apps in China in near future.
Thank you.

**Comment by simonjj** [comment]
This is done now 🎉
