### ISSUE TITLE
Creation of managed environment fails via SDK

### ISSUE THREAD

**Issue by k-krupka** [microsoft/azure-container-apps#314]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am using the preview version of the Resource Management SDK to create Azure Container Apps resource. When I try to create a managed environment, I have to provide the Log Analytics workspace. Even when I do so, the creation still fails.

### Steps to reproduct
1. Start with empty resource group, where you wanna create an environment, empty, no container apps yet.
2. Use the SDK in your c# example: 
3. `<PackageReference Include="Azure.ResourceManager.Applications.Containers" Version="1.0.0-beta.1" />`
4. The try to execute the following source code:
```
    [TestMethod]
    public async Task A_DeployManagedEnvironment()
    {
        SubscriptionResource subscription = await _armClient.GetSubscriptions().GetAsync(_subscriptionId.ToString(), cancellationToken);
        ResourceGroupResource resourceGroup = await subscription.GetResourceGroups().GetAsync(_resourceGroupName, cancellationToken);

        ManagedEnvironmentCollection managedEnvironmentCollection = resourceGroup.GetManagedEnvironments();

        ManagedEnvironmentData managedEnvironmentData = new ManagedEnvironmentData(_location)
        {
            DaprAIInstrumentationKey = null,
            DaprAIConnectionString = null,
            AppLogsConfiguration = new AppLogsConfiguration
            {
                Destination = "log-analytics",
                LogAnalyticsConfiguration = new LogAnalyticsConfiguration
                {
                    CustomerId = _logAnalyticsCustomerId,   // NOTE: This is the value I've got from the LogAnalytics resource.
                    SharedKey = null
                },
            },
            ZoneRedundant = false,
            Location = _location,
            Tags = { },
        };
        await managedEnvironmentCollection.CreateOrUpdateAsync(WaitUntil.Completed, _managedEnvironmentName, managedEnvironmentData, cancellationToken);

    }
```
5. Exception occurs:
```
Test method Class1.A_DeployManagedEnvironment threw exception: 
Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Content:
{"code":"InvalidRequestParameterWithDetails","message":"LogAnalyticsConfiguration is invalid.  Must provide a valid LogAnalyticsConfiguration"}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-ratelimit-remaining-subscription-resource-requests: REDACTED
api-supported-versions: REDACTED
Server: Microsoft-IIS/10.0
X-Powered-By: REDACTED
x-ms-request-id: 8a9bb00b-ca13-4e9b-a813-0acef0ce68d6
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Fri, 15 Jul 2022 04:39:39 GMT
Content-Length: 143
Content-Type: application/json; charset=utf-8
Expires: -1
```

**Expected behavior**
No exception is thrown and "empty" Container App environment is created.

**Actual behavior** [What actually happened.]
Exception which says that configuration is invalid.

**Screenshots**         
n/a

### Additional context
The SDK works super nice, we managed to make it work for all our use cases so far except the creation of the Managed Environment. Frankly, when you create an environment via Azure Portal, then debug the code, you see which properties in the SDK are filled in, example of existing environment:
![image](https://user-images.githubusercontent.com/20299573/179152686-0478d59e-6fc4-4f06-bb7e-1477156f6671.png)
On the screenshot you see that the only parameter available for the Log Analytics Configuration is the CustomerId.

**Comment by k-krupka** [comment]
Hi @vturecek ,
No, I am not providing the SharedKey, only the CustomerId.
Should I be providing both?

**Comment by ruslany** [comment]
Hi @k-krupka - yes, the SharedKey is required.
