### ISSUE TITLE
Feature Request: Support Application metrics capture from endpoint

### ISSUE THREAD

**Issue by san360** [microsoft/azure-container-apps#316]
**Is your feature request related to a problem? Please describe**.  
Support application metrics capture from container app via specified endpoint similar to AKS with OMS agent

**Describe the solution you'd like**.    
Configuration of metric endpoint and port

**Describe alternatives you've considered**.   
Publishing metrics to stdout

**Additional context**.  
N.A

**Comment by torosent** [comment]
We are exposing our metrics through Azure Monitor? do mean adding the option to send custom metrics?
