### ISSUE TITLE
Feature Request: Tunneling of outbound Traffic via NVA/Firewall

### ISSUE THREAD

**Issue by san360** [microsoft/azure-container-apps#318]
**Is your feature request related to a problem? Please describe**.  
Tunneling of outbound Traffic via NVA/Firewall

**Describe the solution you'd like**.    
Tunneling of outbound Traffic via NVA/Firewall

**Describe alternatives you've considered**.   
N.A

**Additional context**.  
N.A

**Comment by torosent** [comment]
Our our roadmap for Q4 2022.

**Comment by snobu** [comment]
Please consider NAT Gateway as one of the outbound options, for applications that need a lot of outbound SNAT translations.

**Comment by kendallroden** [comment]
Support ETA: Q1 2023

**Comment by labyrinthinesecurity** [comment]
Injecting ACA into a customer Vnet shouldn’t cause UDRs to be ignored. We need UDRs support to route egress through Azure Firewall.

**Comment by chinadragon0515** [comment]
refer to https://github.com/microsoft/azure-container-apps/issues/227 for newest update

**Comment by chinadragon0515** [comment]
refer to https://github.com/microsoft/azure-container-apps/issues/227 for newest update

**Comment by yansyunchen** [comment]
Hi, Would like to know how about if I'm not route the all traffic to NVA (firewall) and just set the UDR for 10.0.0.0/8 -> NVA (firewall). Is that possible?
