### ISSUE TITLE
Feature Request: Secret management with Azure Keyvault

### ISSUE THREAD

**Issue by san360** [microsoft/azure-container-apps#319]
**Is your feature request related to a problem? Please describe**.  
ACA does not support secret management with AZ Keyvault

**Describe the solution you'd like**.    
ACA having native integration with Azure keyvault via Managed Identity

**Describe alternatives you've considered**.   
Deploy time injection of secrets from CI/CD

**Additional context**.  
N.A

**Comment by anrub** [comment]
I hope it will be possible to manage custom TLS certificates via keyvault, just like in application gateway.
