### ISSUE TITLE
Feature Request: VNET Peering to the Managed VNET

### ISSUE THREAD

**Issue by omni-htg** [microsoft/azure-container-apps#320]
**Is your feature request related to a problem? Please describe**.  
I would like to consult on and / or request the posibility to Peer a VNET to the managed self-provided VNET created by an ACA Environment.

**Describe the solution you'd like**.    
Being able to peer into the VNET should allow for it to do its managed stuff while allowing easy interaction with other VNETs and services.
For example, if I have a set of microservices bundled together and do not care about their vnet / environment for no other reason besides protecting their front-facing interactions or allowing them to communicate with other services that are hosted on their own vnets.

**Describe alternatives you've considered**.   
My current understanding is that, for example, in order to provision an Application Gateway in front of an ACA Environment, my only choice is to provide a Custom VNET with an Internal Environment. Even in that case, I'm not entirely sure it'll work as it might depend on the same principles as [why a Firewall is still not supported](https://docs.microsoft.com/en-us/azure/container-apps/firewall-integration):

> Using custom user-defined routes (UDRs) or ExpressRoutes, other than with UDRs of selected destinations that you own, are not yet supported for Container App Environments with VNETs. Therefore, securing a Container App Environment with a firewall is not yet supported.

Clarification and correction on this is greatly appreciated :)

**Additional context**.  
As of today, I seem to remember that further documentation on how an External Managed Environment is secured is being worked on -- so for now, directly exposing the external ingress endpoint without any other protections (ie AG, AFD, NSGs, Firewall, etc) might not be the best choice for us.
Regardless of the interest or usefulness of the request itself, I'd be more than welcome to recieve guidance or opinion on this.
Thanks!

EDIT: Might be related #318

**Comment by sioakim** [comment]
@kendallroden Can you please validate if VNET peering is supported or not?
It seems that when I enable it my App Environment is not responding and application's don't start up.
Disabling it brings back the functionality.

I need VNET peering as my container app is calling some internal services that are not on the same VNET and some are on-premises. Pretty much I'm trying to peer to my Hub spoke.

If this is not supported what is currently the alternative for a container app to talk to other internal services?

In my case, I'm using External Endpoint for simplicity with Internal VNET.

**Comment by cachai2** [comment]
VNet peering is supported for custom VNets. This is not something we plan to support for non-custom VNets.
