### ISSUE TITLE
Feature Request: Support for Container Apps in Application Gateway

### ISSUE THREAD

**Issue by jamie-magenta** [microsoft/azure-container-apps#322]
**Is your feature request related to a problem? Please describe**.  
Yes, it's related to a problem: Currently, every few deployments, the certificate of the generated `.azurecontainerapps.io` domain seems to change and makes our backend unavailable until we update the certificates manually inside the gateway backend settings. I don't know if this is a bug, but it's causing a downtime of our application.

**Describe the solution you'd like**.    
Something like an option for App Services in the Application Gateway Backend Settings (see Additional Context for a screenshot).

**Describe alternatives you've considered**.   
/

**Additional context**.  
![image](https://user-images.githubusercontent.com/84012740/179673267-bdd7b4d9-f973-40bc-b282-cfff5bb0de53.png)

**Comment by jamie-magenta** [comment]
Update: I just tried to activate "Use for App service" and now our backend is healthy again, so this seems to work although we're using Container Apps. I'm closing this issue.

**Comment by luissalgadofreire** [comment]
Hi, @jamie-magenta. I'm trying to do the same. Just a quick question, hoping that you can help. How did you get the public certificate of the default container app domain? Or did you add a new certificate for that domain to the container app environment?

**Comment by luissalgadofreire** [comment]
Sorry, just read it with more attention. I'm using terraform and it doesn't seem that the option 'Use for App service' is available to copy the backend public certificate to the application gateway.
