### ISSUE TITLE
Quotas

### ISSUE THREAD

**Issue by spyroskaravanis** [microsoft/azure-container-apps#323]
It is not clear which are the actual quotas. Although it is stated that cpu is up to 20, we are able to create a container app of 2 cpu that scales to 30. Also it would be nice to know what  your plans are in terms of scaling. Will the limit of 20 cpu be increased in the near future?

**Comment by torosent** [comment]
We are working to increase the quotas. In the meantime, you can open a support ticket to increase the quotas.

**Comment by onionhammer** [comment]
Watching / waiting for this one.. quotas are the last big limitation for us to start transitioning from app service

**Comment by onionhammer** [comment]
Bump

**Comment by spyroskaravanis** [comment]
I have increased my quotas. Thanks for your time.

**Comment by ArneDeProft** [comment]
> We are working to increase the quotas. In the meantime, you can open a support ticket to increase the quotas.

Where would we land in terms of quota? Because it's a question I am getting quite often.
