### ISSUE TITLE
Vnet only on internal network

### ISSUE THREAD

**Issue by spyroskaravanis** [microsoft/azure-container-apps#324]
My application consists of 25 microservices. I have 4 environments for scaling due to app and cpu limitation. I have created a VNET which I have connected with every environment. There is no way, that I know, in which I can internally connect microservices from different environments. It would be nice if we could have a VNET URL in the container app as we have internal URL within the cluster.

**Comment by torosent** [comment]
The solution here is to increase the quotas for one env so all the apps will be deployed in it. You can open a support ticket and we will increase the quotas for you. cores, number of apps, replicas, etc...

**Comment by spyroskaravanis** [comment]
I have increased my quotas. Thanks for your time.
