### ISSUE TITLE
Revision failed on provisioning, ContainerCrashing error

### ISSUE THREAD

**Issue by adeliab** [microsoft/azure-container-apps#326]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Created a revision using an image from ACR. Provisioning of revision failed, ContainerAppSystemLogs_CL shows ContainerCrashing error.

### Steps to reproduct
1. Created a new .NET Core API project in Visual Studio 2022 with Docker Support enabled (almost no changes to the default template code, only added 1 extra API that returns a string)
2. Published image to ACR from Visual Studio (release mode)
3. Created container app with hello world image
4. Deployed new revision using the deployed image in ACR, added environment variable ASPNETCORE_URLS=https://+:443;http://+:80
5. Provisioning failed

**Expected behavior** [What you expected to happen.]
The provisioning should be successful and application is running

**Actual behavior** [What actually happened.]
Provisioning failed with ContainerCrashing

**Screenshots**         
-

### Additional context
Issue happened in the Portal

**Comment by anthonychu** [comment]
I think the issue is `ASPNETCORE_URLS`. Because it includes `https://+:443`, HTTPS is enabled in the ASP.NET Core app. TLS is terminated at the ingress, the app container doesn't need HTTPS enabled. In ASP.NET Core, the app redirects HTTP requests on port 80 to HTTPS when an HTTPS URL is enabled. The solution is to remove the `ASPNETCORE_URLS` variable (it should already be set to `http://+:80` by default in the ASP.NET Core base image). 

@BigMorty Is there anything that can be added to the VS tooling to guard against this issue?

**Comment by adeliab** [comment]
@anthonychu the first time I deployed it, I didn't see the env variable and it crashed as well. But your comment pointed me to the fix, I removed `app.UseHttpsRedirection();` in Program.cs and it is provisioned now.

**Comment by adeliab** [comment]
Is it not possible to delete inactive revision/ container?

**Comment by adeliab** [comment]
Ok, apparently the issue is because of the Ingress target port was set to 443. Once I set it to 80, it works

**Comment by BigMorty** [comment]
Yes, this is a common error we see where the Ingress port on the app does not match the port your container is running on. We are discussing if we can detect this in advance.

Regarding deleting inactive revisions, no you cannot today. We are also looking into something in this area. Today you need to delete the app and redeploy a new one.
