### ISSUE TITLE
Best networking resource for URL based routing to different container apps

### ISSUE THREAD

**Issue by adeliab** [microsoft/azure-container-apps#327]
I plan on deploying multiple internal APIs as container apps. These APIs will be triggered by a service bus subscription, HTTP call or event grid web hook.

I want to have 1 domain for these APIs and use URL based routing to map the requests to the right container app. The consumer of these APIs will be a public facing API.
What would be the best networking resource for this?

Currently I'm leaning towards application gateway, but it seems like some of the features of application gateway are already supported by container app itself. Like TLS termination, HTTPS redirect, health probes. Is there a better option for this?

With TLS termination on the application gateway, would HTTP requests from the application gateway be redirected to HTTPS by container app?

If I create an internal container app environment which is only accessible through vnet, is there a way to test the deployed app from my browser? Maybe an IP exception?

**Comment by kendallroden** [comment]
We are investigating this feature!

**Comment by cachai2** [comment]
@adeliab we've recently released a blog post on how path-based routing can be achieved in Azure Container Apps today by using an nginx container as a reverse proxy. Would love to hear your feedback if this covers your scenarios and if not what is missing from the experience and what you would like to see.

Blog post: [https://techcommunity.microsoft.com/t5/apps-on-azure-blog/path-and-hostname-based-routing-in-azure-container-apps-with/ba-p/4068923](url)

**Comment by simonjj** [comment]
Closing this. Please use #591 going forward for additional comments or questions.
