### ISSUE TITLE
Feature Request: support `watch` as container entry point

### ISSUE THREAD

**Issue by masters3d** [microsoft/azure-container-apps#328]
**Is your feature request related to a problem? Please describe**.  
A clear and concise description of what the problem is

"Error opening terminal: unknown." and failing a revision.
Image
![image](https://user-images.githubusercontent.com/6539412/181114246-80c0758e-74ad-4a0c-b208-5c02bcc890ce.png)

Chéyo Jiménez @masters3d — Yesterday at 8:48 PM
Seems like the watch program is throwing off ACA since the same ACI works fine.

**Describe the solution you'd like**.    
A clear and concise description of what you want to happen, any scenarios it will unblock, etc.  

not to error. 

**Describe alternatives you've considered**.   

I switched to using while loop in bash. 

**Additional context**.  

the `watch` version works fine in ACI groups

**Comment by ahmelsayed** [comment]
You'll need to set `TERM` env var. The default ubuntu image doesn't define a terminal type, and we don't set one by default either. Try adding an env var `TERM=xterm` to your image or app.

**Comment by masters3d** [comment]
I saw the same issue with Alpine. Give it a try with watch. The env var is set.
