### ISSUE TITLE
"Certificate doesn't exist" when trying to create a new revision

### ISSUE THREAD

**Issue by AliMirlou** [microsoft/azure-container-apps#333]
### This issue is a:
- [x] bug report
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The error:
```
Certificate '/subscriptions/97e6785f-b82b-48b5-8a66-6844aa792173/resourceGroups/rg-ratior/providers/Microsoft.App/managedEnvironments/managedEnvironment-rgratior-bf97/certificates/' doesn't exist
```
is suddenly showing up when trying to update a container app and creating a new revision. Both with the Azure Portal and the Azure CLI.
This procedure was working fine in our CI/CD pipelines a week ago, without anyone changing anything!

I checked the certificate in the Container Apps Environment. There was nothing wrong with it and no one has changed anything.

### Steps to reproduct
1. Ran the following command: `az containerapp update --name ratior-frontend-production --resource-group rg-ratior --image crdevonso.azurecr.io/ratior-frontend-production:2196`

**Expected behavior** [What you expected to happen.]
I expected to see a new revision created and my service updated.

**Actual behavior** [What actually happened.]
The above mentioned error is printed in the console.

**Screenshots**
Also tested with the Azure Portal and the same error showed up:

![image](https://user-images.githubusercontent.com/19661419/182192067-57ca039e-03a0-48f1-9ed0-816d5e37d974.png)

**Comment by AliMirlou** [comment]
This is happening for all of our current container apps that are inside the mentioned Container Apps Environment, but not for the new container apps that are created inside it.

**Comment by vinisoto** [comment]
@AliMirlou we have identified a bug. We will be preparing a fix and deploying it shortly. Thank you for reporting this

**Comment by AliMirlou** [comment]
The bug seems to have been fixed. Thanks and I'll close the issue.

**Comment by mike-wood-sibylline** [comment]
I suggest this bug has returned. Same error just now whilst I can see the valid certificate within the portal.
