### ISSUE TITLE
Error creating Container Apps Environment in Pulumi with Log Analytics in different subscription

### ISSUE THREAD

**Issue by PhilBroderick** [microsoft/azure-container-apps#334]
### This issue is a:
- [ ] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The error seen in the pulumi logs:
```
Code="OperationFailed" Message="ErrorCode: ManagedEnvironmentProvisioningError, Message: Fail to create managed environment because creation of the managed cluster failed, please retry later."
```

Although the Container Apps environment resource has been created in Azure, when I attempt to manually create a Container App, I receive the following error: 
![image](https://user-images.githubusercontent.com/33251762/182385475-33ba04eb-3781-4bee-8ea1-1bf65a93ed90.png)

I tried to re-create the container app environment manually in the portal, and this step leads me to believe I can only use a log analytics in the same subscription:
![image](https://user-images.githubusercontent.com/33251762/182386083-3d034d3c-c4a8-4b8b-a3c3-3e2ecc6f15e8.png)

Is this correct? I wanted to have a central log analytics workspace in a different subscription that would store logs for various resources, but this doesn't look like the case for Container Apps?

### Steps to reproduct
1. Create a Container App Environment with Pulumi and a Log Analytics workspace in a different subscription

**Expected behavior** [What you expected to happen.]
I expected to be able to create a Container Apps environment with a Log Analytics workspace in another subscription.

**Actual behavior** [What actually happened.]
I was unable to do so. The Container Apps Environment resource was partially deployed, but it an errored state, so could do nothing with it.

### Additional context
This occurred through Pulumi, with a central log analytics workspace previously defined and being referenced when creating the Container Apps Environment using the following resource: https://www.pulumi.com/registry/packages/azure-native/api-docs/app/managedenvironment/

**Comment by dgcaron** [comment]
i am actually running into the same error with a bicep file that worked previously:

```
@description('The name of the log analytics workspace resource')
param name string

@description('The location in which the resource is deployed')
param location string = resourceGroup().location

@description('Object containing the tags to apply to all resources')
param commonTags object = {}

@description('The name of the log analytics workspace')
param logAanalyticsName string

@description('The resource ID for the control plane subnet')
param infrastructureSubnetId string

@description('The resource ID for the runtime subnet')
param runtimeSubnetId string

resource loganalytics 'Microsoft.OperationalInsights/workspaces@2021-12-01-preview' existing = {
  name: logAanalyticsName
}

resource containerAppEnv 'Microsoft.App/managedEnvironments@2022-01-01-preview' = {
  name: name
  location: location
  tags: commonTags
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: loganalytics.properties.customerId
        sharedKey: loganalytics.listKeys().primarySharedKey
      }
    }
    vnetConfiguration: {
      internal: true
      infrastructureSubnetId: infrastructureSubnetId
      runtimeSubnetId: runtimeSubnetId
    }
  }
}
```

**Comment by torosent** [comment]
Can you send the subscriptions id and env name to `acasupport@microsoft.com`?

**Comment by kasper090288** [comment]
@torosent any thoughts on this issue?

I receive same error as well:
`
Code="OperationFailed" Message="ErrorCode: ManagedEnvironmentProvisioningError, Message: Fail to create managed environment because creation of the managed cluster failed, please retry later."
`

The error is received, when deploying following ARM template. Resource is deployed to same subscription and resource group as resource Microsoft.OperationalInsights/workspaces.

```json
{
	"apiVersion": "2022-03-01",
	"dependsOn": [
		"[resourceId('Microsoft.OperationalInsights/workspaces', 'log-analytics')]"
	],
	"location": "westeurope",
	"name": "container-environment-dft",
	"properties": {
		"appLogsConfiguration": {
			"destination": "log-analytics",
			"logAnalyticsConfiguration": {
				"customerId": "[reference(resourceId('Microsoft.OperationalInsights/workspaces', 'log-analytics'), '2021-12-01-preview').customerId]",
				"sharedKey": "[listkeys(resourceId('Microsoft.OperationalInsights/workspaces', 'log-analytics'), '2021-12-01-preview').primarySharedKey]"
			}
		},
		"vnetConfiguration": {
			"infrastructureSubnetId": "[concat(resourceId('rg-all', 'Microsoft.Network/virtualNetworks', 'vnet'), '/subnets/snet-container-apps-env')]",
			"internal": false
		},
		"zoneRedundant": false
	},
	"type": "Microsoft.App/managedEnvironments"
}
```

**Comment by jijohn14** [comment]
Please retry deployment after registering your subscription (hosting your VNET) to `Microsoft.ContainerService`

**Comment by torosent** [comment]
`az provider register --namespace Microsoft.ContainerService`

**Comment by dgcaron** [comment]
For me the issue when away when I deployed an instance with the same name and settings through the portal. Now the system accepts the bicep file. It isn't really a workaround and I haven't tried it again with a different name that doesn't exist yet. I'll try that tomorrow and post back the results

**Comment by jijohn14** [comment]
Portal implicitly does the registration. You have to do explicitly do this for REST and ARM templates.

**Comment by kasper090288** [comment]
It works, thanks. Like @dgcaron, I also tried adding a container app through the portal, and @jijohn14 you're probably right, a registration has happened implicitly. Now, I can deploy same ARM template as mentioned in earlier comment.

**Comment by jijohn14** [comment]
@gary-lg Is the issue happening after explicit registration to `Microsoft.ContainerService`?

**Comment by kendallroden** [comment]
@gary-lg  please let us know ^
