### ISSUE TITLE
Revision failed provisioning

### ISSUE THREAD

**Issue by ashC05** [microsoft/azure-container-apps#335]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Upon attempting to provision a new revision provisioning is failing. Both from CLI and portal.

ContainerAppSystemLogs_CL shows:
2/2 Failed:...ContainerCrashing

ContainerAppConsoleLogs_CL shows:
"Middleware[0] At least one of http20OnlyDestinationHostUrl and http20OnlyListenUrl not provided"

### Steps to reproduct
1. Build custom solution to docker container
2. Publish to ACR
3. Provision via CLI

**Expected behavior** [What you expected to happen.]
Container revision provisioned successfully.

**Actual behavior** [What actually happened.]
Container revision failed to provision with errors shown above.

### Additional context
Similar error seen here with function apps but with no solution identified:
https://docs.microsoft.com/en-us/answers/questions/819706/azure-functions-host-warning-at-least-one-of-http2.html

Similar error reported here:
https://github.com/microsoft/azure-container-apps/issues/326

Note, ingress port does match the exposed / entry port of container

**Comment by torosent** [comment]
Is your your app listening on an HTTP port? if not, you need to turn ingress off.
