### ISSUE TITLE
Bug - neither Memory nor CPU scaling are working

### ISSUE THREAD

**Issue by vigneshsubbu9990** [microsoft/azure-container-apps#336]
> Please provide us with the following information:

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
 The auto-scaling no longer works, tried various combinations of scaling no luck
1. with volume mounting 
2. without volume mounting
3. CPU more than 15% Utilization
4. CPU more than 20% Utilization
5.  CPU more than 50% Utilization
6. Memory more than 15% Utilization
7. Memory more than 20% Utilization
8. Memory more than 50% Utilization

### Steps to reproduct
1. .. Create a container app with an apache airflow image: docker.io/apache/airflow:latest
2. Setup Memory or CPU scaling for 50% utilization with 1 min-replica and 6 max-replica
3. Run some heavy workloads in the container app
4. Observer CPU or Memory crossing more than 50% and stays at 50% for more than 30 minutes
5. Observer that No additional replicas are created

**Expected behavior** [What you expected to happen.]
The second replica should have been created upon hitting 50% of CPU or Memory

**Actual behavior** [What actually happened.]
Only one replica remained and no other replicas were created (no scaling up)

**Screenshots**         

Container Configuration: 1 CPU and 2GB Memory
![Screenshot 2022-08-02 at 11 07 02 AM](https://user-images.githubusercontent.com/19555796/182408870-1d5e520e-7ef5-4ddf-ac46-f077859909a9.png)

Setup Scaling. Memory Utilization more than 50% ##### Min Replica: 1 and Max Replica: 6
![Screenshot 2022-08-02 at 11 11 25 AM](https://user-images.githubusercontent.com/19555796/182409196-ba6e9119-ccc0-468d-864f-d66a8d5e4788.png)

Observe Memory Spikes up more than 50%
![Screenshot 2022-08-02 at 11 06 50 AM](https://user-images.githubusercontent.com/19555796/182409486-43198a98-dc56-444e-b07a-012b6c22d242.png)

Observe no other containers or pods scaled up
![Screenshot 2022-08-02 at 11 07 23 AM](https://user-images.githubusercontent.com/19555796/182409578-eb83ad5e-afe7-414e-a7d2-1c694a1c4b44.png)

### Additional context
tested both with CLI and portal, this issue still prevails, 

### Possible Cause
I suspect that Azure may have to remove KEDA's deprecated variables like **type** in CPU or Memory Scaling and add replace it with **metricType** variable as per KEDA's depreciation notice, Please refer to the screenshot from KEDA

![Screenshot 2022-08-02 at 11 16 35 AM](https://user-images.githubusercontent.com/19555796/182410664-6486a8cd-0079-44b5-bf08-9d98e1d37da3.png)

**Comment by vigneshsubbu9990** [comment]
Turns out to be the meta-data implementation was wrong. Hence closing this issue, thx

**Comment by LaurynasGr** [comment]
> Turns out to be the meta-data implementation was wrong. Hence closing this issue, thx

Wrong how? I'm trying to set up CPU-based scaling and I'm observing the exact same behaviour.
Any chance you could drop a sceenshot of the correct scaling rule setup for CPU/memory utilization in the Azure Portal?

Thanks!

**Comment by LaurynasGr** [comment]
> Turns out to be the meta-data implementation was wrong. Hence closing this issue, thx

Found the correct setup by trial and error. Here's a screenshot if someone else stumbles upon this issue:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/34269850/194184804-01c79a2b-351e-4e27-b263-654d258b47c3.png">
