### ISSUE TITLE
ADO Task

### ISSUE THREAD

**Issue by fisica3** [microsoft/azure-container-apps#34]
Being that with Bicep we can create for first time the complete stack for Azure Container Apps, is pending how to automate the deployment of new versions of our containers using Azure DevOps, so it would be great to have a **task** that helps the deployment using Azure Pipelines, some companies will still be using Azure DevOps so first class support will be appreciated.

**Comment by torosent** [comment]
We will provide documentation on how to deploy Container App with ADO.

**Comment by cmenzi** [comment]
Please consider any CI/CD system and don't  couple it too much to GitHub or ADO as you did in static web apps, where deployments needs a GitHub account.

Just make the CLI awesome.

**Comment by Squixx** [comment]
> Please consider any CI/CD system and don't couple it too much to GitHub or ADO as you did in static web apps, where deployments needs a GitHub account.
> 
> Just make the CLI awesome.

exactly, any AZ cli command to create a new revision  and/or to switch over traffic to a revision would be perfect.

**Comment by kendallroden** [comment]
The documentation for the **ADO Task** and **GitHub action** are pending deployment and will be publish by EOW this week!

**Comment by kendallroden** [comment]
Thanks for your patience. See docs https://learn.microsoft.com/en-us/azure/container-apps/azure-pipelines
