### ISSUE TITLE
Can not use Azure Container Registry with az containerapp update command 

### ISSUE THREAD

**Issue by ranjeetkpGit** [microsoft/azure-container-apps#343]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

Not able to use az containerapp update command with Azure Container Registry. I tried with Admin enabled (update command does not have login server, user name and password parameters) and without admin enabled. It always says UnAuthorized. I am able to use same container registry with az containerapp up comamnd

### Steps to reproduct
1. ..  execute az containerapp update command with any azure container registry image

**Expected behavior** [What you expected to happen.]
az container app update command should work with azure container registry images

**Actual behavior** [What actually happened.]
UnAuthorized

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

CLI Issue -
Yes

**Comment by haroonf** [comment]
Hello, `az containerapp update` does not support registry commands. There is a separate subgroup (`az containerapp registry`) that is used to update / create / delete registries. You would have to use `az containerapp registry` followed by `az containerapp update` if you want to use an image that is in a repository not currently associated with your containerapp.

**Comment by ranjeetkpGit** [comment]
Thanks Haroon. I will try this way
