### ISSUE TITLE
Feature Request: Allow managed resource group created with tag when deploying a Container App in a custom vnet

### ISSUE THREAD

**Issue by petergithubuser123** [microsoft/azure-container-apps#345]
**Is your feature request related to a problem? Please describe**.  
Problem creating a Container App in a custom vnet with error - 'ErrorCode: ManagedEnvironmentResourceGroupDisallowedByPolicy, Message: Fail to create managed environment because resource group creation is disallowed by policy, refer to https://go.microsoft.com/fwlink/?linkid=2198255 for more detail.'
This is caused by an Azure custom Policy assignment in our organisation requiring a custom tag to be attached to a resource which it inherits from a resource group.  Although the Container App is created with the custom tag, the managed resource group does not pick this up.  With Azure Synapse for example, the managed resource group created with Synapse inherits the tag of the main resource. 

**Describe the solution you'd like**.    
I would like the managed resource group to automatically inherit the tags of the Container App at the point of creation

**Describe alternatives you've considered**.   
MS Support had advised a workaround to add a Policy assignment exception for Resource Groups that have the MC_ prefix, and _region suffix, where region is the region that you are deploying the Container App Environment to.  

**Additional context**.

**Comment by asos-andrewpotts** [comment]
I have experienced the same problem. If you provision the Container App without VNet support it works as no new resource group is created, however this is not desirable.

**Comment by p9139010** [comment]
we are blocked by this bug. our networks are restricted and new resource group if it can be provisioned prior to deployment would help.

**Comment by mthoger** [comment]
we are likewise blocked by this, It would be nice to be able to define a namingstandard for the resources created within the resourcegroup aswell.

**Comment by miro1127** [comment]
Tag inheritance by the managed resource group would be consistent with other Azure resources that creates such resource group, for example: Azure Databricks or AKS. I am looking forward to have the same behavior applied to Container Apps as well.

**Comment by jasonjohnlee** [comment]
This is creating a problem for us as our environments have policies that require resources to have tags for organization and billing purposes.

**Comment by pmartynski** [comment]
Any update? This behaviour is preventing us from using container apps in our project.

**Comment by TrayanZapryanov** [comment]
Same in our company.

**Comment by chinadragon0515** [comment]
For now, any tags specified in container app environment creation will be auto added to the auto created resource group.

Any update on the container app environment tags will update to the auto created resource group too. Let us know if you have any issues.

Close the issue now.

**Comment by vaclavhluzek** [comment]
Perfect, but I am still facing the old behaviour when deploying with latest ARM template apiVersion: 2022-11-01-preview. What should I do ?
