### ISSUE TITLE
'az containerapp up --env-vars..' Is there any character length or number of environment variables limit      

### ISSUE THREAD

**Issue by ranjeetkpGit** [microsoft/azure-container-apps#346]
Is there any character length or number of environment variables limit in 'az containerapp up --env-vars..' cli
It does not add env variables in container app

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
CLI

**Comment by haroonf** [comment]
There is no limit on the CLI side, would you be able to provide more details for debug purposes?

**Comment by ranjeetkpGit** [comment]
> There is no limit on the CLI side, would you be able to provide more details for debug purposes?

Thanks Haroon for reply. Issue was with few line breaks in CLI. Fixed.

I am using 'az containerapp up' command with environment variable 'CosmosAccountName=secretref:cosmos-account' from CLI but after command succeeded it display 'container app' name for 'CosmosAccountName' variable in Azure Portal.

 Tried secretRef too. It just take it as string and adds 'secretRef:connection-name' in environment variable

I am creating container app and secrets using Pulumi(IaC) and deploying image with environment variables (contains secrets) using CLI. (Don't want to configure it on Azure Portal)

**Comment by haroonf** [comment]
> > There is no limit on the CLI side, would you be able to provide more details for debug purposes?
> 
> Thanks Haroon for reply. Issue was with few line breaks in CLI. Fixed.
> 
> I am using 'az containerapp up' command with environment variable 'CosmosAccountName=secretref:cosmos-account' from CLI but after command succeeded it display 'container app' name for 'CosmosAccountName' variable in Azure Portal.
> 
> Tried secretRef too. It just take it as string and adds 'secretRef:connection-name' in environment variable
> 
> I am creating container app and secrets using Pulumi(IaC) and deploying image with environment variables (contains secrets) using CLI. (Don't want to configure it on Azure Portal)

Could you try running with lowercase `secretref:cosmos-account`? I believe CLI only supports lowercase when add envs with secret refs. Thanks.

**Comment by ranjeetkpGit** [comment]
Hi

> > > There is no limit on the CLI side, would you be able to provide more details for debug purposes?
> > 
> > 
> > Thanks Haroon for reply. Issue was with few line breaks in CLI. Fixed.
> > I am using 'az containerapp up' command with environment variable 'CosmosAccountName=secretref:cosmos-account' from CLI but after command succeeded it display 'container app' name for 'CosmosAccountName' variable in Azure Portal.
> > Tried secretRef too. It just take it as string and adds 'secretRef:connection-name' in environment variable
> > I am creating container app and secrets using Pulumi(IaC) and deploying image with environment variables (contains secrets) using CLI. (Don't want to configure it on Azure Portal)
> 
> Could you try running with lowercase `--env-vars CosmosAccountName=secretref:cosmos-account`? CLI only supports lowercase `secretref: `
![env-var](https://user-images.githubusercontent.com/92055761/183941363-db6c7bd3-6d82-464a-837f-ede2099486dc.png)
 keyword when adding envs with secret refs. If that doesn't work, try making sure your secret value is set correctly using `az containerapp secret show`. Thanks.

Hi Harron,
Thanks for reply.
I have tried 'AppInsightsKey=secretref:appinsights-key'
but on portal i see like below image
![env-var](https://user-images.githubusercontent.com/92055761/183941542-eef26bff-d5b0-4ce0-b75f-16b60c4b6f8d.png)

**Comment by kendallroden** [comment]
Do we still need to continue investigating this issue or is it likely user error? Please let us know if you are still having trouble @ranjeetkpGit

**Comment by panchagnula** [comment]
@kendallroden this is not a client issue but a limit from platform side so please check with Tomer or some ACA dev, not something we set or control on client side

**Comment by kendallroden** [comment]
looks like there was a work item to fix this.
