### ISSUE TITLE
Update Documentation on default scaling rules

### ISSUE THREAD

**Issue by vigneshsubbu9990** [microsoft/azure-container-apps#348]
**Is your feature request related to a problem? Please describe**.  
Cannot tell which scaling rules/technique are applied when http, azure queue or custom rules are not selected?

**Describe the solution you'd like**.    
It would be great if we can update the below documentation with more information on the default scaling rules applied (in other words on what basis applications scale from min-replicas to max-replicas when scaling rules are not set)
https://docs.microsoft.com/en-us/azure/container-apps/scale-app

**Additional context**.  
Attached screenshot for more clarity on this screnario
I can see the app is scaling up sometimes, but can't tell whether it is CPU or Memory or KEDA Redis Lists and what is the default threshold set, etc.. are unclear

![Screenshot 2022-08-08 at 10 33 47 AM](https://user-images.githubusercontent.com/19555796/183443351-e0f595be-fce8-49d5-9ba9-b36bde6a1802.png)

**Comment by kendallroden** [comment]
Thanks for the feedback we will investigate

**Comment by kendallroden** [comment]
If the app is HTTP enabled (or TCP) it’ll have a default HTTP/TCP scale rule that’s `concurrentRequests: 10`. Otherwise, it will not have any. We will update the docs accordingly

**Comment by kendallroden** [comment]
The default scaling rules are highlighted in a doc that will be rolling out by EOW next week. We are also looking into ways to optimize the experience and create visibility into default scale rules.

**Comment by vigneshsubbu9990** [comment]
Thank you very much, Appreciate it!
