### ISSUE TITLE
Can't create more than 2 Container Apps using az containerapp up

### ISSUE THREAD

**Issue by MrSimonC** [microsoft/azure-container-apps#349]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting - done
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Using `az containerapp up`, we can't create more than two container apps in the same location.

### Steps to reproduce
Start with an empty subscription.

Using the following code, add 2 container apps:

* Azure Container App1 with environment name "development", location: uksouth
* Azure Container App2 with environment name "development", location: uksouth

Example Code is:

```shell
az extension add --name containerapp --upgrade --yes
az provider register --namespace Microsoft.App

NAME="simonflask5"
RESOURCE_GROUP="simonflasktest5"
TARGET_PORT="3000"
CONTAINERAPPS_ENVIRONMENT="development"
LOCATION="uksouth"

az containerapp up \
    --name $NAME \
    --resource-group $RESOURCE_GROUP \
    --location $LOCATION \
    --environment $CONTAINERAPPS_ENVIRONMENT \
    --ingress external \
    --target-port $TARGET_PORT \
    --source .
```

Run this either from your own command line - or as I do, in an Azure Dev Ops pipeline with appropirate Service Connection. e.g.

```shell
name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  batch: true
  branches:
    include:
    - main

stages:
  - stage: deploy_container_app
    jobs:
      - job: deploy_app
        steps:
          - task: AzureCLI@2
            displayName: Deploy app to Container App
            inputs:
              azureSubscription: MPFA Development Subscription Connection
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                #!/bin/bash
                az extension add --name containerapp --upgrade --yes
                az provider register --namespace Microsoft.App
                
                NAME="simonflask5"
                RESOURCE_GROUP="simonflasktest5"
                TARGET_PORT="3000"
                CONTAINERAPPS_ENVIRONMENT="development"
                LOCATION="uksouth"

                az containerapp up \
                  --name $NAME \
                  --resource-group $RESOURCE_GROUP \
                  --location $LOCATION \
                  --environment $CONTAINERAPPS_ENVIRONMENT \
                  --ingress external \
                  --target-port $TARGET_PORT \
                  --source .
```

Both Container apps will be created.

Run the code again:

* Azure Container App3 with environment name "development", location: uksouth

**Expected behavior** [What you expected to happen.]
App should deploy, since [quotas](https://docs.microsoft.com/en-us/azure/container-apps/quotas) indicate we should be able to create 5 environments per region per subscription. In this example, we've only creating one environment - "development", yet can't deploy due to what looks like a setting in `az containerapp up` restricting the amount of created environments, regardless of their name.

**Actual behavior** [What actually happened.]

```shell
Container app fails to deploy with error message:
WARNING: The installed extension 'containerapp' is in preview.
WARNING: Creating resource group 'simonflasktest5'
WARNING: Creating ContainerAppEnvironment 'development' in resource group simonflasktest5
ERROR: You have more than 2 environments in location uksouth. List of eligible locations: canadacentral, westeurope, northeurope, eastus, eastus2, eastasia, australiaeast, germanywestcentral, japaneast, westus, centralus, northcentralus, southcentralus, koreacentral, brazilsouth.
##[error]Script failed with exit code: 1
```

### Additional context
This occurs in an azure dev ops pipeline. Note: when _creating_ a 3rd app using the portal, this succeeds, indicating the portal's quotas are (more and) misaligned with the `az containerapp up` command (settings). Once the third container app is created in the portal, we still can't deploy to it using `az containerapp up` due to the above error as described.

**Comment by haroonf** [comment]
Thanks for bringing this to our attention, we will have a fix out in the next containerapp release.

**Comment by horihiro** [comment]
The error message is from [this line](https://github.com/Azure/azure-cli-extensions/blob/main/src/containerapp/azext_containerapp/_up_utils.py#L845) related to `az containerapp up`.
And `MAX_ENV_PER_LOCATION` that is used as a threshold in only the `up` sub-command is defined to `2` at [this line](https://github.com/Azure/azure-cli-extensions/blob/main/src/containerapp/azext_containerapp/_constants.py#L17). It should be `5` according to this [documentation](https://docs.microsoft.com/en-us/azure/container-apps/quotas).

**Comment by horihiro** [comment]
I think this CLI/extension should not have quota values because this way cannot reflect quota expansion by future service upgrade or customer requests.

**Comment by horihiro** [comment]
It seems that [v0.3.9](https://github.com/Azure/azure-cli-extensions/commit/cc90552f10f121720948c61df36805a4e1119fe5#diff-c0bc99c8d9be50ec3160807248de9a56ddb4050be693046185a9b59424c985cb) fixes this issue.

**Comment by MrSimonC** [comment]
This issue remains @horihiro (thanks for helping out) and @haroonf - tested on v0.3.9

Because the validation code in `az containerapp up` (which in my opinion, you should take out, and leave up to the quota validation code on Azure RM) is counting the amount of environments which exist in total, _not_ the amount of environments with different names.

I've been able to deploy 5 in 1 environment:
![image](https://user-images.githubusercontent.com/3033044/186479519-f218de6d-ab0c-4ec2-a63a-d1d8c284553c.png)

but again errors on the next app apply with:

> WARNING: Creating ContainerAppEnvironment 'development' in resource group simonflasktest7
>ERROR: You have more than 5 environments in location uksouth. List of eligible locations: canadacentral, westeurope, northeurope, eastus, eastus2, eastasia, australiaeast, germanywestcentral, japaneast, westus, centralus, northcentralus, southcentralus, koreacentral, brazilsouth, westus3, francecentral, southafricanorth, norwayeast.
>##[error]Script failed with exit code: 1

Again, according [to quotas](https://docs.microsoft.com/en-us/azure/container-apps/quotas), we should be allowed 20 apps per environment, not 5.

**Comment by haroonf** [comment]
> This issue remains @horihiro (thanks for helping out) and @haroonf - tested on v0.3.9
> 
> Because the validation code in `az containerapp up` (which in my opinion, you should take out, and leave up to the quota validation code on Azure RM) is counting the amount of environments which exist in total, _not_ the amount of environments with different names.
> 
> I've been able to deploy 5 in 1 environment: ![image](https://user-images.githubusercontent.com/3033044/186479519-f218de6d-ab0c-4ec2-a63a-d1d8c284553c.png)
> 
> but again errors on the next app apply with:
> 
> > WARNING: Creating ContainerAppEnvironment 'development' in resource group simonflasktest7
> > ERROR: You have more than 5 environments in location uksouth. List of eligible locations: canadacentral, westeurope, northeurope, eastus, eastus2, eastasia, australiaeast, germanywestcentral, japaneast, westus, centralus, northcentralus, southcentralus, koreacentral, brazilsouth, westus3, francecentral, southafricanorth, norwayeast.
> > ##[error]Script failed with exit code: 1
> 
> Again, according [to quotas](https://docs.microsoft.com/en-us/azure/container-apps/quotas), we should be allowed 20 apps per environment, not 5.

It looks like you are creating new environments every time you run the command (resource names in Azure are only unique per resource group, not per subscription). The logger error `Creating ContainerAppEnvironment 'development' in resource group simonflasktest7'` means we are attempting to create a new environment on the passed location. Looking at the quotas, we only allow 5 environments per location (in this case, you have 5 environments in UK South in different resource groups). In order to reuse the same environment, please either pass the resource ID of the environment or use `containerapp up` with the same resource group as your original environment.

**Comment by MrSimonC** [comment]
Thanks @haroonf that makes a lot of sense now.

To complete the picture (for anyone else reading), creating an ACA through the portal, but creating a new environment results in the same error - as, quite correctly as haroonf pointed out, if we go to the "Container App Environments" section of the portal, we find I've created 5 there in the same location.

I've updated, tested and confirmed that wecan reuse an existing environment in the script I posted above, by updating these lines:

```shell
# CONTAINERAPPS_ENVIRONMENT=development  # to create a new environment, or to reuse one:
existingEnvironmentResourceId=$(az resource show --name development --resource-group simonflasktest6 --resource-type Microsoft.App/managedEnvironments --query id --output tsv)
CONTAINERAPPS_ENVIRONMENT=$existingEnvironmentResourceId
```

and in my example, simonflasktest7 (my 6th ACA app) deploys well into simonflasktest6's environment (see it now contains 2 apps):
![image](https://user-images.githubusercontent.com/3033044/186629375-0ec5f727-d6e9-4718-8c0c-8b119011654a.png)
