### ISSUE TITLE
Required Azure AD Role/Permission to Deploy New Container App Revision?

### ISSUE THREAD

**Issue by mikeball** [microsoft/azure-container-apps#35]
I would like to create/activate new revisions using the azure cli from within a bitbucket pipelines using a service principal. What role assignments/grant names are necessary for a user to deploy a new revision to container apps?

For example a user to push a new image to azure container registry is "AcrPush". Below is example creating such a principal and role.
```
> az ad sp create-for-rbac --name MyDeployUser
> az role assignment create --assignee GUIDOFMYDEPLOYUSER --role AcrPush
```

And here is an example of azure cli command currently used  to deploy revisions.
```
> az containerapp update -n mycontainerappname -g myresourcegroup --image myregistryname.azurecr.io/myapp:mytag
```

**Comment by ahmelsayed** [comment]
You can use `Contributor`

**Comment by mikeball** [comment]
I was able to create an active directory custom role, then assign that to a service principal and that seems to work with `> az containerapp update ...`. Below is the json starting point of the role, for others that might want to do the same.

```json
{
    "properties": {
        "roleName": "ContainerApps Deployer",
        "description": "Custom role to allow deployment of container app revisions. Eventually would like to limit permissions to only update of revisions.",
        "permissions": [
            {
                "actions": [
                    "Microsoft.Web/kubeEnvironments/join/action",
                    "Microsoft.Web/containerApps/revisions/read",
                    "Microsoft.Web/containerApps/revisions/activate/action",
                    "Microsoft.Web/containerApps/revisions/deactivate/action",
                    "Microsoft.Web/containerApps/revisions/deactivate/restart/action",
                    "Microsoft.Web/containerApps/operationResults/read",
                    "Microsoft.Web/containerApps/write",
                    "Microsoft.Web/containerApps/read"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}
```

**Comment by jmarti326** [comment]
Was this Feature Request ever work on? Is it in the backlog? Is there a timeline?

**Comment by charlesavos** [comment]
Why was this feature request closed? We have the same question as @jmarti326: what's the status of this issue?

**Comment by dombarnes** [comment]
Given that you seem to need Azure AD Premium P1 or P2 for this to create a custom role, this seems very limiting. Requiring Contributor role granting a very wide range of access is overkill.

**Comment by torosent** [comment]
Hi, We will introduce more roles in Q4 2023.

**Comment by RadekKpc** [comment]
@torosent Hi, how is work going on new roles? Can we expect new role added in this quarter for case described in this issue?

**Comment by bgrainger** [comment]
I found that I needed to add the following permissions to a custom role in order for `az containerapp update` to work (not sure if all of them are strictly necessary); it appears that some of the permissions have been renamed since @mikeball posted?

```
      "Microsoft.App/containerApps/revisions/read",
      "Microsoft.App/containerApps/revisions/activate/action",
      "Microsoft.App/containerApps/revisions/deactivate/action",
      "Microsoft.App/containerApps/revisions/restart/action",
      "Microsoft.App/locations/containerappoperationresults/read",
      "Microsoft.App/containerApps/write",
      "Microsoft.App/containerApps/read"
```

**Comment by Quezion** [comment]
I want to +1 @bgrainger's comment. Microsoft indeed seems to have changed rolenames from `Microsoft.Web` to `Microsoft.App`. My initial attempts at a custom role had no success as my service principal account still couldn't see my Azure Container App.

I added all of the roles bgrainger mentioned, the original Microsoft.Web roles, and any other relevant "read/activate/deactivate/write" App Container permissions. _Then my service principal could finally see the App Container._

I can only assume @kendallroden closed this issue as a matter of prioritization, but _please_ reopen it or a similar issue until an Azure role is added for `Container App Writer`. There's already a similar `Container App Reader` role & this should be a straightforward add.

**Comment by fela98** [comment]
@torosent Have there been created any new roles for container apps yet? I couldn't find them in the Azure Portal.

**Comment by dekiesel** [comment]
These new roles would be really handy right now. Any update?

**Comment by tom-HCgY7HY6kq** [comment]
+1

**Comment by ffloimair** [comment]
```
       "Microsoft.App/containerApps/revisions/read",
       "Microsoft.App/containerApps/revisions/activate/action",
       "Microsoft.App/containerApps/revisions/deactivate/action",
       "Microsoft.App/containerApps/revisions/restart/action"
```
At  least these four of the mentioned permissions are part of the new Role "Container Apps Contributor"

I found this useful Webapp to do least privilege calculation or just show permissions that are part of a role.
