### ISSUE TITLE
Can we give container name when we use 'az containerapp up' command to deploy an image from azure container registry

### ISSUE THREAD

**Issue by ranjeetkpGit** [microsoft/azure-container-apps#350]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduct
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by BigMorty** [comment]
Yes, you can specify the --image (-i) option on 'az containerapp up'.

Example - az containerapp up -n MyContainerapp --image myregistry.azurecr.io/myImage:myTag
Command reference is here - https://docs.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-up

**Comment by ranjeetkpGit** [comment]
> Yes, you can specify the --image (-i) option on 'az containerapp up'.
> 
> Example - az containerapp up -n MyContainerapp --image myregistry.azurecr.io/myImage:myTag Command reference is here - https://docs.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-up

Hi #BigMorty,
Thanks for reply.
My question is , Is there any way we can deploy image to any existing container in container app? 
There could be multiple containers in a container app.

**Comment by BigMorty** [comment]
Yes, you can create a new revision of your app and update the image to a new image in your registry. You can use 'az containerapp update ...' or 'az containerapp revision copy...'

Examples:
az containerapp update -n MyContainerapp -g MyResourceGroup --image myregistry.azurecr.io/my-app:v2.0

az containerapp revision copy -n MyContainerapp -g MyResourceGroup --image myregistry.azurecr.io/my-app:v2.0
//Note the 'revision copy' command defaults to copying from the latest revision, you can alter this with the '--from-revision' option
