### ISSUE TITLE
Can we create a Azure Container App without an image (Initial Infrastructure setup) for Enterprise Apps

### ISSUE THREAD

**Issue by ranjeetkpGit** [microsoft/azure-container-apps#353]
Hi Team,
I create Container App and its Infrastructure (Dapr, Scaling, Probes) using IaC (Pulumi).
Can we create a container app without providing any dummy(from mcr.microsoft.com/azuredocs/containerapps-helloworld or others) image. If we don't have any image to start with, which image is recommended from Microsoft for any Enterprise application as we don't want to use hello world in higher environments.

**Comment by BigMorty** [comment]
No, you need to specify an image. I would suggest you create the smallest image possible so it will pull/startup fast.
