### ISSUE TITLE
Revision Takes time in Provisioning (Container App with Dapr bindings.cron)

### ISSUE THREAD

**Issue by ranjeetkpGit** [microsoft/azure-container-apps#354]
Hi,
I am creating a Container App with a dummy image (alpine) using IaC (Pulumi). It does not get provisioned and Fails. It gets provisioned after few hours itself or when we manually create Revision.
I am using 'az containerapp up' command to deploy successive images

Is there any predefined time required Revision to get provisioned? 
Sometime i see it gets provision immediately.

I checked the log when Revision Fails and it says
1/1 Failed:daprdContainerCrashing

**Comment by kendallroden** [comment]
This means there is an error with your configuration that is causing dapr to crash. We would need more information to provide assistance can you confirm you still need help with the above? Sorry for the delay @ranjeetkpGit
