### ISSUE TITLE
Feature Request: Question: Documentation about the outbound IP

### ISSUE THREAD

**Issue by cboghy** [microsoft/azure-container-apps#355]
If I create a container apps environment with the default virtual network, I can then get the "static IP" that assigned. 
If I try to make an http request from the container app to another web address, I see that the request comes from another IP. This outbound IP is different than the "static IP"
Is the outbound IP also static? Can it be used in a whitelist on the server that receives the calls from a container app?

**Comment by clintsinger** [comment]
I have a similar issue where my scenario is that I have a virtual machine that has SQL server exposed but isn't accessible unless allowed through the Network Security Group.   Without knowing what the IP address will be, I can't add it to the allow list.

**Comment by duglin** [comment]
If you do `az containerapp list` you should see something like this for each app:
```
      "outboundIpAddresses": [
        "20.121.75.96",
        "20.121.75.163",
        "20.121.75.187"
      ]
```
I believe those those be the IP addresses you'll need to put in the whitelist.

**Comment by duglin** [comment]
But keep in mind, I suspect that list will change over time as the list of Kubernetes nodes in the environment changes.

**Comment by clintsinger** [comment]
That did the trick for now.   I'm currently using this as a work around while I wait for an answer to #373

**Comment by VeselovAndrey** [comment]
I have same issue - 3rd party API allows access only from whitelisted IPs. So, I need provide outbound IP of my Container App. Is it safe to use "outboundIpAddresses"? How often they can be changed?

Is it possible assign outbound static IP(s) for Container App?

**Comment by VeselovAndrey** [comment]
Also are _outboundIpAddresses_ assigned to the single Container App or they can be shared between couple of them (and using them in whitelists are not secure).

**Comment by ttamg** [comment]
Is it possible to tighten up the documentation on outbound IP being static or not please as this is not clear still in the Azure Container Apps documentation.  

In the portal under the Container app / Overview / Properties / Networking the Outbound IP is shown there.  This is very convenient thanks. 

But it is not at all clear still if this is a static IP or a floating IP and when building a production app I do worry it might change!  The response quoted below is helpful but it's not consistent with the documentation, so is it official that we can rely on this

> The outbound IP is static for a given environment today. We no longer provide 3, and they will be static for the lifetime of an environment. You can use this outbound IP for whitelisting purposes

Thanks!

**Comment by benjaminwillett** [comment]
I seem to have problems with connectivity out from my container. I can do ubuntu updates etc to the container and dns lookups but unable to ping any internet ip.
I can connect to the webservice on my container public ip but unable to make requests out from the container to my public facing SQL server IP. Am I trying to do something the azure infrastructure is not setup to do? Do I need a NAT gateway for the container to be able to make outbound requests? There is no NSG etc attached to my container.
