### ISSUE TITLE
Cannot resolve Container App FQDN from other apps in the vnet (App gateway, ACI)

### ISSUE THREAD

**Issue by evalann** [microsoft/azure-container-apps#356]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting

### Issue description
Applications within our VNET are unable to resolve the FQDN that is automatically assigned to our container app, but if I go to the container and get the Internal IP Address then attempt to access the API via that IP everything works as expected. This is not ideal though because my understanding is that the IP of the container app may change over time or there may be multiple IPs if the container app is scaled out.

If I connect to the container for my Azure Container App and make a request to the API using the FQDN I get back the expected response, but if I connect to a container in my Azure Container Instances and attempt to make the same request it fails to resolve the FQDN. (e.g. curl: (6) Could not resolve host: aca-customers-development-eu.politebeach-ff70ca9f.eastus.azurecontainerapps.io)

Our primary use case is to use the FQDN as a backend pool for our Application Gateway, but this results in a 502 (Bad Gateway) when attempting to make requests. 

### Steps to reproduct
We have a vnet defined with address space 10.0.0.0/16
This vnet has multiple subnets:
- 10.0.0.0/24 (Dedicated to an Application Gateway)
- 10.0.2.0/24 (Dedicated to our Azure Container Instances)
- 10.0.4.0/23 (Created for use with our Azure Container Apps) (acaSubnetResource)

When creating the container app environment I'm using the following vnet configuration:
```
vnetConfiguration:{
      internal: true
      runtimeSubnetId: acaSubnetResource.Id
      infrastructureSubnetId: acaSubnetResource.Id
    }
```

Ingress config for the container app:
```
ingress: {
        transport: 'auto'
        external: true
        targetPort: 80
        traffic: [
          {
            latestRevision: true
            weight: 100
          }
        ]
      }

```

**Expected behavior** [What you expected to happen.]
Applications within the same vnet should be able to resolve the FQDN and make requests to the container app. 

**Actual behavior** [What actually happened.]
Applications within the same vnet are unable to resolve the FQDN.

**Screenshots**         
Portal Ingress Tab on the container app:
![image](https://user-images.githubusercontent.com/40572240/184351149-8a779433-0bed-46b7-a987-cb628d1e54ab.png)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by omni-htg** [comment]
I know it's not a "solution" of sorts, but have you tried [setting up a Private DNS Zone](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-container-apps-virtual-network-integration/ba-p/3096932)?

**Comment by evalann** [comment]
> I know it's not a "solution" of sorts, but have you tried [setting up a Private DNS Zone](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-container-apps-virtual-network-integration/ba-p/3096932)?

Thanks, this worked! It left me with a different issue entirely, but I'll figure that out myself and close this thread.

**Comment by willtho89** [comment]
Hi,

this is still a problem and not working as expected imo. I would expect that the Application Gateway can resolve the automatically assigned name of the container instance in the same vnet.

My configuration is basically as described by @evalann above. My Application Gateway can not resolve the fqdn of the container.
![764644CF-DC07-4134-A7EC-490AB105B50F](https://user-images.githubusercontent.com/4933503/214127526-dc94ac7e-af1b-43ac-b081-90490bf20a07.png)

**Comment by willtho89** [comment]
For people from the future trying to make this work:
* Create a private DNS zone with a wildcard A entry to your internal load balancer (Static IP from the Container Application Enviroment)
* In the Application Gateway use the FQDN of your container as a target
* In the Application Gateway create a HealthProbe for HTTPS, set the FQDN of your container as Host
* In the Application Gateway overwrite the Backend Settings:
  * Protocoll HTTPS
  * Override with new Hostname: yes
  * set the host name to the FQDN of your container
  * use the newly created health probe

Thanks @evalann for guiding in the correct way ❤️

**Comment by evalann** [comment]
> For people from the future trying to make this work:
> 
> * Create a private DNS zone with a wildcard A entry to your internal load balancer (Static IP from the Container Application Enviroment)
> * In the Application Gateway use the FQDN of your container as a target
> * In the Application Gateway create a HealthProbe for HTTPS, set the FQDN of your container as Host
> * In the Application Gateway overwrite the Backend Settings:
>   
>   * Protocoll HTTPS
>   * Override with new Hostname: yes
>   * set the host name to the FQDN of your container
>   * use the newly created health probe
> 
> Thanks @evalann for guiding in the correct way ❤️

Happy to have helped! I'm surprised I was coherent at 10pm on LinkedIn messages.

**Comment by hungdhm-0574** [comment]
@willtho89 @evalann  I have a question, why we have to create a Private DNS zone instead of using internal load balancer (Static IP from the Container Application Enviroment) as a target in Application Gateway Backend pool target?

**Comment by evalann** [comment]
> @willtho89 @evalann I have a question, why we have to create a Private DNS zone instead of using internal load balancer (Static IP from the Container Application Enviroment) as a target in Application Gateway Backend pool target?

From that link [omni-htg](https://github.com/omni-htg) posted: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-container-apps-virtual-network-integration/ba-p/3096932

> By default, there is no domain registration for the internal load balancer (ILB) that is created. This means customers will be responsible for configuring DNS resolution for the environment endpoint. In Azure, this can be accomplished by creating and configuring an [Azure Private DNS Zone](https://docs.microsoft.com/en-us/azure/dns/private-dns-privatednszone).

My understanding is that the internal load balancer is only available within the container app environment and the Private DNS Zone is needed so that other applications in the VNet can resolve the IPs of the containers from their `.azurecontainerapps.io` URLs.

**Comment by hungdhm-0574** [comment]
@evalann thank you. In the case you try to use FQDN  as a target. I think it is correct. But why we have to use FQDN ? Why we cannot use its IP instead of FQDN ? 
I cant understand why Azure for us to do that.

**Comment by evalann** [comment]
> @evalann thank you. In the case you try to use FQDN as a target. I think it is correct. But why we have to use FQDN ? Why we cannot use its IP instead of FQDN ? I cant understand why Azure for us to do that.

Technically you can use the IP of the container apps themselves if you wanted to, but this isn't ideal because that IP address may change when container apps scale in/out or if you deploy a new revision. If you mean the IP of the container app environment, I'm not too sure :) Might be worth opening another issue or chatting with the MS guys on their Discord.

**Comment by hungdhm-0574** [comment]
@evalann thank you :) 
I mean the IP of the container app environment, that is internal loadbalancer IP of ACA. I think it would not change :D 
ANW, thanks a lot for your help. 💯

**Comment by arpanpreneur** [comment]
But why would I pay for a Private DNS, when I don't even need the name, all I want is a static IP to their ingress envoy.

**Comment by evalann** [comment]
> But why would I pay for a Private DNS, when I don't even need the name, all I want is a static IP to their ingress envoy.

I don't think you need the Private DNS if you're okay with the static IP, in my case I needed other applications in the same VNET to be able to resolve the container app FQDNs.

**Comment by shyam-king** [comment]
How will the ingress route traffic to your container app without knowing it's name? I don't think it will work with the static ip.
