### ISSUE TITLE
AAD Auth - CORS Issue

### ISSUE THREAD

**Issue by marvinbuss** [microsoft/azure-container-apps#359]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.
When enabling AAD auth for a Web API hosted on Container Apps and trying to access the API via SPA and MSAL (React), the preflight call (OPTIONS REST API call) always fails with a 401 Unauthorized. We have properly configured CORS in the backend and when disabling the AAD Auth feature, everything works fine. We haven't found a way to configure this in the AAD sidecar. I also checked the logs for the `http-auth` sidecar, but that did not help either. I can just see the 401 requests in the traces. How can we overcome the issue?

### Steps to reproduce
1. Host Web API on Container App
2. Enable AAD Auth for Web API Container App
3. Create React App with MSAL
4. Open React App in Browser and try to call API

**Expected behavior** [What you expected to happen.]
API call succeeds.

**Actual behavior** [What actually happened.]
API call fails due to 401 Unauthorized for preflight.

**Screenshots**         
Not required.

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
See above

**Comment by torosent** [comment]
@Hamster-Huey Can you help with this issue?

**Comment by Hamster-Huey** [comment]
Hi @marvinbuss  

In your repro steps, could you share how you are configuring cors on your app?

**Comment by marvinbuss** [comment]
Hi @Hamster-Huey,
I am using a CORS Middleware in my Python application (FastAPI). As soon as I disable the Container Apps Auth feature, everything works fine. When I turn it on, the CORS request gets blocked and the API call fails accordingly.

**Comment by Hamster-Huey** [comment]
What's likely happening is that the Auth feature enables a middleware container to spin up that all requests to your apps are routed to. This container authenticates all requests that flow through it, and so even the OPTIONS request is being routed through the middleware and failing with 401 (since the request is unauthorized and not browser initiated to initiate login flow). This middleware (similar to App Service) does allow you to configure CORS allowed origins that will then do the right thing for preflight calls. 

@torosent is there currently a way for Container Apps to configure CORS settings on the authentication middleware?

**Comment by marvinbuss** [comment]
@Hamster-Huey that is also what I identified. I tested this with Postman and when including the Bearer Token in teh OPTIONS call, the API call was successful. The browser does not do that though and hence teh sidecar returns a 401 response.

Would be great, if we could configure CORS, but I could not see any option in the portal or ARM property bag that could help here. Appreciate your help!

**Comment by torosent** [comment]
Hi. We are not exposing the option to configure CORS but I've added it to our backlog.

**Comment by marvinbuss** [comment]
Hi  @torosent ,
So that means that we are blocked at this point and have to configure AAD auth in the app code?

**Comment by marvinbuss** [comment]
Hi @torosent & @Hamster-Huey,
Any updates here?

Thanks for your help!

**Comment by torosent** [comment]
We are working on this now but it will take a few weeks to deploy since we need to add it to a new API version. I will update this thread once it will be ready.

**Comment by marvinbuss** [comment]
Thanks for the update @torosent 
Great to hear that you are working on a fix. 🚀

**Comment by SariDev** [comment]
Hi, do you have some news regarding the state of this issue?

Is there a roadmap / release plan for the next versions of azure container apps?

**Comment by kendallroden** [comment]
I asked the team yesterday and they said the work is in progress and they will give me an ETA asap

**Comment by torosent** [comment]
@SariDev @marvinbuss 
You can now setup CORS for the app using ARM/Bicep with api version 2022-10-01. CLI and Portal will be added in Q1 2023.
```json 
{
  ...
  "configuration": {
      "ingress": {
          "external": true,
          "targetPort": 80,
          "transport": "auto",
          "corsPolicy": {
              "allowedOrigins": ["*"]
           }
      }
  }
}
```
https://github.com/Azure/azure-rest-api-specs/blob/release-app-Microsoft.App-2022-10-01/specification/app/resource-manager/Microsoft.App/stable/2022-10-01/ContainerApps.json#L793

https://github.com/Azure/azure-rest-api-specs/blob/release-app-Microsoft.App-2022-10-01/specification/app/resource-manager/Microsoft.App/stable/2022-10-01/ContainerApps.json#L946

**Comment by SariDev** [comment]
@torosent thank you for the update :)

I will check it and give you feedback!

**Comment by SariDev** [comment]
As I'm using Pulumi.AzureNative V1.88.1, currently I have no access to the API version 2022-10-01.
The V1.89.0-alpha.1670395396 also doesn't have it right now.

![image](https://user-images.githubusercontent.com/13918020/206276807-6e6cc3c4-a248-4c4d-85b9-81d15aca0f3f.png)

I guess I'll have to wait for PR to be merge, before it will be availabe in Pulumi.
https://github.com/Azure/azure-rest-api-specs/pull/21683

But once it's available, I'll give feedback :)

**Comment by SariDev** [comment]
Hi Team,

so after Pulumi.AzureNative got an update to Version="1.89.1" I was able to test this.
Unfortunately I still have CORS issues.

My setup is like this:
1 Container App Environment with 3 Container Apps inside it and a Azure SQL DB.
1 Container App is publicly accessible (Ingress External = true) and it talks to the other 2 container apps via HTTP.
They are not publicly accessible (Ingress External = false).

```mermaid
flowchart TB;
subgraph containerAppEnvironment ["Container App Environment"]

    subgraph containerAppFrontend ["Container App Frontend"]
        webFrontend[".NET 7 Blazor WASM App (Self hosted)<br>External = true"]
    end

    subgraph containerAppUsers ["Container App User API"]
        webApiUsers[".NET 7 Web API - Users<br>External = false"]
    end

    subgraph containerAppShared ["Container App Shared API"]
        webApiShared[".NET 7 Web API - Shared<br>External = false"]
    end

end

    subgraph azureSqlDatabase ["Azure SQL database"]
        Database[(Database)];
    end
    
    webFrontend -->|"REST HTTP(S) calls"| webApiShared;
    webFrontend -->|"REST HTTP(S) calls"| webApiUsers;  
    
    webApiUsers -->|"EF Core calls"| Database;
    webApiShared -->|"EF Core calls"| Database;
```

My Frontend loads and I click on the button that does the API requests and then I can see the CORS error in the browser dev tools.
![image](https://user-images.githubusercontent.com/13918020/207376663-bb8f473a-256a-4e99-93e0-9a6a7e446831.png)

My Infrastructure code for both API container apps have CORS set up like mentioned here:
https://github.com/microsoft/azure-container-apps/issues/359#issuecomment-1339818898
![image](https://user-images.githubusercontent.com/13918020/207379561-f5623ed6-9abb-4c3d-9895-28c4e77e6e0b.png)

CORS is also NOT enabled in the ASP .NET Core WEB API projects (no app.UseCors() call).

---

I tried to execute a REST GET query via the Azure Container App of my frontend.
I used the console in the Azure Portal and had to setup CURL like this:
```bash
apt-get update; apt-get install curl
```

Than I send the request like this:
```bash
curl https://xxx-api.jollyisland-280266ef.westeurope.azurecontainerapps.io/xxx -H "Authorization: Bearer TOKEN"
```

The curl request here worked without issues and gave me the expected result.

Any ideas, what I might be doing wrong?

**Comment by ahmelsayed** [comment]
CORS is a browser-only concept. You shouldn't need CORS between backend services that are using non-browser clients between each other (e.g: `System.Net.HttpClient`) 

The error you're seeing in the browser's console, i.e:
![207380456-e67e824c-869c-42c2-afa4-786afa9970e0](https://user-images.githubusercontent.com/645740/207438883-ca419040-320a-44bc-9016-fc0cd877a7ad.png)

is because the browser can't actually reach `xxx-api.internal.jollyisland-280266ef.westeurope.azurecontainerapps.io` since it's **internal** only. If you check the network tab in the browser, I bet it's doing an OPTIONS request to check the CORS policy on `xxx-api.internal.jollyisland-280266ef.westeurope.azurecontainerapps.io` but getting a 404. 

The reason it's working from curl, is because you're running curl inside the ACA environment, where that end point is accessible as opposed to outside (i.e the browser) where that end point isn't. 

In your design, you can either:

1- Make `Container App User API` and `Container App Shared API` external, so the browser can reach them. You'll still need to configure CORS for them but calling them from client-side code (i.e blazor) should work.


2- Have a path/endpoint on your frontend app that proxies requests to other apps you don't want to expose on the internet. So your setup does something like:


```
browser -> https://frontend.jollyisland-280266ef../api/users -> https://user-api.internal.jollyisland-280266ef...
# or 
browser -> https://frontend.jollyisland-280266ef../api/shared -> https://shared-api.internal.jollyisland-280266ef...
```

For example, using https://github.com/microsoft/reverse-proxy you could do something like: _(see for more details https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html)_ 

```csharp
public void Configure(IApplicationBuilder app, IHttpForwarder forwarder)
{
    var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
    {
        UseProxy = false,
        AllowAutoRedirect = false,
        AutomaticDecompression = DecompressionMethods.None,
        UseCookies = false,
        ActivityHeadersPropagator = new ReverseProxyPropagator(DistributedContextPropagator.Current)
    });
    var requestConfig = new ForwarderRequestConfig { ActivityTimeout = TimeSpan.FromSeconds(100) };

    // this should resolve to 'jollyisland-280266ef.westeurope.azurecontainerapps.io' for example
    var dnsSuffix = System.Environment.GetEnvironmentVariable("CONTAINER_APP_ENV_DNS_SUFFIX");

    app.UseRouting();
    app.UseEndpoints(endpoints =>
    {
        // map /api/user/*
        endpoints.Map("/api/user/{**catch-all}", async httpContext =>
        {
            var error = await forwarder.SendAsync(httpContext, $"https://user-api.internal.{dnsSuffix}",
                httpClient, requestConfig, HttpTransformer.Default);
            // Check if the operation was successful..
        });

        // map /api/shared/*
        endpoints.Map("/api/shared/{**catch-all}", async httpContext =>
        {
            var error = await forwarder.SendAsync(httpContext, $"https://shared-api.internal.{dnsSuffix}",
                httpClient, requestConfig, HttpTransformer.Default);
            // Check if the operation was successful..
        });
    });
```

or using a package like https://github.com/twitchax/AspNetCore.Proxy with something like:

```csharp
var dnsSuffix = System.Environment.GetEnvironmentVariable("CONTAINER_APP_ENV_DNS_SUFFIX");

app.UseProxies(proxies =>
{
    // Map /api/users/*
    proxies.Map("api/users/{**catchAll}", proxy => proxy.UseHttp((_, args) => $"https://users-api.internal.{dnsSuffix}/{args["catchAll"]}"));

    // Map /api/shared/*
    proxies.Map("api/shared/{**catchAll}", proxy => proxy.UseHttp((_, args) => $"https://shared-api.internal.{dnsSuffix}/{args["catchAll"]}"));
});
```

Then your blazor app will be calling `https://frontend.jollyisland-280266ef.westeurope.azurecontainerapps.io/api/users` or `https://frontend.jollyisland-280266ef.westeurope.azurecontainerapps.io/api/shared` and the frontend will be proxying those calls to the internal only microservices.

**Comment by manlm** [comment]
I have set the cors policy but still get the cors block on browser, my front-end is deploy azure static web app

![image](https://user-images.githubusercontent.com/12764063/207495905-5653435d-e94d-4813-8df6-20bd4c34e5d1.png)

**Comment by SariDev** [comment]
@ahmelsayed thank you for your super helpful response!

I had a look at the 2nd option you mentioned and got it working for my project.

Now my Blazor WASM Frontend host application uses YARP to "direct forward" requests to my API container apps and they can stay internal.

Everything now works as expected.

I have also removed the CORS policy I set up for the Container Apps, as it was not needed.

**Comment by ahmelsayed** [comment]
> I have set the cors policy but still get the cors block on browser, my front-end is deployed on azure static web app

@manlm what do you get if you do 


```bash
$ curl -XOPTIONS -I \
    -H "Access-Control-Request-Method: GET" \
    -H "Access-Control-Request-Headers: Foo-Header"
    -H "Origin: https://foo.com" \
    https://{your-app-url}
```

With your config, you should expect back something like

```
HTTP/2 200
access-control-allow-origin: https://foo.com
access-control-allow-methods: GET
access-control-allow-headers: Foo-Header
access-control-max-age: 0
```

**Comment by ahmelsayed** [comment]
Closing this issue as completed.
