### ISSUE TITLE
Support do SSL and DNS

### ISSUE THREAD

**Issue by carloscds** [microsoft/azure-container-apps#36]

**Comment by ahmelsayed** [comment]
@carloscds can you explain a bit more what you're looking for?

**Comment by carloscds** [comment]
Same of AppServices. I can put a DNS name over application and a SSL.

**Comment by ahmelsayed** [comment]
Got it. I think this is a dup of https://github.com/microsoft/azure-container-apps/issues/8 It's definitely planned and on the roadmap.

**Comment by carloscds** [comment]
Yes!
