### ISSUE TITLE
Unable to use external KEDA scaler

### ISSUE THREAD

**Issue by VeselovAndrey** [microsoft/azure-container-apps#364]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Unable to use external KEDA scaler. It's configured, can be accessed using GRPS test client but there is always one instance.

### Steps to reproduct
1. Create a Contaner App
2. Verify that external scaler up and running.
3. Add external scaler for replica
```json
"scale": {
                "minReplicas": 0,
                "maxReplicas": 6,
                "rules": [
                    {
                        "name": "external-scaler",
                        "custom": {
                            "type": "external",
                            "metadata": {
                                "scalerAddress": "site-name.azurewebsites.net:443"
                            }
                        }
                    }
                ]
            }
```

**Expected behavior** [What you expected to happen.]
Contaianer App scaling replicas according to external scaler.

**Actual behavior** [What actually happened.]
There is 1 replica always, external scaler log has no signs of requests.

**Comment by ahmelsayed** [comment]
@VeselovAndrey can you share your app name with me (ahmels at microsoft.com)

**Comment by VeselovAndrey** [comment]
@ahmelsayed I sent name to your email.

**Comment by taehokangithub** [comment]
Any news for this? I'm having the same problem, no clue so just searching around

**Comment by tomkerkhove** [comment]
Did you check the system logs in Log Analytics if it gives pointers?

**Comment by taehokangithub** [comment]
@tomkerkhove It's only showing provisioning and revision related logs. Does it mean my settings isn't really running KEDA at all?
I've added this and implemented gRPC scaler at the given address, and waiting for something to happen.... 

        minReplicas: siloServerSpec.minReplicas
        maxReplicas: siloServerSpec.maxReplicas
        rules: [
          {
            name: 'scaler'
            custom: {
              type: 'external'
              metadata: {
                scalerAddress: '${scaler.properties.configuration.ingress.fqdn}:80'
                grainThreshold: '300'
              }
            }
          }

**Comment by kendallroden** [comment]
@ahmelsayed Hey were we able to resolve or determine the root cause? Thanks

**Comment by simonjj** [comment]
Closing this issue. Not 100% on what an external scaler refers to in this context but we have KEDA built-in with the ability to provide a custom rule. If you feel strongly please reopen/create a new issue.

**Comment by tomkerkhove** [comment]
@simonjj In KEDA we offer capability to use "external" scaler - https://keda.sh/docs/2.15/scalers/external/

Customers can configure this through the custom rule that you have mentioned, so maybe the person opening this issue could not get that custom rule to workThis should be sup

**Comment by Badabum** [comment]
Tried 100 times to make `external` and `external-push` scaler to work with 0 luck. Tried both intra-environment scaler grpc service, outside of environment grpc service - nothing worked. My service was not even called by the KEDA.
