### ISSUE TITLE
Feature Request: Support Container Apps logging using standard Azure Monitor resource logging practices

### ISSUE THREAD

**Issue by maskati** [microsoft/azure-container-apps#366]
**Is your feature request related to a problem? Please describe**.  
Azure logging practices widely used by most other Azure services include [configuring resource logging using diagnostic settings](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/resource-logs#send-to-log-analytics-workspace) as well as using [standard Azure resource specific tables](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/resource-logs#resource-specific) (rather than custom tables) for Azure resource logs. This architecture supports filtering collected logs by category, collecting metrics, as well as shipping to multiple destinations such as multiple Log Analytics workspaces, Storage Accounts or Event Hubs. It also allows implementing Azure Policy enforced log collection.

**Describe the solution you'd like**.    
Align the Container Apps logging with standard Azure Monitor practices. Use diagnostic settings at the environment and app levels to support collecting system and console logs as well as metrics to desired destinations. This also allows enforcing log collection through Azure Policy.

**Describe alternatives you've considered**.   
The use of Log Analytics data export as a workaround to multiple log destinations, but this is blocked by the use of legacy DCA based custom tables (data export [only supports newer DCR based custom tables](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-data-export?tabs=portal#limitations)).

**Comment by BigMorty** [comment]
We are actively working on exactly this!

**Comment by BigMorty** [comment]
This is now available via the "Logging options" page in the portal for an ACA environment. It can also be set in the CLI when creating a new environment. Soon it will an option in the portal when creating a new environment.

**Comment by martinjt** [comment]
@BigMorty It looks like this has only been partially completed from what I can see. Right now, it looks like it's not using the Diagnostic Settings functionality, but rather something different? This means it doesn't get caught by the Azure Policy, and doesn't allow you to send the Metrics and Logs to EventHubs or Partner solutions. Is this correct or am I missing something obvious.

To be clear, the portal seems to allow you to setup the Diagnostic Settings through the Diagnostic Settings blade, but not through the Container Apps Environment blade. However, once setup, nothing gets sent to EventHubs.

<img width="899" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/1699587/db0fb76f-42c0-46dc-8baf-d5d2808953d1">
