### ISSUE TITLE
Is it possible to open up host ports to map to internal docker container ports in any way other than 80/443? Severe Ingress limitation.

### ISSUE THREAD

**Issue by xtianus79** [microsoft/azure-container-apps#367]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
It doesn't seem possible but I don't think Microsoft should ignore the amount of time and effort it takes a person to come to the conclusion that this is probably not possible. If there is a way I'd like to know. If there is no possible way through any mechanism I would like to know. But the documentation very carefully skirts around the issue and is wildly confusing. 

This here shouldn't be closed it should be discusses because I can't understand how this is being something overlooked. 
https://github.com/microsoft/azure-container-apps/issues/201

I want to bind my host ports to my container ports through internet traffic from the outside. 

On what roadmap was that left off? That makes this product severely limited. Only 80/443? Why? On top of it the recipe seems possible because you're running VNET's and ILB's and you're charging for it. So then, why not let me define the ports. 

Can I at least connect an SLB -> ILB? Can I do that. I can define my ports on the SLB and then make that connect to the ILB. Is this possible? It seems like it should be but I don't think so because you've layer-7 the ingress. So if I can't act upon the ILB to open up ports other than 80/443 then I can't even do what would then make logical sense which would be to take a standard load balancer and hook it up to my VNET so that I could frontface how I want and backend pool how I want. If that's connecting to my internal inside system I should be able to do that. 

Effectively, the way this is now to put it bluntly, I can't connect to anything from the outside world other than 80/443. Layer-7 only. 

Is that the purpose and goal of this product? Because if its then i'm not using it. 

As well, what container system other than using a VM is it possible to connect to the outside world through ports other than layer-7 (80/443)?

**Comment by torosent** [comment]
Hi. Please refer to this announcement https://github.com/microsoft/azure-container-apps/issues/375

**Comment by justinpenguin45** [comment]
> Hi. Please refer to this announcement #375

Although that issue shows progress - there is still a serious limitation in that multiple ports cannot be exposed.
