### ISSUE TITLE
I should be able to setup a docker server i.e., docker.io without using a username and password for public containers

### ISSUE THREAD

**Issue by xtianus79** [microsoft/azure-container-apps#368]
### This issue is a: (mark with an x)
- [] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
It seems that if I just want to use docker.io for a container that is public I shouldn't have to use my credentials to obtain it. Is there a way to go directly to the docker container through an endpoint? If there is it's not very apparent. It's not like docker provides a git clone type http::URL. 

As of now, one has to use the private registry connection in order to pull anything from docker. At least some documentation stating that would be helpful.

**Comment by duglin** [comment]
have you tried providing just the Docker namespace and image name without the docker.io part?  For example, I've used duglin/echo without any auth and it works for me.

**Comment by xtianus79** [comment]
@duglin in the portal you are correct. In the cli that's not the case. you have to set a password and username and server. If the cli functionality was the same it would make sense.

**Comment by duglin** [comment]
@xtianus79 you're correct! Another interesting thing is that it appears I can do an app update on its image w/o a user/password, but a new app create does show the issue you're seeing:
```
$ az containerapp create -n echo1 -i duglin/echo -g default --environment demo2
Registry username and password are required if not using Azure Container Registry.
```

**Comment by duglin** [comment]
ping @anthonychu

**Comment by StrawnSC** [comment]
@duglin and @xtianus79 this is a known issue and we have a fix for this in review right now: https://github.com/Azure/azure-cli-extensions/pull/5241. I'm hoping to get it released this week

**Comment by StrawnSC** [comment]
You can also track this bug with this GitHub issue: https://github.com/Azure/azure-cli-extensions/issues/5253

**Comment by panchagnula** [comment]
please use the latest version which has the fix
 "name": "containerapp",
    "version": "0.3.10"

**Comment by JennyLawrance** [comment]
Closing issue as fix is available.
