### ISSUE TITLE
Env vars using secret references are replacing chosen secret names with the container app's resource name

### ISSUE THREAD

**Issue by bbi-willemtoorenburgh** [microsoft/azure-container-apps#370]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
As described in the title. Using Pulumi, I provisioned a set of Container Apps which have secrets and environment variables referencing those secrets:

```c#
Secrets = new List<Pulumi.AzureNative.App.Inputs.SecretArgs>
    {
        new ()
        {
            Name = "azure-storage-account-key-base64",
            Value = this.PrimaryStorageKey
        }
    }
//...
Env = new List<Pulumi.AzureNative.App.Inputs.EnvironmentVarArgs>
    {
        new ()
        {
            Name = "AZURE_STORAGE_ACCOUNT_KEY_BASE64",
            SecretRef = "azure-storage-account-key-base64"
        }
    }
```

The deployment runs successfully. However, when I view the container app in the portal, the revision is scaled to zero, and the revision is marked as failed. If I create a new revision changing nothing, the revision fails to deploy, with an error message stating it cannot find referenced secrets:

```
Failed to deploy new revision: SecretRef 'capp-my-container-app173d7e0c' defined for container 'container1' not found.
```

For troubleshooting, I tried manually editing the container definition in a new revision to correctly reference the secrets. This deploys successfully, however, when I go to check the new revision, it's marked as failed, and the secret ref is back to the container app's name. This confirms to me that this is an issue on the Container Apps backend, as the behaviour is consistent both in the portal and through the API.

### Steps to reproduce
1. Create a container app
2. Define a secret in that container app
3. Define a container with an environment variable referencing a secret
4. Run the deployment

**Expected behavior** [What you expected to happen.]
I expect the deployment to use the values I provided it, deploy successfully, and for the container to come online with the correct values in the defined env vars.

**Actual behavior** [What actually happened.]
The deployment succeeds, but the new revision is marked as failed (Perhaps deployments reporting success but actually failing is worth it's own issue report? If that isn't related to this issue, that is) and the container doesn't run. SecretRefs are pointing to the container app's resource name, rather than the actual secrets they were pointing to.

### Additional context
I believe this is a regression as I've seen this happen a few months ago. At the time, I thought it was a Pulumi issue and [logged an issue about it](https://github.com/pulumi/pulumi-azure-native/issues/1715), but now I'm not so sure. The issue cleared up on its own, and now it has returned.

**Comment by njuCZ** [comment]
@bbi-willemtoorenburgh thanks for reporting this issue. We have already made a fix, it will be deployed in the upcoming week.
