### ISSUE TITLE
Feature Request: Multiple links to the same container app

### ISSUE THREAD

**Issue by cannehag** [microsoft/azure-container-apps#371]
Unable to link multiple static web apps to use the same container app.

Possibility to link multiple static web apps to the same container app. There might be different UI depending on different usage scenarios, but only one API.

**Comment by anthonychu** [comment]
@annikel Is this possible?

**Comment by cannehag** [comment]
@anthonychu Let's have the approach that everything is possible shall we? :)

**Comment by simonjj** [comment]
You could use the revision URL. Closing this for now, if you feel strongly, please reopen.
