### ISSUE TITLE
How dapr is scoped when multiple revisions are active?

### ISSUE THREAD

**Issue by bppn** [microsoft/azure-container-apps#372]
The dapr id is shared between revisions of the same application.

When multi-revision mode is active, each revision will receive the same dapr id.

We have revisions with labels and traffic configuration (some have 0 traffic, like a development label).

The dapr documentation is stating the possibility of using namespaces for service invocation.
https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-namespaces/

However, how can this be done in azure container apps?  Is there a namespace automatically configured? Or can we configure namespaces manually?

**Comment by ahmelsayed** [comment]
dapr service to service invocation will follow traffic weights on the target (if they are defined, latest otherwise), but you can't address individual revisions from within dapr service to service call.

**Comment by bppn** [comment]
ok, thanks for the information.  We have work around it then.
