### ISSUE TITLE
Access virtual machine on another VNET

### ISSUE THREAD

**Issue by clintsinger** [microsoft/azure-container-apps#373]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We have an old virtual machine hosting SQL server.   We are working on a new API surface that we would like to host in ACA but to do that we need to be able to access the SQL server instance.   

Currently the virtual machine and ACA instance are in the same region but separate resource groups.   They also have their own VNET's that were created by default in each instance.

Is there a way to connect the two so that the ACA can access the SQL server instance on the virtual machine?

**Comment by kendallroden** [comment]
This is more a question on your networking model. If you have a vm deployed within an azure vnet you should be able to use vnet peering etc to ensure the vnet where aca is can communicate to the vm. You will need to bring your own vnet if your sql vm is in a private network. LMK if you have any more questions
