### ISSUE TITLE
TCP Support

### ISSUE THREAD

**Issue by torosent** [microsoft/azure-container-apps#375]
*Update*: ETA to GA: Q2 2023

Hi All,

We have been working for a while on enabling TCP support and are preparing to release it in about 3 weeks as Preview.
Our initial release will support ARM with CLI, Portal and other tools following shortly after. 

### Features:

1. TCP Ingress communication:
    - "transport" should be "tcp" for tcp apps.
    - "external" designates whether the tcp endpoint of the app is reachable outside the environment or only internally in the environment. 
    - "targetPort" is the port the TCP application is listening on
    - "exposedPort" optional port (defaults to the same value as targetPort). Must be unique per environment if the app is external: true. Doesn't have to be unique if the app is internal only. 
2. Scale out configuration: Applications can scale based on the active number of TCP connections. However, during a scale-down operation, it's not guaranteed that active connections will remain undisrupted. If the app is scaled out to 10 instance but should be running at 2, 8 instances will be asked to shutdown, and the clients connected to those instances will have to reconnect. 
3. Traffic splitting with TCP. If you have multiple revisions (rev1, rev2) you can split tcp traffic between them.

### Examples: 

**Redis support with TCP**
```json
{
    "id": "/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.App/containerapps/redis-test-app",
    "name": "redis-test-app",
    "type": "Microsoft.App/containerApps",
    "location": "North Central US",
    "properties": {
        "configuration": {
            "activeRevisionsMode": "single",
            "ingress": {
                "fqdn": "<env name>.azurecontainerapps.io",
                "external": true,
                "targetPort": 6379,
                "exposedPort": 20305,
                "transport": "tcp"
            }
        },
        "template": {
            "containers": [
                {
                    "image": "docker.io/redis:7.0",
                    "name": "redis",
                    "resources": {
                        "cpu": 0.25,
                        "memory": "0.5Gi"
                    }
                }
            ],
            "scale": {
                "minReplicas": 0,
                "maxReplicas": 10,
                "rules": [
                    {
                        "name": "my-tcp-scale-rule",
                        "tcp": {
                            "metadata": {
                                "concurrentConnections": "10"
                            }
                        }
                    }
                ]
            }
        }
    }
}

```
```sh
#You should be able to connect to the app from anywhere using:

$ redis-cli -h <env name>.azurecontainerapps.io -p 20305

#You can also access the app from inside the environment using

$ redis-cli -h redis-test-app -p 20305

```

**Traffic splits between revisions**

```json
{
    "id": "/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.App/containerapps/redis-test-app",
    "name": "redis-test-app",
    "type": "Microsoft.App/containerApps",
    "location": "North Central US",
    "properties": {
        "configuration": {
            "activeRevisionsMode": "single",
            "ingress": {
                "fqdn": "<env name>.azurecontainerapps.io",
                "external": false,
                "targetPort": 6379,
                "exposedPort": 6379,
                "transport": "tcp",
                "traffic": [
                    {
                        "revisionName": "redis-test-app--rev1",
                        "weight": 80
                    },
                    {
                        "revisionName": "redis-test-app--rev2",
                        "weight": 20
                    }
                ]
            }
        },
        "template": {
            "containers": [
                {
                    "image": "docker.io/redis:7.0",
                    "name": "redis",
                    "resources": {
                        "cpu": 0.25,
                        "memory": "0.5Gi"
                    }
                }
            ],
            "scale": {
                "minReplicas": 0,
                "maxReplicas": 10
            }
        }
    }
}
```

**TCP support will address the following issues**
- #276 
- #367 
- #148 
- #113 
- 

**Out of scope items:**

1. UDP Support. #129
2. Exposing more than 1 port in an app. #201

**Comment by clintsinger** [comment]
Will this also include UDP support?

**Comment by clintsinger** [comment]
Will UDP be handled as separate update?

**Comment by torosent** [comment]
Yes but we are still planning how to support UDP so I can't commit to it yet.

**Comment by WagnerJanissetti** [comment]
This is awesome news! I have a few questions regarding this:
- `Price per request`, will that be the same as http requests? [Azure Container Apps pricing](https://azure.microsoft.com/en-us/pricing/details/container-apps/)
- `Exposing ports`, setting `targetPort` and `exposedPort`, can we set more than one port per container? Given your explanation it looks like it will be 1 port exposed per container.
- `Traffic splitting`, it is supported as you described, but will that support the same features described in the [Revisions in Azure Container Apps](https://docs.microsoft.com/en-us/azure/container-apps/revisions)?
- `Scale down`, it doesn't guarantee that requests won't be lost, is that a limitation for tcp protocol requests or is it the same for http requests as well?

**Comment by ahmelsayed** [comment]
> Exposing ports, setting `targetPort` and `exposedPort`, can we set more than one port per container? Given your explanation it looks like it will be 1 port exposed per container.

Correct, it's 1 exposed port per app.

> Traffic splitting, it is supported as you described, but will that support the same features described in the [Revisions in Azure Container Apps](https://docs.microsoft.com/en-us/azure/container-apps/revisions)?

Labels aren't supported yet for tcp. Otherwise, it works the same way, but for TCP connections rather than http requests. 

> Scale down, it doesn't guarantee that requests won't be lost, is that a limitation for tcp protocol requests or is it the same for http requests as well?

When shutting down instances (or replicas), an instance might be asked to shutdown even if it has an active connection or request. It can trap SIGTERM to until it finishes the request or connection it's handling (up to 30 seconds since `terminationGracePeriodSeconds` isn't configurable atm). The scale decision doesn't coordinate with the loadbalancer state. 

New connections or requests to the app will go to active/running instances only, not ones that have been asked to shutdown. If you don't trap or handle SIGTERM then the process will exit right away. As long as the client reconnects (both for TCP and long running http requests like websockets or GRPC streams) then it should be routed to a running instance of the app. 

This is true for both http and tcp. For other event sources (azure queues, service bus, sqs, kafka, rabbitmq, etc) the SIGTERM is the only mechanism to use there to ensure the instance that's processing a queue or a message finishes processing and not dequeue or accept new messages.

**Comment by ravitol** [comment]
This is really good news as we need this capability to connect to a redis cache.  When you say preview will it be private preview or public preview.  How would we go about signing up to enable this capability on our container app ?

**Comment by cybernetic-mountaineer** [comment]
Question...will we be able to support multiple services? I have an application with 2 containers that are tightly coupled. One exposes HTTP on 8080, the other TCP on 10051...will I be able to expose both in version one of this release? 

Also timing on release still this week ish?

**Comment by torosent** [comment]
> connect

It will be available shortly as Public Preview

**Comment by torosent** [comment]
We don't support multiple ports in the same app but it's in the roadmap.

**Comment by ahmelsayed** [comment]
@cybernetic-mountaineer best option to achieve this for now is to run those 2 containers as 2 separate ContainerApps.

A couple of questions to you if you don't mind: I'm assuming that you have a single deployment (say `D1`) that has 2 containers (say `C1` and `C2`) that both communicate to each other over `localhost`, but both `C1` and `C2` need to also be addressable from other applications you're running, right? Why do you have those `C1` and `C2` coupled together over `localhost` as opposed to `C1` communicating with `C2` over a service?

**Comment by cybernetic-mountaineer** [comment]
It's not required at all that they'd need to be running in the same "pod" so to speak. It probably makes more sense to run them as separate services since their lifecycle is decoupled...they could and probably should be two apps in the same app environment.

**Comment by StefanFl** [comment]
Any news when the public preview will start? I am in the process of finishing a customer project and would like to know if I will still have the chance to implement the Redis integration.

**Comment by cybernetic-mountaineer** [comment]
Bump...any timeline for TCP preview to be launched? Thanks!

**Comment by ekalyvio** [comment]
What about health probes for TCP? Will it be anything like that? How can we know if the container works as expected?

**Comment by the-bug** [comment]
@ekalyvio I think this is already supported. Have a look at https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-03-01/containerapps?pivots=deployment-language-bicep#containerappprobetcpsocket

**Comment by ravitol** [comment]
@torosent  - Can you share an ETA on when this would be available for public preview  ?

**Comment by ksaur** [comment]
@ravitol it is already available! https://learn.microsoft.com/en-us/azure/container-apps/ingress?tabs=bash#tcp

Make sure you have the latest version of az cli

**Comment by marshallr12** [comment]
It would be very useful if one could assign at least two ports. Many protocols (http) included specify an insecure and secure port - POP / SPOP, IMAP / IMAPS, FTP / FTPS, etc.

**Comment by sunefred** [comment]
> Make sure you have the latest version of az cli

What version is working for you? I am still getting ""Applications with TCP ingress can only be deployed to Container App Environments that have a custom VNET" with:

```
Bicep CLI version 0.11.1 (030248df55)

azure-cli                         2.41.0

core                              2.41.0
telemetry                          1.0.8

Extensions:
azure-iot                         0.17.3
containerapp                      0.3.13
```

**Comment by ksaur** [comment]
Hmm, the ` 0.3.13` should work.  Maybe try the container version?

```
docker run -it mcr.microsoft.com/azure-cli:latest
az extension add --name containerapp --upgrade
```

Make sure it's there:
```
bash-5.1# az containerapp create --transport 'blah'
az containerapp create: 'blah' is not a valid value for '--transport'. Allowed values: auto, http, http2, tcp.
```

**Comment by ahmelsayed** [comment]
> "Applications with TCP ingress can only be deployed to Container App Environments that have a custom VNET"

The environment still has to have a custom VNET

**Comment by sunefred** [comment]
Checklist

[x] Use `2022-06-01-preview`
[x] Use latest azure-cli (2.41.0)
[x] Use latest containerapp extension (0.3.13). Tcp support checked as per @ksaur suggestion
[x] Use custom VNET

With all that, it still didn't work. However, I figured out the problem!

It is currently not possible to **update** from an older Application Environment and Application without TCP support. I was updating, using Bicep, from an ACA created with `2022-03-01` at which point i got the error. Creating the ACA from scratch works fine.

**Comment by alexbot89** [comment]
> > "Applications with TCP ingress can only be deployed to Container App Environments that have a custom VNET"
> 
> The environment still has to have a custom VNET
> 
> https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-cli

Is custom VNET requirement for the preview only?
Will there be support for the managed VNET on the roadmap?

**Comment by jimseld** [comment]
I discovered these issues when using 2022-06-01-preview:

1. In an ARM template, for "Microsoft.App/containerApps", under "ingress", if using TCP then "allowInsecure" and "traffic" are invalid and must not be specified. Documentation does not mention this.
2. The managed environment *must* have a SKU string specified. Only 1 of the samples shows this, and it is not documented. Insert this at the same level as type, name, location, etc.:
			"sku":
			{
				"name": "Consumption"
			},

**Comment by ahmelsayed** [comment]
Traffic is not invalid. You can still split traffic when using tcp. Labels are not currently supported for tcp revisions. 

targetPort is the port your application is listening on. exposedPort is optional. If not set, it defaults to targetPort, but it can be a different port if needed.

**Comment by jimseld** [comment]
Yes, "traffic" is OK but "label" within it is invalid for TCP connections. Not documented - have to run the script and discover the error.

**Comment by jimseld** [comment]
Another issue with TCP protocol setting. Attempting to make a new revision of a previously deployed wins this error:

Deploy revision
Failed to deploy new revision: Ingress exposed port can only be set on external apps with transport tcp. Port must be in range [1,65535].

**Comment by anthonychu** [comment]
> Another issue with TCP protocol setting. Attempting to make a new revision of a previously deployed wins this error:
> 
> Deploy revision Failed to deploy new revision: Ingress exposed port can only be set on external apps with transport tcp. Port must be in range [1,65535].

@jimseld Is this with the portal? Portal support for TCP should be rolling out over the next week.

**Comment by mattmshell** [comment]
I feel somewhat mislead by the documentation. When you say you `don't support multiple ports in the same app` do you mean applications cannot use loopback/hairpin connections to any port except ingress?

I ask because a commercial app I'm deploying is comprised of several microservices and works fine in ACI but refuses to work on ACA because it can't open sockets to localhost.

**Comment by cri5ti** [comment]
I have been trying to connect from one internal app to another internal app (a postgres container) and after many hours of troubleshooting I finally worked out an inconsistency when moving from http to tcp:

With `http` transport, you need to use the FQDN hostname to connect across apps:
 * for internal apps: `<app>.internal.<appsEnvDomain>`
 * for external apps: `<app>.<appsEnvDomain>`

With `tcp` transport the internal FQDN hostname doesn't work when using internal to internal connection:
 * for internal apps: `<app>` (without the `.internal.<appEnvDomain>` suffix)
 * for external apps, both the `<app>` and FQDN `<app>.<appsEnvDomain>` work.

**Comment by dneogi** [comment]
I have two ports exposed in my docker file: 8080 and 9000
My app has HTTP listening on port 8080 and gRPC on 9000.
Using Azure Container Instance, I can get my docker image to work correctly.
However, using Azure Container App, I am unable to expose both the ports. I tried with TCP but that still allows exposing one port. Am I missing something or is this a limitation of Azure Container Apps?

**Comment by ekalyvio** [comment]
I found a problem with TCP. I create 2 different TCP ingress container apps in the same environment (both of them accepting traffic from anywhere). One is listening on port 8000. The other on port 8001.
The one listening on 8000 has application Url xxx.canadacentral.azurecontainerapps.io:8000.
The one listening on 8001 has application Url yyy.canadacentral.azurecontainerapps.io:8001.

If I use just the first Url (eg xxx.canadacentral.azurecontainerapps.io), I can hit both ports (8000 & 8001) and get the respective answers. The same exact thing is happening if I use the other Url. I get the exact same answers.

It seems like both application Urls hit the exact same container apps. Since they are on the same environment they should share the same Url instead of having separate ones.

**Comment by ahmelsayed** [comment]
Both FQDNs do resolve to the same external IP address, but the port is what distinguishes the app (since environments today only use 1 external IP address). 

i.e: `curl xxx.canadacentral.azurecontainerapps.io:8000` is the same as `curl $(dig xxx.canadacentral.azurecontainerapps.io +short | head -n 1):8000`

The fqdn just helps resolve the external IP of the environment, but it's a wildcard dns record.

**Comment by filleokus** [comment]
I have a kind of a niche use case where I need to receive untouched tcp packets on port 80 and 443 inside my app.

Just to confirm that I'm reading the docs correct, this is not supported right?

> `exposedPort`: (TCP ingress only) The port used to access the app. **If external is true, the value must be unique in the Container Apps environment and cannot be 80 or 443.**

Are there any plans on supporting this in the future?

**Comment by ahmelsayed** [comment]
If 80 and/or 443 are the ports the client must use and it's an external app, then unfortunately yes it's not possible as the doc mentiones.

Today each environment has 1 external IP address, and ports 80/443 are reserved for the default http ingress.

**Comment by duglin** [comment]
@filleokus do you need the client to use 80/443 or just that the code in the app needs to listen on 80/443 but you can have the client some other ports?

**Comment by filleokus** [comment]
Sorry for the late response.

> @filleokus do you need the client to use 80/443 or just that the code in the app needs to listen on 80/443 but you can have the client some other ports?

No, the clients are normal browsers so I need to expose 80/443. I'm basically just answering simple HTTP(s) but with a very large amount of domains whose certs I need to manage (fetch/generate) in my own code, and thus own the whole TLS termination. A L4 load balancer + two small VM's work today, but would have been neat to simplify the setup.

> Today each environment has 1 external IP address, and ports 80/443 are reserved for the default http ingress.

Makes total sense, and I get this is not a common use case - just wanted to double check. Thanks!

**Comment by 0GiS0** [comment]
Hi all,

I was trying to test this with no success. These are my example:

```
# Variables
RESOURCE_GROUP="containerapps-demo"
LOCATION="westeurope"
CONTAINERAPPS_ENVIRONMENT="tcp-demo"
VNET_NAME="demo-vnet"

# Create a resource group
az group create --name $RESOURCE_GROUP --location $LOCATION

# https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom-internal?tabs=bash&pivots=azure-cli
# Create vnet
az network vnet create \
  --resource-group $RESOURCE_GROUP \
  --name $VNET_NAME \
  --location $LOCATION \
  --address-prefix 10.0.0.0/16

# Network subnet address prefix requires a CIDR range of /23.
az network vnet subnet create \
  --resource-group $RESOURCE_GROUP \
  --vnet-name $VNET_NAME \
  --name infrastructure-subnet \
  --address-prefixes 10.0.0.0/23

INFRASTRUCTURE_SUBNET=$(az network vnet subnet show --resource-group ${RESOURCE_GROUP} --vnet-name $VNET_NAME --name infrastructure-subnet --query "id" -o tsv | tr -d '[:space:]')

# Create an environment
az containerapp env create \
  --name $CONTAINERAPPS_ENVIRONMENT \
  --resource-group $RESOURCE_GROUP \
  --location "$LOCATION" \
  --infrastructure-subnet-resource-id $INFRASTRUCTURE_SUBNET \
  --debug

# Deploy services

#### Redis #####
az containerapp create \
  --name redisdb \
  --resource-group $RESOURCE_GROUP \
  --environment $CONTAINERAPPS_ENVIRONMENT \
  --image docker.io/redis:7.0 \
  --target-port 6379 \
  --exposed-port 20305 \
  --ingress 'external' \
  --transport tcp \
  --cpu 0.25 --memory 0.5Gi

az containerapp logs show --resource-group $RESOURCE_GROUP -n redisdb --container redisdb

# With TCP ingress enabled, your container app features the following characteristics:

# The container app is accessed via its fully qualified domain name (FQDN) and exposed port number
# Other container apps in the same environment can also access a TCP ingress-enabled container app by using its name (defined by the name property in the Container Apps resource) and exposed port number

# Create client for that redis to test it
az containerapp create \
  --name redis-client \
  --resource-group $RESOURCE_GROUP \
  --environment $CONTAINERAPPS_ENVIRONMENT \
  --image docker.io/redis:7.0 
  
az containerapp logs show --resource-group $RESOURCE_GROUP -n redis-client  --container redis-client --follow

az containerapp exec --name redis-client -g $RESOURCE_GROUP 

# Commands inside container
redis-cli -h redisdb -p 20305
SET mykey "Hello\nWorld"
GET mykey
```

When I execute the commands from inside  nothing happen

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/175379/208234182-8622f29d-6c55-46d5-90a0-65943e1ffc41.png">

Any ideas? 

Thank you so much!

**Comment by mustafazeya** [comment]
> 

@torosent Do we have some issue which we can track for this?

**Comment by ahmelsayed** [comment]
@0GiS0 This seems to be some issue with how `az containerapp exec` redirects the terminal. It doesn't seem to be sending the correct carriage return when you hit enter at the end of the command. 

You can try something like 

```
# redis-cli -h redisdb -p 20305 PING
PONG
# redis-cli -h redisdb -p 20305 SET mykey "Hello\nWorld"
OK
# redis-cli -h redisdb -p 20305 GET mykey
"Hello\\nWorld"
#
```

or the portal console UI which seems to handle this fine as well
![image](https://user-images.githubusercontent.com/645740/210426419-79d6ff64-32e2-4277-8dcb-ed5ec7b85d61.png)

/cc @anthonychu for the CLI issue.

**Comment by ahmelsayed** [comment]
@mustafazeya which issue are you referring to?

**Comment by anthonychu** [comment]
Thanks @0GiS0 @ahmelsayed. Created internal bug 16702144 to track the CLI issue.

**Comment by merou** [comment]
I noticed that tcp connectivity between container apps in the same aca env starting to work when re-creating the env as stated by  @sunefred - would it be possible to have an option in the env to update to a newer version (like versions for AKS), instead of recreate it?

**Comment by Zapnologica** [comment]
Good day,

I would like to know why there is only 1 port available per instance.

it's quite common to have multiple different ports.  For example the service port and the UI or management web port.

**Comment by ahmelsayed** [comment]
> Good day,
> 
> I would like to know why there is only 1 port available per instance.
> 
> it's quite common to have multiple different ports. For example the service port and the UI or management web port.

tracked in https://github.com/microsoft/azure-container-apps/issues/546

**Comment by SophCarp** [comment]
Closing issue, as it's GA

**Comment by mburumaxwell** [comment]
Is a custom VNET still required for GA? I ask because the docs are not yet updated to reflect the switch to GA.

**Comment by ahmelsayed** [comment]
> Is a custom VNET still required for GA? I ask because the docs are not yet updated to reflect the switch to GA.

Only for publicly exposed TCP apps. Internal TCP apps/endpoints don't require a VNET.

**Comment by mburumaxwell** [comment]
> > Is a custom VNET still required for GA? I ask because the docs are not yet updated to reflect the switch to GA.
> 
> Only for publicly exposed TCP apps. Internal TCP apps/endpoints don't require a VNET.

Is it an infrastructural limitation? Is there a possibility that the publicly exposed apps would work with the managed VNET in the future?
