### ISSUE TITLE
Failed request to an app shouldn't retry

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#377]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
It appears that when a request reaches an instance of my app and then the instance is killed (due to me updating my app), the request is retried against the new instance/pod. This shouldn't happen as it could have unintended side effects, like the request resulting in almost twice the work being done. Once a connection is established with an instance, if the connection is dropped then the request should just be allowed to fail (and the http error code returned to the client) and the client can decide if it wants to try again based on the error.

The only time we should retry (if you can call it that) is if we can't establish a connection at all with the instance. 

On a side note, and probably a second issue, the original connection should NOT be killed due to a the app changing. Existing connections should be allowed to complete while new connections are sent to the next version of the app.

### Steps to reproduct
1. deploy an app (e.g. image=duglin/echo)
2. send a request to the app that sleeps for 60 seconds (e.g. curl APP_URL?sleep=60)
3. after 30 second, update the app (e.g. duglin/helloworld)
4. the curl will return after about 90 seconds (not 60) and it'll show the output from the new image, not the original

**Expected behavior** [What you expected to happen.]
- existing connection is allowed to complete

**Actual behavior** [What actually happened.]
- connection is dropped and retried against the new version of the app

**Comment by kendallroden** [comment]
Hey @ahmelsayed can you confirm if this is intended behavior or if this is an issue we should revisit? Thanks

**Comment by kendallroden** [comment]
took offline
