### ISSUE TITLE
GRPC/HTTP2 Support? 

### ISSUE THREAD

**Issue by mikeball** [microsoft/azure-container-apps#38]
I would like to run grpc servcies with container apps, and so created a grpc service serving http2 cleartext and works with BloomRPC and Insomnia when run locally as docker container. However attempts to connect to the grpc service from public url when the image is deployed as a container app fail with error "14 UNAVAILABLE: TCP Read Failed"(bloom) and "13 Received RST_STREAM with code 2"(insomnia).

I believe I saw it mentioned in a video that via the dapr sidecar that grpc is supported. What's the status of GRPC support in container apps? Can GRPC be access from public url? Only when using dapr sidecar? Only within the subnet?

**Comment by ahmelsayed** [comment]
@mikeball can you make sure you set `--trasport http2` or 

```json
"properties": {
    "configuration": {
        "ingress": {
            ...
            "transport": "http2",
        }
    },
...
```

**Comment by andreasfrosig** [comment]
@mikeball To my knowledge the enabling of http2 is not doable through the UI, so you need to run the command:
`az containerapp update --name {container app name} --resource-group {rescource group name} --transport http2`
In general a lot on options are only doable through the client, so `az containerapp update --help` is very helpful.

**Comment by mikeball** [comment]
Originally the app was created using the ui, but unfortunately after updating the transport to http2 using the cli requests still fail with same error messages. I also tried transport = auto, and that made no difference either.

I'm pretty confident the app is using http2 cleartext and responding. Here's the response when I run the container locally.
```
> sudo docker run --name hello-grpc -i -t --rm -p 8080:8080 myregistry.azurecr.io/hello-grpc:mytag
```
```
> curl -i --http2-prior-knowledge http://localhost:8080

HTTP/2 200
content-type: text/plain; charset=utf-8
date: Fri, 19 Nov 2021 16:19:34 GMT
server: Kestrel

grpc service...%
```

This is the request I get from container app
```
> curl -i --http2-prior-knowledge https://hello-grpc-canada.bluemushroom-myappid.canadacentral.azurecontainerapps.io/

HTTP/2 502
date: Fri, 19 Nov 2021 16:32:48 GMT
content-length: 0
```

**Comment by andreasfrosig** [comment]
Maybe a stupid question: but are you sure that you forward to the port from the ingress? if not it will not start and you get an error i believe.
I get the following when i use you call (to my service).
HTTP/2 404
date: Mon, 22 Nov 2021 08:10:49 GMT

**Comment by mikeball** [comment]
Confirmed that ingress is enabled and ingress visibility is set to external, and target port set to 8080.
```
"configuration": {
    "ingress": {
      "allowInsecure": false,
      "external": true,
      "targetPort": 8080,
      "transport": "Http2"
    },
  }
```

I also have the web server(kestrel) set to use http2 only, does the container need to serve HttpProtocols.Http1AndHttp2 perhaps?

**Comment by andreasfrosig** [comment]
No it does not. I have the same set and mine runs as expected.

**Comment by ahmelsayed** [comment]
@mikeball 

This is a sample of an app that works for me: https://github.com/ahmelsayed/grpc-test 


_it's just the output of `dotnet new grpc -o GrpcGreeter`, but I added Reflections to enable `grpcurl` below_


```console
$ az containerapp create --name grpc-app-test --environment test-env-302 -g test-rg-302 --image docker.io/ahmelsayed/grpc-stuff:1 --target-port 80 --ingress 'external' --transport http2 --query configuration.ingress.fqdn

https://grpc-app-test.calmplant-3d9a21e6.centraluseuap.azurecontainerapps.io
```


then 

```console
$ curl -i --http2-prior-knowledge https://grpc-app-test.calmplant-3d9a21e6.centraluseuap.azurecontainerapps.io/
HTTP/2 200
content-type: text/plain; charset=utf-8
date: Mon, 22 Nov 2021 20:21:21 GMT
server: Kestrel

Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909%

$ grpcurl -vv -d '{"name": "World"}' grpc-app-test.calmplant-3d9a21e6.centraluseuap.azurecontainerapps.io:443 greet.Greeter/SayHello

Resolved method descriptor:
rpc SayHello ( .greet.HelloRequest ) returns ( .greet.HelloReply );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc
date: Mon, 22 Nov 2021 20:20:33 GMT
server: Kestrel

Estimated response size: 13 bytes

Response contents:
{
  "message": "Hello World"
}

Response trailers received:
(empty)
Sent 1 request and received 1 response
```

**Comment by ahmelsayed** [comment]
Can you check the logs for your application in the env Log Analytics workspace, do you see any crashes or errors there?

**Comment by takekazuomi** [comment]
Hello, I also checked the operation with golang. Write what I noticed.
When I first deploy the containerapp with transport 'auto' and then change it to 'http2', I still can't communicate.

From the beginning, deploying with transport 'http2' will work. It also works if you remove the containerapp and then deploy with transport 'http2'.

If you get the following error, we recommend that you remove and recreate the containerapp.
> upstream connect error or disconnect / reset before headers. reset reason: connection termination

My verification code is here.
https://github.com/takekazuomi/golang-grpc02

**Comment by ahmelsayed** [comment]
Thanks @takekazuomi This is definitely a bug. Changing values under `configuration`, like `ingress`, doesn't generate a new revision. However, the upstream http2 prior knowledge setting is being read from the revision config. Causing a new revision (by changing the image or env var) should get it to start working (or deleting and recreating the app). Will have a fix for this soon.

**Comment by mikeball** [comment]
Thanks @ahmelsayed I was able to get a new app deployed using the cli and was able to successfully call the service using grpcurl.

I did run into a couple problems:
- Attempts to create a container app using yaml file failed because http2 is not an allowed transport, only http and auto were allowed.
- Requests made with 2 different ui client insomnia & bloomrpc both fail where grpcurl works. I suspect many people will be using these tools and get apparent failures as I did.

```
az containerapp create \
        --name hello-grpc5-canada \
        --resource-group myresourcegroup-canada \
        --environment my-app-environment-canada \
        --target-port 8080 \
        --ingress external \
        --transport http2 \
        --registry-login-server "myregistry.azurecr.io" \
        --registry-username "myuser" \
        --registry-password "mypass" \
        --revisions-mode single \
        --image myregistry.azurecr.io/hello-grpc:8396e6f
```

grpc curl call:
```
grpcurl -vv -proto "greet.Proto" -d '{"name": "bob"}' hello-grpc5-canada.bluemushroom-e1065d34.canadacentral.azurecontainerapps.io:443 greet.Greeter/SayHello

Resolved method descriptor:
// Sends a greeting
rpc SayHello ( .greet.HelloRequest ) returns ( .greet.HelloReply );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc
date: Tue, 23 Nov 2021 17:29:29 GMT
server: Kestrel

Estimated response size: 15 bytes

Response contents:
{
  "message": "Howdy bob ..."
}

Response trailers received:
(empty)
Sent 1 request and received 1 response
```

**Comment by mikeball** [comment]
> Can you check the logs for your application in the env Log Analytics workspace, do you see any crashes or errors there?

Could you give us a super simple step by step explanation how to look a the logs? For the life of me I can't find anything related to container apps when I go into the log Analytics workspace, it's a mystery.

**Comment by ahmelsayed** [comment]
@mikeball it looks like BloomRPC and Insomnia need to be explicitly set to use TLS instead of plaintext. By default all container apps will do a 301 redirect for any plaintext traffic to the https endpoint. But grpc doesn't handle 3xx http. 

For BloomRPC it's under TLS
 
![FmADplZ2YB](https://user-images.githubusercontent.com/645740/143137185-7aebe46f-ec29-49b5-a3a8-c87f17380966.gif)
 

For Insomnia, you need to prefix the url with `grpcs://` (https://docs.insomnia.rest/insomnia/grpc)

![an41Rhn2AT](https://user-images.githubusercontent.com/645740/143137645-1c0b59b5-a6ac-4973-9fb2-d59c05d37ca4.gif)

I'm adding a `allowInsecure` property on the ingress (default: `false`) to allow disabling tls redirect if user wants plaintext (which makes more sense for `internal` ingress apps.

**Comment by ahmelsayed** [comment]
> > Can you check the logs for your application in the env Log Analytics workspace, do you see any crashes or errors there?
> 
> Could you give us a super simple step by step explanation how to look a the logs? For the life of me I can't find anything related to container apps when I go into the log Analytics workspace, it's a mystery.

You can open the Log Analytics workspace you've created for the environment. Then from the left, click on `Logs`

![image](https://user-images.githubusercontent.com/645740/143138942-3190f2e8-2e85-4fd6-b971-0a74e54cec6c.png)
 
Then you can begin writing queries there 

![UsaZiiT8w4](https://user-images.githubusercontent.com/645740/143139762-5f0c66e9-e4e0-42db-ac73-5c9f3b9f34f1.gif)

```kusto
ContainerAppConsoleLogs_CL
| where TimeGenerated > ago(1d)
| where ContainerAppName_s == "grpc-app-test"
```

_If you're not familiar with that query language, it's [KQL (Kusto Query Language) ](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/), and this is a quick [written](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/log-analytics-tutorial) or [video](https://www.microsoft.com/en-us/videoplayer/embed/RWxNOq) tutorial_ 


The log table there, `ContainerAppConsoleLogs_CL`, should contain all stdout logs from the app (and dapr). There other tables that need to be added.

**Comment by takekazuomi** [comment]
It will take some time for ContainerAppConsoleLogs_CL to be displayed. It takes a few minutes in my environment.

@ahmelsayed 
The story will be off, but please let me know if you like. Can I see anything other than the container's stdout/stderr?

for example
ACI EventLog https://docs.microsoft.com/en-us/azure/container-instances/container-instances-get-logs#get-diagnostic-events
or
Container insights on AKS
https://docs.microsoft.com/en-us/azure/aks/monitor-aks#container-insights

**Comment by mikeball** [comment]
@ahmelsayed you are awesome! Thank you so much.

**Comment by joseph-hungerman** [comment]
I don't know how this was fixed, but I am still experiencing this issue with an Aspire app deployment
![Screenshot 2024-06-21 125000](https://github.com/microsoft/azure-container-apps/assets/149249449/07da8194-3642-4549-ad7a-108ce99e1e7b)
This is with everything set to HTTP2 transport. If I switch it to auto I end up with "Request protocol of 'HTTP/1.1' is not supported." from the server.
