### ISSUE TITLE
Provisioning fails on every deploy with internal server error

### ISSUE THREAD

**Issue by ChristophHornung** [microsoft/azure-container-apps#380]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Whenever I try to provision my container app I get a `Failed` provisioning status and a notification reading:

Deploy revision
Failed to deploy new revision: Internal server error occurred. correlation ID: 987230fd-d684-47b6-a69c-750696418af2

### Steps to reproduct
1. Revision management -> create new revision
2. Change something then "Create".

**Expected behavior** 
The provisioning to succeed.

**Actual behavior**
The provisioning fails.

**Screenshots**         
<img width="641" alt="image" src="https://user-images.githubusercontent.com/18534790/187406390-2fe75536-1ed9-41b9-af6b-61db0cd54cce.png">
<img width="342" alt="image" src="https://user-images.githubusercontent.com/18534790/187406458-aefdc5d8-d2b7-4fc7-a7b3-7aaaf72b2a76.png">

### Additional context
If I try to query the ContainerAppSystemLogs_CL I get query timeouts. 

A nearly identical aca (only one environment variable is different) is running fine at the moment.

**Comment by ChristophHornung** [comment]
After retrying the log query I got a few entries like the following from ContainerAppSystemLogs_CL
|   |   |
|---|---|
|TenantId|myTenantId|
|SourceSystem|RestAPI|
|TimeGenerated [UTC]|2022-08-30T09:28:32.475Z|
|Error_s|2/2 Pending:ImagePullBackOff|
|time_t [UTC]|2022-08-30T09:28:31.515Z|
|_timestamp_d|1661851711.51509|
|Log_s||Error provisioning revision.|
|Level|info|EnvironmentName_skindfield-e52636d3|
|RevisionName_s|ca-byk-dewc-smart-web-testing--oqzj0ka|
|Type|ContainerAppSystemLogs_CL|

**Comment by scottydog75** [comment]
Experiencing the exact same issue in Australia East. Provisioning fails and logs timeout.

**Comment by tomkerkhove** [comment]
This is due to a live site incident: https://status.azure.com/en-us/status

**Comment by fernandodelacalle** [comment]
same for eu-west, it fails when try to pull the image.

**Comment by Hoang-Minh** [comment]
Same here for us-west-2, its time out when trying to pull the image

**Comment by relax94** [comment]
Same for east-us-2

**Comment by naushadmohammed** [comment]
Same for eu-west. It fails with the error : `1/1 Pending:ImagePullBackOff`

**Comment by tjoudeh** [comment]
Same here, no containers are created...  East US Region

![image](https://user-images.githubusercontent.com/3114431/187557803-23a08465-43d7-4ac4-a265-56bf872b50e6.png)

**Comment by mgarf** [comment]
same

**Comment by Hoang-Minh** [comment]
I had to stop my azure aks cluster, then restarted it for the images to be pull back properly.

**Comment by tjoudeh** [comment]
@Hoang-Minh Wish I can do the same, on ACA we don't have control over AKS. I will try to create a new revision now, hopefully, it work!!

**Comment by alexbot89** [comment]
westus has been busted for a while, it's unfortunate that ACA does not allow you to restart the node pool like you can in AKS, maybe this should be a feature request.

**Comment by torosent** [comment]
Hi All. I'm very sorry for the inconvenience. We mitigated the issue for most environments and only a small subset remains. 
The fix is actually more complicated than just restarting the AKS cluster and requires a few configuration changes. This is the reason AKS is also still showing an outage. 
We are working with the relevant teams to mitigate the issue and will provide an RCA once this incident will be mitigated completely.

**Comment by StefanFl** [comment]
Thanks for the info @torosent. My instance in West Europe still has this issue.

**Comment by torosent** [comment]
> Thanks for the info @torosent. My instance in West Europe still has this issue.

Can you send your subscription id and env name to acasupport at Microsoft dot com?

**Comment by tomgallagher** [comment]
I also still have this problem in UK South. I'd be happy to send a subscription id and env name to an email address. Can you detail the right email address? @torosent

**Comment by torosent** [comment]
> I also still have this problem in UK South. I'd be happy to send a subscription id and env name to an email address. Can you detail the right email address? @torosent 

acasupport at microsoft dot com

**Comment by StefanFl** [comment]
>  Thanks for the info @torosent. My instance in West Europe still has this issue.
> 
>> Can you send your subscription id and env name to acasupport at Microsoft dot com?

Support has fixed it for me :-)
