### ISSUE TITLE
Can we use Image from Azure container registry which is in different subscription

### ISSUE THREAD

**Issue by ranjeetkpGit** [microsoft/azure-container-apps#383]
Hi,
Can we use an image from Azure container registry which is in different subscription (sub2)?
Container app is in different subscription (sub1).

az containerapp up --name 
                                    [--image]
                                     [--registry-password]
                                    [--registry-server]
                                   [--registry-username]

**Comment by kendallroden** [comment]
yes. you can also use managed identity to do the image pull and do not need the username and password if using that approach
