### ISSUE TITLE
GET /dapr/config 404  Scale 0-1 service bus item bus handled multiple times

### ISSUE THREAD

**Issue by sf-declanomalley** [microsoft/azure-container-apps#384]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
experiencing an issue with dapr sidecar picking up service bus topic item multiple times for a single subscription due to receiving an error (404) when the application is trying to retrieve dapr/config. This results in the service bus item being handled multiple times but the service is completing the request successfully both times. 

Have found this to be an issue with a scale rule of 0-1 only. when we change to 1-1 we do not get this issue and the dapr sidecar only forwards on the request to the application once.

### Steps to reproduce
1. .NET 6  minimal web api subscribing to the dapr sidecar pubsub
```
app.MapPost("/send", async (TestModel message){
    return Results.Ok();
})
.WithName("Test")
.WithTopic(Constants.DaprServiceBusComponentName, Constants.SendEmailRequestTopicName);
```
2. deploy to container apps with scale rule of 0-1
3. the issue doesn't display straight away but after some time
4. add message to service bus topic
5. application will be sent message twice
![image](https://user-images.githubusercontent.com/79090955/187948223-4288c219-766a-4402-bc89-fa57f86b7de8.png)

**Expected behavior** [What you expected to happen.]
dapr sidecar only sends request once to application
**Actual behavior** [What actually happened.]
dapr is sending the same message twice
**Screenshots**

**Comment by kendallroden** [comment]
Hi @sf-declanomalley can you help me understand how the 404 for config (which basically just means you arent using actors) and the duplicated read are related? It looks like this is a strange issue but were you able to confirm its related to the 404 or are you correlating the two just because you aren't sure why this behavior is happening? we will look into this.

**Comment by kendallroden** [comment]
ping ^

**Comment by ekjuanrejon** [comment]
i'm having the same issue. Not that is is affecting the system... it's polluting our logs in app insights... seeing a lot of 404 /dapr/config

**Comment by MichielCMM** [comment]
We see this same log pollution in app insights 

![Image](https://github.com/user-attachments/assets/de575536-f635-4e8c-9e7f-72a7d55c6b84)
