### ISSUE TITLE
Bug: Container App Revision - No external calls successful

### ISSUE THREAD

**Issue by marvinbuss** [microsoft/azure-container-apps#385]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
This issue started after the larger outage yesterday. Before, it worked fine for months since the release. I am experiencing issues when applying an ARM template with a new revision suffix. Apparently, the new revision becomes unresponsive. The container successfully starts and we can see the log stream as well as the probes running against the container, but no external API calls are successful. They don't even reach the container. When we create a new revision manually in the portal where we only change the revision suffix, the container becomes available for external API calls again.
Nothing else is changed in the new ARM template except for the suffix. Would be great to get some help here.

### Steps to reproduct
1. Re-apply ARM template and change revision suffix
2. Call API and see that Web App running on teh same Vnet cannot reach the endpoint anymore

**Expected behavior** [What you expected to happen.]
Revision is available for external API calls from the same Vnet.

**Actual behavior** [What actually happened.]
Revision is not available for external API calls.

**Screenshots**         
Not required. Let me know if this is required.

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
ARM/Bicep. After update through the Portal, the new revision works again as expected.

**Comment by marvinbuss** [comment]
I identified that this is related to the `revisionSuffix`. When choosing a suffix that is longer than 28 characters, I am able to reproduce the error. When reducing the length of the `revisionSuffix` to anything less than or equals to 28 characters, my container runs without issues.
CC @torosent

**Comment by kendallroden** [comment]
Thanks Marvin for reporting- looks like it is being investigated by @torosent

**Comment by marvinbuss** [comment]
I also noticed recently that this depends on the length of the container app name. So if your container app name is longer, it may happen that your `revisionSuffix` needs to be shorter than the 28 characters mentioned above.

**Comment by torosent** [comment]
fixed

**Comment by marvinbuss** [comment]
Thanks for the update @torosent . Great work!
