### ISSUE TITLE
Feature Request: support maxConcurrentRequests

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#386]
Today `concurrentRequests` is defined as the trigger when an app is scaled up. However, there's also the need for the user to specify that each instance of their app can't support more than a certain number of requests at a time - and therefore the infrastructure should not send any additional requests to that instance. This will often happen when the processing of requests is cpu/memory intensive and they can therefore only handle a fixed number of requests at a time.

This isn't something the app can fix themselves because their choices would be:
- reject the additional requests, which isn't what the app's users would expect
- buffer the additional requests until existing connections are done, which means the latency of these requests will not be what's expected since there will likely be other instances of the app waiting to process requests and could meet the app's latency expectations

I would suggest that we add a new option so the user can specify the maximum number of requests allowed per instance. The infra (activator?) would then hold on to the request until an available instance becomes ready. It might be nice to rename "concurrentRequests" to something like "targetConcurrentRequest" to indicate that it's a soft-limit and not a hard one, which today's naming could imply (at least to me it did until I read the docs).

**Comment by simonjj** [comment]
Closing this, please reopen if you feel strongly.
