### ISSUE TITLE
Feature Request: Add aibility to set concurrentRequests via the CLI

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#387]
Unless I missed it I don't see a way to set the `concurrentRequests` parameter via the ACA Azure CLI. It would be really nice to support that so I don't need to visit the portal to do so.

**Comment by anthonychu** [comment]
This has been added to `az containerapp create/update` in version 0.3.11 of the extension. Use `az extension add -n containerapp --upgrade` to update and confirm with `az --version`.

```bash
az containerapp create -n myapp -g mygroup --environment myenv --image nginx \
            --ingress external --target-port 80 \
            --scale-rule-name my-http-rule \
            --scale-rule-http-concurrency 50
```

**Comment by duglin** [comment]
excellent! thanks @anthonychu
