### ISSUE TITLE
Feature Request: support setting the scaled-down time

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#388]
There doesn't seem to be a way for a user to tell ACA how long an instance of their app should be idle before it is scaled down. From my testing it appears that it takes about 10 minutes before an instance is terminated. That's a really long time for a consumption based model if customers are cost conscious. I would recommend two things:
1 - add a way for the user to set it on a per app basis
2 - make the default something much smaller than 10 minutes, something more like 10 seconds

Another variant would be to also add a scale-down time for the "last instance" since scaling from zero to one (cold start times) are usually a very sensitive topic for customers - so allowing the last instance to live longer than the 2+ instances is a really nice customization option.

Being able to set it on a per environment might be nice too, but per app initially would be a huge benefit.

**Comment by duglin** [comment]
I think we need both n->n-1 and 1->0 (or if this isn't specified the default to the n->n-1 value)

**Comment by kendallroden** [comment]
I agree on this and its a customer request we have received. Will consider if we can make these settings available in RP

**Comment by rhuanbarreto** [comment]
For me the most important is the cooldown period. For development workloads which scale from 1 to 0, we want to set the cooldown period to 3600 seconds (1 hour) to avoid cold starts but still be cost effective to scale to 0 if not used. For production, which scale from n to n-1 replicas, 300s is good enough but it could be better to control the ramp so we avoid abrupt changes

**Comment by bastiennoel93** [comment]
Cool down period not yet available in azure container app scale rules? 
I tried to customize this rule:
![image](https://github.com/microsoft/azure-container-apps/assets/18250350/0f5133cd-a1a2-4511-a765-e7727723dabb)

But when I look the monitoring, I see that the cool down period remains at 300:
![image](https://github.com/microsoft/azure-container-apps/assets/18250350/b1f973f0-fd57-4f97-a60c-676369efde4c)

**Comment by aaltotsky** [comment]
This issue become a major cost problem. We have an API that runs every 15 min. My preference is to scale the container down in 60 sec (not 300). This will save us 16 minutes per hour of the unused containers. Any updates on this?

**Comment by klemmchr** [comment]
Also interested into this. Would like to customize the cool down period for http scalers.

**Comment by fijsh** [comment]
I also couldn't find a way to do it with an Azure ServiceBus scaling rule. This option should be added together with stabilization window scale-up/down settings.

**Comment by kacperwojtyniakcf** [comment]
What is the status of this? We could really use more flexibility around cool down period.

**Comment by syky27** [comment]
Do I really need to create a cron job on other server to wake up the app via ingress? Can we get an status update on this please? Thank you.

**Comment by kacperwojtyniakcf** [comment]
@kendallroden what is the status of this?

**Comment by jsheetzmt** [comment]
Also would like to change the cooldown period for 1 -> 0. Our non-prod container apps are setup to scale to zero, and it works great. However, a 60 minute cooldown would be preferable during work hours to keep instances running. Then, we can scale to zero during nights/weekends when we are not working.

**Comment by lemeow125** [comment]
+1 to @jsheetzmt's comment. We also require non-prod containers to have a higher cooldown before shutting off. We have some tasks that get cut off due to the scaler shutting down the container

**Comment by kacperwojtyniakcf** [comment]
Maybe @duglin can help?

**Comment by kacperwojtyniakcf** [comment]
@duglin Do you happen to have any update on this?

**Comment by nikkag** [comment]
+1 to this request. We have a similar use case as @jsheetzmt

**Comment by Mithgroth** [comment]
Can we please have an update on this one? It's been a year and a half.

**Comment by miroslavgrozdanovski** [comment]
This might be a deal breaker for us using ACA much more extensively across multiple projects/clients, so an update is really needed.

**Comment by a30018417** [comment]
Same here, appreciate an update on this feature please

**Comment by TripleBrass** [comment]
Our organization is highly interested in this feature and it alone may be a deal breaker on adopting container apps or not.  Would love some input from the team.

**Comment by hieutomra** [comment]
+1

**Comment by manusisnova** [comment]
+1

**Comment by roshan-mosaicai** [comment]
+1 I actually need this so that we can keep the container apps running for long since the cold start is bit longer for one of our app

**Comment by wklepacki** [comment]
+1

**Comment by FilippTrigub** [comment]
+1 from me as well!

Got some apps running long computational jobs, which KEDA seems to ignore and just downscale the app.

**Comment by mateusz-wosinski-ds** [comment]
any news on that?

**Comment by nbarichev** [comment]
+1

**Comment by heydenb** [comment]
+1

**Comment by anthonychu** [comment]
The ability to configure cooldownPeriod and pollingInterval were added in API version [2024-10-02-preview](https://learn.microsoft.com/en-us/rest/api/resource-manager/containerapps/container-apps/create-or-update?view=rest-resource-manager-containerapps-2024-10-02-preview&tabs=HTTP#scale). Currently accessible in ARM/Bicep. It should be enabled in the portal in January.

![Image](https://github.com/user-attachments/assets/a8037243-5976-46bb-a7b2-4b078737296f)

**Comment by anthonychu** [comment]
Closing this. Please see #573 for latest.

**Comment by kamalsivalingam** [comment]
@anthonychu How do we configure cool down period using Bicep for Azure Function hosted container app

**Comment by kamalsivalingam** [comment]
Is there an example bicep with the cool down period configuration? Not sure about the property name

**Comment by anthonychu** [comment]
Here’s an example for a container app: https://github.com/anthonychu/container-apps-image-classifier/blob/54acab6b426c9a7ae43e78f9636e9e6a7bfc39ca/infra/classifier-app.bicep#L53

I don’t know if it’s supported for Functions, as the scale rules configuration is managed on your behalf. @raorugan

**Comment by FilippTrigub** [comment]
Is there a way to set this property with the az cli? WOuld be very grateful for documentation!

**Comment by j-lebrun** [comment]
> Is there a way to set this property with the az cli? WOuld be very grateful for documentation!

Would be interested as well.
