### ISSUE TITLE
Feature Request: Add Dapr Dashboard

### ISSUE THREAD

**Issue by dale-personal** [microsoft/azure-container-apps#389]
**Is your feature request related to a problem? Please describe**.  
Dapr provides a built in dashboard via the "dapr dashboard" command.
This dashboard is particularly useful for things like actors, seeing # of replicas, # of actors, etc.

**Describe the solution you'd like**.    
provide a similar azure container environment dashboard 

**Describe alternatives you've considered**.   
could  be within the azure portal or via the existing dashboard UI (see attachment)

**Additional context**.  
This was potentially asked here but not fully answered:
https://github.com/microsoft/azure-container-apps/issues/204 :  @kendallroden, is the Dapr dashboard available in the running container app or elsewhere?

![dapr-dashboard](https://user-images.githubusercontent.com/51532677/188170144-8e048124-61bb-4718-ab68-4763681ea96d.png)

**Comment by kendallroden** [comment]
We do not have plans today to run the dapr dashboard. We are considering ways we can improve visibility into your apps running in an environment including replica count etc but will likely not do that via the dapr dashboard UI

**Comment by mcupito** [comment]
It's been a little bit of time since this thread was opened -- is there any more information to share on this topic? Not sure if Diagrid would be an option here as a native integration for Azure Container Apps? Apologies for the bump but also curious and wanting to find the right tool for observability for Dapr.
