### ISSUE TITLE
Support for KeyVault reference syntax like in Web Aps

### ISSUE THREAD

**Issue by SebastianSchuetze** [microsoft/azure-container-apps#39]
I would like the following possible in Container Apps for referencing secrets from a key vault like in Web Apps
https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#reference-syntax

`@Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/)`

![image](https://user-images.githubusercontent.com/7256168/142697849-15657789-f833-4176-8b84-c8fbe54607fb.png)

**Comment by kendallroden** [comment]
duplicate https://github.com/microsoft/azure-container-apps/issues/7
