### ISSUE TITLE
Feature Request: Prerequisites for increasing quotas for Container App Environment with VNet

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#394]
**Is your feature request related to a problem? Please describe**.  
I want to avoid affecting the VNet (Subnet) when raising the quota (CPU core) in an Container Apps Environment with VNet that is scheduled to be deployed in the production environment.

**Describe the solution you'd like**.    
Would you please document the minimum number of CIDR prefixes required for a VNet (subnet) when increasing the quota from the default 20 max CPU cores per Environment.
// Are okay with the minimal prefix of /23 ?

**Describe alternatives you've considered**.   
Set the prefix to /22 or higher in advance in anticipation of future CPU core quota increases.

**Additional context**.  
- Quotas for Azure Container Apps | Microsoft Docs  
https://docs.microsoft.com/azure/container-apps/quotas

- Networking architecture in Azure Container Apps | Microsoft Docs  
https://docs.microsoft.com/azure/container-apps/networking

**Comment by chinadragon0515** [comment]
The IP number depends on the quota and the CPU core set per application.
For your case, you need /22 prefix.
In the meanwhile, we are working to reduce the IP request, the feature is under testing, will open to customer soon. thanks

**Comment by YuKogasaka** [comment]
Thanks.
Are there any prerequisites other than the subnet prefix length?

**Comment by kendallroden** [comment]
I am not 100% clear what the ask is here

**Comment by YuKogasaka** [comment]
I just want to check if there are any prerequisites other than VNet (subnet) required for the Azure Container Apps quota limit (or if it is exceeded).

**Comment by kendallroden** [comment]
Your IP planning is based around how many apps you plan to run. I don't believe there are any other considerations for increasing quota if you are just looking to share more cpu across the same number of services you would be fine without bringing a larger VNet. If you plan to run more container apps in the env based on the quota increase, you would need to have a larger range. We will be switching out networking model to give a bit more flexibility here, but I do not know of any other prereqs at this time that you would need to consider.

**Comment by pilouk** [comment]
> Your IP planning is based around how many apps you plan to run. I don't believe there are any other considerations for increasing quota if you are just looking to share more cpu across the same number of services you would be fine without bringing a larger VNet. If you plan to run more container apps in the env based on the quota increase, you would need to have a larger range. We will be switching out networking model to give a bit more flexibility here, but I do not know of any other prereqs at this time that you would need to consider.

Will the new networking model be compatible with any current production environment? or we will have to create a new env?
