### ISSUE TITLE
REST API /providers/Microsoft.App/containerApps returns no Apps despite exist

### ISSUE THREAD

**Issue by CezaryKlus** [microsoft/azure-container-apps#396]
## This issue is a:
- [x ] bug report

### Issue description
We have Azure Marketplace Managed Application automation performed leveraging Azure REST API to deploy images onto container apps.
Today our automation is failing due to empty result returned from:

https://management.azure.com{{managedResourceGroupId}}/providers/Microsoft.App/containerApps?api-version=2022-03-01

```
{
    "value": []
}

```

Issue is definitely not related to permissions. Also Azure Portal via resource graph API lists container apps as resources in resource group under the same user account.

**Comment by CezaryKlus** [comment]
Today. The same account context, REST API returns app objects properly. However this has has to be investigated for better stability.

**Comment by kendallroden** [comment]
Thank you for letting us know

**Comment by CezaryKlus** [comment]
Today the issue occurs again. West Europe region.

https://learn.microsoft.com/en-us/rest/api/containerapps/container-apps/list-by-resource-group?tabs=HTTP

This api returns empty array despite resources exist.

**Comment by kendallroden** [comment]
@CezaryKlus please consider filing a support ticket so we can properly investigate your issues
