### ISSUE TITLE
Feature Request: Don't require a "container name" via the Portal

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#398]
When creating an app via the CLI I really only need to provide it the app name and image. Via the Portal I'm required to also provide it a "container name" - can we make that optional to align with the CLI?

**Comment by panchagnula** [comment]
@duglin thanks for reaching out - but this forum is for CLI only - I can't comment on portal. @btardif FYI. please send email to portal team on this.

**Comment by simonjj** [comment]
This is a great idea. Closing now.
