### ISSUE TITLE
Revisions Management

### ISSUE THREAD

**Issue by chris-schra** [microsoft/azure-container-apps#4]
Really awesome offering, but I'm wondering how can manage revisions via CLI.

Use Case: PR & Preview Deployments where we want to create (and later delete) a revision with each PR create / delete

**Comment by chris-schra** [comment]
I guess they're all partying :D

**Comment by vturecek** [comment]
[A revision is automatically created](https://docs.microsoft.com/azure/container-apps/revisions) whenever you make a change to certain parts of your application (container settings, scale settings, or dapr settings). Through the CLI you can do things like activate and deactivate existing revisions and control traffic weights between revisions for applications that have HTTP ingress enabled. Here is the full list of operations supported on revisions: https://docs.microsoft.com/azure/container-apps/revisions-manage?tabs=bash

For the rest of this, I'm assuming your application has HTTP ingress enabled..

So your application has a URL that your end users go through. This URL goes through a proxy that allows you to control traffic splitting between revisions. But each revision also has its own unique URL that you can use to test endpoints on just that revision without routing any end-user traffic to it. You can see this URL if you run:

```
az containerapp revision show \
  --name <REVISION_NAME> \
  --app <CONTAINER_APP_NAME> \
  --resource-group <RESOURCE_GROUP_NAME>
```

You can also give revisions well-known suffixes on their names. This can help you identify which revisions are created for previewing, and which are meant for live traffic.

So for your scenario, one approach you could take is to make an application update on PR create and give it a suffix so you know it's for previewing ("-preview" or something, use `az containerapp update --yaml` and pass in an [application definition](https://docs.microsoft.com/azure/container-apps/azure-resource-manager-api-spec)). When a PR is deleted, you can deactivate the revision. No end-user traffic will go to these revisions as long as you don't have `"latestRevision": true` in any of your [traffic splitting rules](https://docs.microsoft.com/en-us/azure/container-apps/revisions-manage?tabs=bash#traffic-splitting), and you'll have a URL that goes directly to that revision for previewing your changes.

Hope that helps!

**Comment by chris-schra** [comment]
@vturecek thanks for the quick reply... related question: can we apply CNAMEs?

**Comment by vturecek** [comment]
You can but that's going to break SSL, because we don't have a certificate for your domain that you CNAME to the auto-generated one.

**Comment by chris-schra** [comment]
I see, thanks.
Just checked and it just returns a blank page - I guess because it can‘t map the CNAME to the actual service. Maybe a user problem, but unfortunately it looks like this service doesn‘t fit our use case. It‘s a pitty because I find it hard to find a service which is able to deploy preview environments in our AKS infrastructure

**Comment by dariagrigoriu** [comment]
@chris-schra, would the custom domains support requested in https://github.com/microsoft/azure-container-apps/issues/8 address your use case?

**Comment by chris-schra** [comment]
@dariagrigoriu Absolutely!
