### ISSUE TITLE
Validation error: "cannot have more than Castle.Proxies.SubscriptionQuotaRuleProxy environments in Canada Central"

### ISSUE THREAD

**Issue by charris-msft** [microsoft/azure-container-apps#401]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When trying to create a Container App with a template or through the Portal I get this error:
![image](https://user-images.githubusercontent.com/74415662/189759745-8f6d591f-e289-482e-bafa-325ea9929566.png)

### Steps to reproduce
1. Open this GitHub page: https://github.com/charris-msft/DeployToAzure/tree/main/Metabase
2. Click the Deploy to Azure button which uses this URI: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fcharris-msft%2FDeployToAzure%2Fmain%2FMetabase%2Fazuredeploy.json
3. Or use this page: https://ms.portal.azure.com/#create/Microsoft.ContainerApp

**Expected behavior** [What you expected to happen.]
Create the environment and ACA, or tell me what the limit is

**Actual behavior** [What actually happened.]
The error looks like we're showing the name of the limit object rather than the value property

**Screenshots**         
![image](https://user-images.githubusercontent.com/74415662/189758915-1c4f4e33-93a6-4676-b048-efb485b88c9b.png)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by onionhammer** [comment]
I'm getting this same error

**Comment by dieterdp** [comment]
i think the problems occurs if you already have a container app environment and/or workspace in the same region on you subscription

**Comment by onionhammer** [comment]
@dieterdp in any region, I think. I can't add an app env to any region now that I have one in central us

**Comment by jasonjohnlee** [comment]
Hi, we got this error and learned that there is actually a soft limit of 5 ACA environments per region.  You can create a ticket with MS support to have this limit increased.
https://learn.microsoft.com/en-ca/azure/container-apps/quotas?WT.mc_id=Portal-Microsoft_Azure_Support

**Comment by onionhammer** [comment]
Apparently the limit is 1 per entire subscription, because that's what I'm seeing.

[{"code":"MaxNumberOfGlobalEnvironmentsInSubExceeded","message":"The subscription '...' cannot have more than 1 environments among all regions."}]}],"message":"The template deployment 'Microsoft.App-ContainerApp-Portal-2a338dce-ae6b' is not valid according to the validation procedure. The tracking id is 'bd7a77c2-12e4-462f-8b63-bd5bc87f2035'. See inner errors for details."}

**Comment by jasonjohnlee** [comment]
@onionhammer What type of subscription do you have?  The docs at the bottom say that Pay-as-you-go and trial subscriptions have a limit of 1.  That might be the reason why you haven't heard from support yet too.  I'm lucky enough that my company has a high tier support agreement so I heard back from MS support within the hour.

**Comment by craigshoemaker** [comment]
The [doc is updated](https://learn.microsoft.com/azure/container-apps/quotas) with the correct quota values.
