### ISSUE TITLE
Feature Request: Availability in UK West?

### ISSUE THREAD

**Issue by kzhen** [microsoft/azure-container-apps#404]
**Is your feature request related to a problem? Please describe**.  
No.

**Describe the solution you'd like**.    
Currently Container Apps is available in UK South (as well as other regions around the world), I would like to know if you have any plans to make it available in UK West?

**Describe alternatives you've considered**.   
N/A

**Additional context**.  
N/A

**Comment by kendallroden** [comment]
UK West support is not planned in the next 6 months

**Comment by kzhen** [comment]
Thanks for the update @kendallroden

**Comment by kzhen** [comment]
Container apps are now available in UK West
