### ISSUE TITLE
Feature Request: Availability in US West 2?

### ISSUE THREAD

**Issue by ldepaiva** [microsoft/azure-container-apps#405]
Is your feature request related to a problem? Please describe.
No.

Describe the solution you'd like.
Currently, it's available for US West and US West 3, how about US West 2? Is it just not available through the UI Portal? Does it work if I set it up using Azure CLI? The Container App sailing page says it's available for US West 2 but I can't get this option when creating through the UI Portal =/

Describe alternatives you've considered.
N/A

Additional context.
N/A

**Comment by praneetloke** [comment]
I was trying to deploy a Container Apps environment in West US 2 and got this error:

>  List of available regions for the resource type is 'northcentralusstage,canadacentral,westeurope,northeurope,eastus,eastus2,eastasia,australiaeast,germanywestcentral,japaneast,uksouth,westus,centralus,northcentralus,southcentralus,koreacentral,brazilsouth,westus3,francecentral,southafricanorth,norwayeast,switzerlandnorth'."

Is there any plan to enable Container Apps in West US 2 anytime soon?

**Comment by MiLtOnXeZaR** [comment]
> Is there any plan to enable Container Apps in West US 2 anytime soon?

I would like to know too!

**Comment by torosent** [comment]
The region is available
