### ISSUE TITLE
Create containerapp hangs when revision-suffix is greater than 40 characters 

### ISSUE THREAD

**Issue by KarsonAlford** [microsoft/azure-container-apps#407]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When creating a container app with a revision-suffix greater than 40 characters the command runs (/ Running .. | Running ..) for 10 minutes before reporting that the container app was created.

### Steps to reproduce
```
az containerapp create `
    --name $(ContainerAppName) `
    --resource-group $(ResourceGroup) `
    --environment $(ContainerAppEnvironment) `
    --image $(ContainerRegistryLoginServer)/$(Repository):$(ImageTag) `
    --target-port 80 `
    --ingress 'external' `
    --query configuration.ingress.fqdn `
    --registry-server $(ContainerRegistryLoginServer) `
    --registry-username $(ContainerRegistryUsername) `
    --registry-password $(ContainerRegistryPassword) `
    --revision-suffix 'a2345678901234567890123456789012345678901' `
    --revisions-mode multiple 
```

**Expected behavior** [What you expected to happen.]
An error stating that the revision-suffix is invalid.

**Actual behavior** [What actually happened.]
The container app is created but the revision cannot be created.  The command reports Running for 10 minutes then cancels and reports that the container app has been created (and in the case above with the --query option the fqdn displays the ingress URL for the container app).

/ Running ..
| Running ..
WARNING: 
Container app created. Access your app at https://<>-237ab5bd.centralus.azurecontainerapps.io/
\ Running ..

**Comment by jscheeres** [comment]
Same issue
https://github.com/Azure/azure-cli/issues/23934
