### ISSUE TITLE
Cannot delete Container Apps environment due to inconsistent resource state

### ISSUE THREAD

**Issue by maskati** [microsoft/azure-container-apps#408]
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have a custom VNet integrated Container Apps environment which cannot be deleted since the resource state seems to be inconsistent or corrupted.
- The environment resource deletion operation succeeds, but the resource is not removed
- The environment resource is shown in the Azure Portal when using the normal resources list, which is implemented using [Azure Resource Graph API](https://learn.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph(2021-03-01)/resources/resources?tabs=HTTP)
- The environment is not shown when using the Azure Portal simplified view, which is implemented using [Azure Resource Manager API](https://learn.microsoft.com/en-us/rest/api/resources/resources/list)
- Clicking the environment open in the portal gives a resource not found response
- The associated managed infrastructure resource group (MC_) containing VNet integration resources also still exists
- The load balancers still show an association to AKS agent pool interfaces (`aks-agentpool-29554799-vmss`)
- The VNet still shows connected scale set instances from the AKS agent pool (`aks-agentpool-29554799-vmss`)

Below are examples showing inconsistent state reported by ARM and the Container App resource provider:

```powershell
# uses GET /subscriptions/{subscriptionId}/providers/Microsoft.App/managedEnvironments?api-version=2022-06-01-preview
az containerapp env list
# same as above
az rest -m get -u '/subscriptions/{subscriptionId}/providers/Microsoft.App/managedEnvironments?api-version=2022-06-01-preview'
# uses GET /subscriptions/{subscriptionId}/resources?$filter=&api-version=2021-04-01
az resource list --query "[?type=='Microsoft.App/managedEnvironments']"
# uses resource graph
az rest -m post -u '/providers/Microsoft.ResourceGraph/resources?api-version=2021-03-01' --headers Content-Type=application/json -b '{\"query\":\"resources|where type==''microsoft.app/managedenvironments''|project id\"}'
```
![image](https://user-images.githubusercontent.com/21118898/191440858-89feb0aa-c94c-4789-8c38-5753f731fb2c.png)

**Comment by maskati** [comment]
The environment resource has now disappeared from the resource graph API, but ACA backend AKS resources are still associated with my custom VNet, preventing removal of such resources. It seems like the ACA environment removal process has partially failed, leaving an orphan managed infrastructure resource group and backend AKS node pool. Association is to the following VMSS in a Microsoft managed subscription: `/subscriptions/efb26ea2-ef9f-43ee-864c-3f653a36c95e/resourceGroups/MC_jollysmoke-a665c896-rg_jollysmoke-a665c896_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-29554799-vmss`

**Comment by maskati** [comment]
It took a week for the process to start, but ACA finally deleted the managed infrastructure group. Eventually consistent :smile:

**Comment by kendallroden** [comment]
Glad it was removed. Sorry for the inconvenience
