### ISSUE TITLE
Container App Environment fails when using custom VNet

### ISSUE THREAD

**Issue by grott0** [microsoft/azure-container-apps#416]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm trying to create a container application environment with a custom virtual network.

### Steps to reproduce
1. Follow the tutorial: https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-cli
2. Make sure you use an existing resource group.
2. Make sure you have resource group creation policies (mandatory tags for instance) in the chosen subscription.

**Expected behavior** Deployment success.

**Actual behavior** Deployment failed. 
"ErrorCode: ManagedEnvironmentResourceGroupDisallowedByPolicy, Message: Fail to create managed environment because resource group creation is disallowed by policy, refer to https://go.microsoft.com/fwlink/?linkid=2198255 for more detail."

### Additional context
Issue appears both in the Azure Portal and in the CLI. From what I can see the deployment is failing due to a group creation policy, but what does that have to do with creating a container app + environment? There's no resource group creation involved in the process (unless Azure isn't doing something under the hood). Also, there's absolutely no information which policy was violated during the deployment process. I'm attaching a log file from Azure CLI. [container-app-fail.txt](https://github.com/microsoft/azure-container-apps/files/9646500/container-app-fail.txt)

**Comment by kendallroden** [comment]
closing based on duplicate - I believe we are working on the above
