### ISSUE TITLE
Feature Request: Enable applications to authenticate requests arriving from the Dapr sidecar

### ISSUE THREAD

**Issue by alhardy** [microsoft/azure-container-apps#417]
**Is your feature request related to a problem? Please describe**.  
I need to enable applications to authenticate requests that are arriving from the Dapr sidecar.

**Describe the solution you'd like**.    
The ability to set the APP_API_TOKEN env var so that my applications can authenticate requests. As described [here](https://docs.dapr.io/operations/security/app-api-token/)

**Describe alternatives you've considered**.   
I have not considered alternatives

**Additional context**.  
- https://docs.dapr.io/operations/security/app-api-token/

**Comment by onionhammer** [comment]
What is the recommendation here? It seems like a potentially big gap if the documented ACA samples leave an app's dapr endpoints open to public IPs by default

**Comment by alhardy** [comment]
Would have to ensure apis hosting cron and topic endpoints for example are private services. Still it'd typically be recommended from a security perspective to have a second layer of protection.

**Comment by alhardy** [comment]
Any update on this?

**Comment by onionhammer** [comment]
Our team would also love to know..

**Comment by rvanmaanen** [comment]
Same question here.

Thought I'd try to create a secret with the name 'APP_API_TOKEN' as I read that the secrets are exposed through environment variables, but that's not possible because of naming restrictions (only lowercase and no underscores allowed).

**Comment by jamie-magenta** [comment]
> Thought I'd try to create a secret with the name 'APP_API_TOKEN' as I read that the secrets are exposed through environment variables, but that's not possible because of naming restrictions (only lowercase and no underscores allowed).

Actually, you can name them like you wish,  at least in an ARM template:

```json
{
    "type":"Microsoft.App/containerApps",
    "properties":{
        "configuration":{
            "secrets":[
                {
                    "name":"app-api-token",
                    "value":"your-value"
                }
            ]
        },
        "template":{
            "containers":[
                {
                    "env":[
                        {
                            "name":"APP_API_TOKEN",
                            "secretRef":"app-api-token"
                        }
                    ]
                }
            ]
        }
    }
}
```

**Comment by kendallroden** [comment]
We will triage this enhancement request. This would require us to do testing with our implementation of envoy and we would need to expose the annotation in the dapr section. It is a valid request! Will create a backlog item and let you know where we land

**Comment by onionhammer** [comment]
Seems like ACA could, minimally, generate & automatically rotate a `APP_API_TOKEN` variable

**Comment by anweihe** [comment]
@kendallroden And where did it land? And is there a workaround?

**Comment by SophCarp** [comment]
Hi @onionhammer and @anweihe! @kendallroden has moved on from the ACA team. I'm not sure where we are on this project but will look into it. @greenie-msft do you know?

**Comment by alhardy** [comment]
Any update on this?

**Comment by WolfspiritM** [comment]
We need this, too. I wonder if, as a first step, we can create a middleware that blocks access to dapr specific endpoints if the source IP is not 127.0.0.1 (assuming that requests inside ACA are not coming from another sidecar in the same Pod). I will do some testing...

**Comment by alhardy** [comment]
> We need this, too. I wonder if, as a first step, we can create a middleware that blocks access to dapr specific endpoints if the source IP is not 127.0.0.1 (assuming that requests inside ACA are not coming from another sidecar in the same Pod). I will do some testing...

Didn't think of that as an approach for now. Let me know how you go @WolfspiritM

**Comment by ztepsic** [comment]
@SophCarp any update on this?

**Comment by greenie-msft** [comment]
Hi everyone,

We've raised the priority of this feature request and are looking into how we can best support this scenario. I will provide an update once I have additional details to share. 

Thanks for your patience.

**Comment by greenie-msft** [comment]
Providing an update - this feature request is being targeted for the next sprint. Will have more details to share in the coming days/week.

**Comment by onionhammer** [comment]
@ahmelsayed this is done now? How does it work?

**Comment by ahmelsayed** [comment]
oops, sorry about that. It's not deployed yet.

**Comment by greenie-msft** [comment]
@onionhammer, the work for this capability is done and it will start rolling out in the next week or two.

Regarding how it will work - when Dapr is enabled on a container app,  the  "APP_API_TOKEN" env var will be automatically set and available to your container app. The token is randomly generated and uniquer per each app and app revision.
 
You can use this token to authenticate that calls coming into your application are actually coming from the Dapr sidecar - the Dapr SDKs do this automatically.

**Comment by iamdrewhayes** [comment]
@ahmelsayed @greenie-msft Could you follow up with a link to the documentation once this has been deployed?

When you say that the Dapr SDKs authenticate using the APP_API_TOKEN automatically, does this include controller actions decorated with the "Topic" attribute?

Thanks everyone, I'm looking forward to this!

**Comment by Brianovitch** [comment]
When can we expect this feature to be deployed?

**Comment by greenie-msft** [comment]
Thanks for your patience with this.

This feature is now available and the documentation for how to use it can be found [here](https://learn.microsoft.com/en-us/azure/container-apps/dapr-authentication-token?branch=pr-en-us-234558&tabs=sdk).

Please let me know if you have any questions.

**Comment by onionhammer** [comment]
I'm still not seeing this rolled out

**Comment by onionhammer** [comment]
Interestingly, none of the samples for .NET seem to utilize the APP_API_TOKEN

**Comment by WolfspiritM** [comment]
> Interestingly, none of the samples for .NET seem to utilize the APP_API_TOKEN authentication

I found a "sample" in the integrationtests here:
https://github.com/dapr/dotnet-sdk/blob/8e9db70c0f58050f44970cda003297f561ab570a/test/Dapr.AspNetCore.IntegrationTest.App/DaprController.cs#L167

https://github.com/dapr/dotnet-sdk/blob/8e9db70c0f58050f44970cda003297f561ab570a/test/Dapr.AspNetCore.IntegrationTest.App/Startup.cs#L38

So as far as I can see it requires this additional configuration:
Program.cs (Startup.cs):
```cs
            services.AddAuthentication().AddDapr(); // options will read APP_API_TOKEN per default so no need to specify token here
            services.AddAuthorization(o => o.AddDapr()); // this adds the policy that can be used in the "Authorize" attribute on a controller or via minimal api
```

Annoyingly "DaprAuthenticationOptions.DefaultScheme" is internal (this should probably be changed) so it needs to be referenced by string in the Controller:
```cs
        [Authorize("Dapr")]
        [HttpPost("/requires-api-token")]
        public ActionResult<UserInfo> RequiresApiToken(UserInfo user)
        {
            return user;
        }
```

**Comment by onionhammer** [comment]
@WolfspiritM Bear in mind that the .NET dapr actor SDK does not take advantage of the authorization by default, if you're using it.
