### ISSUE TITLE
Feature Request: Provide the ability to configure dapr access policies

### ISSUE THREAD

**Issue by alhardy** [microsoft/azure-container-apps#420]
**Is your feature request related to a problem? Please describe**.  
I would like to be able to secure communication with service invocation by configuring dapr [access policies](https://docs.dapr.io/concepts/security-concept/)

**Describe the solution you'd like**.    
The ability to edit the dapr `appconfig` spec so that I can set policies on service invocations.

**Describe alternatives you've considered**.   
- Use a Service Mesh
- Use OAuth2 to provide scope authorization on endpoints

**Additional context**.  
- https://docs.dapr.io/operations/configuration/invoke-allowlist/

**Comment by kendallroden** [comment]
closing this because its a duplicate! Please track https://github.com/microsoft/azure-container-apps/issues/303
