### ISSUE TITLE
Azure Portal displays Dapr component even though it isn't scoped to the app

### ISSUE THREAD

**Issue by cwe1ss** [microsoft/azure-container-apps#422]
### This issue is a:
- [x] bug report

### Issue description
The App's "Dapr" screen in the portal shows Dapr components that aren't scoped to it. 

I have a pubsub component that is scoped to two apps:
* internal-http-bus
* internal-grpc-sql-bus

I have another app called "public-razor" which does show this component in the UI.

### Steps to reproduce
1. Deploy a Dapr component with scopes
2. Deploy an app that isn't included in these scopes
3. Look at the "Dapr" screen of that app

**Expected behavior**
I expected the page to only display components that are valid for the current app.

**Actual behavior**
A component is displayed, that isn't scoped for the app.

**Screenshots**         
The pubsub component (note that I have currently only deployed my "public-razor" app, hence the "App not found" messages.
![image](https://user-images.githubusercontent.com/4581460/192741800-71857434-1cd0-4c0b-9425-8482f57ed961.png)

My "public-razor" app:
![image](https://user-images.githubusercontent.com/4581460/192741982-d547be03-5d6a-49aa-b158-3acfd66bb0d6.png)

### Additional context
I deployed from my public template: https://github.com/cwe1ss/msa-template

**Comment by kendallroden** [comment]
Thanks for reporting this. looks like a bug. Will report to portal team

**Comment by kendallroden** [comment]
This change is completed on our side and rolling out
