### ISSUE TITLE
Sending StreamContent greater than 10mb from Container App to Container App Fails

### ISSUE THREAD

**Issue by alexbot89** [microsoft/azure-container-apps#424]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have two dotnet 6 container apps deployed in 1 environment.
When trying to send a file greater than 10mb via `StreamContent`, http client fails with exception.
Any stream under 10mb succeeds to be retrieved on the 2nd container app.

### Steps to reproduce
1. Deploy 2 dotnet 6 container apps
2. Have a the first container app send an http request to the 2nd container app, with stream content greater than 10mb
3. Alternatively you can send it via postman to the first, then have the first send the stream to the second

**Expected behavior** [What you expected to happen.]
I expected that the 2nd container app would receive the request successfully.

**Actual behavior** [What actually happened.]
An error ocurred, the exception is as follows:

Message:
`"Error while copying content to a stream."`

Exception:
`{"Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.."}`

CallStack:
> "   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\r\n   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()\r\n   at System.Net.Security.SslStream.<<WriteSingleChunk>g__CompleteWriteAsync|182_1>d`1.MoveNext()\r\n   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()\r\n   at System.Net.Security.SslStream.<WriteAsyncChunked>d__181`1.MoveNext()\r\n   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()\r\n   at System.Net.Security.SslStream.<WriteAsyncInternal>d__191`1.MoveNext()\r\n   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()\r\n   at System.Net.Http.HttpConnection.<WriteAsync>d__78.MoveNext()\r\n   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()\r\n   at System.Net.Http.HttpContent.<<CopyToAsync>g__WaitAsync|56_0>d.MoveNext()"

**Screenshots**         

### Additional context
What I tried:
1. Deployed the 2nd container app to Azure App Services and sent the same payload to it, no error occurred.
2. Turned the ingress to public on the 2nd container app, send the payload directly via Postman, no error occurred.
3. I am wondering if there is some hidden configuration on ACA where it limits how much data we can send to the service, because anything under 10mb is successful.

Sample Code:
```cs
    internal static async Task<IResult> Upload(HttpRequest request,IHttpClientFactory factory)
    {
        var myclient = factory.CreateClient("myclient");

        myclient.BaseAddress = new Uri("https://{{host}}.westus.azurecontainerapps.io");

        using var streamCopy = new MemoryStream();
        await request.Body.CopyToAsync(streamCopy);
        streamCopy.Position = 0;
        var uploadContent = new StreamContent(streamCopy);

        uploadContent.Headers.ContentType = new MediaTypeHeaderValue(request.ContentType);
        uploadContent.Headers.ContentLength = request.ContentLength;

        var result = await myclient.PostAsync("/upload", uploadContent);
        var message = await result.Content.ReadAsStringAsync();

        return Results.Ok(message);
    }
```

**Comment by ahmelsayed** [comment]
I'm unable to repro this. This is what I used 

`Program.cs`

<details>

```csharp
using System.Net.Http.Headers;

var builder = WebApplication.CreateBuilder(args);
// default is 30MB?
builder.WebHost.UseKestrel(o => o.Limits.MaxRequestBodySize = long.MaxValue);
var app = builder.Build();

var client = new HttpClient()
{
    Timeout = TimeSpan.FromMinutes(4)
};

app.MapPost("/upload", async ctx =>
{
    var targetApp = Environment.GetEnvironmentVariable("TARGET_APP") ?? "target-app";

    using var streamCopy = new MemoryStream();
    await ctx.Request.Body.CopyToAsync(streamCopy);
    streamCopy.Position = 0;
    var uploadContent = new StreamContent(streamCopy);
    // or just pass the stream directly to avoid buffering it in memory unless needed
    // var uploadContent = new StreamContent(ctx.Request.Body);

    uploadContent.Headers.ContentType = new MediaTypeHeaderValue(ctx.Request.ContentType);
    uploadContent.Headers.ContentLength = ctx.Request.ContentLength;

    var result = await client.PostAsync(new Uri($"https://{GetInternalFqdn(targetApp)}/upload-internal"), uploadContent);
    var message = await result.Content.ReadAsStringAsync();

    await ctx.Response.WriteAsync(message);
});

app.MapPost("/upload-internal", async ctx =>
{
    await using var file = new FileStream("/tmp/test", FileMode.OpenOrCreate, FileAccess.Write);
    await ctx.Request.Body.CopyToAsync(file);
    await ctx.Response.WriteAsync("success");
});

string GetInternalFqdn(string appName)
{
    var fqdn = Environment.GetEnvironmentVariable("CONTAINER_APP_ENV_DNS_SUFFIX");
    return string.IsNullOrEmpty(fqdn) ? appName : $"{appName}.internal.{fqdn}";
}

app.Run();
```

</details>

created 2 apps with the same image, `public-app`, `internal-app`, and a 100MB file


```console
$ az containerapp create --name public-app --image ahmelsayed/upload-app --ingress external ...
$ az containerapp create --name target-app --image ahmelsayed/upload-app --ingress internal ...

$ head -c 104857600 </dev/urandom > 100mb.file 
$ curl https://public-app.env.westus.azurecontainerapps.io --data-binary @100mb.file -v

> POST /upload HTTP/2
> Host: public-app.env.westus.azurecontainerapps.io 
> user-agent: curl/7.79.1
> accept: */*
> content-length: 104857600
> content-type: application/x-www-form-urlencoded
> 
* We are completely uploaded and fine
< HTTP/2 200 
< date: Thu, 29 Sep 2022 04:49:59 GMT
< server: Kestrel
< content-type: text/plain; charset=utf-8
< 
* Connection #0 to host public-app.env.westus.azurecontainerapps.io left intact

success%
```

Do you see any particular error on the target app?

**Comment by ahmelsayed** [comment]
If you can share your app url and a rough time frame with me I can check what error our proxy saw between the 2 apps. you can use ahmels at microsoft.com if you don't want to share the details publicly.
