### ISSUE TITLE
The environment network configuration is invalid: Provided subnet must have a size of at least /23

### ISSUE THREAD

**Issue by jedi0606** [microsoft/azure-container-apps#425]
### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I cannot deploy Container Apps Env due to issues with subnet IPs
Error message is 
`RESPONSE 400: 400 Bad Request
"message": "The environment network configuration is invalid: Provided subnet must have a size of at least /23"

### Steps to reproduce
1. Apply Container app via Terraform
2. Receive errors. 

My code is
`resource "azapi_resource" "aca-test-environment" {
  name      = "ca-test-environment"
  type      = "Microsoft.App/managedEnvironments@2022-03-01"
  location = var.location
  parent_id = module.resource_groups.rg-test-id
  depends_on   = [module.resource_groups, module.virtual_networks]
   lifecycle {
        prevent_destroy = true
        ignore_changes = ["body" ]
    }
  body = jsonencode({
    properties = {
      appLogsConfiguration = {
        destination = "log-analytics"
        logAnalyticsConfiguration = {
          customerId = azurerm_log_analytics_workspace.loganalytics.workspace_id
          sharedKey  = azurerm_log_analytics_workspace.loganalytics.primary_shared_key
        }
      }
      vnetConfiguration = {
        internal               = true
        infrastructureSubnetId = module.virtual_networks.subnet_with_LinuxVM_id
        dockerBridgeCidr       = "10.2.0.1/16"
        platformReservedCidr   = "10.0.0.0/16"
        platformReservedDnsIP  = "10.0.0.2"
      }

    }
  })
}`

IPs of my subnet is : 10.1.0.0/24
**Expected behavior** [What you expected to happen.]
Be able to deploy Container Environment App and Container App via Terraform without errors

**Comment by cwe1ss** [comment]
The subnet in your example uses `/24` (256 IPs) which is smaller than the required `/23` (512 IPs). 

You could vote on the following issue if you need this to work in smaller subnets:
* https://github.com/microsoft/azure-container-apps/issues/247

docs: https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-portal#create-an-environment
