### ISSUE TITLE
Microsoft.App managedEnvironments cannot be deployed

### ISSUE THREAD

**Issue by jedi0606** [microsoft/azure-container-apps#426]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm trying to add storage to container environment via Terraform using this guide:
https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-03-01/managedenvironments/storages?pivots=deployment-language-terraform

### Steps to reproduct
1. Apply Terraform and receive error

My code is 
`resource "azapi_resource" "containerapp_environment" {
  type      = "Microsoft.App/managedEnvironments@2022-03-01"
  name      = "${var.aca_name}acae"
  parent_id = azurerm_resource_group.rg.id
  location  = azurerm_resource_group.rg.location

  body = jsonencode({
    properties = {
      appLogsConfiguration = {
        destination = "log-analytics"
        logAnalyticsConfiguration = {
          customerId = azurerm_log_analytics_workspace.loganalytics.workspace_id
          sharedKey  = azurerm_log_analytics_workspace.loganalytics.primary_shared_key
        }
      }
      vnetConfiguration = {
        internal               = true
        infrastructureSubnetId = azurerm_subnet.aca_subnet.id
        dockerBridgeCidr       = "10.2.0.1/16"
        platformReservedCidr   = "10.1.0.0/16"
        platformReservedDnsIP  = "10.1.0.2"
      }
    }
  })
  depends_on = [
    azurerm_virtual_network.virtual_network, azurerm_storage_account.aci_storage
  ]
  ignore_missing_property = true
  ignore_casing = true
  schema_validation_enabled = false
}

resource "azapi_resource" "symbolicname" {
  type = "Microsoft.App/managedEnvironments/storages@2022-03-01"
  name = "string"
  parent_id = azapi_resource.containerapp_environment.id
  body = jsonencode({
    properties = {
      azureFile = {
        accountKey = data.azurerm_storage_account.aci_storage.primary_access_key
        accountName = azurerm_storage_account.aci_storage.name
        shareName = azurerm_storage_share.container_share.name
      }
    }
  })
}`

**Expected behavior** [What you expected to happen.]
Container environment along wit storage can be deployed using Terraform

**Actual behavior** [What actually happened.]
Error message is :
`Error: creating/updating "Resource: (ResourceId \"/subscriptions/10071b3d-8531-45e2-bc9c-699f6331a09b/resourceGroups/testneww-rg/providers/Microsoft.App/managedEnvironments/testnewwacae\" / Api Version \"2022-03-01\")": GET https://management.azure.com/subscriptions/10071b3d-8531-45e2-bc9c-699f6331a09b/providers/Microsoft.App/locations/uksouth/managedEnvironmentOperationStatuses/46749e98-0fcb-4cc2-b599-0e5e1db7518d
│ --------------------------------------------------------------------------------
│ RESPONSE 200: 200 OK
│ ERROR CODE: OperationFailed
│ --------------------------------------------------------------------------------
│ {
│   "id": "/subscriptions/10071b3d-8531-45e2-bc9c-699f6331a09b/providers/Microsoft.App/locations/uksouth/managedEnvironmentOperationStatuses/46749e98-0fcb-4cc2-b599-0e5e1db7518d",
│   "name": "46749e98-0fcb-4cc2-b599-0e5e1db7518d",
│   "status": "Failed",
│   "error": {
│     "code": "OperationFailed",
│     "message": "ErrorCode: ManagedEnvironmentResourceDisallowedByPolicy, Message: Fail to create managed environment because creation of required resources was disallowed by policy, refer to https://go.microsoft.com/fwlink/?linkid=2198255 for more detail."
│   },
│   "startTime": "2022-09-29T13:41:56.8910411"
│ }
│ --------------------------------------------------------------------------------
│ 
│

**Comment by torosent** [comment]
Hi, Do you have a policy in your subscription that prevents creation of resource groups? Since you are using your own VNET, we will try to create a MC_ resource group in your sub and that seems to be blocked.
https://learn.microsoft.com/en-us/azure/container-apps/networking#managed-resources
