### ISSUE TITLE
Feature Request: Allow for container apps to be a resource target for Azure DevOps environments 

### ISSUE THREAD

**Issue by kevball2** [microsoft/azure-container-apps#428]
**Is your feature request related to a problem? Please describe**.  
A clear and concise description of what the problem is

**Describe the solution you'd like**.    
Adding Azure container apps as a supported environment resource in Azure DevOps would allow us to take advantage of the various option in the [Deployment Job](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops) for YAML pipelines. Being able to tie into features such preDeploy, traffic routing, and rollback would would be very beneficial. Additionally taking advantage of [Environments](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops) to allow for better diagnostics and traceability of deployed container apps would also greatly benefit developers.  

**Describe alternatives you've considered**.   

**Additional context**.

**Comment by simonjj** [comment]
We have a DevOps task now. https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-container-apps-v1?view=azure-pipelines
