### ISSUE TITLE
Chain of issues with Container Apps - Locked and can't use the service

### ISSUE THREAD

**Issue by epomatti** [microsoft/azure-container-apps#429]
Here are all the issues that occurred to me in a sequence of events. Perhaps the team can look at it to avoid these kinds of deadlocks.

1. Managed Environment deletion is not going through, event after hours trying. I don't have paid support plan on my personal account, so I'm stuck.
    <img src="https://user-images.githubusercontent.com/6530769/193680103-b4765512-7a47-4196-89f5-f54f0d009cd9.png" width=500 />

2. When trying to create a new resource, Terraform AzApi for Container Apps is throwing me some random error that I can't work with:
    ![image](https://user-images.githubusercontent.com/6530769/193680499-84edfe6e-05f1-4c1f-a4f1-c304ecd8ec21.png)

3. Using the [REST API](https://learn.microsoft.com/en-us/rest/api/containerapps/managed-environments/create-or-update?tabs=HTTP) to create the Managed Service gives me this error:
    ```json
    {
      "code": "MaxNumberOfRegionalEnvironmentsInSubExceeded",
      "message": "The subscription '00000000-0000-0000-0000-000000000000' cannot have more than 1 environments in East US."
    }
    ```
    According to the [limits](https://learn.microsoft.com/en-us/azure/container-apps/quotas) documentation my Pay-as-you-go limit is this:
    
    > Pay-as-you-go and trial subscriptions are limited to 1 environment per region per subscription.
    
    Anyways, so creating in another region should solve it right? No...

4. Now when creating on East US 2 I get another error, saying the limit is **1 for all regions**:
    ```json
    {
      "code": "MaxNumberOfGlobalEnvironmentsInSubExceeded",
      "message": "The subscription '00000000-0000-0000-0000-000000000000' cannot have more than 1 environments among all regions."
    }
    ```

Lastly, I finally decided to create a new subscription to work around the issues above, and of course I ran into another problem.  The new subscription is not showing up anywhere in the Portal. At this moment I have 2 support tickets opened and this issues to register it all.

**Comment by torosent** [comment]
We identified the issue and resolved it. Can you confirm it is resolved for you?

**Comment by epomatti** [comment]
@torosent tests ok here.
