### ISSUE TITLE
Managed Environment stuck on delete process

### ISSUE THREAD

**Issue by epomatti** [microsoft/azure-container-apps#430]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Unable to delete Managed Environment after trying for hours.

![image](https://user-images.githubusercontent.com/6530769/193703179-72a63595-8a88-4d3a-96ca-0e9f07528ef8.png)

### Steps to reproduce
I can't, it happens randomly.

**Expected behavior**

Delete and it should work.

**Actual behavior**

Managed environment is not being deleted.

**Comment by epomatti** [comment]
Closing as it is reported that this has been fixed and in my tests it seems ok too.

**Comment by FarzamMohammadi** [comment]
The UI isn't functioning as anticipated, especially when compared to other resources. It moves the resources to a "ScheduledForDelete" state, but then the delete bar vanishes and nothing progresses. The CLI does work, but it operates at a significantly reduced speed, taking an unusually long time to complete—somewhere between 5 to 10 minutes.

**Comment by KuSh** [comment]
Seems to happen again
![image](https://github.com/microsoft/azure-container-apps/assets/60970/b2d60eaa-5c0f-4682-befc-c3de3a8f4dd2)

Using cli seems to work alas its really slow

**Comment by KrisSimon** [comment]
cli sys: "Containerapp environment successfully deleted" put it is still there in portal. Even after 3h. 
Is there any trick you know how to `--force` delete it?
