### ISSUE TITLE
Limit quotas not compatible with documentation - please fix it

### ISSUE THREAD

**Issue by epomatti** [microsoft/azure-container-apps#431]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The [documentation](https://learn.microsoft.com/en-us/azure/container-apps/quotas) is clear on which there should be a limit of 1 environment per region per subscription in a Pay-as-you-go account.

> Pay-as-you-go and trial subscriptions are limited to 1 environment per region per subscription.

However, it is imposing a limit of 1 globally. This is not the actual documented behavior, please fix one or the other.

Response I'm getting from the REST API:

```json
{
  "code": "MaxNumberOfGlobalEnvironmentsInSubExceeded",
  "message": "The subscription '00000000-0000-0000-0000-000000000000' cannot have more than 1 environments among all regions."
}
```

Either the documentation or the API is wrong.

### Steps to reproduce
1. Create an environment
2. Try creating another in a secondary location and it won't allow it.

**Comment by kendallroden** [comment]
issue appears to have been resolved
