### ISSUE TITLE
Feature Request: Deploy multiple containers in one ContainerApp

### ISSUE THREAD

**Issue by jedi0606** [microsoft/azure-container-apps#432]
**Is your feature request related to a problem? Please describe**.  
It would be good to be able to have 2 containers with different images like we have in K8s Pods

**Describe the solution you'd like**.    
To have something like this:
`` template = {
          containers = [
          container = 
          {
            image = "image1"
            name  = "container1"
          },
         container = 
             {                 
            image = "image2"
            name  = "container2"
            }]`
**Additional context**.  
The documentation says that it is possible
"You can define multiple containers in a single container app to implement the [sidecar pattern](https://learn.microsoft.com/en-us/azure/architecture/patterns/sidecar).". If so, how exactly?
https://learn.microsoft.com/en-us/azure/container-apps/containers

**Comment by cwe1ss** [comment]
Haven't tried it myself yet, but you should be able to deploy multiple containers with ARM/Bicep templates by providing multiple container-objects to the `properties.template.containers`-field: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps

Here's an example of a Bicep template for Azure Container Apps in case that's new for you: https://github.com/Azure/reddog-containerapps/blob/3a4164a893369f01c29b4704edf0cac02bf855a7/deploy/bicep/modules/container-apps/accounting-service.bicep#L17

Be sure to follow the docs you've linked though - the total CPU & RAM of all containers must match a fixed set of combinations that's listed on that page.
