### ISSUE TITLE
Container App environment not provisioned successfully

### ISSUE THREAD

**Issue by pamelafox** [microsoft/azure-container-apps#433]
### This issue is a: (mark with an x)
- [X] bug report
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I am following my own [guide to deploying a containerized Flask app](http://blog.pamelafox.org/2022/09/deploying-containerized-flask-app-to.html), which worked a few days ago. This time, my request to create a new container app environment is taking either a very long time or forever. So far, it has taken an hour.

When I query the status via `az containerapp env show -n pamelafox-site-container-environment -g pamelafox-site-group`,
it says "provisioningState": "Waiting".

I'm not sure if I should actually keep waiting, or if I should give up and create a new environment.

### Steps to reproduce
This is the command I ran to create the environment:

```
az containerapp env create --name pamelafox-site-container-environment --resource-group pamelafox-site-group --location eastus
```

**Expected behavior** [What you expected to happen.]

I expected it to provision it within a few minutes, as it did previously.

**Actual behavior** [What actually happened.]

It has still failed to provision it, still says Waiting.

**Screenshots**         

<img width="901" alt="Screen Shot 2022-10-04 at 10 17 17 AM" src="https://user-images.githubusercontent.com/297042/193886370-ef1da452-743d-4750-b0ad-295fa4f0036f.png">

### Additional context

Happened in CLI, verified in Portal.

**Comment by pamelafox** [comment]
Update: I attempted to create a new environment group, but was told the subscription couldn't have more than one environment in that region, so I'm now attempting to delete the un-provisioned environment group to make space for another one. The delete operation is still pending.

**Comment by epomatti** [comment]
@pamelafox same here:
- https://github.com/microsoft/azure-container-apps/issues/429
- https://github.com/microsoft/azure-container-apps/issues/430
- https://github.com/microsoft/azure-container-apps/issues/431

**Comment by torosent** [comment]
Hi all. We identified the issue and resolved it. Can you check again?

**Comment by dhilgarth** [comment]
@torosent
I'm having this issue today as well:

![image](https://github.com/microsoft/azure-container-apps/assets/1180105/44c9ef13-d619-4f67-8610-e1654938bb98)

The environment has been created via Terraform. This used to work properly the past days. Is there any possibility for me to troubleshoot this further?

**Comment by praneetloke** [comment]
I am now encountering this issue when I am trying to update the container image for an existing container in my container apps environment, plus I see this (screenshot) in the portal when I open my already existing environment. I have no idea what is wrong here because there is no additional information on what failed to provision.

![image](https://github.com/microsoft/azure-container-apps/assets/1466314/e013aaef-e48c-4d96-ab4e-1b109aba90db)
