### ISSUE TITLE
Feature Request: Refresh button on the environment.Apps page

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#439]
When I look at the list of apps in my environment via the portal there's no "Refresh" button like there is on most other pages. It would be nice if one was there so I didn't have to hit the browser's reload button - for consistency.

**Comment by btardif** [comment]
@duglin can you confirm this is the right view where the button should be added?

![image](https://user-images.githubusercontent.com/4119816/195140117-1e76f848-6223-47db-a0ad-7ee35f4bb6db.png)

cc: @kendallroden

**Comment by duglin** [comment]
@btardif yup - that's the view I was thinking of. Thanks
