### ISSUE TITLE
app delete needs a way to wait until it's really gone

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#440]
Right now, by default, `az containerapp delete` will wait a while before it returns to the user. And there's a `--no-wait` flag you can specify to return right away w/o waiting at all. However, in the mode where it waits it's not waiting long enough. Right now if I do a "delete" and then immediately do a "create" using the same app name I'll get an error due to a conflict. Either the default should wait until the app is fully gone so a create using the same name works, or we should add another flag to ask for that behavior. W/o this the user is forced to do their own polling mechanism to know when it's safe to reuse the name.

I'd prefer to have the default just wait until the name is safe to reuse since --no-wait should be sufficient for all other cases. Today's behavior is a bit undefined and I'm not sure who would want to have the command return to them in this unknown half-there state (it seems like it should be either "return immediately" or "return when really gone").

**Comment by simonjj** [comment]
Closing this, please reopen if you feel strongly.
