### ISSUE TITLE
Feature Request: tell me which flags are being ignored

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#443]
When I tried to create an app by specifying it's yaml:
```
az containerapp create -n redis --yaml redis.yaml
```
I see this:
```
WARNING: Additional flags were passed along with --yaml. These flags will be ignored, and the configuration defined in the yaml will be used instead
```
However, I'm not sure which flags it's referring to since the only other flag was `-n` and I get this error when I leave that off:
```
ERROR: the following arguments are required: --name/-n
```

So there are two issues:
1 - I think the WARNING is incorrect and should not be shown
2 - When it is correct it should tell me which flags are being ignored so the user can know exactly which ones to remove w/o having to do a diff against the docs to see which might be redundant.

**Comment by simonjj** [comment]
Closing this, please reopen if you feel strongly.
