### ISSUE TITLE
Create App from the Portal

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure-container-apps#448]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduce
1. Use this [App](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv) with its [Dockerfile](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/7b91324eba775673da3a17c76fc2375078419500/docker/petclinic-admin-server/Dockerfile)
2. Follow the [doc](https://learn.microsoft.com/en-us/azure/container-apps/managed-identity-image-pull?tabs=azure-cli&pivots=azure-portal) to create an App using a User Assigned MI
3. Create a new revision
4. set scale min to 1
5. The Probe are declared in the Java code at [https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/7b91324eba775673da3a17c76fc2375078419500/spring-petclinic-admin-server/src/main/resources/application.yml](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/7b91324eba775673da3a17c76fc2375078419500/spring-petclinic-admin-server/src/main/resources/application.yml) , port used is 8081 whereas the App port is 9090

```bash
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/manage"
      exposure: # https://docs.spring.io/spring-boot/docs/2.6.3/reference/html/actuator.html#actuator.endpoints.exposing
        include: "health,info,env,mappings" # "*"
        exclude: "beans"    
  endpoint:
    health:
      enabled: true
      status:
        http-mapping:
          down: 503
          fatal: 503
          out-of-service: 503
      group:
        readiness:
          include: "readinessState"
        liveness:
          include: "livenessState"                      
    probes:
        enabled: true      
    info:
      enabled: true
    env:
      enabled: true
    mappings:
      enabled: true            
  server:
    port: 8081
```

system logs show:
```console
Readiness probe failed: dial tcp 10.240.0.38:**9090**: connect: connection refused
```

Whereas all Probe are displayed as 'probes disabled' in the Portal / containers panel

**Expected behavior** [What you expected to happen.]
The App should successfully deployed as probe have not been enabled from the Portal.

**Actual behavior** [What actually happened.]
Revision failed to start

**Screenshots**         
N/A

### Additional context
This issue occur in the Portal

**Comment by kendallroden** [comment]
Hi there- we set default probes in ACA as you'll find here: https://learn.microsoft.com/en-us/azure/container-apps/health-probes?tabs=arm-template#default-configuration

This could be causing your issue. I will pass this along to have another set of eyes

**Comment by ezYakaEagle442** [comment]
@kendallroden  this doc does not help, I did already set the Probe tha tshould override the default ones set in ACA:

```sh
          probes: [
            {
              failureThreshold: 5
              httpGet: {
                path: '/manage/health/liveness' /* /actuator */
                port: 8081
                scheme: 'HTTP'
              }
              initialDelaySeconds: 30
              periodSeconds: 60
              successThreshold: 1              
              timeoutSeconds: 3
              type: 'Liveness'
            }
            {
              failureThreshold: 5
              httpGet: {
                path: '/manage/health/readiness' /* /actuator */
                port: 8081
                scheme: 'HTTP'
              }
              initialDelaySeconds: 30
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 3
              type: 'Readiness'
            }
            {
              failureThreshold: 5
              httpGet: {
                path: '/manage/info' /* /actuator */
                port: 8081
                scheme: 'HTTP'
              }
              initialDelaySeconds: 30
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 3
              type: 'Startup'
            }
          ]
```

Kusto Query logs shows:
```console
Stopping container aca-petcliaca-admin-server
Stopping container aca-petcliaca-admin-server
Startup probe failed: Get "http://10.250.0.221:8081/manage/health": dial tcp 10.250.0.221:8081: connect: connection refused          
Startup probe failed: Get "http://10.250.0.221:8081/manage/health": dial tcp 10.250.0.221:8081: connect: connection refused
Startup probe failed: Get "http://10.250.0.101:8081/manage/health": dial tcp 10.250.0.101:8081: connect: connection refused    
Startup probe failed: Get "http://10.250.0.101:8081/manage/health": dial tcp 10.250.0.101:8081: connect: connection refused    
Successfully pulled image "acrpetcliaca.azurecr.io/petclinic/admin-server:8ddcc039" in 5.235310586s
Successfully pulled image "acrpetcliaca.azurecr.io/petclinic/admin-server:8ddcc039" in 5.235310586s
Updating revision : aca-petcliaca-admin-server--cxjblx4  
Updating revision : aca-petcliaca-admin-server--cxjblx4
Pulling image "acrpetcliaca.azurecr.io/petclinic/admin-server:8ddcc039"
Pulling image "acrpetcliaca.azurecr.io/petclinic/admin-server:8ddcc039"
```

Whereas when I run locally the Docker image , I can then exec a shell to check inside the container :

```console
curl localhost:8081/manage/info
{"git":{"branch":"main","commit":{"id":"c15aa99","time":"2022-10-03T19:31:50Z"}},"build":{"encoding":{"reporting":"UTF-8","source":"UTF-8"},"version":"2.6.6","artifact":"aca-spring-petclinic-admin-server","java":{"source":"11","target":"11"},"name":"aca-spring-petclinic-admin-server","time":"2022-10-03T19:58:33.771Z","group":"org.springframework.samples.petclinic.admin"}}
```

**Comment by kendallroden** [comment]
This is not an aca probe you have set up, but a probe in the code correct?

**Comment by csteeg** [comment]
I'm having the same issue. No mather how I turn on the health probes, they always show "disabled" in the azure-portal.
If I supply the probes through my bicep deploy, or if I turn them on manually through azure portal, the result is azure portal shows "disabled" for all three of them

**Comment by kendallroden** [comment]
@csteeg raising this to the team
