### ISSUE TITLE
ContainerAppConsoleLogs_CL table is not created

### ISSUE THREAD

**Issue by EtienneLorthoy** [microsoft/azure-container-apps#450]
> No _ContainerAppConsoleLogs_CL_ table
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
_ContainerAppConsoleLogs_CL_ doesn't seem to be created when I deploy a Container App Env and a Container App. So I'm unable to get Console Logs.
I do have the other table for System Logs _ContainerAppSystemLogs_CL like shown in this doc https://learn.microsoft.com/en-us/azure/container-apps/log-monitoring?cid=kerryherger&tabs=bash

### Steps to reproduce
1. Deploy with Bicep Container App Env, Container App (could use HelloWorld Container), and a linked Log Analytics Workspace 
2. Open Log Analytics Workspace in Azure portal, tab "Logs" and show in the section "Tables" : a _ContainerAppSystemLogs_CL is there but no ContainerAppConsoleLogs_CL.

**Expected behavior**
See that sweet sweet ContainerAppConsoleLogs_CL table that could help me diag container bootstrap issue.

**Actual behavior**
No table, no console logs

**Screenshots**         
![image](https://user-images.githubusercontent.com/18291446/195692501-e8aa73e7-b3ff-470d-97c8-a131d3606051.png)

### Additional context
I tried _az containerapp logs show \
  --name <ContainerAppName> \
  --resource-group <ResourceGroup> \
  --tail 50_
with no success.

Here's the bicep file used, inspired from https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.app/container-app-create
```
resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2020-10-01' = {
  name: containerAppLogAnalyticsName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
  }
}

resource containerAppEnv 'Microsoft.App/managedEnvironments@2022-01-01-preview' = {
  name: containerAppEnvName
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
  }
}
```

**Comment by cwe1ss** [comment]
Do you see any console output in the [Log Stream](https://learn.microsoft.com/en-us/azure/container-apps/log-streaming?tabs=bash) page of the Container App? I guess it would only create the Log analytics table if there's actual log output.

You could also try the (very) new "azure-monitor"-based diagnostics: https://learn.microsoft.com/en-us/azure/container-apps/log-options
This will send the logs to the tables `ContainerAppConsoleLogs` and `ContainerAppSystemLogs` (without the `_CL`)

**Comment by EtienneLorthoy** [comment]
No console output in the Log Stream in the Azure Portal. The container does try to bootstrap, but then it fails almost immediately. Probably a missing config for my asp.net app, or something like it. So the log stream won't show anything because the container isn't running long enough to show up there.

Getting those precious app console logs somewhere will help to diagnose future issues, as it most likely won't be the last time.

I'll give azure-monitor a try!

**Comment by EtienneLorthoy** [comment]
So far:
- I tried running my bicep template with the basic hello-world image: it does create the ContainerAppConsoleLogs_CL properly.
- I tried Azure Monitor. Works as you said it would. It creates the same tables without _CL. But if there isn't the ContainerAppConsoleLogs_CL at first, the Azure Monitor logging options won't create ContainerAppConsoleLogs (without _CL)

It seems that if the container fails "too quickly" (let's say a few seconds) it will lose the console logs.

**Comment by EtienneLorthoy** [comment]
Finally: the container I was using wasn't outputting a single console line. And since the ContainerAppConsoleLogs_CL table seems to be created at the first output line, in my case it was never created.

Ensuring that the container outputting something fixed the issue for me.

**Comment by pablospe** [comment]
I have this problem but with Azure Container Jobs. As far as I understand, I am generating output, but seems I can't see the actual output I couldn't debug it.

Is there any Azure Container Jobs template? Perhaps I started wrong and there is a misconfiguration before.

**Comment by pablospe** [comment]
Related Issues

#945 - Intermittent log generation for short-lived jobs
#1206 - Container App Jobs logging differences between manual vs queue triggers
hashicorp/terraform-provider-azurerm#30116 - Terraform provider authentication issue that triggers workspace recreation

**Comment by duckdrone** [comment]
@pablospe I think this should help you:
https://azureossd.github.io/2025/08/12/Log-Analytic-tables-in-Container-Apps-not-being-created/

setting disableLocalAuth to false worked for me.
