### ISSUE TITLE
Is it already possible to use Premium Sku for Container Apps Environment?

### ISSUE THREAD

**Issue by macpak** [microsoft/azure-container-apps#452]
Hi,

I'd like to test some features provided in `2022-06-01-preview`, namely `vnetConfiguration.outboundSettings`. As far as I know, in order to do that it, I need to use `Premium Sku`. I've tried to create a Container Apps Environment with `Sku = Premium`, but I get an error: `PremiumManagedEnvironmentCreationNotEnabled`. What do I need to do to start using `Premium Sku` ?

**Comment by kendallroden** [comment]
Hi @macpak thanks for the question. We were evaluating the introduction of the Premium SKU but have delayed based on optimizations we are planning that will enhance the experience on a multitude of fronts. We will keep the community informed of the new ETA as more details are available
