### ISSUE TITLE
Probe successThreshold value validation not concistent with Bicep

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure-container-apps#454]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

see also [https://github.com/microsoft/azure-container-apps/issues/361](https://github.com/microsoft/azure-container-apps/issues/361)

This Bicep Probe config is validated in VS, a mouseover shows _XX_

```console
successThreshold: int
Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness and startup. Minimum value is 1. Maximum value is 10.
```

```sh
          probes: [
            {
              failureThreshold: 5
              httpGet: {
                path: '/manage/health/liveness' /* /actuator */
                port: 8081
                scheme: 'HTTP'
              }
              initialDelaySeconds: 30
              periodSeconds: 60
              successThreshold: 5
              timeoutSeconds: 30
              type: 'Liveness'
            }
            {
              failureThreshold: 5
              httpGet: {
                path: '/manage/health/readiness' /* /actuator */
                port: 8081
                scheme: 'HTTP'
              }
              initialDelaySeconds: 30
              periodSeconds: 60
              successThreshold: 5
              timeoutSeconds: 30
              type: 'Readiness'
            }            
          ]
```

### Steps to reproduce
1. Deploy an ACA with the above Probe setting  successThreshold: 5
2. Look at the logs

**Expected behavior** [What you expected to happen.]
The deployment should be successfull as the VS code the Linter shows 'Maximum value is 10.'

**Actual behavior** [What actually happened.]

```console
"ContainerAppProbeSuccessThresholdStartupOrLivenessInvalid\",\r\n            \"message\": \"Container 'aca-petcliaca-visits-service' 'Type' probe's SuccessThreshold must be 1.\"\r\n          ***,\r\n          ***\r\n            \"code\": \"ContainerAppProbeSuccessThresholdStartupOrLivenessInvalid\",\r\n            \"message\": \"Container 'aca-petcliaca-api-gateway' 'Type' probe's SuccessThreshold must be 1.\"\r\n          ***\r\n        ]\r\n      ***\r\n    ]\r\n  ***\r\n***"***]***
```

**Screenshots**         
N/A

### Additional context
Bicep from GH Workflow

**Comment by ruslany** [comment]
@ezYakaEagle442 - I think the VS code validation for bicep uses the property definition from the [azure-rest-api-spec repo](https://github.com/Azure/azure-rest-api-specs/blob/19aa8ab5d14b22bdeb67eab31c65b47c5380fd06/specification/app/resource-manager/Microsoft.App/stable/2022-03-01/CommonDefinitions.json#L198). I don't think it has the logic to validate the min/max values based on the type of the probe. The property description and the error message are consistent though.
