### ISSUE TITLE
Feature Request: Easier to navigate back and forth between Container Apps Environment and Container Apps

### ISSUE THREAD

**Issue by TonyFjo** [microsoft/azure-container-apps#457]
**Is your feature request related to a problem? Please describe**.  
When you click on an app in Container Apps Environment you the view changes and you get to the container app. There is a link at the top but then you have to navigate back to container apps environment before we can move to next container app.

![image](https://user-images.githubusercontent.com/67278295/196124386-2d58fc7a-e011-4974-a557-798b92dbbae3.png)

**Describe the solution you'd like**.    
A clear and concise description of what you want to happen, any scenarios it will unblock, etc.
Under apps in container apps environment you get a a list of the apps that you can navigate to and when you click you end up on the app page and there is no way to directly cklick on the next app. Usually you have several apps working togheter and you need to move between them.

![image](https://user-images.githubusercontent.com/67278295/196124538-b2488b9c-c644-435e-9a27-cca71988e88d.png)

An solution for this could be that the view looks like a lot of other views where we keep the previous level to the left of the container apps view.

![image](https://user-images.githubusercontent.com/67278295/196124628-23bff2c2-bece-4fa2-a8fc-0da8998a77d5.png)

**Describe alternatives you've considered**.   

**Additional context**.

**Comment by kendallroden** [comment]
Thanks for your feedback

**Comment by simonjj** [comment]
Unfortunately, based on portal team conversation there are some issues with enabling this. We won't be able to do this.
