### ISSUE TITLE
Unable to create app Limited to VNet from cli

### ISSUE THREAD

**Issue by MonsieurTib** [microsoft/azure-container-apps#458]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
az containerapp create (cli) does not expose a parameter for ingress traffic "Limited to VNet".  
When Ingress is set to "Internal", Ingress traffic is set to "Limited to Container Apps Environment"

**Screenshots**         

<img width="851" alt="screen-az" src="https://user-images.githubusercontent.com/11044865/196244861-42a33a71-1d1d-4e08-b5ff-e2a15fb75a21.png">

**Comment by kendallroden** [comment]
Hi there- sorry for any confusion. When you deploy the app in a VNet scenario and want the "Limited to VNet" you can use the "--ingress internal" command in the CLI

**Comment by MonsieurTib** [comment]
Hi @kendallroden,
thank you for clarifications, it works.
