### ISSUE TITLE
Getting MaxNumberOfGlobalEnvironmentsInSubExceeded for making second ACA in free tier

### ISSUE THREAD

**Issue by pamelafox** [microsoft/azure-container-apps#459]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

From my personal Azure account, I am trying to create a deployment using the "Deploy to Azure" flow.

Here's the link I'm using:

https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fpamelafox%2Fbabybuddy-azure%2Fmain%2Finfra%2Fmain.json

When I specify a region where I do not have any container app environments (e.g. "Canada Central"), I get this error:

```
{"code":"InvalidTemplateDeployment","details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"MaxNumberOfGlobalEnvironmentsInSubExceeded","message":"The subscription '74feb6f3-f646-478d-a99b-37fafee75e29' cannot have more than 1 environments among all regions."}]}],"message":"The template deployment 'Microsoft.Template-20221017144926' is not valid according to the validation procedure. The tracking id is '5a281424-3495-456e-ad39-508b6d51428f'. See inner errors for details."}
```

I *am* able to successfully deploy the resources when I follow the same link from my corporate account, which has a higher tier.

**Expected behavior** [What you expected to happen.]

According to the documentation at https://learn.microsoft.com/en-us/azure/container-apps/quotas, "Pay-as-you-go and trial subscriptions are limited to 1 environment per region per subscription."

I expected that if I specified a region where I had no existing container app environment, it would successfully create it.

**Actual behavior** [What actually happened.]

I got the MaxNumberOfGlobalEnvironmentsInSubExceeded error instead.

**Screenshots**         

![Screen Shot 2022-10-17 at 3 01 03 PM](https://user-images.githubusercontent.com/297042/196292035-e476e829-25da-4c03-a5a3-cef0922e7a04.png)

**Comment by kendallroden** [comment]
Based on the above this documentation has been updated

**Comment by onionhammer** [comment]
@kendallroden To be clear; 

```
* Pay-as-you-go and trial subscriptions are limited to 1 environment per region per subscription.
```

This text was removed; does that mean the limit of 1 for pay-as-you-go is lifted to 5?
