### ISSUE TITLE
Support for mounting Azure files inside a container

### ISSUE THREAD

**Issue by vikramjb** [microsoft/azure-container-apps#46]
I am testing a React + .Net Core 3.1 application on Container Apps and it seems to be working without issues except for persistent file storage. In my local container I was able to mount an Azure file instance by running the container in privileged mode. However I don't see an option in ACA for running the container in privileged mode or connect the container to an Azure files instance.

Are there plans to support this feature?

**Comment by tomkerkhove** [comment]
+1

**Comment by xatier** [comment]
+1

**Comment by iAmBipinPaul** [comment]
+ 1

**Comment by anthonychu** [comment]
CLI support for this is coming soon. If you want to give it a try now, you'll need to do 3 things via ARM:

- Configure the file share storage on the Container Apps environment
- Add a volume to your revision, referencing the storage you created
- Mount the volume in the containers that need it

See this ARM template for adding a storage:

```json
{
  "type": "Microsoft.App/managedEnvironments",
  "apiVersion": "2022-03-01",
  "name": "[parameters('environment_name')]",
  "location": "[parameters('location')]",
  "properties": {
    "daprAIInstrumentationKey": "[parameters('dapr_ai_instrumentation_key')]",
    "appLogsConfiguration": {
      "destination": "log-analytics",
      "logAnalyticsConfiguration": {
        "customerId": "[parameters('log_analytics_customer_id')]",
        "sharedKey": "[parameters('log_analytics_shared_key')]"
      }
    }
  },
  "resources": [
    {
      "type": "storages",
      "name": "myazurefiles",
      "apiVersion": "2022-03-01",
      "dependsOn": [
        "[resourceId('Microsoft.App/managedEnvironments', parameters('environment_name'))]"
      ],
      "properties": {
        "azureFile": {
          "accountName": "[parameters('storage_account_name')]",
          "accountKey": "[parameters('storage_account_key')]",
          "shareName": "[parameters('storage_share_name')]",
          "accessMode": "ReadWrite"
        }
      }
    }
  ]
}
```

Then include the volume and volume mounts in your Container Apps resource:

```json
{
  "apiVersion": "2022-03-01",
  "type": "Microsoft.App/containerApps",
  "name": "[parameters('containerappName')]",
  "location": "[parameters('location')]",
  "properties": {
    
    ...

    "template": {
      "revisionSuffix": "myrevision",
      "containers": [
        {
          "name": "main",
          "image": "[parameters('container_image')]",
          "resources": {
            "cpu": 0.5,
            "memory": "1Gi"
          },
          "volumeMounts": [
            {
              "mountPath": "/myfiles",
              "volumeName": "azure-files-volume"
            }
          ]
        }
      ],
      "scale": {
        "minReplicas": 1,
        "maxReplicas": 3
      },
      "volumes": [
        {
          "name": "azure-files-volume",
          "storageType": "AzureFile",
          "storageName": "myazurefiles"
        }
      ]
    }
  }
}
```

**Comment by sylus** [comment]
Was curious if this was released since is ACA is GA now.

Waiting for this to be added so then the terraform provider can implement the specs, similar to how this worked in Azure Web Apps for Containers :)

**Comment by sylus** [comment]
Hi @anthonychu I keep getting asked why apps can't deploy Drupal onto ACA since we can do it on Kubernetes, and I am saying until Azure Files is fully supported we can't do stateful apps. To minimize confusion is there a place we can add this to the docs so people can know what is / isn't possible on ACA at the moment?

**Comment by sylus** [comment]
Oh wow @kendallroden that was a much quicker turnaround then i was thinking.

I will definitely be testing this out over the next few weeks!

Thank you for your response and the link it is greatly appreciated :D

**Comment by jwalitptl** [comment]
does azure file supports "ReadWriteMany" for container apps same as AKS
