### ISSUE TITLE
How to setup AzureDevops Selfhosted agents in Azure ContainerAppservice?

### ISSUE THREAD

**Issue by vivuu1989** [microsoft/azure-container-apps#462]
We are using Azuredevops server and looking for a way to run our self hosted Build agents in Azure ContainerAPP service as this will support KEDA. But looking in Microsoft documents, there is no guidance to create it and couldnt find any good article on how to create the ADO self hosted agents in AzureContainerApp with private access.

Is anybody achieved this in your envireonments or tried? Please help me with the steps if you have achieved this already.

{
    "status": "Failed",
    "error": {
        "code": "InternalServerError",
        "message": "Internal server error occurred. correlation ID: xxxxxxxxxxxxxxxx"
    }
}

**Comment by kendallroden** [comment]
Hi @vivuu1989 are you trying to use the KEDA scaler Job object for devops agents? This is not supported today per the docs. We are currently designing Jobs! Let me know

**Comment by vivuu1989** [comment]
> Hi @vivuu1989 are you trying to use the KEDA scaler Job object for devops agents? This is not supported today per the docs. We are currently designing Jobs! Let me know

But from the docs, Its mentioned that Container app is supporting KEDA and also found some articles about build agents in containerapps.

![image](https://user-images.githubusercontent.com/25169130/197375460-d814e558-9a8c-422a-b611-8c377849faa4.png)

**Comment by vivuu1989** [comment]
> Hi @vivuu1989 are you trying to use the KEDA scaler Job object for devops agents? This is not supported today per the docs. We are currently designing Jobs! Let me know

hi, 

But from the docs, its mentined that the containerapp is supporting KEDA feature and over internet could find some articles about configuring build agents in containerapps.

https://techmindfactory.com/Containers-For-Azure-DevOps-Automation/

**Comment by kendallroden** [comment]
see: https://github.com/microsoft/azure-container-apps/issues/24 and please add comments there for tracking
