### ISSUE TITLE
Feature Request/Question: Configure static external ip address for container apps in similar way to container instances?  

### ISSUE THREAD

**Issue by ErikRosengren-work** [microsoft/azure-container-apps#466]
**Is your feature request related to a problem? Please describe**.  
I have a use case where I need a container app to have a static egress IP-address that is the same every time (for whitelist reasons of a TCP connection). As far as I can tell, the only way to get a static public egress IP-address is to deploy the container environment to a VNET which will then create a resource group containing two public IP-addresses, one for egress and one for ingress, detailed here: https://learn.microsoft.com/en-us/azure/container-apps/networking#managed-resources
The issue with this approach is that I don't have the option to deploy the IP-address since this resource group is managed by the Azure Container Apps platform. So my question is: what is the "correct" way to ensure that the egress IP-address from a container app is always the same? Is it to use a VNET and the public ip that is created by the Azure Container Apps platform? 

For container instances it is possible to get this behavior by using a NAT Gateway and a VNET but as far as I can tell this is not possible with container apps, is that correct?

Apologies if this is the wrong place for this question!

**Comment by kendallroden** [comment]
Hi @ErikRosengren-work! 
Today, a given ACA env has a single outbound static IP that is used by all of the apps from an egress perspective. We are working on support for the scenario you just described supported by ACI where you will be able to use a NAT Gateway.

**Comment by aarondandy** [comment]
@kendallroden, what is the appropriate place for us to request NAT gateway support or egress control, and how can us users be kept up to date on the progress of such a feature?
