### ISSUE TITLE
Feature Request: Allow user to set the imagepullpolicy

### ISSUE THREAD

**Issue by yodobrin** [microsoft/azure-container-apps#470]
**Is your feature request related to a problem? Please describe**.  
While in development, the image tag may not change while the underline image is. since there is no control on the imagepull policy in aca, the developer must work with changing tags.

**Describe the solution you'd like**.    
Allow users (under the 'Continuous deployment' blade, as a suggestion, it could be elsewhere) the ability to perform always pull - with proper information that this is not for production. This will allow developers to focus on functionality they create w/o changing the image tag with each build. this capability should be also exposed via bicep.

**Describe alternatives you've considered**.   
developers will need to tag the image with a new tag on each build.

**Additional context**.  
As developers might be working locally (not running actions or pipelines) giving new tags could be a pain, this will allow them to focus on developing capabilities.

**Comment by simonjj** [comment]
Please _always_ use unique tags. Please see here for more background: https://learn.microsoft.com/en-us/azure/container-registry/container-registry-image-tag-version
