### ISSUE TITLE
az containerapp env dapr-component set returns a "DaprComponentInvalidRequest...must contain properties.ComponentType" Error

### ISSUE THREAD

**Issue by digitalkingsley** [microsoft/azure-container-apps#472]
### Issue description

I'm attempting to add a Dapr Component to the Container Apps Environment for my project, via the Azure CLI.
However, each time I issue the instruction to add  the component, I end up with the error shown in the images below:<br><br>

Here's the instruction I issued to add the component: <br>

   `az containerapp env dapr-component set --name %env% --resource-group %rg% --dapr-component-name azurekeyvault --yaml azurekeyvault.yaml`  **(Command Prompt)**<br>

   or

   ` az containerapp env dapr-component set --name $env --resource-group $rg --dapr-component-name azurekeyvault --yaml 
     azurekeyvault.yaml ` **(Powershell)**

<br>

 **Note:**     ***env*** and ***rg*** are environment-variables I defined for the Container Apps Environment and the Resource Group respectively, within the terminal-sessions.<br><br>

***Command Issued Via The Command Prompt (With Error Message)***

![via-command](https://user-images.githubusercontent.com/41226938/198911049-b2da7b18-6ea9-4a64-aff5-5d07608ea5ba.JPG)
<br><br>

***Same Command Issued Via Power Shell (With Error Message)***

![via-powershell](https://user-images.githubusercontent.com/41226938/198912393-a373ceb5-4022-474b-bb53-fc040c8a614b.JPG)

<br><br>

***And Here's My Dapr Component Config File***

![yaml](https://user-images.githubusercontent.com/41226938/198912521-d9fb36cd-70c0-45c6-af4e-efac2432cef6.JPG)

### Steps to reproduce
1. Install the Azure CLI
2. Add the containerapp extension with the following command:

    `az extension add --name containerapp --upgrade`

3. Register the **Microsoft.App** and **Microsoft.OperationalInsights** namespaces with the following commands:

    `az provider register --namespace Microsoft.App`

    `az provider register --namespace Microsoft.OperationalInsights`
4. Create a **secretstore** config-file as shown above
5. Register variables as shown above
6. Navigate to the directory where the config-file was created and issue the command (s) shown above. <br><br>

### Expected behavior
I expected the Dapr Component to be added to the Container Apps Environment <br>

### Actual behavior
An error (as shown in the images above) occured.

**Comment by digitalkingsley** [comment]
Anyone looking into this, please?

**Comment by kendallroden** [comment]
Yes will investigate. Can you also confirm you ran the commands without environment variables to ensure the same behavior?

**Comment by kendallroden** [comment]
I could not reproduce your issue in powershell or on my mac using bash. I have a feeling your yaml file has some type of spacing issue.

**Comment by digitalkingsley** [comment]
> I'm sorry, I could not reproduce your issue in Powershell or on my mac using bash. I have a feeling your yaml file has some type of spacing issue.

I had the same feeling about improperly formed yaml file, too. But, after re-writing my yaml file (for Azure Container Apps) so many times, with the same result, I gave up. 

You should know, I run Dapr locally, with yaml files written for all components (secretstore and pubsub), and everything works perfectly. I only encounter this issue when I attempt to add Dapr Components (to a Container App Environment) via the CLI.

Anyways, In the interim, I have resorted to creating Container Apps Environments (and adding components) via the Azure Portal, and then using the CLI only when provisioning the Container Apps themselves.

Thanks for your help.

**Comment by SophCarp** [comment]
I am going to close this issue since you seem to have a solid workaround. Let me know if there's anything else we can help you with!

**Comment by vmateiaiv** [comment]
Yeah, it's still not solved though!

**Comment by marcelmedina** [comment]
+1
still getting the same error, after following the documentation: https://learn.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash%2Cazure-cli

**Comment by JasonRodman** [comment]
Any news on this yet? I am running into the same problem. I would like to script my entire deployment and this is the only part that simply does not work. I have resort to the azure powershell commands for this part to work around this issue.

**Comment by Ryan-PRQX** [comment]
I banged my head on this for a couple hours.  For anyone running into this issue, it is a file encoding problem probably.  I resolved it by using ascii encoding for the powershell I was using.

`$ContentToWrite | Out-File -FilePath $tempFilePath -Force -Encoding ascii`

**Comment by 12emerta** [comment]
> I banged my head on this for a couple hours. For anyone running into this issue, it is a file encoding problem probably. I resolved it by using ascii encoding for the powershell I was using.
> 
> `$ContentToWrite | Out-File -FilePath $tempFilePath -Force -Encoding ascii`

I was creating yaml files on the fly and changing the file save from utf8 to ascii fixed my issue as well.
