### ISSUE TITLE
Announcement:  Deprecation of API version 2022-01-01-preview

### ISSUE THREAD

**Issue by torosent** [microsoft/azure-container-apps#475]
Azure Container Apps will deprecate API version 2022-01-01-preview on March 20, 2023.  Please make sure you are using the latest stable or preview versions in your APIs and templates.

**Comment by navesimchi** [comment]
@torosent 
We use a container app and all of a sudden its console is stuck with a black screen and we get this error in the activity log:
![image](https://github.com/microsoft/azure-container-apps/assets/118109659/8c360113-1abb-46ea-8cb2-22908333ccd7)

Do you know how to change this API version so it will work?
