### ISSUE TITLE
Restricted subnet ranges

### ISSUE THREAD

**Issue by Code-DJ** [microsoft/azure-container-apps#476]
**Is your feature request related to a problem? Please describe**.  
Per the documentation [https://learn.microsoft.com/en-us/azure/container-apps/networking](https://learn.microsoft.com/en-us/azure/container-apps/networking) the following IP addresses are restricted. It is my understanding that these IP addresses cannot be in use either in Azure VNET or any network connected to Azure using VPN e.g. on-prem. In our situation we are using 172.30.0.0/16 on-prem.

- 169.254.0.0/16
- 172.30.0.0/16
- 172.31.0.0/16
- 192.0.2.0/24

It is not clear why these subnets are blocked.

**Describe the solution you'd like**.    
Allow us to provide an alternate subnet that can be used by Azure.

**Describe alternatives you've considered**.   
The only alternative is to migrate the on-prem subnet which will be quite an endeavor.

If the above assumptions are incorrect then the documentation needs to be updated with additional details.

**Comment by kendallroden** [comment]
Hi @Code-DJ - this is due to this set of ranges being reserved by the underlying AKS platform that we are operating on your behalf. The same requirements are present in the AKS service. I will talk to the team to see if some of the work we are doing will alleviate this requirement or if there are work arounds for customers in your position.

**Comment by kendallroden** [comment]
@Code-DJ  we are working on some networking optimizations which should land around Q12023 that will remove this set of restricted ranges

**Comment by anrub** [comment]
I read the documentation and understand, that the subnet ranges can't be used as ACA subnet. But in my view, it should'nt be a problem if the IPs are used somewhere else.

**Comment by Code-DJ** [comment]
Hi, any updated timeline on this? Thanks!

**Comment by simonjj** [comment]
We've added details to the documentation. If this is still impacting you @Code-DJ maybe you can implement NAT translation on your VNet to shuffle your traffic back and forth.
