### ISSUE TITLE
[Bug] Failed to provision container apps (replicated during a workshop with 50p)

### ISSUE THREAD

**Issue by sinedied** [microsoft/azure-container-apps#478]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
3 weeks ago at Devoxx conference we played this workshop to a full room of 50 people: https://azure.github.io/aca-java-runtimes-workshop/

We tested it few days before the event with a few people with internal MS subscriptions, without any issues.

During the event, when came the time to create the Container Apps Environment and deploy Container Apps, we ran into issues:

- First, some folks seems to have the command creating the Container Apps Environment stuck indefinitely (some let it wait 20min+). I could replicate this also on my machine. Even though the CLI command was stuck (I killed it at some point), the environment seems to have been created fine when looking at the portal.

Command used ([workshop step](https://azure.github.io/aca-java-runtimes-workshop/#creating-the-container-apps-environment)):
```
az containerapp env create \
    --resource-group "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --tags system="$TAG" \
    --name "$CONTAINERAPPS_ENVIRONMENT" \
    --logs-workspace-id "$LOG_ANALYTICS_WORKSPACE_CLIENT_ID" \
    --logs-workspace-key "$LOG_ANALYTICS_WORKSPACE_CLIENT_SECRET"
```

Then the main issue we face was when creating the container apps ([see workshop step](https://azure.github.io/aca-java-runtimes-workshop/#creating-the-container-apps)). Everytime we tried to create a container app, it failed with an error and no helping message ("Could not provision container apps", no detail even when enabling debug logs).

This could be reproduced on standard subscriptions, Azure Pass subscriptions and MS internal subscriptions.
We tried deploying through CLI or Portal, same result.

Everyone was using the location `eastus2` at the time.

Then after one hour trying different things, we found that re-creating the Container Apps Environment in a different location (we switched to `west europe`) fixed the issue.

**This was really a bad Azure experience for all the folks participating in the workshop!**. Even with 4 Azure experts present at the workshop trying different things to find the issue, we were helpless facing this as no meaningful errors could help us understand was was wrong, and it only took a "chance guess" to find a workaround.

Maybe the region was over capacity (our guess?), preventing the provisioning of the Container Apps, but in that case an explicit error message would have helped. Or even better, preventing the creation of the Container Apps Environment itself would have been better.

### Additional context
The errors could be reproduced on a variety of environments:
- Mac OS (Intel)
- Mac OS (M1)
- Linux
- Windows 10 (with WSL/Ubuntu)
- Windows 10

**Comment by kendallroden** [comment]
When was the workshop? Azure Key Vault had an outage this week.

**Comment by cstickel** [comment]
might that be related to:
https://github.com/microsoft/azure-container-apps/issues/465

we had huge issues with long lasting (40-90 min) and partially completely failing container app environment deployments last week. also deleting took ages. we thought it might be related to the fact that they were internal-only (first time we tried internal-only container app environments) and terraform. on thursday it worked fine with azure cli. and non internal only we created the last month multiple times without issues. however, maybe it was not related to terraform or internal-only, but just completely broken for some time?
in our case it was wednesday afternoon (~14:00-18:00 MEZ 02.11.2022) and we created it in `germanywestcentral`.
going to try it again today to check if it was a temporary issue at that time and not because of the combination of terraform&internal-only.
in the other issue quite some people seemed to have issues this week with container app environments.

**Comment by cstickel** [comment]
oh, maybe then our issues were connected to the keyvault outage.
at least it was somehow a temporary issue, since i tried it at the weekend and everything worked fine (~10 min for creating/deleting an internal only container app env).

**Comment by sinedied** [comment]
@kendallroden The workshop was on October, 11th, from 13h30 to 16h30 CET.

To be fair the main issue wasn't that deployments weren't working (outage can happen), but that we were completely helpless facing the situation in front of the audience:
- no incident reported at the time on the portal or status page
- no helpful error message explaining why the deployments failed, even hints would have been appreciated!
- not even the system logs were helpful trying to debug the issue

**Comment by SophCarp** [comment]
We're working on enhancements for visibility into environments that are in waiting state based on overutilization of a given region.
