### ISSUE TITLE
Support for path property on ingress configuration

### ISSUE THREAD

**Issue by fegonfe** [microsoft/azure-container-apps#48]
To allow use cases where app runs on root and api's run on /api/apix.

API config:
{
  ...
  "configuration": {
      "ingress": {
          "external": **false**,
          "targetPort": 80,
          "transport": auto,
          "path": "/api/apix"
      }
  }
}

root config:
{
  ...
  "configuration": {
      "ingress": {
          "external": **true**,
          "targetPort": 80,
          "transport": auto,
          "path": "/"
      }
  }
}

**Comment by kendallroden** [comment]
closing this request. See #99 to track future progress
