### ISSUE TITLE
Unable to authenticate to container registry  

### ISSUE THREAD

**Issue by edgreenberg-mri** [microsoft/azure-container-apps#480]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ X] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.
Unable to authenticate to container registry.

System: Centos 7

az version indicates:
```
edg@edglaptop ~ $ az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "containerapp": "0.3.13"
  }
}
edg@edglaptop ~ $ 
```
After az login, do ```az acr login``` and get error 
```
AADSTS700082: The refresh token has expired due to inactivity. 
```
### Steps to reproduce
1. do ```az login --scope https://management.core.windows.net//.default``` and interact with web browser. Note that we use a third party SSO: okta. 
2. do: ```sudo az acr login --name REGISTRY.azurecr.io --expose-token```

**Expected behavior** [What you expected to happen.]

I expect a token that I can use with sudo docker login REGISTRY.azurecr.io

**Actual behavior** [What actually happened.]
Afer the ```az acr login``` I get:
```
edg@edglaptop ~ $ sudo az acr login --name happysoftware.azurecr.io --expose-token
The login server endpoint suffix '.azurecr.io' is automatically omitted.
AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2022-06-16T18:30:37.7431805Z and was inactive for 90.00:00:00.
Trace ID: d2bc0872-b84d-4ef9-8687-4cd6cd35a300
Correlation ID: 48c26c87-c108-4ce4-b760-9b7454a36cf5
Timestamp: 2022-11-07 19:32:06Z
To re-authenticate, please run:
az login --scope https://management.core.windows.net//.default
edg@edglaptop ~ $ 
```
Doing the ```az login``` again just sends me through the same loop. 

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?  CLI

**Comment by cwe1ss** [comment]
Sounds like this is a specific issue with the "Azure Container Registry" service instead of "Azure Container Apps". There would be a separate GitHub repository for Azure Container Registry here: https://github.com/Azure/acr

**Comment by edgreenberg-mri** [comment]
Posting there.

**Comment by anthonychu** [comment]
Closing this for now. Please reopen if this needs attention from Container Apps. Thanks. https://github.com/Azure/acr/issues/655
