### ISSUE TITLE
Can't delete env var via portal

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#482]
### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I created an ACA app with an env var. I then went into the portal to delete the env var but it won't let me. I see this dialog:
![image](https://user-images.githubusercontent.com/1944671/200593640-d0f45fdf-e4a6-45ea-b346-04bf2b05d25b.png)

Notice there's nothing under the "delete" column at the bottom right. Apparently, erasing the name of the var did seem to do it, but that doesn't seem like the right UX - and I think that's a bug too since an empty name isn't valid. There should be a checkbox under the "delete" column so I can choose multiple env vars to delete.

**Comment by anthonychu** [comment]
Thanks. I can repro this behavior. We'll investigate.
