### ISSUE TITLE
Feature Request: Overview should show overall status of app

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#484]
When I create an app that continually crashes (it never comes up ok), I would have expected something on the overview tab to tell me that something is wrong. Instead I have to know to go look under the "Revisions" tab to see that the revision is failing, and then I need to go look at the console logs to see the error messages.

Request/proposal: add some kind of "status" to the overview tab showing the status of the latest revision, or revisions if there's more than one receiving traffic. Then if there is one that's failing, it would be nice if there was a quick href that would take the user to more info. Perhaps show: `Failing (revisions | logs)` where "revisions" takes them to the revisions tab and the "logs" takes them to the "console log stream".

**Comment by anthonychu** [comment]
Thanks. We're tracking some improvements in health status over the next few months. We hope to surface this information more prominently.

**Comment by reidav** [comment]
@anthonychu would be great also to display all ingress endpoints in the container app (such as the one inherited from the custom DNS suffix settings in Container Environment).

**Comment by simonjj** [comment]
We've updated the overview and more updates will likely come. Check out the running status.
