### ISSUE TITLE
Error when trying to change Logs Destination from Azure portal

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#486]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
Attempting to change the log destination from the default (Azure Log Analytics) from the Azure portal fails with a "Failed to update logging options" error.
(Previously, configuration changes could be made successfully.)

### Steps to reproduce
1. Select the [Management blade in Container Apps environment] - [Monitoring] - [Logging options].
2. Select another item ([Azure Monitor [preview] or [Don't save logs]) from the default ([Azure Log Analytics]) for the Log Destination, and click [save].

**Expected behavior** [What you expected to happen.]
The Log Destination setting is changed successfully.

**Actual behavior** [What actually happened.]
The following error message is displayed in the notification area and cannot be changed.

```
Update Logging Options
Failed to update logging options: No registered resource provider found for location 'japaneast' and API version '32' for type 'managedEnvironments'. The supported api-versions are '2022-01-01-preview, 2022-03-01, 2022-06-01-preview'. The supported locations are 'northcentralusstage, canadacentral, westeurope, northeurope, eastus, eastus2, eastasia, australiaeast, germanywestcentral, japaneast, uksouth, westus, centralus, northcentralus, southcentralus, koreacentral, brazilsouth, westus3, francecentral, southafricanorth, norwayeast'.
```

**Screenshots**         
![20221110_001](https://user-images.githubusercontent.com/15773157/201017989-e56a4029-47eb-43a0-8547-cb7cd7f151d8.png)

### Additional context
In the Azure Portal.

**Comment by RyDoug** [comment]
Same issue.

Re-registering the provider under subscription > resource providers did not help.

We are able to bypass this with using Azure CLI though.

Reference: https://learn.microsoft.com/en-us/cli/azure/containerapp/env?view=azure-cli-latest#az-containerapp-env-update

**Comment by dariagrigoriu** [comment]
Thank you for reporting this, the team is investigating.
