### ISSUE TITLE
ContainerApps: tokenStore is documented but not supported?!

### ISSUE THREAD

**Issue by adammerk** [microsoft/azure-container-apps#488]
> tokenStore is not currently supported.

If the **tokenStore** is not supported why is a "**enable token store**" parameter mentioned in "**az containerapp auth update**" command.

`az containerapp auth update --name
                            --resource-group
                            [--action {AllowAnonymous, RedirectToLoginPage, Return401, Return403}]
                            [--config-file-path]
                            [--custom-host-header]
                            [--custom-proto-header]
                            [--enable-token-store {false, true}]
                            [--enabled {false, true}]
                            [--excluded-paths]
                            [--proxy-convention {Custom, NoProxy, Standard}]
                            [--redirect-provider]
                            [--require-https {false, true}]
                            [--runtime-version]
                            [--set]`

See: https://learn.microsoft.com/en-us/cli/azure/containerapp/auth?view=azure-cli-latest#az-containerapp-auth-update

_Originally posted by @adammerk in https://github.com/microsoft/azure-container-apps/issues/479#issuecomment-1308420424_

Thanks for having a look!
Adam

**Comment by anthonychu** [comment]
Thanks for pointing this out. Looks like this parameter was added to the CLI by mistake.

**Comment by simonjj** [comment]
This should be fixed now that we have token store support.
