### ISSUE TITLE
Address already in use when running multiple Container Apps

### ISSUE THREAD

**Issue by jaliyaudagedara** [microsoft/azure-container-apps#490]
### This issue is a
- [x] bug report -> please search issues before submitting

### Issue description
I was migrating some set of Azure Container Apps that I have created like a year back (when it was in Preview). 

I have created a new Container Apps Environment and have created 3 Container Apps. One was created from Visual Studio Publish Wizard, others were created from the Portal itself. Deployed 2 Web APIs and 1 Blazor Project for created Container Apps. Deployment was done through GitHub actions generated from Visual Studio 2022 (17.5.0 Preview 1.0). I haven't used Dockerfiles, instead used .NET SDK container support.

All my containers are failing to start, upon checking the logs, I am seeing,
 ` Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use`

All the containers are attempting to run on Port 80.
![image](https://user-images.githubusercontent.com/5653381/201865338-416f6ff9-75d5-49d1-aad2-a6d44e07ad9d.png)

### Steps to reproduce
1. GitHub Repo: [https://github.com/jaliyaudagedara/azure-container-apps-demo](https://github.com/jaliyaudagedara/azure-container-apps-demo)

**Comment by anthonychu** [comment]
Took a look at your app. It appears you have 2 containers defined in your revision: a "hello world" container from the original container app that you created, and the app container you're trying to run. Both of them listen to port 80.

Your intention is likely just to have your app as the single container that's running. To do this, create a new revision and delete the hello world. See this screenshot of a similar app: 
![image](https://user-images.githubusercontent.com/3982077/201968351-4e44c2f9-6d88-4926-8582-c2cd107d8625.png)

**Comment by jaliyaudagedara** [comment]
@anthonychu, 

Thank you very much, that did it.
