### ISSUE TITLE
Dapr version running in Azure Container Apps

### ISSUE THREAD

**Issue by dmhiggins23** [microsoft/azure-container-apps#491]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I've been trying to get a container app running on azure using dapr binding component bindings.azure.storagequeues. For the configuration, I had to switch from using accountName to storageAccount, and accountKey to storageAccessKey, to get it to work. Checking the logs, I see the following entry: 'Container image "mcr.microsoft.com/daprio/daprd:1.8.4-msft-2-mariner" already present on machine'. My inference is that while the dapr reference provides documentation for 1.9, ACA is using 1.8.4. I believe that using managed  identity also requires the component version in 1.9 (so far, I have not been able to get managed identity to work to access the storage queue). I've been setting this up using the Azure portal, and couldn't find any way to either read or set the version of dapr to be used. 

**Expected behavior** [What you expected to happen.]
Managed identities and the dapr 1.9 config file schema for bindings.azure.storagequeues to work on Azure ACA.

**Actual behavior** [What actually happened.]
Appears to be using 1.8.4.

### Additional context
This happened on the portal.

**Comment by kendallroden** [comment]
There were a few fixes that delayed the 1.9 release. Barring issues, our goal is to release new version of dapr within 2-4 weeks of OSS release. 1.9.3 should be rolling out and available within 2 weeks. 
Managed identity is already supported today. Please let me know if the dapr integration guide in the docs does not provide clarity or create an issue if you have reproduction steps.

**Comment by dmhiggins23** [comment]
Thank you, I set up managed identity by setting azureClientId in the bindings component definition. Unfortunately, it didn't work. The container app console logs shows an error which includes the following text:

AuthenticationErrorDetail: The MAC signature found in the HTTP request '<A_BASE_64_STRING>' 
is not the same as any computed signature. 

If you have any insight into what may be causing this, I would appreciate any guidance. Thank you!
