### ISSUE TITLE
Support for container registries exposed on a custom port

### ISSUE THREAD

**Issue by ThorstenHans** [microsoft/azure-container-apps#499]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

Azure Container Apps prevents users from using a private Docker Registry (valid Docker Registry 2.0) that uses a non-standard port. For example: `myregistry.domain.com:9443` 

When creating a new Container App and specifying an `registry` having a port  in its `server` field, deployment will not succeed.
 
**Expected behavior** [What you expected to happen.]

Azure Container Apps should support private container registries exposed on various TCP ports

**Actual behavior** [What actually happened.]

Azure Container Apps  does not accept registries that explicitly specify a port

**Comment by ThorstenHans** [comment]
Any update regarding this one?

**Comment by lapfrank12** [comment]
Any updates? We were planning on using the container app service, but the lack of support for registries running on specific ports would force us to use AWS ECS instead.

**Comment by dan-connektica** [comment]
This is a significant blocker for our project, as the images we plan to deploy are hosted in an internal docker repo on a non-standard port. Is there any workaround available for this issue, or any timeline for when this issue will be corrected?

**Comment by ThorstenHans** [comment]
Maybe @dariagrigoriu can share some thoughts / updates / roadmap

**Comment by anthonychu** [comment]
This should be fixed now. Please reopen if still an issue.
