### ISSUE TITLE
Is Microsoft Orleans supported in Azure Container Apps?

### ISSUE THREAD

**Issue by christiansparre** [microsoft/azure-container-apps#5]
Azure Container Apps seems like a really interesting new service offering from Azure.

The documentation seems to be very dapr oriented. I'm wondering if hosting Orleans inside Azure Container Apps is going to be supported?

The connect multiple apps documentation (https://docs.microsoft.com/en-gb/azure/container-apps/connect-apps?tabs=bash)  only mentions HTTP.

Will it be possible to have an Orleans silo host (with multiple instances) as a container app and an Orleans client as another app within the same container app environment.

For Orleans TCP connections on multiple ports would need to be possible, but there are no networking documentation yet.

So my guess right now is, no Orleans is not supported? But it is hard to know with the current documentation.

Hope someone can shed some light on the possibilities and maybe limitations.

**Comment by jhedt** [comment]
Yes please.  What a fantastic microservice architecture that would be.

**Comment by christiansparre** [comment]
I have not had the time to play around with it yet but @jeffhollan and @JennyLawrance have elaborated a bit about the networking on twitter

* https://twitter.com/jeffhollan/status/1455916386190979078
* https://twitter.com/jennylwrnce/status/1455597456545050624

**Comment by christiansparre** [comment]
I have made a small sample showing that it works here https://github.com/christiansparre/HelloContainerApps

It is currently deployed to: https://spio-hello-aca4-client.orangegrass-26d615b9.northeurope.azurecontainerapps.io/

I'll probably delete it shortly as to not burn through all my Azure credits :)

**Comment by jeffhollan** [comment]
Wow! Are you cool if I share this sample out on Twitter?

**Comment by christiansparre** [comment]
@jeffhollan totally cool, share away! 👍 I'm going to clean it up a bit more to maybe have some variant of it as a sample for Orleans.

**Comment by hiyelbaz** [comment]
Does client-host communication trigger auto-scaling for silos?

**Comment by BigMorty** [comment]
Here is a sample showing Orleans in Container Apps - https://github.com/Azure-Samples/Orleans-Cluster-on-Azure-Container-Apps
