### ISSUE TITLE
Please include which policy is blocking creation of managed resource group

### ISSUE THREAD

**Issue by ChristianLloydGrannes** [microsoft/azure-container-apps#500]
When creating the Container App I receive this mesage:
_**"deploymentErrors": "ErrorCode: ManagedEnvironmentResourceGroupDisallowedByPolicy, Message: Fail to create managed environment because resource group creation is disallowed by policy,**_

I have several hundreds of policies so kind of hard identify which policy to exclude.

All other services include the name of the policy blocking...

**Comment by kendallroden** [comment]
Hi Christian. Working with the team on this topic will report back

**Comment by dariagrigoriu** [comment]
Planning updates to the Azure Container Apps FAQs to indicate how to bypass policy limitations.

**Comment by ractando** [comment]
Can we have any ETA for this @dariagrigoriu ?

**Comment by LianaAdaza** [comment]
Issue has been resolved. Please create a new issue if you continue to experience difficulties.

CC: @sanchitmehta
