### ISSUE TITLE
Continuous deployment - Devops Repo > Pipeline > Azure Container Registry > Update Existing Container

### ISSUE THREAD

**Issue by dyardy** [microsoft/azure-container-apps#505]
Is it possible to have the following components?
DevOps Repo > Pipeline > Azure Container Registry > Update Existing Container

**Given that the following is working** >  code is updated in Azure DevOps repo my code is checked in and the pipeline is triggered which will build the container and push it to the container registry.

I want to then trigger an Azure Container App to get the latest image out of the registry and rebuild.

**Is this possible?** 

I see that within the configuration of the container app there is a 'Continuous Deployment' option but this integration seems very connected with public GitHub (not DevOps).

**Comment by anthonychu** [comment]
We recently shipped an Azure DevOps task. Take a look at the docs here: https://learn.microsoft.com/azure/container-apps/azure-pipelines

It's currently installable from the Visual Studio Marketplace, but a version of the task will be available by default in Azure Pipelines in the next month or so.

**Comment by simonjj** [comment]
We now have a DevOps task.
