### ISSUE TITLE
Feature Request: availability in UK West

### ISSUE THREAD

**Issue by traynors22** [microsoft/azure-container-apps#507]
**Is your feature request related to a problem? Please describe**.  
A clear and concise description of what the problem is
We were looking at Azure Container Apps as a potential hosting option for one of our clients, they have a multi-region requirement where the data needs to reside in the UK. It looks like the service is currently only supported in UK South, is there any plans to extend the availability of the service to UK West?

**Describe the solution you'd like**.    
A clear and concise description of what you want to happen, any scenarios it will unblock, etc.  
A view as to if there is a plan for the service to be available in UK West

**Describe alternatives you've considered**.   
We are also considering AKS which is available in both regions.

**Additional context**.

**Comment by MatthewWilkes** [comment]
With apologies for a +1 comment, I agree that this would be very useful indeed. The zonal support of UK South helps mitigate the problem, but multi-region within the UK is one of the key reasons UK public sector organisations like Azure. Being able to deploy container apps across the UK regions would make it easier to choice container apps over app services, container instances or AKS.

**Comment by martinjosephogorman** [comment]
+1 same issue, need UK west

**Comment by bowlerma** [comment]
Would love to see this too.  To mitigate regional failures we require that our application be able to be deployed to paired regions, and for data sovereignty reason require these to be in the UK.  It would also help if availability zones were available in UK West, but that's another feature request.

**Comment by cachai2** [comment]
Closing as Azure Container Apps is available now in UK West.
