### ISSUE TITLE
Feature Request: ARM template for setting up DNS suffix

### ISSUE THREAD

**Issue by bppn** [microsoft/azure-container-apps#508]
The new feature "DNS suffix" is described in the documentation as a portal feature.  However, we are using container applications in a managed application and all setup is automatically.

A automated function would be needed.  Is this possible today, I cannot find any ARM documentation on this.

**Comment by tamland** [comment]
It's present in the preview version here: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/managedenvironments?pivots=deployment-language-arm-template

**Comment by SophCarp** [comment]
Closing based on documentation: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/managedenvironments?pivots=deployment-language-arm-template
