### ISSUE TITLE
Feature Request: Managed certificates

### ISSUE THREAD

**Issue by bppn** [microsoft/azure-container-apps#509]
A managed certificate for a custom domain / domain suffix would be a great feature.

Like the feature in Azure App Service.

This way a production api would be much more reliable since the certificates would not expire.

**Comment by SophCarp** [comment]
Thanks for the request! The team is committed to this feature in the future. No ETA at this time

**Comment by bppn** [comment]
Thanks for the reply!

**Comment by KarenTazayan** [comment]
+1 upvote, it will be great!

**Comment by simonjj** [comment]
This functionality is now supported 🎉
