### ISSUE TITLE
Is it possible to use private link with Azure Container Apps

### ISSUE THREAD

**Issue by arisewanggithub** [microsoft/azure-container-apps#512]
Our organization has a new security requirement to block all public ports on services. So, in order to use Azure Container Apps, we must use internal ingress instead. And the only way allowed as the public interface is Azure Frontdoor. In order to expose our service to the internet, we can only connect Azure frontdoor to the internal ingress in some way. But I didn't find a way to connect Azure Frontdoor to Azure Container Apps using private link. Is there any workaround available to connect Azure Frontdoor to Azure Container Apps internal ingress?

**Comment by reidav** [comment]
I've never tested it yet, but it seems like someone already did it https://github.com/sebafo/frontdoor-container-apps

**Comment by arisewanggithub** [comment]
Thanks @reidav. I followed the link and it works!
