### ISSUE TITLE
Env failure due to lack of support for NAT Gateway

### ISSUE THREAD

**Issue by mnadeem** [microsoft/azure-container-apps#522]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Container Apps Creation with Existing Vnet fails without reason.

### Steps to reproduce
1. Create a Vnet 
3. Create Subnet with NSG defined as in [here](https://learn.microsoft.com/en-us/azure/container-apps/firewall-integration
4. Create Container apps env, it fails without reason.

**Expected behavior** [Should Create Container Apps env without issue]

**Actual behavior** [Container Apps env not getting created.]

**Screenshots**         
Vnet with subnets
<img width="687" alt="image" src="https://user-images.githubusercontent.com/476145/206920342-7b18d6ca-9be6-4dd4-a82f-b2059fd0ba76.png">
subnet
<img width="281" alt="image" src="https://user-images.githubusercontent.com/476145/206920406-c935b2e4-194d-4c8d-94c8-cd88ece01ed4.png">

NSG rules
<img width="911" alt="image" src="https://user-images.githubusercontent.com/476145/206920464-cb47b828-e75a-4d89-b066-6121847edddc.png">

CAE creation failed.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/476145/206920612-b5f3c2a5-3614-403c-8c44-8fc9715c3a80.png">

command used to to create cae
```
az containerapp env create --name prefix-dev-cae --resource-group prefix-dev-rg --logs-workspace-id workspace-id --logs-workspace-key key --location centralus --logs-destination log-analytics --infrastructure-subnet-resource-id /subscriptions/<sid>/resourceGroups/prefix-dev-rg/providers/Microsoft.Network/virtualNetworks/prefix-dev-vn/subnets/prefix-dev-con-sn --tags app.environment=dev
```

### Additional context
Same behavior both in portal and cli

**Comment by mnadeem** [comment]
Today I got the following error

deploymentErrors": "ErrorCode: ManagedEnvironmentApiServerConnectionBlocked, Message: Fail to create managed environment because connection to the managed cluster API server was blocked, it could be caused by UDR, refer to https://go.microsoft.com/fwlink/?linkid=2198255 for more detail.",

**Comment by mnadeem** [comment]
Same issue even without a NSG attached to a subnet

**Comment by chinadragon0515** [comment]
@mndeem Seems you have configured virtual network NAT gateway for the subnet which is not supported yet. Can you remove the NAT from subnet and add NSG to try again.

BTW, we are working on to support NAT gateway, we will have private preview soon.

**Comment by mnadeem** [comment]
Thanks @chinadragon0515  couple of questions

1) With out NAT, will the subnet would be able to talk to outside world ?
2) Does AKS also does not support NAT gateway as of now?
3) Any time line on when NAT gateway would be supported (at least in preview) for ACA ?

**Comment by chinadragon0515** [comment]
@mnadeem,
1.  Yes
2. AKS supports NAT gateway. ACA does not support yet due to potential security risk.
3. We are actively working on this issue but no solid target date to share now.

**Comment by mnadeem** [comment]
Thanks a bundle @chinadragon0515

**Comment by mnadeem** [comment]
Hi @chinadragon0515 

After adding [file storage](https://techcommunity.microsoft.com/t5/fasttrack-for-azure/azure-container-apps-working-with-storage/ba-p/3561853), the revision is in provision state for ever, with out file storage it works fine

<img width="904" alt="image" src="https://user-images.githubusercontent.com/476145/207945571-1b512615-0cf3-4e48-b1df-aeaf36dbae42.png">

I have got storage with two subnets
<img width="953" alt="image" src="https://user-images.githubusercontent.com/476145/207945879-21fa82ff-3d37-496b-b658-23285f503267.png">

In storage subnet I have configured the storage account and in container subnet I have configured the aca

Storage subnet nsg

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/476145/207946175-457e6c43-24f4-404a-945c-1be70cf85b84.png">

Container subnet nsg
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/476145/207946334-70a6efdd-7049-4656-b0ba-94d2499567dc.png">

Am I missing anything? Do I have to Add NSG rule to allow container subnet to talk to storage subnet ?

**Comment by chinadragon0515** [comment]
Normal vnet request is allowed by default, can you send your sub/rg name/env name/app name/ failed time  to acasupport@microsoft.com, so we can check more?

**Comment by mnadeem** [comment]
Sent email with detail

**Comment by strofimo** [comment]
Hi @chinadragon0515,

We are expririence the same issue with container app env vnet integration when subnet configured with NAT gateway.
We have stantard tier Redis cache and using Redis firewall rules to grant the access for resources from subnets to Redis based on NAT gateway IP. As it's non-premium tier we can't use vnet integration for Redis. Wondering what other options do we have to grant access to Redis for container apps? 

Thanks a lot in advance!

**Comment by mnadeem** [comment]
@chinadragon0515  

As communicate over the email there is one more issue.

Have storage account in one subnet, and ACA in another subnet, the movement you mount azure files to container app, container app seizes to provision. 

Not able to mount storage on conatiner app, seems to be blocker and very critical issue

**Comment by chinadragon0515** [comment]
@strofimo  if you configure NAT on subnet, the env could not be created successfully now. If you met issue without NAT, can you send your sub/rg name/env name/app name/ failed time to [acasupport@microsoft.com](mailto:acasupport@microsoft.com), so we can check more?

**Comment by chinadragon0515** [comment]
@mnadeem we have received the detail and investigated the issue,

The mount error(13): permission denied is generally caused by cluster can not connect to azure file share.
Can you confirm following points:
1.	Storage access key is right
2.	It seems you are using nsg. Make sure the azure file share address and port 445 is not blocked.
3.	Make sure the azure file share is accessible from the cluster subnet.

**Comment by strofimo** [comment]
> @strofimo if you configure NAT on subnet, the env could not be created successfully now. If you met issue without NAT, can you send your sub/rg name/env name/app name/ failed time to [acasupport@microsoft.com](mailto:acasupport@microsoft.com), so we can check more?

hi @chinadragon0515 , sorry for the delay. Yes we tried with NAT on subnet. We did it because our apps in ACA needs to access on-premise resources so it much easy to configure NAT and whitelist NAT IPs upfront. As it's not possible atm do we have any other way to achive it? Whitelist ACA outbound ip is not very convenient. 

Thanks a lot in advance!

**Comment by decewei** [comment]
@chinadragon0515 is there an issue or ticket we can track the progress on NAT gateway support on ACA? Thanks.

**Comment by lukecalderon** [comment]
For anyone banging their head against a wall like I've been for the last week, I think I've found a fix...

**Investigation**
I'm using the AzAPI provider with Terraform, and was using the following TF:
```
resource "azapi_resource" "ca_env" {
  type      = "Microsoft.App/managedEnvironments@2022-10-01"
  name      = "containerappenvname"
  parent_id = "/subscriptions/xyz/resourceGroups/rg-name"
  location  = "northeurope"

  body = jsonencode({
    properties = {
      appLogsConfiguration = {
        destination = "log-analytics"
        logAnalyticsConfiguration = {
          customerId = "law_workspace_id"
          sharedKey  = "law_primary_shared_key"
        }
      }
      vnetConfiguration = {
        internal               = true
        infrastructureSubnetId = "subnetResourceId"
        dockerBridgeCidr       = "172.16.0.1/16"
        platformReservedCidr   = "172.17.0.0/16"
        platformReservedDnsIP  = "172.17.0.2"
      }
    }
  })

  depends_on = [azurerm_virtual_network.main]

  response_export_values  = ["properties.defaultDomain", "properties.staticIp"]
  ignore_missing_property = false
}
```

Which would produce the exact same issue as logged by @mnadeem .

I also tested with a NAT Gateway on the subnet (not realising this was not supported), which led to this error:
` Message: Fail to create managed environment because outbound connectivity was blocked `

I decided to deploy a temporary Container App Env via the portal, and compare the JSON from the produced resources, which highlighted this was **not** automatically populated:
```
vnetConfiguration = {
  ...
  outboundSettings = {
    outBoundType = "LoadBalancer"
  }
}
```

The MS docs don't seem to indicate this is a required attribute, but valid values are documented [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-10-01/managedenvironments?pivots=deployment-language-arm-template#managedenvironmentoutboundsettings-1).

I've only just had the requirement to start using this, so I can't be sure, but I'd assume at some point this was auto-populuated to be ` outBoundType = "loadBalancer" ` and now no longer is, which is why we're being caught out by it.

**The Fix**
Using the following TF, I've just deployed a Container App Environment successfully:
```
resource "azapi_resource" "ca_env" {
  type      = "Microsoft.App/managedEnvironments@2022-10-01"
  name      = "containerappenvname"
  parent_id = "/subscriptions/xyz/resourceGroups/rg-name"
  location  = "northeurope"

  body = jsonencode({
    properties = {
      appLogsConfiguration = {
        destination = "log-analytics"
        logAnalyticsConfiguration = {
          customerId = "law_workspace_id"
          sharedKey  = "law_primary_shared_key"
        }
      }
      vnetConfiguration = {
        internal               = true
        infrastructureSubnetId = "subnetResourceId"
        dockerBridgeCidr       = "172.16.0.1/16"
        platformReservedCidr   = "172.17.0.0/16"
        platformReservedDnsIP  = "172.17.0.2"
        outboundSettings = {
          outBoundType = "LoadBalancer"
        }
      }
    }
  })

  depends_on = [azurerm_virtual_network.main]

  response_export_values  = ["properties.defaultDomain", "properties.staticIp"]
  ignore_missing_property = false
}
```

The interesting thing that also now appears, is on the overview page of the ACA Environment there is now a property in the **Essentials** part of the resource overview, showing the load balancer static IP.

@chinadragon0515 FYI

**Comment by cachai2** [comment]
FYI - NAT Gateway support is currently in public preview for the Consumption + Dedicated plan structure. [Documentation](https://learn.microsoft.com/en-us/azure/container-apps/networking#nat-gateway-integration---preview)

**Comment by l3ender** [comment]
We are facing this same issue when our vnet's subnet is configured with a route table with a user-defined route to a firewall. We are not using NAT gateway or NSG on the subnet. Is there a resolution for this scenario?

**Comment by simonjj** [comment]
Closing this because NAT gateway is now supported. @l3ender we're tracking your issue via #881.
