### ISSUE TITLE
IP Restrictions seems to block Dapr Service Invokes

### ISSUE THREAD

**Issue by christle** [microsoft/azure-container-apps#527]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I was trying out the IP restrictions and made a strange observation. We have multiple container apps and restrict the ingress communication to the API Management. But for one app, we use a dapr service to service invoke and get the 403 RBAC. If I remove the IP Restrictions, everything works fine again.

### Steps to reproduce
1. Create a Service Invoke between 2 Container Apps with Dapr
2. Add a allow IP Restriction for a single IP (like an API Management ) to both services

**Expected behavior** [What you expected to happen.]
The Envoy blocks all external requests to the container apps except the allow rule.

**Actual behavior** [What actually happened.]
The internal communication between services and Dapr works even with an external IP restriction.

**Comment by christle** [comment]
hi, any updates on this?

**Comment by SophCarp** [comment]
Hi @christle thanks for your patience. We are addressing the bug and it will be fixed by end of February.

**Comment by ahmelsayed** [comment]
This should be fixed now.
