### ISSUE TITLE
Feature Request: Support a secret referenced from KeyVault

### ISSUE THREAD

**Issue by kamilzzz** [microsoft/azure-container-apps#528]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Service Connector creates a secret with KeyVault reference (`@Microsoft.KeyVault(SecretUri=https://{vault-name}.vault.azure.net/secrets/azure-storageblob-connectionstring-75f0d/3d25209ed8d34ecfb51b6df806db3ab3`) which is not supported in Container Apps.

### Steps to reproduce
1. Configure service connector for Key Vault
2. Configure service connector for Storage Account blobs, choose connection string as connection method and select "Store secret in KeyVault"

**Expected behavior**
Secret to be stored in KeyVault and correctly resolved using Key Vault reference.

**Actual behavior** 
Secret is not resolved.

**Screenshots**         
![image](https://user-images.githubusercontent.com/32141632/207729633-c6ee87f8-a26f-47a3-a8ae-42539fde4dc3.png)
![image](https://user-images.githubusercontent.com/32141632/207729718-964ef6b9-226f-416c-9372-399025c8b6ea.png)

**Comment by SophCarp** [comment]
Bug has been logged

**Comment by howang-ms** [comment]
@kamilzzz , the secret referenced from the key vault is currently not supported in Container Apps. We will block this scenario in the Portal for now. Apologize for the inconvenience.

**Comment by simonjj** [comment]
We will be adding this feature over the next several months. A a workaround I suggest you resolve the secret inside your app, please find instructions for:
Java: https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-java?tabs=azure-cli
.NET: https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-net?tabs=azure-cli
Python: https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python?tabs=azure-cli
Node: https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-node

**Comment by simonjj** [comment]
Another workaround might be #7 which is also what you can track on [Container Apps Public Roadmap](https://github.com/orgs/microsoft/projects/540/views/1)

**Comment by torosent** [comment]
The feature is available
