### ISSUE TITLE
I have Problems using the commnad "New-AzContainerApp", with param "IdentityUserAssignedIdentity"

### ISSUE THREAD

**Issue by erniker** [microsoft/azure-container-apps#532]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am following this tutorial: https://learn.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=azure-powershell.
I am following all the step but I am stuk in the step "Deploy the service application (HTTP web server)"

### Steps to reproduce
1. I have executed all the necesary command:
```
$PrincipalId = (Get-AzUserAssignedIdentity -ResourceGroupName $ResourceGroupName -Name 'nodeAppIdentity').PrincipalId
$IdentityId = (Get-AzUserAssignedIdentity -ResourceGroupName $ResourceGroupName -Name 'nodeAppIdentity').Id
$ClientId = (Get-AzUserAssignedIdentity -ResourceGroupName $ResourceGroupName -Name 'nodeAppIdentity').ClientId

$EnvId = (Get-AzContainerAppManagedEnv -ResourceGroupName $ResourceGroupName -EnvName $ContainerAppsEnvironment).Id
$EnvVars = New-AzContainerAppEnvironmentVarObject -Name APP_PORT -Value 3000

$TemplateArgs = @{
  Name = 'nodeapp'
  Image = 'dapriosamples/hello-k8s-node:latest'
  Env = $EnvVars
}
$ServiceTemplateObj = New-AzContainerAppTemplateObject @TemplateArgs

$ServiceArgs = @{
    Name = 'nodeapp'
    ResourceGroupName = $ResourceGroupName
    Location = $Location
    ManagedEnvironmentId = $EnvId
    TemplateContainer = $ServiceTemplateObj
    IngressTargetPort = 3000
    ScaleMinReplica = 1
    ScaleMaxReplica = 1
    DaprEnabled = $true
    DaprAppId = 'nodeapp'
    DaprAppPort = 3000
    IdentityType = 'UserAssigned'
    IdentityUserAssignedIdentity = $IdentityId
}
New-AzContainerApp @ServiceArgs
```

**Expected behavior** [What you expected to happen.]

I expect the service application it deployed

**Actual behavior** [What actually happened.]
I receive this message:
```
New-AzContainerApp: Cannot process argument transformation on parameter 'IdentityUserAssignedIdentity'. Cannot convert the "/subscriptions/a476cea9-f6bb-4913-899e-09071xxxxxxx/resourcegroups/my-container-apps/providers/Microsoft.ManagedIdentity/userAssignedIdentities/nodeAppIdentity" value of type "System.String" to type "System.Collections.Hashtable".
```

**Screenshots**         

### Additional context
This issue occur in the CLI

Thank you!

**Comment by SophCarp** [comment]
@craigshoemaker would you have time to check this out?

**Comment by erniker** [comment]
> @craigshoemaker would you have time to check this out?

Hi SophCarp I guess I could check, yes when?  sorry for the  delay, but with the holidays I have not use my laptop

**Comment by SophCarp** [comment]
@erniker we're all a bit delayed for the holidays 😄 no need to apologize. I don't think you need to do anything unless we have any follow-up questions. @craigshoemaker or someone else on the ACA team can look into this after the holidays.

**Comment by simonkurtz-MSFT** [comment]
Hi @SophCarp & @craigshoemaker,
I am looking at the same tutorial as @erniker and am stuck on the same issue. Do you have any updates, please?

**Comment by anthonychu** [comment]
Looks like the doc has a typo and `IdentityUserAssignedIdentity` should be a hashtable with the identity id as the key and an empty object as the value. See: https://learn.microsoft.com/en-us/azure/container-apps/managed-identity-image-pull?tabs=azure-powershell&pivots=command-line#create-a-container-app-2

Try:

```powershell
$ServiceArgs = @{
    Name = 'nodeapp'
    ResourceGroupName = $ResourceGroupName
    Location = $Location
    ManagedEnvironmentId = $EnvId
    TemplateContainer = $ServiceTemplateObj
    IngressTargetPort = 3000
    ScaleMinReplica = 1
    ScaleMaxReplica = 1
    DaprEnabled = $true
    DaprAppId = 'nodeapp'
    DaprAppPort = 3000
    IdentityType = 'UserAssigned'
    IdentityUserAssignedIdentity = @{
        $IdentityId = @{}
    }
}
New-AzContainerApp @ServiceArgs
```

**Comment by SophCarp** [comment]
The docs should be fixed now!
