### ISSUE TITLE
Default HTTP scaling: not scaling in, only out

### ISSUE THREAD

**Issue by maltegoetz** [microsoft/azure-container-apps#536]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When setting up an ACA with for example 1 replica as the minimum and 10 as the maximum and **not** configuring any individual scaling rules, I am experiencing an issue with the scaling. When starting a small load test making HTTP requests it scales out to the 10 replica maximum, so far so good. But when the load test finishes, Azure either does not scale in the replicas or only by a small amount. For example 9 of 10 replicas are still running even **without any** requests coming in for hours. Only by manually setting the maximum replicas to 1 I can get rid of the replicas. The attached screenshot shows the replicas and the requests within a timespan of 12 hours.

### Steps to reproduce
1. Create new ACA with 1 replica minimum, 10 replicas maximum
2. Enable public ingress
3. Deploy an API gateway like YARP to the ACA
4. Start a load test on the gateway making HTTP requests

**Expected behavior**
Azure scales in the replicas to a single instance as the amount of requests is dropping as described in the docs & official blog posts:

> Container Apps implements the KEDA [ScaledObject](https://keda.sh/docs/concepts/scaling-deployments/#details) and HTTP scaler with the following default settings.
> - pollingInterval: 30 seconds
> - cooldownPeriod: 300 seconds

[Scaling Container Apps (azure.github.io)](https://azure.github.io/Cloud-Native/blog/11-scaling-container-apps/)

> By default, when you deploy a container app, it is set to scale from 0 to 10 replicas. The default scaling rule uses HTTP scaling and defaults to a [minimum of 10 concurrent requests](https://docs.microsoft.com/azure/container-apps/scale-app#http) per second. Once the threshold of 10 concurrent request per second is met, another replica will be deployed until it reaches the maximum number of replicas.

**Actual behavior**
Azure does not scale in the replicas at all or only by a small amount.

**Screenshots**         
![207660556-6ef2fe19-c6f0-41dd-9e7d-8c0a2cdd7202_2](https://user-images.githubusercontent.com/1928933/208687592-c3ec266c-a575-4306-97c2-72df0cf0ab2d.png)

### Additional context
none

**Comment by tomkerkhove** [comment]
Nit:
```diff
- scaling down, only up
+ scaling in, only out
```

**Comment by ahmelsayed** [comment]
I'm not very familiar with configuring YARP, but do you have anything there around connection lifetime?

I'm suspecting that HTTP2 connections are kept alive between the gateway and other apps. Scaling http apps takes into account active connections as well as requests. If I'm looking at the correct app, it seems that the last request was around ~8:10 UTC, but 70 HTTP2 streams were keps open to the gateway app until ~13:00 UTC. It seems that in your graph scaledown happened around 14:00 or 15:00 though, which it even few hours after the app I'm looking at the logs for, so I'm not 100 sure I'm looking at the right application.

**Comment by maltegoetz** [comment]
@ahmelsayed We did not explicitly configure a connection lifetime. Yarp has the option to configure an activity timeout, which is basically a connection lifetime as HTTP/2 protocol pings do not reset the timeout. The default for this according to the [Yarp documentation](https://microsoft.github.io/reverse-proxy/api/Yarp.ReverseProxy.Forwarder.ForwarderRequestConfig.html#Yarp_ReverseProxy_Forwarder_ForwarderRequestConfig_ActivityTimeout) is 100 seconds, so this should be fine, except for the scenario that this is a bug with Yarp.

You are indeed right that there is a gap between the scale-in at about 16:50 (4:50PM) UTC according to the metrics (which only took place because I manually changed the replica count to 1) and the time that the HTTP/2 connections were closed at around 13:00 (1:00PM) UTC. This particular incident we are talking about is from the 14th December.

Is there a way to provide you with details like the subscription id or our Azure support ticket number? So we can make sure that you are looking at the correct app.
Also you might want to update the documentation, reflecting that not only the requests are considered for default http scaling but also the active connections.

**Comment by maltegoetz** [comment]
@SophCarp Sure thing. I have just sent you an email with the details.

**Comment by aconsolati-cvet** [comment]
Our team is experiencing a similar issue.  Please refer to metrics below, comparing **requests** vs **replica count** over the same time period:
![image](https://github.com/microsoft/azure-container-apps/assets/124010286/f4518dde-bcee-4fc1-a8dd-616d6a5c7005)

There is one scaling rule defined: 
Scale rule setting
`Min / max replicas
2 - 10`

Scale rule details
`Rule name: http-scaling
Type: HTTP scaling
Concurrent requests: 45`

Observe that scaling works as expected in the first half of the period, but then gets 'stuck' at a minimum of 7 replicas when request volume is low.  It will still scale up, but does not scale down to the minimum of 2 replicas as per the defined rule.

Could you please let us know if this is still under investigation.  We are willing to provide additional details in order to resolve.

**Comment by aconsolati** [comment]
Updating this issue as we have observed correct scale-in over the last several weeks, and had our support ticket resolved via Microsoft.  Our sincere thanks to the ACA team for chasing this down.

![IMG_2199](https://github.com/microsoft/azure-container-apps/assets/5485161/c2fe69ba-4c74-491e-9c8d-ff0821d11222)

**Comment by akmani-w** [comment]
@here I kind of Face similar issue
