### ISSUE TITLE
Event Hub event-driven scale doesn’t work

### ISSUE THREAD

**Issue by mcollier** [microsoft/azure-container-apps#539]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
As of early December 2022, event-driven scale doesn’t work on Container Apps if the event producer is Azure Event Hubs.  This is due to incompatibility between the version of Dapr and KEDA used by Container Apps.

DAPR stores the (Event Hub) checkpoint at this path “{blobContainer}/dapr-{topic}-{consumerGroup}-{partitionId}”, while the KEDA “goSdk” checkpoint strategy checks “{blobContainer}/{partitionId}”.

KEDA 2.9 was released on December 9th and should resolve this issue when using the “dapr” checkpoint strategy.  The KEDA version used by Container Apps is currently unknown as Container Apps doesn’t yet disclose versions of Dapr or KEDA. (#538)

**Comment by SophCarp** [comment]
We've requested internal investigation. Thank you for sharing!

**Comment by tomkerkhove** [comment]
I can confirm the above is correct and we have introduced the `dapr` checkpointing strategy in KEDA 2.9 for this.

**Comment by ItalyPaleAle** [comment]
Please note that Dapr 1.10 is rolling out in Container Apps and we've upgraded the Event Hubs SDK to "track 2" in this release. Checkpointing has changed and is now using the default checkpoints used by the upstream SDK.

**Comment by mcollier** [comment]
What's the implication for KEDA on this change?  @ItalyPaleAle @tomkerkhove

**Comment by tomkerkhove** [comment]
Good question indeed. We offer different flavors but no idea what "track 2" of Event Hubs SDK means.

**Comment by ItalyPaleAle** [comment]
It means that Dapr will use whatever the upstream new Azure SDK uses: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azeventhubs the path for the checkpoint store has changed, and we now rely on the default used by the SDK

**Comment by tomkerkhove** [comment]
I met with @italypaleale and opened a discussion on the KEDA side to ensure we do support this.
In theory the `default` checkpoint strategy should work and most likely we (KEDA) will deprecate the `Dapr` checkpointing strategy.

**Comment by tomkerkhove** [comment]
Feel free to give Dapr 1.10 a try with the `default` checkpoint strategy, @mcollier

**Comment by ahmelsayed** [comment]
Both Dapr >= 1.10 and KEDA >= 2.9 should be available everywhere now.
