### ISSUE TITLE
Open a shell to running container

### ISSUE THREAD

**Issue by andlju** [microsoft/azure-container-apps#54]
I'm currently trying to figure out why one of my container apps refuses to work properly. For debugging reasons it would be great to be able to open up a shell to a running container. Any plans to support something like `kubectl exec`, or at least the ability to open a web shell?

**Comment by vikramjb** [comment]
@andlju For now try the logs, the logs should give you some idea as to why its not working.

**Comment by VeselovAndrey** [comment]
Looks like logs is the only options to debug currently. But IMHO having access to the specific pod is required. E.g. you can have access to dotnet CLI and use it to get more details about failing app (for .net apps of course but other langs also have CLIs)

**Comment by marcindulak** [comment]
A shell into a container may be insufficient if the available tools and permissions inside are restricted. k8s introduced https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container that help debugging such restricted containers.

**Comment by BigMorty** [comment]
Streaming Logs and Console Connect is coming soon!
