### ISSUE TITLE
Unusual scaling in Container Apps

### ISSUE THREAD

**Issue by vinothrao** [microsoft/azure-container-apps#544]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X ] bug report
  We see unusual scaling activity in Azure Container Apps. Even when there are no messages in the queue, it's scaling to 1 or 2 container apps. There are 2 places we see different metrics. In Log Stream, we are getting a message like "This revision is scaled to Zero", but Metrics still shows some containers are running. This behavior is confusing. When we aggregate Sum in metrics it shows some 20k replicas created in replica count. But the actual count of messages in the Queue itself is 760 and the scaling rule is set to scale 100 messages per replica. 

### Steps to reproduce
1. Create a queue triggered Container app
2.  Set the scaling to Queue trigger and queue length to 100 
3. Post some 1000 messages to the queue
4. Look for the metrics of Replica Count

**Expected behavior**

For 760 messages and QueueLength of 100, it should create max of 8 replicas but created almost 1200 replicas

**Screenshots**         
![image](https://user-images.githubusercontent.com/5294130/209275843-e42b5ee9-aac1-463e-b237-62e04babadb4.png)

### Additional context
In Portal when we look into the Sum aggregate of Replica Count. Please explain how exactly the scaling is happening in Container apps and replicas are created on what basis? Is there something wrong with the metrics?

**Comment by ahmelsayed** [comment]
I think you want to use Max, not Sum when aggregating the replica count metric. Metrics are emitted on a fixed interval regardless of changes in the metric value. A metric once a minute reporting 20 replicas of your app for an hour will show 20 replicas with Max, but 1,200 with sum.

**Comment by SophCarp** [comment]
Hi @vinothrao did Ahmed and Charles resolve your problem? If so I will close the issue.

**Comment by ahmelsayed** [comment]
Closing this issue. See this comment for details https://github.com/microsoft/azure-container-apps/issues/554#issuecomment-1442352986
