### ISSUE TITLE
Revision Creation fails when the value of "volumeName" variable has uppercase letters in it.

### ISSUE THREAD

**Issue by ractando** [microsoft/azure-container-apps#545]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I am carrying out CA deployment via a .bicep file. Everything in the bicep file is correct however the deployment is going on endlessly and subsequently fails. When I remove the Storage configuration section from the template, the deployment gets successful.  

After checks and debugging, I figured out that the problem was caused by the casing of the volume name. Apparently, the name has to be in lowercase otherwise the provisioning fails without any error being logged on screen or even the System logs, indicating that this is required. Once I changed the volume name to all lowercase, it started working and the app was deployed successfully with storage mounted. This issue was replicated while using ARM template also and is currently not mentioned in MS Container Apps documentation. 

**Expected behavior** [What you expected to happen.]
The deployment should happen successfully.

**Actual behavior** [What actually happened.]
The deployment is running and the Container App provisioning status is Unknown.
 
**Screenshots**         
![image](https://user-images.githubusercontent.com/17726651/210198973-e69cd4ba-f762-4e7e-af0f-77377618c38b.png)
![image](https://user-images.githubusercontent.com/17726651/210199001-e4923eb2-83f8-480b-88a0-e8b9f62406b3.png)

### Additional context
Ex. Did this issue occur in the CLI or the Portal? **CLI**

**Comment by simonjj** [comment]
@ractando, would you happen to know if this still happens? Please let us know.
