### ISSUE TITLE
Keda error with RabbitMQ limited to Container Apps Environment

### ISSUE THREAD

**Issue by rstropek** [microsoft/azure-container-apps#547]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I have a Container Apps Environment containing a RabbitMQ instance (scaled to exactly 1 replica, uses the official RabbitMQ container image `rabbitmq:3-management-alpine`), a producer app that sends requests to RabbitMQ, and a worker app that processes the requests. RabbitMQ has a TCP ingress **limited to Container Apps Environment** for port 5672. Producer, worker, and RabbitMQ work fine. Producer and consumer use the name of the RabbitMQ app (in my case `aca-rabbitmq-vgsf7wrtnouti`) to connect to RabbitMQ. Therefore, the connection string is `amqp://guest:guest@aca-rabbitmq-vgsf7wrtnouti:5672/`. Functionally, this works perfectly fine.

Now I want to setup Keda autoscaling for the worker app based on the RabbitMQ queue length. Here is the scale rule configuration:

![image](https://user-images.githubusercontent.com/2341573/210338430-2db95d22-74d4-4174-8ab5-71820365b6f4.png)

Although the connection string `amqp://guest:guest@aca-rabbitmq-vgsf7wrtnouti:5672/` works fine for the producer and worker apps, Keda keeps complaining that there is no such host (error message in `ContainerAppSystemLogs_CL` log table is *error establishing rabbitmq connection: dial tcp: lookup aca-rabbitmq-vgsf7wrtnouti on 10.1.0.2:53: no such host*). I already tried using `amqp://guest:guest@aca-rabbitmq-vgsf7wrtnouti.default:5672/` to rule out K8s namespace issues, same error. As a result, auto-scaling does not work.

### Steps to reproduce
1. Create a Container App running RabbitMQ with ingress that is **limited to Container Apps Environment** (details see above)
2. Create a Container App with a custom scaling rule on the RabbitMQ queue length (details see above)

**Expected behavior** [What you expected to happen.]

Keda should be able to use the same RabbitMQ connection string as the worker app.

**Actual behavior** [What actually happened.]

Keda cannot find the RabbitMQ server, although the Container App that should be scaled can.

**Screenshots**         

See above

**Comment by rstropek** [comment]
For the sake of completeness, I changed the TCP ingress configuration from *Limited to Container Apps Environment* to *Limited to VNet*. The error remains the same (*no such host* when using `amqp://guest:guest@aca-rabbitmq-vgsf7wrtnouti:5672/`).

**Comment by ahmelsayed** [comment]
This should be fixed now.
