### ISSUE TITLE
Websockets don't work when authentication is enabled

### ISSUE THREAD

**Issue by prutsert** [microsoft/azure-container-apps#549]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Websocket support breaks when authentication is enabled.
This may be a bug (as the documentation states that both Websockets and authentication are working features for Container apps). But it may also be a feature request, in which case this is a documentation issue.

### Steps to reproduce
1. Deploy a websocket enabled Container App. For this example, I use [jmalloc/echo-server](https://github.com/jmalloc/echo-server):
```
az extension add --name containerapp --upgrade
az group create --location westeurope -g websocket-test
az containerapp env create -n websocket-test-cae -g websocket-test -l westeurope
az containerapp create -n echoservice-ca -g websocket-test --environment websocket-test-cae -i jmalloc/echo-server --ingress external --target-port 8080 --transport http --cpu 0.25 --memory 0.5 --min-replicas 1 --max-replicas 1
```
2. Test the websocket connection by pointing the browser to the container app: https://echoservice-ca.**********.westeurope.azurecontainerapps.io/.ws. It will open a websocket connection, and send and receive a ws message every 1.5 seconds.
3. Add an authentication provider to the Container App, and enable it (I used Azure Portal so I don't have az-cli commands for this).
4. Notice that the /.ws page displays that it disconnects, and is not able to reconnect.
5. Disable authentication for the Container App
```
az containerapp auth update -n echoservice-ca -g websocket-test --enabled false
```
6. Notice that /.ws page is now able to create a websocket connecting, and continues sending and receiving messages.

**Expected behavior** [What you expected to happen.]
Websocket connections work, whether authentication is enabled or not.

**Actual behavior** [What actually happened.]
Websocket support breaks when authentication is enabled.

**Comment by SophCarp** [comment]
Hi @prutsert! Just to troubleshoot, did you follow the instructions listed in the docs here: https://learn.microsoft.com/en-us/azure/container-apps/ingress?tabs=bash ?

**Comment by prutsert** [comment]
Hi @SophCarp. There are no instructions in that document on how to add ingress configuration. I added the ingress in the `az containerapp create` command as documented here: https://learn.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-create
I did use the page you linked, to add IP restrictions to the app, but I tested without IP restrictions as well. The results are the same.

For completeness, I'll add the current configuration of the containerapp and the auth settings of the app (with some masking).
```
# show containerapp configuration
az containerapp show -n echoservice-ca -g websocket-test -ojson
```

```
{
  "id": "/subscriptions/********/resourceGroups/websocket-test/providers/Microsoft.App/containerapps/echoservice-ca",
  "identity": {
    "type": "None"
  },
  "location": "West Europe",
  "name": "echoservice-ca",
  "properties": {
    "configuration": {
      "activeRevisionsMode": "Single",
      "dapr": null,
      "ingress": {
        "allowInsecure": false,
        "customDomains": null,
        "exposedPort": 0,
        "external": true,
        "fqdn": "echoservice-ca.********.westeurope.azurecontainerapps.io",
        "ipSecurityRestrictions": [
          {
            "action": "Allow",
            "ipAddressRange": "********/32",
            "name": "Prutsert_at_Home"
          }
        ],
        "targetPort": 8080,
        "traffic": [
          {
            "latestRevision": true,
            "weight": 100
          }
        ],
        "transport": "Http"
      },
      "maxInactiveRevisions": null,
      "registries": null,
      "secrets": [
        {
          "name": "microsoft-provider-authentication-secret"
        }
      ]
    },
    "customDomainVerificationId": "********",
    "environmentId": "/subscriptions/********/resourceGroups/websocket-test/providers/Microsoft.App/managedEnvironments/websocket-test-cae",
    "eventStreamEndpoint": "https://westeurope.azurecontainerapps.dev/subscriptions/********/resourceGroups/websocket-test/containerApps/echoservice-ca/eventstream",
    "latestRevisionFqdn": "echoservice-ca--62jwd4r.********.westeurope.azurecontainerapps.io",
    "latestRevisionName": "echoservice-ca--62jwd4r",
    "managedEnvironmentId": "/subscriptions/********/resourceGroups/websocket-test/providers/Microsoft.App/managedEnvironments/websocket-test-cae",
    "outboundIpAddresses": [
      "********"
    ],
    "provisioningState": "Succeeded",
    "template": {
      "containers": [
        {
          "image": "jmalloc/echo-server",
          "name": "echoservice-ca",
          "resources": {
            "cpu": 0.25,
            "ephemeralStorage": "1Gi",
            "memory": "0.5Gi"
          }
        }
      ],
      "initContainers": null,
      "revisionSuffix": "",
      "scale": {
        "maxReplicas": 1,
        "minReplicas": 1,
        "rules": null
      },
      "volumes": null
    },
    "workloadProfileType": null
  },
  "resourceGroup": "websocket-test",
  "systemData": {
    "createdAt": "2023-01-04T15:44:39.9433813",
    "createdBy": "prutsert@example.com",
    "createdByType": "User",
    "lastModifiedAt": "2023-01-05T07:35:02.3262594",
    "lastModifiedBy": "prutsert@example.com",
    "lastModifiedByType": "User"
  },
  "tags": {
    "contact": "prutsert"
  },
  "type": "Microsoft.App/containerApps"
}
```

```
# show containerapp auth configuration
az containerapp auth show -n echoservice-ca -g websocket-test -ojson
```
```
{
  "globalValidation": {
    "redirectToProvider": "azureactivedirectory",
    "unauthenticatedClientAction": "RedirectToLoginPage"
  },
  "identityProviders": {
    "azureActiveDirectory": {
      "isAutoProvisioned": true,
      "registration": {
        "clientId": "********",
        "clientSecretSettingName": "microsoft-provider-authentication-secret",
        "openIdIssuer": "https://sts.windows.net/********/v2.0"
      },
      "validation": {
        "allowedAudiences": [
          "api://********"
        ]
      }
    }
  },
  "login": {
    "allowedExternalRedirectUrls": [],
    "preserveUrlFragmentsForLogins": false
  },
  "platform": {
    "enabled": true
  }
}
```

**Comment by SophCarp** [comment]
@prutsert Thanks for the info. We are investigating this bug.

**Comment by SophCarp** [comment]
A fix is being worked on.

**Comment by SophCarp** [comment]
Fix has been deployed! I'm going to close this issue, let us know if the issue persists 😊

**Comment by prutsert** [comment]
> Fix has been deployed! I'm going to close this issue, let us know if the issue persists 😊

@SophCarp, I don't see it working yet in West Europe. Is there a way to find out if I'm actually using the latest deployment of ContainerApps?

**Comment by SophCarp** [comment]
@prutsert Ope sorry, I misread the deployments. The fix is currently being deployed; it hasn't been updated everywhere. It will deploy in West Europe in the next couple days. 

To answer your question, there is no way currently for customers to check what deployment of ACA they are using. That isn't something we've made available. I did a quick check of the github issues, and I don't see any requests to make this available. If you'd like, you can make a feature request for it, and we can see if it's something many users want.

**Comment by SophCarp** [comment]
Thanks for your patience! I've checked the deployments this fix should be everywhere.

**Comment by prutsert** [comment]
It appears to work now, thanks!
