### ISSUE TITLE
Support for static url or IP address

### ISSUE THREAD

**Issue by byme8** [microsoft/azure-container-apps#55]
Are there plans to support the static URL or IP addresses for deployed services? 

It would be nice to have it, because DNS entries can be slow to update. What can lead to issues in production environments.

**Comment by ahmelsayed** [comment]
What do you mean by a static URL? the IP addresses for your fqdn are static/stable per fqdn.

**Comment by byme8** [comment]
Right now when you deploy a service you can access it via generated URL like  https://whoami.livelyforest-090127b6.canadacentral.azurecontainerapps.io/

**Comment by ahmelsayed** [comment]
Got it.

being able to map `whoami.my.com` => `whoami.livelyforest-090127b6.canadacentral.azurecontainerapps.io` is tracked under [custom domains feature](https://github.com/microsoft/azure-container-apps/issues/8) and it's definitely planned and coming soon. 


---

**p.s.:** The DNS entry registered for your cluster is actually for `*.livelyforest-090127b6.canadacentral.azurecontainerapps.io` any app you create on a given environment will get the same public IP as other apps on the same environment. You can try 

```
dig blahblah.livelyforest-090127b6.canadacentral.azurecontainerapps.io
```

_or any thing in place of blahblah_ 

It should always resolve to the same A record/IP. You can always assume that for an app `foo` on that environment, the default fqdn will always be `foo.livelyforest-090127b6.canadacentral.azurecontainerapps.io`.  Inside the cluster that could be computed using `foo.$CONTAINER_APP_ENV_DNS_SUFFIX` as `CONTAINER_APP_ENV_DNS_SUFFIX` is an env var available to all apps running in the cluster that resolves to the cluster's default DNS suffix, e.g: `livelyforest-090127b6.canadacentral.azurecontainerapps.io`
