### ISSUE TITLE
Container App Infrastructure Subnet length 

### ISSUE THREAD

**Issue by KamilLach** [microsoft/azure-container-apps#551]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
According to documentation  https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom-internal?tabs=bash&pivots=azure-cli network with CIDR /21 is required for use with container apps. However, container apps work fine with networks /23 

### Steps to reproduce
1. Create a Virtual Network with CIDR /28 
2. Try to create container environment, with the above network assigned (I am using pulumi) 

**Expected behavior** Error should be returned according to documentation

**Actual behavior** Documentation mentioning that /21 subnet is required, however from API error mentions subnet /23. Additionally, when creating a Container environment with Infra subnet /23 it works perfectly fine. 

**Screenshots**         
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/2822114/210985873-3549d090-2b3f-4f80-ac5a-f9b8d9d2888f.png">

**Comment by SophCarp** [comment]
Docs have been updated, thank you! The minimum subnet currently is /23 for CIDR.
