### ISSUE TITLE
Dapr's AAD credentials expired, and it is not retrieving a new access token

### ISSUE THREAD

**Issue by onionhammer** [microsoft/azure-container-apps#552]
Using a dapr binding component

```bicep
  // Dapr Component: Storage Queue - Send Invites
  resource queueSendInvites 'daprComponents' = {
    name: 'send-invites'
    properties: {
      componentType: 'bindings.azure.storagequeues'
      version: 'v1'
      metadata: [
        {
          name: 'queueName'
          value: internalStorage.outputs.queueSendInvites
        }
        {
          name: 'accountName'
          value: internalStorage.outputs.storageAccountName
        }
        {
          name: 'azureClientId'
          value: appIdentity.outputs.clientId
        }
      ]
      scopes: [
        myapp.name
      ]
    }
  }
```

This initially works, but after the app has been up for several hours/days I received this when attempting to invoke the (output) binding, once I restarted the revision it started working again.

![image](https://user-images.githubusercontent.com/969938/211093909-cdd1b8bb-5be7-4b66-92c8-5b99b8945af1.png)

**Comment by onionhammer** [comment]
Additionally:

It appears on the input binding side, my CPU usage jumps when the credentials expire. That CPU usage is likely from the dapr sidecare itself, not from my container.

![image](https://user-images.githubusercontent.com/969938/211094962-263176f5-ebd4-4787-9d99-44492761752f.png)

**Comment by SophCarp** [comment]
Thanks @onionhammer for sharing. @ItalyPaleAle commented in the dapr github (https://github.com/dapr/components-contrib/issues/2417) "we have a fix for the issue which will be released in Container Apps in the next few days."

**Comment by onionhammer** [comment]
@SophCarp has this started rolling out?

**Comment by SophCarp** [comment]
@onionhammer that's a good question! @ItalyPaleAle, could you confirm? I'm not sure where to check release updates for Dapr.

**Comment by ItalyPaleAle** [comment]
@sanchitmehta has more details on the releases
