### ISSUE TITLE
Feature Request: Support traffic splitting to multiple app versions 

### ISSUE THREAD

**Issue by seanli1988** [microsoft/azure-container-apps#555]
Support traffic splitting to multiple app versions by HTTP header to accelerate the release

Scenario:
Canary release for sub-system (a group of apps) or app level is becoming more and more frequent (every 2 weeks). To release in canary, our customer needs to host multiple versions of an app. 
For example, a group of apps has 2 versions: app-version 1 (production version) and app-version 2 (trial version for pilot cities). The traffic should be split by the following rules:
1.                   if incoming traffic with http header key and value (i.e. city==xyz, and starting from certain time = 2022-11-20T23:00:00.000), it will be split to app-version 2 (trial version)
2.                   else, it will be split to app-version 1 (production version).

**Comment by romanlum** [comment]
+1

**Comment by BigMorty** [comment]
HTTP header routing to revisions is also mentioned in https://github.com/microsoft/azure-container-apps/issues/99

**Comment by marchagele** [comment]
+1

**Comment by anthonychu** [comment]
This is something that we might be about to add in https://github.com/microsoft/azure-container-apps/issues/591 #99. Let's track it there.
