### ISSUE TITLE
traceparent not propagating between services when using http calls via Dapr

### ISSUE THREAD

**Issue by davidjones-pc** [microsoft/azure-container-apps#556]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
traceparent header is not propagating between services when using http calls via Dapr

### Steps to reproduce
1. Create two separate ASP.NET based services in container apps (service A and service B)
2. Enable Dapr on both services using HTTP
3. Expose an endpoint on service A that makes a HTTP call through to service B using Dapr (`http://127.0.0.1:3500` & include `dapr-app-id` header with the app id of service B)
4. Call the exposed endpoint on service A. 

**Expected behavior** [What you expected to happen.]
The traceparent header received on service B should be the same value that was sent from service A. 

**Actual behavior** [What actually happened.]
The traceparent header received on service B has been overwritten with an empty value (`00-00000000000000000000000000000000-0000000000000000-00`) 

**Screenshots**         
N/A

### Additional context
We are publishing all tracing to application insights directly from the services themselves. We have not set the connection string or instrumentation key on the container app environment. 

The [Dapr documentation](https://docs.dapr.io/developing-applications/building-blocks/observability/tracing-overview/#generating-your-own-trace-context-headers-from-non-daprized-applications) suggests that it should propagate the trace context headers if they are present.

**Comment by jon-mca** [comment]
Getting the same issue trying to chain up requests among services (container apps) using DAPR where the trace parent header isn't being persisted across services and resets it to an empty value. Makes reviewing these requests in App Insights difficult and time consuming.

**Comment by greenie-msft** [comment]
@davidjones-pc Are you able to provide screenshots of where you are seeing the traceparent id being overwritten?

I quickly tested this through the hello world sample and can see the ids propagating correctly.

**Comment by davidjones-pc** [comment]
Hi @greenie-msft.

Here are some screenshots from our app-insights. 

This first screenshot shows the request going to our first API and the call it is making out to the second API. 

![Screenshot 2023-01-19 at 10 35 48](https://user-images.githubusercontent.com/100356617/213425636-2d546c82-a30b-43d1-858e-24dc8b51cee9.jpeg)

This screenshot shows the request being received in the second API and the parent ID is empty. 

![Screenshot 2023-01-19 at 10 47 44](https://user-images.githubusercontent.com/100356617/213425848-7a3e2ff7-a38e-49f5-afbc-a9f894db5242.jpeg)

The call is made using a HttpClient that is generated from `DaprClient.CreateInvokeHttpClient`.

Please can you point me in the direction of the hello world sample that you have tried and I will test it in our container app environment.

**Comment by greenie-msft** [comment]
@davidjones-pc thank you for the additional details. 

I deployed this sample: https://learn.microsoft.com/en-us/azure/container-apps/microservices-dapr-azure-resource-manager?tabs=bash&pivots=container-apps-bicep

The Python service issues a service invoke request to the Node service. 

Screenshot from the caller: 
<img width="1396" alt="Screenshot 2023-01-18 at 10 35 13 AM" src="https://user-images.githubusercontent.com/56556602/213505119-d7f2c09f-9f7c-406d-a6ad-69b343299af3.png">

Screenshot from the callee:
<img width="1398" alt="Screenshot 2023-01-18 at 10 35 48 AM" src="https://user-images.githubusercontent.com/56556602/213505243-2b9fb3a0-f4b5-48c2-9d6f-0fa09946cb93.png">

This is your scenario, correct? I'm still looking into why this might be different. One key difference is that this sample is not using the .NET SDK and yours is, right?.

**Comment by davidjones-pc** [comment]
@greenie-msft

Yes, we are using ASP.NET and the DaprClient SDK. 

I will try and deploy the sample to our environment and let you know how I get on with that. It will be interesting to see if it is our environment or .NET.

**Comment by KaiFelixBennett** [comment]
I have the same or very similiar issue. I'm using the daprClient SDK calling DaprClient.InvokeBindingAsync(). In my local docker-compose environment traceId and traceParent are created correct. As soon I deployed it to container apps, the traceId and traceParent are empty. I don't have service to service calls, but calling a Azure Service Bus. I add an screenshot from an example message send from Azure Container Apps with dapr to the Azure Service Bus:

![image](https://user-images.githubusercontent.com/83428264/215061066-39d86de2-72ef-4198-9e80-dff8429587d6.png)

**Comment by berndverst** [comment]
Please note that Dapr trace header propagation (and generation) is currently only possible if a trace exporter is configured. In Azure Container Apps this means you must have Application Insights enabled.

I suspect everyone seeing zero'd trace ID / traceparent values does not have App Insights configured at that time.

Since this is obviously causing a lot of confusion we will try to enable trace header propagation even without a trace exporter configured. This requires additions in open source Dapr. The following PR will make this possible, which then would become the default internal configuration for Container Apps for those users who do not have App Insights configured.

Anyone who immediately needs trace parent / trace ID to be propagated or generated should enable Application Insights.

We will update this issue once this *new functionality* has been rolled out. But please note that what is being observed is expected behavior at this time.

Bernd (Dapr maintainer)

**Comment by berndverst** [comment]
As an aside, the local Dapr install comes with a Zipkin container and a Dapr configuration that configures the telemetry exporter to use said Zipkin. This is why trace headers are passed through / generated when using Dapr locally in standalone mode.

**Comment by davidjones-pc** [comment]
Hi @berndverst. Thanks for the update on this. 

Can I just confirm, when you say we need to have application insights enabled in container apps, do you mean enabled on the container app environment? I can only see options in bicep to set the `daprAIConnectionString` and `daprAIInstrumentationKey` attributes on the environment which I am assuming are used to enable app insights. I cannot see anything relating to app insights on the container apps themselves. If that is not what you mean, please could you point me in the direction of some documentation on how to enable it.

**Comment by berndverst** [comment]
> daprAIInstrumentationKey

The `daprAIInstrumentationKey` is what currently governs the behavior. If that is set then trace headers will be sent.

**Comment by berndverst** [comment]
When Container Apps rolls out Dapr 1.10 the OSS change I made to allow trace header propagation without trace exporting will be included (only in container apps - in OSS you'd have to wait for Dapr 1.11 or run a nightly build).
So when you see container apps run 1.10 you don't necessarily need to use App Insights anymore just to use this feature.

**Comment by davidjones-pc** [comment]
This doesn't appear to have fixed the problem for me. However, I am not 100% sure the `daprAIInstrumentationKey` has been set after deploying my bicep template. Is there a way of seeing if it has been set correctly in either the Azure portal or the CLI? I have tried exporting the template for the container app environment in the portal and it doesn't seem to include the `daprAIInstrumentationKey` in it. I have also tried showing the environment in the CLI and the attribute is not showing in there either.

**Comment by SophCarp** [comment]
Hey @davidjones-pc If you go to your environment's overiew in the portal, there's an option to "View JSON" in the top right corner. If you click that, you should see if the instrumentation key is set :

},
    "properties": {
        "provisioningState": "Succeeded",
        "daprAIInstrumentationKey": null,
        "daprAIConnectionString": null
        
  Does that help?

**Comment by davidjones-pc** [comment]
> 

Hi @SophCarp. Sorry, I missed you message. Yes, that was useful in checking if the value had been set. 

With regards to the original problem, it appears to have been resolved now and we are seeing our log messages linking together in App Insights. The ParentId is being correctly passed through.
