### ISSUE TITLE
Can't retrieve the Access Token

### ISSUE THREAD

**Issue by subesokun** [microsoft/azure-container-apps#558]
### This issue is a: (mark with an x)
- [x] documentation issue or request

### Issue description

Hi, I want to use the built-in Authentication feature of the Container Apps and the linked documentation (behind "Learn more") implies that I should be able to access the necessary Access Token to query the Graph API on the user's behalf when using this feature. However, what is currently implemented seems to be vastly different to what is documented here https://learn.microsoft.com/en-us/azure/app-service/overview-authentication-authorization

![image](https://user-images.githubusercontent.com/6920421/211984918-54bfe42d-5f17-4ccb-bfed-e0517efca5a8.png)

The server receives via the `X-MS-CLIENT-PRINCIPAL` header only a kind of JWT token which looks like an Identity Token rather than an Access Token as it's missing necessary properties like the scope (e.g. `User.Read`) and the Graph API rejects it with an invalid token error. Not sure if I'm doing something completely wrong or if it's simply not possible to get the Access Token with the current used authentication middleware.

**Expected behavior** [What you expected to happen.]

Referenced documentation is up to date with what is currently possible with the Container Apps.

**Actual behavior** [What actually happened.]

The portal links only to the App Service documentation which seems the be different to what has been implemented for the Container Apps.

**Comment by SophCarp** [comment]
Hi @subesokun, thanks for asking! Could you take a screenshot of the page with the link to the app service documentation? 

Here is the ACA docs for enabling authentication: https://learn.microsoft.com/en-us/azure/container-apps/authentication-azure-active-directory (This is to one based on azure active directory, but there are also options for authentication via Facebook, GitHub, Google, Twitter, or custom OpenID connect). Does that help your issue?

**Comment by gt-downunder** [comment]
Without attempting to hijack this question, related to it is how to handle authentication locally if the Azure Container App ingress handles authentication once deployed? 

@subesokun, the documentation you linked mentions that authentication middleware is not necessary when using the container apps authentication setting. However, my app needs a token to authenticate against the Graph API which when deployed is easy to obtain, but the "http-auth" container is not available to me during local development.  What is the recommended approach for local development?

**Comment by subesokun** [comment]
@gt-downunder A very good question and I've wondered too how local development should work. But probably better create a dedicated ticket for it 👍

**Comment by subesokun** [comment]
@SophCarp My problem was solved via the Azure support. Basically you need to use the initial identity token for requesting the actual authentication token as a second step. This won't be performed by the auth middleware and has to be done programmatically.

**Comment by SophCarp** [comment]
@subesokun I'm glad your problem was resolved! Let us know if there's anything else you need support with!

**Comment by SophCarp** [comment]
We've also updated the portal links to all go to container apps documentation, rather than app service documentation.

**Comment by tnabil** [comment]
@subesokun @SophCarp Any chance you can share the solution here or if the documentation was updated to reflect that, provide a link? Many thanks!
