### ISSUE TITLE
what is minimum CIDR range of internal ACA environment 

### ISSUE THREAD

**Issue by baoj-dfo** [microsoft/azure-container-apps#564]
based on https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash&pivots=azure-portal, external ACA environment need CIDR range of minimum /21 
what about CIDR range of internal ACA environment ?

**Comment by SophCarp** [comment]
Network address prefixes requires a CIDR range of /23 or larger. There is a note in the docs now (It may have been added since you posted the question). Thanks for asking, does this answer your question?

**Comment by baoj-dfo** [comment]
@SophCarp  Thanks for the document update. Issue resloved.
