### ISSUE TITLE
'Edit a container' screen does not display registries in list when user selects user assigned identity

### ISSUE THREAD

**Issue by onionhammer** [microsoft/azure-container-apps#566]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Relates to #183, the 'registries' dropdown is empty in the UI even when just versioning an existing container if using a user assigned managed identity

### Steps to reproduce
1. Deploy an image using a user assigned managed identity (bicep or az cli)
2. Click 'Create new revision'
3. Click container image, opening the 'edit a container' image
4. first issue: user assigned managed identity already in-use is not preselected
5. second issue: Selecting the user assigned managed identity does not populate the list of registries.

**Screenshots**         
![image](https://user-images.githubusercontent.com/969938/212997677-fce9b6c1-e72e-47b9-9a42-a18eea4fee1f.png)

**Comment by anthonychu** [comment]
Filed internal bug 16853368. Thanks.

**Comment by andimarc** [comment]
@onionhammer

With regard to user assigned managed identity not being preselected, this looks like a known issue that can happen in either of the follow scenarios:
- The configured ACR registry is on a different subscription than the container app.
- The user doesn't have read permissions on the configured ACR registry.

The issue with the registry list not populating can happen if the subscription the container app is on doesn't have any ACR registries or the user doesn't have read permissions on any ACR registries on that subscription.

We have internal bug 12771808 tracking both issues.

Does your case fall into the scenarios above?

**Comment by onionhammer** [comment]
> @onionhammer
> 
> With regard to user assigned managed identity not being preselected, this looks like a known issue that can happen in either of the follow scenarios:
> 
> * The configured ACR registry is on a different subscription than the container app.
> * The user doesn't have read permissions on the configured ACR registry.
> 
> The issue with the registry list not populating can happen if the subscription the container app is on doesn't have any ACR registries or the user doesn't have read permissions on any ACR registries on that subscription.
> 
> We have internal bug 12771808 tracking both issues.
> 
> Does your case fall into the scenarios above?

Hi @andimarc, yes you are right - the ACR registry is on a production subscription, and the QA app is on "dev" subscription. I do have access to both.

**Comment by akmani-w** [comment]
@anthonychu Any progress on this issue ?

**Comment by LianaAdaza** [comment]
Both internal bugs 16853368 and 12771808 have been resolved. Please feel free to reach out if you continue to encounter difficulties.
