### ISSUE TITLE
Environment becomes inactive after 'a long period of inactivity'

### ISSUE THREAD

**Issue by amolenk** [microsoft/azure-container-apps#571]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

Today, I was running a demo application on an ACA environment consisting of a couple of Apps. Initially, the solution worked fine. 
Had a Teams call, came back again about 90 minutes later to find that all my Apps were unresponsive. I couldn't get the Overview page of any App to load in the portal, and the System logs of the environment showed PodUnhealthy / readiness probe failed warnings.

I redeployed my Bicep file to get back to a working solution and it returned the following error message:
> The environment is stopped due to a long period of inactivity. It is now restarting and it will take around 5 minutes. Please retry in few minutes.

I was really surprised and confused by this message because all my Apps have a minimum scale setting of 1.

- Why did the environment stop?
- How long is 'a long period of inactivity'?
- Does this mean that I cannot use ACA in scenario's with low traffic?
- Is there any other way to 'reactivate' the environment without doing a new deployment.

### Steps to reproduce
1. Deploy a solution to ACA
2. Don't send any request for 'a long period'

**Expected behavior** [What you expected to happen.]

I expect the environment to stay active always. 

**Actual behavior** [What actually happened.]

The environment becomes inactive and unresponsive.

**Comment by simonjj** [comment]
Closing this issue due to it being inactive. If it still exists please reopen a new issue and point to this to preserve history.
