### ISSUE TITLE
Feature Request: Support for Session Affinity 

### ISSUE THREAD

**Issue by maiaacademy** [microsoft/azure-container-apps#575]
**Is your feature request related to a problem? Please describe**.  
I have experienced a problem with a customer implementing Azure Container Apps, as a solution for migrating the entire environment of Web applications from Docker Containers to Azure.
 
However, one of the problems that I have encountered when working with multiple replicas and Auto scale in Container Apps is authentication failure since this application in question is an NGINX and PHP-FPM that uses an authentication Forms and every time a user connects and is with multiple replicas the process fails, only when it returns to a single replica does it work again.
 
**Describe the solution you'd like**.    
I believe what will actually solve this scenario will be the use of Session Affinity.

**Describe alternatives you've considered**.   
We are considering not migrating this environment to Azure using Container Apps due to this limitation

**Comment by anthonychu** [comment]
@maiaacademy We are working on adding support for session affinity to Container Apps. Initially, it’ll use an http cookie to route clients back to their previous replica and available only in single revision mode. Will this work for your scenario?

**Comment by maiaacademy** [comment]
It will help, because we depend on this feature to migrate to Azure Container Apps.
Would you have an estimated date to pass on to the customer?

**Comment by SophCarp** [comment]
This item is on our roadmap, you can track it at #590. I'm not sure what the estimated date is yet.

**Comment by SophCarp** [comment]
@maiaacademy Estimated time for public preview is by end of Q1 (End of march) :)

**Comment by anthonychu** [comment]
This is available for single revision mode. If you also need session affinity for multiple revision mode as well, please open a separate issue.
