### ISSUE TITLE
Azure provided "Application Url" not working for Azure Container Apps on Azure Arc

### ISSUE THREAD

**Issue by KarenTazayan** [microsoft/azure-container-apps#577]
Hi everyone,

I successfully deployed Azure Container Apps on Azure Arc by using [this tutorial](https://learn.microsoft.com/en-us/azure/container-apps/azure-arc-enable-cluster?tabs=bash) on my local workstation.

![2023-01-23_18-05-40](https://user-images.githubusercontent.com/39263060/214059705-f90e76f1-bf02-4519-801d-50c7c57d852d.jpg)

I also successfully created a sample application by using the following command:
```
az containerapp create `
    --resource-group $GROUP_NAME `
    --name ca-azure-arc-sample-2 `
    --environment $CONNECTED_ENVIRONMENT_ID `
    --environment-type connected `
    --image mcr.microsoft.com/dotnet/samples:aspnetapp `
    --target-port 80 `
    --ingress 'external'
```
Everything works,

![2023-01-23_18-06-34](https://user-images.githubusercontent.com/39263060/214060090-8b75fe36-3d79-43d0-b494-38c01954ee93.jpg)

but I'm unable to access application by using Azure provided "Application Url":

![2023-01-23_18-12-23](https://user-images.githubusercontent.com/39263060/214061410-9a9a02a7-5bf9-47a6-9c96-fafcbd797cb4.jpg)

Please see the error bellow:

![2023-01-23_18-18-58](https://user-images.githubusercontent.com/39263060/214062764-7078df45-ec0b-401d-a0dc-f4506ae4b89e.jpg)

I know that Azure Container Apps on Azure Arc is in an early preview stage. Can anyone help with this? What I'm doing wrong?

**Comment by KarenTazayan** [comment]
As I understand here, we need **something like a reverse proxy** for Azure Arc agents. That proxy listens to requests to an external IP/FQDN and forwards traffic to the Azure Arc on-prem infrastructure. Was this functionality implemented? Is there any documentation for this?

**Comment by apwestgarth** [comment]
@KarenTazayan have you deployed to AKS or AKS-HCI?  Azure Container Apps on Azure Arc enabled Kubernetes includes the configuration of the same Envoy reverse proxy.  If you run kubectl get services -n <custom location namespace> what is the output?

**Comment by KarenTazayan** [comment]
Hi @apwestgarth, thank you for the response. I deployed on VM with WSL 2. [Here I describe](https://github.com/KarenTazayan/Azure-Container-Apps-On-Azure-Arc) all detailed instructions what I did.

> If you run kubectl get services -n

```
kubectl get services -n appplat-ns
NAME                                     TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
app-webhooks-service                     ClusterIP      10.99.106.129    <none>        443/TCP                               5d
appenv-ext-k8se-activator                ClusterIP      10.98.186.182    <none>        4045/TCP,4050/TCP,4046/TCP,5050/TCP   5d
appenv-ext-k8se-billing                  ClusterIP      10.106.99.54     <none>        4055/TCP                              5d
appenv-ext-k8se-envoy                    LoadBalancer   10.104.54.8      localhost     80:30815/TCP,443:31685/TCP            5d
appenv-ext-k8se-envoy-controller         ClusterIP      10.97.237.114    <none>        9090/TCP                              5d
appenv-ext-k8se-envoy-dapr               ClusterIP      10.103.184.7     <none>        80/TCP                                5d
appenv-ext-k8se-envoy-internal           ClusterIP      10.111.35.211    <none>        80/TCP,443/TCP                        5d
appenv-ext-k8se-event-processor          ClusterIP      10.102.6.240     <none>        8080/TCP                              5d
appenv-ext-k8se-http-scaler              ClusterIP      10.97.143.166    <none>        4055/TCP,4050/TCP                     5d
appenv-ext-k8se-keda-cosmosdb-scaler     ClusterIP      10.99.180.60     <none>        4050/TCP                              5d
appenv-ext-k8se-keda-metrics-apiserver   ClusterIP      10.106.16.164    <none>        443/TCP,80/TCP                        5d
appenv-ext-k8se-mdm                      ClusterIP      10.108.179.146   <none>        8125/UDP                              5d
containerapp-controller-api              ClusterIP      10.109.84.46     <none>        8443/TCP                              5d
containerapp-webhooks-service            ClusterIP      10.105.129.51    <none>        443/TCP                               5d
dapr-api                                 ClusterIP      10.105.36.204    <none>        80/TCP                                5d
dapr-placement-server                    ClusterIP      None             <none>        50005/TCP,8201/TCP                    5d
dapr-sentry                              ClusterIP      10.103.5.73      <none>        80/TCP                                5d
dapr-webhook                             ClusterIP      10.102.11.122    <none>        443/TCP                               5d
```

**Comment by apwestgarth** [comment]
At this point we have only validated the preview on AKS and AKS-HCI

Are you attempting to browse to the app from within the VM on which you have deployed Kubernetes or from your local workstation - I think from reading your issue that you are attempting to browse to the VM hosting Kubernetes from your local workstation.

**Comment by KarenTazayan** [comment]
@apwestgarth I did [the steps from this tutorial](https://github.com/KarenTazayan/Azure-Container-Apps-On-Azure-Arc) with VM in Azure (Windows with WSL 2) and everything works as expected. At the same time when I do the same steps on a local Hyper-V VM a URL not working.

**Comment by apwestgarth** [comment]
@KarenTazayan the requests to your cluster do not route through Azure.  They will route direct to the cluster using your local networking configuration.  

When you create a connected environment our control plane queries the cluster to discover the external IP of the envoy service.  If the IP is an IP then we create an A record in Azure DNS to resolve to, if in the example of some other platforms the envoy service is bound to a domain name we create a CNAME record.

What looks to be happening is that your client cannot reach the envoy proxy loadbalancer service.  We have validated on AKS-HCI which in the majority of situations sits within a customer's network and Application URL resolves and the cluster is reachable.

**Comment by KarenTazayan** [comment]
@apwestgarth ok thank you! As I understand in this case, we need globally reachable IP. I mean unique static IP for an on-prem environment. Am I right? Is there any documentation where all traffic routing processes are deeply described?

**Comment by K-Hamdy** [comment]
did anyone manage to solve this? i'm having the same issue

**Comment by simonjj** [comment]
@K-Hamdy this should be fixed at this point. If you're still experiencing this please let us know.
