### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by SophCarp** [microsoft/azure-container-apps#582]
In Public Preview

Docs: https://learn.microsoft.com/azure/container-apps/cors

No solid ETA for GA

**Comment by hamenu** [comment]
Not sure if this has already been acknowledged or not, but when creating a new revision in Azure Poral, the `corsPolicy` property is set to `null`.

Use this template to provision a container app which includes `corsPolicy`:

```
param suffix string = uniqueString(resourceGroup().id) 
param location string = resourceGroup().location

resource managedEnvironment 'Microsoft.App/managedEnvironments@2022-10-01' = {
  name: 'env${suffix}'
  location: location
  properties: {
  }
}

resource containerApp 'Microsoft.App/containerApps@2022-10-01' = {
  name: 'app${suffix}'
  location: location
  properties: {
    managedEnvironmentId: managedEnvironment.id
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 80
        exposedPort: 0
        traffic: [
          {
            latestRevision: true
            weight: 100
          }
        ]
        corsPolicy: {
          allowedOrigins: [
            'http://localhost:1234'
          ]
        }
      }
    }
    template: {
      containers: [
        {
          name: 'app${suffix}'
          image: 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'
          resources: {
            cpu: json('0.25')
            memory: '0.5Gi'
          }
        }
      ]
      scale: {
        minReplicas: 1
        maxReplicas: 1
      }
    }
  }
}
```

Once deployed, you can see the `corsPolicy` is resource JSON under verson `2022-10-01`:

![image](https://user-images.githubusercontent.com/123523199/227084419-c1217b89-5958-4e4a-a02d-5a09b7897b60.png)

Now, using Azure Portal under 'Revision management' pane, create a new revision.

Once created/provisioned, load the resource JSON again. `corsPolicy` has changed to `null`:

![image](https://user-images.githubusercontent.com/123523199/227085012-a1c6552a-c4d4-4de1-b5ba-b0aab827b5c9.png)

It doesn't happen when using Azure CLI:

```
$ az containerapp revision copy --resource-group <resource-group> --name <container-app> --revision-suffix blahblah
```

```
$ az version
{
  "azure-cli": "2.42.0",
  "azure-cli-core": "2.42.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-devops": "0.26.0",
    "containerapp": "0.3.17",
    "front-door": "1.0.17",
    "portal": "0.1.3"
  }
}
```

Let me know if I need to create a separate issue for this.

**Comment by davemaul** [comment]
I got a similar issue when spinning up a Container App using the latest Pulumi Azure Native Provider (1.97.0) and the 20221001 API Version. In my case, the cors policy is ignored completely and thus not showing up in the final resource JSON.

**Comment by SophCarp** [comment]
We found the issue, and the fix will be released with the next portal update :)

**Comment by luklis** [comment]
@SophCarp What date is the next portal update scheduled for?

**Comment by SophCarp** [comment]
@luklis you should get the next portal update end of next week :)

**Comment by zane-woodard-drc** [comment]
Any update on when the fix will be released?

**Comment by davemaul** [comment]
This is critical for us as we are currently relying on (and paying for) the super unstable Azure Container Instances. The current ETA seems to quite unrealistic as April is almost over. It would be great if a fix or at least some information were release soon, @SophCarp. :)

**Comment by SophCarp** [comment]
Apologies for the delay. The bug mentioned in the comments was fixed, and CORS is now in Public preview.

**Comment by realrubberduckdev** [comment]
Is there any news on when this will be GA? We want to use CORS in production. Thanks.
