### ISSUE TITLE
Support Dapr Resiliency 

### ISSUE THREAD

**Issue by SophCarp** [microsoft/azure-container-apps#585]
ETA: Public Preview November

**Comment by greenie-msft** [comment]
Hi @michaelmccarver, @mikocot, others,

Yes, there is a bit of a delay with the Resiliency feature, but that's due to the scope of this capability expanding. 

We're in the design phase and currently looking for customer input. If you're open to having a conversation with the ACA product team to discuss the resiliency feature in-depth/share some of your project requirements as it pertains to resiliency, can you email me at nigreenf@microsoft.com? 

Thanks!

**Comment by michaelmccarver** [comment]
@greenie-msft 
Email Sent! Thanks for reaching out.

**Comment by berndverst** [comment]
@michaelmccarver I think that's a mistake by @dfraze.

This is definitely not in Public Preview.

I'm one of the Dapr maintainers and I also work on Dapr in Container Apps. This feature is not ready in Container Apps.

**Comment by cvisotski** [comment]
Has there been any update or new estimation to when we might see this feature ?

**Comment by henrikthorin** [comment]
Has this been released recently? We can see the following in our dapr logs 
`Error processing operation DaprBuiltInServiceRetries. Retrying in 1s…`

Long running calls are now being cancelled after 15 seconds and it seems like retries are taking place. I have not found any way to control either the timeouts or the resiliency in Azure Container Apps. All documentation on dapr relates to resiliency.yaml.

**Comment by aa-thomasjbyrne** [comment]
**URGENT - PRODUCTION ISSUE**

Also seeing the following in our Dapr logs:
**Error processing operation DaprBuiltInServiceRetries. Retrying in 1s…**" app_id=api-gateway-public instance=ca-xxxx-xxxxxx-xxxx-01--xxxxxx-xxxxxxx-xxxxxscope=**dapr.runtime** type=**log ver=1.11.2**-msft-3

Azure Deployment:
Web Portal \ Swagger >> **max 60 seconds**>> APIGateway (App Container + Dapr) >> **retrying every 15 seconds** >> QuotatrionService ( App Container + Dapr) [Quote takes  ~17 seconds to external API] 


Our API Gateway has a 60 seconds timeout, it calls another containerised service using Dapr up to 4 times, once every 15 seconds. This only started happening Monday 23rd Oct at 01:00:00 UTC.

**Has something been released to production that should not have been?? This is urgent as it is stopping business processing through our production system.**

**Comment by greenie-msft** [comment]
@michaelmccarver, @mikocot, @cvisotski 

The resiliency feature is now available: https://techcommunity.microsoft.com/t5/azure-developer-community-blog/resiliency-policies-now-available-in-azure-container-apps/ba-p/3978864

Please let me know if you have any questions as you try out resiliency in ACA!

**Comment by mcupito** [comment]
Glad to see this supported! We'll be giving this a try and reply with any feedback we may have -- thanks team!

**Comment by mikocot** [comment]
@greenie-msft good to hear that, unfortunately we had to give up dapr on the way due to multiple reliability issues, so I can't test it anymore. But I guess it's one step closer now :)

**Comment by greenie-msft** [comment]
@mikocot, I'm interested in learning more about the reliability issues you encountered. If you have the time and care to share please send any details to my email nigreenf at microsoft dot com.

**Comment by greenie-msft** [comment]
Closing as the resiliency feature is now available: https://github.com/microsoft/azure-container-apps/issues/999

**Comment by onionhammer** [comment]
How do I disable this? I'm seeing errors in my environment @greenie-msft

**Comment by berndverst** [comment]
> How do I disable this? I'm seeing errors in my environment @greenie-msft

@onionhammer it is not enabled for Dapr service invocation. And for components it is only enabled if you explicitly create a component resiliency policy.

Please contact Azure support for your specific concern for the fastest resolution. Of course you can open a new GitHub issue in this repo - but there is no guaranteed response time in this repo.
