### ISSUE TITLE
Peer-to-peer encryption

### ISSUE THREAD

**Issue by SophCarp** [microsoft/azure-container-apps#589]
8/30/2023 Public Preview: https://azure.microsoft.com/en-us/updates/public-preview-azure-container-apps-supports-environment-level-mtls-encryption/ 
Docs: https://aka.ms/aca/mtls

**Comment by cachai2** [comment]
Closing as [peer-to-peer encryption is GA](https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=workload-profiles-env%2Cazure-cli#peer-to-peer-encryption).
