### ISSUE TITLE
Support volume mount

### ISSUE THREAD

**Issue by takekazuomi** [microsoft/azure-container-apps#59]
Volume mount support.
1. Azure Storage volume mount, Storage File and Page Blob. 
2. Secret volume. That based on key vault secrets. 
3. Host machine local disk for temporary. 
Volume support is one of the big missing parts of container apps. I think.

**Comment by torosent** [comment]
Thanks @takekazuomi.  We are working on these features and will provide more details in the upcoming months.

**Comment by torosent** [comment]
Thanks @takekazuomi .  We are working on these features and will provide more details in the upcoming months

**Comment by ThorstenHans** [comment]
@torosent any updates regarding this one that you might want to share?

**Comment by danielmackay** [comment]
Any updates on when volume mounts will be available?  I'd like to know as if it's not going to be for a while I'll have to switch to using container instances instead.  Thanks in advance.

**Comment by kaushikCanada** [comment]
Any updates regarding htis? I need persistent volumes to work with this. also support putting in configuration variables like app service.

**Comment by voslucas** [comment]
Same here. Would love to see persistent volumes!

**Comment by mmayer-pt** [comment]
a warning in the ["compare" documentation](https://docs.microsoft.com/en-us/azure/container-apps/compare-options) or here in the [FAQ](https://github.com/microsoft/azure-container-apps/wiki/FAQs) with a feature/implementation-status matrix can help interested parties in the meantime when deciding on the service.

(Some language frameworks require writing a small number of transient files during runtime (<50MB). While the bulk can be moved into network caches, a filesystem is still needed)

**Comment by robersonliou** [comment]
We really need this feature! Please prioritize this requirement.

**Comment by anthonychu** [comment]
Azure Files and EmptyDir are coming within the next couple of weeks.

**Comment by ezYakaEagle442** [comment]
I have a customer having also this requirement

**Comment by zdrgeo-scaleforce** [comment]
I am happy to hear that Azure Files mount is coming soon. I see Azure Container Apps as potentially suitable for our journey to bring one of our old business-critical systems to 21st century and we will need this feature.

**Comment by robersonliou** [comment]
@anthonychu any update here?

**Comment by robersonliou** [comment]
Mount storage into container apps is available now! 
https://docs.microsoft.com/en-us/azure/container-apps/storage-mounts?pivots=aca-cli#azure-files

**Comment by StianHaugland1** [comment]
Ive been trying to run a container(official wordpress) with a volume mounted at /var/www/html and that works, but it makes the container really slow.... navigating between pages takes 5-15 seconds.

**Comment by onionhammer** [comment]
This seems like it's here, but there's definitely issues; 

```
2022-08-30T15:51:32.413418701Z Caused by: java.nio.file.FileSystemException: /opt/sonarqube/extensions/downloads/sonar-auth-aad-plugin-1.3.1.jar: Operation not permitted
```

Example; Running sonarqube in a container and mounting the plugins folder.

**Comment by kendallroden** [comment]
closing this because the feature is available- if you have issues please file a new issue

**Comment by dss010101** [comment]
is this supported with terraform?  documentation is lacking...
