### ISSUE TITLE
Roadmap: Event Grid support for system events

### ISSUE THREAD

**Issue by SophCarp** [microsoft/azure-container-apps#595]
No ETA (as of 1/31/23)

**Comment by Tapanila** [comment]
What does eventgrid support mean in this context?

**Comment by anthonychu** [comment]
@Tapanila  This is currently under design. Are there any specific system events you're looking for?

**Comment by Tapanila** [comment]
I would be very interested on the events that you are planning to support.

My Wishlist would be:

Container Apps Environment:
- Application added & removed
- Certification added & removed

Container App:
- Revision created & updated & deleted
- Container health probe failed
- container liveness probe failed
- secrets added & updated & removed
- Scaling (Keda) events

**Comment by tomkerkhove** [comment]
Related: https://github.com/kedacore/keda/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Acloudevents

**Comment by merou** [comment]
Maybe part of @Tapanila request - but it would be nice to have an event with the tag(version) of the docker image deployed and status.
The goal is to feed a downstream Internal Development Platform via the Event Grid webhook.

**Comment by denniszielke** [comment]
@anthonychu @SophCarp can you also include events for ACA shutdown?

**Comment by vportascarta** [comment]
Hi, I don't know if this issue is still active but to be able to have scheduled maintenance notifications in event grid would be nice (related issue https://github.com/microsoft/azure-container-apps/issues/1144)

**Comment by simonjj** [comment]
we will track this via #1144
