### ISSUE TITLE
Creating a container environment is failing

### ISSUE THREAD

**Issue by phillipleblanc** [microsoft/azure-container-apps#6]
I'm following the quickstart here: https://docs.microsoft.com/en-us/azure/container-apps/get-started?ocid=AID3042118&tabs=bash

And when I get to the point where I need to create a container environment, it is failing with the following message:

```bash
~ ❯❯❯ az containerapp env create --name $CONTAINERAPPS_ENVIRONMENT --resource-group $RESOURCE_GROUP --logs-workspace-id $LOG_ANALYTICS_WORKSPACE_CLIENT_ID --logs-workspace-key $LOG_ANALYTICS_WORKSPACE_CLIENT_SECRET --location "westcentralus"
Command group 'containerapp env' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/[subscription-id-removed]/resourceGroups/container-apps-quickstart/providers/Microsoft.Web/kubeEnvironments/containerapps-env?api-version=2021-02-01 (Caused by ResponseError('too many 500 error responses'))
```

**Comment by vturecek** [comment]
We don't yet support the `westcentralus` region. At this stage of the preview we only support `canadacentral` and `northeurope`.

**Comment by richeney** [comment]
The official docs pages do not mention the region limitation; I suggest this is added to the [overview](https://docs.microsoft.com/azure/container-apps/overview) page. 

Also a reminder on the [quickstart](https://docs.microsoft.com/azure/container-apps/get-started) where the variables are set.

The example on the [connect multiple apps](https://docs.microsoft.com/azure/container-apps/connect-apps?#location) page is for eastus2, which is not a supported region in preview.

The error message for Azure CLI commands (e.g. is not clear either). Running the `az containerapp env create` command in the quickstart against an unsupported region returns:

```text
Requested features are not allowed for subscription.
```

I suggest that this is trapped better and mentions that the only supported regions in preview are `canadacentral` and `northeurope`.

**Comment by Arcalise08** [comment]
I have been on support for days thinking something was wrong with my account. I created new accounts, submitted numerous support request and talked to no less then 10 microsoft representatives who could tell me nothing about why this was happening. It was only until i thought to look at the github that i found this. There is nothing, from the portal to the weird 500 errors you get trying to manually create it that would even hint to the possibility that only those two regions are supported.

This should be documented asap for future customers.

**Comment by kendallroden** [comment]
@anthonychu @craigshoemaker do we document the list of available regions anywhere?

**Comment by kendallroden** [comment]
FYI: az provider show -n Microsoft.App --query "resourceTypes[?resourceType=='managedEnvironments'].locations

**Comment by richeney** [comment]
```bash
az provider show --namespace Microsoft.App --query "resourceTypes[?resourceType=='managedEnvironments'].locations[]"
```

Current output:

```json
[
  "Canada Central",
  "West Europe",
  "North Europe",
  "East US",
  "East US 2"
]
```
