### ISSUE TITLE
ARM API for microsoft.app/managedenvironments version 2022-06-01-preview is broken

### ISSUE THREAD

**Issue by tedvanderveen** [microsoft/azure-container-apps#602]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a:
- [x] bug report
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When we try to use version `2022-06-01-preview`, the ARM API always returns error `PremiumManagedEnvironmentCreationNotEnabled`.
PremiumManagedEnvironmentCreationNotEnabled
### Steps to reproduce
1. Follow guidelines provided by Microsoft: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-06-01-preview/managedenvironments?pivots=deployment-language-bicep#environmentskuproperties
2. Provide following Bicep configuration:
```
resource containerAppsEnvironment 'Microsoft.App/managedEnvironments@2022-06-01-preview' = {
  name: containerAppsEnvName
  location: location
  sku: {
    name: 'Premium'
  }
  properties: {
    workloadProfiles: [
      {
        workloadProfileType: 'GP1'
        minimumCount: 3
        maximumCount: 5
      }
    ]
    vnetConfiguration: {
      infrastructureSubnetId: resourceId(resourceGroup().name, 'Microsoft.Network/virtualNetworks/subnets', spokeVnet.name, containerappenvSubnetName)
      internal: true
      outboundSettings: {
        outBoundType: 'UserDefinedRouting'
        virtualNetworkApplianceIp: '10.205.0.132'
      }
    }
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalyticsWorkspace.properties.customerId
        sharedKey: logAnalyticsWorkspace.listKeys().primarySharedKey
      }
    }
    zoneRedundant: false
  }
}
```

**Expected behavior** The Azure Container App Environment is successfully created and egress traffic is routed via the configured UDR and virtualNetworkAppliance configured in Bicep property `properties.vnetConfiguration.outboundSettings`.

**Actual behavior**
Azure ARM API returns error message:
```
{
    "status": "Failed",
    "error": {
        "code": "PremiumManagedEnvironmentCreationNotEnabled",
        "message": "Creating Premium Plan Container Apps Environments is not enabled."
    }
}
```

**Comment by cwe1ss** [comment]
There is no "Premium" SKU yet. you can either completely leave out the "sku"-property, or I guess it will also work with the value "Consumption".

**Comment by torosent** [comment]
Hi. Please use the stable API versions. UDR is currently under development. Public preview is slated for Q1 2023.
