### ISSUE TITLE
Internal containers communication and redirection to HTTPS

### ISSUE THREAD

**Issue by KrzychuR** [microsoft/azure-container-apps#61]
# Our test scenario

1. Container1: NGINX as frontend server 
2. Container2: WebAPI as application API

## important NGINX part

```
location /xxx-api {
            rewrite ^/xxx-api/(.*) /$1 break;
            proxy_pass http://xxx-api.internal.yyyy.northeurope.azurecontainerapps.io;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host xxx-api.internal.yyyy.northeurope.azurecontainerapps.io;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
```
## ingress configuration for WebAPI
```
            "ingress": {
                "fqdn": "xxx-api.internal.yyyy.northeurope.azurecontainerapps.io",
                "external": false,
                "targetPort": 80,
                "transport": "Auto",
                "traffic": [
                    {
                        "weight": 100,
                        "latestRevision": true
                    }
                ],
                "allowInsecure": false
            },
```
Observed issues:

1. HTTP call to WebAPI FQDN returns redirect response to HTTPS  - is it expected ?
2. No way to set `allowInsecure: true` via `az containerapp update` I'll try to create new container later then
3. Issues with update similar to https://github.com/microsoft/azure-container-apps/issues/60
4. Is `proxy_set_header Host xxx-api.internal.yyyy.northeurope.azurecontainerapps.io;` correct? Can we use just `proxy_set_header Host $host` ?

**Comment by simonjj** [comment]
@KrzychuR, closing this issue, but from my knowledge the answers are as follows:

1. Yes, if you don't allow insecure this is expected.
2. Yes, this setting you will have to change through the App's Yaml
3. This seems resolved
4. Yes, I believe that notation should work and have the same outcome.
