### ISSUE TITLE
Feature Request: Ignore urls to bypass authentication

### ISSUE THREAD

**Issue by rhuanbarreto** [microsoft/azure-container-apps#610]
I'm setting up a Streamlit application in ACA. And in order to not have to develop the auth myself, I'm deploying the container directly to ACA and using the auth middleware container as described in the docs https://learn.microsoft.com/en-us/azure/container-apps/authentication.

The problem is that Streamlit uses web sockets to stream the UI to the browser. And if I apply the middleware, the connection breaks, most probably due to not using HTTP 1 and propagating headers. Even though I'm using http on ingress instead of http2.

It would really be beneficial to unblock such use cases, where you don't want to develop the authentication code yourself and leverage the power of ACA in order to not think about it.

The desired solution would be to use the auth middleware and have a websockets endpoint working normally.

Only alternative today is to not use this feature in ACA and make it yourself, either through Python or through other proxies like https://oauth2-proxy.github.io/oauth2-proxy/. Using other proxies you would probably need to add some extra configuration to treat the connection as http1 and add some extra headers.

**Comment by ahmelsayed** [comment]
I believe this is the same as https://github.com/microsoft/azure-container-apps/issues/549 

It should be fixed now, so closing the issue.
