### ISSUE TITLE
Feedback : Public IP Address resource associated with Container App Environment

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#613]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
In the following documents, the description "Outbound IPs aren't guaranteed and may change over time." was added to the "Outbound public IP" item. 

- Networking architecture in Azure Container Apps  
  https://learn.microsoft.com/en-us/azure/container-apps/networking

This outbound IP is a recognition of Microsoft-managed public IP Address resources (Standard SKU, Static IP), similar to the inbound IP address, and the IP address is a fixed recognition.

Would you please clarify in what cases the sending IP may be changed?

The reason for my feedback is that there are web applications in other clouds that act on the results output by ACAs. The access control of the web application is only IP address, and I am afraid that if the sending IP address of ACAs is changed unintentionally, it will not work as a system.

### Steps to reproduce
Due to the lack of SNAT, it is our understanding that Microsoft-managed public IP Address resource created during deployment will not be removed or changed, even if additional outbound IP addresses are added through a support inquiry.

**Comment by cachai2** [comment]
We don't guarantee that specific outbound IP addresses used by your Container Apps won't change based on scenario. If needed, you can [define your static IP with a NAT Gateway](https://learn.microsoft.com/en-us/azure/container-apps/networking#nat-gateway-integration---preview) in the workload profiles architecture which is currently in preview. Does this work for your requirements?

**Comment by YuKogasaka** [comment]
@cachai2,

Since Workload Profiles Architecture is the only way to fix outbound IP address, I think it will be necessary to rebuild the Container Apps Environment and redeploy ACA, but it meets the my requirements.

thank you.

**Comment by cachai2** [comment]
Awesome! I'll close this issue for now, but please let us know if anything else comes up or if you have any additional feedback.
