### ISSUE TITLE
Revision is Provisioned but there are no replicas (scale 1-1)

### ISSUE THREAD

**Issue by nickraphael** [microsoft/azure-container-apps#614]
There seems to be a big disconnect between the 'Provision Status' on the Revision Management screen and what's really provisioned.  
What is the source of truth here?  I have a container scaled to 1-1 that is apparently Provisioned but when viewed on the Log Stream screen I'm told 'The revision is scaled to zero'.  And I can't hit it from outside so I guess it's not really provisioned.

Regards

**Comment by SophCarp** [comment]
responded to this issue in #615
