### ISSUE TITLE
"ScaledObject doesn't have correct scaleTargetRef specification" in logs

### ISSUE THREAD

**Issue by nickraphael** [microsoft/azure-container-apps#615]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
In the azure portal, the 'revision management' screen shows my latest revision is Provisioned.  But clicking to 'Log stream' page shows 
'This revision is scaled to zero.' message.  Scaling is set to 1-1 for this app.

### Steps to reproduce
1. .  Create a new revision
2. .  Once provisioned, navigate to Log Stream screen.

**Expected behavior** [What you expected to happen.]
I'd have expected a status of Provisioned once the replicas have been created.

**Actual behavior** [What actually happened.]
Status of provisioned but no replicas created.

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by SophCarp** [comment]
Hi @nickraphael! There are a few different ways to access observability in ACA: https://learn.microsoft.com/en-us/azure/container-apps/observability . There are times when an app is provisioned but something has happened to affect the health. I'm working on a feature to add health observability. When the log stream can't observe anything, the "logs" blade might help you instead. Here's a tutorial for using log analytics: https://learn.microsoft.com/en-us/azure/azure-monitor/logs/log-analytics-tutorial 

![image](https://user-images.githubusercontent.com/103968777/218822925-468fe7f3-49c1-4e8f-9a6f-e1616dca3a4b.png)

Let me know if that helped!
