### ISSUE TITLE
Feature Request: Provide a way to easily and quickly scale a container app to zero

### ISSUE THREAD

**Issue by avalanchis** [microsoft/azure-container-apps#618]
**Is your feature request related to a problem? Please describe**.  
I have several container applications that process messages from Azure Service Bus.  During development, I often need to scale an application to zero in order to run my application locally so that the service bus messages are only processed by my local instance.

Currently I'm using the UI to set the scale to 0-1 and then I have to wait approximately five minutes for the application to scale to zero.  When we were running our application under AKS I could easily shut down all pods immediately with a simple Kubernetes command.

**Describe the solution you'd like**.    
I would like an easy way to immediately scale an application to zero via the UI.  Another nice to have would be an easy way to scale the application back up to its previously configured scale values.  Essentially I'd like an easy way to stop/start an application.

**Comment by avalanchis** [comment]
Similar to #376.

**Comment by simonjj** [comment]
There's a stop button now.

<img width="653" alt="image" src="https://github.com/user-attachments/assets/b0500a86-7909-4b52-886c-6180bb99a0db">

**Comment by avalanchis** [comment]
Yes, I've been using it for a while now.  Works great thanks!
