### ISSUE TITLE
EasyAuth support

### ISSUE THREAD

**Issue by KrzychuR** [microsoft/azure-container-apps#62]
This feature: https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization is very handy. It works as expected with Web App for Containers. Any plans to enable it for Azure Container Apps?

**Comment by denniszielke** [comment]
Dapr middleware support would be one option to enable this.

**Comment by torosent** [comment]
We are working on EasyAuth integration and will provide more details soon.

**Comment by danielkon96** [comment]
There is a project that a few of my colleagues and I at Microsoft worked on to bring EasyAuth to Kubernetes. You can find the repo here: https://github.com/Azure/EasyAuthForK8s
