### ISSUE TITLE
Replica starts consuming 100% CPU constantly

### ISSUE THREAD

**Issue by grott0** [microsoft/azure-container-apps#620]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We have a container app revision for testing purposes which has a very basic scale rule:

![scale-options](https://user-images.githubusercontent.com/29913734/218118853-bf9deca1-a953-442e-bfcb-9375948d5236.PNG)

The revision does scale and the replicas increase, but at some point one of the replicas starts consuming max CPU constantly and appears to be stuck.

![metrics](https://user-images.githubusercontent.com/29913734/218119959-724e6f05-5c74-4b1f-9e2c-79665f1787c3.PNG)

We've already tried diagnosing the issue by connecting to the replica container through the console and installing all things necessary to run dotnet-counter, dotnet-trace and dotnet-dump, but all of these tools get stuck when ran:

![dotnet-trace](https://user-images.githubusercontent.com/29913734/218120295-833cf1b8-75f4-4667-b254-31a94dae1bf7.PNG)

![dotnet-dump](https://user-images.githubusercontent.com/29913734/218120314-6bc034cc-1b5d-45d4-96a0-3dc18ed4adb9.PNG)

The issue is gone after a revision restart. An interesting thing is that the 'stuck' revision is still visible in the log stream tab, but when one tries to connect to it, the following error is shown:

INFO: Connecting to the container 'wf-background-emea-raccoon-initial-container1'...
ERROR: {"Error":{"Code":"ClusterExecEndpointWebSocketConnectionError","Message":"Failed to establish WebSocket connection with the container, error is Failed to establish WebSocket connection with Kubsernetes cluster exec endpoint, error: The server returned status code \u0027500\u0027 when status code \u0027101\u0027 was expected..","Details":null,"Target":null},"Code":"ClusterExecEndpointWebSocketConnectionError","Message":"Failed to establish WebSocket connection with the container, error is Failed to establish WebSocket connection with Kubsernetes cluster exec endpoint, error: The server returned status code \u0027500\u0027 when status code \u0027101\u0027 was expected..","Details":null,"Target":null}

### Steps to reproduce
No stable reproduce. We notice that it happens from time to time.

**Expected behavior**  We expect the replica to oscillate in terms of CPU usage based on the load it experiences.

**Actual behavior** CPU remains constantly high.

**Screenshots**         
I've already added them above.

### Additional context
N/A

**Comment by grott0** [comment]
Update: 

We tried removing the 'cpu-scaling' rule and leaving the min/max replica count config as it was (1 min - 3 max). Even without any scale rules defined, the revision still scaled to 3 replicas and all of the replicas started consuming max CPU (1 core as per the Metrics graph). If there are no explicit scale rules defined, what  are the implicit rules for scaling? We definitely feel like this problem is related to scaling, because all of the revisions that experience it have scaled in some way or another.

**Comment by grott0** [comment]
Update:

We've made all of our revisions 'unscalable' (min/max count == 1). The issue still occurs. The scaling problems hypothesis is not correct. At this point we've created an internal support request with MS for this issue as it's seriously impeding our work.

**Comment by SophCarp** [comment]
Thank you for requesting an internal support request. Can you email the support request details so we can track it on our end? socarpenter@microsoft.com

**Comment by grott0** [comment]
@SophCarp you've got mail :)

**Comment by grott0** [comment]
Update:

It's worth noting that when I connect to a replica which hosts a non-responsive app and I run top/htop, I can see that the app is constantly consuming 100% CPU, yet when I look at the Metrics blade on the container app the graph shows that the replica is consuming 1 core constantly, which is actually 50% of the allocated 2 cores. Why is that and where does the discrepancy come from?

**Comment by ahmelsayed** [comment]
@grott0 that's because [top(1)](https://man7.org/linux/man-pages/man1/top.1.html#3._FIELDS_/_Columns) reports CPU per core. So you'd have 200% for 2 cores.

**Comment by ahmelsayed** [comment]
I think there is an open support case for this app, right? If this repros by restarting the app the on-call engineer can help collecting the dotnet traces needed since you won't be able to run dotnet-monitor with the permissions it needs as mentioned in #653

**Comment by grott0** [comment]
> @grott0 that's because [top(1)](https://man7.org/linux/man-pages/man1/top.1.html#3._FIELDS_/_Columns) reports CPU per core. So you'd have 200% for 2 cores.
> 
> _edit: by default at least, as the man page says, you can toggle that by pressing `H` or use [`htop`](https://man7.org/linux/man-pages/man1/htop.1.html)_

Yeah. That makes sense now. Thank you!

> I think there is an open support case for this app, right? If this repros by restarting the app the on-call engineer can help collecting the dotnet traces needed since you won't be able to run dotnet-monitor with the permissions it needs as mentioned in #653

Not reproducible in a deterministic manner so restart and collect is not a viable option. We notice that this behavior occurs only when there's a significant amount of load on the replica. 
Anyway, I've been in email contact with one of your support colleagues for a couple of weeks now and will try to schedule a call with him so we can agree on a gameplan of how the log collection will be achieved.

P.S. I've replied to #653 before doing so here, but I still the question which I posed is still valid.

**Comment by grott0** [comment]
The issue has been resolved. It seems like the problems were caused by the base Docker image of the .NET Runtime which we were using. We switched from Alpine to Debian and the hanging + CPU consumption issues are gone now.
