### ISSUE TITLE
Unable to deploy container apps in East US (both portal and arm) 

### ISSUE THREAD

**Issue by KamilLach** [microsoft/azure-container-apps#622]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Starting today around 1 PM (UTC) we noticed failures during container app deployment (the previous builds were successful). Builds are failing after 10 mins (I think timeout-related)  with the message: **Internal server error occurred. correlation ID: 4c363f44-f615-4681-97ed-30e25f3b08b3**

Region: East US
Managed Environment mode: Internal, Limited to Vnet only
Container registry:  Custom registry available in the internal network 

### Steps to reproduce
1. Deploy using ARM API 
2. Build of the container app will fail after 10 mins with an internal server error. 

**Expected behavior** Deployent should work

**Actual behavior** Deployment failing with **Internal server error occurred. correlation ID: 4c363f44-f615-4681-97ed-30e25f3b08b3**

### Additional context
Deployment using the azure portal fails immediately with the following:
![image](https://user-images.githubusercontent.com/2822114/218482000-080305cd-5740-4692-970c-04abf276f654.png)

**Comment by torosent** [comment]
We are investigating according to your correlation id. Will update soon

**Comment by torosent** [comment]
@KamilLach, we confirmed this is a bug related to one of our validation components and created a work item to fix it.

**Comment by ekjuanrejon** [comment]
I'm having the same issue. trying to use the following bicep

https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-bicep

**Comment by ekjuanrejon** [comment]
"statusMessage": "{\"error\":{\"code\":\"InternalServerError\",\"message\":\"Internal server error occurred. correlation ID: ce88060a-a271-419e-964d-4cb9d215c504\"}}"

**Comment by RiverHeart** [comment]
This issue stills seems to be happening, at least when VNET integration is enabled.

**Comment by simonjj** [comment]
I hope this has long been addressed. Please reopen if it still exists.
