### ISSUE TITLE
Console Logs & System Logs no longer open Logs query to respective logs

### ISSUE THREAD

**Issue by charris-msft** [microsoft/azure-container-apps#624]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduce
1. From Revision Management > Revision details 
2. Click"View details" for either Console logs or System logs 
3. The generic Logs page opens with no query pre-selected, and hundreds or thousands of queries to choose from

**Expected behavior**
Logs page opens with query appropriately pre-populated and run for the selected logs.

**Actual behavior** [What actually happened.]
The generic Logs page opens with no query pre-selected, and hundreds or thousands of queries to choose from

**Screenshots**         
![image](https://user-images.githubusercontent.com/74415662/218612462-530aa39e-aeb0-4b35-a8a7-f77c3d9971be.png)

### Additional context
Portal

**Comment by samsp-msft** [comment]
See also #635

**Comment by SophCarp** [comment]
Bug has been logged (17422339), thanks for sharing!

**Comment by LianaAdaza** [comment]
Thank you for your report. Internal bug 17422339 has been resolved. Please feel free to reach out if you continue to encounter difficulties.
