### ISSUE TITLE
Feature Request: Sort Logs by date automatically

### ISSUE THREAD

**Issue by charris-msft** [microsoft/azure-container-apps#625]
**Is your feature request related to a problem? Please describe**.  
Sort order for ContainerAppConsoleLogs_CL (or system logs) query results are not sorted by date by default. Unless you happen to notice this, the order of the entries in the logs can be very confusing and this certainly leads to longer troubleshooting.

![image](https://user-images.githubusercontent.com/74415662/218613206-3f74200a-f7c0-4c2e-82ce-04b0183c1492.png)

**Describe the solution you'd like**.    
The default query that opens when you click "System Logs" or "Console Logs" from the details window should sort the logs with the most recent entry at the top and the oldest one at the bottom. 
Why newest at top? The user shouldn't be able to start reviewing most recent activity immediately without having to scroll.

**Describe alternatives you've considered**.   
I already fix this myself when I open the query, but this is a poor user experience when we can make it much better automatically.

**Additional context**.

**Comment by LianaAdaza** [comment]
Fix has been rolled out. Please create a new issue if you continue to experience difficulties.
