### ISSUE TITLE
Bug Report: inconsistent operation of the container app, starts and crashes

### ISSUE THREAD

**Issue by makaralaszlo** [microsoft/azure-container-apps#628]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We have two container app environments. On one we deployed a Python-based microservice and it works fine. We deployed that docker container to an identical container app environment, but it does not work on that environment. It starts up and crashes with an error code of 137. According to the 137 errror code, the container should be running out of memory, but based on the Application insights, it is not using even 1 Gb of memory. The container app is sized for 2 CPU cores and 4 Gb of memory.

While trying to access the container via the console, we get the following logs:
```
INFO: Connecting to the container 'azure-hu-lp-data-export-test'...
ERROR: {"Error":{"Code":"ClusterExecEndpointWebSocketConnectionError","Message":"Failed to establish WebSocket connection with the container, error is Failed to establish WebSocket connection with Kubsernetes cluster exec endpoint, error: The server returned status code \u0027500\u0027 when status code \u0027101\u0027 was expected..","Details":null,"Target":null},"Code":"ClusterExecEndpointWebSocketConnectionError","Message":"Failed to establish WebSocket connection with the container, error is Failed to establish WebSocket connection with Kubsernetes cluster exec endpoint, error: The server returned status code \u0027500\u0027 when status code \u0027101\u0027 was expected..","Details":null,"Target":null}
```

```
INFO: Connecting to the container 'azure-hu-lp-data-export-test'...
ERROR: {"Error":{"Code":"ClusterExecEndpointWebSocketConnectionError","Message":"Failed to establish WebSocket connection with the container, error is Failed to establish WebSocket connection with Kubsernetes cluster exec endpoint, error: The server returned status code \u0027500\u0027 when status code \u0027101\u0027 was expected..","Details":null,"Target":null},"Code":"ClusterExecEndpointWebSocketConnectionError","Message":"Failed to establish WebSocket connection with the container, error is Failed to establish WebSocket connection with Kubsernetes cluster exec endpoint, error: The server returned status code \u0027500\u0027 when status code \u0027101\u0027 was expected..","Details":null,"Target":null}
```

With the same configuration, on the container app environment where the container is working properly, the following amount of resources are consumed:
CPU: 3.9%
MEM: 0.5%

### Steps to reproduce
1. idk - this is probably due to a bug in the container app environment

**Expected behavior** [What you expected to happen.]
Python (Flask-based) application starts.

**Actual behavior** [What actually happened.]
Alternate between provisioning, provisioned and failed state.

**Screenshots**         
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/41130143/218746636-b2630bab-aa31-4828-824e-b266174f5095.png)
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/41130143/218746640-958b6a87-c4b2-443c-8445-f9d615352cf2.png)
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/41130143/218746645-d15d0d9c-279e-4578-96f1-32f4759d4646.png)
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/41130143/218746651-01b45db2-f78f-4d2e-bc50-db631c6ec03a.png)
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/41130143/218746655-5d75b0e5-1cd3-4a05-8aa4-aa75f1309ef8.png)
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/41130143/218746659-50a6b62f-a74a-412d-87e4-32d6d7cefbe6.png)

### Additional context
Tested on the Portal page.

**Comment by SophCarp** [comment]
Hi @makaralaszlo thanks for sharing. This might be related to issue #534. There was discussion there that you can read. We're also in the process of increasing the ephemeral storage, which you can track on the roadmap in issue #599. Let me know if 534 helped you out! If not, I can triage it as a bug.

**Comment by SophCarp** [comment]
hmm, okay, good to know. Can you email me the details of your container app (subscription, environment name, app name) and I can pass it along. socarpenter@microsoft.com

Thanks!

**Comment by redfave** [comment]
I'm also affected by this bug. It just happend to affect new deployments of container apps, without a reasonable explanation. I'm using Terraform for deploying required resources for testing an container app and deleting them afterwards.
Whereas last week the Terraform script worked, today the new deployed containers inside a container app just starts, but terminates immideatly after a successfull start, as described in the initial report. 
Cpu is set to `0.25` and RAM to `0.5Gi`. It's a very simple node.js app inside an alpine container and consumes barely 200 MB of RAM, looking at the metrics. The Azure Region is set to `West Europe`.

**Comment by desokey** [comment]
@makaralaszlo it seems you deleted the affected app, environment, can you please repro and send me the app name and environment id.
@redfave  please feel free to send me your too. maldesok@microsoft.com

**Comment by SophCarp** [comment]
Closing issue as resolved, as the apps have been deleted. Please let me know if this issue is continuing, and we can re-open. Thanks!
