### ISSUE TITLE
'az containerapp env certificate list ' is broken in containerapp extension v0.3.22

### ISSUE THREAD

**Issue by asankaf** [microsoft/azure-container-apps#631]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
Running azure cli command `az containerapp env certificate list` stopped working in the latest version of containerapp extension (0.3.22). It works just fine in version 0.3.21

### Steps to reproduce
1. Install latest version of containerapp extension in azure cli (0.3.22)
2. execute the command `az containerapp env certificate list -g MyResourceGroup --name MyEnvironment`

**Expected behavior** [What you expected to happen.]
The command to return the list of certificates added into the container apps environment specified

**Actual behavior** [What actually happened.]
It returns an error "ERROR: Not Found({"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-0e305be13ababbc5eb2cec3eb561279f-c4c7b9a3af956ec6-01"})" 

**Screenshots**         
v0.3.22 (Broken)
![image](https://user-images.githubusercontent.com/1999525/219395492-7c72d452-f07f-4dfa-b3d6-e77d58a95a86.png)

v0.3.21 (Works)
![image](https://user-images.githubusercontent.com/1999525/219394676-3ceec291-0d21-42d2-bf1a-8503d7d9b26e.png)

**Comment by SophCarp** [comment]
We reverted the update that caused this issue, and it should be fixed now. Let me know if it still is showing up!
