### ISSUE TITLE
Increased memory and vCPU

### ISSUE THREAD

**Issue by SophCarp** [microsoft/azure-container-apps#633]
ETA: Early April

**Comment by BigMorty** [comment]
You can see the new limits in our docs here - https://learn.microsoft.com/azure/container-apps/containers#configuration

The increase is only in the new Consumption + Dedicated plan structure we just released in public preview. You can read more about that here - https://learn.microsoft.com/azure/container-apps/plans

**Comment by tamland** [comment]
Will the consumption only plan receive similar increases in the future?
The Consumption + Dedicated plan allows 100 cores for the Consumption profile while the Consumption only plan allows only 40. We have tried the new Consumption + Dedicated plan structure however, it requires creating a new environment and manually migrating existing apps over (a lot of work), and it does not appear to support zone redundancy.

**Comment by passarela** [comment]
When will we have availability in the Brazil South region?

**Comment by BigMorty** [comment]
Yes, the consumption only plan will be increasing to 100 cores very soon. I am checking on the timing for this and will get back when I know specifics.

We are working to bring the new Consumption + Dedicated to more regions.

We are investigating what it would take to migrate from Consumption only to Consumption + Dedicated. It is not something that will happen soon to set expectations.

**Comment by tamland** [comment]
@BigMorty Do you have an update for when 100 cores will be available, or should we submit a support ticket requesting a limit increase?

**Comment by SophCarp** [comment]
@tamland,100 cores is available in consumption! The docs are being updated now.
