### ISSUE TITLE
Unable to connect to container app console via UI or CLI

### ISSUE THREAD

**Issue by ragemnky** [microsoft/azure-container-apps#634]
> Please provide us with the following information:
> ---------------------------------------------------------------

### Issue description
Unable to connect to container app console via UI or CLI. 

### Steps to reproduce
1. New container app environment, use your own virtual network set to no.
2. New container app using quickstart image, simple-hello-world-container.
3. Scale set to 1:1, revision management showing provisioned.
4. UI (Azure Portal) > Container App > Monitoring > Console > Connect.
or
5. Azure CLI; az containerapp exec --name mycontainer --resource-group myresourcegroup

**Expected behavior** [What you expected to happen.]

Connect to container console via UI or CLI.

**Actual behavior** [What actually happened.]

UI errors with: Failed to connect to replica.
CLI errors with: websocket._exceptions.WebSocketBadStatusException: Handshake status 401 Unauthorized

**Comment by nattyg93** [comment]
We're experiencing the same issue - is there any news on a fix for this one? It's making life very difficult.

**Comment by AlokBisht** [comment]
We are facing the same issue.
<img width="508" alt="image" src="https://user-images.githubusercontent.com/11396663/234477044-b10dce3c-53dd-4564-a2b4-e2783fc3d05d.png">

**Comment by drattek** [comment]
Same issue here.

**Comment by giladshanan** [comment]
This issue hit us some time in the last week - was there a recent update that might have caused a regression?

**Comment by FekryMostafa** [comment]
same

**Comment by hederms** [comment]
Same issue here, only in regions West US and Brazil South.

**Comment by dmexs** [comment]
Experienced today in use2.

**Comment by davidfrigolet** [comment]
Experienced today in UK South

**Comment by jasn-seso** [comment]
Just a few minutes ago the same thing.

**Comment by simonjj** [comment]
Thank you for reaching out. Question for you, is this an issue that happens repeatably throughout the day or does this work during off times.

**Comment by jasn-seso** [comment]
> Thank you for reaching out. Question for you, is this an issue that happens repeatably throughout the day or does this work during off times.

There was a time when it was very recurrent, I'm talking about months ago, this time it was in the early hours of the morning and it caused us a lot of problems for us.

**Comment by nattyg93** [comment]
This is an ongoing issue and needs to be reopened. We are experiencing this again today in Australia east.

**Comment by matyasrichter** [comment]
Experiencing this today in West Europe.

**Comment by admsallai** [comment]
Same issue just now

**Comment by CezaryKlus** [comment]
Same issue here: #1299 1299

**Comment by simonjj** [comment]
Thank you all. Please use #1299 to report any new occurrences of this. Please make sure to mention your deployed region as well.
