### ISSUE TITLE
Feature Request: Include a handful of queries under an "Azure Container Apps" node in the queries popup

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/azure-container-apps#635]
**Is your feature request related to a problem? Please describe**.  
When you click the "Logs" pane in the ACA portal you are presented with a view looking something like:
 
![image](https://user-images.githubusercontent.com/54915162/219801319-a6707447-9df6-4898-8612-6a2b73924a14.png)

What I typically want to do is to see the most recent logs, however, nothing in the left is related to ACA, so there is a steep learning curve involved to be able to see the logs.

**Describe the solution you'd like**.    
Include a set of default queries, under a category of "Azure Container Apps". The first of which I'd suggest would be:

"Most Recent Log entries"

which would have a query something like:

``` kusto
ContainerAppConsoleLogs_CL 
| top 500 by _timestamp_d
| project  ContainerName_s,TimeGenerated , Log_s
| summarize by ContainerName_s, TimeGenerated, Log_s
```

The columns of the query should be kept to a minimum, so that the "Log_s" result has the most width, as that is what users will recognize from the console.

There are probably other ACA related queries, that would be good to include, but again I'd recommend keeping the list small so that its easy to find the ones that you want.

**Comment by simonjj** [comment]
we now have some of these queries
![image](https://github.com/user-attachments/assets/bdaf8c65-4776-4366-b58f-6007bf2943da)
