### ISSUE TITLE
Log stream fails when container is scaled to 0

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/azure-container-apps#636]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The error that is produced when attempting to use the Log Stream when the container has been timed out is confusing.

![image](https://user-images.githubusercontent.com/54915162/219802971-d7846229-235c-4e21-9229-9f45bea46cb0.png)

The problem is really that the container has been scaled to 0 because of inactivity. The default scale rule is a 0..N configuration, and when developing a service it's not likely to have constant traffic, and timing out will be common. 

### Steps to reproduce
1. Create an app, deploy it, let it time out
2. Try and use the Log Stream to see what is going on with the application

**Expected behavior** [What you expected to happen.]

The page should state:

> There are no active instances. This may be because of a scale rule for 0..N instances, and the service has scaled to 0 because of inactivity. Calling the service via {url} should create a new instance, wait {suggested timeout} and refresh to view the logs.

**Actual behavior** [What actually happened.]

See screenshot above.

The link to revision management is not helpful, as there is nothing directly in that page to adjust the scaling. Adjusting from a 0..N scaling is probably not what is needed by the customer, as it will potentially cost them more to keep the service running when it is not needed. The page does not explain that containers can be scaled to 0 due to inactivity, and that they can be woken again.

**Comment by SophCarp** [comment]
Hi @samsp-msft thanks for reaching out!

I've logged the issue (17422217), so it's in our backlog.

**Comment by simonjj** [comment]
keeping this open for now

**Comment by marcindulak** [comment]
> keeping this open for now

However it got closed?
