### ISSUE TITLE
Unable to create a new revision in portal when container has a volume mount defined

### ISSUE THREAD

**Issue by ronlhayes** [microsoft/azure-container-apps#637]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
After creating a container volume mount using CLI (yaml) I am unable to create a revision. The portal displays an error "Editing a container with a volume mount is currently not supported". I realize this feature is in preview but what good is the feature if it prevents you from editing or adding new revisions? When will this be fixed (not currently supported)? Having volume mounts is a requirement for our project.

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]
Ability to create/edit revisions.

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal? Portal (have not tried CLI)

**Comment by SophCarp** [comment]
@anthonychu

**Comment by simonjj** [comment]
Closing this, because we have portal support for volume mounts now.  🎉
