### ISSUE TITLE
scaling down to min replicas on deployment

### ISSUE THREAD

**Issue by JonasSamuelsson** [microsoft/azure-container-apps#638]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We're seeing unexpected behavior during deployments.
We are running in single revision mode on a minimum of 2 replicas with CPU based auto scaling enabled.
Deployments are done using azure cli command ´az containerapp revision copy´ where we update the image.

This works great for us as our system is used primarily during office hours, we scale out as needed and then back down to 2 replicas during nights and weekends.

As seen in the screenshots below this api is running on 7 replicas when a new version is deployed.
All traffic is routed to the new version at 9:36:45 but only on 2 replicas.
After almost 2 minutes we get 2 more replicas and after yet another 30 seconds we get 4 more.

Our assumptions were that the new version would continue on the same number of replicas as the previous version, but it looks like the scale state is lost on each deployment. This leads to lousy response times for a few minutes on each deploy as the new replicas are bombarded with traffic until they are scaled out again.
Is this the expected behavior?

These screenshots are from app insights during a deployment, they are all per second.

Requests per application version
![image](https://user-images.githubusercontent.com/2103937/220176860-1743d994-03dc-44f6-a379-51f298baa92d.png)

Requests per replica
![image](https://user-images.githubusercontent.com/2103937/220177004-58681be9-64b0-4e78-be6c-86052df152bf.png)

Replicas per application version
![image](https://user-images.githubusercontent.com/2103937/220176784-025ead38-a438-4165-b2f3-23256ff41097.png)

These screenshots are from azure metrics, slightly wider timeframe and per minute.

Average CPU per replica
![image](https://user-images.githubusercontent.com/2103937/220178187-0371b84a-4a6b-4c25-af3b-bdcf6c8a54e0.png)

Requests per replica
![image](https://user-images.githubusercontent.com/2103937/220178115-4c9f607e-4c7a-4a43-a031-5a21c78f5cfe.png)

**Comment by JonasSamuelsson** [comment]
I found [this reply](https://github.com/microsoft/azure-container-apps/issues/493#issuecomment-1317898844) from @ahmelsayed in another issue

> Correct, each revision has its own scale meters/counters. The http counters are not inherent or shared between revisions, so it'll go through its own scaling flow. I agree that it'd work better if the new revisions come up with the scale counters of the previous revision

That comment refers to http counters but is it the same for cpu as well, I'm guessing it is?
You seem to agree that this is problematic, for us it's a blocker, is this on your roadmap to fix?

**Comment by SophCarp** [comment]
Hi Jonahs, thanks for bringing this issue up. I haven't seen this on our roadmap, but @ahmelsayed do you know anything?

**Comment by JonasSamuelsson** [comment]
Any feedback here would be greatly appreciated, this is a major blocker for us to start using container apps.

Ping @SophCarp, @ahmelsayed, @anthonychu, @BigMorty.

**Comment by SophCarp** [comment]
Hi @JonasSamuelsson thanks for your patience. We've made a made a work item for this issue (# 17577362) and the team is discussing how best to solve this issue.

**Comment by jsok** [comment]
Can confirm that this behaviour is surprising and also quite impactful on QoS for users of the app.

In my case the previous revision is running 20-30 replicas and then when a new deployment is made all traffic is diverted to to the sole replica of the new revision.
Given how awfully slow the replica scaling strategy is, traffic and latency doesn't recover for a very long time (6 minutes in my case)!

Having the ability to ensure new revisions start with the same number of replicas as the currently running revision would be very high on my list of "must haves" before comfortably putting real traffic through Container Apps.

**Comment by BigMorty** [comment]
Thanks for pinging on this agian, I have started a discussion with the team about it.

I understand how going from 20-30 replicas to 1 could impact an app, is setting your min replica count something you could do to help in the meantime?

Also, what are the scaling rule(s) you are using for your app?

**Comment by torosent** [comment]
We are working on a fix. ETA: May 2023.

**Comment by jsok** [comment]
Cloud Run has recently implemented this capability: https://cloud.google.com/run/docs/release-notes#April_10_2023

> When [deploying a new revision](https://cloud.google.com/run/docs/deploying#revision), Cloud Run now starts enough instances of the new revision before directing traffic to it. This reduces the impact of new revision deployments on request latencies, notably when serving high levels of traffic.

**Comment by duglin** [comment]
Interesting they don't say what they do about quotas or maxScale. I've seen customer set maxScale to the exact number of licenses they have and scaling beyond that number will have serious impact.

**Comment by JonasSamuelsson** [comment]
@torosent Any update on the state of this?

**Comment by torosent** [comment]
Hi. It's still being worked on but I don't have an ETA yet.

**Comment by JonasSamuelsson** [comment]
Ok, is there a new ETA?

**Comment by revanthgss** [comment]
Hi, any progress on this?

**Comment by JonasSamuelsson** [comment]
Do you have any status update on this?

Ping @torosent, @BigMorty, @anthonychu, @SophCarp.

**Comment by torosent** [comment]
Hi. This is fixed and rolled out to all regions.
