### ISSUE TITLE
Health Probe on container app fails even though containers seem fine

### ISSUE THREAD

**Issue by JonasCordsen** [microsoft/azure-container-apps#639]
> Please provide us with the following information:

> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have a Container Apps Environment with one Container app
The Container Apps Environment is vnet integrated.
There are 3 containers in the container app

After some time of running the load balancer (Deployed by the Container Apps Environment) reports that a health probe is failed.
After that only 2/3 of the health probes answer. It does not come up again.

The containers all work as expected, all 3.

If I do a curl at the health probe I get the following:

curl -Is http://10.119.4.4:32018/healthz
HTTP/1.1 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
Date: Wed, 22 Feb 2023 07:10:39 GMT
Content-Length: 95

curl -Is http://10.119.4.78:32018/healthz
HTTP/1.1 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
Date: Wed, 22 Feb 2023 07:11:14 GMT
Content-Length: 95

http://10.119.4.41:32018/healthz
HTTP/1.1 503 Service Unavailable
Content-Type: application/json
X-Content-Type-Options: nosniff
Date: Wed, 22 Feb 2023 07:11:30 GMT
Content-Length: 95

### Steps to reproduce
1.  Created Container Apps Environment with vnet integration
2. Add container app, with 3 containers in
3. After some time, the load balancer report health probe failure.

**Screenshots**         
![Screenshot 2023-02-22 at 08 29 49](https://user-images.githubusercontent.com/106592722/220552395-1f0cea22-1ce8-4876-80d5-46309a003634.png)

**Comment by cachai2** [comment]
This would require additional details and investigation. Can you open a support ticket with the team?
