### ISSUE TITLE
Feature Request: Container Apps Burst Demo

### ISSUE THREAD

**Issue by runemy** [microsoft/azure-container-apps#642]
**Is your feature request related to a problem? Please describe**.  
Need a tutorial / demo on how to use Azure Container Apps to do burst processing.

**Describe the solution you'd like**.    
Would like to have a tutorial on how to set up Azure Container Apps to do AI Image processing.
Something like this:
- https://github.com/Azure-Samples/virtual-kubelet-aci-burst/issues/9
- https://github.com/Azure-Samples/virtual-kubelet-aci-burst/blob/master/Bursting%20Video.mp4?raw=true

**Additional context**.  
This will makes it easier to show how Azure Container Apps can scale

**Comment by SophCarp** [comment]
Thanks for sharing! There are always more tutorials and resources we want to make. I don't think we have any current plans to make this demo, but we can track it with this issue. 

I know it's not the burst tutorial you'd like, but here'sour basic how-to for scaling in ACA: https://learn.microsoft.com/en-us/azure/container-apps/scale-app?pivots=azure-cli

**Comment by simonjj** [comment]
Closing this, let us know if this is still important by reopening please.
