### ISSUE TITLE
Dapr .Net BulkStore issues

### ISSUE THREAD

**Issue by BC89** [microsoft/azure-container-apps#645]
Should bulksecrets request be working in container apps? 

Using the latest dapr and the code works in my dev container enviroment but not when deployed. Errors out with the following:

at Dapr.Extensions.Configuration.DaprSecretStoreConfigurationExtensions.AddDaprSecretStore(IConfigurationBuilder configurationBuilder, String store, DaprClient client, IReadOnlyDictionary`2 metada`
at Dapr.Client.DaprClientGrpc.WaitForSidecarAsync(CancellationToken cancellationToken)
`

```
public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services, ConfigurationManager configuration)
    {
        var secrets = configuration.GetValue<string>("secretstorename");
        _ = configuration.AddDaprSecretStore(secrets!, new DaprClientBuilder().Build().CreateInvokeHttpClient(), TimeSpan.FromSeconds(20));

        services.AddDaprClient();
```

Thanks!

**Comment by BlackRider97** [comment]
@BC89 Which secret store you are using? We only support and recommend using Azure Key Vault secret store for ACA. 
However, you can also run other 3P secret store as long you have connected with right authN and networking access.  Few secret stores are explicitly disabled for security reasons.

![image](https://github.com/microsoft/azure-container-apps/assets/4725916/24ac860e-0202-4b3b-9a49-698b33df4601)
