### ISSUE TITLE
New revisions keep hanging, when near resource limit, even if there is enough space

### ISSUE THREAD

**Issue by anrub** [microsoft/azure-container-apps#649]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

When reaching near the 40 cores limit, I have the following issues:

1. If you reach this limit, then no additional revisions can be deployed, without any error message - there should be at least some logs or a failed revision - but the additional deployed revision, has no space to deploy, keeps green with no replicas
2. Once the limit is reached, even if you delete apps/revisions - the revisions that were created, while the limit was reached, keep hanging around. The capp-env does not recognize that there are resources again and restart/deploy the hanging revisions. It would be great if these revisions would be processed in a normal way. So that the deployment can work in a sequential manner, even if there is only little room left.

It looks like the previous revision is kept and not deleted, so that the resources for new deployments don't get freed.

### Steps to reproduce
1. Deploy 19 apps a 2 CPUs, so that 38 cores are used
2. Update environment-vars on EVERY app, so that 19 new revisions are created
4. Delete an app or revision - the revisions from  step 2 are still there and are not moving forward
5. Sometimes the deletion triggers some other hanging revisions to deploy again, others keep hanging

**Expected behavior** [What you expected to happen.]

The revisions should be processed, if there are enough resources. e.g. the revisions are created sequentially one after the other.

**Actual behavior** [What actually happened.]

Revisions that were created while limit reached keeps "Provisioned" but without any replicas or logs and dont' start.

**Comment by SophCarp** [comment]
Thanks for reaching out! Please submit a support ticket: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
