### ISSUE TITLE
Long-running executions 

### ISSUE THREAD

**Issue by cmenzi** [microsoft/azure-container-apps#65]
KEDA supports multi strategies on how to handle long running executions: https://keda.sh/docs/2.5/concepts/scaling-deployments/#long-running-executions

a) Is there a way to control the `terminationGracePeriodSeconds` in the ARM, Yaml template?
b) Is it possible to register `postStart` and `preStop` hooks?

Or alternatively: Is there plan to support `Scaled Jobs`: 
- https://keda.sh/docs/2.5/concepts/scaling-deployments/#run-as-jobs
- https://keda.sh/docs/2.5/concepts/scaling-jobs/

**Comment by kendallroden** [comment]
Hey @cmenzi email me at keroden@microsoft.com if you want to give your feedback and provide some requirements as we validate the design

**Comment by somehowadev** [comment]
@kendallroden If you still want some requirements/feedback can send our own too? Have similar requirements for something like Scaled Jobs.

Though do note that it's come up a few times in the repo, so probably have all that you need!

**Comment by kendallroden** [comment]
Please track https://github.com/microsoft/azure-container-apps/issues/526 

@somehowadev - we will reach out if we need futher validation! Thanks for the offer. Feel free to email me so I can pass on to the team.
