### ISSUE TITLE
Creating revision with the same name fails silently.

### ISSUE THREAD

**Issue by hwfbcisod** [microsoft/azure-container-apps#650]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When you create a new revision with the same revision suffix as an already existing, but inactive revision, the operation goes through successfully (as per the notification received), but a new revision is not created and the old one is still inactive. In other words - nothing happens.

### Steps to reproduce
1. Create a container app in multiple active revisions mode.
2. Create an initial revision with the suffix 'foo'.
3. Create another revision with the suffix 'bar'.
4. Make the 'foo' revision inactive.
5. Create a new revision and use the 'foo' suffix again.

**Expected behavior** The revision creation operation should fail with a descriptive notification message.

**Actual behavior** The revision creation operation passes through successfully, but there is absolutely no change in the current state of the container app. A "Sucessfully deployed new revision" message is displayed in the Notifications tab.

**Screenshots**         
N/A

### Additional context
This issue occurs in the Portal. Haven't tried CLI.

**Comment by anthonychu** [comment]
@torosent Is this the expected behavior?

**Comment by simonjj** [comment]
Closing this issue as it seems to have timed out. Please reopen if this is still an issue.
