### ISSUE TITLE
Metrics suddently missing

### ISSUE THREAD

**Issue by cstickel** [microsoft/azure-container-apps#651]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
From the night of the 27.02 to 28.02 around 3am our container apps stopped to report metrics.
Creating new revisions does not fix it, it might be fixed by recreating the whole app or the app environment.

### Steps to reproduce
1. Check the metrics of a container app that was already in place on 27.02. It does not show any metrics anymore.

**Expected behavior** [What you expected to happen.]
Container apps should not suddently stop to report metrics.

**Actual behavior** [What actually happened.]
All our container apps suddently stopped reporting metrics.

**Screenshots**         
![image](https://user-images.githubusercontent.com/1065026/222199303-d13167ac-e512-44bf-892b-288cc5c30008.png)

**Comment by passarela** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/72925771/222245589-4ab2b3fa-a1c5-49e8-b3ad-94eae8dedff9.png)

**Comment by MiLtOnXeZaR** [comment]
I have too

**Comment by grott0** [comment]
Our organization is also affected.

**Comment by paulwood** [comment]
Me too... all containers showing no data in both staging and prod environments. Any chance we can get an update on this one?

**Comment by anthonychu** [comment]
Sorry you ran into this. We have identified the issue and will be rolling out an upgrade addressing this behavior. We'll update this thread with an ETA once we have it.

**Comment by anthonychu** [comment]
The team applied an update to mitigate this issue that completed rollout on March 2 at 15:30UTC.
