### ISSUE TITLE
Unable to create TCP scaling rule via GUI or CLI

### ISSUE THREAD

**Issue by danlambethskyport** [microsoft/azure-container-apps#655]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Creating a TCP scaling rule fails silently. No error is given in the front end or via CLI. 

### Steps to reproduce
1. Create a container app 
2. run the following ``` az containerapp update -n <Container App name> -g <Resource group> --scale-rule-name tcp --scale-rule-tcp-concurrency 100 --scale-rule-type tcp  ```

**Expected behavior** 
Creates A Scaling rule 

**Actual behavior**
Nothing

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by simonjj** [comment]
Tested and this works now, although you need to make sure ingress is set to TCP for your app. Closing issue.
