### ISSUE TITLE
LAW not attached to ACA

### ISSUE THREAD

**Issue by lgmorand** [microsoft/azure-container-apps#66]
I created an environment following the documentation

`az containerapp env create \
  --name $CONTAINERAPPS_ENVIRONMENT \
  --resource-group $RESOURCE_GROUP \
  --logs-workspace-id $LOG_ANALYTICS_WORKSPACE_CLIENT_ID \
  --logs-workspace-key $LOG_ANALYTICS_WORKSPACE_CLIENT_SECRET \
  --location "$LOCATION"`

The creation is successful:

`root@TourPerso:/mnt/e/Repos# az containerapp env create \
>   --name $CONTAINERAPPS_ENVIRONMENT \
>   --resource-group $RESOURCE_GROUP \
>   --logs-workspace-id $LOG_ANALYTICS_WORKSPACE_CLIENT_ID \
>   --logs-workspace-key $LOG_ANALYTICS_WORKSPACE_CLIENT_SECRET \
>   --location "$LOCATION"
Command group 'containerapp env' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "aksResourceId": null,
  "appLogsConfiguration": {
    "destination": "log-analytics",
    "logAnalyticsConfiguration": {
      "customerId": "1142fe52-aaf8-49d1-a750-128a2c85d835\r",
      "sharedKey": null
    }
  },
  "arcConfiguration": null,
  "containerAppsConfiguration": {
    "aciSubnetResourceName": null,
    "appSubnetResourceId": null,
    "controlPlaneSubnetResourceId": null,
    "daprAIInstrumentationKey": null,
    "dockerBridgeCidr": null,
    "platformReservedCidr": null,
    "platformReservedDnsIP": null,
    "subnetResourceId": null
  },
  "defaultDomain": "ashysky-0108c158.northeurope.azurecontainerapps.io",
  "deploymentErrors": null,
  "extendedLocation": null,
  "id": "/subscriptions/6c9dc160-dca4-47cb-9e76-ed16a4b4edb1/resourceGroups/rg-my-container-apps/providers/Microsoft.Web/kubeEnvironments/my-environment",
  "internalLoadBalancerEnabled": null,
  "kind": "containerenvironment",
  "kubeEnvironmentType": "managed",
  "location": "northeurope",
  "name": "my-environment",
  "provisioningState": "Succeeded",
  "resourceGroup": "rg-my-container-apps",
  "staticIp": "40.85.128.245",
  "tags": null,
  "type": "Microsoft.Web/kubeenvironments"
}`

but once in the UI, it says that no LAW is found

![no law](https://user-images.githubusercontent.com/6757079/146918400-840759b3-c4be-49aa-b6a4-7e81ae8dbb8c.png)

I don't know how I can attach my LAW after creation

**Comment by johnnyruz** [comment]
I noticed there is a "\r" at the end of your Log Analytics Customer Id. Can you check how you're setting that variable prior to running the azure cli command?

**Comment by lgmorand** [comment]
nice catch but it does not seem to be the reason or I don't understand how this '\r' could be added. Echoing variables does not show weird. if there is a '\r' in the variable, I don't know how to show it nor when it comes from

![image](https://user-images.githubusercontent.com/6757079/146997767-ec1c9271-f10a-493a-bfe2-67f7dccd83ee.png)

**Comment by johnnyruz** [comment]
I don't see anything obvious either, all those commands there look correct. Can you try running the az containerapp env create command just passing in the CLIENT_ID and CLIENT_SECRET in the command rather than referencing variables just to see if that allows you to link it?

**Comment by lgmorand** [comment]
It seems that there is a known issue if using WSL.
There is indeed a "\r" added automatically but I don't why nor how to get rid of it

`root@TourPerso:/mnt/e/Repos# LOG_ANALYTICS_WORKSPACE_CLIENT_ID=`az monitor log-analytics workspace show --query customerId -g $RESOURCE_GROUP -n $LOG_ANALYTICS_WORKSPACE --out tsv`
root@TourPerso:/mnt/e/Repos# printf '%q\n' $LOG_ANALYTICS_WORKSPACE_CLIENT_ID
$'5a8a2c4e-b770-438b-9575-ea0961e62ffb\r'`
