### ISSUE TITLE
Envoy conflict

### ISSUE THREAD

**Issue by mrentier** [microsoft/azure-container-apps#663]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
My solution runs an Envoy proxy in a container. Recently my Envoy container stopped working in Azure Container Apps, but works in other environments. The error is: 
unable to bind domain socket with base_id=0, id=0, errno=98 (see --base-id option)

Envoy documentation states that this error occurs when more than one instance of Envoy runs within the same host. Am I seeing a conflict here with Envoy instances used by Azure Container Apps? Should I refrain from using Envoy within Azure Container Apps?

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by ahmelsayed** [comment]
/cc @zhenqxuMSFT 

It should be fine to run envoy in ACA. We started running an envoy instance to handle some internal routing scenarios. We should pick a non-default base-id to not conflict with user application.

**Comment by AndrewL97** [comment]
We have recently encountered this issue, and our gateway container app fails to start.

Does MSFT's envoy instance use a particular --base-id to startup?
If it had a set value that we could avoid (either by explicitly setting our own base-id, or using the default of 0), that would be good.

Also, is there documentation on services that run on the containers by default? I had a google around but couldn't find anything relating to this new envoy service :)

**Comment by mrentier** [comment]
I worked around it by setting a base-id on my instance. But it did come as a bit of a surprise.

**Comment by zhenqxuMSFT** [comment]
@AndrewL97 @mrentier I am making a change pick up a non 0, fixed base id for the envoy instance. 

The documentation for the new envoy instance is not ready yet.

**Comment by AndrewL97** [comment]
Thanks @zhenqxuMSFT & @ahmelsayed  !

For my own sanity, was this a recent change? Plus is there somewhere I can monitor for this sort of thing?

This announcement generally lines up with when our issue started -> https://azure.microsoft.com/en-au/updates/generally-available-azure-monitor-integration-with-azure-container-apps/
But I am not sure if that would be the cause, or if that blog is even the correct place to go for news like this :)

**Comment by zioproto** [comment]
Hey folks, should this be documented here ?
https://learn.microsoft.com/en-us/azure/container-apps/networking#http-edge-proxy-behavior

**Comment by ahmelsayed** [comment]
This has been fixed for a while. For envoy we use `--base-id 4141`.
