### ISSUE TITLE
Minimum 100Mb memory limit on container apps

### ISSUE THREAD

**Issue by makhele** [microsoft/azure-container-apps#666]
Currently, the minimum memory of a single container app is 0.5Gi, is the plan to reduce it to 0.1Gi,

Because I have like 8 apps deployed as microservices which are costing like $50 per month for idling only...

**Comment by passarela** [comment]
I agree, I also need this minimum memory adjustment, ideally flexible. Memory does not depend on the CPU.

I have several applications that do not reach 10% use of 0.500mb.

**Comment by simonjj** [comment]
Good news! We now offer a dedicated workload profile which allows you to go lower than 500MB of memory. Would this solve the issue for you guys?

**Comment by passarela** [comment]
> Good news! We now offer a dedicated workload profile which allows you to go lower than 500MB of memory. Would this solve the issue for you guys?

In my case, this would not work, because to use a workload profile, I must review at least one "Dedicated-D4" instance, which has a custom minimum of USD 224,808.

Use only the "Consumption Plan" due to the individual costs of each container.
