### ISSUE TITLE
Feature Request: Prominently Indicate When Provision Status Is Not Provisioned

### ISSUE THREAD

**Issue by simonkurtz-MSFT** [microsoft/azure-container-apps#669]
**Is your feature request related to a problem? Please describe**.  
When my revision does not get provisioned successfully, it is not immediately apparent, especially to unfamiliar users.

**Describe the solution you'd like**.    
I would like to see a prominent banner or indicator, perhaps above the blade content. This indicator should have:

- at least a message about the failed status, and/or
- better, a link to Log Analytics and a suitable query (narrow to container name, etc.), if the Log Analytics Workspace was created with the Container App Environment, and/or
- ideally analyze the issue (hello, OpenAI) and provide means of resolution

**Describe alternatives you've considered**.   
See above. =)

**Additional context**.  
N/A

**Comment by SophCarp** [comment]
Hi @simonkurtz-MSFT thanks for making this request! I'm working on a feature to clarify provisioning and status and include some running statuses. It looks like it will be available by June.

**Comment by simonkurtz-MSFT** [comment]
That's super, @SophCarp! Thank you. I love seeing ACA get better and better.

**Comment by simonjj** [comment]
We've added a running status now also we're looking to make additional changes soonish.
