### ISSUE TITLE
"Roadmap and issues for Azure Container Apps"

### ISSUE THREAD

**Issue by lgmorand** [microsoft/azure-container-apps#67]
Description of the repo says: "**Roadmap** and issues for Azure Container Apps" but there is no roadmap

It could be super cool to have a roadmap project like AKS because ACA is a high-demanded subject right now :)

**Comment by dariagrigoriu** [comment]
Please note we already use the roadmap label to identify items on our roadmap. We will look into a more comprehensive roadmap as we approach general availability.

**Comment by snpdev** [comment]
@lgmorand [A list of issues tagged "roadmap"](https://github.com/microsoft/azure-container-apps/issues?q=is%3Aissue+is%3Aopen+label%3Aroadmap)

**Comment by lgmorand** [comment]
@snpdev the actual list is made of four issues opened by end-users which are features requests which became roadmap, but I'm not sure it contains "our" vision and features that PG has in mind.

But @dariagrigoriu answered my question when talking about a more comprehensive roadmap later. I fully understand that we are far from GA and there is a lot on the plate due to the large interest of people for ACA :)
