### ISSUE TITLE
Cannot select ACR from different subscription using managed identity

### ISSUE THREAD

**Issue by klemmchr** [microsoft/azure-container-apps#671]
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm trying to set up a new revision on an existing container app. When selecting the container registry I get no results.

### Steps to reproduce
1. Create an ACR in Subscription A
2. Create a container app in Subscription B using the HelloWorld image
3. Assign a system-managed identity to the container app
4. Assign `acrpull` role for newly created identity in ACR
5. Create new revision
6. Remove the existing container, add a new one
7. Select Image Source: Azure Container Registry
8. Select Identity: System assigned
9. Click on the Registry dropdown. No results appear.

**Expected behavior**
The dropdown shows the ACR.

**Actual behavior**
The dropdown shows no result.

**Screenshots**         
![image](https://user-images.githubusercontent.com/6552521/225333903-fad838e0-0850-4d9d-aaba-51928cce30f2.png)
![image](https://user-images.githubusercontent.com/6552521/225334569-3e1262a2-6a3b-48ff-aec9-c08a56dbd50c.png)

### Additional context
Azure Portal doesn't work, Azure CLI does

Probably related to #672 since the behavior seems to be the same. Looks like the endpoint for returning the registries causes this error.

**Comment by torosent** [comment]
Hi. It's a bug with the portal but you can do it with the cli or ARM.

**Comment by phcbarros** [comment]
any news about this problem?

**Comment by klemmchr** [comment]
Still happening for me, just like #671, which makes it very inconvenient to create new revisions using the Azure Portal

**Comment by kaganmersin** [comment]
I have same problem with terraform (azurerm v3.79.0). Do we have any deadline for solution ?

**Comment by kaganmersin** [comment]
I have same problem with terraform (azurerm v3.79.0). Do we have any deadline for solution ? I see there is no improvement on the issue for a long time from the comments 
@SophCarp  @anthonychu @torosent

**Comment by ehamai** [comment]
Hey everyone.  Sorry for the delay but thanks for bubbling this up.  Our current target to have this fully deployed to production around beginning of January.

**Comment by klemmchr** [comment]
> Hey everyone.  Sorry for the delay but thanks for bubbling this up.  Our current target to have this fully deployed to production around beginning of January.

Grat to hear, does this also apply to #672 ?

**Comment by KalyanChanumolu** [comment]
> Hey everyone. Sorry for the delay but thanks for bubbling this up. Our current target to have this fully deployed to production around beginning of January.

Thank you. This is a much have functionality for our use case

**Comment by af-vijay** [comment]
Any update on this @ehamai ?

**Comment by ddjmos** [comment]
I can confirm that the workaround suggested by @klemmchr does work - for now.
However, I do not believe this to be the correct way of working when the UI is designed to guide users in their choices. 
I used the ACR and as such would expect to choose ACR and Private for my images as seen in the above UI snippet.

**Comment by klemmchr** [comment]
@anthonychu is there any news on this? Last update was that this will be deployed around the end of January. This issue will have its first anniversary in ten days.

**Comment by alexpkent** [comment]
This workaround does not appear to work any more and after running the az command ACA then fails to pull the image from the Azure Container Registry with a managed identity.

**Comment by klemmchr** [comment]
> This workaround does not appear to work any more and after running the az command ACA then fails to pull the image from the Azure Container Registry with a managed identity.

I cannot confirm that this workaround is not working any more. It works totally fine for me. Double check whether your registry is set correctly and you assigned at least the `AcrPull` role to the identity.

**Comment by klemmchr** [comment]
Apparently this has been fixed silently. While I'm happy that this is finally fixed, it would've been great to be informed about it.
![Untitled](https://github.com/microsoft/azure-container-apps/assets/6552521/7d261598-f803-410e-b880-19fd3498a5f6)
