### ISSUE TITLE
Registry login server is not saved using private registry

### ISSUE THREAD

**Issue by klemmchr** [microsoft/azure-container-apps#672]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Due to #671 I am forced to use username and password for authentication with ACR. When setting the required credentials while editing a revision these changes *appear* to not be saved properly.

### Steps to reproduce
1. Create container app with HelloWorld container
2. Edit revision and container
3. Select Image source: Docker Hub and other registries
4. Select Image type: Private
5. Add some registry login server
6. Enter some image and tag
7. Save revision
8. Edit revision and container
9. The registry login server dropdown is empty

**Expected behavior**
The previously saved registry login server is shown

**Actual behavior**
No entry shown

**Screenshots**         
![image](https://user-images.githubusercontent.com/6552521/225358949-624b21db-76a8-4585-8494-d03810723460.png)
![image](https://user-images.githubusercontent.com/6552521/225360798-9c1b9862-1b1d-4eda-a460-44193952be1a.png)

### Additional context
Azure Portal does not work, CLI does

Every time after saving the new revision a new secret with the registry password is created.

During observation of networking I noticed that the request to `WebsitesExtension.GetRegistries` returns an empty array.  
The request to `WebsitesExtension.GetContainerAppInfo` returns proper configuration, `properties.configuration.registries` has a single item containing the previously saved registry information.

**Comment by vanmash** [comment]
what's the status, @anthonychu
