### ISSUE TITLE
Container App Environment stuck in provisioning state 'ScheduledForDelete'

### ISSUE THREAD

**Issue by michielpeeters** [microsoft/azure-container-apps#674]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm trying to delete an container app environment resource, however this environment keeps stuck on ScheduledForDelete and I have no option to force the deletion.

### Steps to reproduce
It's difficult to reproduce. I have this problem now and I can't understand why this is happening and how it happened.

**Expected behavior**
The container app environment should have been deleted succesfully via portal (or cli or powershell).

**Actual behavior**
The container app environment is not deleted and stuck in the provisioningState: ScheduledForDelete

**Screenshots**         
![image](https://user-images.githubusercontent.com/22633564/225466208-bf7ee97e-7858-488b-b03e-7ea653d92e7b.png)

### Additional context
This issue started to occur when executing the delete via the Portal. After that I tried multiple times via the Portal, CLI, Powershell but nothing worked.

**Comment by michielpeeters** [comment]
I was now able to delete the component on a creative way. Somehow the move resource component within azure accepted to move this faulty resource to another resource group. By this the resource component was completely vanished. The only thing I needed to wait for is that the resource groups return back to its original state and voila, all was cleaned :-).

**Comment by onionhammer** [comment]
Seems like this is an issue though that you didn't fix, so we should keep this open. I've been waiting for an ACA environment to be deleted for over an hour.

**Comment by thierrydecae** [comment]
Hi, I'm still having the same issue, is the above the only fix?

**Comment by lonux999** [comment]
Hello,

is there any solution to this. 
I am running into the same issue and currently we a stuck!

**Comment by rpetersson** [comment]
Same issue...

**Comment by mobi-pedroestanislau** [comment]
Same issue. I have seen the following troubleshooting  [troubleshooting ](https://learn.microsoft.com/en-us/azure/container-apps/troubleshooting?tabs=bash#manually-delete-the-vnet-being-used-by-the-azure-container-apps-environment) suggestion but it is a joke. I cannot delete my VNET.

**Comment by lukaferlez** [comment]
We have the same problem with two environments, one with "ProvisioningState" = "Failed" & another with "ScheduledForDelete".

It never gets deleted these environments have been 'deleted' two days ago now, both through the portal & cli, both report 'success', however the environments are still there.

Can't really delete the entire VNET.

**Comment by hlavacek87** [comment]
Same issue ...

**Comment by mobi-pedroestanislau** [comment]
I was able to delete the CAP ENV by removing the delete lock on my VNET

**Comment by chrispangg** [comment]
any update? Same issue here too

**Comment by chrispangg** [comment]
> any update? Same issue here too

fixed it by removing locks on the VNET resources i.e. subnet, vnet and nsgs - thanks @mobi-pedroestanislau!
