### ISSUE TITLE
Calls to http://127.0.0.1/dapr/subscribe are failing with status code 404

### ISSUE THREAD

**Issue by brbarnett** [microsoft/azure-container-apps#676]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
As of 3/14 at around 3-4am Eastern, many or all calls to `GET /dapr/subscribe` began failing in all of our container apps environments. Prior to this time, it very rarely happened. After this date, we're seeing a few hundred of these logged in App Insights every 12 hours.

This is an example of our prod App Insights:
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/6238678/225702464-a9a34bb2-8a58-4f6c-9a01-3bdb4b19023a.png">

The pattern of timing and volume is very similar in all 3 of our environments, suggesting that it wasn't any of our changes that created this issue.

### Steps to reproduce
N/A

**Expected behavior** [What you expected to happen.]
N/A

**Actual behavior** [What actually happened.]
N/A

**Screenshots**         
Shared above

### Additional context
Dapr appears to still be functioning in our environments, but I'm concerned there's something going on that I'm not aware of.

**Comment by SophCarp** [comment]
Thanks for the clarification. @greenie-msft can you look into this?

**Comment by alexbot89** [comment]
Our environment is also encountering this issue, I tried to restart and recreate the revision but the issue persists.

**Comment by greenie-msft** [comment]
@brbarnett @alexbot89 

Are you still encountering this behavior?

**Comment by alexbot89** [comment]
Looks resolved on my side, app insights is all green.
