### ISSUE TITLE
Exec lifecycle hook ([/bin/sh /wait_ready.sh]) for Container "k8se-envoysc" in Pod

### ISSUE THREAD

**Issue by sleekflowleochoi** [microsoft/azure-container-apps#677]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

Exec lifecycle hook ([/bin/sh /wait_ready.sh]) for Container "k8se-envoysc" in Pod "sleekflow-wh-app2b58762d--nyferx2-7d6694bbfd-ks96l_k8se-apps(fdc5fab4-8e1f-484b-9069-096cc182105e)" failed - error: command '/bin/sh /wait_ready.sh' exited with 124: , message: ""

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

All containers in my environment are unable to serve all traffics. Seems not related to my containers.

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by SophCarp** [comment]
Hi @sleekflowleochoi I'm having some trouble parsing this. Could you please describe the issue?

**Comment by sleekflowleochoi** [comment]
All containers in my environment are unable to serve traffics. But I can confirm it is not related to my containers. It is related to the envoy controller that is controlled by Azure Container Apps.

**Comment by SophCarp** [comment]
Ah, thank you for the clarification! @cachai2 can you look into this?

**Comment by torosent** [comment]
@sleekflowleochoi , Can you confirm if this is still happening? If so, please send us all the details including sub id and env name to `acasupport at microsoft dot com`

**Comment by sleekflowleochoi** [comment]
All good now. Thank you.

I submitted the support ticket in Azure. The engineer said it is related to there are too many revisions for the apps and caused the envoy controller unable to start. And after the fix was applied, no issue again.

The temporary mitigation I applied is to create a new environment and deploy all my container apps there, so @ahmelsayed you see the app is removed.
