### ISSUE TITLE
Feature Request: Make MC_ node resource group name changeable

### ISSUE THREAD

**Issue by Geertvdc** [microsoft/azure-container-apps#678]
When deploying an Azure container app environment with vnet connection an extra resource group is created with the name `MC_######`. In a lot of enterprises there are naming policies on resource groups so it would be nice to be able to change this name in the same way that this is possible in AKS.

I would like to be able to give a custom name to this resource group like we can do with AKS
AKS example:
`az aks create --name myAKSCluster --resource-group myResourceGroup --node-resource-group myNodeResourceGroup`

Since Container Apps is using AKS in the background maybe you could make use of this AKS feature in container apps as well?

**Comment by andrekiba** [comment]
Why the resources that are inside the MC_ resource group cannot be created inside the resource group where everything else is?? What happens if I need to move the container app from one subscription to another one?

**Comment by simonjj** [comment]
We currently don't support the changing of the RGs unfortunately. There are no immediate plans to support this.
