### ISSUE TITLE
Custom domains are cleared when updating ingress via Azure CLI

### ISSUE THREAD

**Issue by fabiankaimer** [microsoft/azure-container-apps#681]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When using the `az containerapp ingress enable` command (in my case I call it from my devops pipeline) to update my pre-existing ingress, my manually assigend custom domains are cleared. This issue seems pretty similar to that one: [Issue 234](https://github.com/microsoft/azure-container-apps/issues/234). However, it does only occur on when using `az containerapp ingress enable`.

### Steps to reproduce
1. Create a containerapp and add a custom domain
2. Update containerapp ingress via `az containerapp ingress enable`, e.g.:
```
az containerapp ingress enable \
          -n $(guiContainerAppName) \
          -g $(resourceGroup) \
          --type internal \
          --target-port 80
```
3. Check custom domains

**Expected behavior** [What you expected to happen.]
I would have expected the custom domains do not be wiped when updating the ingress via Azure CLI.

**Actual behavior** [What actually happened.]
The custom domains are wiped when updating the ingress via Azure CLI.

### Additional context
The output of `az --version`:
```
az --version
azure-cli                         2.46.0

core                              2.46.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/[USERNAME]/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Mar  6 2023, 09:39:14) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by SophCarp** [comment]
We now have the "az containerapp ingress update" command which only changes the affect the mentioned properties! This command won't wipe your custom domains. Thanks for bringing up this issue!
