### ISSUE TITLE
Regional deployment of the service "Azure Container Apps" in Central India region

### ISSUE THREAD

**Issue by dhpaliwa** [microsoft/azure-container-apps#684]
> Please provide us with the following information:
> -------------------------------- 

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

- As per Product availability Roadmap tool GA date for the service was May 2022, but the service hasn't GA yet (refer screenshot below). We wanted team's help in revised ETA for the asked service. Accordingly, we can signal this to the customers (in India) who have the service’s requirement.

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

![image](https://user-images.githubusercontent.com/128451079/226525769-7b3fc992-bed0-43e2-99c6-45b75e145b54.png)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

Product availability roadmap tool needs update with new ETA for the service's deployment in Central India region.

**Comment by simonjj** [comment]
Central India is now a supported region. Please check regional availability via `az provider show --namespace Microsoft.App --query "resourceTypes[?resourceType=='managedEnvironments'].locations"`. We've also updated the official marketing pages now. Closing this issue.
