### ISSUE TITLE
Cannot deploy a new revision without any traffic assigned to it

### ISSUE THREAD

**Issue by JefSchraag** [microsoft/azure-container-apps#688]
### This issue is a
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I can't deploy a new revision that gets 0% traffic assigned to it using a Bicep template.

The goal is to deploy pull requests builds that will only be accssible through the revision URL, i.e. with 0% traffic assigned to them, just like asked in issue #4

Issue #4 is resolved but I would like to achieve the same thing with Bicep, however all the traffic configuration varieties I tried have not resulted into a new revision without any traffic assigned to it.

**Expected behavior** [What you expected to happen.]

The new revision is deployed (and active) and it has 0% traffic assigned to it

**Actual behavior** [What actually happened.]

When I specify:

```bicep
        traffic:[
          {
            latestRevision:true
            weight:100
          }
          {
            revisionName: myNewRevisionName
            weight:0
          }]
```

or 

```bicep
        traffic:[
          {
            latestRevision:true
            weight:100
          }]
```

or 

ommit the `traffic:` element

Then 100% gets assigned to the new revision I'm publishing

when I specify:

```bicep
        traffic:[
          {
            revisionName: myNewRevisionName
            weight:0
          }]
```

or

```bicep
        traffic:[]
```

I get an error that the traffic elements must add up to 100. I understand that I could fix that problem by explicitly including the existing revision(s) but the revision names for those are not easily available. It would make more sense to me that `weight:0` elements are just added to the existing traffic list since they will not affect the existing traffic splitting anyway.

**Comment by ahmelsayed** [comment]
Unfortunately that's not possible in bicep. If you want to persist a state, you'll need to set that state in your bicep template. The `latestRevision: true` semantic is a way around that to be able to refer to the latest created revision.

If you want to persist a state that the system produced, i.e: the unknown existing revision, you will need to do a GET, then update your PUT payload. You can always resolve what revision `latestRevision: true` is referring to by calling `az containerapp show -n {} -g {} --query properties.latestReadyRevisionName`
