### ISSUE TITLE
Feature Request: execute commands in containers non-interactively

### ISSUE THREAD

**Issue by daseth** [microsoft/azure-container-apps#689]
**Describe the solution you'd like**.    
Ideally the **az containerapp exec** command should support a --non-interactive flag to allow running commands from inside a container running on ACA programatically

**Describe alternatives you've considered**.   
None

**Comment by simonjj** [comment]
Can you please share more why you want to this functionality please?

**Comment by Trueber** [comment]
My use case would be to trigger configuration updates from CI without restarting the container (e.g. nginx)
