### ISSUE TITLE
Replica resources (CPU, memory) have significantly increased in all of our environments suddenly as of 3/22 4am ET 

### ISSUE THREAD

**Issue by brbarnett** [microsoft/azure-container-apps#690]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
As of 3/22 4am ET our CPU and memory on our apps have gone up considerably, which has caused our services to auto-scale. We have not deployed any new code to UAT or Prod since 3/7, and we have seen other regression issues introduced around 4am ET which leads me to believe that this is the ACA release window. My guess is that something has been deployed that has destabilized at least some environments.

### Steps to reproduce
N/A

**Expected behavior** [What you expected to happen.]
N/A

**Actual behavior** [What actually happened.]
N/A

**Screenshots**         
#### Prod environment
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/6238678/227007325-3b6cb3ba-1197-4641-b723-b9184e6215f7.png">

#### UAT environment
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/6238678/227007524-78b24e93-bc4b-43ba-ae51-041091a756bf.png">

#### Dev environment
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/6238678/227007444-85429b9c-8933-40f9-ac36-7437b15ce61c.png">

### Additional context
Portal, all 3 of our container environments

**Comment by torosent** [comment]
Dapr 1.10.4 with the memory leak fix is deployed to all regions.
