### ISSUE TITLE
Auto exposing ACR password on the ACA

### ISSUE THREAD

**Issue by ayxano** [microsoft/azure-container-apps#692]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When deploying container app with ACR through azure command line, it automatically add ACR's password to the container's secret. 
Instead of using azure cli, when using azure portal, the password of ACR will not be added to the secrets section of container app.
Everyone who have access to the container app, can read the ACR password.

`az containerapp create --name ${BITBUCKET_REPO_SLUG} --resource-group $BITBUCKET_BRANCH --image "${IMAGE}:${VERSION}" --ingress external --min-replicas 1 --transport auto --target-port 80 --memory 1.0Gi --cpu 0.5 --environment container-apps-environment-${BITBUCKET_BRANCH} --system-assigned --registry-server "XXXXXXXX.azurecr.io" --tags environment=$BITBUCKET_BRANCH`

```
No credential was provided to access Azure Container Registry. Trying to look up credentials...
Adding registry password as a secret with name "XXXXXXXX-XXXXXXXXX"
```

### Steps to reproduce
1. After deploying container app, it should remove the ACR password OR it should not store the ACR password as secret to the container app during deployment.

**Expected behavior** [it should not store the ACR password as secret to the container app during deployment with CLI]

**Actual behavior** [it stores the ACR password as secret to the container app during deployment with CLI.]

**Screenshots**         

### Additional context
Did this issue occur in the CLI or the Portal?
Answer: CLI

**Comment by torosent** [comment]
Hi, 
I understand you concern. 
1. This can be managed by RBAC on the container app level. For example, you can assign users `ContainerApp reader` role and then they won't be able to do read secrets. We can introduce new roles that will provide better granularity to control this but you can also do this today by creating custom roles.
2. The recommended way to access ACR is by Managed Identity and not by password.

**Comment by ayxano** [comment]
> Hi, I understand your concern.
> 
> 1. This can be managed by RBAC on the container app level. For example, you can assign users `ContainerApp reader` role and then they won't be able to do read secrets. We can introduce new roles that will provide better granularity to control this but you can also do this today by creating custom roles.
> 2. The recommended way to access ACR is by Managed Identity and not by password.

Hi there. Can you provide me an example of Managed Identity deployment to ACA using azure CLI? Any resource, any documentation I appriciate. Thanks.

**Comment by pagariyaalok** [comment]
https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=cli%2Cdotnet

**Comment by simonjj** [comment]
You can now use MI for the full end to end process please see here for details: https://learn.microsoft.com/en-us/azure/container-apps/managed-identity-image-pull?tabs=bash&pivots=console
