### ISSUE TITLE
Multiple idle apps with nearly identical cpu/memory have wildly different CPU nanocore usage

### ISSUE THREAD

**Issue by onionhammer** [microsoft/azure-container-apps#693]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have three different apps, two of them idle at around 7-9 m cores, and one around 2.89 m cores, however when I pop open the live metrics from application insights, none of the apps is currently handling any requests, all are sitting idle at 0 req/sec, 0-1% cpu usage, ~350mb, 2 instances each.

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         
App A:
![image](https://user-images.githubusercontent.com/969938/227381357-44130f7d-51b4-436f-9068-a002b034ee29.png)
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/969938/227381509-56217d45-3404-42d2-9c54-a9e93bca05d3.png">

App B:
![image](https://user-images.githubusercontent.com/969938/227381635-a35e86a1-3484-4381-8084-a9185e931dfa.png)
<img width="1742" alt="image" src="https://user-images.githubusercontent.com/969938/227381692-34daf792-ac3a-42f7-999b-fa75fbc461d8.png">

### Additional context
App A has Dapr enabled, App B does not, other than that they are set up almost identically

**Comment by torosent** [comment]
Hi,

It relates to this issue https://github.com/dapr/dapr/pull/6130

We are rolling a hotfix for it. 
Note that you are not billed for the daprd sidecar.

**Comment by onionhammer** [comment]
@torosent Even when dapr isnt enabled?

**Comment by torosent** [comment]
Ok. I miss read that. We will need to investigate more. Please send me the details to  `acasupport at microsoft dot com`

**Comment by simonjj** [comment]
Closing this, if this issue persists please reopen or a create new one and link to this.
