### ISSUE TITLE
Feature Request: Better APIM Integration

### ISSUE THREAD

**Issue by alexbot89** [microsoft/azure-container-apps#694]
**Is your feature request related to a problem? Please describe**.  
Our current solution is ACA with managed VNET, traffic is going through APIM (Dev SKU) and being funneled into 1 Container App with an IP Restriction. This works but I am worried about SNAT port exhaustion from the APIM as well as having the request go through the Internet before resolving back into the Microsoft network.

**Describe the solution you'd like**.    
A better solution for APIM integration with ACA especially with non-custom VNET, perhaps something in the Portal that allows us to link the APIM to an ACA environment where the APIM can access all the container apps natively, perhaps some private link or vnet peering behind the scenes.

**Describe alternatives you've considered**.   
1. A workaround I've considered is to manually shard the Container App that manages the input traffic from APIM then load balance through that, but that requires additional Container Apps to actually be created.
2. Restart from scratch and make a custom VNET for both APIM and ACA, not possible at the moment as we have this in prod it would be incredibly disruptive.
3. Put a NAT gateway in the APIM VNET, not able to do this, VNET is only available for APIM Premium SKU.

**Comment by cachai2** [comment]
Thanks for the feedback @alexbot89. If you're using APIM and ACA in the same region, the traffic will stay within Azure infrastructure. However, if you need a more private connection, you will need to use a custom VNet. We don't currently have plans to allow private integration with a non-custom VNet.
