### ISSUE TITLE
DeploymentScriptContainerGroupCreationFailed

### ISSUE THREAD

**Issue by codehunter13** [microsoft/azure-container-apps#695]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Sometimes, during our bicep deploys, we got the following error. Not always on the same scripts
```
Exception of type 'Microsoft.Azure.Blueprint.ResourceProvider.Shared.CommonJobs.DeploymentScriptContainerCreationException' was thrown. (Code: DeploymentScriptContainerGroupCreationFailed)
```

**Screenshots**         
![image](https://user-images.githubusercontent.com/7559059/227613244-c122c913-8565-4718-b26c-252cc4ea4674.png)

**Comment by torosent** [comment]
Hi, I created a case for the oncall engineer.

**Comment by howang-ms** [comment]
@codehunter13, could you please share more information to the acasupport@microsoft.com?
Including:
1. The ContainerApp or Container App Enviorment name you try to operate.
2. Your subscription id
3. The target region you are doing the operation.

**Comment by boylec** [comment]
We're seeing the same thing intermittently

**Comment by howang-ms** [comment]
Hi @boylec,
I would appreciate it if you could share more information with acasupport@microsoft.com. The DeploymentScriptContainerGroupCreationFailed is a general error from the deployment script, without enough detail it will hard for us to know where the error comes from.

**Comment by boylec** [comment]
> Hi @boylec, I would appreciate it if you could share more information with [acasupport@microsoft.com](mailto:acasupport@microsoft.com). The DeploymentScriptContainerGroupCreationFailed is a general error from the deployment script, without enough detail it will hard for us to know where the error comes from.

Will do

**Comment by torosent** [comment]
Not related to ACA
