### ISSUE TITLE
Key Vault support for secret management

### ISSUE THREAD

**Issue by takekazuomi** [microsoft/azure-container-apps#7]
I want it to have a mechanism like App Services KeyVault Reference.

https://docs.microsoft.com/en-us/azure/container-apps/secure-app?tabs=arm-template
Do you have any plans?

**Comment by takekazuomi** [comment]
Or should I use Dapr's Secret Management? In that case, I think that it is configured with daprComponents. Is there an example of how to write it?

https://docs.dapr.io/reference/components-reference/supported-secret-stores/azure-keyvault/#authenticating-with-azure-ad

**Comment by tomkerkhove** [comment]
Or have both being supported? That would be nice!

**Comment by vturecek** [comment]
@takekazuomi are you looking to be able to store secret references in a Key Vault that you own (in your subscription)? For example, if we had a config setting that allowed you to specify your own Key Vault as the backing secret store for secrets in a Container App, would that work for your scenario?

**Comment by takekazuomi** [comment]
> if we had a config setting that allowed you to specify your own Key Vault as the backing secret store for secrets in a Container App, would that work for your scenario?
Is this something like the Azure Key Vault Provider for Secrets Store CSI Driver?
https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
This is a bit cumbersome to handle, but I think it can be used.

In the current scenario, we need to be able to limit the key vault containers that can be accessed for each container.
Each container has its own secret, which is stored in a separate key vault container. There is also a container common secret, which is stored in a shared key vault.
In App Service, we used system-assigned identity and key vault references in these scenarios.

**Comment by takekazuomi** [comment]
Another idea.
I find it useful to use App Configurations as a backing store for configurations, but it's a bit expensive.

**Comment by ezYakaEagle442** [comment]
In ACA you can assign several User-Assigned Identities to your App, then  how to use Dapr Secret store / Azure KV + AAD Workload-Identity ?

see also [https://github.com/dapr/docs/issues/2952](https://github.com/dapr/docs/issues/2952)

**Comment by onionhammer** [comment]
This would be great.

When using IaaC with ARM, you have to define that secret in your arm/bicep file, it cannot be omitted, or future deployments of the infrastructure will fail; "SecretRef 'graphapi-secret' defined for container 'xxx' not found."

To workaround this, you could store the secret in the key vault, then get the secret value at the time of deployment, but then you are basically storing the secret in the key vault anyways and enabling template access to secrets on the vault (not ideal), this feature would shortcut that whole process.

**Comment by thomas-vercoutre-nzta** [comment]
I feel like the service connector could be used in this case?
https://learn.microsoft.com/en-us/azure/service-connector/how-to-integrate-key-vault?tabs=container-apps

**Comment by onionhammer** [comment]
@CrazyTuna looks promising... but I don't see any documentation on how to actually use it, just info that says it's supported.

**Comment by maskati** [comment]
App Configuration service, Dapr and Service Connectors are all implementation specific. The nice thing about App Service Key Vault references is that they are application agnostic and require no additional implementation effort. You just read the correct environment variable that has been magically replaced by the hosting platform, using the application identity, with the referenced Key Vault secret value.

**Comment by onionhammer** [comment]
@maskati agreed, it's a much better solution to what is available with ACA

**Comment by maskati** [comment]
Mock of a poor man's Container App key vault references (secret resolution in the container command by replacing `@Microsoft.KeyVault` environment variables with the corresponding secret using system assigned managed identity):

```bicep
param location string = resourceGroup().location

resource keyVault 'Microsoft.KeyVault/vaults@2022-07-01' = {
  name: 'kv-${uniqueString(resourceGroup().id)}'
  location: location
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: tenant().tenantId
    enableRbacAuthorization: true
  }
}

resource keyVaultSecret 'Microsoft.KeyVault/vaults/secrets@2022-07-01' = {
  name: 'mysecret'
  parent: keyVault
  properties: {
    value: 'a big secret!'
  }
}

var keyVaultSecretsUserRoleDefinitionId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')
var keyVaultSecretsUserRoleAssignmentName = guid(keyVault.id, containerApp.id, keyVaultSecretsUserRoleDefinitionId)
resource keyVaultSecretsUserRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: keyVaultSecretsUserRoleAssignmentName
  scope: keyVault
  properties: {
    roleDefinitionId: keyVaultSecretsUserRoleDefinitionId
    principalType: 'ServicePrincipal'
    principalId: containerApp.identity.principalId
  }
}

resource containerAppEnvironment 'Microsoft.App/managedEnvironments@2022-06-01-preview' = {
  name: 'cap-env'
  location: location
  properties: {
    appLogsConfiguration: {
      destination: null
    }
  }
}

resource containerApp 'Microsoft.App/containerApps@2022-06-01-preview' = {
  name: 'cap-app'
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    managedEnvironmentId: containerAppEnvironment.id
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 80
        transport: 'auto'
      }
    }
    template: {
      containers: [
        {
          name: 'alpine'
          image: 'docker.io/alpine:latest'
          env: [
            {
              name: 'TestKeyVaultReference'
              value: '@Microsoft.KeyVault(SecretUri=${keyVaultSecret.properties.secretUriWithVersion})'
            }
          ]
          command: [
            '/bin/sh'
            '-c'
            #disable-next-line no-hardcoded-env-urls
            'apk update && apk add curl && apk add jq && for ev in $(env); do if expr \${ev#*=} : "@Microsoft.KeyVault" > /dev/null; then export "\${ev%%=*}"="$(curl -s -H "Authorization:Bearer $(curl -s -H X-IDENTITY-HEADER:\${IDENTITY_HEADER} \'http://localhost:42356/msi/token?api-version=2019-08-01&resource=https://vault.azure.net\' | jq -r \'.access_token\')" "$(echo \${ev#*=} | sed \'s/.*SecretUri=\\([^)]*\\).*/\\1/\')?api-version=7.3" | jq -r \'.value\')"; fi; done && env && while true; do echo -e "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\n$(env)" | nc -l -p 80; done'
          ]
          args: []
          resources: {
            cpu: json('0.25')
            memory: '0.5Gi'
          }
        }
      ]
      scale: {
        minReplicas: 0
        maxReplicas: 1
      }
    }
  }
}
```
Results in (you may need to restart the revision due to RBAC propagation delay):

![image](https://user-images.githubusercontent.com/21118898/211296656-e72560fe-6ddb-4b8f-9387-624a21a8bdb1.png)

**Comment by cemerick** [comment]
Thanks for spitballing that! I ended up incorporating something similar (tho a little less clever perhaps) into our startup script, and it's working well enough until real support lands (soon, hopefully!).

**Comment by ryantk** [comment]
@maskati I have considered doing that, does this also populate the env variables for when I am using the "console" from within the container apps panel within the azure portal?

**Comment by torosent** [comment]
https://learn.microsoft.com/en-us/azure/container-apps/manage-secrets?tabs=azure-portal#reference-secret-from-key-vault
