### ISSUE TITLE
Support for setting Dapr App Protocol to gRPC 

### ISSUE THREAD

**Issue by kendallroden** [microsoft/azure-container-apps#70]
Dapr implements both an HTTP and a gRPC API for local calls. gRPC is useful for low-latency, high performance scenarios and has language integration using the proto clients. 

In order to tell Dapr to use gRPC to talk to an application, a user must be able to specify the app protocol as grpc vs. the default of http. 

Currently in Container Apps, we support setting a transport of http2 in the ingress configuration, but need to ensure we include the app protocol within the dapr configuration in order to enable Dapr + gRPC within Container Apps

**Comment by XavierGeerinck** [comment]
Note: currently the Python SDK is unusable due to this issue

https://github.com/dapr/python-sdk/issues/347
https://github.com/dapr/python-sdk/issues/342

**Comment by ChrisProlls** [comment]
Any news on this ?

**Comment by kendallroden** [comment]
It is available @ChrisProlls
