### ISSUE TITLE
Logs for Container App missing

### ISSUE THREAD

**Issue by cstickel** [microsoft/azure-container-apps#700]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
One of our Container Apps doesn't show most of the log entries in Azure Monitor (`ContainerAppConsoleLogs_CL`). However the logs are shown perfectly fine in the "Log stream". It's also working fine for all of our other container apps. What makes this even more strange is, that we have the same container app configuration in two resource groups (staging and production) and it's only broken in one of them. They use the same terraform code to deploy and the exact same image. Deleting the Container App and redeploying also didn't fix the issue.
A few of the logs were even logged, but they were missing the first part and therefor invalid json.
![image](https://user-images.githubusercontent.com/1065026/228337442-13494d5d-bbcf-435f-a4b9-bafbd2132753.png)

`stderr` seems to work fine. also some other logs. for the non working logs `Stream_s` is empty and not showing `stderr` or `stdout`

### Steps to reproduce
Unsure how to reproduce, because it's only affecting one instance.

**Expected behavior** [What you expected to happen.]
Logs that are shown in "Log stream" should also reliably appear in `ContainerAppConsoleLogs_CL`.

**Actual behavior** [What actually happened.]
One of the container apps doesn't show the logs reliably in `ContainerAppConsoleLogs_CL`.

**Comment by ekjuanrejon** [comment]
having same issue

**Comment by WolfspiritM** [comment]
Any news? We're having the same issue. For us it's two of our apps.

It's actually happening to the first two apps we deployed. It's possible that Logging to Log Analytics wasn't set up back then when they were deployed and updated afterwards. Could that be the reason?

**Comment by sanchitmehta** [comment]
Could you please share your environment resource id at acasupport[at]microsoft.com ?

**Comment by xwang971** [comment]
Hi @cstickel sorry for the delay. Do you still see this problem? If yes can you please provide the information of the containerapps(both working one and non-working one): containerapp name, region, subscriptionId?

**Comment by hmg-hholland** [comment]
Hi @xwang971
I will take over for @cstickel . It now affects two services at our end as well. How should I transmit the requested data?

**Comment by xwang971** [comment]
@hmg-hholland Hi, can you please send the information to acasupport@microsoft.com please?

**Comment by Torgeir-Hansen** [comment]
We are seeing a similar issue in our deployment, at least one container app has log entries that are visible in the log stream - but they fail to end up in log analytics.
There seems to be a correlation between messages that do and do not end up in log analytics, unfortunately the error messages are omitted 😬

**Comment by hmg-hholland** [comment]
It seems that the [custom column limit](https://learn.microsoft.com/en-us/azure/azure-monitor/service-limits#log-analytics-workspaces:~:text=in%20a%20table-,500,-Maximum%20characters%20for) in the Log Analytics workspace table `ContainerAppConsoleLogs_CL` is reached. We didn't figure out how to fix the issue though.

**Comment by xwang971** [comment]
@cstickel Hi, really sorry for the delay. We were adding metrics to the environment and found there were no logs dropped there and yes you are right the reason why the logs are missing is because of the limit of the number of table columns since we are now parsing the output and allocate different columns for each key. Could you try sending everything to azure monitoring instead of log analytics for mitigation please? We'll work on the fix for the limit issue and would update here once there's update.

**Comment by cstickel** [comment]
@xwang971 as said in our staging environment there are no logs dropped anymore, since we recreated the log analytics workspace table `ContainerAppConsoleLogs_CL` which is broken since then.
![image](https://github.com/microsoft/azure-container-apps/assets/1065026/91fb8121-cd97-4009-8e27-503fefc347b5)
so since a week the `edit schema` link is disabled, and it did not inherit the retention and plan from the workspace
![image](https://github.com/microsoft/azure-container-apps/assets/1065026/428701b3-dafb-4bee-b8d7-8c8c2d06591b)
also it logs each log entry, but most columns are empty.
it's not even showing data in columns like `ContainerName_s` which should be filled always for container apps:
![image](https://github.com/microsoft/azure-container-apps/assets/1065026/47eaa576-6186-4b38-b7ed-713a923ecb09)

you can see in the operation table, that before we recreated the table there were actually logs dropped:
![image](https://github.com/microsoft/azure-container-apps/assets/1065026/18fc186f-bdf8-4df7-84fe-a519959d6d79)


but actually on the other (production) resource group, we still get logs dropped, because we manually deleted columns in the `edit schema` which should not be used. but instead of getting deleted, they were converted from `Custom Columns` to `Azure Columns` which are not deletable.
![image](https://github.com/microsoft/azure-container-apps/assets/1065026/7c17ccc8-0629-4e1e-8f30-c0522d389611)

this is even more concerning for us, because that's our production environment.

however, i can turn azure monitor logging on, on our staging environment, if that helps to figure out the problem, why there is data in most columns missing. didn't know that this option even exists... is this new? as far as i remember last year log analytics workspace was required for container app environments.

if i change it to azure monitor, do you have any requirements to which sources we send the data, or is it fine to just switch to `Azure monitor` in `Logging options` and then select again analytics workspace as target in diagnostic settings?

**Comment by xwang971** [comment]
Hi, @cstickel, the logs from our end look good with all the required information like containerappName, environmentName, could you check with log-analytics team please?

To configure azure monitoring, yes you can select again analytics workspace as target in diagnostic settings. The only difference here is that azure monitoring as a middleware would format the logs in the certain way so that no new columns would be added. And it would forward logs to log-analytics table ContainerAppConsoleLogs(**without _CL**)

**Example:**
![image](https://github.com/microsoft/azure-container-apps/assets/79332479/9db9f544-61e1-46b0-8574-485495e529fb)

The log contains the whole line of log even it's in json format without parsing into new columns. This would mitigate the issue.

Again we are sorry for the inconvenience and working on fixing the issue directly sending logs to log-analytics. We would update here where there's progress.

**Comment by cstickel** [comment]
@xwang971 thanks for the info, we weren't aware of the new logging configuration. it's pretty new, isn't it?
changed our staging environment and that works perfectly fine so far. we need some more time to test it and also deploy it to our production environments and then we'll give feedback.
so far the new solution with logs configuration through diagnostic settings looks conceptionally much better than the old one, and more aligned with the other azure products.

we'll give feedback if the issue is finally fixed for us until end of the week. thanks for all the support!

**Comment by xwang971** [comment]
@cstickel Thanks for the feedbacks! Please let us know if there's any update/issue.

**Comment by cstickel** [comment]
@xwang971 is there any specific size limit for logs? first impression is, that it works a lot better, but for quite large json objects (3k+ byte) the logs are missing. it's not an issue, we can just reduce the amount of information, but would be nice to know if there is any limit we should know about.

**Comment by cstickel** [comment]
with the change to azure monitor all problems seem to be fixed. couldn't find any situation with missing logs anymore.

so from my point of view, the issue can be closed.
@ekjuanrejon 
@WolfspiritM 
@Torgeir-Hansen 

do you guys still need this issue or can it be closed?
summary:
1. checking "operations" table if you're at the column limit (then it's the same issue we had)
2. changing to azure monitor in the azure container app environment should fix it (actually even without the issue this is a good idea imho)

**Comment by ekjuanrejon** [comment]
sure

**Comment by cstickel** [comment]
@xwang971  that's weird, because logs bigger than ~3kb didn't end up in the azure monitoring for us... for smaller logs it's working perfectly fine.
not an issue for us, but you might just want to double check if the 32kb value is correct.

**Comment by cstickel** [comment]
@xwang971 seems that it's not the size, but maximum nesting, that causes logs to be dropped (and only the single entry that has the very deep nesting).
totally unrelated to this issue, so would close this one, because with monitoring logs seem to work fine.

**Comment by tasdflkjweio** [comment]
this is a problem still

**Comment by CaishenNefri** [comment]
Issue persist. One time it works, one time not. The same query, nothing special

![chrome_zPZyMJZPqD](https://github.com/microsoft/azure-container-apps/assets/24476768/79f9af80-f48c-4f1e-9c35-9703ad12eb49)

![1rHnRZYIBc](https://github.com/microsoft/azure-container-apps/assets/24476768/91885362-99bb-4fa6-9348-dd9468196fc0)
