### ISSUE TITLE
deployment via bicep

### ISSUE THREAD

**Issue by ekjuanrejon** [microsoft/azure-container-apps#701]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ManagedEnvironmentOperationInProgress","message":"Cannot modify Container Apps environment duende-dev-cae because another operation is in progress."}]}

**Comment by ekjuanrejon** [comment]
@SophCarp

**Comment by torosent** [comment]
Hi. Can you please send us the details to `acasupport at microsoft dot com`
