### ISSUE TITLE
Feature Request: Notifications of replicas change

### ISSUE THREAD

**Issue by rambotzhong** [microsoft/azure-container-apps#703]
**Is your feature request related to a problem? Please describe**.  
Azure Container App is able to auto scale with scacler, but I can not get any notifications of the replica count change. Currently, we can only pull the relicas at intervals, but it's not a good way to get the real-time replicas count.

**Describe the solution you'd like**.    
Is there a way we can get the notifications of any replicas change?

**Describe alternatives you've considered**.   

**Additional context**.

**Comment by anthonychu** [comment]
@rambotzhong I don’t think real-time notifications are possible today. How would you like to subscribe to notifications? For example, would Event Grid work for you?
