### ISSUE TITLE
Not possible to run a mongoDB container with azure files persistence

### ISSUE THREAD

**Issue by rhuanbarreto** [microsoft/azure-container-apps#704]
### Discussed in https://github.com/microsoft/azure-container-apps/discussions/702

<div type='discussions-op-text'>

<sup>Originally posted by **rhuanbarreto** March 30, 2023</sup>
I've tried to run a mongoDB container as a sidecar and persist its storage to azure files volume mount without success. The container doesn't even emit any logs about it. Is there any incompatibility with azure files?</div>

How can I make this possible?

**Comment by torosent** [comment]
Hi, You can't do it with Azure Files and SMB. You will need Azure Files with NFS support which we don't support at the moment.

**Comment by simonjj** [comment]
We support NFS now. Closing this now.
