### ISSUE TITLE
unable to scale to 0 with memory scale rule

### ISSUE THREAD

**Issue by MonsieurTib** [microsoft/azure-container-apps#707]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have a scale rule defined as follow :

min-max replica : 0-1
scale rule : 
name : "memory"
type : custom
custom rule type : memory

metadata : 
type : AverageValue
value : 90

Given that my app never exceeds 15-20% of the RAM's capacity, it never scales down to 0 with this configuration.
My application scales down to zero without any issues when I remove this particular scaling rule.

**Expected behavior** [What you expected to happen.]
I expect my application to scale down to zero when the average memory usage is below 90%

**Actual behavior** [What actually happened.]
stuck with one replica

**Comment by ahmelsayed** [comment]
[Memory](https://keda.sh/docs/2.10/scalers/memory/) and [CPU](https://keda.sh/docs/2.10/scalers/cpu/) scalers will never scale the app to 0. KEDA doesn't do it because it'll will never be able to scale it back from 0 and ACA just inherits KEDA's behavior.

**Comment by MonsieurTib** [comment]
I understand, and it makes perfect sense.
