### ISSUE TITLE
Support updating specific container

### ISSUE THREAD

**Issue by shawncx** [microsoft/azure-container-apps#71]
For current CLI, it can only update first container's image name, env, command... If I want to update other containers, I have to prepare a yaml, which is quite complicated. Sometimes, I just want to update an environment variable of a particular container.

Can we add an argument allow user to tell the target container, like "--container-name"?

**Comment by cmenzi** [comment]
Hi @shawncx 

I've created DTOs and the Yaml Serialization for all current available values. If you like you can take a look: https://github.com/cmenzi/container-apps-dtos

I basically create the deployment definition and save it to to disk and execute the Azure CLI command with the `--yaml <file>` parameter.

Maybe this helps the one or the other :-)

**Comment by simonjj** [comment]
Closing this, if this is still a relevant issue please comment to reopen.
