### ISSUE TITLE
Feature Request: availability in Australia Southeast

### ISSUE THREAD

**Issue by cdayne** [microsoft/azure-container-apps#711]
**Is your feature request related to a problem? Please describe**.  
Any ETA on when it will be available in Australia Southeast region?

**Describe the solution you'd like**.    
Made available in the Australia Southeast region to support region pairs.

**Describe alternatives you've considered**.   
N/A

**Additional context**.  
N/A

**Comment by christianacca** [comment]
In the absence of Australia Southeast, which region to recommend for deploy a failover instance?

**Comment by simonjj** [comment]
We're tracking this via #1329.
