### ISSUE TITLE
Managed certificate property name incorrect in 2022-11-01-preview REST API

### ISSUE THREAD

**Issue by source-studio** [microsoft/azure-container-apps#712]
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I believe one of the property names is incorrect in the 2022-11-01-preview REST API related to [managed certificates](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/app/resource-manager/Microsoft.App/preview/2022-11-01-preview/CommonDefinitions.json#L1047).

Specifically, `domainControlValidation` should be named `validationMethod`. The CLI extension appears to use `validationMethod`, so I'm assuming this is the correct name.

I originally mentioned this issue [here](https://github.com/microsoft/azure-container-apps/issues/607).

**Comment by torosent** [comment]
Thanks @source-studio. We are still working on this feature and the property will be consistent across the API, CLI and portal.

**Comment by source-studio** [comment]
@torosent - I was just wondering if there is any update on this, now that the Managed Certificate feature is officially in public preview? I'm assuming the property name is intended to be `domainControlValidation`, as per the current ARM spec? Are there plans to provide examples on how to provision and bind a managed certificate via ARM/Bicep? Thanks.

**Comment by simonjj** [comment]
This is fixed now. Closing.
