### ISSUE TITLE
Client certificate authentication doesn't work with self signed certificate and the caller in .net full framework

### ISSUE THREAD

**Issue by andrekiba** [microsoft/azure-container-apps#714]
### This issue is a: (mark with an x)
- [ x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Trying to call a .net 6 api in ACA with a self signed client certificate doesn't work if the call comes from a .net full framework (tested with 4.5 and .4.8)
The issue is related to [279](https://github.com/microsoft/azure-container-apps/issues/279)

### Steps to reproduce
1. create a self signed certificate
2. create a console app full framework
3. make a call using HttpClient, attach the certificate

**Expected behavior**
be able to reach the api code with the certificate information inside the header x-forwarded-client-cert

**Actual behavior**
no x-forwarded-client-cert at all because the client certificate is not sent at all 

### Additional context
If I deploy the same containerized .net 6 api (the one that is now on ACA) using a linux azure app service...it works also from .net full framework.
During the SERVER HELLO step of the handshake seems that the app service is more permissive, it doesn't specify any issuer allowing the caller to provide it's own self signed certificate (and then is the api code in charge to control the info and eventually trust the certificate or not).
On the other hand ACA specifies a list of possible issuers (where do those 127 default ones I see come from?) and this automatically deletes the self signed certificate by not finding any trusted issuers...
**this leads to an anonymous call --> no x-forwarded-client-cert --> 403 forbidden**

ACA:
```
System.Net Information: 0 : [13544] SecureChannel#41622463 - We have user-provided certificates. The server has specified 127 issuer(s). Looking for certificates that match any of the issuers.
System.Net Information: 0 : [13544] SecureChannel#41622463 - Left with 0 client certificates to choose from.
```

App Service:
```
System.Net Information: 0 : [34872] SecureChannel#41622463 - We have user-provided certificates. The server has not specified any issuers, so try all the certificates.
System.Net Information: 0 : [34872] SecureChannel#41622463 - Left with 1 client certificates to choose from.
System.Net Information: 0 : [34872] SecureChannel#41622463 - Selected certificate: [Version] V3
```

**Comment by andrekiba** [comment]
@ahmelsayed I also ask here for an update, thank you

**Comment by ahmelsayed** [comment]
Yes, this should have rolled out to all regions earlier this week. Closing this issue as done.
