### ISSUE TITLE
Feature Request: Need platform support to host Apache Flink based components in Container apps

### ISSUE THREAD

**Issue by thilakbe** [microsoft/azure-container-apps#716]
**Is your feature request related to a problem? Please describe**.  
We are trying to deploy Apache Flink based components in Container apps which is not working as expected. 

**Describe the solution you'd like**.    
We have deployed Apache Flink based components in Azure Kubernetes Service which is giving the desired results, now we are trying to migrate the Flink application from AKS to Azure Native tool Container Apps which is not compatible. It would be good if Container apps has the ability to support Flink deployments.

**Describe alternatives you've considered**.   
None

**Additional context**.  
Please find the Apache Flink documentation which has the deployment support for Docker and Kubernetes
https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/overview/

**Comment by simonjj** [comment]
Can you please share more.
