### ISSUE TITLE
Modify Task definition for Azure Container Apps

### ISSUE THREAD

**Issue by deepaksinghwrites** [microsoft/azure-container-apps#718]
Issue Description - 
I would like to modify the entry point for azure container apps to be proxied via a Dapr sidecar.

My use case is as follows - 
I have a monitoring agent running in the Dapr sidecar. I would like to send all ingress and egress traffic proxied from my application via this agent.

**Comment by greenie-msft** [comment]
Hi @deepaksinghwrites,

Thanks for opening this feature request and for explaining your scenario. 

This is not something that is on the immediate roadmap, but I can take note and will adjust priority if it continues to come up.

Thank you,

**Comment by greenie-msft** [comment]
Hi @deepaksinghwrites,

Thanks for opening this feature request and for explaining your scenario. 

This capability is not something we have on the immediate roadmap, but I can take note and will adjust priority if it continues to come up.
