### ISSUE TITLE
Cannot create container app with image from ACR in different subscription using managed identity with cli

### ISSUE THREAD

**Issue by anotherRedbeard** [microsoft/azure-container-apps#719]
### This issue is a: 
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm attempting to create a container app using an image from an azure container registry in a different subscription using the azure cli.  When I run the `az containerapp create` command I get an error stating that there is no registry with that name in my subscription

### Steps to reproduce
1. Create a container registry in Subscription A
2. Create a container app environment in Subscription B
3. Create a user assigned managed identity in Subscription B
4. Grant ACRPull access to previously created managed identity for the container registry resource
5. Run the following cli command:  `az containerapp create -n $ACA_NAME  -g $ACA_RG_NAME --image $IMAGE_NAME --environment $ACA_ENV_NAME --registry-server $ACR_SERVER_NAME --registry-identity $MI_RESOURCE_ID --ingress external --target-port 80 --min-replicas 1`

**Expected behavior** 
New container app/revision to be created in Subscription B that is using the image pulled from the container registry in Subscription A.

**Actual behavior**
I receive this error (i scrubbed out the server name and subid):  The resource with name '<acr_server_name>' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription '<subscription-that-contains-container-app-environment>'

### Additional context
I have a single tenant setup in this case.  I also tried to use the Portal but that doesn't allow me to see the other subscription's ACR either.  That already has an issue created [671](https://github.com/microsoft/azure-container-apps/issues/671) with (at the time of this issue creation) a comment stating that the cli would work.  I have also confirmed that the cli does work when using username and password command `az containerapp create -n $ACA_NAME  -g $ACA_RG_NAME --image $IMAGE_NAME --environment $ACA_ENV_NAME --registry-server $ACR_SERVER_NAME --registry-username $ACR_USERNAME --registry-password $ACR_PASSWORD --ingress external --target-port 80 --min-replicas 1` so I believe this issue may be specific to attempting this with the managed identity.

**Comment by vturecek** [comment]
@anotherRedbeard can you check if ARM tokens are allowed to access your ACR:
```
az acr config authentication-as-arm show -r <registry>
```

If ARM tokens are disallowed, you can allow them with the following command:

```
az acr config authentication-as-arm update -r <registry> --status [enabled/disabled]
```

**Comment by anotherRedbeard** [comment]
HI @vturecek,

It looks like they are enabled:

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/34103220/233742695-2835e0d5-da87-430f-a872-9db2b9014534.png">

**Comment by phcbarros** [comment]
Hi everybody! 

I have a similar problem but I can deploy** my image (Subscription A) on my container app (Subscription B)  and when I tried to access my CA the newest revision is on provisioning status forever and the last revision is on provisioning status too. I tried to deploy twice and in the second one the newest revision was provisioned and the old one was on provisioning status but if I try access my CA url it does not working otherwise the revision url is working. 


** My deploy takes 10 minutes to publish on CA 

```
az containerapp create --name $ACA_NAME \
                  --resource-group $ACA_RG_NAME \
                  --image $ACR_NAME.azurecr.io/$REPO:$TAG \
                  --registry-server $ACR_NAME.azurecr.io \
                  --registry-username $ACR_USERNAME \ 
                  --registry-password $ACR_PASSWORD \
                  --ingress external --target-port 3000 \
```

I tried using **up** instead of **create** and my pipeline shows me the following error message:

ERROR: The resource with name '***' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'Subscription B'

**Comment by vturecek** [comment]
@anotherRedbeard, @phcbarros - are you only getting this error when you deploy with the `az containerapp` CLI? For example, if you deploy an ARM template like the following, do you see an error?

```
az deployment group create --resource-group $RESOURCEGROUP --template-file app.json
```

**app.json:**
```
{
    "identity": {
      "type": "UserAssigned",
      "userAssignedIdentities": {
        "/subscriptions/<YOUR SUB>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY NAME>": {}
      }
    },
    "location": "eastus2",
    "properties": {
      "managedEnvironmentId": "/subscriptions/<YOUR SUB>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.App/managedEnvironments/<YOUR ENV>",
      "configuration": {
        "ingress": {
          "external": true,
          "targetPort": 80
        },
        "registries": [
          {
            "server": "<YOUR ACR IN A DIFFERENT SUB>.azurecr.io",
            "identity": "/subscriptions/<YOUR SUB>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY NAME>"
          }
        ]
      },
      "template": {
        "containers": [
          {
            "image": "<YOUR ACR IN A DIFFERENT SUB>.azurecr.io/<IMAGE>:<TAG>",
            "name": "testimage"
          }
        ]
      }
    }
  }
```

**Comment by phcbarros** [comment]
@anotherRedbeard I have no tried with ARM just using azure CLI

**Comment by anotherRedbeard** [comment]
HI @vturecek , I tried using the arm method and it works as expected.  So just for clarity, the arm method works, but cli does not.

**Comment by vturecek** [comment]
thanks @anotherRedbeard for confirming. Version `0.3.29` of the containerapp CLI extension has a fix for this (please note you need a minimum version 2.45.0 of CLI core).

This fixes the error you are seeing and you will no longer be blocked from using an ACR and a Managed Identity in different subscriptions. However, if they are in different subscriptions, the CLI command will not be able to automatically create a rol assignment to grant the managed identity pull access to the registry, and you'll see a warning like this:

```
Role assignment failed with error message: "The resource with name 'foo' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'bar'.".
To add the role assignment manually, please run 'az role assignment create --assignee <object ID> --scope <container-registry-resource-id> --role acrpull'.
You may have to restart the containerapp with 'az containerapp revision restart'.
```

So as long as you add the role assignment first, this should succeed.

**Comment by anotherRedbeard** [comment]
Hi @vturecek , I just confirmed that this worked for me as well with version `0.3.29`.  Thanks for your help getting this resolved.  I will close this issue.

**Comment by smartouss** [comment]
Is this solved? what is the steps to fix it in devops pipeline? i am passing the server registry username and password

**Comment by phcbarros** [comment]
I am using the AzureContainerApps@1 task which uses the az containerapp up command. Switching to az containerapp create worked.

**Comment by phcbarros** [comment]
I solved my problem by following these steps:

1. Use the "create" command to recreate my app container (az containerapp create).
1. Recreate my secrets (az containerapp secret set ....).
1. Update the container app (az containerapp update...).

Obs.: The container app needs to have the "acr-pull" permission.

**Comment by philipbTC** [comment]
Hi All,

Does anyone know if this is still an issue? I'm having this exact problem.

I've confirmed that authentication-as-arm is enabled

```
az acr config authentication-as-arm update -r <registry> --status [enabled/disabled]
```
