### ISSUE TITLE
Microsoft Orleans networking trouble with new Consumption + Dedicated feature

### ISSUE THREAD

**Issue by christiansparre** [microsoft/azure-container-apps#721]
### This issue is a:
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
Hi, I'm trying out Orleans with the new Consumption + Dedicated stuff and something have changed with networking. Previously in the Orleans `ConfigureEndpoints` we used `Dns.GetHostname` and Orleans in turn resolved that to ex. 100.100.0.160 or 100.100.0.144 for each silo as the advertised IP address. With the new stuff that now resolves to 127.0.0.1 it seems

So I have been trying to figure out how to get the "internal" ip address of each replica so the Orleans silos and clients can talk to each other.

A bit of exploring lead to
Dns.GetHostname = 71c4a040de524291b53a370d528133b4 
Dns.GetHostEntry(container app name) = 100.100.158.250
Dns.GetHostEntry(71c4a040de524291b53a370d528133b4) = 127.0.0.1, 169.254.1.240, 169.254.1.241, fe80::7c9d:e9ff:fea2:116%2

When omitting the `Dns.GetHostname` from the `ConfigureEndpoints` call in Orleans will resolve to ex. 169.254.1.240 but that does not seem to work either.

I'm a bit lost on how to proceed figuring this out. What changed with the networking and how do I get the IP address of the replica that Orleans needs for internal TCP communication?

The ACA environment is deployed using Bicep (Microsoft.App/containerApps@2022-11-01-preview)

**Expected behavior**
Orleans silos and clients able to communicate internally over TCP

**Actual behavior**
Dns.GetHostname previously resolved to usable IP address, now resolves to 127.0.0.1 or IP Address that is not accesible

**Comment by torosent** [comment]
Hi, It's a bug in Workload Profile - Consumption and we are working on a fix.

**Comment by christiansparre** [comment]
Hi @torosent, any progress on this you could share? Or is it tracked somewhere else I can keep updated?

**Comment by torosent** [comment]
We are still working on it. ETA: Week of May 22.

**Comment by richardkooiman** [comment]
Stumbled upon the same issue today when trying to run Orleans on an Azure Container Apps consumption workload profile. I've tried some things to try determine the replica's private IP address but haven't found a way (but it should have one within our VNet's subnet I suppose).

@christiansparre Did you manage to find any workaround for this in the meanwhile?
@torosent Hope you don't mind me asking - but any news on when the issue will be resolved?

**Comment by christiansparre** [comment]
@richardkooiman No, I have not looked into it since.

**Comment by torosent** [comment]
Hi, It is still in progress. We have a slight delay compared to our initial estimation.

**Comment by richardkooiman** [comment]
Thanks for the update. :) Eagerly awaiting!

**Comment by christiansparre** [comment]
@torosent are you any closer to resolving this issue? We are eagerly awaiting news as well as we have a use case for the dedicated instances alongside our consumption usage.

**Comment by christiansparre** [comment]
@torosent Ok, this might be something else then. I have tried creating a simple app to reproduce the issue we see with Orleans where it now does not seem to be able to bind to the sockets it needs for communication.

I would appreciate any insights into what might be causing this or if I have missed any documentation 😀

The repro outputs a few values that are relevant and does more or less what Orleans does:

**"Old" consumption plan that still works**
```
Dns.GetHostName: cns-consumption-app--3nofpek-5dfc8ddb94-66hw9
ResolveIPAddressOrDefault (Orleans): 100.100.0.23
Dns.GetHostAddresses:
 - 100.100.0.23
 - fe80::3c73:32ff:fe72:35a9%63
Socket.Bind(100.100.0.23:20001) successful
```

**New consumption and dedicated plan with the app running in "consumption"**
```
Dns.GetHostName: cns-consumption-dedicated-app--8f67f12-5775cf577d-wv5dh
ResolveIPAddressOrDefault (Orleans): 100.100.61.190
Dns.GetHostAddresses:
 - 100.100.61.190
 - 169.254.5.5
 - 169.254.5.6
 - fe80::a86c:dfff:fe77:a1e6%2
Socket.Bind(100.100.61.190:20001) failed
Cannot assign requested address   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Program.<>c.<<Main>$>b__0_0() in /src/WebApplication2/Program.cs:line 49
```

It returns a few more IP addresses than the "old" one, and the first IP is no longer a 100.100.0.*, but a 100.100.61.* don't know if that matters.

The exception we are seeing in Orleans is:
```
System.Net.Sockets.SocketException (99): Cannot assign requested address
at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Bind(EndPoint localEP)
at Orleans.Networking.Shared.SocketConnectionListener.Bind() in /_/src/Orleans.Core/Networking/Shared/SocketConnectionListener.cs:line 63
at Orleans.Networking.Shared.SocketConnectionListenerFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken) in /_/src/Orleans.Core/Networking/Shared/SocketConnectionListenerFactory.cs:line 41
at Orleans.Runtime.Messaging.ConnectionListener.BindAsync() in /_/src/Orleans.Runtime/Networking/ConnectionListener.cs:line 78
at Orleans.Runtime.Messaging.SiloConnectionListener.<Orleans.ILifecycleObserver.OnStart>b__15_0() in /_/src/Orleans.Runtime/Networking/SiloConnectionListener.cs:line 80
at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 134
at Orleans.LifecycleSubject.OnStart(CancellationToken cancellationToken) in /_/src/Orleans.Core/Lifecycle/LifecycleSubject.cs:line 118
```

**Comment by torosent** [comment]
@christiansparre, we are taking a look

**Comment by TheGrayFrost** [comment]
Hi @christiansparre @richardkooiman 

I took a look at the issue. It might be because of directly trying to bind to the Vnet IP (100.100.61.190), which isn't directly exposed to container in Consumption Workload Profile.
Consumption has a different networking design wherein expose a virtual IP like "169.254.1.240" (which you see in the GetHostEntry.)

Could you please share how exactly are you configuring Orleans?

I believe the fix would be to do something like:
```
var hostName = Dns.GetHostName();
builder.ConfigureEndpoints(
    hostname: hostName,
    siloPort: siloPort,
    gatewayPort: gatewayPort,
    **listenOnAnyHostAddress: true**);
```

By default this listenOnAnyHostAddress setting is false, and thus you may have been getting socket bind error. 
Please try configuring the app in above mentioned way and it should work on both Dedicated and Consumption.

**Comment by richardkooiman** [comment]
@TheGrayFrost Thanks for your time looking into this. Ran a deployment with the configuration as you proposed and all seemed to be working this time. Not sure if the `listenOnAnyHostAddress` really did the trick or something else has changed in the meanwhile, but glad with the result.

**Comment by christiansparre** [comment]
@TheGrayFrost thanks for looking into this, only had a chance to look at it yesterday and also ran a deployment of our codebase with `listenOnAnyHostAddress` and that seems to work for us as well. It also worked in my simple repro 👍

I'll close the issue now, again thank you for looking into it 😁

**Comment by TheGrayFrost** [comment]
Hi @christiansparre @richardkooiman 
We recently made another update to the networking model on Consumption workload profile. Now there should be more parity between Consumption and Dedicated, and you should be able to use Orleans as:
```
builder.ConfigureEndpoints(
    siloPort: siloPort,
    gatewayPort: gatewayPort);
```

You don't need to specify `hostname` or `listenOnAnyHostAddress` for consumption or for dedicated. (Of course, things will still work if you do specify those params)
