### ISSUE TITLE
Mitigate Potential Memory Pressure Effects With cgroup v2

### ISSUE THREAD

**Issue by dariagrigoriu** [microsoft/azure-container-apps#724]
Starting on 5/15/2023, Azure Container Apps will run on Azure Kubernetes version 1.25.* or higher.  In this version, Kubernetes uses [cgroup v2](https://kubernetes.io/blog/2022/08/31/cgroupv2-ga-1-25/) and can result in potential memory pressure effects for customers using JRE versions lower than [11.0.18](https://bugs.java.com/bugdatabase/view_bug?bug_id=8230305), .NET < 6, [nodejs](https://github.com/nodejs/node/issues/47259), or any other framework that does not support cgroup v2, e.g. [High memory consumption with v1.25.2 · Issue #3443 · Azure/AKS (github.com)](https://github.com/Azure/AKS/issues/3443). Please consider framework version updates, memory usage optimizations, or allocating more memory to impacted apps.

**Comment by floriankoch** [comment]
NodeJs 20.3.0 has a fix for this (new libuv Version https://github.com/nodejs/node/pull/48078)
