### ISSUE TITLE
"cannot have more than 0 environments" on Pay-as-you-Go subscription

### ISSUE THREAD

**Issue by rikroe** [microsoft/azure-container-apps#729]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
After deleting the only container app environment on my Visual Studio subscription, my global quota for Container App Environments is set to 0 and is not updating back to 1.

When deploying a new Container App Environment, I get the following message:

`{"code": "ManagedEnvironmentCountExceededForSubscription", "message": "The subscription 'VISUAL_STUDIO_SUBSCRIPTION' cannot have more than 0 environments."}`

I have raised a ticket with Azure support for my immediate issue, but I think the counter should reset?

### Steps to reproduce
1. Create Container App Environment on a Visual Studio Subscription
2. Delete the Environment
3. Create another Environment

**Expected behavior** [What you expected to happen.]
The new Container App Environment is created.

**Actual behavior** [What actually happened.]
See error above.

**Screenshots**         

### Additional context
Error occurs when deploying through Portal and az cli (Bicep).

**Comment by rikroe** [comment]
Just encountered the same issue on a Azure Sponsorship subscription, I am unable to create even the first environment.
On an Enterprise Agreement subscription, I am able to create the managed environment without issues.

**Comment by Kimbahir** [comment]
I think I have an ordinary Azure pay-as-you-go subscription. I have one I created earlier, but not I am told I am allowed to have 0 - and I don't dare to touch the one (1) I have. Also, the documentation states I should be able to have 15 in 1 subscription...

**Comment by 01F0** [comment]
Same here, I'm on a standard Pay-as-you-go subscription (trying to create an environment on the West Europe region FWIW).

**Comment by rikroe** [comment]
Worked today for me again without any changes to my subscriptions/deployments.

**Comment by Kimbahir** [comment]
Same here- good but a sad waste of hours on a good Sunday

**Comment by torosent** [comment]
Hi Folks, can you send me your subscription ids to `acasupport at microsoft dot com`? we will investigate why it happened.

**Comment by chinadragon0515** [comment]
There is a race condition causing some subs quota was set to wrong number, this has been recovered, let us know if you still see the issues.
