### ISSUE TITLE
Reserved IP 

### ISSUE THREAD

**Issue by VeselovAndrey** [microsoft/azure-container-apps#73]
I have an event-driven app that I want port to Container Apps.
Periodically it communicates with other 3rd party (outside of Azure) services, but these service uses IP whitelists as one of security measures.
Is there any have to have a reserved IP that will be used to communicate from containers with external services.

**Comment by inuvano-labs** [comment]
I'm wondering whether this will work out-the-box once VNET's are supported and enabling outbound NAT on the integration subnet. I can see that VNET are on their roadmap - so you may have to wait until then.

**Comment by StoneCypher** [comment]
you can just buy an ipv6 block from arin and ARP it to yourself

**Comment by duglin** [comment]
@VeselovAndrey if you do a `show` on your ACA app then you should see something like:
```
      "outboundIpAddresses": [
        "20.121.75.96",
        "20.121.75.163",
        "20.121.75.187"
      ],
```
you should be able to whitelist those IPs to address your problem.
Please ping if we need to reopen
