### ISSUE TITLE
Microsoft.App/managedEnvironments@2022-11-01-preview Managed Environment deployment fails after initial deployment

### ISSUE THREAD

**Issue by ChrisTrailight** [microsoft/azure-container-apps#731]
Hiya,

just notification of a minor issue when deploying the new workloadProfiles in managed container app environments using the Microsoft.App/managedEnvironments@2022-11-01-preview API with bicep:

[Original report]((https://github.com/Azure/bicep-types-az/issues/1508#issuecomment-1518395677))

Bicep version: 0.16.2

When deploying a container app to a managed container app environment configured to use a workload profile of 'Consumption', after the first deployment, subsequent deployments fail with the error

{
    "status": "Failed",
    "error": {
        "code": "WorkloadProfileInUse",
        "message": "Cannot remove workload profile(s): Consumption because it is being used by container apps"
    }
}
Expected behaviour:

The container app environment deployment would either succeed or have its state updated depending on the template inputs and then succeed

Steps to reproduce:

Create a bicep template that deploys: a managed container app environment using the Microsoft.App/managedEnvironments@2022-11-01-preview API, configured with a workload profile of 'Consumption', that runs a container app.
deploy the template
redeploy the template
bicep snippet:

resource managedEnvironment_name_resource 'Microsoft.App/managedEnvironments@2022-11-01-preview' = {
  name: managedEnvironment_name
  location: location
  properties: {
    vnetConfiguration: {
      internal: true
      infrastructureSubnetId: resourceId('Microsoft.Network/virtualNetworks/subnets', vnet_name_resource.name, ContainerAppSubnet)
    }
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: LogAnalytics_resource.properties.customerId
        sharedKey: LogAnalytics_resource.listkeys().primarySharedKey
      }
    }
    workloadProfiles: [
      {
        workloadProfileType: 'Consumption'
      }
    ]
    zoneRedundant: false
    customDomainConfiguration: {}
  }
}

I opened an issue report over with the Bicep team and @brwilkinson has super-helpfully identified that the issue is that the "name" parameter is **required** when specifying the workloadProfileType, but this is not currently enforced. Adding name to the workload profile declaration is effective and the resource deployment succeeds after its initial deployment. 

    workloadProfiles: [
      {
        workloadProfileType: 'Consumption'
        name: 'Consumption'
      }
    ]

many thanks,

Chris

**Comment by jijohn14** [comment]
Reproduced the issue. We are working on a fix.
Thank you for reporting it.

**Comment by simonjj** [comment]
This is hopefully fixed now. Closing this now.
