### ISSUE TITLE
Multi container apps - How to determine which container will receive ingress traffic

### ISSUE THREAD

**Issue by matt-psaltis-work** [microsoft/azure-container-apps#732]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When utilising Azure Container Apps with multiple containers within the pod, the usual ContainerPort configuration and selectors don't seem to be exposed. This makes it difficult to determine which container within the pod will receive the ingress request.

Can we please get further guidance on this scenario?

**Comment by rikroe** [comment]
In my experience, all ports of a app running in a container are exposed in the pod.
As you cannot have multiple containers in one pod exposing the same port, use different ports per container and just set the [`targetPort`](https://learn.microsoft.com/en-us/azure/container-apps/ingress-how-to?tabs=azure-cli%2Cportal%2Carm-template&pivots=azure-cli#ingress-settings) of the ingress to the port you want to connect to.

**Comment by rikroe** [comment]
Hey @anthonychu seems your bot likes to repeat itself and needs some support... 😄
