### ISSUE TITLE
Warn if a privileged target port (<1024) is requested  for non-root containers

### ISSUE THREAD

**Issue by michaelp** [microsoft/azure-container-apps#737]
**Is your feature request related to a problem? Please describe**.  
Using privileged ports (<1024) in non-root containers can be pretty tricky. These ports require root access to bind to them, which may work in the docker-desktop environment, but not on cloud-hosted environments like container apps
I wish container apps could warn the developers about this issue when they try to use these ports. Maybe there is already a warning that I missed?

**Describe the solution you'd like**.    
* to have a default of 8080 in all templates and guidances (this is already planned for the next version to the best of my knowledge). Also, the default examples of containers should be non-root. Right now it is the exact opposite. 
* to have a clear warning of the binding issue in the system logs
* To provide guidance on how to closely recreate the container apps' behaviour in the local environment, to simplify the developer flow.

**Additional context**.  
Issue troubleshooting was slower than expected due to the following reasons 
* The problem with bindings was not easily discoverable from the system logs 
_The deployment was successful but the system was failing on provisioning revision_
The `ContainerAppSystemLogs_CL` log entity attributes were  
  * Error_s: `1/1 Failed:app-23nwtz2ijewg2ContainerCrashing` 
  * Log_s:  `Error provisioning revision.`
*  It was misleading that the container pulled into the local docker-desktop environment worked without any issues
  
**References**
* https://github.com/dotnet/aspnetcore/issues/43149
* https://github.com/dotnet/dotnet-docker/issues/2249
* https://github.com/dotnet/dotnet-docker/issues/1757

**Comment by simonjj** [comment]
This should actually work without an issue. Closing this as won't do. Maybe I am missing something but I've bound plenty of containers to < 1024.
