### ISSUE TITLE
Feature Request: any ETA on 'az containerapp' extension GA?

### ISSUE THREAD

**Issue by hosseinabbasi-mryum** [microsoft/azure-container-apps#738]
**Is your feature request related to a problem? Please describe**.  
Container Apps has become GA for a year now and we would love to adopt them for our production workload, however, Bicep/ClickOps in Azure Portal is not enough for us.

We rely on these commands for our complete CI/CD pipeline to work:
* `az containerapp show`
* `az containerapp update --image '<new-image>'` <---- this is the actual deployment step
* `az containerapp revision show`
* `az containerapp revision restart` (required for when a secret changes)

With `az containerapp` extension being still in preview, we are a bit hesitant about going live.

**Describe the solution you'd like**.    
To have a GA version of `az containerapp` extension in its current state, or an ETA on that 🙂

**Describe alternatives you've considered**.   
We _can_ start using the extension and don't mind updating the syntax if a future version requires us to do so. However, if something like `az containerapp update --image` goes away, we will be in a pickle!

**Additional context**.  
Nothing.

**UPDATE:** Here is the output of `az version`:

```
{
  "azure-cli": "2.42.0",
  "azure-cli-core": "2.42.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-devops": "0.26.0",
    "containerapp": "0.3.17",
    "front-door": "1.0.17",
    "portal": "0.1.3"
  }
}
```

**Comment by simonjj** [comment]
We've split the core/GA commands from the extension. The extension will **_remain_** non-GA to remain more experimental. We are GA now for most of the features. 🎉 🎉 🎉
