### ISSUE TITLE
Are custom KEDA scalers supported?

### ISSUE THREAD

**Issue by VeselovAndrey** [microsoft/azure-container-apps#74]
I created and deployed a custom KEDA scaler as described on KEDA site.
In the Revision settings 
* Type = Custom
* scalerAddress = [APP URL:PORT]
+ some additional parameters. As I understand these params must be sent with requites to scaler.
I can access my app manually and get correct response.
But I see no requests from ConainerApp to scaler in logs. As result instance count goes to 0 and app stops working.

Are custom KEDA scalers supported?

**Comment by wterpstra** [comment]
Seems like it is supported: https://www.youtube.com/watch?v=z_QnOKVpbkA

**Comment by kendallroden** [comment]
Custom scalers are supported!
