### ISSUE TITLE
Container App memory scale not available anymore ?

### ISSUE THREAD

**Issue by jeremy1392** [microsoft/azure-container-apps#740]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
It looks like the documentation of Microsoft does not contain the scale information based on memory.
What happens with this feature ? When I use the KEDA memory  scaler https://keda.sh/docs/2.10/scalers/memory/ I'm not able to scale my container app based on memory usage.

### Steps to reproduce

            "scale": {
                "minReplicas": 1,
                "maxReplicas": 10,
                "rules": [
                    {
                        "name": "memory",
                        "custom": {
                            "type": "memory",
                            "metadata": {
                                "containerName": "scanner",
                                "metricType": "Utilization",
                                "value": "5"
                            }
                        }
                    }
                ]

**Expected behavior**
I was expecting to see the creation of a replica when memory goes more than 5%

**Actual behavior** 

Nothing happens

**Screenshots**         
Available
![memory-scalset](https://user-images.githubusercontent.com/33451078/236507788-2df9a1c3-453e-4692-802e-a9004b8292a4.png)
![morethan5](https://user-images.githubusercontent.com/33451078/236507793-941f33ff-fc9c-46a3-86ff-678df5d366fc.png)

**Comment by mateuszkozakiewicz** [comment]
I noticed similar behavior, scaling based on CPU/memory utilization no longer seems to be a valid configuration, following bicep code fails:
```
      scale: {
        maxReplicas: maxReplicas
        minReplicas: minReplicas
        rules: [
          {
            name: 'cpu-scaling-rule'
            custom: {
              type: 'cpu'
              metadata: {
                Utilization: scalingCpuUtilization
              }
            }
          }
        ]
      }
```
with following error:
```
  "details": [
    {
      "code": "InvalidParameterValueInContainerTemplate",
      "message": "The following field(s) are either invalid or missing. Field 'template.scale.rules.cpu.metadata.value' is invalid with details: 'Required value: value property in cpu/memory trigger metadata is required';."
    }
  ] 
```
The same thing happens when attempting to modify the resource via Azure Portal UI. Note the configuration is applied as stated in the bicep code but can no longer be modified eg. changing `Utilization: 50` to `Utilization: 51` is not possible.

As far as I can see `Utilization` is a valid KEDA metric type.
