### ISSUE TITLE
Azure Monitor Integration is GA, but API docs still show Log Analytics as only supported option

### ISSUE THREAD

**Issue by chriswangelin** [microsoft/azure-container-apps#741]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
[Azure Monitor Integration with Azure Container Apps (ACA) announced as generally available](https://azure.microsoft.com/en-us/updates/generally-available-azure-monitor-integration-with-azure-container-apps/), but API documentation for creating/updating ACA Environment shows that Log Analytics is still the only supported option.

### Steps to reproduce
View properties.appLogsConfiguration description in [REST API Request Body for creating/updating an Managed Environment](https://learn.microsoft.com/en-us/rest/api/containerapps/stable/managed-environments/create-or-update?tabs=HTTP#request-body)

**Expected behavior**

API documentation for creating/updating a Managed Environment indicates how to configure Azure Monitor as a logging destination for an ACA environment.

**Actual behavior**

API documentation indicates: "Currently only "log-analytics" is supported" for the properties.appLogsConfiguration request parameter.  No other request parameters appear to exist for configuring Azure Monitor integration.

**Comment by giovannifl** [comment]
Any update on this topic ?
ACA Environment onlys shows Log Analytics as the only supported option while also Azure Monitor should be showed.

**Comment by LianaAdaza** [comment]
Fix has been rolled out. Please create a new issue if you continue to experience difficulties.
