### ISSUE TITLE
Failed to provision appears to ignore startup probe

### ISSUE THREAD

**Issue by waynebrantley** [microsoft/azure-container-apps#747]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report 

### Issue description
Deploying a dotnet container that takes longer than 30 seconds to start.   The provisioning starts and the app is killed after 30 seconds and it tries again.  Ingress is enabled, but I only have a startup probe that appears as if it would let it have much longer than 30 seconds before failing.

### Steps to reproduce
1. dotnet asp.net container that takes a long while to start.
2. observe it restarting after 30 seconds

I have attached a screenshot of the probe configuration (perhaps I misunderstood or have it wrong?)
Container system logs show it failing after 30 seconds.

![image](https://github.com/microsoft/azure-container-apps/assets/157082/1d049436-2fc4-40d5-b03e-f494859f3286)

**Comment by ahmelsayed** [comment]
Do you have dapr enabled by any chance?

**Comment by waynebrantley** [comment]
@ahmelsayed dapr is not enabled.

**Comment by simonjj** [comment]
Closing this, please reopen if still an issue.
