### ISSUE TITLE
How to query replica metrics for given timeframe?

### ISSUE THREAD

**Issue by inuvano-labs** [microsoft/azure-container-apps#75]
If I navigate to my container app revision in the portal - I can see "Replicas" with the total number of running replicas within the range I've specified during deployment.

Can this be queried?

Our Ops dashboard in Azure portal displays a graph of the average http response time our app experiences when making an HTTP request to an Azure Container App. We'd like to overlay this with the replica count.

We noticed that within the workspace for the container environment each container instance is given an Id (ContainerId_s) - we're using this to aggregate the count during a timeframe. But this isn't accurate:

```
ContainerAppConsoleLogs_CL |
summarize Replicas = dcount(ContainerId_s) by bin(TimeGenerated, 1h) |
order by TimeGenerated asc |
render timechart 
```

**Comment by BigMorty** [comment]
Number of Replicas is a metric we added a few months ago.
