### ISSUE TITLE
Running a powershell script works in one environment and throws internal server error in another

### ISSUE THREAD

**Issue by aekundayo** [microsoft/azure-container-apps#750]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

github task

 - name: Deploy DB Boostrap
        shell: pwsh
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}  
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          DB_HOST: ${{ steps.myGetSecretAction.outputs.postgresHost }}
          DB_NAME: ${{ steps.myGetSecretAction.outputs.postgresName }}
          DB_USER: ${{ steps.myGetSecretAction.outputs.postgresUser }}
          DB_PASS: ${{ steps.myGetSecretAction.outputs.postgresPassword }}
          REDIS_KEY: ${{ steps.myGetSecretAction.outputs.redisKey }}
          REDIS_URL: ${{ steps.myGetSecretAction.outputs.redisHostName }}
          AZURE_ACCESS_KEY: ${{ steps.myGetSecretAction.outputs.storageAccountKey }}
          AZURE_ACCOUNT_NAME: ${{ steps.myGetSecretAction.outputs.storageAccountName }}
          AZURE_KEY_VAULT_NAME: ${{ inputs.keyvaultName }}
          USER_ASSIGNED_PRINCIPAL_ID: ${{ steps.myGetSecretAction.outputs.userAssignedPrincipalId }}
          USER_ASSIGNED_ID: ${{ steps.myGetSecretAction.outputs.userAssignedId }}
          SHOWROOM_DB: ${{ steps.myGetSecretAction.outputs.showroomDB }}
        run: |
          pwsh deployment_script/deployBootstrap.ps1 -containerAppEnvName ${{ inputs.containerAppEnvName }}   -backendAppId ${{ inputs.bootstrapApp }}  -revisionSuffix  ${{ github.run_number }} -dockerImageName ${{ inputs.bootstrapImageName }} -environment ${{ inputs.environment }} -resourceGroup ${{ inputs.resourceGroup }} -location ${{ inputs.location }} -subscription_id ${{ secrets.ARM_SUBSCRIPTION_ID }} -acr_password ${{ secrets.REGISTRY_PASSWORD }}     

DEV ENVIRONMENT
=================

Run pwsh deployment_script/deployBootstrap.ps1 -containerAppEnvName cae-ds-dev-westeurope   -backendAppId bootstrap-ds-dev-westeurope  -revisionSuffix  167 -dockerImageName ds-bootstrap -environment Dev -resourceGroup rg-DigitalShowroom-dev-westeurope-001 -location westeurope -subscription_id *** -acr_password ***     
WARNING: The installed extension 'containerapp' is in preview.

/ Running ..
| Running ..
\ Running ..
WARNING: 

<img width="687" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/34714860/8ef24039-43b2-4837-a4fc-9fc801a12771">

TEST  ENVIRONMENT
=================

Run pwsh deployment_script/deployBootstrap.ps1 -containerAppEnvName cae-ds-test-westeurope   -backendAppId bootstrap-ds-test-westeurope  -revisionSuffix  167 -dockerImageName ds-bootstrap -environment test -resourceGroup rg-DigitalShowroom-test-westeurope-001 -location westeurope -subscription_id *** -acr_password ***     
WARNING: The installed extension 'containerapp' is in preview.
ERROR: (InternalServerError) Internal server error occurred. correlation ID: 080c23ac-8b11-47b5-a9b5-31169f72a6f3

<img width="701" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/34714860/5f34e658-bf09-412d-887d-923eaea62ebc">

### Steps to reproduce
1. .. running powershell script to deploy az containerapp
2. 
3. ..

**Expected behavior** [What you expected to happen.]
Deployment
**Actual behavior** [What actually happened.]

**Screenshots**         

<img width="701" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/34714860/5f34e658-bf09-412d-887d-923eaea62ebc">

### Additional context
Ex. In CLI with pwsh ubuntu-latest

**Comment by simonjj** [comment]
Your app seems to be missing. If this is still an issue please reopen.
