### ISSUE TITLE
Error creating container app from Azure Devops

### ISSUE THREAD

**Issue by davidvesp** [microsoft/azure-container-apps#753]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I want to deploy a container app from Azure DevOps passing the config yaml to add the app config. During the pipeline execution, it fails because the pipeline doesn't have permission over the new app (it doesn't exist yet).
The SPN executing the pipeline has Owner permission on the Container App Environment.

### Steps to reproduce
1. Create a pipeline in Azure Devops to create a new container app on existing container app environment.
2. Execute the pipeline.

**Expected behavior** [What you expected to happen.]
Conatiner app created in the container app environment with the config from the yaml.

**Actual behavior** [What actually happened.]
Output of the pipeline
**/usr/bin/az account set --subscription [redacted]
/usr/bin/az config set extension.use_dynamic_install=yes_without_prompt**
WARNING: Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
**/usr/bin/az containerapp show -n web_v2 -g [redacted] -o none**
ERROR: (ResourceNotFound) The Resource 'Microsoft.App/containerApps/web_v2' under resource group 'data-testdavid-rsg-weu1-dev' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
**/usr/bin/az containerapp env show -n [redacted] -g data-testdavid-rsg-weu1-dev -o none**
Logging in to Azure Container Registry using access token to be generated via Azure CLI.
/usr/bin/bash -c CA_ADO_TASK_ACR_ACCESS_TOKEN=$(az acr login --name *** --output json --expose-token --only-show-errors | jq -r '.accessToken'); docker login ***.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p $CA_ADO_TASK_ACR_ACCESS_TOKEN > /dev/null 2>&1
**/usr/bin/az containerapp create -n web_v2 -g [redacted] --yaml containerapp_min.yml**
WARNING: Additional flags were passed along with --yaml. These flags will be ignored, and the configuration defined in the yaml will be used instead
ERROR: (**AuthorizationFailed**) The client '[redacted]' with object id '[redacted]' does not have authorization to perform action **'Microsoft.App/containerApps/write'** over scope **'/subscriptions/[redacted]/resourceGroups/[redacted]/providers/Microsoft.App/containerApps/web_v2'** or the scope is invalid. If access was recently granted, please refresh your credentials.
##[error]Error Code: [1]
##[error]Error: Unable to create Azure Container App from YAML configuration file via 'az containerapp create' command.

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/100422627/3b4a1cf5-1e39-4213-bd6b-42985ff04101)

**Comment by ahmelsayed** [comment]
> I want to deploy a container app from Azure DevOps passing the config yaml to add the app config. During the pipeline execution, it fails because the pipeline doesn't have permission over the new app (it doesn't exist yet).
> The SPN executing the pipeline has Owner permission on the Container App Environment.

A `Microsoft.App/containerApp` resource is a tracked top level resource under a resource group. It's not under the environment.

The SPN needs to have write access to both the environment and resourceGroup it's being created in.
