### ISSUE TITLE
Container App Jobs (preview) deployment fails with cancelled error message.

### ISSUE THREAD

**Issue by mburumaxwell** [microsoft/azure-container-apps#758]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Deployment of ContainerApp Job via bicep/ARM fails to succeed but the job is created and functions as epxected.

### Steps to reproduce
Example bicep file
```bicep
@description('Location for all resources.')
param location string = resourceGroup().location

resource appEnvironment 'Microsoft.App/managedEnvironments@2022-10-01' existing = { name: 'my-env' }

resource job 'Microsoft.App/jobs@2022-11-01-preview' = {
  name: 'my-job'
  location: location
  properties: {
    environmentId: appEnvironment.id
    configuration: {
      scheduleTriggerConfig: {
        cronExpression: '*/15 * * * *'
        parallelism: 1
        replicaCompletionCount: 1
      }
      replicaRetryLimit: 1
      replicaTimeout: 60
      triggerType: 'Schedule'
    }
    template: {
      containers: [
        {
          image: 'mcr.microsoft.com/k8se/quickstart-jobs:latest'
          name: 'main'
          resources: {
            cpu: json('0.25')
            memory: '0.5Gi'
          }
        }
      ]
    }
  }
}
```

Deployment command:
```cmd
az deployment group create --resource-group "<rg-name>" -f job.bicep --confirm-with-what-if
```

**Expected behavior** [What you expected to happen.]
The deployment should succeed since the job has been created and it functions as expected.

**Actual behavior** [What actually happened.]
The job resource is created but the deployment fails with this error message:
> The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Canceled'
CorrelationID: ca496e80-fc5c-4a5b-a013-1471cca2da30

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
This happens for when using ARM templates (json/bicep)

**Comment by joao-figueira** [comment]
Hi @mburumaxwell ,

I'm having the same issue. If you have any update on this let me know. 

Thanks

**Comment by torosent** [comment]
Hi, We found a bug in our ARM validation when invoked from Bicep. We are working on a fix.

**Comment by paolosalvatori** [comment]
Hi @vinisoto,  could you let me/us know if you rolled out the fix? Is anything necessary on the client side?

**Comment by mburumaxwell** [comment]
This is still not working (tried Friday and a few minutes ago).

Start time: 2023-06-13T11:16:13+03:00
Correlation ID: 52e378f2-36a0-41f7-b2c4-aad3a0ea910d

**Comment by paolosalvatori** [comment]
Thanks @mburumaxwell. Is there no way currently to deploy Azure Container App Jobs using Bicep, or does it fail under certain circumstances? cc @vinisoto

**Comment by paolosalvatori** [comment]
I also have another issue: if I try to deploy a job using [az containerapp job create](https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest#az-containerapp-job-create), it works as expected. But if I try to assign the resource id of an existing user-defined managed identity using the `--user-assigned` parameter, it fails with a strange error message as I have owner permissions on my Azure subscription, so I should be able to make assigments:

```bash
#!/bin/bash

# Variables
prefix="Pluto"
name="${prefix}SenderJob"
managedIdentityName="${prefix}WorkloadManagedIdentity"
resourceGroupName="${prefix}RG"
environmentName="${prefix}Environment"
triggerType="Manual"
imageName="paolosalvatori.azurecr.io/sbsender:v1"

# Retrieve the resource id of the user-assigned managed identity
echo "Retrieving the resource id for [$managedIdentityName] managed identity..."
managedIdentityId=$(az identity show \
  --name $managedIdentityName \
  --resource-group $resourceGroupName \
  --query id \
  --output tsv)

if [[ -n $managedIdentityId ]]; then
  echo "[$managedIdentityId] resource id  for the [$managedIdentityName] managed identity successfully retrieved"
else
  echo "Failed to retrieve the resource id for the [$managedIdentityName] managed identity"
  exit
fi

# Create Azure Container App Job
az containerapp job create \
  --name ${name,,} \
  --resource-group $resourceGroupName \
  --environment $environmentName \
  --user-assigned $managedIdentityId \
  --trigger-type $triggerType \
  --replica-timeout 60 \
  --replica-retry-limit 1 \
  --replica-completion-count 1 \
  --parallelism 1 \
  --image $imageName \
  --cpu "0.25" \
  --memory "0.5Gi"
```

Error message:

```bash
(LinkedAuthorizationFailed) The client 'xxxxx@microsoft.com' with object id xxxxxxx-xxxx-xxxxxxxx-xxxxxxxxx' has permission to perform action 'Microsoft.App/jobs/write' on scope '/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/PlutoRG/providers/Microsoft.App/jobs/plutosenderjob'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/PlutoRG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/.' or the linked scope(s) are invalid.
```

**Comment by paolosalvatori** [comment]
> I also have another issue: if I try to deploy a job using [az containerapp job create](https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest#az-containerapp-job-create), it works as expected. But if I try to assign the resource id of an existing user-defined managed identity using the `--user-assigned` parameter, it fails with a strange error message as I have owner permissions on my Azure subscription, so I should be able to make assigments:
> 
> ```shell
> #!/bin/bash
> 
> # Variables
> prefix="Pluto"
> name="${prefix}SenderJob"
> managedIdentityName="${prefix}WorkloadManagedIdentity"
> resourceGroupName="${prefix}RG"
> environmentName="${prefix}Environment"
> triggerType="Manual"
> imageName="paolosalvatori.azurecr.io/sbsender:v1"
> 
> # Retrieve the resource id of the user-assigned managed identity
> echo "Retrieving the resource id for [$managedIdentityName] managed identity..."
> managedIdentityId=$(az identity show \
>   --name $managedIdentityName \
>   --resource-group $resourceGroupName \
>   --query id \
>   --output tsv)
> 
> if [[ -n $managedIdentityId ]]; then
>   echo "[$managedIdentityId] resource id  for the [$managedIdentityName] managed identity successfully retrieved"
> else
>   echo "Failed to retrieve the resource id for the [$managedIdentityName] managed identity"
>   exit
> fi
> 
> # Create Azure Container App Job
> az containerapp job create \
>   --name ${name,,} \
>   --resource-group $resourceGroupName \
>   --environment $environmentName \
>   --user-assigned $managedIdentityId \
>   --trigger-type $triggerType \
>   --replica-timeout 60 \
>   --replica-retry-limit 1 \
>   --replica-completion-count 1 \
>   --parallelism 1 \
>   --image $imageName \
>   --cpu "0.25" \
>   --memory "0.5Gi"
> ```
> 
> Error message:
> 
> ```shell
> (LinkedAuthorizationFailed) The client 'xxxxx@microsoft.com' with object id xxxxxxx-xxxx-xxxxxxxx-xxxxxxxxx' has permission 
> to perform action 'Microsoft.App/jobs/write' on scope '/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/PlutoRG/providers/Microsoft.App/jobs/plutosenderjob'; 
> however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' 
> on the linked scope(s) '/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/PlutoRG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/.' or the linked scope(s) are invalid.
> ```

I solved by installing the latest update of the containerapp extension for Azure CLI that didn't return any error

**Comment by nikneem** [comment]
I still get this error, anyone with an update?

**Comment by OscarFalck17** [comment]
Still an issue today
