### ISSUE TITLE
HTTP StatusCode 502 when accessing files from Azure File Share

### ISSUE THREAD

**Issue by baartch** [microsoft/azure-container-apps#761]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I deployed an app with a single container using the latest [official Docker WordPress image](https://hub.docker.com/_/wordpress/). To make the website persistant, the _wp-content_ directory is placed on a mounted _Azure File Share_.
WordPress runs fine. Files can be uploaded through the backend and are visible on the File Share on the Storage Account (even the thumbnails are generated). But accessing one of the uploaded files through the browser is not possible. There is always the following error:  
https://myappsname.switzerlandnorth.azurecontainerapps.io/wp-content/uploads/2023/05/369601-300x169.jpg  
`HTTP StatusCode 502: upstream connect error or disconnect/reset before headers. retried and the latest reset reason: protocol error`

If I go to the Containers Log Stream, I see a StatusCode 200. So, I assume it's something with Envoy.  
`2023-05-30T07:40:34.956772581Z 89.144.213.24 - - [30/May/2023:07:40:34 +0000] "GET /wp-content/uploads/2023/05/369601-300x169.jpg HTTP/1.1" 200 6052 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"`

I checked already the recommended actions [here](https://azureossd.github.io/2023/03/22/Troubleshooting-ingress-issues-on-Azure-Container-Apps/#http-502). But with no success.

And just to mention, I defenitely want to use the official Docker image, no [custom image](https://github.com/Azure-Samples/apptemplate-wordpress-on-aca/blob/main/customize-docker-image.md) that comes from Microsoft.

### Steps to reproduce
1. Create an ACA environment with an Azure File Share
2. Make sure you have a database (I use Azure managed MariaDB)
3. Deploy an app with a single container using the official Docker image
![image](https://github.com/microsoft/azure-container-apps/assets/26668031/48516516-f449-4d9f-ae5d-237f16567e98) 
![image](https://github.com/microsoft/azure-container-apps/assets/26668031/0a420615-db14-4275-947e-2695ff5f1fe6)
![image](https://github.com/microsoft/azure-container-apps/assets/26668031/5b93f864-e911-4dcd-b499-c8b9a440e909)
4. Go into your WordPress Backend (/wp-admin) and upload a file (e.g. a sample image)
5. Observe in the Browsers Developer Tools on the _Network_ tab that the image gets uploaded but it cannot be displayed in the Media Library or any Blog Post. You can see the `502` error. 

**Expected behavior**
All files lying on the Azure File Share should be accessable the same as the files inside the Container. Since it is a mounted share, there should be no difference between the files on the mount and the files in the Container.

**Actual behavior**
Files that are uploaded to the mounted Azure File Share are not accessable from the web browser.

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/26668031/5b0f1b15-447e-4aeb-8124-8025d3c856c1)

The file is uploaded and the smaller versions of the image are generated.
![image](https://github.com/microsoft/azure-container-apps/assets/26668031/d6cd9877-1211-46eb-9b28-11bb952d1525)

The ingress configuration. Changing _Transport_ to _HTTP/1_ does not fix this issue.
![image](https://github.com/microsoft/azure-container-apps/assets/26668031/be5d24f8-8271-4f1b-a22c-aeb2d09fdade)

**Comment by zhenqxuMSFT** [comment]
Hi @baartch,
First of all, I cannot repro your issue with the same wordpress image and azure file setup.
From the envoy log of your environment, the response got from your app results in "HPE_INVALID_CONSTANT", which means the response was not a valid one. I think it might be related to these issues:
- https://serverfault.com/questions/1044724/apache2-sends-corrupt-responses-when-using-a-cifs-share/1047215#1047215
- https://serverfault.com/questions/1090235/unable-to-serve-images-from-wordpress-site-response-is-malformed
- https://superuser.com/questions/1564329/apache-not-serving-some-content-from-network-share

You may try 'EableSendfile Off' and 'EnableSendfile Off' as suggested in these posts. I am not familiar with wordpress but is it possible to switch to nginx? I see a lot of posts mentioning nginx works fine.
