### ISSUE TITLE
Outbound Ping, Traceroute traffic from ContainerApps

### ISSUE THREAD

**Issue by scdouble** [microsoft/azure-container-apps#769]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am checking network connectivity on ContainerApp. I found that There is no result of Ping or Traceroute from the container deployed on Azure ContainerApp (ping or tracertoute 8.8.8.8 from containerapps get timeout, I can retrieve web pages using curl without any issues.). Until a while ago I remember there was ping results from 8.8.8.8, but now the result is timeout.Has there been any changes? 
### Steps to reproduce
1. create a pubic ingress containerapp, comsumption plan, using official nginx container image
2. use console from azure portal to install ping package

**Expected behavior** [What you expected to happen.]
get ping result from 8.8.8.8

**Actual behavior** [What actually happened.]
timeout

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
Azure Portal

**Comment by cachai2** [comment]
This is expected behavior. By default, outbound ICMP protocol requests aren't allowed through Azure load balancer. Reference doc: https://learn.microsoft.com/en-us/azure/load-balancer/outbound-rules#limitations.

**Comment by scdouble** [comment]
Thank you for your advise
