### ISSUE TITLE
Deployment fails when two container apps reference the same DAPR component

### ISSUE THREAD

**Issue by roelvandegrint** [microsoft/azure-container-apps#77]
Hi,

I ran into this issue while trying to build a simple DAPR pubsub demo. When i deploy two container apps that use the same DAPR component, the deployment of the 2nd container app fails. This happens on a brand new deployment as well as a new revision.

I tried the [reddog container apps](https://github.com/Azure/reddog-containerapps) example to see if i was doing something wrong, but it runs into the same issue currently.

**Comment by renatolfc** [comment]
Seems to be the case for one of my deployments as well.

After successive failures trying to deploy a second container that referenced the same components o the first one, I tried deploying the exact same container to a new environment, and it succeeded.

**Comment by kendallroden** [comment]
Thanks for reporting. Currently due to the scoping of components at the Container App level, the naming of the component itself must be unique per Container App. This is an issue that is currently present in the reddog app as well. 
i.e. If App A - Component A and App B - Component A, you will get an error. You would have to change the name of Component A in App B to Component B. This is not ideal for components that are shared. We are working on changes to the service that will eliminate this limitation and allow a component to be shared across multiple Container Apps with the same name.  @renatolfc @roelvandegrint

**Comment by XavierGeerinck** [comment]
Thanks for reporting @roelvandegrint was facing the same issue here and it kept saying that the provisioning failed but I didn't know why

**Comment by XavierGeerinck** [comment]
Note: when updating, the app doesn't change at all and the deployment hangs. Not sure if this is an issue with the CLI or not and with this, but I resolved it by adding a random identifier that redeploys the container app itself each time.

```javascript
const randomStr = Math.random().toString(36).substring(2, 7); 
const containerAppName = `container-${randomStr}`
```

**Comment by roelvandegrint** [comment]
@kendallroden Thanks for the explanation. Just to be sure I understand correctly. That means in the mean time we cannot do things like pubsub that need to share the same component, right? I don't know of any workaround but since you said 'not ideal' I thought maybe there is?

**Comment by hinter-man** [comment]
@roelvandegrint a workaround that worked for me for things like pubsub was to specify a "pubsub component" for each service, while the components only differ in their names (as @kendallroden mentioned). 
"Under the hood" both dapr components pointed to the same (azure service bus) endpoint.

For example:
**Service A -> Component A**
```            
"dapr": {
  "enabled": true,
  "appId": "service-a",
  "appPort": 80,
  "components": [
    {
      "name": "pubsub-service-a",
      "type": "pubsub.azure.servicebus",
      "version": "v1",
      "metadata": [
        {
          "name": "connectionString",
          "value": "",
          "secretRef": "servicebusendpoint"
        }]
    }]
}
```

**Service B -> Component B**
```            
"dapr": {
  "enabled": true,
  "appId": "service-b",
  "appPort": 80,
  "components": [
    {
      "name": "pubsub-service-b",
      "type": "pubsub.azure.servicebus",
      "version": "v1",
      "metadata": [
        {
          "name": "connectionString",
          "value": "",
          "secretRef": "servicebusendpoint"
        }]
    }]
}
```
