### ISSUE TITLE
Missing eventTriggerConfig to configure Container Apps Jobs

### ISSUE THREAD

**Issue by NatMarchand** [microsoft/azure-container-apps#773]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm trying to set-up an event triggered job (#24)
According to the [documentation](https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-resource-manager#event-driven-jobs), in order to create a container apps job event triggered, one should use the eventTriggerConfig property to configure triggering rule.
However, according to the [ARM reference](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-11-01-preview/jobs?pivots=deployment-language-arm-template) or [REST reference](https://learn.microsoft.com/en-us/rest/api/containerapps/preview/jobs/create-or-update?tabs=HTTP#jobconfiguration) there's no such property. I believe the property works but is private or unsurfaced in the sdk.
As I'm using Pulumi, I'm then unable to create such a job.

**Comment by anthonychu** [comment]
Event driven jobs configuration requires version 2023-04-01-preview. Once this API version is finalized, we'll update the docs to it.

For now, please refer directly to the swagger spec: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/app/resource-manager/Microsoft.App/preview/2023-04-01-preview/Jobs.json#L721

**Comment by NatMarchand** [comment]
Oh thanks for the tip ! Do you have an approximate time range where it should be available ?

**Comment by jason-berk-k1x** [comment]
is `"Microsoft.App/jobs@2023-05-01"` ready for prime time use?
