### ISSUE TITLE
outboundIpAddresses is null for ACA with ACA environment with Consumption + Dedicated tier

### ISSUE THREAD

**Issue by neok-g** [microsoft/azure-container-apps#775]
Hi,

We are currently exploring the Azure Container App (ACA) Environment Consumption + Dedicated tier (preview) because we would like to have support for user defined routes to be able to route all internet traffic to our Azure firewall.
We noticed that the outboundIpAddress for the ACA within this ACA environment is null where it is always filled for ACA's in the ACA environment that have the Consumption tier.
Is this by design or a bug since it is in preview? If it is by design how should I get the outboundIpAddress for such a ACA?

Below a screenshot of part of the Json view:
![image](https://github.com/microsoft/azure-container-apps/assets/3228810/e0c58ff6-be3e-4abe-b26b-906856a02f0f)

**Comment by neok-g** [comment]
@kendallroden Could you explain this one since issue is related to #355 ? Thank you!

**Comment by torosent** [comment]
Hi, 
Unfortunately @kendallroden is not working at Microsoft anymore :(
Is your Container App environment defined as Internal? If so, then the you won't see an outgoing IP and it's up to you to set up Azure Firewall or NAT gateway. Any egress traffic will be routed through these services IP address.

**Comment by neok-g** [comment]
> Hi, Unfortunately @kendallroden is not working at Microsoft anymore :( Is your Container App environment defined as Internal? If so, then the you won't see an outgoing IP and it's up to you to set up Azure Firewall or NAT gateway. Any egress traffic will be routed through these services IP address.

@torosent  Yes it is defined as internal. But if the Consumption plan is used as internal the outgoing IP is filled so it might have somthing to do with the plan. However we are now using the solution with the Azure Firewall and use that PIP for whitelisting purposes and it works. This issue can be closed.

**Comment by cachai2** [comment]
Closing per customer feedback.
