### ISSUE TITLE
Edit a container - Unable to delete environment variable

### ISSUE THREAD

**Issue by marc-wilson** [microsoft/azure-container-apps#776]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When you have multiple envrionment variables defined, you are givin a trash can icon to delete them if needed. This trash can only appears if there are more than 1 environment variables. If you only have 1 environment variable, there is no trash can icon and you have to insert an empty variable to make the record "deletable"

### Steps to reproduce
Before beginning the below steps, make sure you have a Container app with at least 2 environment variables defined.
1. Go to a container app in the azure portal
2. Select Revisions -> Containers
3. Select Edit and deploy
4. Select a Container image
5. Select Edit
6. Delete one of the environment variables
7. Observe how you cannot delete the remaining environment variable

**Expected behavior** [What you expected to happen.]
I should be able to delete all environment variables.

**Actual behavior** [What actually happened.]
I am unable to delete an environment variable when there is only 1 in the list

**Screenshots**         
<img width="570" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/19480392/bc0c7069-fb1d-41b6-ab10-88fc5ba7613d">

<img width="565" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/19480392/cdfa2bce-1f34-423b-9dd7-a404bb20ba88">

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
Portal

**Comment by LianaAdaza** [comment]
Thank you for your report. We can't seem to replicate the issue, so we assume the portal bug has been fixed. Please feel free to reopen if you continue to encounter this difficulty
