### ISSUE TITLE
Running Status always showing processing and a question on Service add-ons

### ISSUE THREAD

**Issue by reza8i** [microsoft/azure-container-apps#781]
> Please provide us with the following information:
> Great sets of innovations guys. thank you!... Two questions:

1- Running Status is always showing as  "processing" in my container apps. Should I be worried?

 2- Why would i use service add-ons to spin up another container app and inject that to my container app via a bunch of environment variables while you've been always telling me that service to service communication is much better off to go through dapr? where does dapr fit into this whole new service to service communication?

**Comment by ahmelsayed** [comment]
> 2- Why would i use service add-ons to spin up another container app and inject that to my container app via a bunch of environment variables while you've been always telling me that service to service communication is much better off to go through dapr? where does dapr fit into this whole new service to service communication?

Service add-ons, or dev services, is just about providing an easy way to create a local postgres/redis/kafka/... instances that you can use to development and deployment. They are cost efficient because they run as regular container apps and can scale to 0 when not in use. They are also only accessible within the same VNET as other apps.

If you want to spin up a quick redis cache instance for development, you can just do 

```
az containerapp service redis create -n dev-redis-01 --environment $APP_ENV 
```

then make it accessible to your app with 

```
az containerapp update -n web-app --bind dev-redis-01 --environment $APP_ENV
```

and use `$REDIS_HOST` to connect to it. 

Dapr is an option to connect to such services. In your app, you can either use a sql, redis, or kafka client for your language to connect to pg, redis or kafka. Or abstract that with a dapr component that connect to the same service, and use the dapr abstractions in your code.

There is support to `--bind` a service to a dapr component that's coming shortly.

**Comment by ranjeetkpGit** [comment]
> 1- Running Status is always showing as "processing" in my container apps. Should I be worried?

I am getting same when I changes scale settings to 0-1. Any solution guys?
It works fine on 1-2.

**Comment by hesperanca** [comment]
> 1- Running Status is always showing as "processing" in my container apps. Should I be worried?
Same issue here. When scaling is changed to 0-x running status is showing as processing. I've also noticed that our "Standard vCPU Active Usage" have increased substantially so I don't think it's calculating the cost properly.

**Comment by SophCarp** [comment]
Hi @reza8i @ranjeetkpGit and @hesperanca 

We've updated running status to clarify these states. We now have: 

**Processing**: 1+ replicas, and some replicas being provisioned 
**Activating**: 0 replicas, 1 replica being provisioned 

Are you still encountering these issues?
We're trying to improve the running status for clarity - please let me know if there are any questions or suggestions!

**Comment by reza8i** [comment]
> Hi @reza8i @ranjeetkpGit and @hesperanca
> 
> We've updated running status to clarify these states. We now have:
> 
> **Processing**: 1+ replicas, and some replicas being provisioned **Activating**: 0 replicas, 1 replica being provisioned
> 
> Are you still encountering these issues? We're trying to improve the running status for clarity - please let me know if there are any questions or suggestions!

I think the issue has been resolved...now i see "Provisioned" in Provisioned State column and "Scaled to Zero" in Running Status column. I think it's all good now. Thank you

**Comment by reza8i** [comment]
> If you want to spin up a quick redis cache instance for development, you can just do
> 
> ```
> az containerapp service redis create -n dev-redis-01 --environment $APP_ENV 
> ```
> 
> then make it accessible to your app with
> 
> ```
> az containerapp update -n web-app --bind dev-redis-01 --environment $APP_ENV
> ```
> 
> and use `$REDIS_HOST` to connect to it.
> 
> Dapr is an option to connect to such services. In your app, you can either use a sql, redis, or kafka client for your language to connect to pg, redis or kafka. Or abstract that with a dapr component that connect to the same service, and use the dapr abstractions in your code.
> 
> There is support to `--bind` a service to a dapr component that's coming shortly.

Thanks for the detailed response. appreciate it. I am still wondering why we are making investments to make it easier for developers to build within the ACA service? Isn't the whole concept of containerization is to promote local dev without the hassles of specific lib dependency, runtime, version conflicts, etc abd easier deployments... i can do everything that service add-ons offer today locally in my docker desktop. why would i create a dependency on the ACA service ever for my local dev? I only want to connect to the ACA service when i am done development and now i want to deploy my container(s) to the service and expect it to work exactly the same way there...what am i missing?
