### ISSUE TITLE
Deploying environment with infrastructureSubnetId fails

### ISSUE THREAD

**Issue by Strandfelt** [microsoft/azure-container-apps#786]
### This issue is a:
- [X] bug report
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When deploying a Container App Environment with the `infrastructureSubnetId` property set to an existing subnet reference with a /23 address size, the deployment fails with the following error:
```
{
    "status": "Failed",
    "error": {
        "code": "ManagedEnvironmentInvalidNetworkConfiguration",
        "message": "The environment network configuration is invalid: The subnet and its addressPrefix could not be found."
    }
}
```

### Steps to reproduce
Deploy the following template:
```
param location string = 'westeurope'

var solutionName = 'sample'
var vNetName = 'vnet-${solutionName}'
var subnetName = 'snet-cae'
var caeName = 'cae-${solutionName}'

resource vNet 'Microsoft.Network/virtualNetworks@2022-11-01' existing = {
  name: vNetName

  resource caeSubnet 'subnets@2022-11-01' existing = {
    name: subnetName
  }
}

resource containerAppEnv 'Microsoft.App/managedEnvironments@2022-10-01' = {
  name: caeName
  location: location
  properties: {
    vnetConfiguration: {
      internal: false
      infrastructureSubnetId: vNet::caeSubnet.id
    }
    zoneRedundant: false
  }
}

```

**Expected behavior** 
Provisioning of container app environment.

**Actual behavior**
Deployment failed with message `The environment network configuration is invalid: The subnet and its addressPrefix could not be found.`

**Screenshots**         

**Additional context**
The Virtual Network is located in the same subscription in the same resource group and in the same region as the Container App Environment.

I have tried copying the actual value of `infrastructureSubnetId` from the JSON properties of an existing Container App Environment that was created from the portal, but that also failed with the same error during bicep deployment.

**Comment by cachai2** [comment]
@Strandfelt can you provide your environment name and a time stamp and email acasupport[at]microsodt[dot]com?

**Comment by Strandfelt** [comment]
> @Strandfelt can you provide your environment name and a time stamp and email acasupport[at]microsodt[dot]com?

Done

**Comment by Strandfelt** [comment]
Hello, anybody here? Seeing this issue still! @cachai2

**Comment by chinadragon0515** [comment]
@Strandfelt  you need to make container apps envs depends on vnet resource so vnet resource will be created first.
You can refer to https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/resource-dependencies on how to add dependencies.

**Comment by Strandfelt** [comment]
> @Strandfelt you need to make container apps envs depends on vnet resource so vnet resource will be created first. You can refer to https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/resource-dependencies on how to add dependencies.

@chinadragon0515  I am well aware of how this works. The VNET is already created, which is why I am using the keyword `existing` in bicep.

**Comment by chinadragon0515** [comment]
@Strandfelt The subnet you are using has addressPrefixes but does not have addressPrefix, and ACA only supports subnet with addressPrefix now.
You have successfully created an env with subnet with addressPrefix.
We will add support subnet with addressPrefixes.

**Comment by chinadragon0515** [comment]
AddressPrefixes is not supported and AddressPrefix is supported.
@muhammad-shameem your issue means there is some policy blocks the managed resource group or resources in this group creation/update, can you help to open new issue if you still have issue.

**Comment by psddp** [comment]
> Strandfelt Based on offline discussion, the subnet you are using has addressPrefixes but does not have addressPrefix, and ACA only supports subnet with addressPrefix now. You have successfully created an env with subnet with addressPrefix. We will add support subnet with addressPrefixes.

 @chinadragon0515  When will it be fixed? We have a vnet with multiple address ranges and ACA refuse to use it
