### ISSUE TITLE
Feature Request: Activate old revisions when using single revision mode in portal

### ISSUE THREAD

**Issue by morgan-cromell** [microsoft/azure-container-apps#787]
**Is your feature request related to a problem? Please describe**.  
Using single revision mode it is not possible to activate an old revision. This would make it easier to roll back to a previous revision in case of failures etc...

**Describe the solution you'd like**.    
Similar to multi-revision mode but you are only able to select one active revision. It would also automatically change the traffic to always be 100% on the selected revision.

**Describe alternatives you've considered**.   
A workaround for this has been to activate multi-revision mode, activate an old revision, and turn multi-revision off. You can also deploy a new revision with an old image tag. But none of these are intuitive.

**Additional context**.  
If I reload the revision screen in portal I am able to quickly see the "show inactive revision" checkbox and can click it in single revision mode. This will show all old revisions so they are still there in both multi and single revisions. I can however not change the active one in single-revision.

**Comment by ahmelsayed** [comment]
It's not exposed in the UI yet. But you can do it from the CLI (or API) while still in single revision mode with

```bash
$ az containerapp revision list --all --name $APP_NAME \
    --resource-group $RESOURCE_GROUP  \
    --output table --query "[].{Name:name, Created:properties.createdTime, Active:properties.active}"

# Name            Created                    Active
# --------------  -------------------------  --------
# app--rev1     2023-05-23T01:02:10+00:00  False
# app--rev2     2023-06-14T17:40:12+00:00  True

$ az containerapp revision activate --name $APP_NAME \
    --resource-group $RESOURCE_GROUP \
    --revision app--rev1

# "Activate succeeded"


$ az containerapp revision list --all --name $APP_NAME \
    --resource-group $RESOURCE_GROUP  \
    --output table --query "[].{Name:name, Created:properties.createdTime, Active:properties.active}"

# Name            Created                    Active
# --------------  -------------------------  --------
# app--rev1     2023-05-23T01:02:10+00:00  True
# app--rev2     2023-06-14T17:40:12+00:00  False
```

**Comment by morgan-cromell** [comment]
Thanks! Is there any timeline when this will be available in the azure portal UI?

**Comment by SophCarp** [comment]
Hi @morgan-cromell we've updated the portal UI! You should now have the option to see previous revisions in single revision mode and select them to activate. We're currently limiting it to just the last 5 inactive revisions. We're also in the middle of updating the revision blade UI to make the previous revisions easier to interact with. You can view the previous revisions by checking the "view inactive revisions" checkbox, which is now available in single revision mode.

**Comment by morgan-cromell** [comment]
@SophCarp. Thank you!

**Comment by SophCarp** [comment]
@morgan-cromell is it alright to close this issue?
