### ISSUE TITLE
Creation of new Azure Container Environments are not succeeding in location West Europe

### ISSUE THREAD

**Issue by bppn** [microsoft/azure-container-apps#792]
Since 15 june 2023, deployment of new Azure Container Environment keeps in "Created" state, does not got into state Succeeded.

Creation of new container apps is not possible since the container is still in waiting state.

Location: West Europe

The subscription is not reaching any quota, it seams to be a problem in the dc westeurope?

**Comment by torosent** [comment]
Same issue as #778. We are working on a fix

**Comment by torosent** [comment]
The issue was mitigated on the week of June 12.
