### ISSUE TITLE
cpa buildbundle - debian repo codename error

### ISSUE THREAD

**Issue by RPalejiya** [microsoft/azure-container-apps#797]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduce
1. ..docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /c/repo/path:/data --entrypoint "/bin/bash" mcr.microsoft.com/container-package-app:latest
cd data
az login --service-principal .....
az acr login ....
cpa buildbundle
2. ..

**Expected behavior** [What you expected to happen.]
It should build bundle

**Actual behavior** [What actually happened.]
=========Following is the error for buildbundle command.==============
[+] Building 7.3s (12/23)
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 1.32kB                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                        0.0s
 => resolve image config for docker.io/docker/dockerfile-upstream:1.4.0                                                                                                0.8s
 => CACHED docker-image://docker.io/docker/dockerfile-upstream:1.4.0@sha256:178c4e4a93795b9365dbf6cf10da8fcf517fcb4a17f1943a775c0f548e9fc2ff                           0.0s
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/debian:stable-slim                                                                                                  0.9s
 => [stage-0  1/15] FROM docker.io/library/debian:stable-slim@sha256:b09f68bffcf9c14f3105f262e92321d05abaf48460d1f43f884325bcd4395b95                                  1.2s
 => => resolve docker.io/library/debian:stable-slim@sha256:b09f68bffcf9c14f3105f262e92321d05abaf48460d1f43f884325bcd4395b95                                            0.0s
 => => sha256:aad73c16cd7c4529e0b6661c0d20d5a19813f51757cd4e64f5a9dbdeed1bf67a 1.46kB / 1.46kB                                                                         0.0s
 => => sha256:16fad9514333424f5386d1127e84d3a8318488071c44ef1161dfcb7e9dc66ebd 29.12MB / 29.12MB                                                                       0.4s
 => => sha256:b09f68bffcf9c14f3105f262e92321d05abaf48460d1f43f884325bcd4395b95 1.85kB / 1.85kB                                                                         0.0s
 => => sha256:cb4f1877372e3b13a254fca5e7345a48a2f3e6accbd29d36f94101049ad661ec 529B / 529B                                                                             0.0s
 => => extracting sha256:16fad9514333424f5386d1127e84d3a8318488071c44ef1161dfcb7e9dc66ebd                                                                              0.7s
 => [internal] load build context                                                                                                                                      0.9s
 => => transferring context: 203.74MB                                                                                                                                  0.8s
 => [stage-0  2/15] RUN useradd nonroot -m -u 65532 -g 0 -o                                                                                                            0.5s
 => [stage-0  3/15] RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache             0.5s
 => ERROR [stage-0  4/15] RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt     apt-get update && apt-get install -y ca-certificate  2.9s
------
 > [stage-0  4/15] RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt     apt-get update && apt-get install -y ca-certificates:
#0 1.974 Get:1 http://deb.debian.org/debian stable InRelease [147 kB]
#0 2.170 Get:2 http://deb.debian.org/debian stable-updates InRelease [52.1 kB]
#0 2.328 Get:3 http://deb.debian.org/debian-security stable-security InRelease [48.0 kB]
#0 2.380 Reading package lists...
#0 2.814 E: Repository 'http://deb.debian.org/debian stable InRelease' changed its 'Codename' value from 'bullseye' to 'bookworm'
#0 2.814 E: Repository 'http://deb.debian.org/debian stable-updates InRelease' changed its 'Codename' value from 'bullseye-updates' to 'bookworm-updates'
#0 2.814 E: Repository 'http://deb.debian.org/debian-security stable-security InRelease' changed its 'Codename' value from 'bullseye-security' to 'bookworm-security'
=========================================================

------

**Screenshots**         

### Additional context
This same repo use to work a week back without any code change. Is there a way to use previous version of azure-container-apps image for the version it use to work until this issue is fixed?

**Comment by RPalejiya** [comment]
I think issue is originating from Debian 12 release on June 10th. .cnab/dockerfile points to 'debian:stable-slim' image and it fails for the "apt-get update" command. Using the older image tag for Debian seems to avoid the codename error. 

Similar impact is observed in other project using Debian image discussed here. https://github.com/Azure/azure-functions-docker/issues/905 

Can someone help to fix this please?

**Comment by torosent** [comment]
@RPalejiya , did you encounter this issue in Azure Container Apps? from your sample and attached issue it doesn't looks like it is related to ACA.

**Comment by RPalejiya** [comment]
My Bad, Issue is in container-package-app. So wrong repo posting. Apologies for that.
