### ISSUE TITLE
containerJobs wrong type information for triggerType (Scheduled -> Schedule)

### ISSUE THREAD

**Issue by floriankoch** [microsoft/azure-container-apps#798]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The type informations for containerJobs trigger type  says the value ist Schedule**d**, but it only works with **Schedule**
API Version 2022-11-01-preview
Docs saying **Schedule**  https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-resource-manager

**Expected behavior** [What you expected to happen.]
Type information and Docs should be  the same
**Actual behavior** [What actually happened.]
Type Information and Docs are different
**Screenshots**  
   Vscode (Bicep)
<img width="948" alt="Screenshot 2023-06-18 at 10 47 06" src="https://github.com/microsoft/azure-container-apps/assets/13452311/8baee1de-64a7-4516-9d95-815b2b518da4">
  
 Portal
<img width="505" alt="Screenshot 2023-06-18 at 10 57 17" src="https://github.com/microsoft/azure-container-apps/assets/13452311/f1d7e41a-ad06-48e0-b1c1-1bcd800bf6d9">

### Additional context
Bicep  / vscode / Portal

**Comment by anandanthony** [comment]
The trigger type shown as `Scheduled` is due to an incorrect spec for the current API versions. We have addressed this and the correct type would be seen in the next API versions. The correct type for Scheduled Container App Jobs is `Schedule`.
