### ISSUE TITLE
Replica not shutting down gracefully (no SIGTERM sent/received) on consumption workload profile + VNet

### ISSUE THREAD

**Issue by richardkooiman** [microsoft/azure-container-apps#802]
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We've observed our .NET application is not shutting down gracefully whenever a replica is being shutdown (should happen every time a new revision is being created). We've concluded this based on missing logs and shutdown logic not being executed.
Our setup uses an environments with a default consumption workload profile, combined with a custom VNet.
As a comparison we tested with the 'older' environments (without workload profiles and without VNet). In that case all seems to be working as expected (logs indicating the application is shutting down, both in the log stream aswell as in the analytics workspace).

### Steps to reproduce
1. Create Azure Container App Environment with default consumption workload profile and custom VNet
2. Create app with a revision of a sample image: mcr.microsoft.com/dotnet/samples:aspnetapp
3. Shutdown existing replica by restarting or creating a new revision.

**Expected behavior**
- SIGTERM is sent to the replica on shutdown to allow graceful shutdown;
- Startup logs visible in log stream and log analytics;
- Shutdown logs visible in log stream and log analytics.

**Actual behavior**
- SIGTERM is NOT sent to the replica on shutdown so graceful shutdown doesn't happen (replica just gets killed);
- Startup logs visible in log stream and log analytics;
- Shutdown logs NOT visible in log stream and log analytics.

**Screenshots**
n/a

### Additional context
- Container app environment was created with Bicep: Microsoft.App/managedEnvironments@2022-11-01-preview
- Container app was created with Bicep: Microsoft.App/containerApps@2022-11-01-preview
- Noticed the newer container app Bicep definition (2023-04-01-preview) contains a new property: terminationGracePeriodSeconds. It describes that if the value is 'nil', the default grace period of 30 seconds is used. If the value is '0', the replica will be killed without graceful shutdown. As we're using the older Bicep definition we're not using this property, but maybe Azure internally has a default of '0' instead of 'nil' on recently created container apps?

[Updated 2023/07/31]
- The missing SIGTERM is only observed when running on a Consumption workload. When running on a Dedicated workload, the SIGTERM is actually received and we're able to gracefully shut down.

[Updated 2024/04/05]
- Have not looked at this for some time since we migrated to the dedicated workloads. But did a test today by running the app on a consumption workload profile and seems the issue has been resolved. When restarting a revision, the old replica receives a SIGTERM (observed by logs) and is able to shut down gracefully.

**Comment by TrayanZapryanov** [comment]
@richardkooiman Can you help me with a sample code/article how you hook to SIGTERM/shutdown event in .NET?
I want to hook into our app and to be able gracefully shutdown but haven't found any sample code demonstrating this.
Thank you very much in advance.

**Comment by richardkooiman** [comment]
Hi @TrayanZapryanov, thanks for looking into this!

**Our case**
We are registering hosted services (IHostedService) of which the StopAsync() method should be called on graceful shutdown. This works when running locally on a development environment, but does not work when running in the mentioned Azure Container Apps environment setup.

**Reproduction on Azure Container Apps**
When running the sample application image (mcr.microsoft.com/dotnet/samples:aspnetapp), the default WebApplicationBuilder (or other host builders for that matter) already hook into the application lifetime and generate logs on startup and shutdown (https://source.dot.net/#Microsoft.Extensions.Hosting/Internal/ConsoleLifetime.cs,84).
When running the mentioned image on our Azure Container Apps environment setup, we see the startup logs, but we do not see the shutdown logs (both in log stream as also in the log analytics workspace).

**Sample of manual registration to listen for shutdown (e.g. SIGTERM)**
This will generate a custom additional log entry on shutdown (besides the default log entry as mentioned above).
```csharp
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.Lifetime.ApplicationStopping.Register(() =>
{
    Console.WriteLine("Test log on shutdown.");
});

await app.RunAsync();
```

**Comment by richardkooiman** [comment]
Update: The missing SIGTERM is only observed when running on a Consumption workload. When running on a Dedicated workload, the SIGTERM is actually received and we're able to gracefully shut down.

**Comment by bogdanioanliviu** [comment]
> Update: The missing SIGTERM is only observed when running on a Consumption workload. When running on a Dedicated workload, the SIGTERM is actually received and we're able to gracefully shut down.

Same thing happend to me with a linux image (for Devops agent ). With consumption workload the SIGTERM it's never received but with a dedicated workload profile it works as expected. As well it works with Consumption internat (not workload.)

**Comment by richardkooiman** [comment]
Have not looked at this for some time since we migrated to the dedicated workloads. But did a test today by running the app on a consumption workload profile and seems the issue has been resolved. When restarting a revision, the old replica receives a SIGTERM (observed by logs) and is able to shut down gracefully.

Thanks for fixing whoever did this! 😊
