### ISSUE TITLE
InternalServerError when deploying Bicep with Azure Container App

### ISSUE THREAD

**Issue by maikelvanhaaren** [microsoft/azure-container-apps#806]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
InternalServerError occurred when deploying Bicep with Azure Container App

### Steps to reproduce
1. Create a bicep with an Azure Container App Environment and Azure Container App
2. Deploy to Azure

**Expected behavior** [What you expected to happen.]

- Resources are created

**Actual behavior** [What actually happened.]

- Internal server error occurred.

### Additional context
Deploying bicep through Azure CLI in an Azure Pipeline

ARM deployment response for the specific container app:

```json
{
    "status": "Failed",
    "error": {
        "code": "InternalServerError",
        "message": "Internal server error occurred. correlation ID: 405f0021-e93e-4892-8833-f308fbd7db11"
    }
}
```

**Comment by g0dm0d3** [comment]
We have the same issue with container app deployment within terraform.

**Comment by dchasani** [comment]
We have the same issue with container apps deployment

**Comment by rs-troper** [comment]
Same issue here. Cannot deploy via ARM template, nor via the UI. I cannot provision a new replica, or restart the current one. My application is down and all paths to restart or redeploy are throwing a 500 Internal Server Error.

**Comment by vturecek** [comment]
@maikelvanhaaren this should be resolved now, can you give it another try and let us know if you still see this error?
