### ISSUE TITLE
All revision deployment actions via both CLI and UI are returning 500 Internal Server Error 

### ISSUE THREAD

**Issue by rs-troper** [microsoft/azure-container-apps#808]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
Creating a new revision or restarting an existing revision fails with a 500 Internal Server Error. This includes both CLI and via the Azure Portal UI.

### Steps to reproduce
**Via UI:**
1. Login to Azure Portal
2. Navigate to Container Apps
3. Go to "Revisions"
4. Try "Create New Revision", or navigate to an existing revision and choose "Restart"

**Via CLI:**
1. Run `az containerapp update`

> Starting script execution via docker image mcr.microsoft.com/azure-cli:2.49.0
WARNING: Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: The command requires the extension containerapp. It will be installed first.
WARNING: The installed extension 'containerapp' is in preview.
WARNING: Updating existing registry.
ERROR: (InternalServerError) Internal server error occurred. correlation ID: 20c6c2b4-c77d-4eaf-84a0-a60c9213463a
Error: Error: az cli script failed.

**Comment by limoniapps** [comment]
Running into the same issue.
All containers in one specific container app environment are all down.
The log in the container app environment reads the following when attempting to access the container:
"Msg":"startup probe failed: connection refused","Reason":"ReplicaUnhealthy"
Recreating the container app environment and containers resolves the issue.

Any attempts to make changes and deploy a revision also fail.
Error message: Failed to deploy new revision: Internal server error occurred. correlation ID: 967df002-1219-428f-ab91-ed39cfa11e31

**Comment by faheemgani** [comment]
Hi, we are seeing the same issue, we are using Azure Container Apps organization wide and we are getting this issue across all of our apps deployed into one of our container app environments. All container app environments are hosted within the same region (UK South).

We can physically browse to the apps (they appear to be running). However, the existing revisions don't load under the 'Revision Management' tab, and when going to the 'Containers' page the container details do not appear to load.

If we try and create a new revision or update an existing revision through the CLI or portal we get a 500 response code:

`{
    "status": "Failed",
    "error": {
        "code": "InternalServerError",
        "message": "Internal server error occurred. correlation ID: 57cb37ec-c616-47ca-bb17-3eedb70a5cf3"
    }
}`

Our teams are relying on these environments being available and we need to be able to deploy changes to the apps. It is concerning that this issue has been ongoing for 3 days and there isn't a workaround or fix in place.

We are considering deleting and re-provisioning the container app environment and the apps within it, can you advise whether this will resolve the issue?

**Comment by torosent** [comment]
Thank you for adding the correlation id. We are investigating.

**Comment by vturecek** [comment]
@rs-troper, @limoniapps, @faheemgani - thanks for your patience. The problem should be resolved now, can you give it another try and let us know if you still see the error?

**Comment by faheemgani** [comment]
@vturecek Thanks for the update - all seems to be working fine for us now. 

Do you know what the root cause was?

**Comment by faheemgani** [comment]
@vturecek @torosent We have started seeing the same issue again, same container app environment... What is going on?

``(InternalServerError) Internal server error occurred. correlation ID: 7dc6122e-ede9-4170-8774-47bdf66305f7``

**Comment by torosent** [comment]
@faheemgani, The first issue was due to a cluster version upgrade that failed in a few clusters. That issue was addressed and fixed. 
The second request with the correlation id `7dc6122e-ede9-4170-8774-47bdf66305f7` is a transient request failure with AKS. If you retry the request it would solve it. 
We are actively working to fix these kind of transient 500 errors..
