### ISSUE TITLE
Cannot configure authentication via Portal or AZ CLI

### ISSUE THREAD

**Issue by Jade-Codes** [microsoft/azure-container-apps#810]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When configuring authentication for a Container App using the Microsoft provider, this error is generated in the activity log 'Unknown properties tokenStore in Microsoft.ContainerApps.WebApi.Views.Version20221101Preview.LoginView are not supported'.

There is a brief toast displayed on the website 'Failed to add Microsoft identity provider settings'. The App registration is created in the 'Default Directory' but it is not attached to the app. Trying again and choosing 'Pick an existing app registration in this directory' gives the same error.

### Steps to reproduce
1. Add Azure AD Authentication to Container App via Azure Portal 

**Expected behavior** [What you expected to happen.]
1. Add Azure AD Authentication to Container App via Azure Portal 
2. Successfully added

**Actual behavior** [What actually happened.]
1. Add Azure AD Authentication to Container App via Azure Portal 
2. Error saying 'Failed to add Microsoft identity provider settings'
3. Error in activity log 'Unknown properties tokenStore in Microsoft.ContainerApps.WebApi.Views.Version20221101Preview.LoginView are not supported'.

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/9397730/73531e8e-a619-4ae4-adba-8f93fefe27f3)

### Additional context
Initially raised here: https://learn.microsoft.com/en-us/answers/questions/1310672/container-apps-authentication-error-cannot-configu

**Comment by Jaydee123** [comment]
I was able to successfully add authentication doing the following api rest call, when not using the tokenStore property:

PUT:
`https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.App/containerApps/{{containerAppName}}/authConfigs/{{authConfigName}}?api-version=2022-11-01-preview`

Body:
```
{
  "properties": {
    "platform": { "enabled": true },
    "identityProviders": {
      "azureActiveDirectory": {
        "isAutoProvisioned": false,
        "registration": {
          "clientId": {{clientId}},
          "clientSecretSettingName": "microsoft-provider-authentication-secret",
          "openIdIssuer": "https://sts.windows.net/{{tenantId}}/v2.0"
        },
        "validation": { "allowedAudiences": ["api:/{{clientId}}"] }
      }
    },
    "login": {},
    "globalValidation": {
      "redirectToProvider": "azureactivedirectory",
      "unauthenticatedClientAction": "RedirectToLoginPage"
    }
  }
}
```

**Comment by torosent** [comment]
Hi. Token store is not supported yet. This feature is currently in progress.

**Comment by Jaydee123** [comment]
@torosent I'm not trying to use token store. This is what happens when you try and add authentication via the portal...

**Comment by torosent** [comment]
Thanks. We are checking why it's happening

**Comment by rliberoff** [comment]
The very same issue is happening to me. It wasn't happening a month ago. The issue happens when trying to add Authentication to an Azure Container App with Microsoft.

I get the very same error message in the Azure Portal:

![image](https://github.com/microsoft/azure-container-apps/assets/5644891/6f912455-7459-45de-b253-36c3d8d560e7)

**Comment by kokelowo** [comment]
A fix for this bug has been deployed. Please and let us know if it's still and issue for you.
