### ISSUE TITLE
Cannot use existing infrastructureResourceGroup when creating a new Consumption + Dedicated managed environment

### ISSUE THREAD

**Issue by jlosenicky** [microsoft/azure-container-apps#811]
### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When creating a Consumption + Dedicated managed environment I am required to provide a resource group that will be used for hosting infrastructure resources; if this resource group already exists I get an error stating as such. The alternative is to provide a name that doesn't exist and let Azure create the resource group but that doesn't work in my case as my company has an Azure policy in place requiring certain tags and so the resource group create gets rejected by policy.

### Steps to reproduce
1. In the portal, begin creating a new container app and choose to create a new environment.
2. For the new new environment, choose Consumption and Dedicated workload profile.
3. In the networking tab, choose a resource group that already exists for for "Infrastructure resource group".
4. Complete setup of the container app.
5. Upon deploy, get an error indicating the infrastructure resource group already exists.

**Expected behavior** [What you expected to happen.]
The existing resource group is used by the managed environment.

**Actual behavior** [What actually happened.]
Error when deploying the managed environment.

**Screenshots**
*Choose an existing resource group.*
![image](https://github.com/microsoft/azure-container-apps/assets/10156584/26925b4d-8a55-4f99-9b82-95f9e4534f32)

*Error when using an existing resource group.*
![image](https://github.com/microsoft/azure-container-apps/assets/10156584/b9f46732-a07b-49c0-aead-a4ade0fd48fb)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by torosent** [comment]
Hi, you can't use an existing resource group. It must be created empty and managed by ACA.

**Comment by jlosenicky** [comment]
> ...but that doesn't work in my case as my company has an Azure policy in place requiring certain tags and so the resource group create gets rejected by policy.

What's the recommendation for the case I mentioned where a policy causes the managed resource group create to fail? As far as I can tell there's no way to pass those tags in. The only workaround I can think of is to temporarily disable that policy or put some sort of exception in place based upon maybe a naming convention; neither one seem like a very user friendly solution.

**Comment by torosent** [comment]
If it's just tags propagation then you should have these options in the create flow. The environment tags will propagate to the managed resource group.
<img width="811" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/17064840/4b446312-7535-40a4-926e-456aac4b5508">

**Comment by jlosenicky** [comment]
That doesn't seem to be working either:

When creating a container app opt to create a new environment, Consumption + Dedicated, and specify the infrastructure resource group.
![image](https://github.com/microsoft/azure-container-apps/assets/10156584/115403b4-cc95-4ca3-80dd-975d9cbfad38)

Continue creating the container app and specify the required tags:
![image](https://github.com/microsoft/azure-container-apps/assets/10156584/a2ea64a8-7f2b-499b-812d-9f33fc17b61d)

The infrastructure resource group gets rejected by policy, you can see here one of the tags it's complaining about which is added in the above screenshot.
![image](https://github.com/microsoft/azure-container-apps/assets/10156584/17e40884-f471-4cc8-ac52-db7ffea950e2)

**Comment by torosent** [comment]
sending me you subscription id and correlation id to `acasupport at microsoft dot com`. The on call engineer will take a look.

**Comment by torosent** [comment]
@jlosenicky, we found the bug a fixed it. The fix will be deployed in the upcoming two weeks.

**Comment by penfold** [comment]
Has the 'Infrastructure Resource Group' input been removed? Or is not yet available in UKSouth?

![image](https://github.com/microsoft/azure-container-apps/assets/342662/fb1ebf5b-0535-4689-bc2d-b826ab998988)

I'm populating it in my Bicep script but it is ignored.

![image](https://github.com/microsoft/azure-container-apps/assets/342662/68edad59-5e83-4d1a-af20-f588564aeb18)

Related question:
If I don't populate infrastructureResourceGroup, then will/should it be populated in my Bicep script once the CAE is created?

**Comment by ryancastle** [comment]
This works correctly as described by @torosent. Might be worth articulating the propagation of tags in the documentation. It's not intuitive that a resource group is a "child" of the environment.

The error you currently see is also confusing - it implies you might be able to nominate an existing resource group if it's "unassigned".

> The resource group  /subscriptions/.../resourceGroups/... already exists or is assigned to another managed environment

**Comment by peter-bertok** [comment]
It is still not possible to create a Container App and its environment via the Azure Portal for any organisation that enforces mandatory Tags on their Resource Groups.

**Comment by mike-wood-oli** [comment]
In addition when using Deployment stacks. The stack will succeed for the first run, but subsequent runs will fail because the resource group is no longer empty.

**Comment by toni-miettinen** [comment]
@mike-wood-oli how about terraform / bicep?
