### ISSUE TITLE
Error pulling private image from registry.hub.docker.com

### ISSUE THREAD

**Issue by acomarce** [microsoft/azure-container-apps#817]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When creating an app using AzureContainerApps which uses a private image hosted on registry.hub.docker.com, the following error is returned in the Azure UI : `The following field(s) are either invalid or missing. Field 'template.containers.theimage.image' is invalid with details: 'Invalid value: "registry.hub.docker.com/theimage:latest": GET https:: unexpected status code 401 Unauthorized: {"detail": "user_id not found in jwt", "error": true}
';. (Code: InvalidParameterValueInContainerTemplate)`
### Steps to reproduce
1. Create a private repository on Docker Hub (free tier) 
2. Enable 2FA on the DockeHub account
3. Create a new access token on Docker hub with the `Read,Write,Delete` permissions
4. Push an alpine .Net 8-preview-5 based asp.net image to the repository
5. Create a new Azure container app
6. Create a new App, as part of the steps provide the following data:
 Image source: Docker hub or registries
 Image type: private
 Registry login server: [registry.hub.docker.com ](https://stackoverflow.com/a/74239780/3073551)
 Registry user name: The username used to log in to the Docker Hub UI
 Registry password: The access token value
 Image and tag: theimage:latest
0.25CPU 0.5 Memory.
7. Click Create 

**Expected behavior** 
The image is pulled from the private registry using the credentials provided

**Actual behavior** 
Receive the following error: `The following field(s) are either invalid or missing. Field 'template.containers.tgwwod.image' is invalid with details: 'Invalid value: "registry.hub.docker.com/tgwwod:latest": GET https:: unexpected status code 401 Unauthorized: {"detail": "user_id not found in jwt", "error": true}
';. (Code: InvalidParameterValueInContainerTemplate)`

### Additional context
Error occurs in the portal

**Comment by JMackCo** [comment]
same issue here. Cannot pull an image from my Docker Hub private registry.

**Comment by acomarce** [comment]
This resolves the issue, it might be useful to update the documentation on the exact syntax you need for the `image` field, for anyone stuck on this it's: `"${var.dockerRegistryUrl}/${var.dockerRegistryUsername}/${var.appName}:${var.dockerImageTag}"`.

**Comment by dyllandry** [comment]
This issue is still happening and came up in an older issue: https://github.com/microsoft/azure-container-apps/issues/817

Using docker.io as the registry login server is supposed to work.

If you create a Container App, choose "Docker Hub or other registries", choose "Private" for image type,  the "Registry login server" field will autofill with `docker.io`. This sets you up to fail as images pulled from that url don't work. You need to use `registry.hub.docker.com` instead.

**Comment by serdar** [comment]
I'm having this issue as well!
I followed the workaround  @dyllandry mentioned and added a new set of credentials for `registry.hub.docker.com`. It seems as though it's having problems piecing together the URL to pull the image from Docker Hub:

> Failed to deploy new revision: Failed to provision revision for container app 'app-demo'. Error details: The following field(s) are either invalid or missing. Field 'template.containers.presidio-anonymizer.image' is invalid with details: 'Invalid value: "registry.hub.docker.com/mcr.microsoft.com/presidio-anonymizer:latest": GET https:: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:mcr.microsoft.com/presidio-anonymizer 

The image I'm trying to retrieve is: https://hub.docker.com/r/microsoft/presidio-anonymizer

**Comment by dyllandry** [comment]
@serdar I found for public images, like redis, that docker.io works. registry.hub.docker.com worked for our private image.

**Comment by serdar** [comment]
Thanks @dyllandry I'll keep trying - the fact that it deletes the config if it fails is annoying, I'd rather have it left in a disconnected state so that I can edit and retry rather than adding all configs again.
