### ISSUE TITLE
Azure Function with http trigger internal ingress?

### ISSUE THREAD

**Issue by Markz878** [microsoft/azure-container-apps#818]
I tested deploying a http triggered Azure Function to my container apps environment, but I can't see any way to make the endpoint internal to the environment. Is there a way to make it behave like internal ingress, or could this feature be added?

**Comment by Markz878** [comment]
It was Azure function directly on Container Apps. I didn't notice the option to containerize the Functions runtime myself. I will look into this, thanks!

**Comment by havarnov** [comment]
This issue is "closed this as completed", but I can't find any documentation on how to actually configure an internal ingress?
