### ISSUE TITLE
Authentication causing undesirable behaviour when there are multiple replicas

### ISSUE THREAD

**Issue by Jade-Codes** [microsoft/azure-container-apps#820]
### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When I am using authentication with multiple replicas, the container app is only successfully authenticating against one of the replicas, which is causing undesirable behaviour in my application

### Steps to reproduce
1. Have a container app with two replicas
2. Have ingress enabled
3. Have a custom domain configured for the container app
4. Have authentication set up with a redirect uri for the custom domain

**Expected behavior** [What you expected to happen.]
I can login to the application successfully and no errors due to authentication occur

**Actual behavior** [What actually happened.]
I can intermittently login, but received a lot of errors when doing so, the errors I receive are:
'react_devtools_backend_compact.js:2367 TypeError: Failed to fetch dynamically imported module:'
'React Router caught the following error during render TypeError: Failed to fetch dynamically imported module:'
'Access to manifest at ... has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.'
'login.windows.net/.../oauth2/v2.0/authorize? ... net::ERR_FAILED 302 (Found)'

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/9397730/12f2efc2-ca48-4923-94ec-30f70aa6e1da)
![image](https://github.com/microsoft/azure-container-apps/assets/9397730/77f328f7-d05c-4ea8-be54-fec1a13e01a3)

### Additional context
**This issue is resolved when I enable 'Session Affinity' and I can successfully login to my application with no issues**

**Comment by ahmelsayed** [comment]
/cc @njucz


I think this needs either token store or session affinitly.

**Comment by anthonychu** [comment]
@Jade-Codes can you please provide more details on how you configured auth for your app? It’s unclear if you are using the built-in authentication feature in Container Apps or something else. Thanks.

**Comment by Jade-Codes** [comment]
@anthonychu yes I am using in built container apps authentication with a redirect.

I am using the built in authentication as documented here:
https://learn.microsoft.com/en-us/azure/container-apps/authentication
With Azure AD

**Comment by njuCZ** [comment]
Hi @Jade-Codes may I confirm that your app is trying to get the info of authenticated user? If that's the case, you need to set token store or session affinity. If your app is just showing info which is unrelated with login user, I think there should be no such issue.

**Comment by Jade-Codes** [comment]
Hi @njuCZ no my app doesn't know anything about the authentication nor did I want it to for this iteration, I am not using anything in the code to reference the authentication. Do I need to?

**Comment by Jade-Codes** [comment]
@njuCZ I have yes, I am using a react application and using the deployment image from here:
https://github.com/IQEngine/IQEngine

**Comment by njuCZ** [comment]
@Jade-Codes I changed to use your image, it still works without enabling session affinity
![image](https://github.com/microsoft/azure-container-apps/assets/2786738/11e17f3d-c326-42c9-856f-1c4a79dd5549)

**Comment by njuCZ** [comment]
Can you directly ping me your container app resource id so I can take a check?

**Comment by Jade-Codes** [comment]
@njuCZ what's your name sorry? I can ping you via Teams

**Comment by njuCZ** [comment]
zhcheng

**Comment by Jade-Codes** [comment]
After investigating with @njuCZ I can determine the issue was due to not having a configured secret for the application which resolves my issue. I am closing this ticket.
