### ISSUE TITLE
Typo in error when failing to connect to Console

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/azure-container-apps#830]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I recently had a container app where connecting to the console via the portal  failed. The error (below) includes the typo `Kubsernetes`:

```json
{"Error":{"Code":"ClusterExecEndpointWebSocketConnectionError","Message":"Failed to establish WebSocket connection with the container, error is Failed to establish WebSocket connection with Kubsernetes cluster exec endpoint, error: The server returned status code \u0027500\u0027 when status code \u0027101\u0027 was expected..","Details":null,"Target":null,"AdditionalInfo":null}}
```

### Steps to reproduce
1. .. With a container that fails to start, attempt to connect to the console via the portal

**Expected behavior** [What you expected to happen.]
Expect the error to include `Failed to establish WebSocket connection with Kubernetes cluster exec endpoint`

**Actual behavior** [What actually happened.]
The actual error includes `Failed to establish WebSocket connection with Kubsernetes cluster exec endpoint`

**Screenshots**         

### Additional context
n/a

**Comment by LianaAdaza** [comment]
Thank you for reporting this! Fix has been rolled out. Please create a new issue if you continue to experience difficulties.
