### ISSUE TITLE
Feature Request: Azure File Share support in Container Jobs

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/azure-container-apps#832]
**Is your feature request related to a problem? Please describe**.  
Enable mounting Azure File Shares in Container Jobs

**Describe the solution you'd like**.    
I'd like to be able to specify an Azure File Share as a volume mount for a Container Job (I attempted this but it didn't get mounted)

**Describe alternatives you've considered**.   
Current alternative would be to rewrite the job as a standard container app with a Dapr cron trigger.

**Additional context**.  
n/a

**Comment by stuartleeks** [comment]
cc @anthonychu

**Comment by torosent** [comment]
We are working on it. ETA: August 2023

**Comment by guydillen** [comment]
What’s the status on this?

**Comment by mcapinha-mxp** [comment]
Hey @torosent , any updates on this?

We're running our production load on container apps and it's been a nice experience. We'd like to start using Azure Container Jobs (it would solve quite a few problems for us) but not being able to mount our volumes is a blocker.

**Comment by stuartleeks** [comment]
I have this working for a project that I deployed to Container Jobs as of a couple of months ago, so I'll close this issue 😄 

Also worth noting this thread around setting mount options: https://github.com/microsoft/azure-container-apps/issues/520
