### ISSUE TITLE
Clarification needed on HTTP -> HTTPS redirect

### ISSUE THREAD

**Issue by FrostSalamander** [microsoft/azure-container-apps#833]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Requesting clarification on HTTP -> HTTPS upgrade.  The documentation says that by default,  HTTP requests are [redirected to HTTPS by default](https://learn.microsoft.com/en-us/azure/container-apps/ingress-overview#http).  Is there a way to disable this behavior? I couldn't find any reference to that anywhere.  

I'm seeing problems in some applications due to this.  For example, if you send traffic through a reverse proxy (e.g. Nginx) hosted on Container Apps and set `proxy_set_header $host`, you'll get a 403 error.  I'm guessing this is because the hostname no longer matches  the upstream host and a TLS handshake fails.  I say 'I'm guessing' because there is no way to troubleshoot this - all you get is a 403.

Also, you can't always seem to call an upstream app using `https://app-name`.  Back to the nginx example, you need to use the full FQDN for some reason.  There is a blog post about it here, but there is no insight as to why this is required: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/use-nginx-as-a-reverse-proxy-in-azure-container-app/ba-p/3870513

I could be completely wrong about all this, but something is going on that I don't quite understand. 

You can test this by sending a request to the HTTP endpoint of any public-facing app in ACA and changing the host header:

```
curl -v -H "Host: somehost.com" http://hello-world--q47nwtm.jollysky-9d68b8d3.uksouth.azurecontainerapps.io/
*   Trying 20.68.184.106:80...
* TCP_NODELAY set
* Connected to hello-world--q47nwtm.jollysky-9d68b8d3.uksouth.azurecontainerapps.io (20.68.184.106) port 80 (#0)
> GET / HTTP/1.1
> Host: somehost.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< date: Sun, 16 Jul 2023 15:49:42 GMT
< content-length: 0
< 
* Connection #0 to host hello-world--q47nwtm.jollysky-9d68b8d3.uksouth.azurecontainerapps.io left intact
* 
```

**Comment by ahmelsayed** [comment]
You can set `allowInsecure: true` on your app to disable https redirect https://learn.microsoft.com/en-us/azure/container-apps/ingress-how-to#ingress-settings 

If you want to use the app name, it should be `http://app-name`, not http**s**. See https://learn.microsoft.com/en-us/azure/container-apps/connect-apps

```
curl -v -H "Host: somehost.com" http://hello-world--q47nwtm.jollysky-9d68b8d3.uksouth.azurecontainerapps.io/
```

You'll need to have `somehost.com` as a custom domain on the app `hello-world` for that command to work.

**Comment by FrostSalamander** [comment]
okay so `allowInsecure: true` disables HTTPS redirect.  Thanks for clarifying that.

And just so I understand:

- using `http://app-name` is the ONLY way to call an internal app using the app name
- using `http://app-name` will use either HTTP or HTTPS, depending on the setting of `allowInsecure`?
- you cannot rewrite the host header for any app that doesn't use a custom domain to match the host header.

The second point is important, as customers will want to understand 100% if the traffic is encrypted or not (even if it's internal).  I would suggest it's worth clarifying this in the document.

Thanks

**Comment by ahmelsayed** [comment]
> using http://app-name is the ONLY way to call an internal app using the app name

Correct. 

> using http://app-name will use either HTTP or HTTPS, depending on the setting of allowInsecure?

No, allowInsecure only affects the fqdn i.e: `http://app-name.env-name.region.azurecontainerapps.io` domains. 

However, you can enable mtls on the environment (`az containerapp env update --enable-mtls ...`) to make sure all traffic routed inside the environment is encrypted. This includes edge proxy to apps, and app to app

You will still be calling `http://app-name`, the mtls/encryption is transparent as traffic is redirected through proxies that authenticate/encrypt with each other.
