### ISSUE TITLE
Azure Container App Environment is represented like an App Service Plan in Azure Portal

### ISSUE THREAD

**Issue by ThorstenHans** [microsoft/azure-container-apps#85]
I've created an Azure Container App Environment today. Surprisingly, Azure Portal presents it like an Azure App Service Plan, which is a kind of confusing and seams to be a bug.

Because it is presented in the wrong way, users are not able to browse Container Apps from the Container App Environment Blade in Azure Portal.

![image](https://user-images.githubusercontent.com/357884/151146747-1c2c7440-3c6a-4992-a0e9-832fbd996c63.png)

In contrast, here a screenshot of an Azure Container App Environment that I've created back in December 2021.

![image](https://user-images.githubusercontent.com/357884/151146772-627a3d7d-f293-4474-8f48-0e64ab621af3.png)

**Comment by vturecek** [comment]
Hi @ThorstenHans, thanks for reporting this. It is indeed a bug in the portal and we are working on a fix.

**Comment by torosent** [comment]
Hi @ThorstenHans. This issue should be resolved now.

**Comment by ThorstenHans** [comment]
@torosent can confirm it is now represented correctly in portal (redployed same application)
