### ISSUE TITLE
Container apps cannot mount Azurefile storage unless AES-128-GCM is used in security protocol settings: Undocumented requirement

### ISSUE THREAD

**Issue by ivanthelad** [microsoft/azure-container-apps#852]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When mounting azure file storage into a container app there is a undocumented requirement that AES-128-GCM be enabled in  the in the protocol settings of the Azure file share

### Steps to reproduce
1.  Following instructions https://learn.microsoft.com/en-us/azure/container-apps/storage-mounts-azure-files?tabs=bash 
2. in the share security setting uncheck "AES-128-GCM"
3. Deploy application 

**Expected behavior** [What you expected to happen.]
Behaviour requirement should be documented 
**Actual behavior** [What actually happened.]
Applications fail to startup. no error message in logs apart from crashing message. 
![image](https://github.com/microsoft/azure-container-apps/assets/2631311/82aa7fc3-6b46-469d-a432-5e8dfe9ce52c)

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/2631311/43a09718-1ea6-4f05-a3e3-b065538b9c07)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by SophCarp** [comment]
Thanks for sharing! We'll investigate this error message.

**Comment by LaylaLiu-gmail** [comment]
@ivanthelad , Thanks for reporting this issue. Currently, we only support SMB 3.1.1. And according to the SMB on Linux https://learn.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-linux?tabs=Ubuntu%2Csmb311, It should have AES-128-GCM encryption enabled. We may link this document into our documentation.

**Comment by simonjj** [comment]
These are the defaults now across the board for both CLI and Portal. Hopefully this resolves this issue. Please reopen if not.
