### ISSUE TITLE
Container Apps Job never completes when Managed Identity is enabled

### ISSUE THREAD

**Issue by nosalan** [microsoft/azure-container-apps#854]
### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

Trying to set up the Container Apps Jobs as self hosted agents following this instructions: https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-azure-pipelines
This works when the ACR has Admin access enabled.
However, after trying to integrate with ACR without Admin Access enabled via managed identity the jobs were never completing until timeout was hit.

### Steps to reproduce
1. ACR without Admin Access and accessible via private link exists
2. Create User Managed Identity
3. Assign ACR pull role to the ACR for this managed identity
4. Create Container Apps Environment in the private VNET
5. Create Container App Jobs with the managed identity assigned via bicep, like below:
```bicep

resource acr 'Microsoft.ContainerRegistry/registries@2023-01-01-preview' existing = {
  name: parAcrName
  scope: resourceGroup(parAcrResourceGroupName)
}

resource logAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' existing = {
  scope: resourceGroup(parLogAnalyticsWorkspaceRg)
  name: parLogAnalyticsWorkspaceName
}

resource agentIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' existing =  {
  name: 'mi-${parContainerAppJobsName}'
}

resource placeholderJob 'Microsoft.App/jobs@2023-04-01-preview' = {
  name: parContainerAppsJobsPlaceholderName
  location: parLocation
  tags: parTags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${agentIdentity.id}': {}
    }
  }
  properties: {
    configuration: {
      triggerType: 'Manual'
      replicaTimeout: 300
      replicaRetryLimit: 1
      manualTriggerConfig: {
        replicaCompletionCount: 1
        parallelism: 1
      }
      registries: [
        {
          server: acr.properties.loginServer
          identity: agentIdentity.id
        }
      ]
      secrets: [
        {
          name: 'personal-access-token'
          value: parPatToAdo
        }
        {
          name: 'organization-url'
          value: 'https://dev.azure.com/XXXXXXXXXXXXX'
        }
      ]
    }
    environmentId: containerAppsEnv.id
    template: {
      containers: [
        {
          env: [
            {
              name: 'AZP_TOKEN'
              secretRef: 'personal-access-token'
            }
            {
              name: 'AZP_URL'
              secretRef: 'organization-url'
            }
            {
              name: 'AZP_POOL'
              value: parAgentPoolNameInAdo
            }
            {
              name: 'AZP_PLACEHOLDER'
              value: '1'
            }
            {
              name: 'AZP_AGENT_NAME'
              value: 'placeholder-agent'
            }
          ]

          image: '${acr.properties.loginServer}/${parAgentDockerTag}'
          name: 'placeholder-agent-job'
          resources: varResources
        }
      ]
    }
    workloadProfileName: 'Consumption'
  }
}
```
6. Job is started via `az containerapp job start`

**Expected behavior** [What you expected to happen.]
Job executes successfully and completes.

**Actual behavior** [What actually happened.]
Job executes successfully but it doesn't exit. It shows as running until timeout. Job exited fine when managed identity was not assigned to it. 

**Screenshots** 
I suspect when managed identity is assigned another sidecar container starts along the job. This is visible in the logs:
![image](https://github.com/microsoft/azure-container-apps/assets/2273250/7be74815-0605-4f4d-ad53-818c305d6584)
I assume there is a bug and this container keeps the job alive after the main task completed.

### Additional context
Bicep + cli

**Comment by vinisoto** [comment]
Thanks for reporting. We have a fix ready for this bug and we will start deploying it in the next few days.

**Comment by ZachTB123** [comment]
@vinisoto Is this deployment still in progress or when can we expect the fix to be available?

**Comment by Superzer0** [comment]
Hello, any updates on this issue?

**Comment by vinisoto** [comment]
Hi, the rollout with the fix for this issue is completed.
