### ISSUE TITLE
Deactivation of Dapr in Azure Container Apps will affect the active revision that has active Dapr

### ISSUE THREAD

**Issue by pengxo** [microsoft/azure-container-apps#857]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Deployment of a new active revision for the app without dapr will affect the old active revision which has active Dapr.
### Steps to reproduce
- Azure Container Apps with Multiple Revision Mode;
- The current active revision has active Dapr used for Service-To-Service Invocation with prefix `http://localhost:3500/v1.0/invoke/<app_name>/method/`
- A new deployment for the app in the previous step is executed and a new active revision is created in the app. The deployment deactivates the Dapr and in the app the private DNS name is used for the communication. Two active revisions: Old active revision with active Dapr and 100% traffic as well as the new active revision without Dapr and 0% traffic.

**Expected behavior** [What you expected to happen.]
The old revision is not affected and it could communicate with other container apps through Dapr (i.e. `http://localhost:3500/v1.0/invoke/<app_name>/method/`)
**Actual behavior** [What actually happened.]
The old revision is broken and cannot communicate with other container apps

### Additional context
Azure CLI is used for the deployment.  Every revision is immutable. Therefore the old revision should still have the Dapr container running as a side car in the Pod. So I think it should work.

**Comment by ahmelsayed** [comment]
yes, dapr is an app level configuration not revision-able. dapr itself is unaware of revisions, only apps by their appId. So dapr configuration is for the entire app (all revisions)

**Comment by pengxo** [comment]
Hi @ahmelsayed, thanks for your explanation. As far as I know, aca is based on kubernetes, there are multiple containers in one Pod including app container and dapr container as sidecar. When there are multiple replicas, every replica has a dapr container as sidecar running in a Pod. Is that right? If yes, what happened when the dapr is deactivated on container app level? If no, does aca run a shared dapr container in one pod for all revisions?

**Comment by pengxo** [comment]
According to the documentation in this link https://learn.microsoft.com/en-us/azure/container-apps/dapr-overview?tabs=bicep1%2Cyaml#dapr-enablement, dapr configuration are application-scope changes and all existing revisions will be restarted to ensure that it is up-to-date with the dapr configuration when there are changes. It makes sense in this case. I will close this ticket.
