### ISSUE TITLE
Error upon deployment: Managed environment failed to initialize

### ISSUE THREAD

**Issue by CezaryKlus** [microsoft/azure-container-apps#86]
Hi,

Today I'm experiencing an issue with the managed KubeEnvironment deployment:
```
{
    "status": "Failed",
    "error": {
        "code": "OperationFailed",
        "message": "Managed environment failed to initialize"
    }
}
```

Originally it broke my Pulumi based deployment. Thinking this is an issue with the Pulumi Azure Native provider, I've tried it manually from Azure Portal with the same result.

Region: North Europe

**Comment by CezaryKlus** [comment]
Additional info: works in East US region

**Comment by KaiWalter** [comment]
Had the same issue on a subscription I never used with Container Apps and then applied `az provider register --namespace Microsoft.Web`, like described in <https://github.com/microsoft/azure-container-apps/wiki/Known-Issues-for-public-preview>. Worked for me.

**Comment by torosent** [comment]
Hi @CezaryKlus, please update if the issue is solved. If not, send me an email: torosent at microsoft dot com

**Comment by maciejporebski** [comment]
I'm facing the same issue when deploying an environment inside a Virtual Network. Unregistering and re-registering the Microsoft.Web provider did not help. Attempted to deploy to North Europe, West Europe and East US and all have resulted in the `Managed environment failed to initialize` error.

**Comment by CezaryKlus** [comment]
Closing this as the issue seemed to be resolved
