### ISSUE TITLE
InvalidParameterValueInContainerTemplate issue, image field are either invalid or missing

### ISSUE THREAD

**Issue by rajesh-nitc** [microsoft/azure-container-apps#863]
Hello team, I am trying to create a container app from Github actions workflow using federated uai.  I am able to build and push image to ACR. I am able to authenticate with ACR and also able to pull image using docker pull in the workflow.
<img width="631" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/44093301/5a24729f-557c-4839-9dbb-e018b38c3e71">

```
az acr login --name $ACR ---> works
docker pull $REGISTRY_LOGIN_SERVER/$IMAGE_NAME-$DEPLOYMENT_ENV:$SHORT_SHA ---> works
az containerapp create --name $CONTAINER_APP_NAME-$DEPLOYMENT_ENV --resource-group $RG --container-name $CONTAINER_NAME-$DEPLOYMENT_ENV --environment $CONTAINER_APP_ENVIRONMENT-$DEPLOYMENT_ENV --image $REGISTRY_LOGIN_SERVER/$IMAGE_NAME-$DEPLOYMENT_ENV:$SHORT_SHA --ingress external --target-port 3000 --user-assigned $CONTAINER_APP_UAI_ID --env-vars "API_URL=http://ca-bu1-app1-api-westus-$DEPLOYMENT_ENV"
```
workflow source: https://github.com/rajesh-nitc/terraform-azure-foundation/blob/main/.github/workflows/aca_webspa.yaml

workflow logs:
https://github.com/rajesh-nitc/terraform-azure-foundation/actions/runs/5764896710/job/15629774462

What do you think is the issue here?

**Comment by shaikmoeed** [comment]
Hi Rajesh, facing a similar issue. How are you able to fix it?

**Comment by rajesh-nitc** [comment]
> Hi Rajesh, facing a similar issue. How are you able to fix it?

I was not proving the below params: 
`--registry-identity $CONTAINER_APP_UAI_ID --registry-server $REGISTRY_LOGIN_SERVER`

See the full command that worked here https://github.com/rajesh-nitc/terraform-azure-foundation/blob/main/.github/workflows/aca_web.yaml

**Comment by TeamDman** [comment]
I ended up having to change my Basic container registry to Premium to use private endpoints to fix this nonsense.
