### ISSUE TITLE
Azure Container Apps CLI extension: az containerapp auth update throws error

### ISSUE THREAD

**Issue by MarcelWouters** [microsoft/azure-container-apps#865]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When running:

`az containerapp auth update -g myResourceGroup --name MyContainerapp --unauthenticated-client-action AllowAnonymous"`

It results in the following error:

> ERROR: (AuthConfigInvalidRequest) AuthConfig is invalid with detail 'IdentityProvider should be provided if easyauth is enabled'

### Steps to reproduce
1. run az containerapp auth update -g myResourceGroup --name MyContainerapp --unauthenticated-client-action AllowAnonymous

**Expected behavior** [What you expected to happen.]
No error. This az cli extension statement worked before in our Azure DevOps pipelines withouts any errors

**Actual behavior** [What actually happened.]
ERROR: (AuthConfigInvalidRequest) AuthConfig is invalid with detail 'IdentityProvider should be provided if easyauth is enabled'

**Screenshots**         

### Additional context
`azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Extensions:
azure-devops                      0.26.0
containerapp                      0.3.36

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2
`

**Comment by njuCZ** [comment]
Hi @MarcelWouters, we have removed this validation to unblock azure cli customer, once it's deployed I will reply again

**Comment by LianaAdaza** [comment]
Thank you for your report. We can't seem to replicate the issue, so we assume the CLI bug has been fixed. Please feel free to reopen if you continue to encounter this difficulty
