### ISSUE TITLE
Support for jobs?

### ISSUE THREAD

**Issue by LoungeFlyZ** [microsoft/azure-container-apps#87]
Is there a recommended or supported way to schedule job containers?  I want to run a one-time job container periodically. Manually triggered at this stage.

**Comment by cmenzi** [comment]
I also asked for this or similar: https://github.com/microsoft/azure-container-apps/issues/65 The concept in KEDA is called Scaled Jobs.

**Comment by torosent** [comment]
Hi. We are looking into Jobs workloads model and will update on our plans to add it.

**Comment by ThorstenHans** [comment]
@torosent Do you consider exposing `Job` and `CronJob` 

I'm speaking about 1st class Kubernetes resources 

- https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/
- https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/

Although recurring jobs can be achieved using KEDA (a combination of AzFunction timer trigger with a message queue), I would highly recommend exposing native `CronJob`. This would allow customers to get rid of additional (unnecessary) cloud infrastructure.

**Comment by tomkerkhove** [comment]
Related: https://github.com/microsoft/azure-container-apps/issues/24

**Comment by kendallroden** [comment]
We are investigating this feature for implementation

**Comment by tomkerkhove** [comment]
> @kendallroden Kendall Roden FTE Is it possible to configure container app to be "always up"?

You can just configure it with min replicas of 1

**Comment by Masahigo** [comment]
I guess it's called idle container app :)

**Comment by kendallroden** [comment]
Please track https://github.com/microsoft/azure-container-apps/issues/526
