### ISSUE TITLE
Failed:identity-service-0cee4339ContainerCrashing when deploying a container app

### ISSUE THREAD

**Issue by vegarnilsen** [microsoft/azure-container-apps#871]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Starting last night we get the error message in the title when we deploy one of our container apps, in revision management. The container app itself seems to be running ok, even though revision management reports that provisioning the app failed.

Since it seems like this `identity-service-0cee4339` is an internal Kubernetes sidecar service I have no visibility into what's failing here.

### Steps to reproduce
1. Deploy an updated version of an existing Container App from Github Actions with ARM / bicep templates
2. Container starts, sidecar fails and the portal is unhappy about the revision

**Expected behavior** [What you expected to happen.]
Container and all required Kubernetes services should work as they've done for a few months

**Actual behavior** [What actually happened.]
Container works but some Kubernetes service doesn't all of a sudden

**Screenshots**      
Revision management:   
![image](https://github.com/microsoft/azure-container-apps/assets/6359167/1160588b-7ec1-486b-9c6d-d2cdc74a81e3)

Scale and replicas:
![image](https://github.com/microsoft/azure-container-apps/assets/6359167/cd67bd01-9b4a-4e00-b609-7162d0393b3b)

### Additional context

Since this problem so far has only happened in our production environment I have not had the chance to try if the same problem happens with other container apps, or if it's isolated to this specific app.

**Comment by vegarnilsen** [comment]
We were able to test with another container app now, in the same container app environment, and it failed in exactly the same way:

Revision management:
![image](https://github.com/microsoft/azure-container-apps/assets/6359167/5fa1ebf4-a8b1-45e1-89ea-f5e714ed3657)

Scale and replicas:
![image](https://github.com/microsoft/azure-container-apps/assets/6359167/8ef6096d-e554-4f98-89a6-109c82fdc065)

And the Github Action reports the deployment as failed with this error message:

The Resource 'Microsoft.App/containerApps/datafanger' under resource group 'rg-cae-*-prod' was not found.

**Comment by torosent** [comment]
Fix is rolling out for this issue

**Comment by torosent** [comment]
Hi, @vegarnilsen The fix has been rolled out to all regions. Please confirm the issue is resolved for you.

**Comment by vegarnilsen** [comment]
> Hi, vegarnilsen The fix has been rolled out to all regions. Please confirm the issue is resolved for you.

We got the same failure now. Do we need to redeploy the entire Container App Environment to activate this fix?

What was the problem here, can you share any information?

**Comment by trylvis** [comment]
Experiencing similar issues for Container Apps hosted in North Europe, started yesterday and also had some this morning. Last around 10:30 AM GMT.

This also happens on already deployed containers, not only when deploying new releases. 

Using default scaling, ie between 0-1 revisions, might be that this occurs when scaling from 0 > 1.

Environment is Consumption, internal-vnet mode.


Any updates on this?

**Comment by torosent** [comment]
Hi all. We are investigating

**Comment by sanchitmehta** [comment]
@Kukukuchu @trylvis  Could you please share your environment resource id's at acasupport[at]microsoft.com?

**Comment by trylvis** [comment]
> @Kukukuchu @trylvis Could you please share your environment resource id's at acasupport[at]microsoft.com?

✅ Sent over resource ID.

**Comment by torosent** [comment]
Hi All, We identified the issue. Its related to ensuring the order of the MI sidecar in the startup process which we added recently. The issue is not consistent and we are working on deploying a fix for it.

**Comment by Kukukuchu** [comment]
> Hi All, We identified the issue. Its related to ensuring the order of the MI sidecar in the startup process which we added recently. The issue is not consistent and we are working on deploying a fix for it.

Any info on the priority of this / ETA? 
Or workarounds that might help get the release out in the meantime?

We've stumbled on this trying to make a new release in dev environment and currently wondering whether we need to invest in pushing through / around this issue or we can afford to wait for the fix.

**Comment by wims80** [comment]
> > Hi All, We identified the issue. Its related to ensuring the order of the MI sidecar in the startup process which we added recently. The issue is not consistent and we are working on deploying a fix for it.
> 
> Any info on the priority of this / ETA? Or workarounds that might help get the release out in the meantime?
> 
> We've stumbled on this trying to make a new release in dev environment and currently wondering whether we need to invest in pushing through / around this issue or we can afford to wait for the fix.

We were able to get our containers deployed by settings minReplicas: 2, maxReplicas: 4 (we used to have minReplicas: 1). The second replica eventually spun up. Your mileage might vary

**Comment by stweb1963** [comment]
We are also seeing similar issues with Container App Jobs with Managed Identities enabled for Scheduled jobs
The deployments hang indefinitely and all our existing Scheduled Jobs have exhibited issues.

**Comment by darenwatkins** [comment]
We were seeing the same issue, but when it was scaling up and deploying. The issue seems to be that was it was trying to look up the Managed System Identity on scale up. This timed out, and then the revision is marked as failed. Have been informed a patch rollout was performed on the 17th August. This seems to have resolved the problem for us now.

**Comment by vegarnilsen** [comment]
After our environments were patched on the 16th all our container apps have worked properly, both existing and freshly deployed apps. Looks like this problem was fixed.
