### ISSUE TITLE
Auto Scaling with Event Hub

### ISSUE THREAD

**Issue by knkukkadapu** [microsoft/azure-container-apps#872]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.
I am trying to use custom auto scale option in container app. The custom auto scale is for azure-eventhub. I am seeing its not getting scaled as expected. I had similar implementation on service bus and it works with out any issues. But its not working on azure-event hub custom auto scale.

I have python script which is reading the events from one event hub and inserting in to another event hub. (I cannot use stream analytics here as there is a business logic involved here).

I have used the KEDA documentation and configured the auto scale options.

### Steps to reproduce
1.  ingest events to event hub.
2. write a simple python to read the events from the event hub and ingest to another event hub.
3. deploy this python script as container app
4. configure the following parameters for auto scale from 1 - 10

- **Type - Custom**
- Custom Rule Type - azure-eventhub
- In Authentication section (Refer the screenshot)
- one connection for checkpoint storage account connection string
- one connection for source event hub connection string 
- **In Meta data** (Refer the screenshot)
- activationUnprocessedEventThreshold - 100
- blobContainer - <<name of the container where the checkpoint is going to stored>>
- connectionFromEnv - <<connection string of Event Hub>>
- consumerGroup -<<consumer Group of input Event Hub>>
- storageConnectionFromEnv - <<connection string of storage account to store the checkpoint>>

**Expected behavior** [What you expected to happen.]
the container app should scale based on the above condition

**Actual behavior** [What actually happened.]
the container app is scaling based on the number partition in the Event hub.

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/100687736/5411194f-f567-4c3d-8223-71e585365c17)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by anthonychu** [comment]
@knkukkadapu What Python SDK are you using to receive messages from Event Hubs? Depending on your SDK, you may need to configure the `checkpointStrategy` metadata value to be `blobMetadata`.

Also, you have defined `connection` and `storageConnection` with secrets in the authentication section and also from the environment in metadata. Maybe not causing the problem here but you only need one of those.

**Comment by knkukkadapu** [comment]
Hello, I am using azure-eventhub==5.3.1 Version.

**Comment by anthonychu** [comment]
I think you might need to write your receiver like [this example](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-python-get-started-send?tabs=connection-string%2Croles-azure-portal#create-a-python-script-to-receive-events) that leverages a blob checkpoint. Then configure the scaler to use the same checkpointStrategy and Event Hubs and blob container settings.

**Comment by knkukkadapu** [comment]
Hello, Thanks for your input. Looks like the container app doesn't scale beyond number of partitions of event hub. Thats the current limitation. I had implemented the checkpoint logic in the python script.
