### ISSUE TITLE
Permission denied mounting Azure Files volume

### ISSUE THREAD

**Issue by Steve887** [microsoft/azure-container-apps#873]
I have a container app I am trying to use with an Azure File storage volume. I've followed the instructions at https://learn.microsoft.com/en-us/azure/container-apps/storage-mounts?pivots=azure-cli#azure-files, created the storage account and file share, added it to my container app environment, then setup the volumeMount and volumes options in my container app bicep file.

While it appears like everything is correct in the portal, when I try to startup the container it fails to start and eventually times out, with the following in the system log:

```
MountVolume.SetUp failed for volume "<volumename>" : rpc error: code = Internal desc = volume() mount //<storageaccount>.file.core.windows.net/<storagefolder> on /var/lib/kubelet/pods/<guid>/volumes/kubernetes.io~csi/<volumename>/mount failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o ,file_mode=0777,dir_mode=0777,actimeo=30,mfsymlinks,nosharesock,<masked> //<storageaccount>.file.core.windows.net/<storagefolder> /var/lib/kubelet/pods/<guid>/volumes/kubernetes.io~csi/<volumename>/mount
Output: mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
```

There doesn't appear to be much more I can do to resolve this. I have tried giving the container app a role assignment to the storage account, tried several different file paths, turning off Secure transfer required. Both the container environment and storage account are on the same VNet and region.

Is there anything else I can do to resolve this issue?

**Comment by njuCZ** [comment]
Hi @Steve887 , there are several reasons that may cause this error, for example, the accesskey is not right, the network is not blocked or allowed to access the storage account.

could you check your settings according to https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/fail-to-mount-azure-file-share#mounterror13?

**Comment by Steve887** [comment]
@njuCZ 

I have checked those things. The container environment and storage are on the same VNET. Storage is set to most Maximum Compatibility and the storage key is correct.

Can you confirm if I need to supply a Kubernetes secret resource? I would assume since it's a managed service I wouldn't need to do any Kubernetes setup myself?

**Comment by njuCZ** [comment]
@Steve887 can you DM me your container app arm resource id so I can take a check?

**Comment by njuCZ** [comment]
@Steve887 you could send email to acasupport at microsoft.com with your arm resource info and we could take a check

**Comment by Steve887** [comment]
I believe I worked it out. I had two issues: I was trying to map to a subfolder in the storage account, which doesn't seem possible, and the container app apparently needs at least Contributor access to the storage account to map the volume. After doing both of these things by storage is mounted correctly.

**Comment by njuCZ** [comment]
@Steve887, container app also supports mounting a storage account subpath by specifying the subpath property in the volumeMount
