### ISSUE TITLE
Long time waiting for a job to schedule: 'Node is not ready'

### ISSUE THREAD

**Issue by nosalan** [microsoft/azure-container-apps#874]
### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When a new Container Apps Job is scheduled, sometimes it takes a long time for the job to start.
In the environment logs it looks like this (at least 7 minutes of waiting):

![image](https://github.com/microsoft/azure-container-apps/assets/2273250/4a8d112d-0095-4a99-80f2-1236f3443c31)
The jobs are configured with Workload Profiles (Consumption): 2 cpu, 4Gi
Region: westeurope

### Steps to reproduce
It bites sometimes when [using the jobs as build agents](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-azure-pipelines).

**Expected behavior** [What you expected to happen.]
Jobs are scheduled faster.

**Actual behavior** [What actually happened.]
Sometimes it takes a long time for the job to start.

**Comment by vinisoto** [comment]
hi @nosalan, we would need more information to investigate this.

Can you please send an email to `acasupport at microsoft dot com` with your subscription id, environment name, job name and approximate date time when this happened?

**Comment by nosalan** [comment]
Hi @vinisoto, email sent.

**Comment by vinisoto** [comment]
hi - closing the loop here. We addressed the issue with @nosalan over email.
