### ISSUE TITLE
Consumption + Dedicated .NET app not able to utilize more than ~2 GB of memory even if configured to ex. 4 or 8 GB

### ISSUE THREAD

**Issue by christiansparre** [microsoft/azure-container-apps#875]
### This issue is a:
- [x ] bug report

### Issue description
I have an app that is running in "consumption" on a Consumption + Dedicated environment. It is configured with 2 vcpu, 4 GB memory.

But I'm running into out of memory exceptions at ~1.2 GB memory usage. 

I have made a repro app that I have deployed to an "old" Consumption only environment and a Consumption + Dedicated environment - both configured with 2cpu, 4GB memory

For each app `GC.GetGCMemoryInfo()` returns the following values:

**On the "old" Consumption only environment:**

```
HighMemoryLoadThresholdBytes = 3865470566 (~3.86 GB)
TotalAvailableMemoryBytes = 3221225472 (~3.22 GB)
```

**On the new Consumption + Dedicated environment:**

```
HighMemoryLoadThresholdBytes = 1956980736 (~1.95 GB)
TotalAvailableMemoryBytes = 1630817280 (~1.63 GB)
```

It does not matter if I set the Consumption + Dedicated app to 8 GB, it's still only showing around 2 GB memory available.

Any idea why this is happening? Am I missing some configuration steps?

**Expected behavior**
The configured memory is available to my app

**Actual behavior**
Only ~2 GB memory is available even if memory is configured to more, ex. 4 or 8 GB

**Comment by erich-wang** [comment]
@christiansparre, thank you for reporting  the issue and we're actively investigating the issue, will update if any progress.

**Comment by qwordy** [comment]
@christiansparre, we confirm it is a code bug. I am fixing it.

**Comment by gameiro** [comment]
I am also running into similar issue when setup the java env variable to `-Xms4g -Xmx4g` using container app with consumption + dedicate plan with 4 CPU and 8GB of memory.

The error was the following:
```bash
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 4294967296 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid13.log
```
The container as more memory but its seems when running the java application it complains.

**Comment by erich-wang** [comment]
@christiansparre , @gameiro, we're rolling the fix to prod, which may around one week. Could you please let me know in which azure region you're deploying container app? I could let you know more precise about fix time.

**Comment by christiansparre** [comment]
Thank you for letting us know @erich-wang, my apps are deploying to west europe.

**Comment by gameiro** [comment]
@erich-wang I am also deploying to west europe, do you know when it will be deployed ?

**Comment by christiansparre** [comment]
@gameiro I'm seeing the change in my repro app on westeurope now. It reports the same values for `GC.GetGCMemoryInfo()` in both consumption and consumption+dedicated environments now. So I guess it has rolled out to that region now 😁

**Comment by gameiro** [comment]
@christiansparre yes it seems to work now great.

**Comment by erich-wang** [comment]
Yes, the change was rolled out to westeurope around Aug 25.

**Comment by christiansparre** [comment]
And GA ❤️🎉

Thank you...
