### ISSUE TITLE
Retirement of API versions 2022-06-01-preview and 2022-11-01-preview?

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#876]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I received an email titled "Action required: Retirement of Azure Container Apps versions" in only one of my multiple subscriptions running Azure Container App (ACA).
// See the screenshot for the content of the email.

I checked the contents of the email, but there is no difference from ACA running in other subscriptions, so I don't know how to respond.

I have two questions:
- Conditions for receiving this email
- Any action that needs to be taken (e.g. Azure CLI update or SDK update in incoming code deploying ACA)

### Steps to reproduce
Nothing in particular (an email from Microsoft Azure arrives)

**ScreenShots**
![20230817-01](https://github.com/microsoft/azure-container-apps/assets/15773157/0032460a-ed7b-41f9-87b8-51c71f29355c)

**Comment by anthonychu** [comment]
This was sent to subscriptions who our logs show had recently made management API calls using the retiring API versions. What do you use to manage your container apps (portal, CLI, Bicep, etc)?

**Comment by YuKogasaka** [comment]
@anthonychu,

I understand the conditions for receiving "Action required" emails.

Different units within a project use different tools to manage ACA.

- Develop unit : Bicep
- Operations unit : Azure CLI and Azure Portal

I recognize that this issue occurred because the unit and members were not properly updated and specified for each tool (API version).

This issue has been resolved, thank you.
