### ISSUE TITLE
Running latest azapi returns Workload Profile property is not supported

### ISSUE THREAD

**Issue by gameiro** [microsoft/azure-container-apps#877]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When running the terraform using the following resource:

```
resource "azapi_resource" "aca_env" {
  type      = "Microsoft.App/managedEnvironments@2023-05-01"
  name      = "consumption-env-test"
  parent_id = data.azurerm_resource_group.main.id
  location  = data.azurerm_resource_group.main.location
  
  body   = jsonencode({
    properties = {
      
      workloadProfiles = [
        {
          name = "Consumption"
          maximumCount = 1
          minimumCount = 1
          workloadProfileType = "Consumption"
        }
      ]
    }
 })
}
```

I am getting the following error:

```
 RESPONSE 400: 400 Bad Request
│ ERROR CODE: WorkloadProfilePropertyNotSupported
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "WorkloadProfilePropertyNotSupported",
│     "message": "Workload Profile property is not supported"
│   }
│ }
│ --------------------------------------------------------------------------------
```

The latest api has the correct property so I don't understand what is the problem here ?

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by howang-ms** [comment]
Can you remove the property of maximumCount/minimumCount  from the request, as it is not appliable for Consumption workload profile type.

**Comment by gameiro** [comment]
> Can you remove the property of maximumCount/minimumCount from the request, as it is not appliable for Consumption workload profile type.

Hei @howang-ms after removal of the max and min count the terraform was suceffull applied but I had to use the azapi version: `2023-04-01-preview`

Because of the following error message:

```bash
│ Error: embedded schema validation failed: the `type`'s api-version is invalid.
│  The supported versions are [2022-01-01-preview, 2022-03-01, 2022-06-01-preview, 2022-10-01, 2022-11-01-preview, 2023-04-01-preview].
│  You can try to update `azapi` provider to the latest version or disable the validation using the feature flag `schema_validation_enabled = false` within the resource block
```
