### ISSUE TITLE
Ingress Target Port 80 and 443

### ISSUE THREAD

**Issue by passarela** [microsoft/azure-container-apps#879]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ X ] regression (a behavior that used to work and stopped in a new release)

### Issue description
My containers are defined with Target Port 80, when creating a new container or editing an existing one returns message:
The value cannot be 80 (HTTP) or 443 (HTTPS).

### Steps to reproduce
1. Select Container App
2. Ingress
3. Ingress Type = HTTP
4. Target Port = 80

**Expected behavior** [What you expected to happen.]
Container apps should allow selecting target port 80

**Actual behavior** [What actually happened.]
Azure portal issues the warning:
The value cannot be 80 (HTTP) or 443 (HTTPS).

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/72925771/9bbe7b1e-c7c4-4f0d-8095-9b4522458e2a)

### Additional context
Portal, through the AZ CLI works.

**Comment by anthonychu** [comment]
Able to reproduce. Investigating. @cachai2

**Comment by cachai2** [comment]
@passarela thank you for flagging this issue. We have implemented a fix which is rolling out and should be complete by end of this week.

**Comment by anthonychu** [comment]
For anyone running into this issue, please use the CLI to create/modify the app for the time being if you need to configure 80/443. Sorry for the inconvenience.

**Comment by passarela** [comment]
Fix has already been applied. Tested in the Brazil South region.
![image](https://github.com/microsoft/azure-container-apps/assets/72925771/9047f74f-261a-4371-bb9b-178f1a5100ab)
