### ISSUE TITLE
aad pod identity (MIC)

### ISSUE THREAD

**Issue by dariuszbz** [microsoft/azure-container-apps#88]
Any plans to enable containers with aad manage identity for pods:

https://github.com/Azure/aad-pod-identity

**Comment by torosent** [comment]
We are working on managed identity, and it will be released in the coming weeks.

**Comment by torosent** [comment]
Duplicate of #16

**Comment by dariuszbz** [comment]
Hi @torosent! It is a great news.

Can we see e2e roadmap, please?
