### ISSUE TITLE
Startup probe not working as expected

### ISSUE THREAD

**Issue by emilmuller** [microsoft/azure-container-apps#882]
I have set up a startup probe with the current configuration:

Initial delay seconds: 3
Period seconds: 3
Timeout seconds: 30

This [documentation](https://learn.microsoft.com/en-us/azure/container-apps/health-probes?tabs=arm-template) says that failure threshold should be the same as timeoutSeconds:

![image](https://github.com/microsoft/azure-container-apps/assets/2487546/8f9d2001-e392-48cc-ae05-fb793c0fee66)

However, I am observing my replica being terminated after 3 attempts, i.e. 9 seconds.

Furthermore, in Kubernetes, I believe that failureThreshold is a unitless number (i.e. not in seconds). According to GPT 🙃, the default failureThreshold in Kubernetes is 3, which seems to match my situation.

Documentation wrong?

After having set the failure threshold to 10 (which I guess would equal ~30 seconds), I am seeing a strange behaviour:

![image](https://github.com/microsoft/azure-container-apps/assets/2487546/a27942d4-7f98-40f9-bcf5-29c9bc2c3ff5)

It would seem that groups of two health probes are executed almost at the same time. Are they failing, then immediately retrying and not respecting the 'period seconds' param?

Kind regards, Emil

**Comment by zhenqxuMSFT** [comment]
> However, I am observing my replica being terminated after 3 attempts, i.e. 9 seconds.

@emilmuller the default values in the document only applies if you do not define the probe at all. If you define the probe while leave some property unset, it defaults to kubernetes defaults. 
@anthonychu @cachai2 Probably we should clarify this in the doc to avoid confusion. Also, I spotted a the default timeout value for startup probe is 3 seconds. Moreover, I feel like it confuses customers by saying `Failure threshold: timeoutSeconds`. In fact the threshold does not related to timeout seconds if customer specifies them. So, we should just document the const default value. For StartupProbe it's 240 and for ReadinessProbe it's 48.

> It would seem that groups of two health probes are executed almost at the same time. Are they failing, then immediately retrying and not respecting the 'period seconds' param?

@emilmuller could you send your container app name, environment name, resource group name, subscription id and region to acasupport#microsoft.com.

**Comment by njuCZ** [comment]
Hi @emilmuller, you are right, the log is duplicated and we have fixed this issue, it may take some time to deploy.
you can filter the log by time_t
