### ISSUE TITLE
Consumption vs Consumption on Dedicated Plan structure memory

### ISSUE THREAD

**Issue by ZachTB123** [microsoft/azure-container-apps#884]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I am currently using the Consumption [plan type](https://learn.microsoft.com/en-us/azure/container-apps/plans) but am looking to switch to the Consumption + Dedicated plan structure since I need UDR support. On the Consumption only plan, my app is able to start with `cpu = 0.25` and `memory = 0.5Gi`. I created a new environment that uses the Consumption + Dedicated plan and moved my app to this environment and selected the consumption workload profile. The revision that gets created gets stuck in the `Activating` running status and eventually goes to `Degraded`. Looking in the system logs, I see: `Container 'my-container' was terminated with exit code '137'`, which would indicate it doesn't have enough memory. The only way I can get the revision to run successfully is to bump the memory to `3.0Gi`.

Next I tried adding the `D4` workload profile type to my environment. I then updated my container app to use this profile and switched back to using `cpu = 0.25` and `memory = 0.5Gi`. With this cpu and memory configuration on `D4`, the revision **does** run successfully.

What could be the cause of needing more memory than normal on the consumption workload profile in the Consumption + Dedicated plan?

**Expected behavior** [What you expected to happen.]

My container runs successfully on both consumption offerings when using the same cpu/memory.

**Actual behavior** [What actually happened.]

I need to bump up the memory on the consumption workload profile in the Consumption + Dedicated plan.

**Comment by ahmelsayed** [comment]
maybe related to https://github.com/microsoft/azure-container-apps/issues/875? not sure. 

/cc @qwordy @erich-wang

**Comment by erich-wang** [comment]
@ZachTB123, could you please provide container app managed env name, app name and azure region?

**Comment by ZachTB123** [comment]
@erich-wang Is there an email address I could send this info to? Or if it is easier, I can open a support ticket.

**Comment by erich-wang** [comment]
@ZachTB123, please send to eriwan@microsoft.com, thx.

**Comment by ZachTB123** [comment]
@erich-wang I sent the info over to you.

**Comment by erich-wang** [comment]
@ZachTB123 , the memory fix has been rolled out to east us 2, could you please try again in east us 2? If issue remains, please do not delete your container app and send me your container app info if container app info changes.

**Comment by ZachTB123** [comment]
@erich-wang It looks to be working as expected now.

**Comment by cachai2** [comment]
Closing as this issue is resolved. Please reopen if needed.
