### ISSUE TITLE
Feature Request: expose mc_ resource group from managed environment api

### ISSUE THREAD

**Issue by serpentfabric** [microsoft/azure-container-apps#885]
**Is your feature request related to a problem? Please describe**.  
if you wish to use some of the managed resources, included in the mc_ Infrastructure resource group group, as inputs to something in iac -- say the aks load balancer in the mc_ resouce group with a soon to be created private link service... you cannot easily do this using terraform/pulumi/bicep/arm because i have no reference to that resource group nor a reliable idea about its name.

**Describe the solution you'd like**.    
expose that information in the api the same way its exposed for aks, via the properties section in the portal "Infrastructure resource group" 

**Describe alternatives you've considered**.   
try to derive the resource group name from the defaultDomain field. it seems it's $"{defaultDomain}-rg {defaultDomain}-{region}".

**Additional context**.

**Comment by torosent** [comment]
Hi, In workload profiles, you can set your managed resource group name so you won't have auto generated MC_ or ME_ names anymore. 
https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=azure-cli#workload-profiles-environment-1
<img width="778" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/17064840/80dd9e1d-985d-49b3-8d94-b90d8b542f94">
