### ISSUE TITLE
Multiple values in CRON expression for jobs no longer works

### ISSUE THREAD

**Issue by mburumaxwell** [microsoft/azure-container-apps#886]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
A few days ago, creating a scheduled job with multiple hours worked but now it doesn't.
For example: `20 0,1,2 * * *` or `20 0-2 * * *`
There are jobs created prior still work but can't be updated.

### Steps to reproduce
Create a job with cron expression containing a comma or hyphen in the hour field for example: `20 0,1,2 * * *` or `20 0-2 * * *`

**Expected behavior**
This should create it because it is a valid CRON, see [explanation](https://crontab.guru/#20_0,1,2_*_*_*)

**Actual behavior**
Error message:
```
Given CRON expression - '20 0,1,2 * * *' is not valid, please visit https://learn.microsoft.com/en-us/rest/api/containerapps/preview/jobs/create-or-update?tabs=HTTP#scheduletriggerconfig for more information. (Code: InvalidCronExpression)
```

**Screenshots**         

### Additional context
Deployment via Bicep/ARM

**Comment by anandanthony** [comment]
This was caused due to a validation added for CRON expressions, we have updated it and would have the fix in our next release.

**Comment by mburumaxwell** [comment]
Thanks @anandanthony 
When can we expect to see the changes? (West EU)

**Comment by ractando** [comment]
@anandanthony By when can we expect the next release ?

**Comment by anandanthony** [comment]
We should have the fix rolled out across by end of next week.

**Comment by Ben675784** [comment]
Hi all,
it appears as though none of the cron-expressions that I have tried work, even very simple ones, like '0 0 0 * * *', see below error:

> (InvalidCronExpression) Given CRON expression - '0 0 0 * * *' is not valid, please visit https://learn.microsoft.com/en-us/rest/api/containerapps/preview/jobs/create-or-update?tabs=HTTP#scheduletriggerconfig for more information.

when executing the following command

`
az containerapp job create \
        --name "[...]" --resource-group "[...]" --environment "[...]" 
        --trigger-type "Schedule" 
        --replica-timeout 10800 --replica-retry-limit 0 --replica-completion-count 1 --parallelism 1 
        --image "[...]" 
        --cpu "0.25" --memory "0.5Gi" 
        --cron-expression "0 0 0 * * *"
`
Is there any alternative way, currently, to deploy a job with a schedule? 

Thanks in advance & best,
Ben

**Comment by mburumaxwell** [comment]
@anandanthony still struggling with this as of 2023-09-22T01:44:00+00:00

The tracking id is '8da6ba1b-f643-45d4-bbcc-b465b3dbc248'
Given CRON expression - '0 22 * * 1-5'
Given CRON expression - '0 23 * * SAT'

**Comment by anandanthony** [comment]
The fix for this issue is available in all the regions.

**Comment by mburumaxwell** [comment]
Thanks
