### ISSUE TITLE
Container jobs cannot connect to container apps in the same environment

### ISSUE THREAD

**Issue by johnliu55-msft** [microsoft/azure-container-apps#889]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A container job cannot access Redis deployed as a container app running in the same container app environment using `<App Name>:<port>`. According to the document this feature should be supported.

- The Redis container app has ingress configured to **Limited to Container Apps Environment**
- The environment has another Python container app that can access Redis app using `<App Name>:<port>` so I'm sure I have configured the ingress correctly.
- DNS resolution using `<App Name>` works. It resolved to three IPs.

### Steps to reproduce
1. Deploy Redis as a container app to a container environment
2. Enable Ingress on the Redis app
3. Create a container job that requires access to the Redis app using the same container environment as step 1

**Expected behavior** [What you expected to happen.]
The container job should be able to access the Redis app using `<App Name>:<port>`

**Actual behavior** [What actually happened.]
When the container job try to access the container app, it shows "Connection refused".

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by vinisoto** [comment]
hi @johnliu55-msft we have a fix for this issue which is currently being rolled out globally. We expect it to be fully deployed by the middle of next week,

**Comment by kstavland** [comment]
Is it possible to see what regions the fix has been deployed to?

**Comment by vinisoto** [comment]
Hi, the fix for this has been rolled out globally.

**Comment by johnliu55-msft** [comment]
Tested on West US 2 and works. Thank you so much!
