### ISSUE TITLE
Preview on EU region

### ISSUE THREAD

**Issue by timonmasberg** [microsoft/azure-container-apps#89]
I don't know if this is the right place to ask, but we are very excited about Azure Container Apps. Is there any ETA when a preview might become available in the EU region?

Thanks!

**Comment by denniszielke** [comment]
It is already available in NorthEurope.

**Comment by torosent** [comment]
Hi @timonmasberg . CA is available now North Europe and West Europe. If They are not showing up, please run `az provider register --namespace Microsoft.Web`.
We will enable more regions worldwide in the upcoming months.

**Comment by timonmasberg** [comment]
Thank you! We will definitely check this out!
