### ISSUE TITLE
Container apps jobs environment variables fail validation

### ISSUE THREAD

**Issue by rob-king-volpara** [microsoft/azure-container-apps#902]
### This issue is a:
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am setting up a new Container Apps Job using the Azure Portal. I have previously run as a Container App without trouble. When I try to set the ENV vars on the container, it fails validation with a generic error "Failed to update containers and any associated Job configuration".

When I look into the dev console, I see the following exception is being returned:
"Invalid Request: Container app secret(s) with name(s) 'azurewebjobsstorage, reg-pswd-41ff328a-8a18, syncfusionlicence, encryptionkey' are invalid: value or keyVaultUrl and identity should be provided."

These are secrets that I have created in the job and am referencing from the env vars.

### Steps to reproduce
1. Create a new container app job referencing a container
2. Create a secret with a plain string value (i.e. no external reference to KeyVault)
3. On the container settings screen where the environment variables are set, click Add and fill in the fields referencing the secret in the job.
4. Click Save.
5. Click Apply.

**Expected behavior** [What you expected to happen.]
I would expect the container apps job to save

**Actual behavior** [What actually happened.]
An error popup occurs and an error is logged in the console.

**Screenshots**         
<img width="488" alt="Screenshot 2023-09-15 165102" src="https://github.com/microsoft/azure-container-apps/assets/83792945/139619a9-7d67-4582-9036-6b8f74266156">
<img width="683" alt="Screenshot 2023-09-15 165149" src="https://github.com/microsoft/azure-container-apps/assets/83792945/9dba0065-02ed-486a-b99c-a9ce159331d5">
<img width="305" alt="Screenshot 2023-09-15 165127" src="https://github.com/microsoft/azure-container-apps/assets/83792945/0dcf9dfd-7263-423e-87db-27d3cdd3307f">

### Additional context
Portal

**Comment by charlie-retzler** [comment]
We are also seeing this same issue with our Azure Container Jobs. In our case the original deployment seems to run to completion, but we can't modify the container or add another container to the Azure Container Job. Both of these cause the ContainerAppSecretInvalid error. It also doesn't seem to matter if we have an environment variable or not.

Trying to run the job also seems to fail, and we are not seeing any logs even after waiting 10 or more minutes.

We are currently using an Azure Container Registry with Admin Credentials. The secrets for the registry are the same as the secret in our working Azure Container App. 

Let us know if we can provide any other information.

**Comment by ahmedkhan50** [comment]
Hey, we also onboarded a container app job today & cant edit anything after that, it fails with error -> "Failed to update containers and any associated Job configuration"

**Comment by Huwbie** [comment]
Hi, We are also suffering this issue, case in point we tried to change the container that would run in the container job post deployment, and it fails with error  "Failed to update containers and any associated Job configuration"

**Comment by charlie-retzler** [comment]
I was able to workaround the limitation of the Azure UI and call the `az  containerapp job update` commands to update a Container App Job to specify new environment variables that I had missed in my initial setup. This made it much easier than deleting and recreating to get all the parameters correct for my job.

**Comment by ahmedkhan50** [comment]
Awesome, thanks! I hope azure fixes this soon.

**Comment by vinisoto** [comment]
Hi, we are starting the rollout out a fix for the Portal experience for Jobs. ETA is by 9/30
