### ISSUE TITLE
Container App Jobs not working in WestEurope region

### ISSUE THREAD

**Issue by nosalan** [microsoft/azure-container-apps#911]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We have a critical issues with job triggering today, in the logs we can see that it tries to restart but usually with no luck, logs:

![image](https://github.com/microsoft/azure-container-apps/assets/2273250/2290fd88-6466-4bfe-9346-817b73968c46)

It's not a problem with the job code because it was working till yesterday and it succeeds sometimes too today. There's nothing in Azure Status.

### Configuration

![image](https://github.com/microsoft/azure-container-apps/assets/2273250/8f058cab-32bb-4cab-87dd-a5bc0a7b1429)

![image](https://github.com/microsoft/azure-container-apps/assets/2273250/42cf2eaf-152d-4d4d-8828-2fb365e0dd2c)

**Expected behavior** [What you expected to happen.]
Jobs are executed.

**Actual behavior** [What actually happened.]
Joba are not executed.

**Comment by drmathias** [comment]
Seeing issues in westeurope too, all the job executions are timing out and there's no container logs.

**Comment by vinisoto** [comment]
We have detected a potential issue and are working on investigating and getting a fix out.

**Comment by vinisoto** [comment]
We have identified a race condition here. We will be rolling out a fix starting next week.

**Comment by vinisoto** [comment]
As a mitigation you can set `retryLimit` to 1 (or any value greater than 0).

**Comment by vinisoto** [comment]
Hi, a permanent fix has already been deployed.

**Comment by avneeshkumar** [comment]
@vinisoto Is fix deployed only to WestEurope or everywhere... We are currently running jobs in West US 
We are also facing the issue but we are not facing it everytime. We are getting it randomly sometime... 
<img width="973" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/3087417/819990f3-2847-4ced-8ff4-49e93db08b7a">

<img width="1397" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/3087417/d4d7339c-1ead-4d96-b702-34f2addfbf87">

**Comment by vinisoto** [comment]
@avneeshkumar - the fix was deployed in all regions.

Yours seems to be a different scenario. From the screenshot of your logs seems that your specific Job instance was failed because the underlying node was being scaled down.

Do you have retries configured in your Job?

If you are still seeing issues, would you mind opening a new GitHub Issue so we can properly track it?
