### ISSUE TITLE
Redploying via Arm/Bicep with vNet fails

### ISSUE THREAD

**Issue by mortenf1984** [microsoft/azure-container-apps#912]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When redeploying a ARM or Bicep Deployment (Or redeploy via Export Template from portal) even without making changes, it gives you this error:
{"code":"ManagedEnvironmentInvalidNetworkConfiguration","message":"The environment network configuration is invalid: The delegated subnet cannot be used by any other Azure resources."}

Subnet it is complaining about is the subnet this CAE is using, so it should not complain.

### Steps to reproduce
1. Create a CAE with vNet integration in Norway East (Not tested other regions) either via ARM/Bicep or Portal
2. Once redeploy is complete, redeploy the same template or go too Export Template and selectet Deploy and deploy without making changes

**Expected behavior** [What you expected to happen.]
I expect it to deploy without error or changes

**Actual behavior** [What actually happened.]
Failes with error message "The environment network configuration is invalid: The delegated subnet cannot be used by any other Azure resources", but subnet is used by it self, and should not be a issue.

### Additional context
Issue has been recreated with deployment from Bicep and from the portal.

**Comment by maskati** [comment]
Same here. Started happening within the last few days.

**Comment by padvdijk** [comment]
Same here for region westeurope. Started this morning

**Comment by epost-vitas** [comment]
Running into the same issue since this morning, last Friday morning (22nd of Sep 2023) it seemed to be working still.

**Comment by SriramAvatar** [comment]
Also facing the same issue from yesterday in westeurope.

**Comment by ractando** [comment]
Is anyone having this issue when the container app is not in a vnet ?
@mortenf1984 @SriramAvatar @maskati @padvdijk @epost-vitas

**Comment by mortenf1984** [comment]
I have not tested without a vNet, but got a Responce yesteday from Tomer in the Discord channel, that a fix had been implemented. Did a Re-Test today, and now I am able to redeploy as expected again. So it seems to be working again.

**Comment by SriramAvatar** [comment]
> Is anyone having this issue when the container app is not in a vnet ? @mortenf1984 @SriramAvatar @maskati @padvdijk @epost-vitas

My setup is in a vNet

**Comment by maskati** [comment]
Works for me now, tested in West Europe at 07:10 UTC.

**Comment by mortenf1984** [comment]
You can use this link:
https://discord.gg/9pXXCvsM
