### ISSUE TITLE
Azure Container App Job Bicep Template Validation does not fit to Keda Azure Pipelines Trigger Specification

### ISSUE THREAD

**Issue by fl-lutz** [microsoft/azure-container-apps#914]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a:
- [x] bug report
- [ ] documentation issue or request
- [ ] regression

### Issue description
When deploying a container app job through a bicep template, it is not feasible to configure the scale rule metadata value "requireAllDemands" as a bool, as documented in the [Keda Azure Pipelines Trigger](https://keda.sh/docs/2.11/scalers/azure-pipelines/). The Keda Scaler disregards the value if set as a string, rendering it ineffective.
### Steps to reproduce
1. Try deploying a Bicep Template similar to this one:

```
resource agentJob 'Microsoft.App/jobs@2023-05-01' = {
  name: jobName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentityResourceId}': {}
    }
  }
  properties: {
    configuration: {
      eventTriggerConfig: {
        parallelism: 1
        replicaCompletionCount: 1
        scale: {
          minExecutions: 0
          maxExecutions: 1
          pollingInterval: 5
          rules: [
            {
              name: 'azure-pipelines'
              type: 'azure-pipelines'
              metadata: {
                poolName: agentPool
                demands: 'someDemand'
                requireAllDemands: false
              }
              auth: [
                {
                  secretRef: 'organization-url'
                  triggerParameter: 'organizationURL'
                }
                {
                  secretRef: 'personal-access-token'
                  triggerParameter: 'personalAccessToken'
                }
              ]
            }
          ]
        }
      }
      replicaTimeout: 240
      replicaRetryLimit: 1
      registries: [
        {
          server: '${acrName}.azurecr.io'
          identity: managedIdentityResourceId
        }
      ]
      secrets: [
        {
          name: 'personal-access-token'
          value: personalAccessToken
        }
        {
          name: 'organization-url'
          value: organizationUrl
        }
      ]
      triggerType: 'Event'
    }
    environmentId: acaenv.id
    template: {
      containers: [
        {
          image: '${acrName}.azurecr.io/${imageName}'
          name: jobName
          resources: {
            cpu: json('1')
            memory: '2Gi'
          }
          env: [
            {
              name: 'AZP_TOKEN'
              secretRef: 'personal-access-token'
            }
            {
              name: 'AZP_URL'
              secretRef: 'organization-url'
            }
            {
              name: 'AZP_POOL'
              value: agentPool
            }
            {
              name: 'someDemand'
              value: 'true'
            }
          ]
        }
      ]
    }
  }
}

```

**Expected behavior**
It deploys the Container App Job with the metadata field "requireAllDemands".
**Actual behavior**
Invalid request body for container apps job. Does not conform to Container Apps Job schema, please visit for more information https://docs.microsoft.com/azure/container-apps/azure-resource-manager-api-spec?tabs=arm-template#container-app

The deployment validation failed
**Screenshots**         
Documentation of Keda Azure Pipelines Trigger:
![image](https://github.com/microsoft/azure-container-apps/assets/53431152/ffa1706b-387a-4170-8dd7-c10a031f9a4d)

**Comment by owattley-rotageek** [comment]
`requireAllDemands` only exists in `v2.10+` of the KEDA scaler. You can see the docs for `v2.9` do not contain that metadata property:

https://keda.sh/docs/2.9/scalers/azure-pipelines/

<img width="475" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/133657588/72d3e9c3-9cd6-4c6f-8547-bd273b28e8c0">


Whereas `v2.10` does:

https://keda.sh/docs/2.10/scalers/azure-pipelines/
<img width="473" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/133657588/353661f2-35be-4a47-afce-d0b6377e9710">


The problem here is likely to do with Microsoft not disclosing which version of KEDA is in use behind the scenes. Versions of KEDA come out frequently and scalers seems to have breaking changes with each new version. It's basically impossible to know what to do without pure trial and error and a lot of guesswork.

I have the same problem with GitHub Runner scaler. I cannot work out which version Container Apps is using. My gut feel is it's currently `v2.10` because the GitHub scaler didn't exist prior to `v2.10`, however this conflicts with what I have pasted above so I am left even more confused.

**Comment by vinisoto** [comment]
Hi, in Container Apps and Container Apps Jobs, scaler metadata is passed as string in all cases. Looking at the Azure Pipelines Scaler code, it seems that it is parsing to `bool` https://github.com/kedacore/keda/blob/8d16e417f5a81b71d9028b90888b522fe9e0a136/pkg/scalers/azure_pipelines_scaler.go#L233

![image](https://github.com/microsoft/azure-container-apps/assets/18271663/2b6ef022-9909-4f3c-9019-816a5f0cba33)

**Comment by vinisoto** [comment]
@owattley-rotageek: you can check the `kedaConfiguration` property in the managed environment to see which KEDA version is being used:

![image](https://github.com/microsoft/azure-container-apps/assets/18271663/3bec1c14-0119-4373-bab8-3b51692bbe48)


@fl-lutz: Looks like there was fix for this particular scaler: https://github.com/kedacore/keda/issues/4404 which went in KEDA 2.11 release (https://github.com/kedacore/keda/releases/tag/v2.11.0)


Container Apps currently uses KEDA 2.10.

**Comment by vinisoto** [comment]
We will rollout 2.11 in the next couple of weeks.

**Comment by vinisoto** [comment]
@Dspirit rollout started last week. We are expecting to complete it by the week of 12/11. By the way, we are upgrading to KEDA 2.12

**Comment by vinisoto** [comment]
Support for KEDA 2.12 has now been rolled out globally. Closing this issue thanks @fl-lutz for your patience here.
