### ISSUE TITLE
About containerapp extension support

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#916]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
containerapp command is available since Azure CLI v2.53.0, but I would like to know how long containerapp extension will be supported.
(Should I uninstall containerapp exentesion now and migrate to Azure CLI?)

### Additional context
- https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md
``` 
az containerapp: Move containerapp from CLI extension to core CLI
```

**Comment by torosent** [comment]
The container apps extension will still be available. It will contain preview features.

**Comment by YuKogasaka** [comment]
@torosent, thanks.
