### ISSUE TITLE
Setting up Continuous Deployment fails with reference to fields not present in Azure Portal

### ISSUE THREAD

**Issue by Kimbahir** [microsoft/azure-container-apps#919]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
Setting up Continuous Deployment via Azure Portal fails with reference to parameters that aren't visible in the user interface. Error code here:

```
Deployment template validation failed: 
'The value for the template parameter ' OidcRbacNameToContainerRegistryId' at line '53' and column '47' is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.'.
```

### Steps to reproduce
1. Create a container based on quick start template
2. After deployment of said container, go to Continuous Deployment
3. Choose Github -> Organization -> Repository -> Branch
4. Choose Docker hub, define image, login server (docker.io), username and pass
5. Press start

**Expected behavior** 
Azure Portal will create the workflow file and build the container and tag with the commit tag

**Actual behavior** 
Throws an error stating that "OidcRbacNameToContainerRegistryId" haven't been defined - something that isn't immediately available in the user interface.

**Screenshots**         
<img width="495" alt="Screenshot 2023-09-28 at 16 56 45" src="https://github.com/microsoft/azure-container-apps/assets/25718544/a5dd0e92-4616-4a61-8fb7-88825f8208e0">

### Additional context
This was done purely in the portal, and I am pretty sure this is how I did it roughly 6 months ago when I last created new container apps.

**Comment by StewartMckenzie** [comment]
Hey sorry about this, we found the issue and we are working on a fix. In mean time I recommend using the service principal option
<img width="683" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/34044735/cddc90a5-7d87-491b-bca7-fdeb32d08891">

**Comment by Kimbahir** [comment]
Hi @StewartMckenzie sounds great - looking forward to it! :) 

I could have sworn there weren't a Service Principal option at the bottom before when I tried to add continuous deployment, but now there is at least and everything is working again! Thanks a bunch

/Kim
