### ISSUE TITLE
Java app containerization and migration to Azure Container Apps

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure-container-apps#92]
The Azure Migrate: App Containerization tool [Java app containerization and migration Tool](https://docs.microsoft.com/en-us/azure/migrate/tutorial-app-containerization-java-kubernetes) Today,  currently supports : 

- Containerizing Java Web Apps on Apache Tomcat (on Linux servers) and deploying them on Linux containers on AKS
- Containerizing Java Web Apps on Apache Tomcat (on Linux servers) and deploying them on Linux containers on App Service

- Containerizing ASP.NET apps and deploying them on Windows containers on AKS.
- Containerizing ASP.NET apps and deploying them on Windows containers on Azure App Service.

RFE: Could you please intagrate this tool with  Azure Container Apps : 
- Containerizing Java Web Apps on Apache Tomcat (on Linux servers) and deploying them on Linux containers on Azure Container Apps
- Containerizing .Net core apps and deploying them on on Linux containers on Azure Container Apps

@dariagrigoriu @kendallroden

**Comment by ezYakaEagle442** [comment]
@rahug1190

**Comment by simonjj** [comment]
This should now be possible since we enabled this via Buildpacks some time back. Please get started here: https://learn.microsoft.com/en-us/azure/container-apps/java-overview
