### ISSUE TITLE
Jobs with custom command

### ISSUE THREAD

**Issue by svickers** [microsoft/azure-container-apps#920]
### This issue is a:
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am trying to create a set of jobs running on different schedules, running the same .py file with different parameters.  I can't find any examples of using the `--command` option when creating a new job and having a hard time figuring out how it should work.

### Steps to reproduce
1. create simple file.py
2. Try it out locally `docker build . -t test-image`
3. run container with custom command `docker run -t test-image python file.py`
4. set up job with additional param: `--command python file.py`

**Expected behavior** 
Expect it to run successfully.

**Actual behavior**
This shows up in the system logs 
`unable to start container process: exec: python file.py: executable file not found in $PATH: unknown`
Also, if I create a run.sh file in the directory with this as the contents:
```
#!/bin/sh

python file.py
```
then use `--command /app/run.sh`, everything works fine.

I've tried a number of different paths in the command and other things and feel like I am missing something really simple, just looking for one example.  

### Additional context
Here is my dockerfile

```
# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/engine/reference/builder/

ARG PYTHON_VERSION=3.11.5
FROM python:${PYTHON_VERSION}-slim as base

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

WORKDIR /app
# Copy the source code into the container.
COPY . .
RUN ls
RUN pip install -r requirements.txt
COPY --chmod=001 *.sh /app

# Run the application.
CMD ["python","-c", "print('hello from docker')"]
```

**Comment by ahmelsayed** [comment]
try with `--args python file.py`

`--args` == docker's CMD
`--command` == docker's entrypoint.
