### ISSUE TITLE
Authenticating Using GitHub App for GitHub Runner Scaler Jobs

### ISSUE THREAD

**Issue by kabal2010** [microsoft/azure-container-apps#921]
Using GitHub App for authentication by specifying *`appKey`* for *`scale-rule-auth`* does not work. The log keeps coming up with the error in the snip below.
![image](https://github.com/MicrosoftDocs/azure-docs/assets/43651292/f972f89c-dbd7-4d30-9293-fb1ef91bbdda)

Can someone please help me on how to authenticate with *`appKey`* instead of *`personalAccessToken`*

**Comment by vinisoto** [comment]
Currently we support KEDA 2.10. We will rollout support for KEDA 2.11 starting the week of 10/16

**Comment by kabal2010** [comment]
@vinisoto 
That is wonderful. I'll test and send confirmation at the feature is rolled out.

**Comment by kabal2010** [comment]
@vinisoto 
Just a confirmation if this is now available for testing

**Comment by kabal2010** [comment]
I've tested and can confirm *`appKey`* is now working for authentication

**Comment by kabal2010** [comment]
Apologies, my initial assertion is wrong as authentication using *`appKey`* is not working yet. Any update on this please?

**Comment by rexebin** [comment]
We tried the `appKey`, and got this error: `error parsing GitHub Runner metadata: no personalAccessToken given`

 `no personalAccessToken given` exception message only exists on version 2.10 or earlier. You can see the source code [here](https://github.com/kedacore/keda/blob/release/v2.10/pkg/scalers/github_runner_scaler.go). 

It means the scaler for the container app at this moment in time is on version 2.10, which doesn't support GitHub App authentication. GitHub App is supported from version 2.11.

**Comment by kabal2010** [comment]
Support for *`Keda 2.11`* is supposed to start at 10/16 as mentioned by @vinisoto.

**Comment by chatelain-io** [comment]
The version of Keda will be automatically updated or there will be a procedure ?

**Comment by vinisoto** [comment]
> The version of Keda will be automatically updated or there will be a procedure ?

The KEDA version will automatically update

**Comment by kabal2010** [comment]
Any update when it'll be available?

**Comment by rexebin** [comment]
> > The version of Keda will be automatically updated or there will be a procedure ?
> 
> The KEDA version will automatically update

How do we check which version of the KEDA Github Runner Scaler the container app jobs are using?

**Comment by rexebin** [comment]
Is there a plan to make the KEDA scaler configurable and pluggable so that end users can choose their own version of scalers?

**Comment by rexebin** [comment]
As of 23/11/2023, after replacing the PAT Token with the Github App setup, we got the 2.10 error: `error parsing GitHub Runner metadata: no personalAccessToken given`. 

So our deployment of Container App Jobs is still on 2.10 Github Runner Scaler.

We would be grateful if this upgrade could be done at your earliest opportunity.

**Comment by chatelain-io** [comment]
> > > The version of Keda will be automatically updated or there will be a procedure ?
> > 
> > 
> > The KEDA version will automatically update
> 
> Good to know, thank you! How do we check which version of the KEDA Github Runner Scaler the container app jobs are using, please?

Azure Portal:
On the Container App Environment's Overview page, click see more and KEDA and Dapr version will show up.

Azure CLI:
`az containerapp env show -g rg_name -n container_app_env_name --query properties.kedaConfiguration.version -o tsv`

**Comment by rexebin** [comment]
> > > > The version of Keda will be automatically updated or there will be a procedure ?
> > > 
> > > 
> > > The KEDA version will automatically update
> > 
> > 
> > Good to know, thank you! How do we check which version of the KEDA Github Runner Scaler the container app jobs are using, please?
> 
> Azure Portal: On the Container App Environment's Overview page, click see more and KEDA and Dapr version will show up.
> 
> Azure CLI: `az containerapp env show -g rg_name -n container_app_env_name --query properties.kedaConfiguration.version -o tsv`

Thank you!
Confirmed, 2.10: ![image](https://github.com/microsoft/azure-container-apps/assets/10893959/dda9ff83-c844-4828-b410-79145a9d3d93)

**Comment by hieunguyen-gkgab** [comment]
> Currently we support KEDA 2.10. We will rollout support for KEDA 2.11 starting the week of 10/16

@vinisoto do you know when is the rollout expected to finish? Thank you very much!

**Comment by vinisoto** [comment]
@hieunguyen-gkgab - we are expecting to complete this rollout on the week of 12/11. By the way, we are rolling out KEDA 2.12

**Comment by kabal2010** [comment]
Thanks @vinisoto.
Looking forward to that

**Comment by kabal2010** [comment]
Can confim this has now been done based on the snip below.
![image](https://github.com/microsoft/azure-container-apps/assets/43651292/c7a22558-955e-47b9-ae88-4612a3e4c206)
