### ISSUE TITLE
Container App Job unexpectedly killed during execution

### ISSUE THREAD

**Issue by alexpovel** [microsoft/azure-container-apps#922]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I am running an application using the newly-GA Container App Jobs feature. The run containerized application gets killed unexpectedly, and I cannot seem to find any indication as to why.

### Steps to reproduce
1. Write application, containerize it. My application is essentially glue code between network calls and writing found content to blob storage.
2. Observe it work, using container storage for temporary scratch space before pushing to blob storage.
3. It eventually gets killed.

**Expected behavior** [What you expected to happen.]

App doesn't get killed.

**Actual behavior** [What actually happened.]

App gets killed.

From console logs, one can see the app is none the wiser: the last emitted log message is a "happy path" log message. There's no stack trace (app is written in Python). I have not checked/instrumented for making received signals visible yet.

The system logs are effectively empty:

![image](https://github.com/microsoft/azure-container-apps/assets/48824213/f380e82b-28dd-44ab-a609-c4f6faaf6997)

As a retry limit, `1` is configured, so this initial failure exceeds that limit and no retries occur.

The system logs **used to contain a warning** about Pod-local storage limits of 4 GiB being exceeded, and then subsequently a forced shutdown. Ever since I saw that, I invested into observability of local disk usage. https://github.com/microsoft/azure-container-apps/issues/896 had a very similar issue, but Jobs cannot be `ssh`ed into. My app now has instrumentation to write out current disk usage to its logs, once a second. Through it, I can see that for the last 8 seconds of the execution run's lifetime, the application sits at *around* 5.8 GB, where it plateaus before execution ends prematurely. During this time, there's an ongoing download running in the background, so usage slightly increases still (but is rounded to 5.8 GB).

https://github.com/microsoft/azure-container-apps/issues/890 is also similar but also not about Jobs.

**The issue could be anything**, but my application doesn't do anything worth writing home about, except for its requirement of a couple of gigs of scratch space. Following the [docs](https://learn.microsoft.com/en-us/azure/container-apps/storage-mounts?pivots=azure-cli#container-file-system), I also tried provisioning an `emptyDir`. The Job is configured at 2 CPU and 4 GiB of memory, so the resulting `emptyDir` I use should come in at 8 GiB capacity. The reported 5.8 GiB should fit well within, but that scenario also crashes, also without output in the system logs.

I am unclear why once I got the warning about exceeding 4 GiB, but now don't anymore.

My use case doesn't need an Azure Files mount, so I am trying to circumvent that extra complexity. `emptyDir` would be nice and easy.

---

Lastly, https://github.com/microsoft/azure-container-apps/issues/911 could be the reason I am seeing failures as well. This Job deployment is in West Europe as well. It would also explain why the disk usage warning isn't always present.

**Comment by alexpovel** [comment]
I am getting intermittent and unexpected *successes*, see #927 . That proves the code and execution in itself *can* succeed in principle.

**Comment by alexpovel** [comment]
Through some [instrumentation](https://psutil.readthedocs.io/en/latest/#memory), it became clear the running process consumes more than 4 GiB of memory (the configured memory for the Job). I cannot confirm this 100%, as reported numbers of available/free/used memory are a bit unclear, but am pretty sure. I now suspect that to be the underlying issue, not disk space. So if this hypothesis holds true, execution killing works as expected; in that case, it'd be of great help to surface more diagnostics in the system logs (reason for killing, resource usage at time of killing etc.)

**Comment by vinisoto** [comment]
hi @alexpovel can you please send us an email to `acasupport at microsoft dot com` with your Job name and subscription Id so we can dig deeper and understand if there are log improvements that are needed?

**Comment by alexpovel** [comment]
Thanks, sent.

**Comment by avneeshkumar** [comment]
We are also facing this issue .. There is no way that RAM consumption has gone over 4GB in our case. Also the same job with same events after getting success in subsequent runs. We have Azure Queue Based Trigger so till that processing is completely finished the item won't be deleted from the Azure Storage queue and keep triggering the job.
