### ISSUE TITLE
Scaling rule for Azure Event Hub using Managed Identity

### ISSUE THREAD

**Issue by andreaskasc** [microsoft/azure-container-apps#925]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Hi Everyone,

I am trying to create a scaling rule for azure event hub in my container app and I am having some difficulties with the Authentication part. I am using a managed identity for the container app but I am not sure how I can do this in the scaling rule. I am trying to do it through the Azure Portal first and the end goal is to use bicep (as I do for the container app already).
I have seen the documentation [here](https://github.com/kedacore/keda-docs/blob/main/content/docs/2.2/scalers/azure-event-hub.md) which means that KEDA supports my need but I wasn't able to understand how to use it in the container app, i.e. what to put in the Authentication section:

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/127096200/ceefd546-0f0f-4b18-950e-7d46732cc1e3)

Any ideas if this is possible and example on how to do it?

**Comment by andreaskasc** [comment]
I guess it is not supported currently according to [this issue](https://github.com/microsoft/azure-container-apps/issues/592).

**Comment by dariagrigoriu** [comment]
Managed identity support for KEDA scaling is an enhancement request.
