### ISSUE TITLE
Container App Job execution time reported incorrectly

### ISSUE THREAD

**Issue by alexpovel** [microsoft/azure-container-apps#927]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

![image](https://github.com/microsoft/azure-container-apps/assets/48824213/634bdae9-7a26-439b-a6e3-06827dbb8bfc)

### Steps to reproduce
1. Deploy Container App Job
2. Reproduction steps are unclear. Intermittent issue. I didn't touch this, this ran overnight, so the three runs in the screenshot are identical from my perspective.

**Expected behavior** [What you expected to happen.]

Report time as what it is.

**Actual behavior** [What actually happened.]

Time reported is much longer. `End time` - `Start time` is about 6 minutes. Time reported is 1h. The timeout is configured as `3600` seconds, so perhaps it's reporting the timeout?

### Additional context

The failures in the screenshots are related to https://github.com/microsoft/azure-container-apps/issues/922 , but unrelated to the issue.

**Comment by vinisoto** [comment]
triaging this together with #922

**Comment by vinijmoura** [comment]
Same problem here!!!!
![image](https://github.com/microsoft/azure-container-apps/assets/8333012/ef702bdf-d4d5-48c0-b8a9-e856e076296a)

**Comment by vinisoto** [comment]
Hi, this is a UX bug which incorrectly displays the duration. We are working on a fix for this.

**Comment by vinisoto** [comment]
Hi, the fix will be deployed within the next two weeks.
