### ISSUE TITLE
can not add new "Container Apps Environment" be to an existing vnet 

### ISSUE THREAD

**Issue by devna13** [microsoft/azure-container-apps#933]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X ] bug report -> please search issues before submitting
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I can't add "Container Apps Environment" to existing vnet ? the subnets are not loading and if i click on new subnet I can see all the existing subnets but can not create a new subnet.

can new "Container Apps Environment" be added to an existing vnet ?

### Steps to reproduce
1. Create 
![image](https://github.com/microsoft/azure-container-apps/assets/4080343/bbea1bc2-7751-469c-84b4-b732f9365758)
1. Create vnet 
2. create a Container Apps Environment and try to set it's vnet to existing vnet.

**Expected behavior** [What you expected to happen.]
add CAE to existing vnet/subnet

**Actual behavior** [What actually happened.]
forces you to create a new vnet

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/4080343/4ef9cad8-2a1b-4260-8cfc-413084037ddd)
![image](https://github.com/microsoft/azure-container-apps/assets/4080343/088927e3-771b-445c-b977-225c7db691fa)
![image](https://github.com/microsoft/azure-container-apps/assets/4080343/465492f3-834f-4fa3-9d85-3acbd3afb655)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
Portal

**Comment by pagariyaalok** [comment]
Could you confirm the subnet CIDR range is meeting the criteria?
For Workload profiles environment current requirement is /27
https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=azure-cli#workload-profiles-environment
For Consumption only environment current requirement is /23
https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=azure-cli#consumption-only-environment

**Comment by devna13** [comment]
Thanks that was the issue.
