### ISSUE TITLE
Unexpected "canary app" running in environment

### ISSUE THREAD

**Issue by maskati** [microsoft/azure-container-apps#942]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Logs show unexpected app `cappscanary-*` running in the environment since 12th October in West Europe. This app has two variants:
- Container named `k8se-localproxy` running image `mcr.microsoft.com/k8se/proxy:1.0.2`
- Container named `containerapps-helloworld` running image `mcr.microsoft.com/k8se/canaryapp:1.11.0-m`

Either these are internal infrastructure that mistakenly log or infrastructure that has been added which does log, in which case it would be good to include in documentation.

**Comment by vturecek** [comment]
Hi @maskati, yes these are infrastructure components that help us monitor the health of each environment and should not interfere with your applications. We'll look into why you're seeing that in your logs.

**Comment by sanchitmehta** [comment]
You shouldn't see these logs in your logging workspace now. This has been fixed

**Comment by maskati** [comment]
I'm not seeing these logs anymore. Thanks!

**Comment by andrew-from-toronto** [comment]
I'm seeing these in my telemetry on an AKS cluster, on a deployment where ACA is not even being used....
