### ISSUE TITLE
Secret volume mount failing in jobs

### ISSUE THREAD

**Issue by Kukukuchu** [microsoft/azure-container-apps#943]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I can't seem to add secret volume mount to the job.
Container fails to start with these messages in logs:
```
MountVolume.SetUp failed for volume "config" : secret "capp-%jobappname%" not found
Unable to attach or mount volumes: unmounted volumes=[config], unattached volumes=[envoy-xds-certs localproxy-certs identity-config identity-secret config envoy-config]: timed out waiting for the condition
```
%jobappname% actually prints name of the job container app.
"config" is name of the volume i am trying to mount but 'capp-%jobappname%' secret is figment of imagination - it is neither an app secret nor mapped in the volume spec.

### Steps to reproduce
```
resource job 'Microsoft.App/jobs@2023-05-02-preview' = {
  name: 'volumetestjob'
  location: location
  properties: {
    environmentId: environment.id
    configuration: {
      replicaTimeout: 15*60
      triggerType: 'Schedule'
      scheduleTriggerConfig: {
        cronExpression: '0 2 * * 1'
      }
      secrets: [
        {
          name: 'mounted-secret'
          value: 'test value'
        }
      ]
    }
    template: {
      containers: [
        {
          image: 'hello-world:latest'
          name: 'volumetest'
          resources: {
            cpu: 1
            memory: '2Gi'
          }
          volumeMounts: [
            {
              mountPath: '/config'
              volumeName: 'config'
            }

          ]
        }
      ]
      volumes: [
        {
          name: 'config'
          storageType: 'Secret'
          secrets: [
            {
              path: 'config.json'
              secretRef: 'mounted-secret'
            }
          ]
        }
      ]
    }
  }
}

```

Deploying that is successful, but when i try to run the container (via CLI or waiting for schedule to run it) execution is created but times out eventually.

I also tried adding a volume mounted secret via portal UI. There I went to Edit Container, Volume Mounts tab, created a new volume (with different name) and selected single secret from app secrets, added volume mount for that volume and hit save. This changed nothing - logs still complain about volume i tried to deploy via bicep.

**Expected behavior** [What you expected to happen.]

To have /config/config.json file in container with value "test value"

**Actual behavior** [What actually happened.]

Container can't start. Logs show:
(for `ContainerAppSystemLogs_CL| where JobName_s == 'volumetestjob' and EnvironmentName_s == '...'`)
```
MountVolume.SetUp failed for volume "config" : secret "capp-volumetestjob" not found
Replica 'volumetestjob-4hpc27m-6hdgq' for Job Execution 'volumetestjob-4hpc27m' has been scheduled to run on a node.
Successfully created pod for Job Execution 'volumetestjob-4hpc27m'
MountVolume.SetUp failed for volume "config" : secret "capp-volumetestjob" not found
MountVolume.SetUp failed for volume "config" : secret "capp-volumetestjob" not found
MountVolume.SetUp failed for volume "config" : secret "capp-volumetestjob" not found
.
.
.
Unable to attach or mount volumes: unmounted volumes=[config], unattached volumes=[envoy-xds-certs localproxy-certs config envoy-config]: timed out waiting for the condition
MountVolume.SetUp failed for volume "config" : secret "capp-volumetestjob" not found
.
.
.
```

**Comment by vinisoto** [comment]
Hi, the fix for this will be deployed within the next two weeks.

**Comment by anandanthony** [comment]
Fix for this has been deployed across all regions.

**Comment by mburumaxwell** [comment]
This fix semes to have caused invalid data in the ARM resources so the SDKs do not work as expected (I tested with the .NET SDK). For the same secret mounted in a ContainerApp vs a ContainerAppJob, the `keyVaultUri is not present (i.e. null) in the former but it is an empty string in the latter.

Example for Container App:

```json
"secrets": [
    {
        "name": "authentication-internal-key",
        "keyVaultUrl": "https://<omited>.vault.azure.net/secrets/<omited>",
        "identity": "/subscriptions/<omited>/resourceGroups/<omited>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<omited>"
    },
    {
        "name": "connection-strings-mongo"
    }
],
```

Example for Container App Job:

```json
"secrets": [
    {
        "name": "authentication-internal-key",
        "keyVaultUrl": "https://<omited>.vault.azure.net/secrets/certificates-auth-internal-key",
        "identity": "/subscriptions/<omited>/resourceGroups/<omited>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<omited>"
    },
    {
        "name": "connection-strings-mongo",
        "keyVaultUrl": "",
        "identity": ""
    }
],
```

**Comment by anandanthony** [comment]
@mburumaxwell the fix for secret volume mounts would not have introduced this behavior, it looks like an issue with SDK. Can you please open a new issue and we will investigate/address this.

**Comment by mburumaxwell** [comment]
It is possible that it wasn't introduced by the change but it sure looks off that the `keyVaultUri` is an empty string for jobs but not for the app. It wasn't possible to test this because mounting secrets was failing prior.

Maybe we can start with https://github.com/Azure/azure-sdk-for-net/issues/38385 ?

**Comment by mburumaxwell** [comment]
A more specific issue: https://github.com/Azure/azure-sdk-for-net/issues/40119

**Comment by vinisoto** [comment]
hi @mburumaxwell - the fix for this issue has been deployed.

**Comment by mburumaxwell** [comment]
Thanks @vinisoto 
When can we expect to see it in WestEU?
