### ISSUE TITLE
ContainerAppConsoleLogs_CL not generating on some Container App Jobs executions  

### ISSUE THREAD

**Issue by jose-kalderos** [microsoft/azure-container-apps#945]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We have multiple Container App Jobs and are experiencing an intermittent issue where ContainerAppConsoleLogs_CL don't appear on every run. This has occurred even on jobs that execute without errors. ContainerAppSystemLogs_CL are always generated. Increasing Container resource allocation has not helped. Increasing the replica retry limit has seemed to help a bit, but logs still fail on a more than 50% of executions. 

A typical flow of System logs looks like this: 
<img width="155" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/63258598/d1f97658-6fb1-427b-bf2a-233369c5333d">

### Steps to reproduce
1. Trigger Container app job

**Expected behavior** [What you expected to happen.]
We expect ContainerAppConsoleLogs_CL to populate for each execution
**Actual behavior** [What actually happened.]
ContainerAppConsoleLogs_CL don't appear for more than 50% of our executions
**Screenshots**         

### Additional context
We've monitored the streaming logs and ContainerAppConsoleLogs don't appear here when this issue occurs. 
We are running a consumption only plan

**Comment by vinisoto** [comment]
We are investigating.

**Comment by sanjevrainmakr** [comment]
I am noticing the same issue myself.

**Comment by LuciaQX** [comment]
Mark it as I met a same error. When I set the type as Manual, I can see the logs as expected. But if I set it as Schedule, no logs there.

**Comment by ricardolb** [comment]
Having the same issue

**Comment by oekstrand** [comment]
Seeing the same issue for scheduled jobs.

**Comment by vinisoto** [comment]
Hi, thank you @jose-kalderos and all others for reaching out.

We detected an issue in which short-lived (<60 seconds) executions, in some cases, would not emit logs. This issue would occur for all trigger types (manual, event, scheduled).

The fix for this issue has been rolled out.

Please comment here if you are still experiencing missing logs.

**Comment by dsczltch** [comment]
Hi,
Same error on our side, we created a manual and an event driver job to use this service for azure devops agents pool, the container fail, and there is no log at all in Log Analytics :/

**Comment by zsharp-gls** [comment]
I'm seeing the exact same issue as dabedin reported:

`Failed to resolve table or column expression named 'ContainerAppConsoleLogs_CL'`

This is on a newly created Container App Job

**Comment by pbomma-avx** [comment]
![Screenshot 2024-01-29 at 8 40 53 PM](https://github.com/microsoft/azure-container-apps/assets/74566557/9f1c3210-de66-4624-82d8-8821c6ce4315)
Logs appear after few hours!!

**Comment by devluke88** [comment]
seeing the same issue as [pbomma-avx](https://github.com/pbomma-avx)

**Comment by hbailles3** [comment]
Seeing the same issue as @pbomma-avx which is really frustrating as we can't see what's going on when there's an issue.

**Comment by vinisoto** [comment]
@hbailles3 @devluke88 @pbomma-avx @zsharp-gls the issue you are seeing is being tracked in #1069

**Comment by jason-berk-k1x** [comment]
@vinisoto how does #1069 relate to this issue?

I opened #1137 which _seems_ more related

**Comment by AdrianProkop** [comment]
Any updates in here? It's June...

**Comment by pablospe** [comment]
Any news on this issue? @jason-berk-k1x, @AdrianProkop, how did you solve your problems?
Is there other way to see the logs perhaps?

**Comment by Tensai123** [comment]
I made workaround - my app inside container is forwarding logs to my telemetry system directly on its' own, I wouldn't get it done if I'd wait for microsoft to help...

**Comment by pablospe** [comment]
I was thinking to save the log in files (like glog style) and then put it in some storage. The telemetry sounds good idea, is your "telemetry system" in the azure container environment too, or is something external?
