### ISSUE TITLE
Dapr CRON binding not working with 0/1 scaling

### ISSUE THREAD

**Issue by jpiquot** [microsoft/azure-container-apps#947]
### This issue is a: 
- [x] bug report 
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have deployed an Azure Container App configured with a scaling range of 0/1, designed to be triggered by a Dapr Cron inbound binding component. While the trigger functions correctly when the scaling is explicitly set to 1/1, it fails to activate when the scaling range is configured as 0/1. This issue persists even after adding an HTTP scaling rule.
### Steps to reproduce
1. Create a container app with a Dapr CRON inbound binding component
2. Scale the App to 0/1

**Expected behavior** The container should upscale from 0 to 1 when the CRON binding component triggers the App

**Actual behavior** The App is not upscaled

**Comment by ItalyPaleAle** [comment]
The cron binding runs within a Dapr, so it does require Dapr to be running. If your application is scaled to 0, there's no Dapr sidecar running, so the cron binding isn't running and can't trigger a scale-up. You will need at least 1 instance of your app running for the cron binding (or any other input binding or pubsub component) to work.
