### ISSUE TITLE
The latest version of the extension is a year behind the ARM version for Container Apps

### ISSUE THREAD

**Issue by moattarwork** [microsoft/azure-container-apps#948]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The latest version of extension does not support the features from latest version of ARM which was in preview from Nov last year and they are released already

### Steps to reproduce
1. Try to update an up build with terraform, Pulumi or Bicep with the latest official version from Azure team 
2. You get an error indicating (WorkloadProfilePropertyNotSupportedInApiVersion) WorkloadProfiles configuration is not supported in 2022-10-01 api version. Use 2022-11-01-preview or above. 

**Expected behavior** [What you expected to happen.]
Run smoothly

**Actual behavior** [What actually happened.]
Error

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal? CLI

**Comment by torosent** [comment]
Hi @moattarwork , What is the version that you are using? 
Can you try updating using `az extension update -n containerapp`
Please make sure you are using the latest AZ cli as well.
![image](https://github.com/microsoft/azure-container-apps/assets/17064840/23c4f105-2b00-4df9-9c86-e36463048781)

**Comment by moattarwork** [comment]
Sorry for the delay @torosent. It worked perfectly. Thanks for the help.
