### ISSUE TITLE
Azure Container App does not scale down to zero with Service Bus Queue KEDA rule

### ISSUE THREAD

**Issue by tino-github** [microsoft/azure-container-apps#952]
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have deployed an Azure Container App configured with a scaling range of 0/10, designed to be triggered by a Dapr service bus queue inbound binding component. Messages that come into the service bus queue are being picked up successfully, but when I have no messages for the cooldown period (300 seconds), the container does not scale back to 0 but remains in the running state.

### Steps to reproduce
1. Create a container app with a Dapr service bus queue component
2. Set KEDA rule with the following settings:
![image](https://github.com/microsoft/azure-container-apps/assets/13571079/213a83ea-3356-4761-aa63-611522baab45)

4. Scale the App to 0/10
![image](https://github.com/microsoft/azure-container-apps/assets/13571079/3d299e4e-0b7e-46bb-9012-27d99835633c)

5. Send one message and wait

**Expected behavior** [What you expected to happen.]
The container should activate when there is a message in the service bus **and** scale down to zero when there are no messages within the Azure Service Bus queue for the cooldown period (300 seconds).

**Actual behavior** [What actually happened.]
The App is not scaled down to zero, it remains running.

**Comment by SpiritZhou** [comment]
Hi, it looks like the Service Bus connections info in Authentication has the wrong parameter name. It should be "connection". Could you help to update it and try again?
Ref: https://keda.sh/docs/2.12/scalers/azure-service-bus/#authentication-parameters

![image](https://github.com/microsoft/azure-container-apps/assets/4278354/bbd1ba94-ec52-47be-8e2e-d29871054e41)

**Comment by tino-github** [comment]
I have updated the parameter name to "connection" but still one replica remains running.

**Comment by CeyssensStef** [comment]
I was running into the same issue. In the scaling rule, I used a (container app) secret that was a key vault reference.
After changing it to not use a secret from key vault but just a container app secret, the scaling started working again.
![image](https://github.com/microsoft/azure-container-apps/assets/62791928/1372257b-068c-4832-851e-6698ba113402)

Although this solves the issue, using key vault references for the scaling rules should be possible in my opinion.

**Comment by tino-github** [comment]
Changing the key to a "Container Apps Secret" did the job. After the cooldown period (5 minutes) it scales down to zero replicas.
