### ISSUE TITLE
Cannot deploy to Azure Container Apps

### ISSUE THREAD

**Issue by mjakeirwin** [microsoft/azure-container-apps#954]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am getting the following error trying to deploy to my Azure container app environment. I have changed no settings with the environment or the container that I am deploying. The same container was able to be deployed last night

Error code
BadRequest
Message
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-33fa8c75329467ff0514954b42323bb4-9b331f3e3dc78d2b-01","errors":{"$":["Unknown properties additionalPortMappings in Microsoft.ContainerApps.WebApi.Views.Version20230501.ContainerAppIngress are not supported"]}}

### Steps to reproduce
1. Deploy revision on Azure container app
2. ..

**Expected behavior** [What you expected to happen.]
Container to be deployed

**Actual behavior** [What actually happened.]
Sending this error code:
Error code
BadRequest
Message
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-33fa8c75329467ff0514954b42323bb4-9b331f3e3dc78d2b-01","errors":{"$":["Unknown properties additionalPortMappings in Microsoft.ContainerApps.WebApi.Views.Version20230501.ContainerAppIngress are not supported"]}}

**Screenshots**         
![Screenshot 2023-10-24 at 11 30 01 AM](https://github.com/microsoft/azure-container-apps/assets/42719036/506f8458-5f5d-4c60-99ec-ee35ab971982)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
Portal

**Comment by ktesoufi** [comment]
I am getting the same error when using the Portal to create a new revision via the UI.

**Comment by JennyLawrance** [comment]
Thanks for the bug report. We are investigating.

**Comment by sanchitmehta** [comment]
**Issue Update**: We've discovered a bug in Portal where an incorrect API version is being utilized for a subset of our users. This affects the updating of the `additionalPortMappings` property.

Our team is actively working on a fix. We'll provide an updated timeline for deployment soon. We appreciate your patience

**Comment by miguelEsteban** [comment]
same here

**Comment by sanchitmehta** [comment]
**Issue Update 3:** We have rolled out a fix for this issue across all regions, please let us know if you still face any issue
