### ISSUE TITLE
Maximum replicas

### ISSUE THREAD

**Issue by pbartos** [microsoft/azure-container-apps#96]
By the documentation I should be able to set the maximum number of replicas up to 25, but only 10 is allowed in configuration (UI, CLI)

`maxReplicas | Maximum number of replicas running for your container app. | n/a | 1 | 25!`

![image](https://user-images.githubusercontent.com/4380421/152480875-0cd76214-0a8c-4df7-8c7f-135d751ce7a6.png)

**Comment by Hipster74** [comment]
Yes, same problem here, trying to use bicep to deploy ACA, setting MaxReplicas to 25 gives me error "The maxReplicas must not be bigger than 10".

[ACA Scale - Maxvalue = 25](https://docs.microsoft.com/en-us/azure/container-apps/scale-app)

I am deploying to region "northeurope".

**Comment by kendallroden** [comment]
Thanks for reporting. Will get back to you

**Comment by kendallroden** [comment]
@etheodoridou is there an update? Can we close this out?

**Comment by liuqidake** [comment]
@kendallroden I am looking into this issue now. Will keep you updated once there is a fix out

**Comment by liuqidake** [comment]
@pbartos It looks like the fix was already on public azure by Feb 11th. The info tip shows the correct message 
![minmaxinfo](https://user-images.githubusercontent.com/33185278/163593233-fd046458-e97b-46ce-8226-836dd4eb18f3.png)

**Comment by pbartos** [comment]
Still invalid in documentation, but I can close it. I am ok with the clarification that the real max value is 10.

![image](https://user-images.githubusercontent.com/4380421/163937808-ce2c82bb-0133-42c6-bf31-a7de753816ae.png)

**Comment by anthonychu** [comment]
Tagging @ramimsft @kendallroden @craigshoemaker who are currently updating this doc

**Comment by ahmelsayed** [comment]
@pbartos is right, the current max is 10. We should fix the docs.

**Comment by craigshoemaker** [comment]
The docs are now updated and will publish to the public site around 10am Pacific.
