### ISSUE TITLE
ContainerAppRegistryCredentials are not supported

### ISSUE THREAD

**Issue by junior-juarez-MSFT** [microsoft/azure-container-apps#961]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The following error message shows up when creating or updating Azure Container Apps Job from portal:

`{'type':'https://tools.ietf.org/html/rfc7231#section-6.5.1','title':'One or more validation errors occurred.','status':400,'traceId':'00-e6cced3e00bf9140de82b9378e25550e-fb751963f71e0d42-01','errors':{'$[0]':['Unknown properties isUpdated, registryResourceId in Microsoft.ContainerApps.WebApi.Views.Version20230502Preview.ContainerAppRegistryCredentials are not supported']}}`

This a report on behalf of customer through support ticket.

Customer is trying to use MSI in conjunction with ACR for authentication.

### Steps to reproduce
Try to update registry settings for ACA Jobs from Azure portal.

**Expected behavior** [What you expected to happen.]
Container App Job should be update successfully from Azure Portal while updating registry settings.

**Actual behavior** [What actually happened.]
This issue is happening on API version `2023-05-02-Preview`

**Comment by junior-juarez-MSFT** [comment]
This G-issue is similar to what was fixed here:

https://github.com/microsoft/azure-container-apps/issues/954

Let me know if the above roll out included fixes this new issue as well.

**Comment by vinisoto** [comment]
hi @junior-juarez-MSFT; I was able to successfully set different Container Apps registry credentials using the portal with and without Managed Identity.

The symptoms you describe correlate with the fix that was rolled out for #954.

Can you please verify that your scenario is working? Thanks!
