### ISSUE TITLE
Azure Container Apps autoscalers using KEDA github-runner

### ISSUE THREAD

**Issue by MaximeMnt** [microsoft/azure-container-apps#967]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

We have tried setting up Github runners on Azure Container Apps using the [github-runner KEDA scaler](https://keda.sh/docs/2.12/scalers/github-runner/). 
After configuring KEDA & setting up the scale settings, we’ve noticed that the github runner is not scaling at all. 
We can see the following system logs: **KEDA is starting a watch for revision 'ca-ghrunner-sbx--k8eq6q5' to monitor scale operations for this revision**
Right after this message we are seeing the following: 
-	**KEDA is stopping the watch for revision 'ca-ghrunner-sbx--k8eq6q5' to monitor scale operations for this revision**
-	**ScaledObject was removed from KEDA watch and would not be auto-scaled. Please check https://learn.microsoft.com/en-us/azure/container-apps/dapr-overview**

### Steps to reproduce
1. Setup Workload profiles container apps using the 'github-runner' KEDA scaler 
2. Setup autoscaling and trigger github actions.

**Expected behavior** The container apps should auto scale based on the queued jobs. 

**Actual behavior** no auto scaling.

**Screenshots**         
This is my KEDA configuration:
![image](https://github.com/microsoft/azure-container-apps/assets/43829863/7b1fd667-7d74-4f13-b56f-787c2d890ded)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by anandanthony** [comment]
@MaximeMnt, wanted to check if there is any specific steps/documentation you are following to configure your **Container App** to run based on GitHub actions? From the log message you shared - `ScaledObject was removed from KEDA watch and would not be auto-scaled. Please check https://learn.microsoft.com/en-us/azure/container-apps/dapr-overview`, are you following the steps in this [article](https://learn.microsoft.com/en-us/azure/container-apps/dapr-overview)?

We have steps to setup a **Container App Job** with GitHub Actions [here](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-github-actions), which triggers an execution for GitHub action.

**Comment by LianaAdaza** [comment]
Thank you for your report! The documentation has been updated. Please create a new issue if you continue to experience difficulties.
