### ISSUE TITLE
[CRITICAL] Dapr resiliency deployed, and no docs on how to adjust default timeout

### ISSUE THREAD

**Issue by bjorkstromm** [microsoft/azure-container-apps#968]
Dapr resiliency was recently deployed, and customers are starting to see logs like
> Error processing operation DaprBuiltInServiceRetries. Retrying in 1s…

Because default timeout is 15s. Some customers might have Service Invocations taking longer than that. These used to work, but suddenly broke.

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)

### Issue description
See comments:
-  https://github.com/microsoft/azure-container-apps/issues/585#issuecomment-1786778480
- https://github.com/microsoft/azure-container-apps/issues/585#issuecomment-1787039991

### Steps to reproduce
1. Do service invocation using Dapr that takes longed than 15s
2. Dapr resiliency kicks in and retries

**Expected behavior** [What you expected to happen.]
Service Invocation should continue to work as it did before Dapr resiliency support was deployed.

**Actual behavior** [What actually happened.]
Service Invocation taking longer than 15s does not work

**Comment by greenie-msft** [comment]
Hi @bjorkstromm, 

Thank you for bringing this issue to our attention.
 
We are rolling out a fix for this issue, and we anticipate its completion by end of day ( in the PST time zone). Please let me know if you are still experiencing the issue tomorrow or have any further questions/concerns.

**Comment by bjorkstromm** [comment]
Thank you @greenie-msft for fast response 👍 I'll keep you posted.

**Comment by bjorkstromm** [comment]
@greenie-msft

> We are rolling out a fix for this issue, and we anticipate its completion by end of day ( in the PST time zone). Please let me know if you are still experiencing the issue tomorrow or have any further questions/concerns.

Confirmed that everything is working again. Thank you! Closing this issue now.
