### ISSUE TITLE
Subnet not released by Container Apps environment after deleting the environment

### ISSUE THREAD

**Issue by venkatavishnu0207** [microsoft/azure-container-apps#974]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

Subnet not released by Container Apps environment to reuse even after the environment is deleted.

### Steps to reproduce
1. Create a private Vnet and subnet with Microsoft.Apps/Environments delegation.
2. Using this subnet create Container Apps environment with Workload Profile as Environment type.
3. Create container App using above created Container Apps environment.
4. Now, delete the Container Apps environment created in step2.
5. Try to use the subnet created in step1 and create a new Container Apps environment.

**Expected behavior** [What you expected to happen.]
A new container apps environment should be created.

**Actual behavior** [What actually happened.]
Unable to create container apps environment as the service shows an error its already mapped with another environment. But here the previously mapped environment is already deleted. So, it should release the subnet but not happening.
**Screenshots**         

### Additional context
We already raised a support request to Microsoft and support engineer confirmed that this is a bug in product which was accepted by product team. So, please accept this issue for our tracking when it closes.
Support request number:- TrackingID#2310170050004372

**Comment by chinadragon0515** [comment]
Per offline discussion, there is delete lock for the vNet, it causes the linked created in the subnet cannot be deleted.
We need the lock be removed before deleting the env, then all resources will be auto cleaned. And the lock can be added back after deletion.
