### ISSUE TITLE
Container/app crashing after downloading larget data sets

### ISSUE THREAD

**Issue by dss010101** [microsoft/azure-container-apps#981]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have a Container App running with a mounted 200GiB mounted file share (StorageV2, LRS).
Number of CPU cores: 0.25 and Memory size (Gi): 0.5Gi
The file storage shows a quota of 200Gib, and a maximum capacity of 5 TiB, currently only about 30mb used.

The app downloads large data sets on request as a gz file than uncompresses and reads the file.  The files uncompressed is about 230-250MB. When i run this process locally, it works fine.

When this process is run on the container hosted in my  azure Container App env, it downloads the data as a gz file, but then the process appears to crash when it tries to read the file.

The trigger for the downloading of the data is a simple flask app.  But on the portal, after the file is downloaded, i see the following in console:

```./start.sh: line 9:     8 Killed                  flask --app /apps/data_svc/web/app.py run --host=0.0.0.0```

I cannot find anything in the app logs or in the logs or metrics on azure portal that is giving me a hint as to cause.

Any suggestions on how to go about debugging this issue?  Does the memory size above above for my container app seem reasonable for this process?

Thanks for any help or hints in resolving this issue.

**Comment by ahmelsayed** [comment]
are you buffering the content in memory anywhere during download or decompressing? You can check system events if the kill was due to memory (it would have an OOMKilled event if that was the case). That would be my first guess at least.

You could also rule that out by trying to increase your memory request on the app and see if that works.

**Comment by dss010101** [comment]
> are you buffering the content in memory anywhere during download or decompressing? You can check system events if the kill was due to memory (it would have an OOMKilled event if that was the case). That would be my first guess at least.
> 
> You could also rule that out by trying to increase your memory request on the app and see if that works.

Scaling the container app to .5/1 failed.  Scaling to 1/2 worked.  So it does seem to be memory.

Related.  Where would this OOMkilled event be logged or how would I query for this?  The metrics I looked at did not really show anything alarming.  The diagnostic tab showed the failure, but just a generic message to look at logs ..nothing really helpful

**Comment by dss010101** [comment]
Most of the usage of this app is fine at .25/.5.
It's only the download and processing, which happens once a day, that is problematic.

My thought then was that maybe I could dynamically spin up a second container app based on the first, but scaled up, trigger the download and processing activity, then scale it to 0 replicas....all the while the first container app remains active to serve requests.

Is that feasible?  What would be the best way to go about doing this?

**Comment by jurepurgar** [comment]
Jobs would probably be the best solution if you have control over the app: https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli

**Comment by dss010101** [comment]
> Jobs would probably be the best solution if you have control over the app: https://learn.microsoft.com/en-us/azure/container-apps/jobs

ah interesting. i did not know about this.  it seems though from the docs that you either use that or container apps.  will give it a try

**Comment by jurepurgar** [comment]
It is just a "special" kind of container app. It can be started on a schedule and it is stopped when container is done its work. It is not always running like ordinary container app. Everything else is more or less the same.

**Comment by jurepurgar** [comment]
It is available in ARM, not sure if it is also available in the portal or CLI

**Comment by dss010101** [comment]
> It is available in ARM, not sure if it is also available in the portal or CLI

i dont see an options using the CLI:  https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest#az-containerapp-job-create

im assuming if its available in arm, then perhaps it may be supported via terraform + azurerm or azapi.  i hope...

**Comment by anthonychu** [comment]
@dss010101 It's available in ARM/Bicep and TF AzAPI: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/jobs?pivots=deployment-language-arm-template

In CLI, volumes are currently supported via YAML when you use az containerapp job create/update.

In portal, currently, you can't configure a volume when creating a job. However, it's available when you edit the job container: 
![image](https://github.com/microsoft/azure-container-apps/assets/3982077/a246975b-6fe8-45dd-9e7f-7753c9e548a7)
