### ISSUE TITLE
Environment stuck at Waiting state

### ISSUE THREAD

**Issue by rhuanbarreto** [microsoft/azure-container-apps#982]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm trying to deploy a vNET-intergated container apps environment from the azure portal and the deployment is running already for more than an hour time without success.

Correlation ID: ad9409c5-8614-4ba7-9e89-f6d32de3f964
Deployment ID: Microsoft.App-ContainerApp-Portal-20d0b3fa-abb3

**Comment by howang-ms** [comment]
Hi @rhuanbarreto
The error seems related to your VNet configuration, and I found your latest creation seems fine. 
Please let us know if you are still seeing any issues.

**Comment by rhuanbarreto** [comment]
I managed to get this info through a support ticket. Thanks.

Now a request:

Could the deployment model fail in a way that this would be more meaningful? The root cause was that the DNS server was not forwarding the unknown names to the Azure DNS. But having the deployment stuck with a 2-hours timeout really bloats CI/CD usage. Maybe a validation of name resolution and failure in case addresses cannot be found in some seconds would make the issue easier to solve without wasting resources like it happened.

**Comment by chinadragon0515** [comment]
@rhuanbarreto we found there was some new error from backend service which are not handled by us and cause the stuck. We have improved the code to handle this issue, you should not see stuck in 2 hours for this issue any more.
