### ISSUE TITLE
Feature Request: Support for TLS 1.3

### ISSUE THREAD

**Issue by CrazyTuna** [microsoft/azure-container-apps#985]
**Is your feature request related to a problem? Please describe**.  
Azure container App only support TLS 1.2 for HTTP ingress. 

**Describe the solution you'd like**.    
Is there an ETA / plan that you could share for TLS 1.3 support ?

**Comment by ahmelsayed** [comment]
This should be deployed everywhere now.

**Comment by CrazyTuna** [comment]
Thanks for you answer, so should this documentation be updated as well?

[Ingress in Azure Container Apps](https://learn.microsoft.com/en-us/azure/container-apps/ingress-overview#http)
>HTTPS endpoints that always use TLS 1.2, terminated at the ingress point

**Comment by ahmelsayed** [comment]
I updated the docs too.

**Comment by CrazyTuna** [comment]
Awesome Thanks
