### ISSUE TITLE
Container app job stops execution after 30 minutes

### ISSUE THREAD

**Issue by vbakshi123** [microsoft/azure-container-apps#986]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Container app job fails after executing for 30 minutes. Error message in the ContainerAppSystemLogs_CL table shows "Job was active longer than specified deadline". Reason being "DeadlineExceeded"

### Steps to reproduce
1. Run any job that takes more than 30 minutes to execute and the error message pops up in log analytics. Job status shows failed

**Expected behavior** - Job should continue executing till it finishes

**Actual behavior** -  Job fails after 30 minutes

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/20863238/764581a3-cd12-447d-8b88-5cd38e57c05e)

### Additional context
In the portal, it shows the error message

**Comment by christiansparre** [comment]
@vbakshi123 are you possibly running into the "Replica timeout" where the description is "The maximum time in seconds to wait for a replica to complete." - the default is 1800 seconds which is 30 minutes? 

https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#job-settings

**Comment by vbakshi123** [comment]
> @vbakshi123 are you possibly running into the "Replica timeout" where the description is "The maximum time in seconds to wait for a replica to complete." - the default is 1800 seconds which is 30 minutes?
> 
> https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#job-settings

You are absolutely right Chris. Believe it or not, I did go through the configuration settings but probably not with a fine tooth comb. Sorry guys. Thank you one more time

**Comment by vbakshi123** [comment]
Sorry for re-opening the issue. There is another issue that has come up. I increase the replica timeout value to 18000 seconds. The jobs exists successfully after 108 minutes with the system log showing "Container 'XXXXXXX-job' was terminated with exit code '0' and reason 'ProcessExited'". The job basically reads from a file stream and inserts into a Azure MySQl Database. Even though it has around 500,000 records pending to insert into the database, it runs for 108 minutes and then terminates graciously on its own.  When I run the same .NET core code on a Windows machine it does it successfully, all records get inserted

**Comment by duglin** [comment]
It sounds like you want this to run forever, have you considered using a normal ACA app instead and setting the min-replicas to 1? If you don't turn on any ingress it should basically be the same thing as a job.

**Comment by vbakshi123** [comment]
> It sounds like you want this to run forever, have you considered using a normal ACA app instead and setting the min-replicas to 1? If you don't turn on any ingress it should basically be the same thing as a job.

Wouldn't say forever, but it would ideally take close to 10 hours for the job to complete as it is writing more than a million records to a database. Don't think ACA app is the right choice as the invocation is via http and I need ingress enabled, since it's private.

**Comment by duglin** [comment]
true, if you want it to stop after a certain amount of time then perhaps apps might not be best, unless you want to dynamically set the min-replica count - which is possible.

re: http - it's not clear to me if you want http or not... I was assuming not. If so, just disable ingress and you should be all set. I've had an aca app running for over 5 hours now w/o any ingress or http server running.

**Comment by vbakshi123** [comment]
> true, if you want it to stop after a certain amount of time then perhaps apps might not be best, unless you want to dynamically set the min-replica count - which is possible.
> 
> re: http - it's not clear to me if you want http or not... I was assuming not. If so, just disable ingress and you should be all set. I've had an aca app running for over 5 hours now w/o any ingress or http server running.

Thank you Dug. Did you have the minimum replica set to 1, for the app to run for 5 hours without ingress enabled in ACA ?
I tried that before shifting to container jobs, and the container Running status will get stuck at "Running (at max)" after an hour or two. I had minimum replica 1 and maximum of 2. After an hour, it would spin up another replica, even though the program is picking up one record at a time and inserting it into a database. When the second replica spins up, it obviously starts from the beginning and tries to insert records that have already been inserted. The code on a Windows machine works fine and inserts one million rows in about 9 hours.

I am going to try with a higher configuration container, 4 cpu and 8 GB memory and see if it makes a difference and it doesn't spin up another container

**Comment by vbakshi123** [comment]
> > true, if you want it to stop after a certain amount of time then perhaps apps might not be best, unless you want to dynamically set the min-replica count - which is possible.
> > re: http - it's not clear to me if you want http or not... I was assuming not. If so, just disable ingress and you should be all set. I've had an aca app running for over 5 hours now w/o any ingress or http server running.
> 
> Thank you Dug. Did you have the minimum replica set to 1, for the app to run for 5 hours without ingress enabled in ACA ? I tried that before shifting to container jobs, and the container Running status will show "Running (at max)" after an hour or two. I had minimum replica 1 and maximum of 2. After an hour, it would spin up another replica, even though the program is picking up one record at a time and inserting it into a database. When the second replica spins up, it obviously starts from the beginning and tries to insert records that have already been inserted. Console messages shows container exited with code 0. The code on a Windows machine works fine and inserts one million rows in about 9 hours.
> 
> I am going to try with a higher configuration container, 4 cpu and 8 GB memory and see if it makes a difference and it doesn't spin up another container

Just wanted to update, that even after upgrading to a higher computer, the results are the same. The container app would just randomly exit with code 0 and restart on its own. Sometimes, it would exit after 2 hour, sometimes it would exist after 5 hours. Even though the minimum replica had been set to 1 and maximum of 4. Unfortunately, azure container apps looks to be very flaky with long running background  jobs that go over 2 hours,

**Comment by vinisoto** [comment]
Hi @vbakshi123 can you share the details for this instance so we can investigate more?

> here is another issue that has come up. I increase the replica timeout value to 18000 seconds. The jobs exists successfully after 108 minutes with the system log showing "Container 'XXXXXXX-job' was terminated with exit code '0' and reason 'ProcessExited'"

please share your subscription Id and Job Name to acasupport [at] microsoft [dot] com

**Comment by vbakshi123** [comment]
> Hi @vbakshi123 can you share the details for this instance so we can investigate more?
> 
> > here is another issue that has come up. I increase the replica timeout value to 18000 seconds. The jobs exists successfully after 108 minutes with the system log showing "Container 'XXXXXXX-job' was terminated with exit code '0' and reason 'ProcessExited'"
> 
> please share your subscription Id and Job Name to acasupport [at] microsoft [dot] com

Have sent the details to acasupport [at] microsoft [dot] com

**Comment by vinisoto** [comment]
Closing this issue as we are following up privately

**Comment by AlexMasson** [comment]
Hi @vbakshi123 , did you get your issue resolved? We are planning to use container jobs to run very long operations, but the problem you encountered makes us doubt the solution being used.

**Comment by vbakshi123** [comment]
> Hi @vbakshi123 , did you get your issue resolved? We are planning to use container jobs to run very long operations, but the problem you encountered makes us doubt the solution being used.

Hello Alex

Unfortunately, the job was still flaky. After MS made some changes to the container app environment, it did make a difference, but wasn't stable. It would run fine for a couple of days and then fail the next day. We had to move our jobs to a VM rather than any container app.

**Comment by AlexMasson** [comment]
@vinisoto thanks!
