### ISSUE TITLE
Container app stopped logging to Azure Monitor

### ISSUE THREAD

**Issue by maskati** [microsoft/azure-container-apps#988]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
An ACA environment in West Europe stopped logging to Azure Monitor log destinations on 11th November at 01:02 UTC. No logs are emitted to either ContainerAppSystemLogs or ContainerAppConsoleLogs. The last logs received were for container k8se-localproxy with Log detail logger of LocalProxyClient.

Until 01:01 UTC the following logs repeated:

```
Failed to receive from stream.
Getting latest ServiceRedirectInfos.
Initialized
Start listening services redirect info updates
```

After which the following logs repeated about 500 times:

```
Failed to receive from stream.
Getting latest ServiceRedirectInfos.
Failed to call GetServiceRedirectInfos
Getting latest ServiceRedirectInfos.
Failed to call GetServiceRedirectInfos
Getting latest ServiceRedirectInfos.
Failed to call GetServiceRedirectInfos
```

Following which all logging stopped. There have not been any logs for several days.

**Comment by howang-ms** [comment]
Hi @maskati 
Is the issue still happening? If so, can you please send an email with your subscription id and environment name to acasupport at microsoft dot com and we will investigate ASAP.

**Comment by chinadragon0515** [comment]
It was a bug and fix already deployed, close the issue

**Comment by blackalegator** [comment]
Getting the same bug with container app job

**Comment by KryptoKnight** [comment]
I can confirm that we are also getting this issue...

{"level":"error","ts":"2023-12-05T11:06:36.712622994Z","logger":"LocalProxyClient","msg":"Failed to call GetServiceRedirectInfos","error":"rpc error: code = Canceled desc = context canceled","stacktrace":"main.run\n\t/__w/k4apps/k4apps/cmd/proxy/main.go:139\nmain.main\n\t/__w/k4apps/k4apps/cmd/proxy/main.go:103\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
