### ISSUE TITLE
Dapr invocations suddenly stopped working

### ISSUE THREAD

**Issue by WolfspiritM** [microsoft/azure-container-apps#989]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Not sure if a dapr or azure container apps issue:
Service invocations via dapr suddenly stopped working for us. It worked again after restarting the revision. Maybe it has something to do with the revision running for a longer time.

The daprd log says:

time="2023-11-14T09:05:16.259528052Z" level=error msg="error starting server: error from authenticator CreateSignedWorkloadCert: error from sentry SignCertificate: rpc error: code = Unknown desc = error validating requester identity: csr validation failed: invalid token: [invalid bearer token, service account token has expired, the server has asked for the client to provide credentials]" app_id=portal instance=portal--f3vmz9v-6547ff5885-55cr8 scope=dapr.runtime.grpc.internal type=log ver=1.11.5-msft.1

### Steps to reproduce
1. Probably having a container/revision running for a longer time
2. Trying to invoke a service

**Expected behavior** [What you expected to happen.]
Service account token gets renewed and certificates can be updated

**Actual behavior** [What actually happened.]
Service Invocations stop working resulting in a:
fail to invoke, id: service, err: failed to invoke target messages after 3 retries. Error: rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

### Additional context
Dapr service to service invokations

**Comment by henrikthorin** [comment]
We have experienced the same issue in two separate environments. In the first environment starting on Sunday the 12th, the issue was resolved automatically after 24 hours. In the other, issues started to happen today and we resolved it by restarting the revision. 

The two affected environments were luckily only test environments. For now our production environment has not yet been affected by this issue.

**Comment by simonm43** [comment]
Hi team,
we were experiencing the same issue. We are also using Azure Container Apps and got the below errors:
2023-11-14T06:07:19.01924293Z renewing certificate: requesting new cert and restarting gRPC server
2023-11-14T06:07:19.019299815Z sending workload csr request to sentry
2023-11-14T06:07:19.037466873Z error starting server: error from authenticator CreateSignedWorkloadCert: error from sentry SignCertificate: rpc error: code = Unknown desc = error validating requester identity: csr validation failed: invalid token: [invalid bearer token, service account token has expired, the server has asked for the client to provide credentials

It is retrying the steps above but always ends up in the error. Even after restarting the revision, this problem still appeared.

We were able to solve it with a redeployment. But we had the same issue for another container and redeployment did not solve the issue.

Regards

**Comment by greenie-msft** [comment]
Hi everyone,

Thank you for bringing this behavior to our attention.

We are actively investigating the root cause. I will respond to the thread as soon as I have an update to share.

**Comment by albigi** [comment]
Thanks @greenie-msft - I was trying to correlate a few logs from our log analytics and it's hard to find a precise pattern on when this started and why, so please take the below with a huge grain of salt....

- I noticed the issue for one specific app started to show up at 3am on nov 12
- the only daprd image showing this error is `mcr.microsoft.com/daprio/daprd:1.11.5-msft.1-mariner`
- prior to that date, the same container image was rolled out around 9am on nov 11
- before that the daprd image being run was 
`mcr.microsoft.com/daprio/daprd:1.11.2-msft-3-mariner`

Also, I was checking at the code which is surfacing the above mentioned error and my understanding is it's coming directly from k8s TokenReview API, but unfortunately I am not aware of a way to instrument some more aggressive logging to exactly know what's getting in/out from that endpoint, which is called [here](https://github.com/dapr/dapr/blob/3bb14c4fd66dd5f237b88cec53697d35ed136206/pkg/sentry/server/validator/kubernetes/kubernetes.go#L273)

hope this helps.
we'll continue some investigation from our end and share any meaningful outcome, although I'm afraid we won't be able to progress much. however, we're happy to help in any way we can to get a better understanding on what's causing this

**Comment by torosent** [comment]
Hi All, This issue was not related to Dapr and should be mitigated by now. You should also have received communication about it.  If this is still happening, please send an email with your subscription id and environment name to acasupport at microsoft dot com and we will investigate ASAP.
