### ISSUE TITLE
Container Apps Environment creation fails with InvalidRequestParameterWithDetails

### ISSUE THREAD

**Issue by andreaskasc** [microsoft/azure-container-apps#990]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a:
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When trying to deploy a new Container Apps Environment through [bicep](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/managedenvironments?pivots=deployment-language-bicep#resource-format), without specifying **_properties.appLogsConfiguration.logAnalyticsConfiguration.sharedKey_** we get an **InvalidRequestParameterWithDetails** error with message _"**LogAnalyticsConfiguration is invalid.  Must provide a valid LogAnalyticsConfiguration**"_.
I have seen already this issue https://github.com/microsoft/azure-container-apps/issues/314 which suggests that sharedkey is mandatory and indeed when adding this key the deployment runs successfully. (That is why I set the category as _documentation issue or request_ and not _bug report_.)

However, what is interesting and I would like some clarifications about, is that using the exact same bicep file without the shared key in already existing container apps environments doesn't cause any issue. Moreover, when I go to the portal or use az cli the shared key is shown as null. How is that so? Is it hidden because it is considered a secret? 
In general, is the shared key cached during the creation of the container app environment and then reused? 

**Screenshots**         
Screenshot of a live system with shared key shown as null.
![image](https://github.com/microsoft/azure-container-apps/assets/127096200/73eb9844-c238-41cc-a2fa-9758bcb95c41)

**Comment by howang-ms** [comment]
Thank you for reporting this.

> However, what is interesting and I would like some clarifications about, is that using the exact same bicep file without the shared key in already existing container apps environments doesn't cause any issue.

This is unexpected, and a bug on our side, we will fix it ASAP. Please don't rely on today's behavior. Sorry for the convenient.
If the SharedKey is not given for PUT request, it is expected to get a validation error. If the ShareKey is not given for the PATCH request, it will be preserved as the original value. 

> Moreover, when I go to the portal or use az cli the shared key is shown as null. How is that so? Is it hidden because it is considered a secret?

Your understanding is correct.

**Comment by jason-berk-k1x** [comment]
I don't think this actually got fixed.  I have an existing ACA env created like so:

```
resource "azurerm_container_app_environment" "container_app_env" {
    name                                         = "${var.prefix}-cae-${var.sub}"
    location                                     = var.location
    resource_group_name            = azurerm_resource_group.cae.name
    log_analytics_workspace_id   = azurerm_log_analytics_workspace.cae_logs.id
}
```

and now I want to use the AzAPI provider to add a `Custom DNS Suffix`.

the first step is to use a data source and get the domain verification and add the A and TXT records to my DNS....which I have done.

the next step would be to update the Container App Environment (CAE):

```
resource "azapi_update_resource" "cae_custom_dns_suffix" {
  type = "Microsoft.App/managedEnvironments@2023-05-02-preview" # pulled from the json view of my resource in the portal
  resource_id = azurerm_container_app_environment.container_app_env.id

  body = jsonencode({
    properties = {
      customDomainConfiguration = {
        dnsSuffix = "sub.domain.io"
        certificatePassword = "blah blah blah"
        certificateValue = filebase64("./my-ssl-cert.pfx")
      }
    }
  })
}
```

which fails with 

> │ Error: creating/updating "Resource: (ResourceId \"/subscriptions/my-sub/resourceGroups/rg-dev/providers/Microsoft.App/managedEnvironments/aca-env-dev\" / Api Version \"2023-05-02-preview\")": PUT https://management.azure.com/subscriptions/my-sub/resourceGroups/rg-dev/providers/Microsoft.App/managedEnvironments/aca-env-dev
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: InvalidRequestParameterWithDetails
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "InvalidRequestParameterWithDetails",
│     "message": "LogAnalyticsConfiguration is invalid.  Must provide a valid LogAnalyticsConfiguration"
│   }
│ }
│ --------------------------------------------------------------------------------
