### ISSUE TITLE
Issues running multiple containers in job (execution never ends (times out), spawns additional replicas)

### ISSUE THREAD

**Issue by christiansparre** [microsoft/azure-container-apps#996]
### This issue is a:
- [x] documentation issue or request

### Issue description
I'm trying to figure out how to run Azure DevOps agents in ACA and have followed the tutorial at https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=powershell&pivots=container-apps-jobs-self-hosted-ci-cd-azure-pipelines

However I have a hard time understanding what is actually going on as the behavior is not what I expected.

The job is defined with two containers, the Azure DevOps agent container and a SQL Server container.

The Azure DevOps agent is configured using the `--once` options so exits after the pipeline has run. This works great when there is only the agent container and not a SQL Server container.

When I have the SQL Server container as well then the job execution never ends and eventually times out and registers as failed. This makes sort of sense iguess because the SQL Server container is still running.

To get around this at the end of the pipeline I tried issuing a `SHUTDOWN WITH NOWAIT;` SQL command to the SQL server causing the SQL server to shutdown and the container to exit.

However this seems to cause the job execution to start a whole new replica! The job execution will then eventually time out and register as failed as before.

These are the system logs for a job exection with an extra replica created:

```
11:43:30.030    Successfully created pod for Job Execution 'en-*****-ci-agents-job4-7pvhb'
11:43:30.030    Replica 'en-*****-ci-agents-job4-7pvhb-7gnpw' for Job Execution 'en-*****-ci-agents-job4-7pvhb' has been scheduled to run on a node.
11:43:33.200    Pulling image ""*****ciacr.azurecr.io/azp-agent:linux""
11:43:34.304    Successfully pulled image ""*****ciacr.azurecr.io/azp-agent:linux"" in 234.105059ms (234.11096ms including waiting)
11:43:34.304    Created container sql-server
11:43:34.304    Created container agent
11:43:34.304    Started container agent
11:43:34.304    Pulling image ""mcr.microsoft.com/mssql/server:2022-latest""
11:43:34.304    Successfully pulled image ""mcr.microsoft.com/mssql/server:2022-latest"" in 46.140146ms (46.150466ms including waiting)
11:43:34.304    Started container sql-server
11:48:10.062    Successfully created pod for Job Execution 'en-*****-ci-agents-job4-7pvhb'
11:48:10.062    Replica 'en-*****-ci-agents-job4-7pvhb-4gh4c' for Job Execution 'en-*****-ci-agents-job4-7pvhb' has been scheduled to run on a node.
11:48:13.064    Pulling image ""*****ciacr.azurecr.io/azp-agent:linux""
11:48:17.080    Successfully pulled image ""mcr.microsoft.com/mssql/server:2022-latest"" in 89.476741ms (89.485568ms including waiting)
11:48:17.080    Created container agent
11:48:17.080    Started container sql-server
11:48:17.080    Successfully pulled image ""*****ciacr.azurecr.io/azp-agent:linux"" in 4.491701809s (4.491710004s including waiting)
11:48:17.080    Started container agent
11:48:17.080    Created container sql-server
11:48:17.080    Pulling image ""mcr.microsoft.com/mssql/server:2022-latest""
11:53:30.296    Deleted pod: en-*****-ci-agents-job4-7pvhb-4gh4c
11:53:30.296    Stopping container sql-server
11:53:30.296    Stopping container agent
11:53:30.296    Job was active longer than specified deadline
```

As I understand it multiple containers in a job should be possible. The portal states "In advanced scenarios, jobs can use additional containers." and there are several issues that states that it is possible ex. https://github.com/microsoft/azure-container-apps/issues/915#issuecomment-1740156271

I'm just wondering how I should go about configuring it. We need to run some dependencies, ex. SQL Server alongside our agent container.

Hope someone can shed a bit of light on it :)

**Comment by anthonychu** [comment]
@christiansparre This may be due to the sql container exiting with a non-zero status code and causing a restart.

Testing this out locally with Docker using `mcr.microsoft.com/mssql/server:2017-latest`, it appears the sql container exits with status code `1` when it's shutdown using `SHUTDOWN WITH NOWAIT;`.

You can try modifying the startup command of the sql container to `bash -c '/opt/mssql/bin/sqlserver || true'`, which should always exit with code 0.

**Comment by christiansparre** [comment]
@anthonychu that was exactly it! Thank you!

I could not seem to make it work using the "Command override" on the container settings. Kept getting errors like: `docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.`

I ended up creating a "custom" image with the following, "overriding" the CMD part and this seems to work for our needs.

```dockerfile
FROM mcr.microsoft.com/mssql/server:2022-latest

CMD [ "/bin/bash", "-c", "/opt/mssql/bin/sqlservr || true" ]
```

Now the jobs complete successfully 🎉
